core/arch/aarchxx/aarchxx.asm, core/arch/x86/x86.asm, core/dynamo.c, core/os_shared.h, core/unix/loader.c, core/unix/os.c
The stack pointer is passed as a third argument to relocate_dynamorio
and on Linux this is used to search the auxiliary vector for AT_PAGESZ.
Similarly, there are calls to os_page_size_init in dynamorio_app_init
and standalone_init to do the same thing. On MacOS, and on Linux if
for some reason os_page_size is called before these initialisations,
the page size is discovered using the system calls mmap and munmap,
which should work on any POSIX system.
A later commit should get Mac OSX to use sysctl_query on hw.pagesize.
Review-URL: https://codereview.appspot.com/313800043
=> i#1680 large pages: Add code to discover page size on Unix.

api/docs/release.dox, ext/drx/drx.c, ext/drx/drx.h, suite/tests/client-interface/drx-test.dll.c
Adds a drx_tail_pad_block() method which constructs a zero-cost label at
the end of any basic block which is not already branch-terminated. This
facilitates the ability to add instrumentation after the current
instruction even if the basic block is not branch-terminated.
=> i#1834 memval Part 1: drx_tail_pad_block

api/docs/release.dox, core/arch/arm/instr_create.h, core/arch/x86/instr_create.h, suite/tests/api/ir_x86.c
Adds XINST_CREATE_load_1byte_zextend() method which on x86 performs a
movzx so that we can effectively perform single byte loads even if given
a register which cannot be resized appropriately. On ARM this emits a
traditional ldrb instruction.
=> i#1834 memval Part 2: XINST_CREATE_load_1byte_zextend

.appveyor.yml, make/FindGhostscript.cmake, suite/runsuite.cmake, suite/runsuite_wrapper.pl
Adds 32-bit VS2010 and full VS2013 AppVeyor setup, both with ninja, which
we install beforehand.  Sends notifications to the devs list.
Fixes several issues blocking AppVeyor from running before:
+ Set the image to 2013 as there is no 2010 image.
+ Use an absolute path for cygpath to avoid picking up git's version.
+ Quote the CC env var to avoid AppVeyor's cmake from complaining.
Adds gswin64c to make/FindGhostscript.cmake.
Adds explicit failure on pre-commit diff content checks.
Qt5 is there but not yet pointed at.
Disables the docs for now as the ghostscript installed with chocolately
fails to be properly launched by fig2dev.
Most importantly, temporarily ignores test failures, keeping AppVeyor
green, until we've fixed the handful of base test failures in this
environment.
=> i#2145 AppVeyor: VS2010 + VS2013 build setup

core/arch/instrlist.c, suite/tests/api/ir_x86_all_opc.h, suite/tests/client-interface/inline.dll.c
If a client mistakenly calls instrlist_encode_to_copy() on an instrlist
that has indication of meta control flow (i.e. labels) but has not set
has_instr_jmp_targets, we warn the client that setting this flag may be
necessary to correctly encode the basic block.
Fixes #2158
=> i#2158: Warn client on incorrect usage of instrlist_encode_to_copy

clients/drcachesim/tracer/tracer.cpp
If the drmemtrace file ops are replaced, it's up the replacer to notify the
user where the trace data is going.  In some cases data is sent over the
network and the replaced create_dir is a nop that returns true, in which
case we don't want the existing message stating where the local log
directory is, as there is no such directory.
=> i#2006 generalize drcachesim: omit log msg when file ops replaced

.appveyor.yml, .travis.yml
Avoids double-CI-runs on pushes to non-master followed immediately by pull
requests.
=> Don't run CI on pushes to non-master

core/unix/memquery_linux.c
Adds bailout of maps file iteration if the file grows just enough to read
more yet not reach a newline when we've already iterated to the prior final
line.
Fixes #2172
=> i#2172: make maps file robust to corner case changes

clients/drcachesim/tests/burst_static.cpp, clients/drcachesim/tests/burst_threads.cpp, clients/drcachesim/tests/offline-burst_static.templatex, clients/drcachesim/tracer/tracer.cpp, core/arch/arch.c, core/config.c, core/dynamo.c, core/globals.h, core/heap.c, core/lib/dr_app.h, core/lib/instrument.c, core/moduledb.c, core/synch.c, core/unix/loader.c, core/unix/os.c, core/utils.c, core/utils.h, core/vmareas.c, core/win32/callback.c, core/win32/module.c, core/win32/ntdll.c, core/win32/os.c, ext/drreg/drreg.c, suite/tests/CMakeLists.txt, suite/tests/api/static_detach.c, suite/tests/api/static_detach.expect, suite/tests/runmulti.cmake
While there are many globals that are not reset, we take a best-effort
approach here and reset the ones that matter, allowing us to re-attach with
a memtrace client and static DR.
Portions of this were initially based on
https://codereview.appspot.com/13314047/ from Peter Goodman.
For DO_ONCE, an incremented counter is used.
For numerous other globals, at exit time if doing_detach is set we reset
them to NULL.
For locks, we simply reset count_times_acquired but leave the deleted field
as it does not matter much (part of the whole theme here: this may never be
rock-solid for unusual option combinations but our goal is supporting the
common case).
For drreg, with the new multi-init feature we have to zero the options at
exit time.
Adds several tests by adding loops around existing …
=> i#2157 re-attach: add best-effort re-attach support

suite/tests/CMakeLists.txt
client.flush is disabled in release build, but that disabling failed to
update the Mac test list, which we fix here.
=> i#1806: fix invalid ref to debug-only test on Mac

README.md, api/docs/samples.dox
74d1190 renamed inscount.c to inscount.cpp but failed to update a few
references, which we fix here.
=> i#2131 droption: fix stale inscount.c references

make/git/devsetup.sh
Renames the now-deprecated aliases to reflect this (later we'll remove
them).  Adds a new "git review" that pushes the local branch to the server.
=> Update git aliases for new workflow

core/arch/asm_defines.asm, suite/tests/common/nzcv.c
On ARM and AArch64 we use the macros SAVE_PRESERVED_REGS and
RESTORE_PRESERVED_REGS to save and restore REG_PRESERVED_1 and the link
register, LR. The function test_nzcv_pos no longer uses REG_PRESERVED_2,
so that macro is removed, for now.
Fixes #2173
=> i#2173: Fix failure to restore REG_PRESERVED_1 in test_nzcv_pos.

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, suite/tests/client-interface/thread.dll.c
Adds condition-variable-type event objects that threads can wait on and
signal to the API.  The implementation is just a wrapper around the
internal event_t interfaces.
Adds a test to the client.thread test by converting its prior hacky use of
bools and yielding to proper events.
Fixes #279
=> i#279: add event objects to the API

suite/tests/CMakeLists.txt
Making these tests pass on Android will require copying them to
the device. That may be all that is required.
=> i#2130 Android: Disable samples on Android.

.appveyor.yml
Unfortunately there's no way to disable emails on pull requests, like
Travis does, so we try to cut down on the noise by disabling status-change
emails.
=> i#2145 appveyor: reduce notification emails

.travis.yml, suite/runsuite.cmake, suite/runsuite_common_pre.cmake, suite/runsuite_wrapper.pl, suite/tests/CMakeLists.txt, tools/drdeploy.c
Splits 32-bit and 64-bit into separate matrix entries, for parallel runs to
shorten the total time and for shorter logs for easier failure diagnosis.
=> i#1962 travis: split 32-bit and 64-bit

clients/drcachesim/tests/drcachesim-TLB-simple.templatex, suite/runsuite_wrapper.pl
Fixes tool.drcachesim.TLB-simple failues by allowing double-digit miss
rates.
Ignores failures in common.floatpc_xl8all, client.nudge_ex, and
security-common.retnonexisting until we can repro and try to fix on Win8.1.
=> i#2145 appveyor: fix and ignore more tests

suite/tests/client-interface/drx_buf-test-shared.h, suite/tests/client-interface/drx_buf-test.c, suite/tests/client-interface/drx_buf-test.dll.c
Commit 4f4a5ac broke AArch64. It is easier to use a register that
does not need to be preserved than to save and restore registers.
=> i#1834 Misc fixes: Use r12 instead of r4 as TEST_REG on ARM.

suite/tests/CMakeLists.txt
f4285ea8 introduced new single-build cross-arch tests but hardcoded them
for debug build.
=> i#1962 travis: fix new cross-arch tests in release

core/os_shared.h, core/vmareas.c, core/win32/callback.c, core/win32/os.c, core/win32/os_exports.h, suite/tests/CMakeLists.txt, suite/tests/security-win32/except-guard.c, suite/tests/security-win32/except-guard.expect
We check the memory protection for the page about to be executed
If there is the guard flag, we forge a guard exception.
Fixes i#2135
=> i#2135: fix crash in check_thread_vm_area for guard pages

suite/runsuite_wrapper.pl
Splits the accidental double-exclusion of nudge_ex for 64-bit to the
intendend exclusion on 32-bit and 64-bit.
=> i#2145 appveyor: exclude 32-bit nudge_ex

suite/runsuite_wrapper.pl
Ensures failure on earlier errors by requiring a RESULTS line.
=> i#2145 appveyor: require RESULTS

suite/tests/client-interface/drreg-test-shared.h
There was the same problem in drreg-test as was fixed in
drx_buf-test by c169d8c: a callee-saved register was corrupted
by an assembler function called from C.
=> In drreg-test, use r12 instead of r4 as TEST_REG on ARM.

api/docs/release.dox, clients/drcachesim/tracer/raw2trace.cpp, clients/drcov/postprocess/drcov2lcov.cpp, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/drmodtrack-test.dll.cpp, suite/tests/client-interface/drmodtrack-test.expect
Adds a set of callbacks for customizing drmodtrack's per-module information
with custom fields during online processing.  Adds callbacks for retrieving
the custom information during offline processing.
Adds support for modifying the path of each module during offline
processing, and support for re-writing the module data out afterward.
Adds a new test for drmodtrack.
=> i#2006 generalize drcachesim: add custom field support to drmodtrack

api/docs/release.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tests/offline-burst_replace.templatex, clients/drcachesim/tracer/drmemtrace.h, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, clients/drcachesim/tracer/tracer.cpp
Adds a set of callbacks for customizing the module list created during
tracing, leveraging drcovlib's customization.
Exports the module log name and the path for customization, in conjunction
with recent drmodtrack features.
Adds a test to burst_replace.
=> i#2006 generalize drcachesim: add custom module processing

core/arch/aarchxx/mangle.c
Pending a proper fix and handling all these cases, at least detect
the cases that we cannot handle.
=> i#2210 clean call: Check no reg used by args conflicts with param reg.

api/docs/release.dox, clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcov/postprocess/drcov2lcov.cpp, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
Changes drmodtrack_offline_looup() to return a struct where the user sets
the size, to make it easier to add new fields in the future without
breaking compatibility.  Adds a containing_index field now to lay the
groundwork for handling module gaps, but it simply equals the index for
now.
=> i#2213 modgap: switch drmodtrack to a struct for easier expansion

clients/drcachesim/tests/burst_replace.cpp, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
Adds handling of gaps inside ELF libraries to drmodtrack.
Additional entries are added both to the online vector and the written
file.  The containing_index field added previously is used to point to the
main entry from sub-entries.
It's not easy to write a test without making a linker script, but on many
recent Linux distros there are gaps in some or even all system libraries,
including some of my machines, so we'll get at least some future regression
coverage.
Fixes #2213
=> i#2213 modgap: add module gap handling to drmodtrack

core/win32/loader.c
Adds a set of new pseudo-dlls seen running the unit_tests and
client.loader tests on Windows 10.
Fixes #1993
=> i#1993: add new win10 pseudo-dlls

core/arch/arch.c, suite/runsuite_wrapper.pl, suite/tests/CMakeLists.txt
Fixes several failing detach tests through two changes:
1) Copy dynamorio.dll into suite/tests/bin instead of suite/tests.
It's not clear how tests were working on other machines before!
2) Adjust an assert on re-attach rather than clearing syscall_method
on exit, as the latter causes a crash on detach on win8+.
=> i#2145 appveyor: fix failing detach tests on win8+

suite/tests/client-interface/drmgr-test.c, suite/tests/client-interface/drmgr-test.dll.c, suite/tests/client-interface/drmgr-test.templatex
Makes drmgr-test robust to extra threads, which are present on win10.
Fixes #2225
=> i#2225: fix drmgr-test on win10

core/win32/loader.c, suite/runsuite_wrapper.pl
On win10, a private combase.dll's entry fails, but ignoring it lets at
least simple clients continue with no visible problems, so we go with
that for now.
This fixes the client.loader test on recent Windows versions.
=> i#2221: ignore private combase.dll entry failure

api/samples/syscall.c, core/lib/instrument_api.h, core/unix/os.c, core/unix/signal.c, core/utils.c, core/utils.h, core/win32/inject.c, core/win32/ntdll.c, core/win32/os.c, core/win32/syscall.c, ext/drwrap/drwrap.c, ext/drx/drx_buf.c, suite/tests/client-interface/strace.dll.c
On win10, NtWriteVirtualMemory no longer returns the number of bytes
written and instead returns -1!  Thus, if the caller of safe_write_ex()
cares about that, we fall back to a try-except version rather than using
the system call.
Clarifies the dr_safe_read and dr_safe_write functions: that they fail if
the bytes read or written is partial.  Updates all callers who want to fail
on a partial read or write to pass NULL instead of taking time to check the
size read/written.
Fixes #2224
=> i#2224: handle win10's change in partial memory writes

core/win32/loader.c
Fixes a private loader crash that is triggered by using drsyms on win10,
where dbghelp explicitly loads an API-set dll and ends up with a NULL
dependent, which is not checked for in the loader.
Fixes #2232
=> i#2232: fix crash using drsyms on win10

suite/tests/security-win32/except-execution.templatex
On Win10, security-win32.except-execution prints
"ContextFlags=0x0001007f" instead of "ContextFlags=0x0001001f".  We
relax the output to allow this, as it already allowed ".f" for some
other OS versions.
=> win10 tests: relax except-execution output to pass on win10

core/dynamo.c, core/globals.h, core/lib/instrument.c, core/win32/loader.c, suite/runsuite_wrapper.pl, suite/tests/client-interface/thread.c, suite/tests/client-interface/thread.dll.c
Fixes an assert on client thread exit on win8.1 by adding a special
dcontext debug-only field for exiting client threads.
Fixes an assert inside the client.thread test itself by setting the TLS for
all threads, not just the main one.
Fixes #2237
=> i#2237: fix client.thread test on win8.1

core/arch/arch.c
76099ce fixed Windows detach asserts but caused vsyscall hook asserts on
re-attach on some Linux variants.  We re-instate the clearing of the
syscall method, for Linux-only.
=> i#2145 appveyor: fix vsyscall hook assert

core/unix/module_elf.c
Explicitly fails other-arch elf header checks to avoid hangs in standalone
mode.  We'd like to support other-arch for standalone and drsyms (i#1345,
i#1532) but we need to redo our hardcoded elf typedefs.
=> i#1345 mixed elf: fails other-arch elf for standalone too

clients/drcachesim/tracer/raw2trace.cpp
For modules with gaps, drraw2trace now simply has the later segments point
at the first mapping, which should itself include the gap and the other
segments.  With all PC arithmetic using the absolute module base, rather
than segment bases, it all works out.
=> i#2213 modgap: avoid double-mapping libs in drraw2trace

clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcov/postprocess/drcov2lcov.cpp, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
Adds a size-written OUT parameter to drmodtrack_offline_write() to avoid
callers needing an expensive strlen() to figure out how much to write from
the buffer to a file.
Includes the checksum and timestamp in the returned offline fields now, to
avoid having to check the struct size for compatibility when we inevitably
add them later.
=> i#2006 generalize drcachesim: improve custom field support

core/unix/os.c
On MacOS before Sierra, gettimeofday returns usecs:secs and does not
set the timeval struct. Sierra correctly fills the timeval struct.
=> i#1815: fix unit_test failure on macos sierra due to gettimeofday

api/docs/release.dox, ext/droption/droption.dox, ext/droption/droption.h, suite/tests/client-interface/option_parse.dll.cpp
Adds a set_value() option to droption_t to enable overriding the value set
on the command line.  Updates the documentation, including clarifying how
to negate a boolean option.  Adds a test case.
=> Add set_value to droption

clients/drcachesim/tests/offline-burst_replace.templatex, clients/drcachesim/tracer/tracer.cpp
Rather than issuing a separate write for each thread's initial header, we
merge it into its first buffer at the cost of a conditional in the buffer
dump routine.  This will help with strategies where writing smaller units
than a full buffer are costly.
=> i#1729 offline traces: merge thread init header into first buffer

clients/drcachesim/CMakeLists.txt, clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/tests/burst_replaceall.cpp, clients/drcachesim/tests/offline-burst_replaceall.templatex, clients/drcachesim/tracer/drmemtrace.h, clients/drcachesim/tracer/tracer.cpp, core/lib/instrument_api.h, suite/tests/CMakeLists.txt
Adds a new mode of operation where each full buffer is handed over to
external code.  A new buffer is allocated and the thread continues
instrumentation using the new buffer, with the external code responsible
for writing it out and freeing it.
This mode is enabled via a new API routine drmemtrace_buffer_handoff(),
which takes a buffer handoff routine, called instead of the write cb, and
an exit routine.  The exit routine provides a control point after other
threads are native but before DR exits, when using
dr_app_stop_and_cleanup().  Without it it would be impossible to use DR
memory in the handoff and we'd need a hack like putting next pointers inside the
redzones or something.
When the handoff is enabled, we disable dumping buffers at syscalls: they
are only dumped (i.e., handed over) …
=> i#2006 generalize drcachesim: add drmemtrace_buffer_handoff()

clients/drcachesim/tracer/instru_offline.cpp, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
Adds a size-written OUT parameter to drmodtrack_dump_buf() to avoid callers
needing an expensive strlen() to figure out how much to write from the
buffer to a file.  Updates the test and drcachesim to use the new parameter.
=> i#2006 generalize drcachesim: improve drmodtrack efficiency

core/arch/aarchxx/mangle.c, core/arch/mangle_shared.c, suite/tests/client-interface/cleancallparams.dll.c
The implementation should efficiently handle any (reasonable) number
of arguments that are immediate integers or full-size registers.
Test cases are added in cleancallparams.dll.c.
Fixes #2210
=> i#2210 clean call: Implement parameter preparation on ARM and AArch64.

core/dynamo.c, core/heap.c, core/win32/os.c, suite/runsuite_wrapper.pl
In mixed mode on win8.1+ we end up allocating the dstack up high (for
DrM-i#1723), which means it does not show up in the unfreed blocks at exit.
This raises an assert, which we relax here.
=> i#2145 appveyor: fix mixedmode test asserts

core/unix/os.c
The OSX kernel used to place the bare executable path above envp.
On recent XNU versions, the kernel now prefixes the executable path
with the string executable_path= so it can be parsed getenv style.
=> i#58: properly parse the executable path on recent OSX kernels

CMakeLists.txt, core/arch/x86/x86.asm, core/arch/x86/x86_shared.asm, core/unix/module_macho.c, core/unix/os.c, core/unix/os_public.h, core/unix/signal.c, core/unix/signal_macos.c, core/unix/signal_private.h, core/unix/tls_macos.c
This commit gets core DR building on MacOS 64-bit.
+ change error notifications to warning to allow build to continue
+ define SC_FIELD for 64-bit registers r8-r15 and update references
+ update dynamorio_mach_dep_syscall to use syscall for 64-bit
+ update dynamorio_mach_syscall to use syscall for 64-bit
+ change code referencing eflags to xflags for cross platform compat
+ misc code fix-ups
=> i#1979: steps towards building on MacOS 64-bit

core/optionsx.h, core/unix/memquery.h, core/unix/module_macho.c
+ Move -vm_base above 4GB since __PAGEZERO takes up first 4GB by default
+ Increase MEMQUERY_INTERNAL_DATA_LEN
+ Update Mach-O parsing to check for LC_SEGMENT_64
=> i#58: misc fixes for MacOS 64-bit support

clients/drcachesim/analyzer.cpp, clients/drcachesim/common/options.cpp, clients/drcachesim/launcher.cpp
Fixes bugs where the ! operator is used incorrectly when checking for
analyzer and tool instantiation success.
Adds missing simulator types to the usage messages.
=> i#2006 generalize drcachesim: fix errors in success checks

clients/drcachesim/CMakeLists.txt, clients/drcachesim/analysis_tool_interface.h, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/analyzer_multi.h, clients/drcachesim/common/options.cpp, clients/drcachesim/launcher.cpp, clients/drcachesim/simulator/analyzer_interface.cpp, clients/drcachesim/tests/histogram-offline.templatex, clients/drcachesim/tools/histogram_launcher.cpp, clients/drcachesim/tracer/raw2trace_launcher.cpp, core/lib/globals_shared.h, libutil/dr_frontend.h, suite/tests/CMakeLists.txt, suite/tests/runmulti.cmake
Splits the analyzer into a base that only reads from an offline (non-raw)
trace file, to support building offline analysis tools that do not need to
link with DR.  The tools to be used are passed in, simplifying tool
creation and lifetime management.
The derived analyzer, analyzer_multi_t, supports online, raw offline, and
transformed offline files.
For analyzer_multi_t, adds a separated interface for instantiating the tool
to be run, supporting linking in a separately built static library.
Adds a sample offline-only tool that runs the histogram analysis.
Adds a test of the new standalone tool.
=> i#2006 generalize drcachesim: split analyzer to support leaner tools

clients/drcachesim/CMakeLists.txt, clients/drcachesim/analysis_tool.h, clients/drcachesim/analyzer.h
Removes subdir references from the key headers needed for offline-only
tools to make it easier to install the headers for third-party tools.
=> i#2006 generalize drcachesim: facilitate tool header installation

CMakeLists.txt, clients/drcachesim/CMakeLists.txt, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/reader/compressed_file_reader.cpp, clients/drcachesim/reader/compressed_file_reader.h, suite/tests/CMakeLists.txt, suite/tests/runmulti.cmake
If zlib is found at build time (should be everywhere but Windows), we use
zlib's gzip file reading interface for reading trace files in the separated
analyzer_t as well as analyzer_multi_t for -infile (for -indir we do not
support compressed files, as there is no efficient way to check the end of
the file).  We do this regardless of whether the specified file is
compressed or not, as zlib outperforms fstream for uncompressed files.
Adds a test of the histogram tool generating, gzipping, and then reading
the gzipped file.
Updates the drcachesim documentation.
Fixes #2277
=> i#2277: add support for reading compressed trace files

core/arch/x86/decode.c, core/arch/x86/decode_private.h, core/arch/x86/decode_table.c, core/arch/x86/disassemble.c, core/arch/x86/encode.c, suite/tests/api/ir_x86.c
DR's decoder and encoder were incorrectly narrowing the x86 stack pointer
on push, pop, and related operations when the address size prefix was
present.  The udis86 test happened to not contain any such instructions.
We correct the bug here and add some tests.
Fixes #2281
=> i#2281: x86 stack pointer unaffected by addr prefix

core/unix/signal.c
When a signal interrupts trace building, we can already have re-linked the
interrupted fragment when we go to deliver the signal.  We avoid attempting
to double-re-link in that scenario here.
Fixes #2066
=> i#2066: fix already-linked assert on signal delivery

core/win32/syscall.c, suite/tests/CMakeLists.txt, suite/tests/security-win32/thread-setcontext.c, suite/tests/security-win32/thread-setcontext.expect
Handles the cases where parameter to syscall SYS_SetContextThread
is own thread id.
Fixes i#2249
=> i#2249: SetThreadContext on own thread.

core/unix/module_elf.c, ext/drsyms/drsyms_elf.c
Fixed the logic used to detect imports on ext/drsyms/drsyms_elf.c.
Now we use the same logic as in core/unix/module_elf.c symbol_is_import.
Fixes issue #2272
=> i#2272 drsyms uses the wrong criteria to distinguish imports on aarch64

libutil/dr_frontend.h, libutil/dr_frontend_common.c
Fix drfront_bufprint's fmt argument to avoid warnings when the
interface is called from C++ application.
Fixes #2275
=> i#2275 fix drfront_bufprint fmt argument

suite/tests/CMakeLists.txt
Switches from the incorrect "if (ZLIB)" to "if (ZLIB_FOUND)" for enabling
the tool.histogram.gzip test.
=> i#2277 zlib: fix error in enabling the zlib test

api/docs/bt.dox
Adds documentation on dr_remove_it_instrs() and dr_insert_it_instrs() and
how drmgr calls them for you, in the "Conditionally Executed Instructions"
section of the docs.
=> Document IT block instrumentation

clients/drcachesim/tests/histogram-offline.templatex, clients/drcachesim/tests/histogram.templatex, clients/drcachesim/tests/reuse_distance.templatex, clients/drcachesim/tools/histogram.cpp, clients/drcachesim/tools/reuse_distance.cpp, clients/drcachesim/tools/reuse_distance.h
Fixes several bugs in the existing reuse distance tool:
+ Crash on small datasets
+ Incorrect total ref count
+ Skipping branch instructions
Also normalizes output among non-simulator tools.
=> i#2300 reuse distance: fixes bugs in the existing tool

core/lib/instrument.c
GCC 7 objects to a memcpy in create_and_initialize_module_data().
(It seems that C99 requires the pointers dest and src to be valid in
memcpy(dest, src, n) even if n is zero.)
=> Avoid potentially derefencing a null pointer in a call to memcpy.

clients/drcachesim/tools/reuse_distance.cpp
Fixes a memory leak that was present in the original reuse distance code.
=> i#2300 reuse distance tool: fix memory leak

clients/drcachesim/simulator/caching_device_stats.cpp, clients/drcachesim/tests/histogram-offline.templatex, clients/drcachesim/tests/histogram.templatex, clients/drcachesim/tools/histogram.cpp
Fixes issues that appear when running multiple trace analysis tools on the
same trace: primarily that locale changes for printing must be local.
Tweaks the histogram tool's name to "Cache line histogram tool" to clearly
distinguish from a reuse distance histogram.
=> i#2006 generalize drcachesim: fix locale and other multi-tool issues

clients/drcachesim/tests/offline-burst_threads.templatex
Relaxes the tool.drcacheoff.burst_threads test output to allow more
variation in thread scheduling on cores as seen on CDash:
http://dynamorio.org/CDash/testDetails.php?test=227131&build=20497
=> Relax burst_threads golden output threads-per-core

core/arch/aarch64/codec.txt, core/arch/aarch64/decode_gen.h, core/arch/aarch64/encode_gen.h, suite/tests/api/dis-a64.txt
The BFM instruction (bitfield move) copies a number of bits from the
source to the destination register, leaving other bits unchanged [1].
This means the destination register must also be a source register,
otherwise DynamoRIO may not restore the original value of the
destination before a BFM instruction.
=> i#1569 AArch64: Make dst reg also a src reg for BFM.

core/dynamo.c, core/os_shared.h, core/synch.c, core/unix/os.c, core/unix/os_exports.h, core/unix/os_private.h, core/unix/signal.c, core/win32/os.c, suite/tests/api/static_signal.c, suite/tests/api/static_signal.expect
Sets the signal handler for the 3 alarm signals to SIG_IGN during attach
and detach, to reduce problems with races while we try to coordinate taking
over or sending native all of the app threads.
This is not a panacea, as timer_create can send out any signal, not just
the 3 classic alarm signals, on timer expiration.  Plus, non-timer-related
signals could arrive during attach or detach.  However, this will help with
the most typical cases.
Adds an itimer to the api.static_signal test, though it is not easy to
reproduce these problems in small applications.
I'm considering this to fix the filed issues despite the above-mentioned
remaining corner cases as I'm considering those to be pathological:
Fixes #2161
Fixes #2270
=> i#2161, i#2270: ignore alarms during attach and detach

core/arch/aarch64/codec.py, core/arch/aarch64/encode_gen.h
This patch fixes a coding style violation pointed out in #2309 in the
auto-generated encode_gen.h.
=> i#1569 AArch64: Move assignments out of expressions in encode_gen.h.

core/arch/aarch64/codec.c, core/arch/aarch64/codec.h, core/arch/aarch64/encode.c
As the parser for AArch64 is not complete yet dumping instructions that could
not be encoded makes it easier to diagnose encoding problems.
=> i#1569 AArch64: Print instruction if encoding fails.

suite/tests/api/static_signal.c, suite/tests/api/static_signal.expect
Relaxes the static_signal test to pass even if no alarms are seen, to avoid
flakiness.  To properly synch with an alarm I wanted to use a mask but the
i#2311 bug prevents that: once i#2311 is fixed we can improve the test and
ensure an alarm is seen.
=> i#2161 alarm races: relax flaky test

core/heap.c, core/heap.h, core/unix/os.c, core/unix/os_private.h, core/unix/signal.c, core/unix/signal_linux_aarch64.c, core/unix/signal_linux_arm.c, core/unix/signal_linux_x86.c, core/unix/signal_macos.c, core/unix/signal_private.h
Adds dynamic sizing of the xstate area in Linux signal frames to handle
forward-going processor extensions.
Sends a signal at init time to obtain the size of the xstate area.  If it
is larger than the known size, adds an OP_xsave operation when updating the
state of a delivered signal.  This is expensive, which is why we avoided it
before.  Using OP_xsaveopt is future work once we have FEATURE_XSAVEOPT
(part of i#1312).
Adjusts the pending signal heap allocations to be aligned properly for an
in-place OP_xsave.
Several stack-allocated xstate structures no longer easily fit on the stack
and are changed to two different kinds of heap buffers: one in TLS for uses
that cannot easily free it locally (thread_set_self_context() and
os_forge_exception()), and one on the regular heap …
=> i#1937: dynamically size signal frame xstate area

core/lib/instrument.c
Adds clearing of client callback lists in release build on detach, rather
than being debug-only.  This fixes static_detach test failures.
Fixes #2188
=> i#2188: fix callback reattach failure in release build

core/arch/aarch64/codec.c, core/arch/aarch64/codec.py, core/arch/aarch64/codec.txt, core/arch/aarch64/encode_gen.h, core/arch/aarch64/instr_create.h
Also adds support for instruction operands to ADR and ADRP encoders.
=> i#1569 AArch64: Add macro to create ADR and ADRP instructions.

core/dynamo.c, core/unix/os.c, core/unix/signal.c
Moves signal handler installation from init time to start-execution time.
This avoids a problem with split init-vs-start where we install our
handler, then remove it to go back native between init and start, and then
reinstate it.  We need to re-install our handlers every start in any case,
so by moving the init time installation to the same point, we simplify the
code.
We keep the init-time SIGSEGV and SIGBUS crash handlers active longer, to
cover crashes later in init, especially in client init.
Fixes #2335
=> i#2335: fix init-vs-start signal handler race

core/unix/os.c, core/unix/os_private.h, core/unix/signal.c
Adds swapping of each thread's signal mask on native<->DR transitions.
Shifts the initial setup of the mask to the same start execution point
where handler setup was moved by i#2335.
Changes the init-time crash handling to only change the mask for the crash
signals rather than everything.
Fixes #2337
=> i#2337: swap signal mask on native-DR transitions

suite/tests/api/startstop.c
As the per-thread functions in the api.startstop test are not generated, it
is a pain to increase the thread count beyond 10.  Here we add modulus to
make it easy to increase the thread count without sacrificing much of what
is being tested.  This is for local experiments to reproduce problems: I
don't know that we want to make the regression test too large.
=> Generalize api.startstop code for increasing thread count

core/arch/instr.h
The instr_is_cti() docs listed some x86 opcodes, implying it was not
cross-platform.  It also failed to list OP_ret.  We change it here to
generalize and make it cross-platform.  We also update the docs for a few
other related routines that are x86-specific.
=> Clarify instr_is_cti() docs and make them cross-platform

core/arch/x86/mangle.c, suite/tests/security-common/selfmod.c, suite/tests/security-common/selfmod.template
Fixes an off by one in the comparison to check if a basic block was modified.
Fixes i#2155
=> i#2155: managing with direction flag set in sandboxing check

api/samples/CMakeLists.txt
Currently, if DEBUG is set, OPT_CFLAGS gets set to -DDEBUG which
overrides the optimization options in OPT_CFLAGS. This patch
adds -DDEBUG to the existing OPT_CFLAGS, enabling optimization
of samples in case DEBUG is set.
=> Fix OPTIMIZE_SAMPLES in api/samples/CmakeLists.txt

ext/drreg/drreg.c, suite/tests/client-interface/drreg-test.dll.c
Changes drreg's aflags restore from the destructive "add 0x7f, al" to
"cmp 0x81, al" to avoid corrupting the aflags being stored in eax.
Adds a test of aflags reserve+restore before every instr.
Fixes #2351
=> i#2351: make aflags restore non-destructive

api/docs/release.dox, ext/drreg/drreg.c, ext/drreg/drreg.h, suite/tests/client-interface/drreg-test.dll.c
Adds a new API routine for restoring the app's aflags value on demand.
This is required for instrumentation that needs to spill the aflags but
test the app's value in the middle of tool code.
Adds tests to drreg-test.
=> i#511 drreg: add drreg_restore_app_aflags()

core/dispatch.c, core/lib/statsx.h, core/link.c, core/link.h, core/unix/signal.c
Currently Windows has the "asynch" special linkstub and UNIX has the
"sigreturn" special linkstub.  Both operate identically as far as dispatch
is concerned, and we've already overloaded the sigreturn linkstub for
forging exceptions.  We go ahead and merge the two into a single
cross-platform asynch linkstub.
=> Merge the sigreturn and asynch linkstubs

suite/tests/client-interface/drreg-test.dll.c
Disables the drreg aflags tests added in 7643545 and 0420d82 until aarch
core flags issues are fixed.
=> i#2263, i#2360: disable drreg aflags tests until aarch is fixed

core/arch/instr.h, ext/drreg/drreg.c, suite/tests/api/ir_arm.c, suite/tests/client-interface/drreg-test.dll.c
DR considers the Q and GE flags to be arithmetic for saving, restoring, and
in the EFLAGS_ARITH constant, yet not in the EFLAGS_{READ,WRITE}_ARITH
defines.  We correct that here by including them in all arithmetic
defines.
Re-enables the drreg test that was broken because of this.
Relaxes a drreg assert on re-spilling to the aflags slot with different
regs, which is exposed by this fix.  This relaxation mirrors what we
already do on restoring aflags.
Fixes #2360
=> i#2360: consistently label nzcvqg as arithmetic on ARM

api/samples/CMakeLists.txt, core/arch/aarch64/codec.c, core/arch/aarch64/codec.txt, core/arch/aarch64/decode_gen.h, core/arch/aarch64/encode_gen.h, core/arch/aarch64/instr_create.h, suite/tests/api/dis-a64.txt
The BL and BLR instruction store the return address in X30, This patch
adds X30 as (implicit) destination register for BL and BLR.
Thanks @zhaoqin for spotting the problem in #2332
=>  i#1569 AArch64: Add support for implicit X30 operands for BL and BLR. 

core/arch/aarchxx/mangle.c
This patch adds generic helper functions for 
insert_{push, pop}_all_registers, that can be used to push
all GPRs or SIMD registers to memory, taking reg_skip into
account.
The intention behind adding this function is to reduce code
duplication. It can also be used to save/restore GPRs for clean call
inlining and in core/arch/aarch64/emit_utils.c. I'll create separate
pull requests for those changes.
=> i#1621 AArch64: Add generic insert_push_or_pop_registers function.

core/arch/aarch64/clean_call_opt.c, core/arch/aarchxx/mangle.c, core/optionsx.h
This patch implements analyze_callee_regs_usage to analyze the usage of
GPRs in the callee. insert_push_all_registers and
insert_pop_all_registers do not save and restore unused registers.
cleanall_opt=1 has limited support now and is the default level for
AArch64.
Based on work by Kevin Zhou and Edmund Grimley-Evans.
=> i#1621 AArch64 cc opt: Use analyze_callee_regs_usage for GPRs.

core/dynamo.c, core/fragment.c, core/fragment.h, core/lib/instrument.c, core/synch.c, core/unix/tls_linux_x86.c, suite/tests/CMakeLists.txt, suite/tests/api/static_sideline.c, suite/tests/api/static_sideline.expect
Fixed several bugs in delayed client sideline threads exit.
- add fragment_exit_post_sideline to delete shared_cache_flush_lock
after instrument_exit,
- add dynamo_exited_all_other_threads reset for reattchment,
- initialize dcontext->client_data->suspendable to be true,
- add flag threads_are_stale in synch_with_all_threads to enforce loop
and avoid stale pointer in threads,
- skip synching client sideline threads in detach_on_permanent_stack
during detachment,
- skip terminating client sideline threads in detach_on_permanent_stack,
- add test for static detach/attach with client sideline threads,
- use app tls gdb index for apps that are statically linked with DR.
=> i#297 delay client-sideline-thread exit: fix several bugs

core/arch/aarch64/codec.c, core/arch/aarch64/decode.c, suite/tests/client-interface/drreg-test.dll.c
Also implement decode_eflags_usage() and reenable client.drreg-test,
disabled by c839a54.
Fixes #2263
=> i#2263 AArch64 flag usage: Set eflags in decode_common().

core/native_exec.c, core/native_exec.h, core/unix/native_elf.c
Split off the uses of is_native_pc() as a test for targets that should
not re-takeover as a new routine is_stay_native_pc().  Use of
dr_app_running_under_dynamorio() was broken in the presence of non-empty
native_exec_areas by 6a8d7d2, causing its execution to go native.
Fixes #2371
=> i#2371: fix native exec regression on gateway vs entry checks

core/fragment.c, suite/tests/api/static_sideline.c, suite/tests/api/static_sideline.expect
Added more synchronization in static_sideline test to make it less flaky.
Fixed a build error for vps-release-external build.
=> i#297 client sideline thread: make static_sideline less flaky

core/arch/emit_utils_shared.c, core/native_exec.c
Adds the use of os_thread_{,not_}under_dynamo() and
os_thread_re_take_over() for proper signal mask and TLS switching between
native and DR states for native_exec under default options.
Adds comments about doing this in gencode for -native_exec_opt.
=> i#2375 update native_exec: properly swap signal and TLS state

core/optionsx.h, core/utils.c, suite/tests/CMakeLists.txt, suite/tests/common/logstderr.templatex
Adds a feature to send all logging to stderr rather than files, under an
off-by-default option -log_to_stderr.  This is useful for some scenarios
where there is no readily accessible and writable local storage.
Adds a simple test.
=> Add new option -log_to_stderr

clients/drcachesim/tests/drcachesim-TLB-threads.templatex
Sometimes the miss rate is higher than 1%, which we allow in this
relaxation.
=> Relaxes the drcachesim.TLB-threads template

core/arch/aarch64/clean_call_opt.c
This patch implements analyze_callee_regs_usage to analyze the usage
of SIMD registers in the callee. insert_push_all_registers and
insert_pop_all_registers do not save and restore unused registers.
Based on work by Kevin Zhou and Edmund Grimley-Evans.
=> i#1621 AArch64 cc opt: Implement analyze_callee_regs_usage for SIMD.

core/arch/aarch64/clean_call_opt.c
This patch implements analyze_callee_save_reg using stp/ldp/str/ldr [sp, #imm]
patterns to detect callee saved registers.
Based on work by Kevin Zhou and Edmund Grimley-Evans.
=> i#1621 AArch64 cc opts: Implement analyze_callee_save_reg.

ext/drcovlib/modules.c
This CL fixed a bug in drcov handling module reload.
Because there could be more than one submodules of a module, we should iterate
the whole module table to update all submodules when a module is reloaded.
Fixes #2387
=> i#2387 assert in drcov: fixed a bug in drcov for module reload

core/annotations.c
Fixes a bug where instrument_annotation() used a thread-private dcontext
for IR allocs even when the caller's IR was using global heap.
Fixes #2392
=> i#2392: use consistent dcontext for annotation IR allocs

core/arch/interp.c, core/native_exec.c, core/optionsx.h, core/os_shared.h, core/unix/os.c, core/win32/os.c
Adds preliminary handling for restartable sequences in Linux, a kernel
feature meant for per-cpu critical regions.  The code here targets a
particular Linux kernel patch, but tries to be general to make it easy to
tweak for other flavors.
Adds a new option -rseq_sysnum to enable this support and to specify the
syscall number for the kernel extension.
For initial handling, we execute the restartable sequence natively.  It is
very complex to build regular blocks and support instrumentation, so we
start with native execution to at least allow correct app execution even if
tools miss some code.  We assume each sub-sequence is entered via a call
and exited via a return, and we use our existing native_exec gateway and
resumption mechanisms.
=> i#2350 rseq: run restartable sequences natively

core/native_exec.c, core/unix/os.c
Fixes a bug in handling the rseq system call where the parameter numbers
were mismatched.  Includes additional native_exec logging that was useful
in diagnosing the bug.
=> i#2350 rseq: fix syscall handling bug

suite/tests/CMakeLists.txt, suite/tests/client-interface/cleancall-opt-1.c, suite/tests/client-interface/cleancall-opt-1.dll.c, suite/tests/client-interface/cleancall-opt-1.expect, suite/tests/client-interface/cleancall-opt-shared.h, suite/tests/client-interface/inline.dll.c
This patch adds a new cleancall-opt-1 test. It reuses most of the
infrastructure from inline.dll.c, which is moved to
cleancall-opt-shared.h and ported to AArch64.
cleancall-opt-1.dll.c at the moment only contains a single test function
(modify_gprs) which modifies all GPRs on AArch64, as well as the SIMD
registers on X86. Once #2333 is merged, an out-of-line clean call will
be used on AArch64. My intention was to modify all relevant registers
on X86 to force using an out-of-line call, but for some reason, no
out-of-line call is used. Any ideas what I might be missing?
=> i#1621 AArch64 cc opt: Add test for -opt_cleancall=1.

core/arch/aarch64/instr_create.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/syscall-mod.c, suite/tests/client-interface/syscall-mod.dll.c
Port assembly and enable syscall-mod test for AArch64.
=> i#1569 AArch64: Enable syscall-mod test.

core/arch/aarchxx/mangle.c, core/arch/arch.h, core/arch/clean_call_opt_shared.c, core/arch/emit_utils_shared.c, core/arch/mangle_shared.c, suite/tests/client-interface/cleancall-opt-1.dll.c, suite/tests/client-interface/cleancall-opt-shared.h
Implement out-of-line calls on AArch64 using BL to jump to the code
cache. Before jumping to the save routine in the code cache, the
stack pointer is adjusted and the original value of X30 is stored
on the stack. The value from the stack is restored after jumping back
from the code cache, as BL puts the return address in X30.
This patch enables out-of-line calls for all clean calls for now, as no
other optimizations are implemented at the moment on AArch64.
=> i#1621 AArch64 cc opts: Implement out-of-line calls.

core/arch/aarchxx/mangle.c, core/arch/arch.h, core/arch/clean_call_opt_shared.c, core/arch/emit_utils_shared.c, core/arch/mangle_shared.c, suite/tests/client-interface/cleancall-opt-1.dll.c, suite/tests/client-interface/cleancall-opt-shared.h
This reverts commit 4bbc682c5db6a3c0a8c7220edfcf31b11fc4613c which broke
every test on ARM.
=> Revert "i#1621 AArch64 cc opts: Implement out-of-line calls. (#2333)"

suite/tests/CMakeLists.txt
Test static_sideline is flaky.
It sometimes hangs on exit and sometimes fails for other reasons.
This CL marks it as flaky to make the test less anonying.
=> i#297 sideline thread exit: mark static_sideline test flaky

clients/drcachesim/CMakeLists.txt, clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/simulator/analyzer_interface.cpp, clients/drcachesim/tests/reuse_time_offline.expect, clients/drcachesim/tools/reuse_time.cpp, clients/drcachesim/tools/reuse_time.h, clients/drcachesim/tools/reuse_time_create.h, suite/tests/CMakeLists.txt
Adds a separate reuse time tool, which grabs a histogram of # memory
accesses between accesses to the same address. Space and time use is
linear with the size of the trace.
TESTED: ctest; code_api|sample.* were failing before.
Fixes #2399
=> i#2399 add reuse time tool to drmemtrace.

core/arch/aarch64/clean_call_opt.c, core/arch/aarchxx/mangle.c
Only use x1 and x2 to save flags, which means x3 does not
have to be saved/restored. It also moves marking x1, x2 and x11 as used
to insert_push_all_registers, because they may not have to be
saved/restored for inlined clean calls.
=> i#1621 AArch64 cc opts: Only use x1 and x2 to save flags.

suite/runsuite_wrapper.pl
This patch updates suite/runsuite_wrapper.pl to ignore known
failures/flaky tests on ARM (AArch32 and AArch64).
Xref #2417, #2416
=> i#2416, i#2417 flaky ARM tests: Ignore known failures on ARM.

core/arch/arch.c
This function is the same on AArch64 as on ARM.
Also correct some coding style problems in the vicinity.
=> i#1569 AArch64: Implement arch_mcontext_reset_stolen_reg.

core/arch/aarchxx/mangle.c, core/lib/instrument_api.h
Moving a value to the zero register is a no-op but we have seen
ADR XZR,... used by Node.js (libv8). Having these API functions,
instrlist_insert_mov_{immed_ptrsz,instr_addr}, create no instructions
potentially adds a case for the caller to handle but most uses of
those functions set the last two arguments to NULL in any case. If it
were a problem we could create a NOP instruction instead. Creating
actual moves to XZR seems less good and would be awkward if in
generating a constant value we ever used instructions that cannot
target XZR.
=> i#1569 AArch64: Implement move (immediate) to zero register.

api/docs/bt.dox, core/arch/instr.h
In the wake of recent user confusion, we improve the docs for when to call
instr_destroy() vs instr_free().
=> Improve documentation of which IR free routines to call

core/arch/interp.c, core/dispatch.c, core/win32/callback.c
Fixes a crash with -tracedump_origins where GLOBAL_DCONTEXT was not handled
by the single-step code from 47b56c8.
Fixes line length style errors from 47b56c8.
Fixes #2144
=> i#2144 single-step: fix crash and style errors

core/arch/aarch64/emit_utils.c, core/arch/aarch64/instr_create.h
However, we omit XINST_CREATE_jump_mem, which is impossible on AArch64.
Also remove XINST_CREATE_and, which was added in error, and reorder to
match order of other architectures.
Change-Id: I9f6ef6cc321b15c49621c79bc7b4de82ee06f8f9
=> i#2440 AArch64 XINST_CREATE: Add missing platform-independent macros.

api/docs/transp.dox
The dr_mutex_create() docs included the restriction on holding locks across
code cache execution, but the warning was missing from the prose
transparency section of the docs.
=> Add missing lock restriction details to transparency docs

clients/drcachesim/simulator/analyzer_interface.cpp
Fixes an error from bc6f5a2 where the final 4 flags were omitted when
creating a cache simulator.
=> i#2006 generalize drcachesim: fix tool creator args

.appveyor.yml
We remove VS2010 from Appveyor to speed it up (it does not parallelize
builds).  This means that we officially no longer support building with
VS2010.
=> i#2406 faster appveyor: drop VS2010 support

suite/runsuite.cmake
We skip the vps build to speed up PR's, using just the merge to
master to catch breakage in vps.
=> i#2406 faster appveyor: disable vps for PR

core/win32/drwinapi/kernel32_proc.c
Fixes a crash with VS2013 client library CRT code on XP where we need to
not redirect FlsGetValue as it doesn't exist natively.
Fixes #2453
=> i#2453: support VS2013 CRT on XP

clients/drcachesim/common/named_pipe_unix.cpp, clients/drcachesim/common/options.cpp, suite/tests/CMakeLists.txt
Changes drcachesim's -ipc_name to accept an absolute path on UNIX.
Passes an absolute path to the build directory for all drcachesim
pipe-using tests, to avoid the problem of stale pipe files: now the next
suite run will delete the prior run's files.
Fixes #2023
=> i#2023: place test pipe files in the build dir to avoid stale files

api/docs/release.dox, core/arch/aarch64/instr_create.h, core/arch/arm/instr_create.h, core/arch/instr.h, core/arch/x86/instr_create.h, suite/tests/api/ir_x86.c, suite/tests/api/ir_x86_2args.h, suite/tests/api/ir_x86_4args.h
Adds three new cross-platform instruction creation macros,
XINST_CREATE_add_sll(), XINST_CREATE_jump_cond() and XINST_CREATE_slr_s(),
for use in drcachesim.
For XINST_CREATE_jump_cond(), we add aliases so that the same DR_PRED_*
constants can be used for x86 as are used on aarchxx.
Adds x86 tests.  The infrastructure for easily adding ARM (#1686) and
AArch64 (#2443) tests is still missing, unfortunately.
=> Add cbr, shift, and add-shift cross-platform instruction macros

core/arch/aarch64/instr_create.h, core/arch/arm/instr_create.h, core/arch/x86/instr_create.h, suite/tests/api/ir_x86_4args.h
Fixes an error with XINST_CREATE_add_sll where on x86 it does not convert
from a shift to the multiply that OP_lea wants.
=> Fix XINST_CREATE_add_sll shift amount on x86

clients/drcachesim/tracer/raw2trace.cpp
Adds missing support for an ARM instruction cache flush in offline trace
postprocessing (#1729).
=> i#1729 offline traces: handle arm iflush in raw2trace

clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/reader/reader.cpp, clients/drcachesim/tests/offline-multiproc.templatex, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Fixes two issues with offline traces (#1729): first, changes the reader to
not assume a separate tid header right after the initial tid,pid header, as
offline traces (as opposed to online) do not contain it.  Second, changes
raw2trace to not emit a superfluous tid entry of 0 just prior to the real
initial tid entry for each thread.
Adds asserts to catch related errors in the future in the test suite.
=> i#1729 offline traces: fix initial tid entry errors

clients/drcachesim/tests/offline-filter.templatex, suite/tests/CMakeLists.txt
Fixes two sources of failing or flaky tests for #2439:
Relaxes the tool.drcacheoff.filter test template to allow any miss rate as
we see unusually low rates on Windows for some reason.
Serializes tool.drcacheoff.filter with the tool.drcacheoff.simple test as
they end up racing on the same-glob-name trace dir.
=> i#2439 L0 filter: fix flaky tests

clients/drcachesim/common/options.cpp, clients/drcachesim/tracer/tracer.cpp
Adds an explicit check that the L0 cache sizes from #2439 are a power of 2.
Updates the docs for all options that are already required to be a power of
2 and/or a multiple of the line size.
=> i#2439 L0 filter: constrain L0 cache sizes

core/arch/aarch64/instr_create.h
This patch fixes the following bugs with XINST_CREATE/ INSTR_CREATE 
macros on AArch64:
* XINST_CREATE_jump_cond: use bcond opcode which encodes the predicate
set using INSTR_PRED
* XINST_CREATE_slr_s: use lsrv for register shift and ubfm for
immediate shifts
* INSTR_CREATE_cmp: use INSTR_CREATE_subs (which sets immediate
* arguments) instead of manually created the instruction
Fixes #2469.
=> i#2469: fix XINST_CREATE macros used by drcachesim on AArch64

core/arch/arm/arm.asm
This makes it possible to run DynamoRIO on hardware without NEON,
at least in some cases. A bit more work is needed to make everything
work reliably on any ARMv7 system with VFPv3-D32.
=> i#2448 NEON: Use VFPv3 rather than NEON instructions in arm.asm.

core/unix/signal.c
GCC 7 had detected that the usage of set->sig[0] in kernel_sigismember, when called via set_blocked in handle_sigreturn, would be uninitialized. This can however be ignored since it occurs immediately after an ASSERT_NOT_IMPLEMENTED(false) on AArch64.
=> i#1569 AArch64: Fix uninitialized variable error when building with GCC 7 on AArch64.

core/unix/include/sigcontext.h, core/unix/signal_linux_arm.c, core/win32/events.mc
With kernels up to 4.12, when CONFIG_IWMMXT is enabled the VFP frame
in the ucontext is offset by the size of the IWMMXT frame even when
no IWMMXT frame is written. We work around this by sending ourselves
a signal at init time and looking for the VFP frame in both places.
=> Handle ARM Linux kernel with CONFIG_IWMMXT enabled.

core/arch/aarchxx/mangle.c
X0 is clobbered by insert_push_all_registers so we should explicitly
save it.
=> i#1621 AArch64 CC opt: Always save/restore X0.

core/arch/arm/table_a32_unpred.c
Replace some "INVALID" lines in A32_ext_simd8.
Also correct the opcodes in A32_ext_bit19.
Change-Id: I5fcf10fd028da215730a4f2327a317ab1f2a9e98
=> i#1686 decoder tests: Add some missing OP_vbic_{i16,i32} encodings.

core/arch/aarchxx/mangle.c
By tightly packing the saved registers on the stack, we can reduce the
clean call stack stack size, which should be done in a follow-up commit.
=> i#1621 AArch64 CC opt: Use consecutive slots to save/restore regs.

core/arch/arm/decode_private.h, core/arch/arm/encode.c
Roll-back of greedy reglists was permitted even when the reglist was
required to have min_num == max_num. This prevented the encoding of
an instruction such as "VTBL.8 d0, {d2-d3}, d4", because it was
tried with TYPE_L_VAx3 (list of length 3) before it was tried with
TYPE_L_VAx2 (list of length 2). The attempt to use TYPE_L_VAx3 would
incorrectly succeed because of the unrestricted roll-back.
The solution used here is to set a field reglist_min_num in the
decode_info_t and disallow roll-back beyond that minimum length.
Fixes #2494
Change-Id: Id1c22723f7862abc2cf24c0bbab4254b32232b33
=> i#2494 ARM encoder: Fix bug in roll-back of reglists.

suite/tests/CMakeLists.txt
Moves the tool.drcachesim.filter's test pipe file into the build dir from
/tmp to avoid stale files, to match all the other drcachesim tests.
=> i#2023 follow-up: apply to tool.drcachesim.filter

core/dynamo.c, core/heap.c, suite/tests/api/dis.c
We call standalone_init() if global_heap_alloc() is invoked in full DR that
is not yet initialized, to support use as a decoding library without
requiring explicit initialization.
Adds a test to api.dis.
Fixes #2499
=> i#2499: auto-standalone-init from global heap alloc

core/arch/aarch64/codec.c, core/arch/aarch64/encode.c, core/arch/arm/encode.c
Make instr_encode_arch() return NULL, without an assertion failure,
if no encoding is found. The failure to encode might indicate an
internal error, but this function is also called from the API,
whose documented behaviour is to return NULL.
Also, on AArch64, move the code to handle OP_xx from codec.c to
encode.c because if encode_common() accepts OP_xx then we cannot
recognise a failure to encode from its uint return value.
Change-Id: I38f582c30481bb447c0a079ef12a5a80562f7176
=> On ARM and AArch64, do not fail when no encoding is found.

core/arch/aarch64/codec.c, core/arch/aarch64/codec.txt
When encoding BL, require X30 as the destination opnd, for
consistency with BLR.
Change-Id: I448ad6e057c2d8bea047854aa3f031c2bcade89d
=> i#1569 AArch64: Follow-up to 3275b81: check X30 opnd in encoder.

core/arch/aarch64/codec.c, core/arch/aarch64/codec.py, core/arch/aarch64/codec.txt, core/arch/aarch64/decode_gen.h, core/arch/aarch64/encode_gen.h
This is neater than hacking the potentially general-purpose formalism
to treat "adr" and "adrp" differently and is also more consistent with
how branch instructions are handled.
Change-Id: I085cf7627dd7d165816b7163ed53498c5c53153a
=> i#1569 AArch64: Follow-up to 428b896: Use opndset for ADR and ADRP.

ext/drx/drx_buf.c, suite/tests/client-interface/drx_buf-test.dll.c
All required XINST_ macros required by drx_buf_insert_buf_memcpy have
been added for AArch64 and the ifndef AARCH64 guards can be removed
from drx_buf_insert_buf_memcpy and the accompanying test
drx_buf-test.dll.c
Thanks @toshipiazza for pointing that out!
Fixes #2520.
=> i#2520: remove ifndef AARCH64 from drx_buf_insert_buf_memcpy

core/arch/aarch64/codec.py, core/arch/aarch64/encode_gen.h
Add some unnecessary initialisers to prevent certain compiler versions
from breaking the build by incorrectly claiming that certain variables
"may be used uninitialized".
Change-Id: I8d9bf5497e64e464d3e7e49a3ba7db8daea3ac69
=> i#1569 AArch64: Initialise variables in encoder functions.

core/arch/aarch64/codec.c, core/arch/aarch64/codec.py, core/arch/aarch64/codec.txt, core/arch/aarch64/decode_gen.h, core/arch/aarch64/encode_gen.h, suite/tests/api/dis-a64.txt
The "x16imm" operand type can be a register, or a constant denoted
in the encoding by register number 31. The value of the constant can
be determined from various bits in the instruction, but those bits
can not be uniquely determined from the constant operand. In particular,
we can not generate bit 30 in this case. Within the constraints of the
current formalism the best solution seems to be to remove bit 30 from
the bits generated by x16imm and duplicate the 14 bit patterns that
use x16imm.
There are other instances of such duplication. The formalism should
perhaps be improved.
Change-Id: I319d8e4b9550d39b11f5dce80fe7801115445446
=> i#1569 AArch64: Fix bug in encoding (SIMD structure load/store).

README.md
=> i#2488: fix links for memtrace and drltrace in README.md

api/docs/intro.dox, suite/tests/CMakeLists.txt
By using 128k for -stack_size, we ensure that stack_size is a multiple
of all valid page sizes on AArch64 (4k, 16k and 64k).
Fixes #2540.
=> i#2540: use 128k for -stack_size in nightly tests.

clients/drcachesim/tracer/drmemtrace.h
Adds drmemtrace_client_main() to the drmemtrace.h header for use by
applications statically linking in the drmemtrace client.
The existing burst_static test for this linking feature did not need a
declaration as it tests a duplicate weak symbol, so there are no test
changes here.
=> i#2006 generalize drcachesim: declare drmemtrace_client_main

clients/drcachesim/CMakeLists.txt, suite/runsuite.cmake, suite/tests/CMakeLists.txt
Fixes ARM build breakage from 66fa2c78 whose test is x86-specific.
Adds test building to the ARM and AArch64 cross-compile debug builds to
catch such errors in the future.
=> i#2511 isolate raw2trace: build tests on x86 only

core/arch/interp.c
Tweaks the availability of bbdump_tags in release builds from ac72b3c0 to
be contingent on CLIENT_INTERFACE, to fix the vps build.
=> Fix bbdump_tags for non-CI builds

core/unix/os.c
Fixes an error where find_free_memory_in_region() thinks that an occupied
region that spans the requested endpoint is free, resulting in an infinite
loop in os_heap_reserve_in_region().
Manually tested on the app whose maps file hit this.  (Creating a suite
test is non-trivial without a mock for the maps iterator.)
Fixes #2557
=> i#2557: fix fencepost error in find_free_memory_in_region()

.travis.yml, suite/runsuite.cmake, suite/runsuite_wrapper.pl
For the Android cross build, we fetch Android NDK r10e and set it up to
use ld.bfd as ld for the build to work. Newer versions of the Android
NDK won't work until #1927 is fixed.
This commit introduces a new DYNAMORIO_CROSS_ANDROID_ONLY environment
variable, to allow building for Android on a separate instance, because
fetching the NDK might take a while.
Fixes #2207
=> i#2207: enable Android cross build on Travis

api/docs/intro.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/tests/burst_noreach.cpp, clients/drcachesim/tests/offline-burst_noreach.templatex, core/dynamo.c, core/heap.c, core/heap.h, core/lib/instrument.c, core/optionsx.h, core/unix/os.c, suite/tests/CMakeLists.txt
Adds a new option -reachable_client, on by default.  When turned off,
client libraries being within 32-bit-displacement reachability of the code
cache is relaxed, both the library load location and the fatal error on
violation.  This is particularly useful for statically-linked clients whose
location is difficult to change.
Includes changes to vmm allocation required to make this work for
statically-linked clients:
+ Eliminates the setting of heap reachability constraints prior to vmm
allocation, except for -heap_in_lower_4GB which has no fallback.
+ Client libraries are now loaded *after* the vmm is allocated.
+ -vm_base_near_app tries to be near the app but on failure, if
-vm_allow_not_at_base, it allows allocating away from the app.
+ When reserving any available memory, on UNIX, we …
=> i#2558: relax client reachability and vmm base location

core/arch/aarchxx/mangle.c, core/arch/arch.h, core/arch/mangle_shared.c, core/arch/x86/mangle.c, core/heap.c, core/lib/instrument.c, core/lib/instrument_api.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/reachability.dll.c, suite/tests/client-interface/reachability.expect
Applies DR_CLEANCALL_INDIRECT to out-of-line helper calls.  Removes the
hardcoded direct calls used for out-of-line clean call setup and cleanup
code and replaces with insert_reachable_cti().
Fixes vmcode_unreachable_pc() to avoid a wraparound issue.
Adds a test where a client generates a clean call into custom
non-code-cache memory.
=> i#774 x64 reachability: extend reachability to out-of-line helper calls

clients/drcachesim/CMakeLists.txt, clients/drcachesim/tests/burst_maps.cpp, clients/drcachesim/tests/offline-burst_maps.templatex, core/unix/memquery.c, core/unix/os.c, suite/tests/CMakeLists.txt
Makes library identification when walking the /proc/self/maps file more
robust, in particular in the presence of anonymous mappings in the text
segment.  memquery_library_bounds_by_iterator() deduces the file backing
for sequences of contiguous entries even when some entries are anonymous.
Changes get_application_base() to use memquery_library_bounds_by_iterator()
to use this functionality as well.
Changes find_executable_vm_areas() to handle an anonymous region with an
ELF header.
Changes mmap_check_for_module_overlap() to use a later inode field if the
first is 0.
I wanted to have a unit test here but while mocking the maps iterator is
feasible, our code here also walks ELF headers, which is harder to
separate.  Instead I made a new application-based test where the app places
anonymous …
=> i#2566: handle anon mmaps in text segments

core/dynamo.c, core/heap.c, core/heap.h, core/vmareas.c, core/vmareas.h
Tested: ctest,internal repro.
Fixes #2571
=> i#2571 exit flags not reset: reset on init.

clients/drcachesim/tests/burst_static.cpp, clients/drcachesim/tests/offline-burst_client.templatex, clients/drcachesim/tests/offline-burst_static.templatex, core/dynamo.c, core/lib/statsx.h, core/optionsx.h, core/utils.c, core/utils.h
Adds a new option -rstats_to_stderr for obtaining some basic peak
statistics from release builds without resorting to concurrent shared
memory reading.
Tweaks the existing rstats to use a consistent name so we can skip the
non-peak stats for this option.
Adds a test case to the burst_static test.
Fixes #2573
=> i#2573: print rstats at exit

core/arch/interp.c, core/arch/mangle_shared.c, core/arch/x86/opcode.h, core/dispatch.c, core/win32/callback.c, suite/tests/security-win32/except-debugreg.c, suite/tests/security-win32/except-debugreg.expect
The previous patch was not complete : it did not work when debug register was set to an address starting a basic block.
The test case checks now both situations : debug register at a start or in the middle of a basic block.
+ there were useless flushes
=> i#2163 : better fix and test case

clients/drcachesim/common/utils.h, clients/drcachesim/tracer/tracer.cpp
The drmemtrace buffer's redzone was much larger than necessary, as it only
needs to hold about one basic block's worth of memory references.  We
shrink it substantially here based on -max_bb_instrs: now it's 4K by
default (for -offline) as opposed to the 32K it took before, which makes a
significant difference on apps with many threads.
Fixes #2299
=> i#2299: shrink drmemtrace buffer redzone

suite/tests/CMakeLists.txt
Currently the api.it test fails on Android, likely due to DT_RUNPATH not
being supported. The way these api.* tests operate should be changed to
support Android as well in the future.
Fixes #2580
=> i#2580 api.it: Fix it test failure on Android

core/translate.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/translate_sandbox.c, suite/tests/client-interface/translate_sandbox.dll.c, suite/tests/client-interface/translate_sandbox.expect
Sets translation to instruction in recreate_app_state_from_info
so that translate_walk_track can restore spilled registers.
=> i#2082 : Sets translation when recreating app state from info

core/arch/mangle_shared.c, suite/tests/security-win32/singlestep.c, suite/tests/security-win32/singlestep.expect
Last patch worked fine for single step execution in normal mode.
But it does not work when dynamorio uses at the same time sandboxing.
Because sandboxing and single step both use special exit, there was a confusion.
When a basic block is built, sandboxing is inserted before mangling, which is used to modify special exit reason. 
But, sandboxing adds another cti (not a meta app) in case there was a self-modification in the basic block.
So, this patch checks that only the last app instruction at single step address will be mangled
=> i#2144: better patch for single step with sandboxing

api/docs/release.dox, api/samples/bbbuf.c, api/samples/bbcount.c, api/samples/inscount.cpp, api/samples/instrace_simple.c, api/samples/memtrace_simple.c, api/samples/opcodes.c, clients/drcachesim/tracer/tracer.cpp, core/lib/instrument.c, ext/drmgr/drmgr.c, ext/drmgr/drmgr.dox, ext/drmgr/drmgr.h, ext/drreg/drreg.c, ext/drx/drx.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/drx-test.dll.c, suite/tests/client-interface/predicate-test.c, suite/tests/client-interface/predicate-test.dll.c, suite/tests/client-interface/predicate-test.expect
Enables global auto-predication as part of drmgr's insertion event. Also
modifies instrace and memtrace samples to do the right thing with
respect to predication during memref tracing vs instruction tracing.
drreg does not interact well with other drmgr passes, as well as main
client passes when auto-predication is enabled. We disable
auto-predication for all drreg passes.
drmemtrace is non-trivial to add auto-predication to. We globally
disable auto-predication for drmemtrace.
Fixes #1723
=> i#1723 predication: Globally enable auto predicate

suite/runsuite_wrapper.pl
Unfortunately two failures are happening often enough that I'm adding them
to the #2145 list here: 32-bit api.detach #2246 and 64-bit drmgr-test #1369.
=> i#2145 appveyor failures: add two tests to the ignore list

core/heap.c, core/heap.h, core/optionsx.h
Reduces the compile-time minimum VMM block size as well as the default
-vmm_block_size from 16KB to 4KB on UNIX to avoid wasted space from
non-16KB-aligned allocation sizes.  The savings are non-trivial for
applications with many threads where we have multiple per-thread small
allocations (such as the TLS mmaps) and will make further memory reductions
via changing unit size parameters more fruitful by allowing a wider range
of sizes without overhead.  The downside is more memory and overhead on
memory management but the tradeoff is worthwhile.  This is much simpler
than trying to share VMM block allocations among separate uses like we do
on Windows for the stack and gencode.
=> i#2575 shrink thread mem: reduce vmm block size to 4KB on UNIX

core/heap.c, core/monitor.c, core/options.c, core/optionsx.h
Eliminates the allocation of per-thread trace head hashtables when traces
are disabled.
Reduces -initial_heap_unit_size on UNIX to 12K, as the per-thread
non-persistent heap typically stays under 12K and there's no reason to
allocate 32K for every thread there.
=> i#2575 shrink thread mem: reduce private heap size

core/heap.c, core/heap.h, core/options.c, core/optionsx.h, core/unix/signal.c, core/unix/signal_private.h, core/win32/events.mc, suite/tests/CMakeLists.txt
Adds a new option -max_pending_signals.  Changes the special heap used for
pending signals to take in an initial unit size and not be dependent on the
regular heap's default unit sizes.  The pending signal heap size is sized
to fit -max_pending_signals entries.  The default is 8, which rounds up to
12K for x86_64, saving per-thread memory over the prior 32K size.
Adds a pending signal count and warns (in release build too) when the
maximum is reached.
Adds a check for getting close to the limit when delivering a pending
signal: if so, we proactively allocate a 2nd unit while we can safely
acquire locks.
Adds a test of "-max_pending_signals 1" for linux.sig* to the long suite.
Issue: #2575
=> i#2575 shrink thread mem: shrink and parameterize pending signals

api/docs/intro.dox, api/docs/release.dox, core/options.c, core/optionsx.h, core/unix/signal.c
Adds a new option -signal_stack_size with a smaller default than
-stack_size (32K for -code_api instead of 56K).  Publicly documents this
option so that clients can control it and better tune their per-thread
memory usage for scaling to applications with many threads.
Issue: #2575
=> i#2575 shrink thread mem: separate signal stack size

suite/tests/CMakeLists.txt, suite/tests/api/detach.c, suite/tests/api/startstop.c, suite/tests/condvar.h, suite/tests/linux/vfork.c, suite/tests/thread.h, suite/tests/thread_clone.h, suite/tests/tools.c, suite/tests/tools.h, suite/tests/win32/nativeterminate.c, suite/tests/win32/threadchurn.c, suite/tests/win32/threadexit.c, suite/tests/win32/threadterm.c
Moves the current clone-based thread routines to thread_clone.h.
Moves the current Windows thread routines into thread.h and adds a
pthread-based UNIX parallel implementation.
Updates api/detach.c and api/startstop.c to use the new cross-platform
routines.
Moves the _WIN32_WINNT define for condvar.h from needing to be in each
test's code (due to header order limitations) to be auto-magically added
from cmake.
Updates other tests to include the right header files.
=> Add cross-platform thread routines for tests

core/dynamo.c, core/globals.h, core/unix/os.c
Fixes a hang on attach on UNIX by avoiding re-takeover of an in-transition
thread, by waiting for uninit_thread_count to reach 0 before initiating
takeover of "unknown" threads.
Tested on the api.detach_spawn test.
Fixes #2603
=> i#2603: fix hang on attach

core/heap.c, core/options.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/stack-overflow.dll.c
Fixes issues from 240b75d6 #2592 which added UNIX stack overflow
reporting:
+ Fixes -stack_size and -signal_stack_size to have a minimum of just the
page size, not double it, as the guards are added on top.
+ Fixes leak reporting to consider -stack_guard_pages and not just
-guard_pages.
+ Makes the client.stack-overflow test less flaky by setting a specific
stack size to avoid variations in compilers and platforms.
Fixes #2606
=> i#2606: stack size with 64K pages

core/heap.c, core/options.c, core/optionsx.h
Increases the default -vm_size for 64-bit from 128M to 256M.
Increases the maximum supported -vm_size for 64-bit from 512M to 1G.
Adds support for a 'G' or 'g' suffix on size options.
=> Increase -vm_size default and max for 64-bit

core/unix/os.c, core/unix/signal_linux_x86.c
In standalone mode we avoid sending the xstate query signal to avoid a
spurious SIGILL in "regular" applications.
Fixes #2617
=> i#2617: do not send query signal for standalone

core/unix/signal_linux_x86.c, core/unix/tls_linux_x86.c, core/win32/events.mc
Relaxes the signal query assert that fpstate is set up, as it's NULL for
WSL (needs further investigation for proper signal support).
Downgrades the general syslog warning for WSL to an internal warning as
simple applications are working.
Issue: #1896
=> i#1896 WSL: relax fpstate assert and unsupported syslog

core/arch/x86/mangle.c
Fixes a bug in insert_mov_immed_arch on x64 which resulted in incorrect top
bits in the immediate.
Fixes #2621
=> i#2621: fix insert_mov_immed_arch x64 size bug

core/unix/include/sigcontext.h, core/unix/signal_linux_arm.c
Kernel 4.13 fixed the bug by inserting a dummy padding block,
and it expects the dummy block to be present if the VFP frame is
offset by the size of an IWMMXT frame. This requires an update to
our work-around.
Change-Id: Ie1fce56bbd89912cc8aa2e2a5360b6688d5f2be9
=> Follow-up to 0b75c63: Handle ARM Linux with CONFIG_IWMMXT.

clients/drcachesim/CMakeLists.txt, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer.h, clients/drcachesim/reader/reader.h, clients/drcachesim/tests/histogram-offline.templatex, clients/drcachesim/tools/histogram_launcher.cpp, suite/tests/CMakeLists.txt
Adds an alternate analyzer_t mode where a single tool controls iteration,
by exposing the iterator and making reader.h public.
Adds a test case of the external iterator to the histogram_launcher-based
tests.
=> i#2006 drcachesim generalization: expose iterator from analyzer

core/unix/memquery.c
Fixes a crash on 4.4.0-93 kernels due to the vdso being placed right before
the exe.  The bug is in the hugepage text handling from i#2566 where it
merges with a prior mapping but fails to check whether the current mapping
is also an ELF header.
Issue: #2634, #2566
Fixes #2634
=> i#2634: fix early crash on latest linux kernels

clients/drcachesim/tracer/raw2trace.cpp
Fixes a bug in 66fa2c7 where errors during raw trace file conversion are
silently ignored and success is misleadingly reported with a truncated output
file.
=> i#2511 raw2trace: fix bug from refactoring

ext/drutil/drutil.c, ext/drutil/drutil.h
Changes drutil_insert_get_mem_addr_x86() to avoid using the 2nd register
when we don't have to, and documents the cases where we have to, so clients
can use registers more efficiently.
Adds an explicit SEG_CS check and assumes it's flat (we were already doing
this in helper routines: we just make it explicit up front here).
=> DrMi#2041: improve drutil_insert_get_mem_addr_x86

core/CMakeLists.txt, core/CMake_readelf.cmake, core/unix/signal.c, make/package.cmake, suite/tests/linux/signal_racesys.c, tools/CMakeLists.txt
Fixes a clang warning in suite/tests/linux/signal_racesys.c.
Changes two inline asm direct jumps to indirect in core/unix/signal.c to
work around clang text relocations that have suddently appeared in recent
clang versions.
However, clang is still marking libdynamorio.so as TEXTREL, so I'm
disabling the TEXTREL check on libdynamorio.so for 32-bit release clang.  I
also add a check refusing to build an official package with clang until
this is fixed.
Issue: #2632
=> i#2632 clang: fix Travis clang build

core/CMakeLists.txt
Adds -fPIC to drhelper to fix a clang build error.
Fixes #2632
=> i#2632 clang: fix Travis clang x64 release build

core/heap.c
On unix it should be safe to free the heap even if there blocks still
being used since we are clearing out all other memory references anyway.
I also included a fix to vmm_heap_unit_init which accidentally left
vmh->alloc_start uninitialized in the branch related to reserving OS
memory at a preferred location.
Issue: #2157
=> i#2157 re-attach: Always free the heap on unix

core/unix/loader.c
Adds a sanity check assert that when we fill the libdynamorio text-data gap
with a no-access mmap, we're not clobbering something that's already there,
like the vvar or vdso mappings.
Issue: #2641
=> i#2641 lib gap: add assert that the gap is empty

clients/drcachesim/CMakeLists.txt, clients/drcachesim/reader/reader.h, clients/drcachesim/simulator/cache_simulator.h, clients/drcachesim/simulator/simulator.cpp, clients/drcachesim/simulator/simulator.h, clients/drcachesim/simulator/tlb_simulator.h, clients/drcachesim/tools/histogram.h, clients/drcachesim/tools/reuse_distance.cpp, clients/drcachesim/tools/reuse_distance.h, clients/drcachesim/tools/reuse_time.cpp, clients/drcachesim/tools/reuse_time.h, clients/drcachesim/tracer/physaddr.cpp, clients/drcachesim/tracer/physaddr.h, ext/droption/droption.h, make/DynamoRIOConfig.cmake.in
Adds -std=c++11 to the build flags for drcachesim.
Adds handling of -std=c++11 in the client flags processing code (i#1820).
Switches all instances of std::map to std::unordered_map in drcachesim.
Adds explicit sorting for printing histograms in the reuse_distance and
reuse_time tools (yes it's still faster to be unordered as the print time
is not on the critical path).
Issue: #2020
Fixes #1820
=> i#1820,i#2020: use c++11 and unordered_map in drcachesim

clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
Adds a cache of decoded instruction information to avoid repeated decoding
on every dynamic execution of each instruction.  We use a drcontainers
hashtable as performance analysis shows that it out-performs C++
unordered_map.
Fixes #2056
=> i#2056: improve raw2trace decode performance

CMakeLists.txt, api/samples/inscount.cpp, clients/drcachesim/CMakeLists.txt, make/DynamoRIOConfig.cmake.in, suite/tests/client-interface/drwrap-test-callconv.dll.cpp, suite/tests/client-interface/exception.dll.cpp
Sets -std=c++11 in the base compiler flags for all DR code.
Refactors configure_DynamoRIO_common(), which used flags set for either C
or C++ depending on the whole target, to be merged and invoked later with
_DR_set_compile_flags(), where we can split the flags by source file rather
than target and have two sets of flags.
Fixes misc warnings with C++11 in various files.
Fixes #2020
=> i#2020: use C++11 in all DR C++ code

core/unix/memquery_linux.c, suite/tests/CMakeLists.txt
Fixes a regression on handling application paths with spaces by replacing
the %s in the maps file scanf format string.
Adds a test with a space in the name by renaming common.broadfun.
Fixes #2538
=> i#2538: fix regression on paths with spaces

core/win32/syscall.c
get_remote_process_ldr_status() returns 'int' but remote_ldr_data was 'uint'
and 'remote_ldr_data >= 0' was always true
=> Fix get_remote_process_ldr_status() failure check

core/arch/aarchxx/mangle.c, core/arch/interp.c, core/arch/mangle_shared.c, core/dispatch.c, core/lib/instrument.c, core/synch.c, core/synch.h, core/translate.c, core/unix/os.c, core/unix/signal.c, core/unix/signal_linux.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/signal.dll.c, suite/tests/client-interface/signal.expect, suite/tests/linux/eintr.c
Changes the strategy for handling interrupted syscalls to use SA_RESTART,
which adds easy handling of interruptions of auto-restart syscalls in
native code, such as during attach or in client C code.
This also simplifies auto-restart of app syscalls, as we now have foolproof
identification of auto-restart situations (before our syscall-number-based
check was inaccurate) and the kernel has restored the clobbered register
value for us.  That eliminates the TLS store we were doing on ARM and the
decode on x86.
For fragment-inlined syscalls, we don't need to do anything anymore: we
deliver the signal immediately and the kernel has already set up the proper
resumption state.
For gencode syscalls, for sane post-syscall handling, we leverage i#1145's
auto-restart emulation and undo what the …
=> i#2659 syscall restart: switch to using SA_RESTART

clients/drcachesim/tracer/raw2trace.cpp
Initialize the modhandle field to NULL, and don't call
drmodtrack_offline_exit when the modhandle is NULL. This prevents a
segfault during the destructor of raw2trace_t when the module file is
missing or invalid.
Fixes #2663
=> i#2663 ~raw2trace_t segfault: Initialize modhandle

ext/drwrap/drwrap.h
Updates the docs for drwrap_{get,set}_arg() to clarify that they honor the
previously specified calling convention.
=> Clarify drwrap_{get,set}_arg calling convention behavior

suite/runsuite_wrapper.pl
Marks api.detach and api.startstop as flaky as they have been failing
occasionally on Appveyor.
Issue: #2093, #2246, #2145
=> i#2145 appveyor: mark api.detach and api.startstop as flaky

.travis.yml
Adds a "brew update" step to work around Travis Mac problems until they
upgrade their VM's.  Xref https://github.com/travis-ci/travis-ci/issues/8552.
=> Fix Travis Mac setup failures

suite/runsuite_wrapper.pl
Marks api.detach_spawn as flaky as a race exists that has not yet been
fixed.
Issue: #2611
=> i#2611 detach race: mark api.detach_spawn flaky

api/docs/release.dox, clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/tests/drcachesim-delay-simple.templatex, clients/drcachesim/tracer/tracer.cpp, ext/drmgr/drmgr.c, suite/tests/CMakeLists.txt
Adds a new option -trace_after_instrs which counts instructions and once
the dynamic instruction count hits the specified threshold, tracing is only
then enabled.  This is more efficient than the -skip_refs simulation-side
option.
Fixes a drmgr bug hit by the dynamic event removal and adding exercised by
this feature.
Adds a test of the option.
Issue: #2645
=> i#2645 delayed burst, part 1: Add delayed-tracing to drmemtrace

clients/drcachesim/reader/compressed_file_reader.h, clients/drcachesim/reader/file_reader.h, clients/drcachesim/tools/histogram.h, clients/drcachesim/tools/reuse_distance.h
Marks the file_reader_t::is_complete() and analyzer_t::init_file_reader()
methods as virtual to provide more flexibility in subclassing.
Cleans up some now-stale comments about drcachesim optimizations.
Issue: #2006
=> i#2006 drcachesim generalization: make subclassing easier

clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/tests/drcachesim-delay-simple.templatex, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Adds a new drmemtrace feature -exit_after_tracing N which exits the process
after tracing N memory references.  Extends the -trace_after_instr test to
include -exit_after_tracing.
We would prefer -detach_after_tracing but we need i#2644 for that and we
leave it for future work.
Fixes #2645
=> i#2645 delayed burst, part 2: add -exit_after_tracing

core/unix/os.c, core/unix/os_private.h, core/unix/signal.c
Adds a check when taking over a new thread during attach to avoid
self-interp when the new thread is the child of a thread that's already
been taken over.
Tested with the api.detach_spawn test from #2601.
Fixes #2688
=> i#2688: avoid self-interp of new child threads during attach

core/io.c
Adds support for the 'z' format code length modifier to dr_sscanf.  It was
already supported for dr_snprintf.
=> Add 'z' format code support to dr_sscanf

api/docs/release.dox, clients/drcov/postprocess/drcov2lcov.cpp, core/module_list.c, core/unix/os.c, ext/drcovlib/drcovlib.c, suite/tests/client-interface/events.dll.c
Adds vdso to the module list at init time.  Previously, it would be added
upon execution (via the module event trigger), but would otherwise be
absent.
I'd like to also add vsyscall, when it's separate, but it has no ELF header
and that complicates placing it on the module list, so for now we leave it
off.
Adds a release note as this could affect existing clients.
Tweaks drcovlib to handle displaced tags such as for the vsyscall hook.
=> Include vdso in the module list

core/lib/dr_api.h
Removes the _USES_DR_VERSION_ symbol from use as a standalone library, as
it causes problems when a standalone-using library is linked into a client.
=> Remove API version symbol from standalone users

ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
Adds an explicit index field to drmodtrack_info_t so that the data
structure can be passed around without an accompanying iterator index.
Issue: #2006
=> i#2006 generalize drcachesim: Add index field to drmodtrack_info_t

ext/drcovlib/drcovlib.c
The changes in ea84da0 to handle displaced vsyscall code in drcovlib's
assert ended up causing asserts for rep str expansion.  We relax the assert
to handle that here.
=> Relax drcovlib assert to handle rep str expansion

tools/drdeploy.c
Tools invoked with the -help option will now emit information to
standard output and exit succesfully, as recommended by the GNU coding
standards [1].
[1] https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html
Issue: #2683
=> i#2683 Emit -help output to stdout and exit successfully

suite/runsuite.cmake
Precommit tests will fail if Git adds tabs to the revision lines in the
diff. This is already handled for SVN, this change does the equivalent
for Git.
=> Remove tabs from git revision lines

ext/drmgr/drmgr.c
Take care to set the registered_fault bool back to false after
event unregister so that it can be re-registered on a later reattach,
Issue #2157
=> i#2157 re-attach: Ensure drmgr events get reinstalled

api/docs/release.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tests/offline-burst_replace.templatex, clients/drcachesim/tracer/drmemtrace.h, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, clients/drcachesim/tracer/tracer.cpp, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c
Adds offline trace handling of VDSO code by dumping the actual contents of
the VDSO pages into drmodtrack custom data and using it to decode
instructions during post-processing.
Updates drmodtrack to handle binary data in custom fields.
Refactors how 3rd-party custom module fields are handled for drcachesim as
they now must be multiplexed with the new VDSO data.  The 3rd party must
now build a custom post-processor by linking with the raw2trace library.
Since the module list file is no longer completely human-readable and
contains hidden custom fields, a new interface
raw2trace_t::do_module_parsing() is added to support building 3rd-party
module file parsing code for use after a trace is gathered.
Adds drmemtrace_get_output_path() for dynamically locating offline trace
files.
Updates the …
=> i#2062 trace non-mod: handle traced VDSO code

clients/drcachesim/tests/reuse_time_offline.expect, clients/drcachesim/tools/reuse_time.cpp, clients/drcachesim/tools/reuse_time.h
Used downstream in derived classes.
=> i#2399 add reuse time tool : count instructions.

core/options.c
This variable is not used anywhere else other than in the file
options.c.  Before it is used, it is always set.  So no need to provide
a default initialization.  This shaves 27,136 bytes from the size of the
statically compiled library.
Before:
-r-xr-xr-x 1 nilayvaish eng 3026934 Nov 23 14:08 libdynamorio.a
After:
-r-xr-xr-x 1 nilayvaish eng 2999798 Nov 23 14:03 libdynamorio.a
=> Do not initialize temp_options variable.

api/docs/API.doxy, api/docs/intro.dox, api/docs/release.dox, core/arch/arch.c, core/globals.h, core/lib/globals_shared.h, core/lib/instrument.c, core/lib/instrument.h, core/lib/instrument_api.h, core/unix/os.c, core/unix/os_exports.h, core/unix/os_private.h, core/unix/signal.c, core/win32/callback.c, core/win32/os.c, core/win32/os_exports.h, ext/drmgr/drmgr.c, ext/drmgr/drmgr.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/drmgr-test.dll.c, suite/tests/client-interface/events.dll.c, suite/tests/client-interface/events.templatex, suite/tests/client-interface/fibers.template, suite/tests/client-interface/flush.dll.c, suite/tests/client-interface/flush.template, suite/tests/client-interface/signal.dll.c, suite/tests/client-interface/signal.expect, suite/tests/client-interface/winxfer.c, suite/tests/client-interface/winxfer.dll.c, suite/tests/client-interface/winxfer.templatex
Adds a new client API event type: a kernel-mediated control transfer.  This
includes UNIX signal delivery and return, Windows APCs, callbacks,
exceptions, NtContinue, NtSetContextThread, and callback returns.  It is
also raised on client redirects.
The new interface passes the source context (control and integer, no
multimedia) but passes just key target fields directly (new pc, new xsp)
and does not pass in the full target register state to avoid copying costs
(particulary for multimedia).  Adds a new internal os_cxt_ptr_t type to
support pointing at a CONTEXT or sig_full_cxt_t for the new events and only
copying from that state if the client calls dr_get_mcontext().  Adds extra
logic to get the source context for dr_redirect_execution() called from the
exception event.
Includes limited …
=> i#241,i#1693: add kernel transfer client events

api/docs/release.dox, clients/drcpusim/drcpusim.cpp, clients/drcpusim/options.cpp, clients/drcpusim/options.h, suite/tests/CMakeLists.txt
Adds a new drcpusim option -ignore_all_libs and uses it on cpuid tests to
avoid failures on Travis Mac where system libraries are using recent
instructions.  These cpuid tests are mainly testing cpuid fooling, not
instruction set violations.
Fixes #2720
=> i#2720 cpusim tests: add -ignore_all_libs option

api/docs/release.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/common/memref.h, clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/common/trace_entry.h, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/reader/reader.cpp, clients/drcachesim/simulator/analyzer_interface.cpp, clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/simulator/tlb_simulator.cpp, clients/drcachesim/tests/basic_counts.templatex, clients/drcachesim/tests/offline-basic_counts.templatex, clients/drcachesim/tools/basic_counts.cpp, clients/drcachesim/tools/basic_counts.h, clients/drcachesim/tools/basic_counts_create.h, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/instru_online.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Adds the concept of "marker entries" to drcachesim's traces, which can be
used to store metadata about a location in a trace.
Uses DR's new kernel xfer event to insert trace marker entries on
kernel-mediated control transfers: signal handlers, signal returns, Windows
APCs, exceptions, callbacks, etc.
To help with testing, adds a new tool basic_counts which counts the number
of each trace entry type per thread in the trace.
Adds new online and offline tests that run the basic_counts tool it on the
common.decode-bad test binary.
Fixes #2708
=> i#2708 trace xfers: record kernel xfer boundaries in traces

api/docs/release.dox, clients/drcachesim/common/trace_entry.h, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/reader/reader.cpp, clients/drcachesim/reader/reader.h, clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/simulator/tlb_simulator.cpp, clients/drcachesim/tests/basic_counts.templatex, clients/drcachesim/tests/offline-basic_counts.templatex, clients/drcachesim/tools/basic_counts.cpp, clients/drcachesim/tools/basic_counts.h, clients/drcachesim/tracer/instru.cpp, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_online.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp, core/arch/aarch64/instr.c, core/arch/arm/instr.c, core/arch/instr.h, core/arch/x86/instr.c, suite/tests/CMakeLists.txt
To satisfy both cache and core simulators we mark subsequent iterations of
rep string loops with a new trace entry type TRACE_TYPE_INSTR_NO_FETCH,
which cache simulators can ignore.  For offline traces, raw2trace does this
for us.  Since online traces would need extra overhead to distinguish the
first from subsequent iters, they use a new internal type
TRACE_TYPE_INSTR_MAYBE_FETCH which is converted by reader_t.
Adds instr_is_string_op() and instr_is_rep_string_op() to DR's API to
facilitate this.
Adds no-fetch stats to the basic_counts tool and updates the basic_counts
tests.
Fixes #2051
=> i#2051 rep ifetch: add no-fetch entries for rep strings

clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer.h, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/common/named_pipe.h, clients/drcachesim/common/named_pipe_unix.cpp, clients/drcachesim/common/named_pipe_win.cpp, clients/drcachesim/launcher.cpp, clients/drcachesim/reader/ipc_reader.cpp, clients/drcachesim/reader/ipc_reader.h, clients/drcachesim/reader/reader.h, clients/drcachesim/tracer/tracer.cpp
Fixes a race by creating the pipe in the ipc_reader_t constructor.
Detects pipe creation errors before launching the child by augmenting the
pipe, reader, and analyzer classes with more diagnostic functionality.
Provides a more useful error message on pipe creation failure.
Closes the pipe when aborting.
Adds control-C handling to the launcher on UNIX which destroys the pipe to
avoid leaving a stale fifo behind.
Fixes #2045
Fixes #2486
Fixes #2487
=> i#2045,i#2486,i#2487: improve drcachesim pipe robustness

core/heap.c
A microbenchmark showed that make_unwritable was causing attach times to
take upwords of 56 seconds, whereas using set_protection (to avoid
excess querying of protections) reduces the time to around 1 second.
Issue #2728
=> i#2728 slow attach: Don't use make_unwritable in stack_alloc.

clients/drcachesim/common/utils.h
GCC 7 enabled -Wimplicit-fallthough and intended fall-throughs can be
annotated by gnu::fallthrough.
See
https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
=> i#2737 gcc 7: Add gnu::fallthrough

core/lib/instrument.c, core/lib/instrument_api.h, core/os_shared.h, core/synch.c, core/unix/os.c, core/utils.c, core/utils.h, core/win32/os.c
This PR adds a new function to support transfer/relocation while waiting for a contended application mutex lock.
Fixes #2725
=> i#2725 xfer under app locks: add dr_app_recurlock_lock

clients/drcachesim/CMakeLists.txt, clients/drcachesim/common/memref.h, clients/drcachesim/common/trace_entry.h, clients/drcachesim/tests/trace_invariants.cpp, clients/drcachesim/tests/trace_invariants.h, clients/drcachesim/tools/histogram_launcher.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Offline traces now guarantee that a branch target instruction entry in a
trace must immediately follow the branch instruction with no intervening
trace switch.  Because doing this during online tracing would cost extra
overhead due to the basic block-based instruction tracing, this is
implemented in raw2trace by delaying a buffer-final branch until the next
buffer for that thread.
Adds a trace_invariants tool linked into histogram_launcher where we can
add sanity checks for trace invariants like this one.
Fixes #2638
=> i#2638: avoid thread switch gaps after branches

clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp
Adds a missing instruction fetch for zero-iteration rep string loops by
moving the instruction instrumentation to the top of a rep string bb rather
than prior to the single memory reference.
The forthcoming trace_invariants continuous PC checks for #2708 will test
this.
Fixes #2011
=> i#2011 repstr ifetch: handle zero-iter loops

core/arch/arch.h, core/arch/mangle_shared.c
This patch adds a get_ABI_stack_alignment function as a
follow-up of a3ff20e. It also updates prepare_for_clean_call
to check if the stack pointer is aligned properly on all
platforms.
This is an  updated version of #2543, because I messed up the commit history in that branch.
=> i#1621 AArch64 CC opt: Add get_ABI_stack_alignment function.

README.md, api/docs/intro.dox, api/docs/tool.gendox
Adds a link to the provided tool list on the front page of the docs.
Augments the description of drcachesim in README.md.
=> Add tool list to top-level docs page

core/arch/interp.c, core/lib/instrument.c, core/unix/loader.c, core/unix/os.c, core/unix/signal.c, core/utils.c, core/vmareas.c
Reduces the size of the static library by 896 bytes.
Before:
-r-xr-xr-x 1 nilayvaish eng 2999798 Nov 23 14:03 libdynamorio.a
After:
-r-xr-xr-x 1 nilayvaish eng 2998902 Nov 23 14:33 libdynamorio.a
Issue #2717
=> i#2717 Mark some of the functions as static.

core/unix/signal.c, core/win32/events.mc
We see this error and it'd be nice to be able to more easily
differentiate when this is the failure case.
Issue #2723
=> i#2723 audit debug-asserts: use fatal error macro in signal handler.

clients/drcachesim/CMakeLists.txt, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/common/trace_entry.h, clients/drcachesim/reader/reader.cpp, clients/drcachesim/tests/drcachesim-invariants.templatex, clients/drcachesim/tests/trace_invariants.cpp, clients/drcachesim/tests/trace_invariants.h, clients/drcachesim/tools/histogram_launcher.cpp, clients/drcachesim/tracer/instru.cpp, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/instru_online.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt, suite/tests/pthreads/ptsig.c
Extends the trace_invariants test from #2638 to ensure there's no
discontinuity in control flow not indicated by a branch or a kernel xfer
marker.
Adds an online trace_invariants test.
Switches the trace_invariants test to run pthreads.ptsig on UNIX, which is
marked un-FLAKY, to test both threads and signals, and on winxfer on
Windows.
Fixes several issues found by this new test:
+ Adds TRACE_TYPE_INSTR_SYSENTER to mark the PC discontinuity from
OP_sysenter.
+ Adds proper handling of a mid-bb fault in offline trace conversion by
looking ahead after each memref to see whether there's a marker.
+ #2011 follow-up: fixes the zero-iter code from 2772b0b which it turns out
only worked for offline traces.  For online, the top-of-bb instr is
jecxz, so the instr type and size were wrong.
+ Fixes …
=> i#2708 trace discontinuity: add test, fix bugs found by test

ext/drcovlib/modules.c
Fixes a reattach-based crash where this TLS leak caused drmgr to run out
of TLS slots.
Issue #2157
=> i#2157 reattach: Unregister TLS field in drcovlib

clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
Commit 85ca26c added internal buffering for peeking and unpeeking in the
thread trace streams, but it failed to handle missing memrefs at the end of
a trace file.  We fix that here, as well as making eof checking more robust
in the presence of the buffering.
Issue: #2708
=> i#2708 trace discontinuity: allow single lookahead

tools/DRstats/DynamoRIOView.cpp
MSVC 14.12 (VS 15.5) cannot compile DrStats due to invalid C++ constructions:
- strings cannot be postfixed with a character
- local variable hides previous local declaration
- CString cannot be passed as an argument to a variadic function
Changes are compatible with Visual Studio 2013 Update 5
=> Improve C++ compatibility on Windows for DrStats project

suite/tests/CMakeLists.txt
An attempt to make Travis and Appveyor greener:
Issue #1308, #2216: marks security-common.decode-bad-stack _FLAKY.
Issue #2752: marks 32-bit api.detach_spawn _FLAKY.
Issue #2694: makes tool.histogram.offline tiny only for 32-bit Windows.
=> i#1308,i#2216,i#2752,i#2694: mark more tests as flaky

clients/drcachesim/tracer/tracer.cpp, ext/drreg/drreg.c, suite/runsuite_wrapper.pl
Fixes a drcachesim -L0_filter crash from requesting too few slots from
drreg.
Fixes drreg to abort lazy restoring at app instr boundaries for registers
in DR slots, which are not guaranteed across app instrs.
Fixes #2761
=> i#2761: fix drcachesim crash from drreg overreach

.travis.yml
Skips running OSX for pull requests for now, since the Travis queue is too
long.  We'll rely on the push to master to catch OSX issues and the dev
will have to revert or fix quickly at that point.
Issue: #2764
=> i#2764 Travis OSX: skip OSX for PR's

core/globals.h, core/lib/globals_shared.h, core/options.c
Curently the functions for setting and getting options have code for
each option generated using preprocessor macros.  This results in
excessive amount of code and increases the size of the library.  With
this commit, we alter the functions for setting and getting options.
* We define a new data type struct option_t.  This struct contains all
the information that we need to process an option.  Using macros, we
have created an array that contains the required information for each
option.
* We also define certain helper types and functions.
* The code for getting and setting options now contains a for loop in
which we go over all the options one by one.  This reduces the amount
of code by a significant amount.
This reduces the size of the static library by about 340 KB.
Issue: #2717
=> i#2717 Change the implementation of options.

clients/drcachesim/common/trace_entry.h, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/instru_online.cpp, clients/drcachesim/tracer/raw2trace.cpp
For -L0_filter on drcachesim, storing only the PC and data address is not
enough to figure out during post-processing which memref it was for a
multi-memref instruction.  Here we add a new offline entry type to store
the memref type and size and use it for multi-memref instructions where the
memrefs are different (when identical, such as for ALU operations, the
first will pass the filter and be picked in post-processing).
Fixes #2756
=> i#2756: proper handling of multi-memref instrs when filtering

CMakeLists.txt, core/link.h, core/unix/signal.c, core/unix/signal_linux.c, core/unix/signal_macos.c, core/unix/signal_private.h
This patch does two things:
- Replaces int with enum type where possible.
- Adds a compiler option "-fshort-enums" for using short enums if
possible.  This reduces the space used for storing these enum values
which results in reduction in size of the static library by 3592 bytes.
Before:
-r-xr-xr-x 1 nilayvaish eng 2778294 Nov 23 16:39
blaze-bin/third_party/dynamorio/libdynamorio.a
After:
-r-xr-xr-x 1 nilayvaish eng 2774702 Nov 23 22:22
blaze-bin/third_party/dynamorio/libdynamorio.a
Issue: #2717
=> i#2717 Shorten enums if possible.

core/globals.h, core/lib/globals_shared.h, core/options.c
This reverts commit 97fda64448161640e8dc77a8a62fb58ccfad7ac8 due to
breaking the AArch64 pre-commit, the VPS build, and changing how options
that have changed are computed.
=> Revert "i#2717 Change the implementation of options. (#2748)"

core/dynamo.c, core/os_shared.h, core/synch.c, core/unix/ksynch.h, core/unix/ksynch_macos.c, core/unix/os.c, core/win32/os.c
After 5 seconds of waiting for a thread to acknowledge a received
signal, os_thread_suspend now returns false so that the caller can
retry.
I have a unit test where there's a small chance that the thread doing detach will send the SUSPEND_SIGNAL to a newly created thread before its dcontext's `signal_field` is `fully_initialized`; the new thread discards the signal (`can_always_delay[SUSPEND_SIGNAL] == true`) and later initializes its `signal_field`, but the thread doing detach currently never retries to send the signal. So, this is kind of a workaround for a specific instance of i#26 that results in DR deadlocking on itself.
Issue: #2157
=> i#2157 re-attach: Add timeout to os_thread_suspend

CMakeLists.txt, core/link.h, core/unix/signal.c, core/unix/signal_linux.c, core/unix/signal_macos.c, core/unix/signal_private.h
This reverts commit ffbc78e74526a7bc95b0e5109cea4569986ae082 as it causes
an assert for -loglevel 3 and -tracedump_text runs.
=> Revert "i#2717 Shorten enums if possible. (#2766)"

suite/tests/CMakeLists.txt
Re-shrinks the 64-bit Windows tool.histogram.offine test as it sometimes
hangs on Appveyor just like the 32-bit version.
Issue: #2752
=> i#2752 raw2trace hang: shrink 64-bit tool.histogram.offline

api/docs/release.dox, clients/CMakeLists.txt, clients/drcachesim/CMakeLists.txt, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/tests/CMakeLists.txt, clients/drcachesim/tests/analyzer_separate.cpp, libutil/dr_frontend.h, make/DynamoRIOConfig.cmake.in, make/package.cmake, suite/tests/CMakeLists.txt
Exports a new drmemtrace_analyzer library along with all trace analysis
libraries as drmemtrace_basic_counts, drmemtrace_histogram,
drmemtrace_reuse_distance, drmemtrace_reuse_time, and drmemtrace_simulator.
Renames the drmemtrace_histogram executable to histogram_launcher to avoid
clashing with the new public library drmemtrace_ prefix.
Exports header files for building trace analysis tools and using our
provided tools in a new location tools/include/drmemtrace/.
Adds a new DynamoRIO CMake package command
use_DynamoRIO_drmemtrace() to facilitate building third-party trace
analysis tools.
Adds a new DynamoRIO CMake package command
configure_DynamoRIO_main_headers() to facilitate using just drfrontendlib
and finding dr_frontend.h, and fixes dr_frontend.h typedef issues when used
by itself. …
=> i#2006 generalize drcachesim: export drmemtrace analysis framework

api/docs/API.doxy, api/docs/CMakeLists.txt, api/docs/CMake_doxyfile.cmake, api/docs/release.dox, clients/CMakeLists.txt, clients/drcachesim/CMakeLists.txt, clients/drcachesim/analysis_tool.h, clients/drcachesim/analyzer.h, clients/drcachesim/common/memref.h, clients/drcachesim/common/trace_entry.h, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/simulator/cache_simulator_create.h, clients/drcachesim/simulator/tlb_simulator_create.h, clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tests/burst_replaceall.cpp, clients/drcachesim/tools/basic_counts_create.h, clients/drcachesim/tools/histogram_create.h, clients/drcachesim/tools/reuse_distance_create.h, clients/drcachesim/tools/reuse_time_create.h, clients/drcachesim/tracer/drmemtrace.h, clients/drcachesim/tracer/raw2trace.h, make/DynamoRIOConfig.cmake.in, make/utils.cmake
Adds doxygen docs to the exported headers in the drmemtrace framework and
includes them all in the doxygen-generated html docs.
Adds hierarchy to the html docs file list to group the drmemtrace headers
together.
Moves drmemtrace.h from ext/include/ to tools/include/drmemtrace with the
analysis tool headers and adds a new CMake function
use_DynamoRIO_drmemtrace_tracer() for finding the header.
Adds a tracer customization section to the drcachesim prose docs.
Installation tested manually and tweaked to remove superfluous drcachesim
debug files.
Issue: #2006
=> i#2006 drcachesim generalization: doxygenate drmemtrace framework

core/string.c
gcc emitted calls to this function when core/options.c was edited to
reduce the size of libdyanmorio.a.  On AArch64, the linker fails to
find this symbol elsewhere.  So we are adding it here like other
similar symbols.
=> Adds __strncat_chk function to string.c

core/win32/loader.c, core/win32/module_shared.c, core/win32/os.c
The C NULL macro (defined as ((void *)0) should be used to initialize
pointer variables to 0. MSVC++ 14.12 will report compiler warnings
when the NULL macro is used to initialize variables or parameters that
are not pointers.
=> Replace incorrect usage of macro NULL with 0 or false

core/dynamo.c
instrument_init appears to call the dr_client_main of a client; since
clients might call dr_create_client_thread in their main func, it's
important to initialize the dr_app_started variable used via
dr_create_client_thread.
Fixes #2335
=> i#2335 sig races: Init dr_app_started before clients

core/arch/arch.c
The looping code assumes that enums are signed.  As per the C standard,
this is implementation defined.  Therefore the code is being changed so
that it does not depend on the type used for the enum.
=> Changes handling of looping on enum ibl_entry_point_type_t.

core/arch/aarch64/clean_call_opt.c
This allows us to remove some unnecessary marco indentation.
=> Mark ifdef as around the file in aarch64/clean_call_opt.c

api/docs/release.dox, clients/drcachesim/tracer/instru.cpp, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/instru_online.cpp, ext/drutil/drutil.c, ext/drutil/drutil.h, suite/tests/client-interface/drutil-test.dll.c
Adds drutil_insert_get_mem_addr_ex() which returns whether the passed-in
extra scratch register was used.  Adds a test.
Leverages the new function to avoid redundant loads in drcachesim.
Issue: #2001
=> i#2001 trace perf: add drutil_insert_get_mem_addr_ex()

clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/instru_online.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp, ext/drreg/drreg.c
For offline traces for a "disp(base)" memref, only stores the base and adds
the disp in raw2trace post-processing, as it's statically known.  The base
can be directly written as it's already in a register, reducing scratch
register pressure.
Moves the second scratch register reservation into the instru_t routines so
we can skip it for this optimization of just writing the base reg for
"disp(base)" memrefs.
Issue: #2001
=> i#2001 trace perf: do not store disp

ext/drreg/drreg.c, suite/tests/client-interface/drreg-test.c
Extends the drreg test's cross-app-instr case of the same instruction
writing and reading the reserved register to include the app accessing the
register afterward.
Fixes a drreg bug exposed by this test case where a tool has reserved a
register across an app instr that both reads and writes the register: drreg
was incorrectly restoring the tool value before writing out the new app
value.
Fixes #2800
=> i#2800: fix drreg app vs tool ordering issue

core/synch.c, core/synch.h, core/utils.h, suite/tests/client-interface/timer.dll.c
Adds missing synchronization on reads of tsd->synch_perm in
thread_synch_state_no_xfer() and thread_synch_check_state(), using a
trylock to avoid hanging on a suspended thread that holds tsd->synch_lock.
On trylock failure, both routines fail, which then prevents unsafe signal
delivery.
TODO: try to create a test that reproduces the hang: it will not be easy
and if it's not reliable it's not clear how much effort to put into it...
Fixes #2805
=> i#2805: use trylock to avoid hang

clients/drcachesim/tools/histogram.h, clients/drcachesim/tools/reuse_distance.h
Remove relative paths for includes in histogram.h and reuse_distance.h.
=> Fix includes for histogram.h and reuse_distance.h

.travis.yml, suite/tests/client-interface/timer.dll.c
Fixes a Mac build issue in the new client.timer test code.
Issue: #2805
=> i#2805 synch lock hang: fix Mac test build

suite/tests/CMakeLists.txt, suite/tests/client-interface/drmgr-test.c, suite/tests/client-interface/signal.c, suite/tests/common/decode.c, suite/tests/security-common/selfmod-big.c
Fixes problems building several tests with gcc 6.x:
+ Avoids relocations for assembly code in client.drmgr-test,
client.drutil-test, client.signal, common.decode, and
security-common.selfmod-big
+ Suppresses memcpy warnings in linux.fib-static
Issue: #1958
=> i#1958 gcc 6: fix test build issues

clients/drcachesim/common/memref.h, clients/drcachesim/common/options.cpp, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/reader/reader.cpp, clients/drcachesim/tests/filter-no-d.templatex, clients/drcachesim/tests/filter-no-i.templatex, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Adds support for instruction-only and data-only filtered traces when the
-L0I_size or L0D_size is set to 0.
Fixes a bug in the reader when reading filtered traces with no instructions.
Clarifies that the guarantee about always having a data trace entry
preceded by an insruction entry for the instruction that issued the data
request does not apply to filtered traces.
Adds tests for "-L0I_size 0" and "-L0D_size 0".
Issue: #2439
=> i#2439 L0 filter: support i-only and d-only

clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/simulator/cache_stats.cpp, clients/drcachesim/simulator/cache_stats.h, clients/drcachesim/simulator/caching_device_stats.cpp, clients/drcachesim/simulator/caching_device_stats.h, clients/drcachesim/tests/warmup-valid.templatex, clients/drcachesim/tests/warmup-zeros.templatex, suite/tests/CMakeLists.txt
When reset is called on caching_device_t, save the current values of num_hits, num_misses and num_child_hits before setting them to zero. Saving the last value on reset can help determine how long (number of misses) it took for the cache to be warm. This is particularly useful when determining cache warmup by fraction loaded rather than number of accesses.
=> iX: Save caching_device_stats counters on reset

CMakeLists.txt
I am assuming here that we do not need things like exception handling
(not possible in C anyway) and backtrace().  Reduces the size of the
library by about 136,284 bytes.
Issue: #2717
=> i#2717 shrink static DR library: disable generation of .eh_frame

core/lib/instrument.c
Allows the callback to be empty when calling dr_set_itimer() with a 0 value
for the timer to disable it.
=> Allow empty callback when disabling itimer

core/unix/signal.c
This ensures that SA_RESTORER is passed to sigaction on 32-bit builds. A signal
restorer is required when vsyscall32 is disabled, which removes the default
signal restorer stub included in the vdso. Therefore, the application cannot
rely on the existence of a default signal handler, and provides one by setting
the SA_RESTORER flag.
Issue: #2812
=> i#2812 sigaction: support disabled vsyscall32

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, suite/tests/client-interface/file_io.dll.c, suite/tests/client-interface/file_io.expect
Adds a dr_vfprintf function (a slight modification of the existing dr_fprintf). This is necessary for defining printf-like functions that wrap dr_fprintf.
=> Expose a dr_vfprintf

ext/drreg/drreg.c
After restoring a no-longer-reserved register, drreg now marks it native
and gives up its slot, avoiding an extra lazy restore later.
Fixes #2814
=> i#2814: fix drreg double-restore

clients/drcachesim/tracer/instru.cpp, ext/drutil/drutil.c
Fixes a bug in the new drutil_insert_get_mem_addr_ex() feature: it wasn't
initializing the output prameter on all paths.
Issue: #2001
=> i#2001 trace perf: fix bug in drutil_insert_get_mem_addr_ex()

clients/drcachesim/CMakeLists.txt, clients/drcachesim/tests/burst_threadfilter.cpp, clients/drcachesim/tests/offline-burst_threadL0filter.templatex, clients/drcachesim/tests/offline-burst_threadfilter.templatex, clients/drcachesim/tracer/drmemtrace.h, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Adds a thread filtering feature to drcachesim, driven by a new API routine
drmemtrace_filter_threads() which decides for each thread whether to trace
it.  In the tracer, untraced threads have no trace buffer, which serves as
the flag indicating to skip instrumentation.  This flag is checked via
the same mechanism as skipping the clean call (the code is shared here as a
new utility insert_conditional_skip()), using jecxz on x86.
There are some complexities with the extra internal control for regular and
cache-filter modes where we need to insert barriers and sometimes wait for
spills we don't truly need.  The benefit is that in the end the
instrumentation is 3x faster than an approach of always filling the
per-thread buffers and filtering the threads only on i/o.
Adds two new bursty trace …
=> i#2820: trace a subset of threads

clients/drcachesim/tests/burst_threadfilter.cpp
Removes logging parameters from the burst_thread*filter tests to fix
release build suite failures.
Issue: #2820
=> i#2820 trace thread subset: fix release build test failure

suite/tests/CMakeLists.txt, suite/tests/win32/multisec.c, suite/tests/win32/multisec.template, suite/tests/win32/rebased.c, suite/tests/win32/rebased.templatex
Fixes the win32.rebased and win32.multisec tests on win8+.
These tests both try to load a separate copy of a dll by
using its 8.3 name which is mapped to the already-loaded full name in
win8+.  We add a post-build step to make a separate copy of the dll file
and load that to solve the problem.
Issue: #1432, #2835
=> i#1432 win8+ tests: fix 8.3 name load failures

core/arch/x86/x86.asm, core/dynamo.c, core/nudge.c, core/win32/ntdll.c, core/win32/ntdll.h
Since NtCreateThread returns STATUS_ACCESS_DENIED on win8+, we implement a
solution for internal nudges using NtCreateThreadEx.  We already have
support for varying who frees the stack in NUDGE_NUDGER_FREE_STACK, which
we leverage here.  The other complication is who frees the arg_buf for a
remote process (since we can't easily put it on the stack): again, we
already have NUDGE_FREE_ARG which we use here.
We also fix a bug in cleanup_and_terminate that results in a double-free of
a nudge dstack: a simple 1-byte-bool error where our asm checks all 4
bytes.  A similar asm bug found by inspection with sig_should_swap_stack()
is also fixed.
This fixes internal nudges.  Client threads and external nudges will be
fixed separately.
Issue: #1309, #1432, #2835
=> i#1309 win8+ threads: use NtCreateThreadEx for internal nudges

core/arch/x86/x86.asm, core/win32/callback.c, core/win32/ntdll.c, core/win32/ntdll.h, core/win32/os.c, core/win32/os_private.h
For client threads where we want to use our dstack yet we're forced to use
NtCreateThreadEx and its kernel-provided stack, we target a wrapper that
switches stacks and calls the client thread function.  We pass data to the
wrapper on the dstack and pass the dstack as its parameter.
Issue: #1309, #1432, #2835
=> i#1309 win8+ threads: use NtCreateThreadEx for client threads

core/win32/ntdll.c, libutil/detach.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/nudge_test.template, suite/tests/runall.cmake, suite/tests/win32/infloop.c, tools/drdeploy.c
Changes the libutil nudge code to use NtCreateThreadEx on Win8+.
For a test, enables the client.nudge_test test, part of i#120: enable
.runall tests on Windows.  Here I added a new app win32.infloop to parallel
linux.infloop, rather than launching calc.exe or notepad.exe like we did in
the past (not yet tackling systemwide injection here).  It has a MessageBox
with a title containing the pid, allowing us to use tools/closewnd with a
unique target name for a clean and race-free exit.  win32.infloop also has
a 3-minute timeout to avoid leaving stale processes behind in case of
issues closing it externally.
Revamped runall.cmake to work on Windows, using "ping" to sleep,
updating nudge and close commands, removing stale pid files, etc.
Ported suite code to use run_in_bg on Windows as well as …
=> i#1309 win8+ threads: use NtCreateThreadEx for external nudges

suite/tests/client-interface/nudge_test.template, suite/tests/win32/infloop.c
Fixes the nudge_test output to not have two "done" message that result in a
race in runall.cmake.
Issue: #1309
Fixes #2845
=> i#2845: fix racy nudge_test test output

clients/drcachesim/tests/burst_threadfilter.cpp, clients/drcachesim/tests/burst_threads.cpp, clients/drcachesim/tests/offline-burst_threadL0filter.templatex, clients/drcachesim/tests/offline-burst_threadfilter.templatex, clients/drcachesim/tests/offline-burst_threads.templatex, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt, suite/tests/runmulti.cmake
Resets callback functions to empty at exit to better support re-attach.
Unfortunately i#2175 still prevents extending the thread filter test to
include re-attach.
Issue: #2820
=> i#2820 trace thread subset: reset callbacks at exit

clients/drcachesim/simulator/analyzer_interface.cpp, clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/simulator/cache_simulator.h, clients/drcachesim/simulator/cache_simulator_create.h, clients/drcachesim/simulator/simulator.cpp, clients/drcachesim/simulator/simulator.h, clients/drcachesim/simulator/tlb_simulator.cpp, clients/drcachesim/simulator/tlb_simulator.h, clients/drcachesim/simulator/tlb_simulator_create.h, clients/drcachesim/tests/drcachesim_unit_tests.cpp, clients/drcachesim/tools/reuse_distance.cpp, clients/drcachesim/tools/reuse_distance.h, clients/drcachesim/tools/reuse_distance_create.h
For tools that have many options, passing a long list of parameters is
cumbersome, error-prone, and difficult to extend with newly added options.
We change cache_simulator, tlb_simulator, and reuse_distance to use a
struct of knobs instead.  Tools with just a couple of options are left
using parameters.
Issue: #2006
=> i#2006 generalize drcachesim: use structs of knobs

clients/drcachesim/tracer/raw2trace.cpp
The trace header refactoring in aedf9be broke post-processing of legacy
trace headers where the first timestamp precedes the first thread id.  We
fix that here.
Issue: #2843
=> i#2843 trace cpus: support legacy headers

api/docs/release.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/tracer.cpp, core/lib/dr_api.h, core/lib/instrument.c, core/lib/instrument_api.h, core/os_shared.h, core/unix/loader.c, core/unix/module.c, core/unix/module.h, core/unix/module_elf.c, core/unix/module_private.h, core/win32/loader.c
Adds a feature where a client library can request that the private loader
complain if malloc & co. are called at any time other than process init or
exit, to help clients that want to support being linked statically with the
app.
Fixes drcachesim to use placement new for its offline custom module data
allocations.
Issue: #975, #2006
=> i#975 static: add optional checks for mid-run malloc calls

core/unix/module.c, suite/tests/client-interface/memval-test.c
Fixes a Mac build error introduced by 3bc33154.
Fixes a Mac test build error that shows up on newer toolchains.
Issue: #975
=> i#975 static DR: fix Mac build

core/unix/signal.c, core/unix/signal_private.h, core/vmareas.c, core/vmareas.h, suite/tests/CMakeLists.txt, suite/tests/linux/bad-signal-stack.c, suite/tests/linux/bad-signal-stack.expect
Eliminates the memory query loop in copy_frame_to_stack() which checks
whether each part of the app stack is writable before copying over the
signal frame.  This loop grabs the global all_memory_areas lock and if that
lookup misses it goes to a maps lookup.  This has shown to cause
noticeable contention.  Instead we perform an overlap check for
is_executable_area_writable followed by a TRY_EXCEPT safe write.
Adds a new test linux.bad-signal-stack which tests this by setting up an
unwritable alternate stack.  It also tests checking for SA_ONSTACK, and we
fix #2017 here to make that work, which is needed for a good test.  The
existing security-common.decode-bad-stack hits the
is_executable_area_writable() case.
Issue: #2214
Fixes #2017
=> i#2214 signal locks: avoid memquery when copying signal frame

.appveyor.yml, .travis.yml, CMakeLists.txt, suite/runsuite.cmake, suite/runsuite_common_pre.cmake, tools/drdeploy.c
Adds support for Travis builds to produce auto-published package files.
Each job can create its own package file, using existing support in
runsuite*.cmake and package.cmake with some additions here to enable and
tweak that code.  Longer-term we may want to use package.cmake instead and
even make official builds on Travis (i#2861).
Adds Travis deployment to Github Releases of produced packages files.  The
tag is "cronbuild-${VERSION_NUMBER}": e.g., "cronbuild-7.0.17592".
Adds better support for 32-bit-only or 64-bit-only x86 package files by
naming them differently and removing the drrun warnings on incomplete
packages when missing the opposite bitwidth.
Issue: #1967
=> i#1967 cron builds: set up weekly travis builds

.appveyor.yml
Adds the proper path for our package files to be "artifacts" that can then
be deployed to GitHub Releases.
Issue: #1967
=> i#1967 cron builds: Appveyor artifacts

clients/drcachesim/tests/offline-burst_threads.templatex
Relaxes the burst_threads output further to handle non-determinism in the
test which had been causing sporadic failures.
=> Make the burst_threads test output matching less flaky

.appveyor.yml, .travis.yml, suite/runsuite.cmake
We don't want flaky tests to derail package deployment, so we disable test
running for such builds.  We've already run the tests for the same commit
via regular master-push triggers: these package builds are coming from a
cron trigger (Travis) or a tag addition (Appveyor), not a code change.
Issue: #1967
=> i#1967 cron builds: do not run tests

core/dynamo.c, core/loader_shared.c, core/unix/loader.c, core/unix/loader_android.c, core/unix/loader_linux.c, core/unix/module_elf.c, core/unix/module_private.h
Because relocating can invoke an ifunc which accesses TLS, for UNIX we move
loader_init() to after thread init.  The custom delayed init function
calling is moved back to privload finalization.  The ELF TLS block setup
for the primary thread is moved up to TLS block discovery time and is moved
to after relocation (but before init function calling).  Windows remains
unchanged as it has other ordering requirements (i#338).
Fixes #2751
Issue: #338
=> i#2751: fix crash in private lib relocs accessing TLS

core/dynamo.c, core/win32/events.mc
Previously, if we weren't able to take over all threads after a few
retries we would have a debug-level assert but otherwise continue on
with running the application. This can cause lots of correctness
problems in the application, and it would be better to cleanly crash
ahead of time rather than wait for an application crash to happen.
Issue #2723
=> i#2723 audit debug asserts: use fatal error macro in dynamorio_take_over_threads

core/unix/signal.c
In environments where there are a lot of signals being delivered to
threads of a process, there is possibly a race where one thread
links/unlinks while another is waiting to do it themselves. With this
commit, we have threads skip linking/unlinking if they notice another
thread did this (after they have obtained the change_linking_lock).
This fixes an ASSERT I'm hitting with an app:
https://github.com/DynamoRIO/dynamorio/blob/9d9129a/core/link.c#L1896
Issue #2066
=> i#2066: add double-checked locking for fragment flags.

core/unix/signal.c
As noted in the added code comment, there are points in time where it's
possible that the app_sigaction is NULL for a signal. This PR makes us
more defensive to avoid a crash on an internal unit test.
Issue #2214
=> i#2214 signal locks: verify app_sigaction is non-NULL in USE_APP_STACK.

core/unix/signal.c, suite/tests/api/static_signal.c
Removes the incorrect removal of all itimers in signal_thread_exit(), which
was disabling app itimers on detach.
Adds a test to api.static_signal.
Fixes #2871
=> i#2871: keep app itimers on detach

api/docs/release.dox, api/docs/tool.gendox
Given the time since the RC1 we're retroactively considering it to be an
official release.  The base version was bumped to 7.0 already in ad850c4.
Here we split the changelist.  Additionally I added the missing
page_drltrace page to match page_drstrace.
=> Splits the changelist: 7.0.0-RC1 is the official 7.0.0

core/unix/memcache.c, core/unix/memcache.h, core/unix/os.c, core/vmareas.c
Adds a complete maps file walk to update the memcache on re-taking-over the
process for dr_api_start.  The memcache is cleared beforehand to avoid both
false positives and negatives in later queries.  This helps to solve issues
with a gap between dr_app_setup() and dr_app_start().
Does not update the executable areas or module list: they are more
difficult to re-walk, and existing lazy updates to those will suffice for
now, with a low risk of false positives.
Adds updating of the memcache on a query miss.  Previously we would just
continue to miss and walk the maps file every time.
Tested manually by disabling the i#2114 change so that a signal does a
query, adding signals to the burst_threads test, and calling dr_app_setup()
before creating the test's threads, causing queries to miss …
=> i#2037: update memcache on re-takeover and query miss

clients/drcachesim/tests/offline-burst_threads.templatex
Allows for zero data or instruction refs on a core and thus no printed miss
rate, to reduce flakiness in the burst_threads test.
Issue: #2092
=> i#2092 burst_threads test: reduce flakiness

api/docs/release.dox, core/arch/emit_utils_shared.c, core/arch/interp.c, core/arch/mangle_shared.c, core/arch/sideline.c, core/arch/x86_code.c, core/dispatch.c, core/dynamo.c, core/fcache.c, core/fcache.h, core/globals.h, core/hotpatch.c, core/lib/instrument.c, core/lib/instrument_api.h, core/monitor.c, core/native_exec.c, core/synch.c, core/unix/os.c, core/unix/pcprofile.c, core/unix/signal.c, core/vmareas.c, core/win32/callback.c, core/win32/os.c, core/win32/os_private.h, core/win32/syscall.c, suite/tests/client-interface/timer.dll.c
Added dr_where_am_i() to better support client self-profiling via
sampling.  This also provides the fragment tag, by refactoring
the pcprofile code into a new helper fcache_refine_whereami().
Renamed the whereami types to better avoid name conflicts:
s/WHERE_xxx/DR_WHERE_xxx/ and s/where_am_i_t/dr_where_am_i_t/.
Exported the dr_where_am_i_t enum.
Fixed a bug where an uninitialized mcontext was passed to a
client timer callback: we only filled in the mcontext for a
DR-internal callback.
Added a test of client sampling to client.timer
Issue: #140
=> i#140 pcprof: add client pc sampling support

core/os_shared.h, core/unix/memcache.c, core/unix/os.c, core/unix/os_private.h
Refactors find_executable_vm_areas() to share its map entry skipping with
the re-takeover re-walk from b06a7022, but not its module list or
executable area updates.  This entry skipping for vmheap turns out to make
a big performance difference when attaching.
Removes individual updates to memcache for entries inside vmheap which were
already bulk-added for the find_executable_vm_areas() walk.
Issue: #2037
=> i#2037 re-walk-maps: refactor to share main walk with re-walk

core/unix/os.c
Fixes Mac build breakage from 8471d5cc.
Issue: #2037
=> i#2037 re-walk maps: fix Mac build

ext/drmgr/drmgr.c, ext/drreg/drreg.c, suite/tests/client-interface/drreg-test.dll.c
Adds static TLS data to support drreg routines being called during process
init before thread init has happened.
Also adds support for drmgr_current_bb_phase(), which is called by drrreg,
being called during process init.
Adds a test case to drreg-test.
Fixes #2910
=> i#2910: support drreg use during process init

suite/runsuite_wrapper.pl
This is another flaky test on ARM. See issues #2898 and #2416.
=> i#2898 sigsupend flaky: mark sigsuspend test as flaky on ARM.

api/docs/release.dox, ext/drreg/drreg.c, ext/drreg/drreg.h, suite/tests/client-interface/drreg-test.dll.c
Adds two drreg features to help support separate control flow paths such as
a slowpath and a fastpath: drreg_reservation_info_ex(), which provides
information on registers which have been unreserved but not yet lazily
restored, and drreg_statelessly_restore_app_value() which restores app
state without changing drreg state, to retain parity with a separate path.
Adds some tests of the new features.
Issue: #511
=> i#511 drreg: add separate-path state restoration features

core/unix/os.c
Fixes a regression from #2037 8471d5cc where the module re-walk hits a
deadlock lock order violation if logging is enabled.
Fixes #2934
=> i#2934: fix module re-walk lock order when logging

api/docs/release.dox, core/lib/instrument.c, ext/drreg/drreg.c, ext/drreg/drreg.h, suite/tests/client-interface/drreg-test.dll.c
Adds a query routine to identify whether an instruction is a spill or
restore generated by drreg.
Adds a sanity check test.
Issue: #511
=> i#511 drreg: add drreg_is_instr_spill_or_restore()

clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/instru_online.cpp, suite/runsuite_wrapper.pl
De-virtualized `sizeof_entry` by converting it to a field and
relying on derived classes to specify its value.
This was noticed while running an internal app under linux `perf` sampling, where `sizeof_entry` appeared as a very hot function.
=> Avoid virtual call overhead of sizeof_entry

api/docs/release.dox, clients/drcachesim/tracer/tracer.cpp, core/arch/mangle_shared.c, core/fcache.c, core/lib/instrument.c, core/lib/instrument.h, core/lib/instrument_api.h, core/synch.c, core/unix/signal.c, suite/tests/client-interface/timer.dll.c
Adds a new API routine dr_track_where_am_i() which enables tracking of
whereami for clean calls.  This is off by default for performance reasons,
which leads to clean calls being labeled initially DR_WHERE_FCACHE and then
refined into DR_WHERE_UNKNOWN.
Adds a query routine dr_is_tracking_where_am_i() for use in the tracer
where this tracking causes a short jump to not reach (#2147).
Cleans up a hole in whereami tracking to include shared context switch code
and do_syscall code along with other generated transition code as
DR_WHERE_CONTEXT_SWITCH.
Adds labeling of DR_WHERE_SIGNAL_HANDLER for at least the ksynch_wait on a
suspend signal; including other handler code is trickier and is left for
future work.
Issue: #140
=> i#140 client prof: eliminate unknown whereami instances

core/unix/signal.c, suite/tests/api/static_signal.c
Adds ignoring of alarm signals post-detach if DR has an itimer and the app
does not, to avoid crashing on a signal that arrives after detach.
Adds testing to api.static_signal but it is not easy to reproduce this
race.
Fixes #2270
=> i#2270 itimer detach: ignore alarm signals post-detach

core/arch/arch.c, core/unix/memquery_linux.c, core/unix/os.c, core/unix/os_exports.h
Adds handling of the vsyscall page not being the first page in vdso, which
happens on Fedora 27's 4.15.17 kernel.
Fixes #2945
=> i#2945: handle vsycall offset from vdso start

core/arch/aarch64/clean_call_opt.c
Break from loop in find_nzcv_spill_reg when spill register found.
Issue: #2796
=> i#2796: Add missing break in find_nzcv_spill_reg

core/arch/clean_call_opt_shared.c
Those macros are not used in the file and there is only one use of
instrlist_meta_preinsert.
Change-Id: I4c7390d6aa6fca9febd19d739f009a91e2f67c93
=> Remove unused POST and PRE defines from clean_call_opt_shared.c

core/arch/aarch64/codec.c, core/arch/aarch64/codec.txt, core/arch/aarch64/instr_create.h, suite/tests/api/dis-a64.txt, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64.expect
This patch adds encoding & decoding support for most arithmetic FP Neon
instructions. The structure of the generated macros and tests follows
the style of #2896.
codec.txt contains comments if not all encodings of an instruction are
supported yet. Also missing are the Arm v8.3-a FCADD and FCMLA
instructions, because their rotation arguments require a bit of special
handling to get nice macros.
Issue #2626
=> i#2626 fp/simd encode: Add support for most FP Neon instructions.

core/arch/arm/decode_private.h
Remove unnecessary const from op_instr extern declaration, caught by
GCC 7.3's -Wduplicate-decl-specifier.
=> Make arm/table_encode.c and decode_private.h agree on op_instr type.

core/arch/emit_utils_shared.c
The `ifdef AARCH64` is nested inside a `ifdef X86`, so it should never be true I think. I suppose it was intended to mark the code path as not implemented on AArch64.
=> Simplify Arm ifdefs slightly in emit_utils_shared.c

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, core/unix/module.c, core/unix/module.h, core/unix/module_elf.c, core/unix/module_macho.c, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
This reverts commit 8c90e2dc81eb9b9dfdcf2313bdf91b02f12c4de4 as it pushes
the module count for drcachesim offline traces beyond the limit in the
module index bitfield (#2956).
Issue: #2006, #2939, #2956.
=> Revert "i#2006 Split segments and record segment offsets (#2940)"

core/arch/arm/table_a32_pred.c, core/arch/arm/table_t32_coproc.c
- Change ARM table for vadd.f32 to use the correct decoding format for
the second source register of single precision floating point operations.
Specifically use WCd format instead of the VCd, which was wrong.
=> Fix wrong source operand decoding for SP vadd.f32

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, core/unix/module.c, core/unix/module.h, core/unix/module_elf.c, core/unix/module_macho.c, ext/drcovlib/drcovlib.h, ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
This reverts commit 48db566af975c96f984cc5060e78294ef99e0ce7 which
reverted the changes in PR #2940. The changes pushed caused some apps to
overflow the modidx field (issue #2956). PR #2969 increased the width of
the modidx field. We can now safely revert the revert.
=> Revert "Revert (#2940)"

CMakeLists.txt, clients/drcachesim/CMakeLists.txt, core/unix/os.c, suite/tests/CMakeLists.txt
Adds signed 64-bit division helper routines to complement the unsigned we
already have for the core.  The signed is needed for gcc 7.3.1 32-bit
release builds.
Disables static drmemtrace tests as a workaround for gcc 7.3.+ link errors
for 32-bit non-debug builds.
Issue #2949
Fixes #2947
=> i#2947: fix gcc 7.3.1 error missing __divdi3

clients/drcachesim/tracer/raw2trace.cpp, core/dynamo.c
Fixes drcachesim offline test failures for 32-bit release build where the
vsyscall hook is copied by unhooking in release build if a module load
event is present.
Fixes #2976
=> i#2976: avoid drcachesim vsyscall hook copying

core/arch/arch_exports.h, core/arch/interp.c, core/arch/opnd_shared.c, core/lib/dr_helper.c, suite/tests/api/dis-a64.c, suite/tests/client-interface/syscall-mod.c
For the dr_extend_type_t enum type, Clang decided that it is unsigned.
I am not sure if we can rely on Gcc to agree or how to ensure that.
=> Fix most warnings generated by Clang 5.0 on AArch64.

core/arch/x86_code.c, core/dynamo.c, core/globals.h
Addresses one init-time itimer race still in place: the initial thread's
itimer is set up prior to putting the signal handlers in place.  We delay
that here to eliminate the problematic time window.
Tested on a third-party app which crashed with SIGVTALRM 8x out of 3000
before this fix and 0x after.
Issue: #2907
=> i#2907 early itimer: delay itimer until handlers are in place

core/synch.c
Relaxes a curiosity assert triggered by 523af3ba which added further use of
DR_WHERE_SYSCALL_HANDLER.
Issue: #140
=> i#140 pcprof: relax whereami assert

core/arch/x86/decode_table.c, suite/tests/api/ir_x86_all_opc.h
Fixes the OP_vpgatherqd and OP_vpgatherqq disassembly string names which
were incorrect.
I would like to add a test to ir_all_opc.h to find string-vs-opcode
mismatches but it is not simple to do so I bailed on it here.
Fixes the encoding chains for OP_vpgather* which should all be singletons.
Issue: #2985
=> i#2985: fix OP_vpgatherqd and OP_vpgatherqq disasm strings

api/samples/syscall.c, clients/drcachesim/tracer/tracer.cpp, core/arch/mangle_shared.c, core/lib/instrument.c, core/lib/instrument_api.h, ext/drmgr/drmgr.c, ext/drmgr/drmgr.h, suite/tests/client-interface/events.dll.c
Updates DR's system call number identification to ignore more
instrumentation:
+ A meta write to the sysreg is ignored
+ Branches are ignored unless they clearly skip the sysreg write or the
syscall instr
Adds a missing syscall filter event to drmemtrace.
Adds a debug-build assert if a client has a pre- or post-syscall event but
no filter event, to help catch a common type of error.
Fixes #2991
=> i#2991: ignore more instru for DR syscall num id

core/unix/signal.c, suite/tests/common/decode-bad.c, suite/tests/tools.h
Adds translation of siginfo_t.si_addr when it's a PC.
Adds a test.
Fixes #2990
=> i#2990: translate si_addr if a PC

core/arch/x86/decode_table.c
With W0 these just produce illegal instructions.
=> Set the modrm bit on OP_vpermq and OP_vpermpd opcodes, which is interpreted as requiring vex.W

core/arch/arch.c, core/arch/arch.h, core/arch/arch_exports.h, core/unix/signal.c, core/unix/signal_private.h
Improves repeated signal interruption by relinking any prior interrupted
fragment before replacing it with a new one.  This happens when we've
guessed at what fragment to unlink when interruption is in generated code.
We add a field indicating the guess and use it to relax an assert.
We also add a new in_fcache_return() routine, used to rule out one case of
incorrect guessing.
Fixes #2328
=> i#2328: improve repeated signal interruption

core/arch/aarch64/emit_utils.c, core/arch/arch.h, core/arch/arm/instr.c, core/arch/emit_utils_shared.c, core/arch/instr.h, core/arch/x86/instr.c, core/arch/x86/mangle.c, core/unix/signal.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/cleancallsig.c, suite/tests/client-interface/cleancallsig.dll.c, suite/tests/client-interface/cleancallsig.expect
Adds handling of a signal interrupting the ibl hit path's jump, where the
target tag is not conveniently sitting in a register like it is in the rest
of the ibl.  We have to instead look at the jump's cache target and find
the fragment to unlink from there.
Also fixes up the i#2328 support for a signal interrupting
clean_call_{save,restore} to work for AArch64.
Adds a new test, client.cleancallsig, which tries to trigger both of these
cases: the client adds a lot of clean calls while the app runs a loop with
a lot of indirect branches along with an itimer.  I managed to hit each of
the new features at least once running this test in a loop on each platform
except the ibl jump on ARM and AArch64.  I left an ASSERT_NOT_TESTED for
those.
Issue: #2328
Fixes #2042
=> i#2042: signal interrupting ibl jump

core/arch/opnd_shared.c, suite/tests/CMakeLists.txt, suite/tests/api/opnd-a64.c, suite/tests/api/opnd-a64.expect
This patch also adds a file for unit tests for the APIs exported from
opnd.h: suite/tests/api/opnd-a64.c. For now it only contains tests for
reg_get_size.
It also removes a ASSERT_NOT_IMPLEMENTED from reg_get_size. All AArch64
registers should be supported, except some system registers.
=> Update reg_get_size to handle AArch64's XZR/WZR.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_2args.h
Hi, I've fixed https://github.com/DynamoRIO/dynamorio/issues/2615 by adding support for the missing ADOX and ADCX instructions. I've verified that the application I was testing and was crashing under drrun due to the missing instructions i now working correctly.
It's the first time I submit a patch, so I hope my opcode declarations are correct. I was unable to find much information on how to add new opcodes, so I mostly reverse-engineered others and studied the Intel manual. Hopefully I got it right.
=> i#2615 Added support for Intel ADX instructions

core/arch/disassemble_shared.c, core/unix/signal.c, core/unix/signal_private.h
Addresses two problems with itimer lock acquisition being split by an
alarm signal:
First, rather than a single lock for all itimers, which is subject to
races due to alarms of different types arriving in different threads
simultaneously, we switch to using a separate lock per itimer signal
type.  (We also have to handle an alarm arriving while handling an app
itimer syscall, which is why we can't just blindly block and wait for
the lock.)
Second, rather than holding a mutex to increment a counter, we switch
two different itimer counters to use atomic increments instead.  These
counters are used for new threads, and an alarm can arrive in a new
thread while it's setting up.  This avoids having a frequent time
window where an alarm splits the lock routine.
Fixes #2993
=> i#2993: avoid itimer lock splitting by alarms

core/unix/os.c, core/unix/os_private.h, core/unix/os_public.h, core/unix/signal.c
With SA_RESTART (#2659), we cannot distinguish
not-yet-executed-syscall from syscall-was-interrupted-in-the-kernel.
This doesn't matter for most syscalls, but it does matter for
sigreturn, whose asynch_target points somewhere other than right after
the syscall, so we exclude it (it can't be interrupted so we know we
haven't executed it yet).
Fixes #2995
=> i#2995: do not blindly "restart" sigreturn

core/arch/aarch64/codec.txt, core/arch/aarch64/instr_create.h, suite/tests/api/dis-a64.txt, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64.expect
This commit adds encoder/decoder support for fmov from GPRs to FPRs.
It does not add support for the variant to move a 64 bit GPR to the top
of a 128 bit register (`FMOV <Vd>.D[1], <Xn>`). I think for that variant,
we would need a way to express the top half of a 128 bit register.
Issue #2626
=> i#2626 AArch64 encoder: Add support for fmov from GPR to FPR.

core/arch/aarch64/instr_create.h, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64.expect
Instructions that take logical immediates are not encoded with shifts and the 
macros were broken for them.
Issue: #1569
=> i#1569 AArch64: Fix macros to create AND,ANDs with imms.

core/arch/aarch64/codec.txt, core/arch/aarch64/instr_create.h, suite/tests/api/dis-a64.txt, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64.expect
Some instructions, like FMLA/FMLS also read the destination register.
I think in the IR, we should have them as source registers too.
I kept the INSTR_CREATE_ macros to not have a extra source operand, as
this is closer to the AArch64 assembly syntax.
Issue: #2626
=> i#2626 AArch64 encoder: Add dst as src for instrs that read it.

core/arch/aarch64/encode.c, core/arch/arch_exports.h, core/arch/encode_shared.c, suite/tests/CMakeLists.txt, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64_negative.c, suite/tests/api/ir_aarch64_negative.expect
This patch implements instr_is_encoding_possible and encoding_possible
using encode_common, which returns ENCFAIL in case of a failure. This
is not the most efficient implementation, but we do not have encoding
tables available in the AArch64 backend.
As a test case, it includes a check to make sure the encoder rejects
some invalid combinations of FMOV.
Issue #2626
=> i#2626 AArch64 encode: Implement instr_is_encoding_possible.

core/lib/instrument_api.h, core/unix/include/siginfo.h, core/unix/nudgesig.c, core/unix/os.c, core/unix/os_private.h, core/unix/signal.c, core/unix/signal_linux.c, core/unix/signal_linux_arm.c, core/unix/signal_linux_x86.c, core/unix/signal_private.h, suite/tests/common/decode-bad.c
Fixes Mac build errors from 2 recent commits:
1) i#2990 7040ca7f added references to si_addr_lsb which are not on older
Linux kernels or Mac.  I put in our own core/unix/include/siginfo.h so
we can have the latest definition.  There is padding in the struct, so
on Linux we can blindly write to new fields and not worry about the
underlying kernel being old.
2) i#2950 e1b6a66a added struct rlimit64 references which we typedef here to
struct rlimit on Mac.
Issue: #2990, #2950
=> i#2990, i#2950: fix Mac build errors

core/arch/x86_code.c, core/dispatch.c, core/dynamo.c, core/globals.h, core/os_shared.h, core/synch.c, core/unix/os.c, core/unix/os_exports.h, core/unix/os_private.h, core/unix/signal.c, core/win32/callback.c, core/win32/os.c
Refactors signal_thread_inherit() to be called from a new routine
os_thread_init_finalize() which is invoked while holding
thread_initexit_lock yet after synch_thread_init().  This eliminates
races with suspend signals arriving in newly half-initialized threads,
which then drop the signals.  The refactoring rearranges several
thread initialization sequences to pass the clone record through
dynamo_thread_init().
This refactoring allows us to revert the os_thread_suspend timeout
from commit 972cddfa PR #2762 which added a timeout to
os_thread_suspend that turns out to not be safe on UNIX as the suspend
model assumes there is no retry.
Delays mask relaxing in handle_suspend_signal() to avoid timeout on
suspend due to an intervening signal.
Includes tweaks to an i#3020-related assert and …
=> i#2779: fix thread creation signal race

core/arch/aarch64/codec.c, core/arch/aarch64/codec.txt, suite/tests/api/dis-a64.txt
This patch adds the operands required to add indexed vector
instructions to codec.txt and adds the vector-by-element encoding of
FMLA as an example. Additional tests and macros should be added once
the script in the project-aarch64-generate-patterns branch gets updated.
Issue #2626
=> i#2626 AArch64 encoder: Add support for indexed vector instrs.

core/unix/os_private.h, core/unix/signal.c, core/unix/signal_private.h
On Mac the kernel's mid-signal-frame padding means our fixed struct's
siginfo_t location is not reliable: we have to go through the pinfo
pointer instead.  This fixes a failure in the i#2990 test on Mac.
Issue: #2990
=> i#2990 siginfo: update correct Mac siginfo

core/dynamo.c, core/globals.h, core/unix/os.c
Adds a barrier to taken-over threads creating new threads until attach
is fully finished.  This avoids problems keeping up with an app that
is creating threads while we try to attach.
Fixes #3023
=> i#3023: add new-thread barrier during attach

core/unix/signal.c
Avoids translating a new signal while suspended, as the resulting lock
acquisitions can lead to deadlock.  An incoming signal there should
always be delayable in any case: the only reason we were trying to
deliver immediately was due to a too-broad check put in for #2659.
It is not easy to create a test that reliably exercises these races:
our existing detach_spawn and other tests are the closest and this
should reduce their flakiness.
Fixes #3026
=> i#3026: do not translate new signals while suspended

core/arch/aarch64/codec.py
core/arch/aarch64/codec.py now works with Python 2 and 3.
=> Update core/arch/aarch64/codec.py to work with Python 3.

clients/drcachesim/drcachesim.dox.in
Adds documentation for several recent features geared toward core
simulator support: avoiding thread switch gaps after branches; cpu
markers; kernel xfer markers; and the raw2trace mapping interfaces.
Issue: #2638, #2843, #2708, #2006
=> i#2638 core sim: document several recent features

core/lib/statsx.h, core/string.c, core/utils.c, tools/drdeploy.c
statsx.h: String too long for buffer (50 chars)
string.c: strncmp cannot place terminating 0.
utils.c: sizeof(dst) instead of sizeof(src).
drdeploy.c: readlink is defined with restrict pointers in standard.
=> Fix some GCC 8 warnings.

ext/drgui/CMakeLists.txt
qt5_use_modules has been deprecated for a while and is not available in qt 5.11. 
The recommended workaround is to use the imported targets.
=> Remove use of deprecated qt5_use_modules.

core/globals.h, core/utils.c, suite/tests/api/static_prepop.c
This change exports the peak_num_threads stat as part of dr_stats_t so that it can be used internally as part of unit tests.
=> iX: Export GLOBAL_STAT(peak_num_threads) as in dr_stats_t

ext/drcontainers/drvector.c, suite/tests/client-interface/drcontainers-test.dll.c
If a drvector_t is initialized with zero capacity, it lazily allocates
memory on the first append invocation. If the vector is deleted before
append is called, then drvector_delete tries to free a nullptr which
shows up as an error in a DEBUG build.
=> Fix drvector_delete for zero capacity vectors.

clients/drcachesim/CMakeLists.txt, clients/drcachesim/common/options.h, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/reader/config_reader.cpp, clients/drcachesim/reader/config_reader.h, clients/drcachesim/tests/config_reader_test.cpp, clients/drcachesim/tests/single_core.conf
Currently, DRCacheSim only supports a 2-level non-inclusive cache hierarchy. For DRCacheSim to be more useful, it should be able to support a wide range of different cache hierarchy configurations. A cache hierarchy should be defined in a configuration file that is read by the analyzer. This change adds support for reading and parsing a configuration file. Support in the cache simulator will follow in the next change.
=> i#1715 Add DRCacheSim support for cache config files:

ext/drmgr/drmgr.c, ext/drwrap/drwrap.c
1) Add code to clean all resources allocated on drwrap_init
Fixes [i3049](https://github.com/DynamoRIO/dynamorio/issues/3049)
=> i#3049 bug-drwrap-exit: drwrap not clean up when exit

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, suite/tests/api/static_prepop.c, suite/tests/api/static_prepop.expect, suite/tests/api/static_signal.c, suite/tests/tools.h
Adds dr_prepopulate_indirect_targets() for filling in indirect branch
target tables to avoid trips to dispatch when attaching.
Adds a test to api.static_prepop.
Issue: #2463
=> i#2463 prepop: add indirect branch table pre-population

core/arch/aarch64/codec.txt, core/arch/aarch64/instr_create.h, suite/tests/api/dis-a64.txt, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64.expect
This commits adds the instructions from the Armv8-a
'Advanced SIMD three same' and 'Advanced SIMD three same (FP16)'
encoding groups. For the macros, all FP16 version are handled by
the macros for 'Advanced SIMD three same'
Issue #2626
=> i#2626 AArch64 encoder: Add encoding group SIMD three same & fp16

ext/droption/droption.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/option_parse.dll.cpp, suite/tests/client-interface/option_parse.expect
Get rid of the hard-code space separator and add customized separator for
droption in droption_t constructor.
Fixes #3059
=> i#3059: add customized separator for droption_t

ext/drwrap/drwrap.c
This commit is a supplement for PR #3050.
We need to clean `postcall_cache` on `drwrap_exit` as well, otherwise
post-callback (one of the arguments when calling `drwrap_wrap_ex`) will not be invoked at re-attach. This is because the registration of post-callback relies on pre-callback, and pre-callback checks postcall-cache before registering the post-callback. Stale data in `postcall_cache` prevents post-callback being registered to the hash table.
Fixes #3049
=> i#3049: clean postcall_cache when drwrap_exit

core/arch/aarch64/codec.c, core/arch/aarch64/codec.txt, core/arch/aarch64/instr_create.h, suite/tests/api/dis-a64.txt, suite/tests/api/ir_aarch64.c, suite/tests/api/ir_aarch64.expect
This patch adds support for the instructions in the Armv8-a
'Floating-point data-processing' encoding groups with 1 source.
Issue #2626
=> i#2626 AArch64 enc: Add FP data-processing instrs (1 source)

clients/drcachesim/tests/missfile-config-file.templatex
The test tool.drcachesim.missfile-config-file is flaky and this commit fixes it by relaxing the output template.
=> i#X: Fix flaky test

clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/opcode_mix.h
Eliminates the too-early destruction of raw2trace_directory_t, as we
need to reference the vdso contents later on.
Issue: #2006
=> i#2006 drcachesim: Fix use-after-free in opcode_mix tool

clients/drcachesim/reader/config_reader.cpp, clients/drcachesim/reader/config_reader.h, clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/simulator/cache_simulator.h, clients/drcachesim/tests/config_reader_test.cpp
Use std namespace qualifier for strings so that they don't cause conflicts with google internal libraries.
=> Use std namespace qualifier for strings.

clients/drcachesim/simulator/cache_simulator.h
Not necessary, plus causes header checking failures with bazel.
=> Remove unnecessary include.

clients/drcachesim/simulator/cache_simulator.cpp, clients/drcachesim/simulator/cache_simulator.h, clients/drcachesim/tests/drcachesim_unit_tests.cpp
Make sure we respect the sim_refs knob when warmup_refs and
warmup_fraction are set to defaults. Add a unit test to check.
Fixes #3069
=> i#3069 DRCachesim: Fix sim_refs regression

clients/drcachesim/CMakeLists.txt, clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/opcode_mix.h, clients/drcachesim/tools/view.cpp, clients/drcachesim/tools/view.h
The drcachesim tools opcode_mix and view depend on headers such as
raw2trace.h and raw2trace_directory.h. We update the CMakeLists.txt for
drcachesim so that they can be referenced directly instead of via
tracer/...
Issue: #2006
=> i#2006: Cleanup headers for drcachesim tools -- opcode mix and view 

core/arch/aarch64/emit_utils.c
Instead of creating unnecessary movk instructions when creating
exit stubs, we insert nops instead just before the branch. Ideally we
would just have a variable size for the exit stub fragments, but at
different places DynamoRIO expects them the be of a fixed size and the
last instruction to be a branch.
Issue #2390
=>  i#2390 ind br: Emit NOPs instead of movk reg, #0. 

make/configure.cmake.h
Fixes the Mac build which was failing on a C++ comment inside configure.h.
Issue: #2876
=> i#2876 clang-format: fix Mac build

core/win32/loader.c
Also observed experimentally on Windows 10, and correlated using [this list](https://redplait.blogspot.com/2017/02/apisetschemadll-from-windows-10-build.html).
=> win32/loader: Add another pseudo-DLL

core/dynamo.c, core/globals.h, core/synch.c, suite/tests/api/static_noclient.c
Adds support for calling dr_app_setup();dr_app_stop_and_cleanup() with
no start in between.  This is useful to use DR as a decode/encode
library when it's statically linked and also used for instrumentation,
as that setup precludes using drdecodelib, which relies on redirecting
heap allocation via name redirection.
Add a test to api.static_noclient.
Issue: #975
=> i#975 static DR: support setup;detach

core/arch/arch_exports.h, core/fragment.c, core/hashtablex.h, core/lib/instrument.c, core/unix/os.c, core/vmareas.c, suite/tests/CMakeLists.txt, suite/tests/api/ibl-stress.c, suite/tests/api/ibl-stress.expect, suite/tests/tools.c, suite/tests/tools.h
Fixes two races with shared ibt tables:
+ Adding a new table entry must write the start_pc before the tag.
This is accomplished with a new ENTRY_SET_TO_ENTRY hashtablex.h
optional specifier.  For ARM #2502 a new MEMORY_STORE_BARRIER macro
is added.
+ Resizing a table must not clear the tags in the old table to avoid
losing the tag on the target_delete ibl path.
Adds a test api.ibl-stress which uses the DR IR to synthetically
construct thousands of basic blocks with indirect branches betweent
them.
To make the test work, relaxes several is-on-stack checks to support
pre-building basic blocks (#2463) from generated code or other
locations not known prior to starting the application.
Issue: #3098, #2502, #2463
Fixes #3098
=> i#3098: fix shared ibt table races

core/CMakeLists.txt, core/arch/aarchxx/mangle.c, core/arch/decodelib.c, core/arch/instrlist.c, core/arch/mangle_shared.c, core/arch/mangle_utils.c, core/arch/x86/mangle.c, core/lib/instrument.c, suite/tests/api/drdecode_x86.c
Moves the instrlist_insert_{mov,push}_{immed_ptrsz,instr_addr}() utility
routines from instrument.c to instrlist.c for inclusion in drdecode.
Moves their first-level helpers from mangle_shared.c to a new file
mangle_utils.c.  Makes their second-level helpers inside
arch/<arch>/mangle.c exposed to drdecode.
Adds minimal tests to api.drdecode.
Fixes #3100
=> i#3100: add ptrsz immed utilities to drdecode

core/arch/x86/mangle.c
Extends the 99530cac fix to include jcc instructions, avoidingg nop
padding errors with too-long branch instructions.
Issue: #1988
=> i#1988 mpx prefixes: fix nop padding on jcc

core/arch/interp.c
For SA_RESTART, in init_build_bb() we change start_pc to
vsyscall_sysenter_displaced_pc: but we need to not do that when not
hooking vsyscall to avoid sending the app to a NULL pc.
Fixes #2674
=> i#2674: fix -sysenter_is_int80

api/docs/bt.dox
The loop in the original example misses the last instruction, and therefore may confuse.
=> Replaced the call instrlist_last(bb) with NULL in an example in api/docs/bt.dox

core/win32/loader.c
Pseudo dlls encountered on Windows Server 2012 R2 after enabling the RD Session Host server role.
Mappings can be validated [here (for WinRT-String)](http://redplait.blogspot.com/2016/07/apisetschemadll-from-windows-10-build.htmll) and [here (for thre reset)](https://redplait.blogspot.com/2017/02/apisetschemadll-from-windows-10-build.html)
=> win32/loader: Adds multiple pseudo-dlls

clients/drcachesim/common/options.cpp, clients/drcachesim/tests/burst_malloc.cpp, clients/drcachesim/tests/offline-burst_malloc.templatex
Update the dafault value of -record_heap_value to include "calloc", "operator new", and "operator delete"
Fixes #3048
=> i#3048 func-trace: update default -record_heap_value

clients/drcachesim/tracer/func_trace.cpp
If the kernel enables mechanisms like remapping sections in the module at runtime (i.e., hugepage_text, related issue #2566), the full_path of the module_data_t provided in drmgr_register_module_load_event callback could be invalid, since the original module file could already be deleted. This leads to the failure of finding PC for a particular function in memtrace func-tracing feature, given drsym_lookup_symbol depends on loading the original module file by path.
This PR is a partial fix to make function tracing feature works under scenarios like hugepage_text by using dr_get_proc_address before calling drsym_lookup_symbol. This way, we can still catch the target function if its name is in the dynamic symbol table. However, if a target function is not in the dynamic symbol table and the …
=> i#3048 func-trace: Use dr_get_proc_address to find dynsym first

clients/drcachesim/drcachesim.dox.in, clients/drcachesim/simulator/cache_stats.cpp
Do not write misses triggered by HW prefetchers into miss files.
=> Disable writing misses triggered by HW prefetches

clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, suite/runsuite_wrapper.pl
Summarize instr_t to decouple trace conversion from DR internals (e.g. instru_t APIs)
As added benefit, the previous APIs were not inlined (at least by clang), being in a different module. That was resulting in noticeable (under perf profiling) function call overhead. This change alleviates that.
Issue: #3129
=> i#3129 raw2trace perf: summarize instr_t during raw2trace conversion

clients/drcachesim/CMakeLists.txt, core/CMakeLists.txt, core/arch/instr.h, core/arch/opnd.h, core/lib/dr_helper.c, core/unix/module_elf.c, libutil/CMakeLists.txt
Adds "#ifndef NOT_DYNAMORIO_CORE_PROPER" around the two option
references in module_elf.c in order to remove the problematic drdecode
dependence from drfrontendlib.  (The drhelper library added in the
past already removed the dynamorio_syscall dependence for us.)
Adds disabling of inlining from instr.h and opnd.h for drhelper who
just wants to include globals.h, to avoid pulling in extra deps.
Issue: #1409
=> i#1409 core libs: eliminate drdecode dependence from drfrontendlib

core/CMakeLists.txt
Fixes 32-bit gcc7.3 build breakage from 4ac94411 by adding
__x86.get_pc_thunk.bp to the globalize_pc_thunks list.
Issue: #2006
=> i#2006 drcachesim: fix 32-bit gcc7.3 build

suite/runsuite_wrapper.pl
Adds the 32-bit gbop-test to the flaky list.
Issue: #2972
=> i#2972 gbop-test: mark 32-bit gbop-test flaky

api/docs/release.dox, clients/drcachesim/tests/raw2trace-simple.templatex, clients/drcachesim/tests/raw2trace_io.cpp, clients/drcachesim/tracer/drmemtrace.h, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
Added thread start checking/validation APIs, and a related, general-purpose API for fetching out the timestamp out of a raw trace.
Issue: #3129
=> i#3129 raw2trace perf: raw trace header inspection APIs

clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
This moves the code we plan to factor out as part of a reusable template to raw2trace.h. The code isn't modified, except:
-  the "CHECK" macro used in raw2trace.cpp was copied to the header and renamed "DR_CHECK", to avoid collisions. The code moved to the header uses DR_CHECK instead of CHECK. This macro is undefined as soon as it's not used anymore.
-  FAULT_INTERRUPTED_BB and INVALID_THREAD_ID became static const members of raw2trace_t instead of macros, to avoid adding macros to the header file.
Issue: #3129
=> i#3129 raw2trace perf: move reusable code to header

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, core/unix/injector.c, core/win32/os.c, suite/tests/CMakeLists.txt, suite/tests/client-interface/abort.dll.c, suite/tests/runcode.cmake
Adds a mechanism to exit immediately with no cleanup and also set an exit
code.  dr_exit_process() can set a code, but always cleans up and thus
cannot be called during process init.
Adds a test using a new script runcode.cmake to check the exit code.
=> Add dr_abort_with_code()

.appveyor.yml
Updates Appveyor to download WinFIG75.zip as the old version no longer
exists.
=> Update Appveyor WinFig version

clients/drcachesim/tests/raw2trace-simple.templatex, clients/drcachesim/tests/raw2trace_io.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
We avoid holding on to global state past module_mapper_t construction. However, we need to remember the custom free_cb callback, if provided, as it will be needed when ~module_mapper_t is called.
Issue #3129
=> i#3129 raw2trace perf: ensure module_mapper_t calls custom data free callback

clients/drcachesim/tracer/raw2trace.h
The operator is implicitly deleted because a member (cached_user_free) is a const pointer.
Issue: #3129
=> i#3129 raw2trace perf: remove module_mapper_t move assignment operator

clients/drcachesim/tracer/raw2trace.h
The move ctors for trace_converter_t and module_mapper_t should be public.
Issue: #3129
=> i#3129 raw2trace perf: move ctors should be public

clients/drcachesim/tracer/raw2trace.h
The code handling interrupted basic blocks assumed serial processing of thread buffers. If the thread buffers are processed in parallel, it might be the last `offline_entry_t` in a buffer was a memref. We can't look past it to see if the BB was interrupted.
The CL leverages the currently-made assumption that a faulting memref will not have its signal/exception marker split into the next buffer, so if this memref is the last one there can be no interruption.
Issue: #3129
=> i#3129 raw2trace perf: handling interrupted basic blocks

core/unix/signal.c
Incorporated maintainer's suggestion of properly handling CPU hardware with no AVX support into the `core/unix/signal.c` during `signal_main_init()`, specifically Intel iCore2.
Fixes issue #3159.
=> #3159 ASSERT unix/signal.c pend_unit_size does not have AVX_ALIGNMENT on processor without AVX Bug-Assert

clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tests/raw2trace_io.cpp, clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/view.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, suite/runsuite_wrapper.pl
module_mapper_t should have move semantics, but simply relying on
default ctors/assignment operands isn't enough: we also need to clear
the originating object, otherwise the destructor would free resources
twice; and the assignment operator would have to figure out what to
do with the original resources.
We don't need an overly-complicated design, and there's very little
value to be gained from module_mapper_t being stack-allocatable. This
CL hides constructors and instead offers a static API that returns a
unique pointer.
Issue: #3129
=> i#3129 raw2trace perf: simplify module_mapper_t lifetime management

clients/drcachesim/CMakeLists.txt, make/DynamoRIOConfig.cmake.in
Disables opcode_mix_launcher on Mac due to static DR not being
supported there yet (#1997).
Fixes #3165
=> i#3165: Fix Mac build breakage from opcode_mix_launcher

core/arch/x86_code.c, core/dynamo.c, core/unix/os.c, core/unix/os_exports.h, core/unix/os_private.h, core/unix/signal.c
Go's thread creation looks at the SYS_clone stack parameter
post-syscall, which DR was not restoring after replacing it with the
dstack.  We fix that here.
That bug led to Go programs using the dstack, resulting in them
executing DR memory, where DR tried to raise an artificial SIGSEGV.
However, this ended up in Go's signal handler where SIGSEGV was
blocked, and due to various #196 checks lining up incorrectly, this
led to an infinite loop.
To fully fix the infinite loop and get the SIGSEGV to the outer lever,
I changed os_forge_exception() to set SI_KERNEL and added a forged
flag into execute_default_action() and avoid trying to call
decode_sizeof() there (just crashes b/c SIGSEGV handler removed).  I
alo cleared the app's signal mask, to avoid SIGSEGV being blocked
during cleanup, …
=> i#3171: fix hang running Go programs

core/unix/signal.c, suite/tests/linux/signal-base.h, suite/tests/linux/sigplain-base.h
Updates the signal mask stored in each signal frame delivered to the
app to properly contain the app's interrupted mask.
Adds tests that DR is doing the right thing with the mask across
signal delivery.
Issue: #3177
=> i#3177 sigstate: update sigmask in app frame

core/unix/signal.c, suite/tests/linux/signal-base.h, suite/tests/linux/sigplain-base.h
Updates the alternate signal stack stored in each signal frame delivered to the
app to properly contain the app's alternate stack.
Restores DR's mask and altstack prior to executing SYS_sigreturn as
part of handling the app's sigreturn (that's the simplest way to
restore non-GPR state).
Adds tests that DR is doing the right thing with the stack across signal delivery.
Fixes #3177
=> i#3177 sigstate: update altstack in app frame

clients/drcachesim/tests/burst_threads.cpp, core/synch.c, core/unix/signal.c
Fixes a signal state initialization issue for attaching versus initial
control where a pre-existing signal alternate stack was getting thrown
away.
Adds a test case to tool.drcacheoff.burst_threads.
Fixes #3116
=> i#3116: app sigaltstack thrown away when attaching

core/unix/os.c, core/unix/os_private.h, core/unix/signal.c, suite/tests/linux/bad-signal-stack.c, suite/tests/linux/signal-base.h, suite/tests/linux/sigplain-base.h
Adds proper error checking for the various ways that the kernel fails
the SYS_sigaltstack system call.  Adds tests of each error case.
Fixes #3178
=> i#3178: proper sigaltstack error checking

core/unix/signal.c
A NULL app_sigaction was observed once in handle_sigreturn.  It is not
clear how it happened: otherwise I would add a test.  For now we add a
defensive check.
Fixes #3182
=> i#3182: check for NULL sigaction in handle_sigreturn

core/lib/instrument.c
SETO sets the LSB, not the MSB.
=> Fix a comment in dr_restore_arith_flags_from_reg

clients/drcachesim/tools/opcode_mix.cpp
The return type of process_memref is bool. One return statement was the empty string. Fixing this avoids special-case build flags.
Fixes #3198
=> i#3198 opcode_mix_t::proces_memref: return bool instead of string

core/unix/signal.c, suite/runsuite_wrapper.pl
Fixes Mac build breakage from 49ee6922 #196.
Fixes Mac test failures from 036900c4 #3177: an assert was added that
should be disabled on Mac where the kernel does not restore the alt
stack from the frame.
Adds ignore rules for still-broken tests for #3127.
Issue: #3127, #196, #3177
=> Fix Mac Travis breakage

core/unix/loader.c, core/unix/memquery.c, core/unix/memquery.h, core/unix/memquery_linux.c, core/unix/os.c, core/unix/os_exports.h
Use get_dynamorio_library_path() instead of DYNAMORIO_LIBRARY_NAME in Linux memquery.
Fixes #3201
=> i#3201: In non-static/Linux, read library name from maps instead of using hard-coded name.

suite/runsuite_wrapper.pl
Runs ctest with -VV on Appveyor so that developers can see the details
of build warnings.  It's pretty common for a developer to not have
Visual Studio access and for a C++ code change to hit a VS-specific
compiler warning.  We'll live with the minor pain of having to
download the results due to their size.
=> Increase Appveyor verbosity

core/arch/instr.h, core/arch/instr_shared.c, core/unix/native_elf.c
Partial fix for native -> non-native re-takeover. Fix look-up for _dl_fixup by searching for first CALL instruction. IAT style dll call re-takeover is tested in common.nativeexec. Minor logging fixes.
Issue: #2868
=> i#2868 test failures: partial fix mix-native

suite/tests/CMakeLists.txt
In native executable to DR controlled dll takeover test, we need PLT stubs to work. This is adding no-pie option for these tests, as some newer unix distrubutions enable pie/pic by default.
Issue: #2868
=> i#2868 pie/pic for native takeover: force plt stubs

clients/drcachesim/tests/miss_analyzer.templatex, clients/drcachesim/tests/stride_benchmark.cpp, suite/tests/CMakeLists.txt
Adds a microbenchmark to test the newly added LLC miss analyzer.
=> i#3203: Add a microbenchmark to test the cache miss analyzer

suite/tests/CMakeLists.txt
pcache tests don't properly seem to handle ET_DYN executables. See i#3233.
Issue: #2868
=> i#2868: Adding -no-pie to pcache tests: fix segfault

api/docs/release.dox, ext/drcontainers/hashtable.c, ext/drcontainers/hashtable.h, suite/tests/client-interface/drcontainers-test.dll.c
Extends hashtable_apply_to_all_payloads() by proposing an additional function hashtable_apply_to_all_payloads_user_data(), which makes user data available when iterating over payloads.
This pull request also contains tests.
=> Extends hashtable_apply_to_all_payloads

suite/tests/CMakeLists.txt
Disables checklevel option for release build regression.
Fixes #2868
=> i#2868 test failures: checklevel only in debug

core/synch.c
If an alarm is received by a thread after it has blocked in
check_wait_at_safe_spot but before the detaching thread sends the
SUSPEND_SIGNAL, it is possible the fcache_unit_areas lock is being held in
record_pending_signal when the SUSPEND_SIGNAL is received. Since the
receiving thread was already marked as waiting at a safe spot, we
synchronize with the thread and detach it, and the fcache_unit_areas
lock is never unlocked.
Issue: #2270
=> i#2270 itimer detach: Remove alarm handlers before synching with threads.

ext/drmgr/drmgr.h
s/dr_register_thread_event_exit/dr_register_thread_exit_event/
Just noticed this comment typo while browsing the code: the former does not exist.
=> Fix incorrect comment

ext/drcontainers/hashtable.c
hash_key previously raced with hashtable resizing in
hashtable_check_for_resize, leading to possibly incorrect executions
of hashtable operations during resize. Now we require holding the
hashtable lock (if relevant) during hash_key.
Fixes #3252
=> i#3252 hashtable race: hold the lock during hash_key

core/dynamo.c
For re-attach, DR's statistics were accumulating each time.  We now
zero them out at exit time, but only when detaching to avoid an
unnecessary performance hit from zeroing out this large structure.
Fixes #2964
=> i#2964: reset statistics on detach to avoid accumulating

make/policies.cmake
CMP0020 is not needed for cmake > 2.8.11, neither are we importing Qt5Core.
Fixes #1418
=> i#1418: Remove unnecessary CMP0020 policy

core/translate.c
Downstream clients can asynchronously request translation of pc addresses in the fragment cache. A strict assertion of a different thread context causes tests to fail in debug mode. Here we relax the assertion to an ASSERT_CURIOSITY.
=> Relax the assertion in recreate_app_state_from_ilist

ext/drcontainers/hashtable.c, ext/drmgr/drmgr.c
Works around a parsing problem in VS2013 where a variable cannot be
declared after an if() with no braces on its body by adding braces to
some recent code changes.
=> Cleanup: VS2013 problematic variable declarations from recent changes

libutil/CMakeLists.txt, libutil/config.h, libutil/detach.c, libutil/dr_config.c, libutil/processes.c, libutil/processes.h, libutil/utils.c, libutil/utils.h
Removes core/ from the include dirs for libutil, to simplify using
drfrontendlib with drcontainers at the same time without hitting a
conflict between drcontainers/hashtable.h and core/hashtable.h.
=> Cleanup: simplify libutil/ include dirs

api/docs/release.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/common/options.cpp, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tests/raw2trace_io.cpp, clients/drcachesim/tools/histogram_launcher.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, clients/drcachesim/tracer/raw2trace_directory.cpp, clients/drcachesim/tracer/raw2trace_directory.h, clients/drcachesim/tracer/raw2trace_launcher.cpp, suite/tests/CMakeLists.txt
Refactors raw2trace to produce a separate trace file per thread rather
than interleaving them into a single file.  The file_reader now does
the interleaving.  As part of the refactoring, per-traced-thread data
is isolated in a data structure which is passed to each processing
routine.  This will make it easier to parallelize in the future.
Changes raw2trace_directory_t to produce a vector of output files, one
per input file.  It puts them in a trace/ subdir that is a peer of the
input raw/ subdir by default.
Deprecates the drcachesim front-end -infile but still supports it for
legacy traces.  Updates analyzer_multi's input code to
auto-post-process the raw files if there no processed files in a
trace/ subdirectory.
Updates the changelog, documentation, and intra-repository uses of …
=> i#3230 split traces: generate per-thread processed trace files

api/docs/intro.dox, api/docs/release.dox, core/dynamo.c, core/heap.c
Disables 32-bit-displacement reachability constraints for DR's heap
when operating in standalone mode.  There is no need for it, as
there's no code cache where generating absolute references is costly.
This removes the 2GB memory limit from tools using DR standalone mode.
Updates the docs to mention this change.
Fixes #3296
=> i#3296: Eliminate 32-bit-heap-reachability in standalone mode

suite/tests/client-interface/drreg-test.c
Add ARM/AArch64 support for 3rd DR spill slot test6 in drreg-test.
Fixes #3303
=> i#3303: add and fix ARM/AArch64 support for drreg-test6

api/docs/release.dox, clients/drcachesim/analysis_tool.h, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer.h, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/tests/burst_replace.cpp, clients/drcachesim/tests/raw2trace_io.cpp, clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/opcode_mix.h, clients/drcachesim/tools/view.cpp, clients/drcachesim/tools/view.h, clients/drcachesim/tracer/raw2trace_directory.cpp, clients/drcachesim/tracer/raw2trace_directory.h, clients/drcachesim/tracer/raw2trace_launcher.cpp
Adds a separate analysis_tool_t::initialize() method to better handle
tool initialization that can fail, separating it out from the
constructor.  This simplifies subclassing as well.
Updates the view_t and opcode_mix_t tools to move their module mapping
and other code into initialize().  Leaves updating the simulator tools
for future work.
Changes raw2trace_directory_t to return error strings instead of
aborting the process, and splits its constructor from new initialize()
and initialize_module_file() methods.
Fixes #3106
=> i#3106: add analysis_tool_t::initialize()

clients/drcachesim/analysis_tool.h, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/opcode_mix.h, clients/drcachesim/tools/view.cpp, clients/drcachesim/tools/view.h
Changes analysis_tool_t::initialize() to directly return an error
string, to simplify the interface.
Issue: #3106
=> i#3106 tool init: analysis_tool_t::initialize returns error

core/arch/x86/decode.c
Fixes #3324 by initialising _opcode_ field of _di_ in _read_instruction_.
Without this fix, a usage error is caused when inserting cmov instructions.
=> i#3324: Fixed use of uninitialised data caused by read_instruction.

api/docs/release.dox, clients/drcachesim/CMakeLists.txt, clients/drcachesim/analysis_tool.h, clients/drcachesim/analyzer.cpp, clients/drcachesim/analyzer.h, clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/tools/basic_counts.cpp, clients/drcachesim/tools/basic_counts.h, clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/opcode_mix.h, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
Adds support for analyzing traces in parallel, concurrently operating on each
traced thread.  This is made possible by the new storage of traces in separate
per-thread files.
Adds a new analysis_tool_t interface where if the tool's
parallel_shard_supported() returns true, analyzer_t switches to a parallel
operation mode.  Today, a simple static scheduling among worker threads is used.
Each worker completely owns one or more shards, eliminating the need for
synchronization when processing a shard's trace entries.  The default shard is
today's trace file split, a traced thread.
A tool's parallel_shard_init() function is invoked to create shard-thread-local
data, which is passed to parallel_shard_memref().  Errors are also shard-local
with parallel_shard_error().  A parallel_shard_exit() is …
=> i#3230 split traces: add parallel trace analysis support

suite/tests/client-interface/mangle_suspend-shared.h, suite/tests/client-interface/mangle_suspend.c
Limits the runtime of client.mangle_suspend test and adds sched_yield to wait loops.
Fixes #3333
=> i#3333: cut runtime of client.mangle_suspend.

clients/drcachesim/tools/basic_counts.cpp, clients/drcachesim/tools/basic_counts.h, clients/drcachesim/tools/opcode_mix.cpp, clients/drcachesim/tools/opcode_mix.h
Adds missing synchronization for adding new per-shard data to the
global map of such data in the basic_counts and opcode_mix tools.
Issue: #3230
=> i#3230 split traces: add lock for shard data map

.travis.yml
We give up for now on sending email to dynamorio-devs and restore the
defaults of just the committer and author's github emails.
Issue: #3031, #3340
=> i#3031 travis emails: restore defaults

.travis.yml
Sending to the dynamorio-devs email list does in fact seem to be
working so we restore that setting.
Issue: #3340
Fixes #3031
=> i#3031 travis emails: send to devs list (again)

core/vmareas.c
Removes the lock acquisition from check_in_last_thread_vm_area to
avoid deadlock.  The scenario we're trying to catch will read and
match with no extra lock due to the bb building lock.
It would be nice to have a test but it is not easy to write due to the
race that needs to be arranged.
Issue: #3346
=> i#3346 trace exit: avoid deadlock in check_in_last_thread_vm_area

core/arch/arch_exports.h
Add clobber flags directives to inline asm statements of atomic operations. Prevents compiler from moving flag modifying operations in between atomic and reading flags.
Issue might still exist in Windows where _Interlocked intrinsics are used.
Issue: #3352
=> i#3352 atomics and flags: clobber flags in inline asm of atomic operations

core/arch/emit_utils_shared.c, core/unix/signal.c, core/unix/tls.h, core/unix/tls_linux_aarchxx.c, core/unix/tls_linux_x86.c, core/unix/tls_macos.c
Adds work-arounds for an AMD processor bug where the processor does
not clear the hidden gs base when the gs selector is written.  Pre-4.7
Linux kernels leave the prior thread's base in place on a switch due
to this.  When we attach and receive SIGUSR2 in a new thread, we can
thus get the wrong dcontext; worse, we can get NULL in the handler but
the wrong dcontext later during init.
To solve the problem on attach, we check the tid for threads receiving
a takeover signal.  For incorrect tid cases or unknown threads we set
a non-zero "pre-init" value (the kernel ignores zero) in the gs base.
We have to be careful to not clobber the valid gs base value of a
temporarily-native thread whose magic field was deliberately set to
invalid.
On detach, we now set a non-zero value rather than zero in …
=> i#3356: work around AMD gs base context switch bug

core/unix/os.c, core/win32/events.mc
We rely on knowing the bounds of the DR library code in order to
correctly detect our special tags for sending the code back to native
while DR is enabled (e.g. detach routines), even when compiled
statically. Reporting this failure early seems better than failing at
detach time for some mysterious reason.
Issue: #2723
=> i#2723 release asserts: require DR's "DLL" bounds to be known.

core/unix/os.c, core/unix/os_private.h, core/unix/signal.c
Fixes an asynch signal arriving late when thread is on its way to exit by blocking all signals during exit. This is ok if because we're at the app's thread_exit system call. When doing a detach, the app's signal mask is restored before going native. For terminate events using kill, we are not blocking the kill signal. Suspend signal is also excluded because a detaching thread may try to synchronize with an exiting thread and as long as the signal is getting delivered to this thread, we need to reply to it from the signal handler.
Adds support to the signal handler for an asynch signal arriving in the middle of a clone system call or temporarily-native thread, while the spawning thread's tls magic sentinel is invalid. We're now detecting this condition in the signal handler by making …
=> i#2921: support asynch signal in late exit and when interrupting a clone syscall

core/synch.c, core/unix/os.c
If a thread is short-lived during take over, it may look like a native thread at consecutive multiple take over attempts. This happens if its thread record will already be deleted. This patch adds a wait loop to yield to exiting threads.
Add assertions to the synch_with_all_threads barrier for no exiting threads at the end of the synch.
Minor re-naming of variable to make its meaning more clear.
Fixes #2694
=> i#2694: wait for short-lived exiting thread during take over

clients/drcachesim/reader/compressed_file_reader.cpp
Fixes a failure to free a boolean array when using
compressed_file_reader_t.
=> Fix leak in compressed_file_reader_t

core/unix/signal.c
Fix a regression introduced in edb2eed6b74646dcf92718675ad2ec9a3fe2b674. If a thread is on its way to exit, the app's sigstack may be restored already. Relax the master_signal_handler assertion accordingly.
Fixes #3369
=> i#3369: relax sigstack assertion in signal handler if thread is at late-exit

core/CMakeLists.txt, core/arch/x86/memfuncs.asm, core/arch/x86/x86_shared.asm, libutil/CMakeLists.txt
Core DR's copies of memset and memcpy were placed into drhelper to
avoid glibc-versioned symbols in our shipped binaries (#1504).
They are linked into the static drfrontendlib and drinjectlib
libraries.  They are also in core DR when built as a static library.
In these static library cases they can conflict with symbols of the
same name elsewhere in the linking application.
To solve this, we first separate memset and memcpy from drhelper into
their own library, drmemfuncs.  We simply avoid linking it into static
core DR, and into drdecode.  For static core DR we assume that
whatever versions the application or glibc provides will be
re-entrant.
We can't avoid linking it into drfrontendlib and drinjectlib (we hit
the glibc versioning problem), but we reduce the chance of conflicts
with …
=> i#3315: avoid conflicts with memset and memcpy

.travis.yml, core/arch/asm_defines.asm, core/arch/x86/memfuncs.asm
Turns WEAK into a nop in asm files as the nasm assembler has no
support for weak symbols, so we live with potential conflicts on Mac.
Temporarily runs Mac on PR builds to ensure this fixes Mac on Travis
(tested locally and it does fix it there).
Issue: #3315
=> i#3315 memcpy conflict: fix Mac build

core/arch/x86/memfuncs.asm
Marks the _-memcpy_check and __memset_chk aliases as weak to further
help avoid conflicts with static linking.
Issue: #3315
=> i#3315 memcpy conflict: mark _check aliases as weak

libutil/dr_frontend_win.c
Fixes an incorrect return value given for SymLoadModuleExW, which is
used by drfront_fetch_module_symbols().  The error caused 64-bit
symbol loading to fail.
=> Fix incorrect symbol load return value in drfrontendlib

api/docs/release.dox, libutil/dr_frontend.h, libutil/dr_frontend_common.c, libutil/dr_frontend_private.h, libutil/dr_frontend_win.c, suite/tests/libutil/frontend_test.c, suite/tests/libutil/frontend_test.template
For investigating symbol fetching errors, it is useful to be able to
obtain verbose diagnostics from the drfrontendlib routines.  Here we add
drfront_set_verbose() to programmatically enable them.
=> Add configurable diagnostics to drfrontendlib

libutil/dr_frontend_win.c
Adds the same workaround for an older dbghelp with newer headers that is
already used in drsyms: we use a compatibility struct size for
SymGetModuleInfoW64().
Issue: #1376
=> i#1376 VS2013: Handle older dbghelp in drfront_fetch_module_symbols()

core/arch/opnd_shared.c
As commented by @egrimley in [#3381](https://github.com/DynamoRIO/dynamorio/issues/3381#issuecomment-467357845) and [#3382](https://github.com/DynamoRIO/dynamorio/pull/3382#issuecomment-467355775), this patch is required in order to build DynamoRIO with GCC7.
He commented that *"That bug should be fixed in any case. I thought it had been."*. So, I don't know if this patch is already present in some other branch that has not been merged yet.
Anyway, I know that the commit message is not correct, but I don't know the motivation for the change. Indeed, I neither know whether it should be specific to GCC 7. Therefore, I am opening this issue to let the CI tools check it agains other versions.
=> fix: opnd_shared.c

core/arch/arch.c, core/arch/instr.h, core/nudge.c
Changes get_ibl_routine_name() to avoid using IF_X86_64() for braces
and an extra dimension in a static array, which was causing
clang-format to fail to parse the file and incorrectly indent several
hundred subsequent lines.
Fixes indentation errors after #endif in instr.h and nudge.c.
Fixes #3407
Fixes #3158
=> i#3407: Work around clang-format parsing errors

core/arch/arch.c
Test api.detach_spawn exposes a race during takeover, where a native thread that hadn't been taken over yet follows the vsyscall hook in the vdso page, and our post-syscall code assuming valid TLS causing a crash.
Issue: #2694
=> i#2694 vsyscall hook: Add XXX comment to describe bug.

core/CMakeLists.txt, core/CMake_finalize_static_lib.cmake, core/CMake_readelf.cmake, core/CMake_symbol_check.cmake, suite/tests/CMakeLists.txt, suite/tests/api/static_symbols.c, suite/tests/api/static_symbols.expect
Adds a new dynamorio_static_nohide library which is only built when
tests are built.  It is used for sanity checks on global symbol names
for better interoperability with toolchains where objcopy
--localize-hidden is a pain point.
Renames core/CMake_globalize_pic_thunks.cmake to
core/CMake_finalize_static_lib.cmake to better reflect the multiple
steps it is taking beyond just the thunks.
Adds a new test api.static_symbols of linking dynamorio_static_nohide.
Adds a new post-build step that runs a new script
CMake_symbol_check.cmake which looks for likely-to-conflict symbols in
dynamorio_static_nohide.
Issue: #3348
=> i#3348 sym conflicts: support not hiding symbols in static DR lib

core/drlibc/drlibc.c
Adds a weak d_r_strncmp in drlibc to fix a Mac link error in non-core
uses of drlibc.
Issue: #3348
=> i#3348 sym conflicts: fix Mac drlibc link error

api/docs/release.dox, core/lib/instrument.c, core/lib/instrument_api.h, core/win32/os.c, core/win32/os_exports.h, suite/tests/client-interface/events.dll.c
Adds new fields to the exported dr_os_version_info_t which contain the
build number, edition, and Windows 10 release identifier.  Adds code to
retrieve them.  The release identifier is used to create an OS name string
and downgrade the warning about an unsupported OS version to a simple
informational message, since we expect a new Windows 10 release to work,
barring hooks blocking dynamic system call analysis or deeper problematic
changes.
Adds a sanity check that the build number and edition are successfully
acquired.
=> Retrieve the Windows build number, edition, and release identifier.

core/drlibc/drlibc_unix.c, core/dynamo.c, core/os_shared.h, core/unix/loader.c, core/unix/os.c, core/unix/os_exports.h
Since we want a single build of drlibc for both static and shared DR
libs, we do not want any STATIC_LIBRARY defines in there.  Here we
remove the define in os_page_size_init() by adding a parameter
"env_followed_by_auxv" and a function
"is_our_environ_followed_by_auxv()" and effectively moving the
STATIC_LIBRARY to the callers.
This fixes a regression for #2122 caused by creating drlibc in
710a6898.
Issue: #1409, #2122
=> i#1409 core libs: remove STATIC_LIBRARY from drlibc

third_party/libgcc/README.dynamorio, third_party/libgcc/arm/lib1funcs.S
Build fails with error `undefined symbol: GLOBAL DEFAULT UND __aeabi_ldivmod` on ARM with GCC 7.
Issue: #3399 
Fixes #2901
---
I have successfully tested this fix on a PYNQ board and on a APM X-Gene 2 server (in arm32v7 and arm64v8 docker containers).
Note that the patch proposed by @TomSie in [#2901](https://github.com/DynamoRIO/dynamorio/issues/2901#issuecomment-429337486) is not included here. It seems to be specific to armv6, but I don't have any such device to test. Therefore I don't know whether it is ok to close #2901 with this PR.
=> i#2901: Fix undefined L_aeabi_ldivmod

core/unix/os.c, core/unix/os_private.h, core/unix/signal_linux.c, suite/tests/linux/syscall_pwait.cpp, suite/tests/linux/syscall_pwait.template
This patch adds support to the emulation of ppoll, epoll_pwait and pselect6 system calls to perform no sigmask manipulation if NULL is passed.
Adds subtests to linux.syscall_pwait for above. It also adds minor changes to print upper case letters in test output.
Fixes #3425
=> i#3425: Fix handling NULL sigmask parameter in ppoll, epoll_pwait and pselect6.

core/CMakeLists.txt, core/arch/arch_exports.h, core/lib/memmove.c, core/string.c
Adds a memmove implementation to drmemfuncs to avoid an import when
the compiler generates a call to memmove in the rare cases it cannot
prove that memcpy is safe.
Issue: #3315
=> i#3315 memfuncs: Add memmove to drmemfuncs

core/CMakeLists.txt
The module_{elf,macho}.c files are part of drlibc but 710a689 failed
to remove them from the UNIX drinjectlib source list.  We do that here.
Issue: #1409
=> i#1409 core libs: remove module files from unix drinjectlib

core/unix/injector.c
Issue: #3381
Issue: #3399
Signed-off-by: Unai Martinez-Corral <unai.martinezcorral@ehu.eus>
---
Building on `armv7l` or `armv8l` fails with:
``` bash
[ 64%] Building C object core/CMakeFiles/drinjectlib.dir/config.c.o
/dynamorio/core/unix/injector.c:866:50: error: 'PTRACE_GETFPXREGS' undeclared here (not in a function)
{ PTRACE_GETFPXREGS, "PTRACE_GETFPXREGS" },
^~~~~~~~~~~~~~~~~
/dynamorio/core/unix/injector.c:867:50: error: 'PTRACE_SETFPXREGS' undeclared here (not in a function)
{ PTRACE_SETFPXREGS, "PTRACE_SETFPXREGS" },
^~~~~~~~~~~~~~~~~
make[2]: *** [core/CMakeFiles/drinjectlib.dir/unix/injector.c.o] Error 1
```
This PR avoids using `PTRACE_GETFPXREGS` and `PTRACE_SETFPXREGS` on `ARM`, as it is currently done on `AARCH64`.
=> Do not reference PTRACE_{G,S}ETFPXREGS when undefined

api/docs/release.dox, core/arch/aarch64/clean_call_opt.c, core/arch/aarch64/proc.c, core/arch/aarchxx/mangle.c, core/arch/arch.c, core/arch/arch.h, core/arch/arm/proc.c, core/arch/clean_call_opt_shared.c, core/arch/proc.h, core/arch/x86/clean_call_opt.c, core/arch/x86/mangle.c, core/arch/x86/proc.c, core/lib/instrument.c, core/unix/signal_linux_x86.c, core/unix/signal_macos.c, core/win32/callback.c, core/win32/inject.c, core/win32/ntdll.c, suite/tests/api/opnd-a64.c, suite/tests/client-interface/cleancall-opt-1.dll.c, suite/tests/client-interface/cleancall-opt-shared.h
This patch takes the next step towards migrating all of DynamoRIO's context switching to support AVX-512. The function proc_num_simd_saved_abs() is introduced that returns the total number of SIMD registers on a given processor and OS. In the future, this number may be different from proc_num_simd_saved() that returns the number of SIMD registers that are actually saved by DynamoRIO and may be optimized. MCXT_NUM_SIMD_SLOTS is now the static number of slots in DynamoRIO's mcontext, regardless of what processor and OS actually support.
Issue: #1312
=> i#1312 AVX-512 support: Add proc_num_simd_saved_abs() and replace MCXT_NUM_SIMD_SLOTS.

core/CMakeLists.txt
Adds a dependence on the generated event headers to drmemfuncs to fix
a build race.
Issue: #3315
Fixes #3437
=> i#3437: Add generated header dependence to drmemfuncs

core/heap.c
Fixes a bug where special heap units use an offset size for subsequent
units, resulting in wasted space as they leak a little bit onto an
additionally allocated page.
Adds ASSERTs on page alignment and confirmed that they show up in our
tests without this fix.
Fixes #1439
=> i#1439: Fix un-aligned special heap unit sizes

core/dynamo.c
We do not want AVX-512 instructions in DynamoRIO itself. This way, DynamoRIO remains portable and also avoids unintended frequency scaling of the processor when running applications that itself don't contain AVX-512 code.
Issues: #1312, #3169
=> i#1312 AVX-512 support: Add a compile error for AVX-512 in DynamoRIO's core.

core/unix/memquery.c
Previously we must have been getting lucky most of the time. I suspect
this will fix any number of low-frequency bugs which are triggered by
incorrect memory bounds discovery (e.g. hang on static detach, or
debug-level complaints about memory bound mismatches).
Fixes #3444
=> i#3444 uninit memory: correctly 0-terminate 'dst' in memquery_library_bounds_by_iterator

core/arch/emit_utils_shared.c, core/optionsx.h, core/perscache.c, suite/tests/CMakeLists.txt
Makes the following 4 changes, fixing 3 different failures in the
client.pcache-use test:
+ Raises the client.pcache.dll preferred base to be above the default
vmm on 64-bit Linux.  THe test relies on this library being at its
preferred base.
+ Changes the default -vm_base on Linux to be slightly lower,
0x3f000000 instead of 0x46000000, to avoid colliding with the
preferred addresses we typically use in the 0x7xxx0000 range with
the new 512M -vm_size default.
+ Fixes a crash by passing the proper at_map=false when freezing
coarse units into pcaches.
+ Augments coarse_cti_is_intra_fragment() to distinguish an
intra-fragment cti which targets the final instruction in its
fragment which was a jump that was elided from a true exit cti.
Fixes #3442
Fixes #1032
=> i#3442: Fix 3 different client.pcache-use test failures

core/win32/loader.c
Adds new API set mappings for win10-1809.  This includes fixing some
formerly-incorrect mappings such as API-MS-Win-Core-CRT-L1.
Patch from PR #3206 by William Woodruff.
Issue: #3391
=> i#3391 win10-1809: Add new API set mappings

core/arch/x86/x86_asm_defines.asm, core/drlibc/drlibc_x86.asm, suite/tests/CMakeLists.txt, suite/tests/win32/dotnet.cs, suite/tests/win32/dotnet.expect
On recent Windows versions, the loader changes the start address of
the initial thread's CONTEXT.  However, for late injection, DR had
already cached the address to the value set by the kernel, which
crashes.  We solve that by updating the start address register when we
run our takeover code.
Adds a .NET test to the suite.
Fixes #3046
=> i#3046: Fix .NET start address problems

core/CMakeLists.txt, core/CMake_symbol_check.cmake
Work around a Binutils bug that causes a warning to STDERR in version 2.30. Both earlier
and later Binutils versions seem to be fine. Binutils bug #24382 has been filed.
Fixes #3450
=> i#3450: Ignore readelf errors for 32-bit release build and Binutils 2.30.

.travis.yml, make/cpp2asm_support.cmake
Switches Travis to Xenial and now defaults to gcc 5.
Adds the -mno-warn-deprecated flag in ARM cross-compiler build to all modules, due to
the ARM assembler of Xenial's cross compiler causing this warning for .asm files other
than just tests.
Fixes #3456
=> i#3456: Switches Travis to Xenial.

clients/drcachesim/tracer/instru.cpp
Adds disassembly of the culprit instruction when instrumentation of
its memory addressing fails, so we can easily tell whether it's from
VSIB or some other factor.
Issue: #2985
=> i#2985 VSIB addrs: Add drcachesim diagnostic on address failure

clients/drcachesim/tests/stride_benchmark.cpp
Cuts down runtime of the drcachesim.miss_analyzer test by cutting down the number of
the main loop's iterations as well as the array size in the test.
Fixes #3485
=> i#3485: Cut down runtime of tool.drcachesim.miss_analyzer.

suite/tests/client-interface/cleancall-opt-shared.h
Fixes xmm/ymm size in shared dump function of cleancall tests.
Fixes #3483
=> i#3483: Minor fix swapped xmm/ymm size in cleancall tests.

core/win32/inject.c
Changes a buffer increment from hardcoded number of bytes into term with YMM_REG_SIZE.
This can be more easily changed to ZMM_REG_SIZE when widening to AVX-512.
Issue: #1312
=> i#1312 AVX-512 support: Make Windows simd buffer increment more general.

core/unix/signal_macos.c
Fixes MacOS build. The ymm structure in mcontext name was changed into simd.
Issue: #1312
=> i#1312 AVX-512 support: Fix MacOS build.

api/docs/release.dox, core/arch/arch.h, core/arch/arch_exports.h, core/arch/x86/x86.asm, core/arch/x86_code_test.c, core/lib/globals_shared.h
Adds function get_opmask_caller_saved() that saves 16-bit AVX-512 OpMask registers to a
buffer. It still lacks support for AVX512BW, which will save 64-bit registers.
Adds a test for get_opmask_caller_saved().
Adds the define MCXT_NUM_OPMASK_SLOTS that will also be used for a future structure in
DynamoRIO's mcontext.
Adds a missing release note that dr_zmm_t was added and adds release notes for this patch.
Issue: #1312
=> i#1312 AVX-512 support: Add get_opmask_caller_saved() function.

api/docs/release.dox, core/lib/globals_shared.h
Amends commit 851a961e2d0bedb9254025ba95 with doxygen links and fixes a documentation bug
for MCXT_NUM_OPMASK_SLOTS.
Issue: #1312
=> i#1312 AVX-512 support: Fix API comment and doxygen links.

ext/drcovlib/modules.c, suite/tests/client-interface/drmodtrack-test.dll.cpp
Adds freeing of drmodtrack custom user allocations on parsing errors.
Previously, we would leak the memory.
Adds a test to drmodtrack-test.  Confirmed that without this fix the
test fails.
Fixes #3314
=> i#3314: Free drmodtrack user memory on parsing errors

core/arch/arm/encode.c, core/arch/x86/encode.c
For AVX-512, we will be adding DR_REG_ZMM0 - DR_REG_ZMM31 registers. We are planning not
to add the compatibility REG_ versions. This patch changes the only internal use of
REG_ that will also require the ZMM versions to using the DR_REG_ enums instead.
Issue: #1312
=> i#1312 AVX-512 support: Partially change REG_ into DR_REG_ in encode.

core/optionsx.h
Updates the -cache_commit_increment option which was accidentally a
"uint" to be a "uint_size" option, so we can specify K and M prefixes
for much easier use.
=> Change -cache_commit_increment to uint_size to accept prefixes

api/docs/release.dox, core/lib/mcxtx.h
Provides a union with ymm field in addition to simd for backward compatibility. The name
was changed in f9c8364fe41752979788a35d.
Issue: #1312
=> i#1312 AVX-512 support: Provide ymm field in mcontext.

suite/tests/CMakeLists.txt
Make common.flags test independent of architecture in RUN_IN_RELEASE set of tests.
Fixes #3479
=> i#3479: Fix RUN_IN_RELEASE set of tests for AArch64.

api/docs/release.dox, clients/drcov/drcov.c, ext/drcovlib/drcovlib.c, ext/drcovlib/drcovlib.h
This PR adds an optional `-logprefix` command line toggle to the `drcov` tool. 
By default, `drcov` will prefix log files with 'drcov', eg `drcov.ls.57735.0000.proc.log`. The addition of this command line option allows users to change the prefix to a string of their choosing. This can be used to build a clear relationship between which invocation produced which log file.
A growing number of DynamoRIO users have been integrating `drcov` into their fuzzing and instrumentation workflows. A common nuisance among these users is that there isn't a great way for a fuzz harness (or anything) that wraps `drcov` to specify an output filename for the coverage log.
As a result, it can be difficult to correlate which fuzzed input testcase generated which log after the fact with any certainty. 
``` …
```
=> Adds optional '-logprefix' command line option to drcov

core/arch/x86/decode_table.c, suite/tests/api/ir_x86_4args.h
The memory operand of vinserti128 is, unsurprisingly, 128 bits wide.
=> Make the xmm/mem operand of vinserti128 the correct size (16 bytes).

suite/tests/CMakeLists.txt
Moves the assignment of RUN_IN_RELEASE label to the "torun" function in order to make
it independent from architecture and other flags. 'drcachesim', 'drcacheoff' and 'common'
tests have been added. This is a slight increase over the previous RUN_IN_RELEASE list,
as now all 'common' tests are part of this label.
Fixes #3479
=> i#3479: Move RUN_IN_RELEASE labeling to test lists.

clients/drcachesim/tools/histogram.cpp, clients/drcachesim/tools/histogram.h
Adds parallel analysis support to the histogram tool.
I see a 4x speedup or so in small tests.
Issue: #3230
=> i#3230 split traces: parallelize the histogram tool

core/arch/emit_utils_shared.c, core/options.c, core/optionsx.h, core/unix/os.c
Enables SELFPROT_GENCODE as the default -protect_mask for UNIX and for
STATIC_LIBRARY.
Fixes two problems that were blocking that:
+ Adds temporary unprotection for update_syscalls().
+ Fixes change_protection() to preserve +x (by delegating to make_{un,}writable()).
Issue: #3522
=> i#3522 unix self-prot: Enable SELFPROT_GENCODE for UNIX and static

core/arch/x86/x86.asm, core/unix/os.c
When creating client threads, we still attempted to invalidate the thread's TLS by writing
a null selector to its segment register. In 64-bit mode, this seemed to work most of the
time because presumably Intel and AMD are then zero'ing out the the hidden segment's
base. Intel doesn't precisely describe this in Vol. 3A 3.4.4.
This patch applies the same scheme introduced and described in #2089.
Before this patch, the test code_api|client.thread ran into all kinds of assertions,
because the client thread interfered with the parent's TLS. These failures are now gone.
Fixes #3526
Issue: #2089
=> i#3526: Apply scheme of i#2089 to client threads.

core/unix/os.c, core/unix/os_exports.h, core/unix/tls.h, core/unix/tls_macos.c, make/configure.cmake.h
For 64-bit MacOS, there is no way to set the %fs base which stops
us from using DR's scheme used on other unix platforms. This commit
provides initial support to MacOS 64-bit by stealing a TLS slot
from the app for DR's TLS base.
+ implement is_thread_tls_initialized for MacOS 64-bit
+ implement tls_thread_init and tls_thread_free
+ set MACOS64 define in cmake script
+ add WRITE_TLS_SLOT_IMM etc. for MacOS 64-bit
+ add read_thread_register for MacOS 64-bit to get pthread_t base
Issue: #1979
=> i#1568: add initial support for TLS on MacOS 64-bit (#2293)

core/arch/arch.c, core/fcache.c, core/heap.c, core/heap.h, core/perscache.c, core/unix/loader_android.c, core/unix/loader_linux.c, core/unix/os.c, core/win32/os.c
Changes the heap_mmap(), heap_mmap_reserve(), and
heap_mmap_reserve_post_stack() functions to take in the protection
bits to use, instead of hardcoding +rwx.
Removes the +x from several mmaps used for TLS segments.
Issue: #1132
=> i#1132 split vmcode: Remove +x from TLS memory

core/win32/os.c
Suppresses a recently-added (in fae84d175) syslog about running on a
new, potentially unsupported Windows 10 version when in standalone
mode.  Also fixes a bug where this syslog was printed even on older
Windows 10 versions.
=> Suppress unknown OS version print for standalone mode

clients/drcachesim/analyzer.cpp, clients/drcachesim/reader/snappy_file_reader.cpp, clients/drcachesim/tests/offline-snappy-serial.templatex, suite/tests/CMakeLists.txt
When using -indir and a serial tool, check if the trace directory has
.sz files. If so, use snappy_reader_t to read them.
This wasn't an issue for the gzip reader, because we default to using it
without looking at file names.
TESTED: added a test.
Fixes #3351
=> i#3351 snappy: Use snappy reader for serial tools.

core/dynamo.c
Optimizers could still ignore this information, and in particular
post-link optimizers will not even see this attribute in their input
binary in the first place. Those scenarios would need their own
optimizer-specific solution.
Fixes #3549
=> i#3549 static inlining: set NOINLINE on DR stopping points.

core/arch/arch.c, core/arch/decodelib.c, core/arch/instr_shared.c, core/fcache.c, core/heap.c, core/heap.h, core/lib/instrument.c, core/monitor.c, core/options.c, core/optionsx.h, core/perscache.c, core/unix/memquery_emulate.c, core/unix/module.c, core/unix/os.c, core/utils.c, core/vmareas.c, suite/tests/CMakeLists.txt
Splits the VMM-managed memory into two pieces: "vmcode" which is
guaranteed 32-bit-displacement-reachable, and "vmheap" which has no
such guarantees.
Adds a new option -vmheap_size to control the size of vmheap.  The
placement is left to the OS, rather than DR trying to do ASLR, as
modern OS's have their own ASLR.
Changes which_vmm_t to a bitmask and adds a flag VMM_REACHABLE so
callers can specify which region to use.  Adds the flag to all
appropriate call sites.
Implements the -reachable_heap option: when on, only vmcode is used
and there is no 2nd region.
Adds heap_reachable_{alloc,free} and use for
dr_{global,thread}_{alloc,free}.  Adds local and global reachable heap
units to implement this.  Adds storage of the type of heap inside
thread_units_t and heap_unit_t.  Places both types …
=> i#1132 split vmcode: Separate vmcode from vmheap

.travis.yml, core/unix/os.c
Fixes a Mac build caused by 99fd6ce.
Enables Mac builds on pull requests.
Issue: #1132, #2764
=> i#1132 split vmcode: Fix Mac build

core/arch/proc.h, core/arch/x86/decode.c, core/arch/x86/decode_fast.c, core/arch/x86/decode_table.c, core/arch/x86/encode.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, core/arch/x86/optimize.c, core/arch/x86/proc.c, core/options.c, core/optionsx.h, core/unix/memquery_linux.c, core/unix/os.c, make/configure.cmake.h
Removes all old stale code for x86 emulation on Itanium which has not been touched in 10+ years and is unlikely to ever be used again.
Fixes #3563
=> i#3563: Drop support for IA32_ON_IA64.

core/arch/x86/decode_table.c
Pre-requisite for AVX-512 opmask instructions. This renames existing float K* types
into F*. Future K* names will be used for k register types.
Issue: #1312
=> i#1312 AVX-512 support: Rename K float types into F.

core/arch/arch.c, core/arch/opnd.h
Certain DR_REG_ enums are used as type opnd_size_t in x86. This patch restores an
assertion to ensure these enums fit into a byte. The affected DR_REG_ enums are
available in combination with a type and template_optype_is_reg is used to identify them.
Fixes #3567
=> i#3567: Restore check for 8-bit register enum size.

core/arch/disassemble_shared.c
Prints the negative hex number instead of the raw displacement for att syntax as it does
for intel syntax. 'objdump' seems to print it the same way.
Issue: #3574
=> i#3574 x86 dec/enc tests: Print two-complement neg displacement.

suite/tests/api/dis-udis86-randtest.license
Adds missing attribution for the dis-udis86-randtest.raw binary test
file which came from the Udis86 project.
=> Add attribution for dis-udis86-randtest.raw test file

core/arch/x86/disassemble.c, suite/tests/api/ir_x86.c
Add missing TYPE_K_REG to operand disassembler.
Fixes #3579
Issue: #1312
=> i#3579 AVX-512 support: Add missing K type to disassembler.

clients/drcachesim/simulator/cache_simulator.cpp
This change fixes a leak which occurs if we fail to initialize the last level cache. Adding the pointer to the all_caches map ensures that the destructor frees the appropriate memory that has been allocated.
=> Fix leak which occurs if the LLC init fails

suite/tests/CMakeLists.txt, suite/tests/api/static_maps_mixup_novars.templatex
Currently this just causes some CIs to ignore failures in this test.
Xref i#2204 for having ctest actually re-run these tests.
Issue: #3538, #2204
=> i#3538 flaky maps mixup: mark static_maps_mixup_novars as FLAKY

core/arch/x86/decode.c, core/arch/x86/decode_private.h, core/arch/x86/decode_table.c
Adds a read_evex function to decoder.
Prepares a switch table for bound instruction and EVEX prefix.
Issue: #1312
=> i#1312 AVX-512 support: Add read_evex function to decoder.

core/arch/x86/decode.c, core/arch/x86/decode_private.h, core/arch/x86/decode_table.c
In order to prepare for evex decode and encode, this renames vex_ext to e_vex_ext.
The evex extensions will be added to the vex_extensions tables.
Isuse: #1312
=> i#1312 AVX-512 support: Re-factor and rename vex_ext to e_vex_ext.

api/docs/intro.dox, api/docs/release.dox, core/drlibc/drlibc_module_elf.c, core/drlibc/drlibc_unix.c, core/heap.c, core/heap.h, core/optionsx.h, core/unix/loader.c, core/unix/memcache.c, core/unix/os.c, core/utils.c, core/utils.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/alloc.dll.c
Adds new VMM capabilities to reserve memory at a specific address for
a file mapping and uses it to load client libs and anything else that
requires reachability inside the vmcode region.
Fixes two unmap failures which now show up as memory leaks with the
VMM managing the space:
+ The inter-segment gaps were not being unmapped.
+ The .bss separation page was not being unmapped.
Makes -vm_size, the size of the vmcode region, 1G by default on UNIX.
We do not go all the way to 2G because that causes -vm_base_near_app
to always fail, which results in always having to mangle rip-relative
accesses and corresponding increased overhead.
Leaves Windows vmcode size and library location unchanged, due to
complexities in placing file mappings inside the region (see the issue
for details).
Increases …
=> i#3570 large vmcode: Load clients inside 1G vmcode on UNIX

core/arch/x86/decode_private.h, core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86.c, suite/tests/api/ir_x86_3args_avx512_evex_mask.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds OP_vmovdqu8, OP_vmovdqu16, OP_vmovdqu32, OP_vmovdqu64, OP_vmovdqa32,
OP_vmovdqa64, OP_vmovss, OP_vmovsd.
Issue: #1312
=> i#1312 AVX-512 support: Add vmovdqu[8|16|32|64], vmovdqa[32|64], vmovss, vmosd.

core/arch/arch.c, core/arch/emit_utils_shared.c, core/arch/interp.c, core/arch/x86/emit_utils.c, core/arch/x86/mangle.c, core/emit.c, core/fcache.c, core/heap.c, core/heap.h, core/options.c, core/optionsx.h, core/os_shared.h, core/unix/include/syscall_linux_x86.h, core/unix/loader_linux.c, core/unix/os.c, core/vmareas.c, core/win32/events.mc, core/win32/os.c, suite/tests/CMakeLists.txt
Adds a new option -satisfy_w_xor_x and implements it for Linux.  It
uses a dual-map approach to satisfy write-xor-execute security
policies.  A writable shadow is created for the vmcode region, while
vmcode itself is read-only.  A constant offset is then used to
translate between writable and executable addresses.
The dual mapping uses memfd_create if available, falling back to shm
if not, for the file backing.  The scheme relies on a single large,
now-separated-from-vmheap vmcode in order to have a single mirrored
region.  If vmcode is left as the default 1G size, the scheme simply
fails if vmcode runs out of space: the user must request 2G up front
(with corresponding loss of -vm_base_near_app: see #3570) for such a
huge application.
Generated code and the code cache store executable …
=> i#3566 w^x: Add -satisfy_w_xor_x for Linux

core/heap.c, core/unix/os.c
Adds a workaround for the large latency from IMA hashing our entire
-vm_size vmcode region: it computes the hash just once, so we
temporarily map our memfd while it's tiny before we set the size.
This is not guaranteed to work for future IMA implementations,
however.
Issue: #3566
=> i#3566 w^x: Work around IMA overhead

suite/tests/client-interface/reachability.dll.c
The client.reachability test was using dr_raw_mem_alloc() but
dr_nonheap_free().
=> Fix incorrect free routine in client.reachability test

core/arch/x86/decode_private.h, core/arch/x86/encode.c, suite/tests/CMakeLists.txt
Adds proper handling of encoding an instr_t immed to a copy.
Adds a test: client.reachability with -satisfy_w_xor_x.
Issue: #3556
Fixes #3615
=> i#3615: Handle copy!=final when encoding instr_t immed

core/arch/emit_utils_shared.c, core/arch/interp.c, core/arch/mangle_shared.c, core/dynamo.c, core/heap.c, core/heap.h, core/lib/instrument.c, core/monitor.c, core/optionsx.h, suite/tests/CMakeLists.txt
Adds W^X-aware handling of several generated code cases missed in the
original implementation:
+ mangle_syscall_code()
+ shift_ctis_in_fragment()
Adds best-effort handling of fork (there is still a race, and
potentially noticeable overhead).
Adds a fix for the proper heap type when extending reachable heap
units (which showed up as a trace encoding bug).
Adds a usage error when using dr_nonheap_alloc() with +wx memory,
which we do not support with W^X.
Changes the single -satisfy_w_xor_x test into a cross-cutting option
set, expanding into multiple tests to cover more behavior.  To include
drcachesim tests here, a new test feature _self_serial is added which
adds dependences for copies of the same test run under different
options.
Issue: #3556
=> i#3556 w^x: Handle fork and fix trace and signal bugs

core/arch/decode.h, core/arch/decode_shared.c, core/arch/x86/decode.c, core/arch/x86/decode_private.h, core/arch/x86/decode_table.c, core/arch/x86/encode.c, core/arch/x86/instr_create.h, suite/tests/api/ir_x86_2args_avx512_evex.h, suite/tests/api/ir_x86_3args_avx512_evex.h, suite/tests/api/ir_x86_3args_avx512_evex_mask.h
Adds the evex form of instructions vmovsldup, vmovddup, vmovhps, vmovhpd, vmovshdup.
Adds the new subreg type OPSZ_half_16_vex32_evex64 for AVX-512.
Adds the decoder flag and check for EVEX.LL.
Adds tests for instructions above.
Issue: #1312
=> i#1312 AVX-512 support: Add instructions vmovlpd, vmovsldup, vmovhps, vmovhpd, vmovshdup.

core/arch/x86/decode.c
Adds a check for a repne prefix on *any* branch to avoid a spurious
"spurious rep/repne prefix" message on MPX-marked branches.
Fixes #1978
=> i#1978: Suppress spurious "spurious rep" message

core/arch/x86/decode.c, core/arch/x86/decode_table.c, core/arch/x86/encode.c, core/arch/x86/instr_create.h, suite/tests/api/ir_x86_2args_avx512_evex.h, suite/tests/api/ir_x86_3args_avx512_evex.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the evex instructions vunpcklps, vunpcklpd, vunpckhps, vunpckhpd, vcvtss2si,
vcvtsd2si, vcvtsi2ss, vcvtsi2sd, vcvttss2si, vcvttsd2si, vmovntps, vmovntpd, vcomiss,
vcomisd, vucomiss, vucomisd.
Adds to decoding support of evex type 'H' and type 'L'.
Issue: #1312
=> i#1312 AVX-512 support: Add evex promoted vunpck* and vcvt* opcodes w/ OPSZ_16 operands.

core/arch/x86/decode.c, core/arch/x86/encode.c
Fixes EVEX decoder and inverted logic for V'. Rountrips do not test this kind of
bug. More thorough testing will be added through disassembler tests once more
instructions have been enabled.
Issue: #1312
=> i#1312 AVX-512 support: Bugfix, EVEX.V' is bit inverted.

core/arch/x86/decode_fast.c, core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, suite/tests/api/dis-x64.expect, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the opcodes vaddps, vaddpd, vaddss, vaddsd, vsubps, vsubpd, vsubss, vsubsd, vpaddb,
vpaddw, vpaddd, vpaddq, vpsubb, vpsubw, vpsubd, vpsubq, vpaddusb, vpaddusw, vpaddsb,
vpaddsw, vpsubusb, vpsubusw, vpsubsb, vpsubsw, vpmaddwd, vpmaddubsw.
Fixes a bug detecting an implied escape byte in combination with evex prefix in fast
decoder.
Issues: #1312
=> i#1312 AVX-512 support: Add evex-encoded v(p|h)add* and v(p|h)sub* opcodes.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the opcodes vmulps, vmulpd, vmulss, vmulsd, vpmullw, vpmulld, vpmullq, vpmuldq,
vpmulhw, vpmulhuw, vpmuludq, vpmulhrsw.
The opcode vpmullq is new in AVX-512.
Note that this fixes a bug where the evex rows were missing from prefix extension 25
in the decode tables. The remaining prefix extensions have been inspected and found
to be ok.
Issue: #1312
=> i#1312 AVX-512 support: Add evex-encoded v(p)mul* opcodes.

clients/drcachesim/simulator/cache_stats.cpp, clients/drcachesim/simulator/cache_stats.h, clients/drcachesim/simulator/caching_device.cpp, clients/drcachesim/simulator/caching_device_stats.cpp, clients/drcachesim/simulator/caching_device_stats.h
Add the tag of the replaced cache block in the cache stats interface. This would allow us to perform analyses on replaced cache blocks by extending the cache_stats_t class. Example of useful analyses: fraction of blocks that never get accessed while in the cache.
=> Add the tag of the replaced cache block in the cache stats interface

core/arch/x86/decode_table.c, suite/tests/api/ir_x86_3args.h, suite/tests/api/ir_x86_3args_avx.h
Submission 738842b missed to fix some of the convert opcodes.
Issue: #1312
=> i#1312 AVX-512 support: Fix AVX vcvtss2sd, vcvtsd2ss's destination in decode table.

core/arch/x86/disassemble.c
Adds missing type exposed by mulx in api.ir.
Fixes #3635
=> i#3635: Add missing TYPE_VAR_REGX to diassemble noimplicit operands.

core/arch/x86/decode.c, core/win32/events.mc, suite/tests/api/ir_x86.expect, suite/tests/api/ir_x86.templatex
Adds a SYSLOG warning if the decoder recognizes an evex encoding until i#1312
will be completed and AVX-512 is fully supported.
Issue: #1312
=> i#1312 AVX-512 support: Add SYSLOG warning when evex prefix is encountered.

core/arch/disassemble_shared.c, suite/tests/api/ir_x86.c
Changes disassembler according to the following styles:
Intel:
<opcode> dst {k1}, src0, src1
At&t:
<opcode> src0, src1, dst {k1}
DynamoRIO:
<opcode> k1 src0 src1 -> dst
Issue: #1312
=> i#1312 AVX-512 support: Print evex mask more suitable to every disassembler style.

api/docs/release.dox, clients/drcachesim/simulator/cache_stats.cpp, clients/drcachesim/simulator/cache_stats.h, clients/drcachesim/simulator/caching_device.cpp, clients/drcachesim/simulator/caching_device_stats.cpp, clients/drcachesim/simulator/caching_device_stats.h, clients/drcachesim/simulator/tlb.cpp
Passes a pointer to the accessed (hit) or replaced (miss) cache block to the cache stats accessor This is a follow up to PR #3637.
=> Pass a pointer to the accessed or replaced cache block to the cache stats accessor

.travis.yml, CMakeLists.txt, api/docs/release.dox
Adds a missing release note describing a compatibility breakage by adding a new field to
instr_t by commit 42a33b33920f7bf1d1.
Bumps the minor version number to 7.91.
Issue: #1312
Fixes #3642
=> i#1312 AVX-512 support: Add release note about instr_t compatibility breakage.

core/arch/x86/decode_table.c
Fixes several W1 bit bugs found by comparing api.ir verbose output to capstone,
gas/binutils and llvm-mc.
Issue: #1312
=> i#1312 AVX-512 support: Fix missing W1 bits, AVX-512 instructions.

make/cpp2asm_support.cmake
Fix to properly locate ml/ml64.exe on windows, thus dynamorio can be built with nmake or jom
=> bring back nmake support for windows (VisualStudio 2013 update 5 build tools)

suite/tests/CMakeLists.txt
When building with UNIX makefiles, the dependencies are not automatically detected unless
header dependencies are explicitly added. This patch adds the new AVX-512 headers that
were missing.
Issue: #1312
=> i#1312 AVX-512 support: Add missing dependencies for build with UNIX makefiles.

core/heap.c, core/heap.h, core/unix/os.c, core/vmareas.c, core/vmareas.h, suite/tests/CMakeLists.txt
Changes how fork is handled to avoid races.  Now the parent makes an
anonymous private temporary copy of vmcode pre-fork, freeing it
post-fork.  The child sets up its new mappings from the temporary
copy, avoiding any issues with copying the parent's live data.
Adds a sanity fork regression test.
Issue: #3556
=> i#3556 w^x: Handle fork races

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the evex-promoted opcodes vfmadd132ps, vfmadd132pd, vfmadd213ps, vfmadd213pd,
vfmadd231ps, vfmadd231pd, vfmadd132ss, vfmadd132sd, vfmadd213ss, vfmadd213sd, vfmadd231ss,
vfmadd231sd, vfmaddsub132ps, vfmaddsub132pd, vfmaddsub213ps, vfmaddsub213pd,
vfmaddsub231ps, vfmaddsub231pd, vfmsubadd132ps, vfmsubadd132pd, vfmsubadd213ps,
vfmsubadd213pd, vfmsubadd231ps, vfmsubadd231pd, vfmsub132ps, vfmsub132pd, vfmsub213ps,
vfmsub213pd, vfmsub231ps, vfmsub231pd, vfmsub132ss, vfmsub132sd, vfmsub213ss, vfmsub213sd,
vfmsub231ss, vfmsub231sd, vfnmadd132ps, vfnmadd132pd, vfnmadd213ps, vfnmadd213pd,
vfnmadd231ps, vfnmadd231pd, vfnmadd132ss, vfnmadd132sd, vfnmadd213ss, vfnmadd213sd,
vfnmadd231ss, vfnmadd231sd, vfnmsub132ps, vfnmsub132pd, vfnmsub213ps, vfnmsub213pd,
vfnmsub231ps, vfnmsub231pd, …
=> i#1312 AVX-512 support: Add vfmadd*, vfnmadd*, vfmsub*, and vfnmsub* opcodes.

clients/drcachesim/tests/offline-legacy.templatex
Generalizes the test output template for tool.drcacheoff.legacy to
make thousands commas optional and decimals or commas for tenths
separators, to de-flake the test.
Tested against the AArch64 output from
http://dynamorio.org/CDash/testDetails.php?test=593481&build=43279
Fixes #3317
=> i#3317: Generalize tool.drcacheoff.legacy template

core/arch/x86/decode_table.c, core/arch/x86/encode.c
Fixes the evex masks' size for all ss* and sd* vector opcodes to reflect 1 bit.
Fixes #3662
Issue: #1312
=> i#3662: Fix mask source operand's size in decode table.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the evex-promoted opcodes vpunpcklbw, vpunpcklwd, vpunpckldq, vpunpcklqdq,
vpunpckhbw, vpunpckhwd, vpunpckhdq, vpunpckhqdq, vpacksswb, vpackssdw, vpackuswb,
vpackusdw.
Issue: #1312
=> i#1312 AVX-512 support: Add remaining vpunpck* and vpack* opcodes.

core/arch/x86/decode_table.c, core/arch/x86/encode.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h, suite/tests/api/ir_x86_5args_avx512_evex_mask.h
Adds the evex-promoted opcodes vpcmpgtb, vpcmpgtw, vpcmpgtd, vpcmpgtq, vcmpps, vcmpss,
vcmppd, vcmpsd, vpcmpeqb, vpcmpeqw, vpcmpeqd, vpcmpeqq.
Adds the new AVX-512 opcodes vpcmpub, vpcmpb, vpcmpuw, vpcmpw, vpcmpud, vpcmpd, vpcmpuq,
vpcmpq.
Fixes a few minor white spaces in the decode table.
Issue: #1312
=> i#1312 AVX-512 support: Adds vcmp* and vpcmp* opcodes.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the evex-promoted opcodes vpminsb, vpminsw, vpminsd, vpmaxsb, vpmaxsw, vpmaxsd,
vpminub, vpminuw, vpminud, vpmaxub, vpmaxuw, vpmaxud.
Adds the new AVX-512 opcodes vpminsq, vpmaxsq, vpminuq, vpmaxuq.
Issue: #1312
=> i#1312 AVX-512 support: Add vpmax* and vpmins* opcodes.

core/arch/x86/decode_table.c
The bug has slipped through, because the python script used for testing crashed due to
a llvm-mc bug decoding vcmpps and the exception was not caught. The script has been
fixed and a bug on llvm-mc-7 has been filed: https://bugs.llvm.org/show_bug.cgi?id=42146.
Issue: #1312
=> i#1312 AVX-512 support: Fix W1 bit bug in vcmppd, vcmpsd opcodes.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_3args_avx512_evex.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the evex-promoted opcodes vpsraw, vpsrad, vpsravw, vpsravd, vpsrlvd, vpsrlvq, vpsllw,
vpslld, vpsllq, vpsllvw, vpsllvd, vpsllvq, vpsrldq, vpslldq.
Adds the new AVX-512 opcodes vprolvd, vprold, vprolq, vprolvq, vprord, vprorvd, vprorq,
vprorvq, vpsraq, vpsrlw, vpsrld, vpsrlq, vpsravq, vpsrlvw.
No information was found on vprorrd, vprorrq. The opcodes are mentioned to be distinct
from vprord, vprorq, but they are not further specified in the instruction tables.
Issue: #1312
=> i#1312 AVX-512 support: Add vpro*, vpsr* and vpsl* opcodes.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_3args_avx512_evex_mask.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds the new AVX-512 opcodes vrcp14ps, vrcp14pd, vrcp14ss, vrcp14sd, vrcp28ps,
vrcp28pd, vrcp28ss, vrcp28sd.
Issue: #1312
=> i#1312 AVX-512 support: Add vrcp* opcodes.

suite/tests/linux/threadexit.c, suite/tests/linux/threadexit2.c
The linux.threadexit tests had uninitialized exit codes, causing
failure if the code was examined.  We fix that here by setting it to
zero in the raw SYS_exit_group syscalls they employ.
=> Fix the exit code of the linux.threadexit tests

core/unix/signal.c, suite/tests/linux/sigaction_nosignals.c
Adds emulation of the Linux kernel's sigaction flag hiding for x86 ABI
compatibility modes, both in the DR core and in our sigaction_nosignals test.
Fixes #3681
=> i#3681: Emulate kernel sigaction flag hiding

core/arch/asm_defines.asm, core/arch/x86/x86.asm, suite/tests/common/decode.c
An Ubuntu 18 system's libc, even with older gcc versions 4.8 (we did not try
< 4.5), decided to callee-save a xmm register on the stack. This patch aligns
the stack in the function in the test that is calling vfprintf. This problem generally
affects all functions that we are hand-coding in asm and calling from a test.
Absent a complete review of all hand-coded functions in the code base, this
fixes this one only single case where a test failure was observed.
Fixes #3674
=> i#3674: Add stack alignment to test calling "vfprintf".

core/arch/x86/decode_table.c, suite/tests/api/ir_x86_3args_avx512_evex_mask.h
Fix a minor bug introduced in b39962496373a. Unlike vbroadcastsd, vbroadcastss allows for
a OPSZ_16 destination size.
Issue: #1312
=> i#1312 AVX-512 support: Fix vbroadcastss destination operand constraint.

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_3args_avx512_evex_mask.h, suite/tests/api/ir_x86_4args_avx512_evex_mask.h, suite/tests/api/ir_x86_5args_avx512_evex_mask.h
Adds the new AVX-512 opcodes valignd, valignq, vblendmps, vblendmpd, vcompressps,
vcompresspd, vexpandps, vexpandpd, vfixupimmps, vfixupimmpd, vfixupimmss, vfixupimmsd,
vgetexppd, vgetexpps, vgetexpsd, vgetexpss, vgetmantpd, vgetmantps, vgetmantsd,
vgetmantss, vpblendmb, vpblendmw, vpblendmd, vpblendmq, vpcompressq, vpcompressd,
vpexpandd, vpexpandq, vptestmb, vptestmw, vptestmd, vptestmq, vptestnmb, vptestnmw,
vptestnmd, vptestnmq.
Issue: #1312
=> i#1312 AVX-512 support: Add valign*, vblend*, vcompress*, vexpand* and further opcodes.

core/arch/x86/decode_table.c
Compacts the prefix_extensions table by saving a line consistent with the other tables.
Issue: #1312
=> i#1312 AVX-512 support: Formatting, compact prefix_extensions table.

core/arch/aarch64/codec.txt, suite/tests/api/dis-a64.txt
This commit does not add the half-float version
of the instruction which is introduced in armv8.2
Signed-off-by: Vasilis Flouris <vflouris@ics.forth.gr>
=> Adds aarch64 fmla vector by element instruction

core/arch/x86/decode_table.c, third_party/binutils/test_decenc/drdecode_decenc_x86.expect, third_party/binutils/test_decenc/drdecode_decenc_x86_64.expect
Arranges pext's encoding which otherwise leads to an illegal instruction exception.
Fixes: #3692
=> i#3692:Added pext encoding fix

core/arch/x86/decode_table.c, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Fix first source operand's size. The encodings were still correct and therefore bug was
not discovered by comparing binutils, llvm-mc etc.
Fix related tests.
Issues: #1312, #3639
=> i#1312 AVX-512 support: Fix vpsraw/d/q, vpsllw/d/q first source operand.

core/arch/x86/decode_table.c
Remove stale and temporary comments from x86 decode table.
Issue: #1312
=> i#1312 AVX-512 support: Remove stale and temporary comments.

suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Adds missing tests for one format of vpermpd. The tests pass the binutils/llvm-mc
comparison.
Issue: #1312
=> i#1312 AVX-512 support: Add missing tests for one version of vpermpd.

core/arch/x86/decode_table.c, suite/tests/api/ir_x86_4args_avx512_evex_mask.h
Similar to bf6579986a0712d685c8da, fix source operand's size. The encodings were still
correct and therefore bug was not discovered by comparing binutils, llvm-mc etc. All
related similar vps* opcodes have been checked.
Fix related tests.
Issues: #1312, #3639
=> i#1312 AVX-512 support: Fix vpsrlw/d/q source operand.

core/arch/decode.h, core/arch/instr.h, core/arch/x86/decode_table.c, core/arch/x86/encode.c
Adds the tuple type from Intel's Vol.2A 2.6.5 "Compressed Displacement (disp8*N) Support
in EVEX" to the decode tables.
Extends flags field of instr_info_t to 32-bit. The upper half is reserved for the evex
tuple type of AVX-512.
Tests will be added in future patch. While each tuple type has been carefully added to
the decode tables, there is no decoder/encoder support yet and no tests.
Issue: #1312
=> i#1312 AVX-512 support: Add tuple type to decode table.

api/docs/release.dox, core/dynamo.c, core/heap.c, core/lib/instrument.c, core/lib/instrument_api.h, core/unix/signal.c, core/vmareas.c, core/vmareas.h, suite/tests/api/static_noclient.c
Adds dr_standalone_exit() with support for subsequent DR use,
including full attach.  This is a better solution than setup;detach
support added in de99d45 for the use case of performing DR
decode/encode with DR statically linked (which precludes using
drdecodelib), followed by a separate use of DR for instrumentation.
Updates the test of this use case in api.static_noclient.
Issue: #975
=> i#975 static DR: add dr_standalone_exit()

core/arch/x86/decode.c
Downgrades 4 decode asserts on strange AVX-512 encodings.  Users of
drdecode or DR clients legitimately want to decode non-code without an
abort.  These asserts were breaking Dr. Memory's search for system call
wrappers.
Issue: #1312
=> i#1312 AVX-512 support: relax 4 decode asserts firing on valid input

core/arch/x86/decode.c
Caps the mask register when decoding AVX-512 operands to be a valid
0..7 register rather than generating non-existent values.
Issue: #3719, #1312
=> i#3719 invalid reg: Avoid an invalid mask reg when decoding

core/arch/x86/decode.c, suite/tests/api/ir_x86.c
Treat the instruction as an invalid encoding when the fourth inverted evex.vvvv bit is 0.
Adds test for above.
Issue: #1312
Fixes #3719
=> i#1312 AVX-512 support: Handle an invalid evex.vvvv mask register.

core/arch/x86/x86.asm
In Unix 64-bit mode, the third parameter is passed in rdx, which was clobbered when
reading the second parameter. Switching with writing to rcx works, because rcx is the
fourth parameter in Unix 64-bit, and the first in Windows 64-bit.
Tested by running through debugger and spot-checking feature bits.
Fixes #3722
=> i#3722: Fix receiving third parameter in our_cpuid.

core/arch/instr_shared.c, core/arch/x86/instr.c
Moves instr_set_encoding_hints and instr_has_encoding_hint to instr_shared where they
belong.
Issue: #1312
=> i#1312 AVX-512 support: Move encoding_hint API to instr_shared.

CMakeLists.txt, core/arch/aarch64/proc.c, core/arch/arch_exports.h, core/arch/arm/proc.c, core/arch/proc.h, core/arch/x86/proc.c, core/lib/globals_shared.h, core/unix/signal_linux_x86.c, core/unix/signal_macos.c, core/win32/callback.c, core/win32/inject.c, core/win32/ntdll.c
Adds the functions proc_num_simd_sse_avx_registers() and proc_num_simd_sse_avx_saved()
that replace proc_num_simd_registers() and proc_num_simd_saved() internally when they
are used to access fixed size structures like sigcontext, fpstate or xstate, i.e. the
structure sizes don't contiguously extend to AVX-512. The new functions need to be used
in favor of the existing ones, e.g. to access xmm and ymmh data of formerly mentioned
structures.
Adds the define MCXT_NUM_SIMD_SSE_AVX_SLOTS used in the same manner as described above.
This patch prepares DynamoRIO to switch the exported proc_num_simd_registers() to AVX-512
extended number of registers if there is feature support of the processor and OS.
Issue: #1312
=> i#1312 AVX-512 support: Separate [xfp]state/sigcontext sse/avx no. of registers internally.

CMakeLists.txt, third_party/vera++/use_vera++.cmake
Reverts suppressing vera++ checks incorrectly committed by e20fec822538d08.
Adds the option VERA_ERROR that optionally can be set to OFF in order to turn vera++
errors into a warning. The default is ON.
Issue: #1312
=> i#1312 AVX-512 support: Revert accidental vera++ check suppression.

core/arch/x86/emit_utils.c, core/arch/x86/mangle.c
Fixes two comments and one real bug when passing alignment flags to move_mm_reg_opcode().
This patch is not directly related to AVX-512.
Issue: #1312
=> i#1312 AVX-512 support: Fix alignment parameters when calling move_mm_reg_opcode.

clients/drcachesim/tests/burst_maps.cpp, core/unix/os.c
For the application module, we use the application path obtained from
early injection or /proc/self/exe on Linux, rather than
/proc/self/maps comments.  The maps comments can be unreliable in the
face of anonymous or deleted-file mremaps used for hugepage backing
and other features.
Adds a test case to the existing "burst_maps" test.
Having the right module full_path helps many cases, including the
forthcoming restartable sequences ("rseq") support for #2350.
Issue: #2566, #2350
=> i#2566 anon text: Use the app path instead of maps comments

CMakeLists.txt, api/docs/release.dox, core/arch/interp.c, core/arch/mangle_shared.c, core/lib/statsx.h, core/unix/include/syscall_linux_arm.h, core/unix/include/syscall_linux_uapi.h, core/unix/include/syscall_linux_x86.h, core/unix/memcache.c, core/unix/module.c, core/unix/module_elf.c, core/unix/module_elf.h, core/unix/os.c, core/unix/os_exports.h, core/unix/os_private.h, core/utils.h, core/vmareas.c, core/vmareas.h, core/win32/events.mc, make/configure.cmake.h, make/utils_exposed.cmake, suite/tests/CMakeLists.txt, suite/tests/linux/rseq.c, suite/tests/linux/rseq.expect
Adds initial handling for the restartable sequence ("rseq") feature
that is now in the mainline Linux kernel.
We identify rseq regions by looking for ELF sections with established
names according to upstream conventions.  Unfortunately this requires
going to disk for most libraries, so we avoid this for
full-control-mode if we have never seen an rseq system call, and for
attach if no thread has registered for rseq.
For blocks inside rseq regions, mangling removes all memory stores.
For the final commit instruction, we append a native call back to the
abort handler.  We assume this extra frame is ok, and we require the
rseq sequence to end in a return.  Future work will improve these
assumptions.
Updates the 3 Linux syscall lists up through SYS_rseq.
Adds 3 RSTATS for rseq operation. …
=> i#2350 rseq: Add initial handling of mainline kernel rseq

core/native_exec.c, core/optionsx.h, core/os_shared.h, core/unix/os.c, core/win32/os.c
Reverts the now-obsolete run-native approach for an older version of
the restartable sequence ("rseq") feature. That version never made it
to the mainline kernel, and the run-native approach failed to allow
tools to see rseq code.  Reverts most of commits cda88be and 0935136.
Issue: #2350
=> i#2350 rseq: Remove old run-native code

core/unix/module.c, core/unix/module_elf.c, core/unix/os.c, core/utils.h
Fixes the lazy rseq support to handle code cache pre-population.
Previously rseq code blocks could be created without rseq handling due
to the lazy checks not triggered until after pre-population.
Issue: #2350
=> i#2350 rseq: Support cache pre-population

core/arch/x86/emit_utils.c, core/heap.h, core/lib/instrument.c, core/optionsx.h, suite/tests/CMakeLists.txt
Fixes a bug introduced in 1beb5463c6cd2, missing the translation to the executable address
view, leading to unreachable 32-bit displacements.
Adds vm_base options to an existing w^x test in order to expose future bugs like above.
Issues: #1312, #3556
=> i#3556 w^x: Fix reachable address to executable view.

api/docs/release.dox, core/unix/module_elf.c, suite/tests/CMakeLists.txt, suite/tests/linux/rseq.c
The __rseq_cs_ptr_array will be relocated, so we should not add the
load offset.
Adds an array to the suite test (previously arrays were only tested
manually using a librseq app).  Creates 2 separate tests to test all 3
section types.
Issue: #2350
=> i#2350 rseq: Fix __rseq_cs_ptr_array parsing crash

api/docs/release.dox, core/arch/mangle_shared.c, core/translate.c, core/unix/module_elf.c, suite/tests/CMakeLists.txt, suite/tests/linux/rseq.c
On any translation, and in particular on detach, we translate from
inside an rseq region to the abort handler.  This is necessary to
avoid problems with a cpu migration earlier in the region while
running the instrumented version.
Augments the api.rseq test with a thread that sits in a loop in an
rseq region to test translation on detach: without the translation, it
loops forever.
Issue: #2350
=> i#2350 rseq: Translate from rseq region to handler

core/unix/signal.c
Removes an assertion and replaces it with a comment, explaining the same case as in
37e1ef9a64dda0d0389. The pend_unit_size may not be aligned, but we ensure alignment
of pending units through the special heap allocator (xref #3749).
Fixes #3380
=> i#3380: Remove invalid alignment assertion.

core/lib/instrument.c, core/unix/memcache.c, core/unix/os.c, core/vmareas.c, core/vmareas.h, core/win32/drwinapi/kernel32_mem.c, core/win32/syscall.c, suite/tests/linux/mmap.c
Fixes problems with pre-syscall versus post-syscall mmap handling
which can lead to asserts.  Adds a check-only version of
app_memory_protection_change() for use in pre-syscall, delaying all
vmarea updates to post-syscall.  Adds protection change checking
inside app_memory_allocation(), simplifying caller usage and providing
broader coverage of mmap behavior.
Adds a vmm attribute to all_memory_areas and disallows merging across
that boundary, to match kernel behavior and avoid mismatch warnings
with the above fix in place which does extra memory querying on each
mmap.
Adds some mmap sequences to linux.mmap to provide some test coverage
for these particular page protection change orderings.
Fixes #3759
=> i#3759: Fix mmap handling conflicts

clients/drcachesim/common/options.cpp, clients/drcachesim/common/options.h, clients/drcachesim/tracer/raw2trace.h, clients/drcachesim/tracer/raw2trace_directory.cpp, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Adds a new drcachesim option -subdir_prefix so our tests using the
same application can all have unique directory name prefixes, avoiding
races on removing and finding output files while testing.  We need to
store this string into a plain-char buffer at init time to avoid using
malloc mid-run.
Updates all of the non-static (plus the L0filter static) drcachesim
offline tests to use the new flag, eliminating the need for the
existing dependency marking and fixing races in the new tests which
were not completely marked versus all the prior tests.
Fixes #3770
=> i#3770: Eliminate drcachesim test races

core/arch/instr_shared.c, core/arch/opnd_shared.c, core/arch/x86/instr.c, suite/tests/api/ir_x86.c
Adds AVX-512 VSIB addressing support to instr_compute_address_ex and
instr_compute_address_ex_pos.
Adds scatter opcodes handling to above.
Augments api.ir with tests for above.
Issue: #1312
=> i#1312 AVX-512 support: Support VSIB addressing in instr_compute_address_ex[_pos].

core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_2args_mm.h, suite/tests/api/ir_x86_3args.h
Adds the Intel SHA opcodes sha1msg1, sha1msg2, sha1nexte, sha1rnds4, sha256msg1,
sha256msg2, and sha256rnds2.
Opcodes have been checked against llvm-mc and binutils/gas/objdump.
Clients should not rely on binary compatibility of the added opcodes until both
issues #3581 and #1312 have been closed.
Issue: #3581
=> i#3581 SHA/MPX/PT support: Add support for Intel SHA instructions.

core/arch/arch.h, core/arch/interp.c, core/arch/x86/decode.c, core/lib/instrument.c
In order to avoid self-detection of AVX-512 gencode, this patch moves the warning to the
main interpreter loop instead.
The warning also has been disabled for UNIX 64-bit. This build has been supported since
cf1ec32e9b89c1d8a28e.
A warning is issued only for AVX-512 application code, not client code.
Fixes #3790
=> i#3790 AVX-512 support: Move AVX-512 warning to interpreter loop.

CMakeLists.txt, core/string.c
GCC >= 8.2 does not accept a different function declaration used for the alias macro
without a warning. Instead of subduing the warning and relying on aliasing it, we now
inline the function body directly with a macro.
Disables the warning errors -Wstringop-truncation, -Wformat-truncation, and
-Wno-stringop-overflow. All 3 warnings are related to '\0' string termination. DynamoRIO
manages string termination and error handling itself in many places. Various re-factoring
would be required in order to turn on the warnings.
Fixes #3792
=> i#3792: Remove alias attribute and replace by real function body.

core/arch/decode.h, core/arch/x86/decode_table.c, core/arch/x86/instr_create.h, core/arch/x86/opcode.h, suite/tests/api/ir_x86_1args.h
Adds the Intel PT instruction ptwrite.
The opcode has been checked against llvm-mc and binutils/gas/objdump.
Fixes #3581
=> i#3581 SHA/MPX/PT support: Add support for Intel PT instructions.

api/docs/bt.dox, core/arch/arch.c, core/arch/arch.h, core/arch/arch_exports.h, core/arch/mangle_shared.c, core/globals.h, core/translate.c, core/unix/os.c, core/unix/os_exports.h, core/unix/rseq_linux.c, core/unix/rseq_linux.h, core/vmareas.c, suite/tests/linux/rseq.c
Changes the native execution of the rseq region to target the start of
the sequence rather than the abort handler.  This is done for two
reasons: to support abort handlers which simply abort and do not
restart, and to make it much easier in the future to run a copy of the
sequence rather than rely on call-return semantics in the app code.
Adds preservation of input registers, limited to general-purpose
registers clearly read-before-written in the sequence.  Documents the
new restrictions.  Tries to pick a better scratch register, though
this should go away once we switch to using a local copy.
Issue: #2350
=> i#2350 rseq: Target start instead of handler

core/unix/loader.c
Adds ignoring of kernels labeling DR's .bss as "[heap]", to avoid
unnecessary reloading at startup.
Fixes failures to unmap the executable's headers on a reload.
Fixes #3799
=> i#3799: Fix leak and false trigger on DR reload

core/arch/decode.h, core/arch/x86/decode.c, core/arch/x86/decode_private.h, core/arch/x86/decode_table.c, core/arch/x86/encode.c, suite/tests/api/ir_x86.c
Fixes a missing check for a prohibited default write mask register for all
scatter/gather opcodes. Adds a new flag.
Adds a test for all scatter/gather opcodes.
A binutils/objdump bug has been filed:
https://sourceware.org/bugzilla/show_bug.cgi?id=24945
Issue: #1312
=> i#1312 AVX-512 support: Do not allow default write mask for scatter/gather.

core/unix/signal_linux_x86.c
Fixes a bug where r8's value is printed for r9 in signal fpstate.
Changes incorrect 2-byte output formatting to 4-byte for ymmh and
32-bit xmm.
=> Fix r8-as-r9 and SIMD format widths when printing x86 signal fpstate

suite/tests/api/detach_state_shared.h
Fixes a build error in 32-bit on an avx-512-enabled toolchain from 2a6bc3c.
Issue: #3812
=> i#3812 avx sigreturn: Fix 32-bit avx-512 build error

core/unix/signal.c
Updates a comment which incorrectly speculated that segment bases were
the cause of a sigreturn crash.
Issue: #3812
=> i#3812 avx sigreturn: Update comment on sigreturn crash

core/arch/x86/instr_create.h, suite/tests/api/ir_x86_4args.h, suite/tests/api/ir_x86_4args_avx512_evex.h
The macro was missing both for AVX and AVX-512. The existing AVX roundtrip test was
incorrectly using the vpinsrd version.
Adds tests for AVX-512.
Issue: #1312
=> i#1312 AVX-512 support: Add missing instr_create macro for vpinsrq.

core/arch/x86/decode.c, core/arch/x86/decode_table.c, core/arch/x86/encode.c, suite/tests/api/dis-x64.expect
Fixes a bug where we didn't respect and check encodings rules for the VEX.L bit.
The VEX encoded AVX-512 instructions had not been ground-truth tested. The opcodes
have now been checked against llvm-mc and binutils/gas/objdump.
Issue: #1312
=> i#1312 AVX-512 support: Fix VEX.L0/VEX.L1 in mask opcode encodings.

suite/tests/client-interface/drx-scattergather.c, suite/tests/client-interface/drx-scattergather.expect, suite/tests/client-interface/drx-scattergather.templatex
When instructions get expanded into the emulation sequence, it may result in skipping some
of the checks. To prepare and make sure they were passed, this patch adds a little bit
more output to the test.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Add more test output to drx-scattergather.

api/docs/bt.dox, core/arch/aarchxx/mangle.c, core/arch/arch.h, core/arch/arch_exports.h, core/arch/instr.h, core/arch/mangle_shared.c, core/arch/mangle_utils.c, core/arch/steal_reg.h, core/arch/x86/mangle.c, core/emit.c, core/fragment.c, core/fragment.h, core/globals.h, core/optionsx.h, core/unix/os.c, core/unix/os_exports.h, core/unix/rseq_linux.c, core/unix/rseq_linux.h, suite/tests/linux/rseq.c, suite/tests/linux/rseq.expect
Eliminates the call-return reliance for the native execution step of
rseq support.  Makes a local copy of the sequence right inside the
sequence-ending block and executes it.  The sequence is inserted as
additional instructions and is then mangled normally (mangling changes
are assumed to be restartable), but it is not passed to clients.  Any
exits are regular block exits, resulting in a block with many exits.
The prior call-return scheme is left under a temporary option
-rseq_assume_call, as a failsafe in case there are stability problems
discovered with this native execution implementation.  Once we are
happy with the new scheme we can remove the option.
To make the local copy an rseq region, the per-thread rseq_cs address
is identified by watching system calls.  For attach, it is …
=> i#2350 rseq: Use a local copy for native execution

core/lib/globals_shared.h, core/optionsx.h, core/unix/os.c, core/unix/os_exports.h, core/unix/tls.h, core/unix/tls_macos.c, core/win32/events.mc
Uses pthread_key_create() to allocate enough contiguous and aligned TLS
slots to fit our os_local_state_t struct.  This makes it easier to share
Linux code for Mac64.
Keeps the scheme from ce8e803 of storing a pointer to the base of
os_local_state_t in TLS slot 6.  This is indirection we don't need with the
entire os_local_state_t struct in TLS but it is not clear we can take that
many TLS slots for large applications, so I'm leaving this mixture until
we're sure which direction to go in.
Disables the options -mangle_app_seg and -safe_read_tls_init for Mac64.
Issue: #1568, #1979
=> i#1568 Mac64 TLS: Use pthread TLS slots for DR and clients

core/arch/asm_defines.asm, core/arch/interp.c, core/arch/x86/x86.asm, core/lib/globals_shared.h, core/lib/instrument.c, core/unix/memquery_macos.c, core/unix/module_macho.c, core/unix/os.c, core/unix/os_private.h, core/unix/os_public.h, core/unix/signal.c, core/unix/signal_macos.c, core/unix/signal_private.h, core/vmareas.c
Fixes several issues to get small 64-bit apps to run on Mojave:
+ Fixes library discovery problems with the dyld shared cache.
On Mojave, SYS_shared_region_check_np returns the whole lib region,
while the existing code assumed its return value was the shared
__LINKEDIT segment.
+ Demotes a DOCHECK at level 1 in check_thread_vm_area to 3 for
Mac64 as it shows up as a large performance hit apparently due
to slow memory queries.
+ Segment fixes: fixes two issues hit due to DR and lib segments being
equal: a bb building assert for -no_mangle_app_seg and a
dr_insert_get_seg_base() assert.
+ Attempts to reduce overhead in memquery_from_os() where it needs extra
iterations to find the surrounding bounds of a free area, by walking
backward instead of starting from 0.
+ Uses SYS_stat64 and …
=> i#1979 Mac64: small app support on Mojave

core/unix/os.c, core/unix/os_private.h, core/unix/signal.c
Fixes a regression from edb2eed where all signals, including SIGSEGV and
SIGBUS, were blocked while running exit code.  This meant that DR wouldn't
catch and report crashes, and more importantly clients couldn't use safe_read
and other features in their exit events.  Now we avoid blocking those two
key signals.
Tested: Dr. Memory's safe_read uses during exit no longer crash or hang.
Fixes #3839
=> i#3839: Do not block SIGSEGV and SIGBUS at exit time

core/unix/memquery_macos.c, core/unix/signal.c, core/unix/tls_macos.c
When querying into a submap, we can go straight to the middle, avoiding
overhead of tons of syscalls querying from the start.  And when we walk
backward finding the prior on a free, a smaller starting step is a win for
common queries.  This drops Dr. Memory from taking 25s (!) on a tiny app
down to 8s.  Most of the 8s is still memqueries on the leak scan but that's
for another day.
Issue: #1979
=> i#1979 Mac64: Faster memquery

make/cpp2asm_support.cmake
i#638: Preprocessor location and flags on MSYS2 MinGW are same as on Unix-like system. This is just a second step toward building with MinGW.
Issue: https://github.com/DynamoRIO/dynamorio/issues/638
Signed-off-by: ofry <tim4job@bmail.ru>
=> i#638: set preprocessor location and flag on MSYS2 MinGW same as on Unix

core/arch/aarch64/clean_call_opt.c, core/arch/arch.c, core/arch/arch.h, core/arch/arch_exports.h, core/arch/clean_call_opt_shared.c, core/arch/mangle_shared.c, core/arch/opnd.h, core/arch/x86/clean_call_opt.c, core/arch/x86/mangle.c, core/unix/os_exports.h
Adds opnd.h to arch_exports.h, allowing replacement of the duplicate
NUM_GP_REGS with DR_NUM_GPR_REGS.
Adds opnd.h to os_exports.h, allowing the use of reg_id_t instead of
ushort.
Fixes #3794
=> i#3794: Export opnd.h to all of core/

core/arch/opnd.h
Adds documentation to inform the user to use opnd_create_base_disp() in order to create a VSIB operand.
Fixes #3856
=> i#3856: Add VSIB documentation

clients/drcachesim/reader/reader.cpp
The type_is_instr() function deliberately excludes
TRACE_TYPE_INSTR_NO_FETCH, yet we can have a bundle preceded by a
no-fetch instruction.  We relax the assert in the reader to reflect
this.
Fixes #3320
=> i#3320: Fix type_is_instr assert in drcachesim

core/loader_shared.c, core/module_shared.h, core/unix/loader.c, core/unix/module_elf.c
This patch makes DynamoRIO's private loader add a client library's rpath + runpath to the
global search path. This is considered a work around for issues stemming from the fact
that currently, DynamoRIO's private loader is traversing library dependencies depth-first
instead of breadth-first. From experiments it looks like the native Linux loader does the
latter.
This resulted into some cases where DynamoRIO's loader couldn't find libraries that
can only be found by considering the client's rpath + runpath. In those cases, the C++
toolchain was adding multiple system dependencies to the client library including a valid
rpath, but the system libraries itself did not reflect the same rpath.
The drawback of this workaround is the unability to handle potential corner cases with
libraries of …
=> i#3850 private loader: Add a client library's rpath + runpath to search path.

core/unix/loader.c
This adds to d33ed98bdb4fb666 by adding all rpaths of the client library to the global
search list before walking dependencies depth-first. This was originally intended like
this and missed by d33ed98bdb4fb666, which stops adding the client library's rpaths to
the list once a library is found.
Issue: #3850
=> i#3850 private loader: Always add all client library's rpaths.

suite/tests/linux/exit.c, suite/tests/linux/fork.c, suite/tests/linux/fork.expect, suite/tests/linux/longjmp.c, suite/tests/linux/syscall_pwait.cpp, suite/tests/pthreads/pthreads.c
Re-factors linux.fork to using tools.
Fixes an uninitialized variable in linux.syscall_pwait.
Changes using printf to using tools in tests linux.exit, linux.longjmp, and pthreads.pthreads.
Please note the stdout change above is somewhat random, and there are various tests left
using printf and a future patch should address changing all remaining tests to using tools.
=> Minor test cleanups and uninitialized variable fix.

core/arch/x86/instr.c
Extends reg_is_simd to consider ZMM registers.
Fixes #3867
=> i#3867: Extend reg_is_simd() to zmm.

core/arch/opnd.h, core/arch/opnd_shared.c, core/unix/loader.c, ext/drx/drx.c, suite/tests/api/ir_x86.c
Extends reg_resize_to_opsz to support SIMD resizing.
Issue: #3865
=> i3865: Extend reg_resize_to_opsz

api/docs/release.dox, core/arch/instr.h, core/arch/instr_shared.c, suite/tests/api/ir_x86.c
Introduces a new function, namely instr_reads_from_exact_reg(), to check whether or not an instruction reads directly and exactly from a given register. 
Fixes #3872
=> i#3872: Adds instr_reads_from_exact_reg()

core/arch/arch_exports.h, core/arch/x86/emit_utils.c
This is my first PR to DR so I hope this conforms the guidelines, I've looked how the other architectures did it and adapted the same style. I used the AMD manual as reference to multibyte nops and also left it as a comment.
Fixes #3828
=> i#3828: Implement multibyte nop for AMD64 architecture

core/unix/rseq_linux.c
Adds allowance for seccomp blocking SYS_rseq.
Tested in a default docker run:
$ docker run <image> bin64/drrun -debug -- ls
Fixes #3848
=> i#3848: Fix rseq assert from seccomp

ext/droption/droption.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/option_parse.dll.cpp, suite/tests/client-interface/option_parse.expect
Modifies convert_from_string() to read into a 64-bit value for the bytesize_t droptions.
Fixes #3605
=> i#3605: Support 64-bit literals for droption bytesize_t

make/policies.cmake
I cannot reproduce the problem with CMP0058 and Ninja on CMake 3.3+ so
I'm removing the setting of that policy to OLD, as that causes
warnings on CMake 3.13+.
Fixes #1955
=> i#1955: Remove CMake CMP0058 policy setting

make/policies.cmake
Our cmake code was manually inspected, and I couldn't find a single instance where we
depend on cmake implicitly expanding a quoted variable in an 'if' statement. Therefore,
we're removing this policy.
Fixes #1718
=> i#1718: Remove CMP0054 OLD behavior policy.

core/unix/module.c, core/unix/module_macho.c, core/unix/module_private.h
We were previously blindly page-aligning MachO segments, yet on
Catalina libraries have sub-page alignment and DR fails due to library
overlap.  We fix this by computing the alignment from the section
alignments, but in the end I'm just leaving the given addresses since
they're already aligned.  We also relax a curiosity about all segments
having the same alignment to only apply to ELF.
Fixes #3886
=> i#3886: Compute alignment of MachO segments and do not page align

CMakeLists.txt, api/samples/CMakeLists.txt, core/CMakeLists.txt, core/optionsx.h, core/unix/os.c, make/policies.cmake, make/utils_exposed.cmake
Removes the CMP0042 policy setting of OLD which is now deprecated.
Sets CMAKE_MACOSX_RPATH at the top level.
Sets CMP0068 to NEW since we comply with the changes there.
Removes the old INSTALL_NAME_DIR setting on libdynamorio.
I tried using @rpath or $ORIGIN for Mac explicit rpaths but both
failed (@rpath is supposed to work) so I left @loader_path in place.
Cleans up some other OSX pieces such as the warning about 64-bit not
being supported, and the max kernel version.
Fixes #1375
=> i#1375: Use modern CMake OSX rpath support

suite/tests/CMakeLists.txt, suite/tests/linux/sigcontext.c
Fixes incorrect buffer sizes in the test.
Adds clobbers making the test more robust.
Adds no vzeroupper flag, necessary on some platforms that are adding the instruction.
Even with above, the test is not bullet proof and could be broken by an existing or
future toolchain. Ideally, some parts should get rewritten in assembly.
=> Fix linux.sigcontext when running with AVX-512.

suite/tests/client-interface/cleancall-opt-1.dll.c, suite/tests/client-interface/cleancall-opt-shared.h, suite/tests/client-interface/inline.dll.c
Changes client.avx512cleancall-opt-1, client.cleancall-opt-1, and client.inline tests
to using instrumentation API to retrieve the binary name instead of hardcoding it.
Adds a minor assertion in case name is not found, replacing it with a crash.
=> Replace using hardcoded names with API.

ext/drreg/drreg.c
Adds to several comments in drreg following analysis with respect to #3823. Issue #3823's
title will be renamed to cover the multiple users aspect. Single user app2app insertion
should be ok as is. we're leaving the door open to potentially introduce special labels
mentioned in #3823 with respect to restore state event in drreg.
Minor renaming drreg_forward_analysis to drreg_forward_liveness_analysis.
Issue: #3823
=> i#3823 drreg multiple users: Amends several minor comments in drreg.

core/unix/module.c, core/unix/module_elf.c
Some VDSO instances have their only segment happening to fit on one
page, with just section headers and non-loaded sections on the second
page.  Since those non-loaded sections are still loaded because VDSO
is placed completely in memory, this causes some confusion with parts
of DR that expect the mapping end to equal the end of the final
segment.  Our solution is to add a synthetic segment for the rest of
the mapping.  It's possible this will cause confusion of its own, but
it seems the least bad thing to do.
Fixes #3900
=> i#3900: Add synthetic segment for VDSO 2nd page

api/docs/release.dox, core/arch/opnd.h
Defines DR_NUM_SIMD_VECTOR_REGS as an alias to MCXT_NUM_SIMD_SLOTS for better code clarity.
Note that the dynamic variant, proc_num_simd_registers(), should be used instead whenever possible.
Fixes #3898
=> i#3898: Added Alias to MCXT_NUM_SIMD_SLOTS

suite/tests/client-interface/cleancall.c, suite/tests/common/decode.c
client.cleancall: Prevent foo() from being optimized away, which was observed with new
toolchains. This is more a bandaid than a fix, and we should re-write this test into
using clean assembler instead. Furthermore, adds a pragma to prevent loop unrolling
that caused the test to break on such systems.
common.decode: On some systems, the monitor instruction is enabled and does not cause
an UD fault. This change here keeps the eax address valid so the monitor instruction will not
throw an GP exception.
=> More test robustness fixes.

suite/tests/client-interface/cleancall-opt-1.c, suite/tests/client-interface/inline.c
client.cleancall-opt-1, client.inline: Prevent test functions from being optimized away
and from getting inlined.
=> Further test robustness fixes.

ext/drx/drx.c, suite/tests/client-interface/drx-scattergather.dll.c, suite/tests/client-interface/drx-scattergather.templatex
Adds emulation labels to the expanded sequence and a test that counts the number of
actual scatter/gather instructions.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Add emulation labels to sequence.

core/unix/os.c, suite/tests/linux/syscall_pwait.cpp, suite/tests/linux/syscall_pwait.template
While the glibc wrapper seems to always pass a valid pointer to the kernel, the latter
does accept NULL pointers. This patch adds support to handle pselect6, ppoll, and
epoll_pwait system calls with NULL sigmask parameter.
Fixes #3911
=> i#3911: Support NULL sigmask parameter passed to pselect, ppoll, epoll_pwait.

core/arch/opnd.h
Change DR_NUM_SIMD_VECTOR_REGS to reflect the actual architectural number of registers
instead of the preserved number of registers as given by MCXT_NUM_SIMD_SLOTS, as it
was intended by beb2ded8ac9e83a02fe418.
Fix the upper bound of number of simd registers of xmm, ymm, and zmm in x86 reflected
by DR_REG_STOP_XMM, DR_REG_STOP_YMM, and DR_REG_STOP_ZMM in 32-bit mode.
Fixes #3906
=> i#3906: Fix DR_NUM_SIMD_VECTOR_REGS to reflect the architectural number of registers.

suite/tests/linux/syscall_pwait.cpp, suite/tests/linux/syscall_pwait.template
Fixes a 64-bit bug that led to a non-zero pointer on some systems and a subsequent test
failure. Using NULL works for both 32-bit and 64-bit.
Additionally:
* Adds missing implicit registers to clobber list of syscall inline asm.
* Adds yet another version for pselect6, in inline asm. The test is semantically redundant
to the existing NULL pointer test, and would only expose unexpected changes in glibc's
syscall() implementation. Added for completeness.
* Casts every parameter passed to variadic function syscall() into their safe type according
to their function definiton.
* Fixes all types passed in asm volatile statements as well.
* Makes all parameters named in asm volatile statements.
Fixes #3911
=> i#3911: Change 0 and 0LL into NULL for variable length arguments of syscall().

api/docs/release.dox, ext/drmgr/drmgr.c, ext/drmgr/drmgr.h, suite/tests/client-interface/low_on_memory.dll.c, suite/tests/client-interface/low_on_memory.templatex
Enhances drmgr to support low-on-memory events.
Fixes: #3913
=> i#3913: Add drmgr wrapper for low-on-memory events

ext/drx/drx.c
As supported by #3899, this patch removes a workaround that was conservatively put in
place for spilling cross-app instructions.
Reserves an additional slot per reserved cross-app register as documented in drreg.
Issues: #2985, #3899
=> i#2985 drx_expand_scatter_gather(): Remove unnecessary workaround.

ext/drx/drx.c, suite/tests/client-interface/drx-scattergather.c, suite/tests/client-interface/drx-scattergather.templatex
Adds support for spilling the scratch mask register to a scratch gpr.
Instead of comprehensively expanding drreg to manage mask registers, we are spilling
the scratch mask for scatter gather expansion to a drreg managed gpr. A future patch
still needs to handle the case of an asynchronous event hitting in the small window where
the mask register is invalid, so we can restore its value.
Adds a test for above.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Support spilling AVX-512 mask register.

CMakeLists.txt
I am using Cmake 3.14 with more than one windows sdk availables, eg.: 8.1.x, 10.0.x, ...
The generated solution use default to 8.1 (not set), which failed during build. It should be set to 10.x  regarding to WindowsSDKVersion ENV variable eg. "10.0.17763.0".
Resource:
* https://stackoverflow.com/questions/45692367/how-to-set-msvc-target-platform-version-with-cmake
* https://gitlab.kitware.com/cmake/cmake/issues/17992
=> Set WinSDK version to use current ENV WindowsSDKVersion value when using MSVC

suite/tests/client-interface/drx-scattergather-shared.h, suite/tests/client-interface/drx-scattergather.c, suite/tests/client-interface/drx-scattergather.dll.c, suite/tests/client-interface/drx-scattergather.templatex
Adds a test to check for the correct state of the gather instruction's mask register if an
asynchronous event hits the sequence after a completed load, but before the mask register
update. Note that the restore event is not implemented yet, and the test is currently
expected to report an error.
Re-factors the tests and puts the functions test_avx512_restore_mask_fault,
test_avx512_restore_mask_clobber, and test_avx512_restore_mask_update
in one common macro.
A future patch that will add support for restoring the mask register will also
include an update to this test.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Add a test for updated mask register state.

clients/drcachesim/drcachesim.dox.in, clients/drcachesim/tests/offline-view.templatex, clients/drcachesim/tools/view.cpp
Adds printing of timestamp, core, and kernel transfer markers to the
drcachesim trace view tool.  The markers embedded in the disassembly
make it much easier to see signal handlers and thread transitions.
Adds a sanity check to the view test and updates the docs.
=> Add markers to drcachesim trace view tool output

core/arch/x86/decode.c, core/arch/x86/decode_table.c, third_party/binutils/test_decenc/drdecode_decenc_x86.expect, third_party/binutils/test_decenc/drdecode_decenc_x86_64.expect
Updates the prefix order to properly decode crc32w.
Fixes the destination size codes for OP_crc32: the destination can
never shrink to 16 bits.  Resolves an old comment expressing confusion
about this where the Intel manual had a separate entry for a data
prefix, resulting in different codes than we need in our table.
Enables all the crc32w test cases in the binutils decenc tests.
Updates the expected test patterns.
Fixes #2431
=> i#2431: Fix decoding of crc32w

core/unix/os.c
We need to close it in cases of successful/failed fd_priv_dup, so just
promote the existing close to before the success/failure check.
Fixes #3940
=> i#3940 FD leak: close the leaked file descriptor with -satisfy_w_xor_x.

core/arch/interp.c, core/translate.c, core/unix/signal.c
Removes the problematic Linux approach for handling an invalid
application instruction in a basic block, where we would isolate it to
its own bb and then copy 17 bytes for native execution, assuming the
processor would raise a fault.  This is very fragile and caused
real-world problems with the crc32w decoder bug (#2431).  Those 17
bytes often end mid-instruction, causing the exit cti to not exist and
DR to execute junk instructions, leading to all kinds of bad behavior.
Now, Linux does what Windows does: we immediately forge an illegal
instruction fault (SIGILL for Linux).  While it might be nicer to try
to continue execution for instructions whose length we can guess at,
there are just too many risks here as described above.  It's better to
have a clear fault that someone can identify …
=> i#3212: Unify invalid app instr handling

core/arch/x86/decode_table.c
Replaces {E,G,M}d_q with {E,G,M}y.  The 'y' code matches what Intel
uses for OPSZ_4_rex8; matches our existing {B,E,G,R}y codes; and
conforms to the convention that an underscore between two size letters
indicates a partial size out of a larger whole.
Renames the F{x,y,z} codes used for particular floating-point sizes to
Ff{x,y,z}, to avoid confusion with Intel's 'x', 'y', and 'z' size
codes.
=> Make decode table size codes consistent

clients/drcachesim/tests/trace_invariants.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h
Fixes a bug where drcachesim's raw2trace places delayed branches
*after* signal markers, leading to confusing trace orderings.
Improves the checking for markers in trace_invariants, but
unfortunately it still will not catch this case as it does not know
the targets of branches nor the addresses of signal handlers.
Adds log_instruction() to trace_converter_t and uses it to disassemble
memtrace instructions on *every* instance, instead of just the first
time encountered.  This is essential for debugging these types of
issues.
Issue: #3937
=> i#3937 memtrace sigs: Order delayed branch before signal markers

core/arch/arch.h
The bug led to an invalid encoding error on machines with no support for AVX512BW,
but AVX512F.
Tested manually by setting proc_avx512_enabled to true on a machine w/o AVX-512.
Issue: #1312
=> i#1312 AVX-512 support: Fix OPSZ_SAVED_OPMASK for non-AVX512BW machines.

core/arch/arch.h, core/arch/x86/proc.c
As pointed out in cf1ec32e9b89c1d8a28e0f3, AVX-512 context management by DynamoRIO is not
fully supported or is untested on non-UNIX as well as on 32-bit builds. Yet processor
detection and certain AVX-512 functionality was enabled on those builds when running on
machines with AVX-512 support enabled by the OS. This was causing problems (xref #3949).
For now, this patch completely disables all AVX-512 features on unsupported and untested
builds.
Fixes #3949
Issue: #1312
=> i#1312 AVX-512 support: Suppress incomplete AVX-512 support on non-UNIX and 32-bit.

core/arch/arch.h, core/arch/x86/proc.c
In dadb8ff2eeb173, we disabled support for AVX-512 for all 32-bit UNIX builds completely.
Yet those builds are only missing support for AVX-512 state in signal frames. Various
tests already exist for existing context switching in 32-bit. In order to keep these tests
working, we are re-enabling partial AVX-512 support for UNIX 32-bit. A warning is issued
if AVX-512 code is encountered.
Issue: #1312
=> i#1312 AVX-512 support: Re-enable partial support for UNIX 32-bit.

ext/drx/drx.c, ext/drx/drx.h, suite/tests/client-interface/drx-scattergather.c, suite/tests/client-interface/drx-scattergather.templatex
Adds a drx restore event that will eventually handle fixing AVX-512 gather, AVX-512
scatter and AVX2 gather emulation sequence application state.
This patch adds drx support to detect and restore the scratch mask as well as the
destination mask state in the AVX-512 gather emulation sequence. This is necessary if
a translation event hits the AVX-512 gather emulation sequence in certain parts of the
emulation code. Detection is done by a state machine that attempts to match a known
pattern of the emulation sequence.
AVX-512 scatter and AVX2 gather is not yet supported.
Removes the relevant errors from client.drx-scattergather.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Support a drx restore event for emulation code.

ext/drx/drx.c
Converts calling the state machine into a function pointer call in order to be able to
more easily share code when adding an AVX-512 scatter and an AVX2 gather state machine.
The patch also fixes 2 minor assertion bugs and another minor state machine bug where we
did not skip unknown instructions.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Re-factor and prepare for more state machines.

clients/drcachesim/analyzer_multi.cpp, clients/drcachesim/common/trace_entry.h, clients/drcachesim/drcachesim.dox.in, clients/drcachesim/reader/ipc_reader.cpp, clients/drcachesim/reader/ipc_reader.h, clients/drcachesim/reader/reader.cpp, clients/drcachesim/tests/signal_invariants.c, clients/drcachesim/tests/trace_invariants.cpp, clients/drcachesim/tests/trace_invariants.h, clients/drcachesim/tracer/instru.h, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/raw2trace.cpp, clients/drcachesim/tracer/raw2trace.h, clients/drcachesim/tracer/tracer.cpp, suite/tests/CMakeLists.txt
Adds the module offset of the interruption point PC to the kernel
event marker to record when a signal happened.  Refactors
raw2trace to check for signals after every insruction and not
just every memref, and to look at the offset for correct
placement.
Adds a new test application signal_invariants which uses assembly
for precise control over tests around signal marker placement.
Changes the trace_invariants tests to use this new application.
The test uses prefetch instructions as annotations to communicate
with the trace_invariants reader.  Uses the new test to add
several additional invariant checks to trace_invariants: signal
placement mid-bb, placement mid-memref, handler resumption,
handler immediacy.
Updates the docs to show an example of a signal handler
interruption in the view …
=> i#3937 memtrace sigs: fix missing near-signal instructions

core/arch/instr.h, core/arch/instr_shared.c, ext/drmgr/drmgr.h
Label callbacks are called every time an instruction is destroyed if the instruction is
a label instruction and the field is valid. When cloning an instruction, we can't blindly
copy the label callback field causing it to be called when the cloned instruction is
destroyed. We are adding a note to the docs of instr_clone() and prevent the field from
being copied.
Fixes #3926
Issue: #3962
=> i#3926: Do not clone label callbacks.

ext/drx/drx.c, suite/tests/client-interface/drx-scattergather.c, suite/tests/client-interface/drx-scattergather.templatex
Adds support for restoring the destination mask in the AVX2 gather emulation sequence. As
before, detection is done by a state machine that attempts to match a known pattern of the
emulation sequence.
Removes the relevant error from client.drx-scattergather and fixes a bug in the test for AVX2
gather in 32-bit mode.
Fixes a bug in the AVX-512 state machine if index is OPSZ_8. Only OPSZ_4 is currently
tested in drx.scattergather.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Add drx restore state machine for AVX2 gather.

ext/droption/droption.dox, ext/droption/droption.h, suite/tests/CMakeLists.txt, suite/tests/client-interface/option_parse.dll.cpp, suite/tests/client-interface/option_parse.expect
- Add default implementations of convert_from_string and default_as_string to avoid crashes.
- Add implementations for long and long long value types
- Update documentation to list the supported value types
=> Improve handling and documentation about supported and unsupported value types in droption

ext/drx/drx.c, suite/tests/client-interface/drx-scattergather.templatex
The patch adds drx support to detect and restore the scratch mask as well as the
destination mask state in the AVX-512 scatter emulation sequence.
Adds two more states to the AVX2 gather and the AVX-512 gather state machine making
them more robust detecting the emulation sequence.
Fixes a bug where we read register values from mcontext instead of raw_mcontext
when restoring it, which matters for example if the register is the stack pointer.
Fixes some bugs in the illustrating comments.
Removes the relevant errors from client.drx-scattergather.
Issue: #2985
=> i#2985 drx_expand_scatter_gather(): Add drx restore state machine for AVX-512 scatter.

core/unix/loader.c
For 32-bit, when the private loader calls functions in potentially
third-party libraries, it needs to align the stack to 16 to account
for the mismatch in DR's 4-byte alignment (i#847) and the new gcc ABI.
Tested on libdrmemtrace which with gcc 8.3.0 has SIMD code which
crashes without alignment.
This is a short-term fix.  More issues remain with clean calls and we
should perhaps consider changing our base alignment.
Issue: #847, #3966
=> i#3966: Align stack to 16 for private library init/fini calls

core/lib/instrument_api.h
=> DOC: Document that dr_mutex_unlock must only be used on mutexes locked by the same thread

core/arch/decode_fast.h, core/arch/x86/decode_fast.c, core/globals.h, make/configure.cmake.h, suite/tests/api/ir_x86.c, suite/tests/api/ir_x86_3args.h, suite/tests/api/ir_x86_all_opc.h
Fixes a bug in decode_cti() with a (e)vex prefix with its 2nd or 3rd
byte also looking like the first byte of a (e)vex prefix where the
instruction is considered invalid, crashing the application.
Adds testing of decode_cti() to api.ir by export decode_cti() in DEBUG
and BUILD_TESTS builds.  Adds a test case that triggers the observed
bug without the fix.
Fixes #3978
=> i#3978: Fix decode_cti bug on particular (e)vex byte sequences

suite/tests/CMakeLists.txt
Updates a reference to a split header in the cmake code which was missed by PR #3993.
Issue: #3992
=> i#3992 VS2013 OOM: Update stale header reference

core/arch/arm/arm.asm
Implements dr_app_start() and dr_running_under_dynamorio() for ARM.
This is initial support for the start/stop interface.
There is more to be done before we can enable the start/stop tests.
Issue: #1551
=> i#1551 ARM: Implement initial start/stop support

core/unix/tls_linux_aarchxx.c
For static DR, there is no private loader segment, and AArch64 was
writing NULL into the TLS register, causing crashes.  We fix that by
using the app's segment in the same way that non-static DR uses the
private segment.
Tested by locally enabling the drcachesim static tests.  We cannot yet
enable them permanently due to Travis build errors.
Issue: #2007
=> i#2007 A64 static DR: Fix TLS setup with no private loader

clients/drcachesim/tracer/raw2trace.cpp
Fixes a bug in raw2trace_t::get_instr_summary() where the INOUT
parameter 'pc' was not correctly updated when the last-query-cache
hit.
=> Fix raw2trace bug on updating the PC when the last-query-cache hits

clients/drcachesim/tracer/raw2trace.h
In drmemtrace offline traces, (non-kernel-transfer) markers between PC
entries and memref entries are not handled.  Here we add handling,
simply emitting any that are found.
Tested on the #4003 scenario by disabling the large-value assert in
order to reach the raw2trace error caused by these markers.
Issue: #4003
=> i#4003 marker order: Handle drmemtrace markers after PC entries

api/docs/release.dox, clients/drcachesim/tracer/tracer.cpp, core/arch/instrlist.c, core/arch/instrlist.h, ext/drmgr/drmgr.c, ext/drmgr/drmgr.h, suite/tests/client-interface/drmgr-test.dll.c
Adds a new API function drmgr_is_first_nonlabel_instr() and uses it in the
drmemtrace tracer to insert the block-PC entry after all labels but
before all app or tool instructions.  This places the PC entry at the
right position with respect to drwrap-hook-inserted marker entries.
Fixes #4003
=> i#4003 marker order: Add drmgr_is_first_nonlabel_instr(); use in drmemtrace

CMakeLists.txt, api/docs/release.dox, clients/drcachesim/reader/file_reader.h, clients/drcachesim/reader/ipc_reader.h, clients/drcachesim/simulator/cache.h, clients/drcachesim/simulator/cache_fifo.h, clients/drcachesim/simulator/cache_lru.h, clients/drcachesim/simulator/cache_miss_analyzer.h, clients/drcachesim/simulator/cache_simulator.h, clients/drcachesim/simulator/cache_stats.h, clients/drcachesim/simulator/simulator.h, clients/drcachesim/simulator/tlb.h, clients/drcachesim/simulator/tlb_simulator.h, clients/drcachesim/tests/trace_invariants.h, clients/drcachesim/tracer/instru.h, ext/droption/droption.h, make/DynamoRIOConfig.cmake.in, suite/runsuite_wrapper.pl
Enables -Wsuggest-override and uses it to replace 'virtual' with
'override' in the C++ code that was not already using 'override'.
This is done in droption.h as well.  Rather than generating macros to
support pre-C++11, I decided that enough time has passed to drop
support for pre-C++11 for users using droption.  The documentation
adds a note about this change.
=> Cleanup: use override keyword and enable warning

clients/drcachesim/common/trace_entry.h, clients/drcachesim/tests/burst_malloc.cpp, clients/drcachesim/tests/offline-burst_malloc.templatex, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/raw2trace.h
For drcachesim offline traces, a single entry cannot hold a full
64-bit value.  To record large values, we use an escape type and two
entries, which raw2trace combines back into a single final trace
entry.
Adds a test case to the burst_malloc test with large return values.
Fixes #3974
=> i#3974: Use two entries for large drcachesim trace marker values

suite/tests/client-interface/drmgr-test.c
Makes the XSAVE buffer large enough to avoid buffer overflow which was
crashing drmgr-test.
Fixes #3496
=> i#3496: Fix crash in drmgr-test

core/lib/instrument_api.h
Updates the old docs for dr_get_stats() which talk only about the
number of blocks, while we have since added various other statistics.
Issue: #2928
=> i#2928 expose stats: Update stale documentation

suite/runsuite_common_pre.cmake
Fixes this error reported by CMake caused by 53577d7 (PR #3860):
CMake Warning (dev) at C:/projects/dynamorio/suite/runsuite.cmake:275 (testbuild_ex):
A logical block opening on the line
C:/projects/dynamorio/suite/runsuite_common_pre.cmake:534 (if)
closes on the line
C:/projects/dynamorio/suite/runsuite_common_pre.cmake:562 (endif)
with mis-matching arguments.
Issue: #2924
=> i#2924 VS2017: Fix mismatched CMake if/endif

clients/drcachesim/common/options.cpp, clients/drcachesim/tracer/instru_offline.cpp, clients/drcachesim/tracer/tracer.cpp
In drcachesim, the combination of -offline and -use_physical is not
supported at this time.  We make that clear in the option docs and
with an up-front exit when the two are requested at once.
Issue: #4014
=> i#4014 offline phys: no support for -offline -use_physical combination

api/docs/intro.dox, api/docs/release.dox, core/arch/aarch64/codec.c, core/arch/aarch64/encode.c, core/arch/arm/decode.c, core/arch/arm/encode.c, core/arch/decode_fast.h, core/arch/instr.h, core/arch/instr_shared.c, core/arch/mangle_shared.c, core/arch/x86/decode.c, core/arch/x86/decode_fast.c, core/arch/x86/decode_private.h, core/arch/x86/encode.c, core/win32/callback.c, suite/tests/api/ir_x86.c
Adds rip-relative information tracking at IR levels 1-3 for
instruction references on x86, extending the existing tracking for
data references.
Adds decode_sizeof_ex() and instr_get_rel_data_or_instr_target() to
support rip-relative displacement and target handling.
Changes decode_from_copy() to preserve raw bits for all instructions,
eliminating problems where untracked encoding features are lost such
as in #4017.
Documents the changes and describes how to avoid the new behavior.
Does just that for intra-sequence cti's in the rseq native code copy.
Adds test cases to api.ir.
Implementing the same thing for AArchXX is left unimplemented, tracked
by i#4016.
Issue: #731, #3271, #3339, #4016, #4017
Fixes #731
Fixes #3271
Fixes #4017
=> i#731,i#3271: Keep IR cti+copied bits valid and re-relativized

core/arch/disassemble_shared.c, core/arch/mangle_shared.c
For i#731 with automatic re-relativization of absolute PC's, in
d6f5fca we simply kept the hardcoded offset for intra-region branch
targets in our native rseq copy.  However, with subsequent mangling
that offset can become incorrect and target the middle of an
instruction, leading to a crash.  We instead take the time to convert
these PC targets to instr_t* targets.
We also tweak the disassembly output to show the instr_t pointer value
for level 3 instructions too, since jumps can target them as well as
synthetic instructions.  This helped with verifying and debugging this
change.
Tested on an inserted system call for locally forcing rseq restarts,
which leads to system call mangling and crashes without this fix.
Issue: #731, #2350
=> i#731 re-rel: Convert native rseq PC targets to instrs

suite/runsuite.cmake
i#4024: Do not build tests in cronbuilds
Disables building of tests in cronbuilds, which then turns on
SHOW_RESULTS in the sample clients.  The prior cronbuilds had
SHOW_RESULTS off, resulting in no output, which is not very useful.
Fixes #4024
=> i#4024: Do not build tests in cronbuilds

core/arch/mangle_shared.c, core/translate.c, suite/tests/linux/rseq.c
Adds translation support for the register restores used in rseq mangling.
Adds a test of a fault/signal in native rseq code by taking advantage
of the lack of xmm support to have different behavior in the
instrumented vs native executions.
I hit this while trying to force a restart for i#4019 in a custom
test, but it could happen in regular execution with an asynchronous
signal.
Issue: #2350
=> i#2350 rseq: Handle translations in native rseq code
