DynamoRIO/dynamorio

- core/utils.c
> i#2121 date conversion: Add cast to avoid overflow.

- clients/drcachesim/tests/burst_static.cpp
- clients/drcachesim/tests/burst_threads.cpp
- clients/drcachesim/tests/offline-burst_static.templatex
- clients/drcachesim/tracer/tracer.cpp
- core/arch/arch.c
- core/config.c
- core/dynamo.c
- core/globals.h
- core/heap.c
- core/lib/dr_app.h
- core/lib/instrument.c
- core/moduledb.c
- core/synch.c
- core/unix/loader.c
- core/unix/os.c
- core/utils.c
- core/utils.h
- core/vmareas.c
- core/win32/callback.c
- core/win32/module.c
- core/win32/ntdll.c
- core/win32/os.c
- ext/drreg/drreg.c
- suite/tests/CMakeLists.txt
- suite/tests/api/static_detach.c
- suite/tests/api/static_detach.expect
- suite/tests/runmulti.cmake
This reverts commit 2dd9659475aef0db32440e1f6adb74562a5dfdbf as it breaks
the Mac build and has several Travis Linux test failures.
> Revert "i#2157 re-attach: add best-effort re-attach support"

- ext/drreg/drreg.c
Fixes a bug in 00d39c7 on keeping aflags in eax where possible, where we
leave flags in xax on a lazy non-release restore but then fail to re-use
it, leading to inconsistent drreg state.
> i#511 drreg: fix bug in aflags-in-xax

- ACKNOWLEDGEMENTS
> Addition to acknowledgements

- make/git/git_pullall.sh
- make/git/git_review.sh
Expands the pullall and review commands into scripts that give us these
features:
+ pullall pulls from both the upstream master and upstream feature branch,
if it exists, using the appropriate rebase or merge in each case.
+ review checks for the branch name matching our conventions.
Fixes #2192
> I2192 pullall and review scripts

- suite/tests/CMakeLists.txt
> i#2135: guard page execution (64 bit test)

- core/arch/instr_shared.c
- core/translate.c
This code should have been removed with 7ee7189.
Fixes #2255
> i#2255 ARM syscall mangling: Delete obsolete code referring to r10.

- core/dispatch.c
Adds code to handle go-native returning due to a racy pending alarm
signal.  We just drop the alarm as the simplest solution.
Fixes #2312
> i#2312: handle go-native returning

- ext/drreg/drreg.c
Fixes two bugs from 00d39c7 on keeping aflags in eax where possible:
1) We were failing to give up the xax register after an app aflags write.
2) If xax is unreserved but unrestored we were re-spilling it to a new
slot, leaking the old slot.
A test is forthcoming but requires a fix for i#2351 first.
> i#511 drreg: fix 2 bugs in aflags-in-xax

- core/arch/interp.c
The -native_exec_retakeover option incorrectly marks the 32-bit dynamic
linker sequence for an imported library call as a non-call, leading to loss
of control.  We fix that by using proper ordering of checks for a
native_exec gateway.
Test improvements that show this will come in as part of #2372.
Fixes #2381
> i#2381: fix loss of control on 32-bit native retakeover

- core/unix/signal.c
The big i#2089 change that made the dcontext NULL for threads we know about
but are temporarily native failed to properly handle temporarily-native
threads being synch-ed later (e.g., for detach): we will attempt to take
them over instead of suspending them, which results in asserts and crashes.
Fixes #2400
> i#2400: handle native threads during a synch

- core/unix/signal.c
Extends the -invoke_on_crash feature to also invoke the app handler on an
assert where dumpcore_mask asks for a deliberate crash.
> i#2119 app-on-crash: invoke app on assert deliberate crashes

- core/arch/arch.c
In shared_gencode_emit make the initialisation of the shared reset stub
conditional on USE_SHARED_GENCODE_ALWAYS() instead of on X86_64.
> i#1569 AArch64: Initialise the shared reset stub on AArch64.

- core/io.c
- core/iox.h
Adds support for the C99 code %z to DR's *printf routines.
Adds tests.
> Add %z support to DR's printf

- core/unix/signal_linux_x86.c
The signal used to query the xstate size from i#1937 474e93b assumed that
the signal frame's fpstate struct would be initialized, which is not always
the case depending on how DR was compiled.  We force-initialize it here by
touching an xmm register.
Fixes #2438
> i#2438: force-initialize xmm state for query signal

- clients/drcachesim/tracer/tracer.cpp
Introduces a FATAL() macro which combines the common pattern of
NOTIFY(0,...) + dr_abort() in the drcachesim tracer.
> Add FATAL macro to drcachesim

- core/arch/aarch64/clean_call_opt.c
The current behavior is to walk from the bottom instruction up to the
current top instruction to find instructions that pop registers. This
is too permissive and may remove instructions not used to save/restore
callee-saved registers, e.g. spills of local variables to the stack.
This patches switches to a more conservative approach in which requires
callee-saved registers to be popped in reverse order they have been pushed.
Both LLVM and GCC commonly use this pattern to save/restore callee-saved
registers on AArch64, but they might use different patterns if that is
more efficient. I think we should use this conservative approach
for now, and maybe make it more permissive once we have clean call
inlining implemented on AArch64 and solid test coverage.
This patch has no effect unless …
> i#1621 AArch64 CC opt: Make analyze_callee_save_reg more conservative.

- suite/tests/CMakeLists.txt
Fixes a CMake warning introduced by f578fd2b #2562
> i#2082 translate from info: fix CMake warning

- core/win32/callback.c
Fixes the VPS Windows build broken by 240b75d6.
> i#2592 stack overflow: fix VPS build

- CONTRIBUTING.md
Updates the contribution docs to remove the CLA requirement which is no
longer necessary.
Fixes #2667
> i#2667: Update docs to reflect removal of CLA requirement

- core/optionsx.h
- core/utils.c
> i2692 Delete spin_yield_mutex option

- tools/drdeploy.c
Fixes a Windows build issue on some CDash machines from 08cd899.
Issue: #2683
> i#2683 drrun output: fix Windows build issue

- clients/drcachesim/drcachesim.dox.in
- clients/drcachesim/launcher.cpp
Improves the drcachesim documentation by adding example output for each
tool, adding new sections on tracing a subset of execution, creating new
analysis tools, highlighting offline support, etc.
> Enhance drcachesim documentation

- clients/drcachesim/CMakeLists.txt
- clients/drcachesim/common/utils.h
- clients/drcachesim/reader/reader.cpp
Adds -Wimplicit-fallthrough and the clang fall-through annotation to drcachesim.
> Add switch fall-through clang annotation

- api/docs/release.dox
> i#2725 xfer under app locks: update release.dox

- core/utils.c
> i#2725 xfer under app locks: allow deletion of in-use mutex.

- .travis.yml
- core/unix/ksynch_macos.c
> i#2157 re-attach: fix the mac build broken by PR 2762

- core/arch/interp.c
- core/arch/x86/emit_utils.c
- core/globals.h
- core/lib/globals_shared.h
- core/options.c
The pull request is mostly what was there last time.  There are three more commits that were required to fix the issues identified with the pull request from last time.
> i#2717 Change the implementation of options. (#2748)

- clients/drcachesim/tests/burst_threads.cpp
Adds synchronization to avoid fewer than one thread per core in the
tool.drcacheoff.burst_threads test, to eliminate flakiness in output
matching.
> Make the burst_threads test less flaky

- api/docs/release.dox
- ext/drmgr/drmgr.c
- ext/drmgr/drmgr.h
- suite/tests/client-interface/drmgr-test.dll.c
- suite/tests/client-interface/drmgr-test.templatex
Adds the passing of user data for callbacks pertaining to syscall events. 
See #2833
> Added the passing of user data for syscall events.

- ext/drutil/drutil.c
Fixes a regression from f6e8e1c4 where drutil_insert_get_mem_addr() gets
the wrong address for a far memref that uses the destination register, due
to improper ordering of operations.
Also optimizes from two steps to one for a far memref that uses the
destination but not the scratch register and has only one of base or index.
Fixes #2913
> i#2913: fix drutil regression on far refs

- core/lib/instrument.c
The client syscall events are called out of dispatch separately from DR's
syscall handlers, so today they end up in the DR_WHERE_DISPATCH bucket.
Here we mark them as the more appropriate DR_WHERE_SYSCALL_HANDLER.
Issue: #140
> i#140 pcprof: label syscall events as in-handler

- core/unix/os.c
- suite/tests/client-interface/file_io.c
Fixes failures in DR's handling of 32-bit rlimit system calls and in the
client.file_io test: both need to use "struct rlimit64".
Adds proper syscall failure for hard limit > soft limit, and for raising
the hard limit, along with tests of those cases.  i#2980 covers allowing
raising the hard limit for privileged processes.
Issue: #2950, #2980
Fixes #2950
> i#2950: fix 32-bit rlimit failures

- core/arch/aarch64/encode.c
- core/arch/arch_exports.h
> i#2626 AArch64 encoder: Fix comment.

- clients/drcachesim/simulator/cache_simulator.cpp
> Use std namespace qualifier for string.

- core/win32/os.c
- make/utils_exposed.cmake
Temporarily strip path such that DR's win loader can handle it (xref DrMi#2138).
Issue: #3278
> i#3278 windows file path: temporarily strip dot/slash in path

- clients/drcachesim/tracer/raw2trace.cpp
- clients/drcachesim/tracer/raw2trace.h
Refactors raw2trace_t for trace-buffer-driven use rather than file-driven use:
+ Separates out a new function process_next_thread_buffer() from
process_thread_file().
+ check_thread_file() now puts the header back, so it can be
universally processed in process_next_thread_buffer() (this seek is
just once per traced thread so there are no performance concerns
like in PR #2749).
+ The thread footer is now written out in on_thread_end(), leaving
process_thread_file() only performing file-specific actions.
+ Removes {un,}read_from_thread_file(), merging them into
{unread,get}_next_entry().
+ Marks key functions as virtual and protected for subclass support.
Issue: #3230
> i#3230 split traces: refactor for buffer-based use

- clients/drcachesim/tracer/raw2trace.h
When using a drcachesim online-filtered trace (-L0_filter), a
multi-memref instruction can have one of its memrefs hit in the cache
and the other miss.  The post-processor will then expect 2 addresses
but only have 1.  The existing code did not handle this at the end of
a buffer, which we fix here.
Writing a regression test would require a non-trivial synthetic trace
which we do not have ready-made tools to generate.  I did test this on
the third-party-app trace where I encountered it.
Fixes #3310
> i#3310: Fix a drcachesim filtered trace post-processing abort

- core/arch/x86/memfuncs.asm
Expands comments on interception issues when static DR uses libc's
memcpy and memset.
Issue: #3315
> i#3315 memcpy conflict: expand comments on interception

- .travis.yml
- CMakeLists.txt
- api/docs/release.dox
Increases the OLDEST_COMPATIBLE_VERSION to 7.1 as well due to the
minor compatibility changes.
Updates the changelog and cronbuild.
> Increase version to 7.1.0

- core/win32/callback.c
Adds code to look for the OP_lea referencing the CONTEXT in
KiUserApcDispatcher rather than hardcoding a constant, as the offset has
changed on Win10-1809.
Tested on Win10-1809, Win10-1803, and Win8.1.
Issue: #3391
> i#3391: dynamically identify APC CONTEXT offset

- core/win32/os.c
Fixes breakage of the VPS build from fae84d17.
> Fix VPS build regression

- core/dynamo.c
Allow for AVX-512 when compiling unit tests.
Issues: #1312, #3169
> i#1312 AVX-512 support: Allow for AVX-512 when compiling for unit tests.

- ext/drutil/drutil.c
Fixes the pointer size in 64-bit builds when reading CPUID and writing a pointer.
Special treatment is given to xbx because of another bug (or feature) of older GNU
toolchains that are using ebx for fPIC, causing a compile error when constraining
the inline asm doing CPUID to ebx.
Fixes #3478
> i#3478: Fix 64-bit release build reading CPUID in drutil.

- core/fcache.c
- core/heap.c
Changes the -heap_commit_increment and -cache_commit_increment options
to no longer be strictly required to be smaller than all unit sizes,
which made it a pain to change the increment size without also
specifying every unit parameter, of which there are many.  It was also
impractical to raise the heap increment on UNIX due to the signal
special heap's maximum size.  Now, each unit simply caps its own
increment size to a maximum of its unit size.
Also fixes a regression: an assert when using -no_vm_reserve.
Tested by running with "-no_vm_reserve -heap_commit_increment 8M
-cache_commit_increment 8M".
Fixes #3507
> i#3507: Relax commit increment options

- core/arch/x86/decode_table.c
- core/arch/x86/instr_create.h
> Adjust adcx/adox table entries to reflect the src/dst operand.

- suite/tests/api/ir_x86.c
Re-factors only. Renames the obsolete REG enums in api.ir test to DR_REG. AVX-512 tests
need to use the DR_REG names anyway, since we stopped providing REG versions for new
AVX-512 registers.
Issue: #1312
> i#1312 AVX-512: Re-factor, rename obsolete REG_ to DR_REG_ in test api.ir.

- core/fcache.c
Puts in three changes to avoid a reset even when it's disabled:
1) Adds a release-build check for reset being enabled in schedule_reset().
2) Adds a release-build check for reset being enabled in
fcache_reset_all_caches_proactively().
3) Clears reset_pending on detach.
Tested manually on an application that first hit this unwanted reset.
Fixes #3645
> i#3645: Avoid a reset even when disabled

- core/arch/x86/decode_table.c
Removes a wasted line from every evex_W_extensions table entry.
Issue: #1312
> i#1312 AVX-512 support: Formatting of evex_W_extensions table.

- core/win32/loader.c
Fixes the VPS build broken by 7bbe9ee.
Issue: #36333
> i#3633 win10-1903: Fix VPS build

- api/samples/memtrace_x86.c
Quick fix to misspelling typo in comment.
> Fix typo in comment

- clients/drcachesim/simulator/cache_simulator.cpp
- clients/drcachesim/simulator/snoop_filter.h
Adds coding style and memory leak fixes to 92599ca473f25f29d885b22.
Issue: #1726
> i#1726 coherence support: Coding style and memory leak fixes.

- CMakeLists.txt
- make/CMake_events.cmake
Preparation to fix for https://github.com/DynamoRIO/dynamorio/issues/638
CMake message compiler exists only in Visual Studio.
It shouldn't broke anything.
Signed-off-by: ofry <tim4job@bmail.ru>
> Preparation to fix for https://github.com/DynamoRIO/dynamorio/issues/638

- api/docs/release.dox
- core/lib/instrument.c
- core/lib/instrument_api.h
- suite/tests/client-interface/thread.dll.c
Adds a new API routine dr_atomic_add64_return_sum() to go along with
dr_atomic_add32_return_sum().
Adds a sanity test.
> Add dr_atomic_add64_return_sum

- clients/drcachesim/reader/reader.cpp
Since 75b13f20 did not fix every instance of this assert, I'm adding
diagnostics here to help figure out the case that remains on Appveyor.
Issue: #3320
> i#3320 cachesim assert: Add diagnostics for Appveyor

- core/arch/x86/emit_utils.c
- core/monitor.c
Fixes an assert when we start building a trace but then have to abort
due to the private copy failing.
There is still a long-term problem here with the private copy failure
potentially happening over and over: that is covered by #4038.
Tested on the linux.rseq tests with new (forthcoming) instrumentation for
#4019 which reliably hit this assert.
Issue: #2989, #4019, #4038
Fixes #2989
> i#2989: Fix trace counter decrement assert

- core/loader_shared.c
- core/win32/loader.c
Extends #4050's static TLS support to the executable itself when
linked with static DR.
Tested on the tool.drcacheoff.burst_static test with VS2017, which
will soon become a regression test when we move to VS2017.
Fixes #4052
> i#4052: Support private static TLS in static DR on Windows

- core/heap.c
Adds a check for standalone_library when STATIC_LIBRARY is defined
inside the global heap routines.  For static DR in standalone mode,
libc malloc and free are used instead of DR's allocator, for two
reasons: better multi-threaded performance and better interoperability
with tools like sanitizers.
Only global alloc needs this because standalone mode never creates
thread contexts.  This is limited to static DR because we can use a
direct call and avoid pulling in libc dependencies into shared-library
DR, which will not work.  Most standalone uses should prefer static DR
in any case.
Fixes #3316
> i#3316: Use libc malloc+free for static DR in standalone mode

- ext/drsyms/drsyms_macho.c
The value for an indirect symbol is the string table index for the
name of the other symbol it points to.  We should add an entry for
that other name with the value of the target but until someone has
time to put in a scheme for that, we skip them to avoid returning
bogus addresses.
Issue: #4081
> i#4081 macho syms: Skip indirect symbols

- api/docs/release.dox
- ext/drreg/drreg.c
- ext/drreg/drreg.h
- suite/tests/CMakeLists.txt
- suite/tests/client-interface/drreg-end-restore.dll.c
- suite/tests/client-interface/drreg-end-restore.expect
Adds finer controls for drreg lazy restoration.
Fixes #4120
> i#4120: Add finer controls for drreg restoration

- ext/drreg/drreg.dox
Updates the .dox file of drreg to present the correct title.
Issue #2891
> i#2891: Tidies .dox file of drreg

- core/unix/module_elf.c
While elf_hash_lookup correctly skips undefined symbols,
gnu_hash_lookup was not, causing it to claim to find symbols with
addresses at the library base.
Tested on drcachesim -record_heap running /bin/ls where before the fix
it claimed "malloc" was at the module base.
Fixes: #4152
> i#4152: Exclude undefined symbols in gnu_hash_lookup

- ext/drsyms/drsyms_windows.c
Adds checking that SymFromName's return value is within the
being-queried module bounds.
Tested on the drcachesim fib test.
Fixes #4153
> i#4153: Fix bogus addresses returned by drsyms

- ext/drwrap/drwrap.c
Cleanup: removes the unused call_site_table.
Issue: #4070
> i#4070 drwrap-site: Remove unused call_site_table

- api/docs/bt.dox
- core/arch/instr.h
Adds a section to the IR docs on the new no-alloc IR feature.
Issue: #4180
> i#4180 no-alloc IR: Add documentation

- suite/runsuite_wrapper.pl
Temporary patched runsuite_wrapper.pl on AArch64 Jenkins
CI was distorting test status.
Issue: #4189
> i#4189 Update AArch64 accepted failures test list

- .travis.yml
- CMakeLists.txt
- api/docs/release.dox
Makes the necessary changes to prepare for 8.0.0 release.
> Prepare 8.0.0 DR release

- core/arch/x86/instr.c
In x86, jcxz has an 0x67 prefix. In x64, jecxz has an 0x67 prefix.
The code in instr_is_cti_short_rewrite() does not take that into
account when the pc argument is not NULL.
The code in instr_invert_cbr does not take that into account when
verifying and inverting the cbr, using wrong offsets in that case.
This fix checks for the 0x67 prefix in both unaddressed cases so
that the checks against the instruction bytes pass as they should.
Issue: #4299
> i#4299: Fix cti_short_rewrite detection and inversion for addr-prefixed jcxz/jecxz

- core/arch/x86/x86.asm
- suite/tests/client-interface/cleancall.dll.c
> i#4301: Fix x86-32 Linux stack alignment before dynamo_process_exit

- core/heap.c
- suite/tests/client-interface/alloc.dll.c
- suite/tests/client-interface/cleancall.dll.c
> i#4335: Fix out of memory error due to allocation of more than 2GB in unreachable heap

- suite/tests/client-interface/winxfer.templatex
Adds more output patterns for the client.winxfer test based on
observed output on Appveyor.
Issue: #4058
> i#4058 flaky tests: Allow more winxfer patterns

- core/fcache.c
Increases the fcache free list header and footer sizes to 32 bits,
supporting larger coalesced free regions.  This is required for larger
cache unit sizes on >4K-sized-page machines.  The only downside is
that the minimum fragment size goes from 16 bytes to 20 bytes, but
only a few 32-bit fragments are that small in any case so it is a
negligible cost.
Tested on a 64K-page machine to confirm it fixes the assert.
Fixes #4434
> i#4434: Increase fcache free list sizes to 32 bits

- core/unix/signal.c
Checks for and drops delayable signals that arrive while a thread is
exiting, which is a fragile time with data structures in inconsistent
states.
Tested on the threadsig app with 50 threads, where the assert was seen
every time before on a local machine and is now gone.  I do not think
we can reliably happen to hit this with a regression test on the CI
machines where core counts are lower and load is higher, and we can't
easily force it with application synchronization since it relies on
signals arriving while in DR code, so I'm living with just the manual
test.
Fixes #4438
> i#4438: Drop delayable signals arriving during thread exit

- clients/drcachesim/tracer/tracer.cpp
Do not try to get the application value of the stolen register on the
jump barrier used for drreg parity in filtered drcachesim
instrumentation.
Enable thread filtering on non-x86: there is no missing support there.
Tested by locally enabling the tool.drcacheoff.burst_threadfilter test
(it is disabled for AArch64 because of the #2007 link failure in some
toolchains), working around #4468 with "-steal_register 25", and
confirming that the drreg failure disappears with the fix here.
This is needed for the forthcoming new global filter for drcachesim
(#4462), in addition to the thread filter feature.  An
enabled-on-AArch64 test should be added as part of that feature to
serve as a regression test here, if #2007 has not been resolved by
then to enable the thread filter test.
Issue: #4461, …
> i#4461: Skip stolen register on drcachesim filter barriers

- core/lib/instrument_api.h
Signed-off-by: Itay Bookstein <itay.bookstein@nextsilicon.com>
> Improve cleancall flags documentation

- core/unix/signal.c
On ARM, the kernel xfer event code added extra calls to
canonicalize_pc_target(), which can't be called twice: the ISA mode is
lost then.  We fix that here by refactoring the code to call just
once.
Tested on the client.signal test, which is ported and enabled in a
forthcoming PR for #4516.
Issue: #4516, #4522
Fixes #4522
> i#4522: Fix wrong ISA modes on signal redirect/delivery

- core/ir/x86/decode_table.c
> Remove duplicated reqL1 in decode table.

- core/win32/os.c
Removes what was thought of as a sanity check for the allocation base
changing in DR's internal query loop, but it turns out there are cases
of anomalous bases for which failing the query has disastrous
consequences.  Just ignoring the anomaly and moving on is the
solution.
Tested on the Github Actions Windows Server 16 images.
Issue: #4588, DynamoRIO/drmemory#2328
Fixes #4588
> i#4588: Handle anomalous alloc bases in Windows query loop

- .github/workflows/ci-package.yml
Fixes a multi-line error in Windows zip commands
Issue: #4549
> i#4549 GA CI: Fix package script error

- .github/workflows/ci-aarchxx.yml
This is a test PR to check behaviour of GA notification action for PRs created from forked repositories
> i#4549: fork repo PR notif testing

- core/translate.c
Fixes a translation bug in translate_walk_restore() where it just
skips GPR restores if it's in between application instructions.  Since
on AArchXX we have many of these cases of cross-app-instr spills (due
to restore elision for back-to-back spills), the assumption that there
will be no outstanding spills does not hold.
The solution is to move the condition to only encompass the stack
pointer restore, while the GPR restores should always be done.
This was caught by the forthcoming common.broadfun-stress test, which
will serve as the regression test once it is added after all other
bugs it finds are addressed.
Issue: #4680
> i#4680 aarch xl8: Fix GPR restore bug on cross-app spills

- core/drlibc/drlibc_module_elf.c
Fixes a problem where the final-segment check for
DR_MAPEXE_SKIP_WRITABLE fails to check the memory size and assumes it
is just the page extension of the file size.
This fixes an assert coming from PR #4733 when run on x86 on AArch64
traces.
Fixes #4731
> i#4731: Fix DR_MAPEXE_SKIP_WRITABLE for cross-arch

- core/unix/signal.c
QEMU prior to 5.0 has a signal number mapping bug where it ends up
failing its app's attempts to invoke sigaction for signals 33 and 64.
We relax DR's assert on sigaction failure when -xarch_root is set for
those numbers, trying to continue for best-effort execution with a
syslog warning.
Tested manually on 4.2.0 and on the forthcoming GA CI QEMU testing in
PR #4747.
Fixes #4627
> i#4627: Work around QEMU signal number bugs

- .github/workflows/ci-aarchxx.yml
Attempts to fix the recent aarchxx job failures by running "apt-get
update" prior to install.
> Fix stale apt version with update

- .github/ISSUE_TEMPLATE/bug_report.md
Changes the bug template title to make it more clear it should be
user-edited.
> Reword bug template title for clarification

- api/docs/CMake_rundoxygen.cmake
Updates the menu entries for directory pages, replacing the hashed
names from the treeview generation with the hashed names for the
embedded generation.
Issue: #4111
> i#4111 web: Update directory page hashed names

- api/docs/CMake_rundoxygen.cmake
Adds search entries for section headers which target the anchor links
directly.
Issue: #4111
> i#4111 web: Add direct section searches

- core/ir/aarch64/codec.txt
- core/ir/aarch64/instr_create_api.h
- suite/tests/api/dis-a64.txt
- suite/tests/api/ir_aarch64.c
- suite/tests/api/ir_aarch64.expect
Add handling of:
- FCVTZS (scalar, fixed-point)
- FCVTZS (vector, fixed-point)(scalar)
Issue: #2626, #4848
> i#4848 AArch64 GPR Decode: Add FCVTZS fixed-point

- core/arch/arch.c
Fixes a failure to insert the vsyscall hook by passing the full size
of the VDSO to mprotect, as recent kernels refuse to split the region.
Tested on an Ubuntu20 VM where the hook was observed to now succeed
with this fix.
Fixes #5085
> i#5085 vsys hook: Pass full vdso size to mprotect

- api/docs/samples.dox
Fixes several file name errors and missing samples in the list in the
docs.
> Update samples list in docs

- ext/drbbdup/drbbdup.c
Add code that lazily initialises the code cache for dynamic handling.
Issue: #3995
> i#3995: Add lazy initialisation

- api/docs/developers.dox
- api/docs/multi_trace_window.dox
Adds a new design document discussing decisions and tradeoffs for the
multi-window trace feature.
Issue: #3995
> i#3995 multi-window: Add design doc for multi-window-trace feature

- core/unix/os.c
This reverts commit 406b20a2e15084146cb89840812a55ec475e48c0.
That commit broke module loading on Android, with it system libraries like libc.so and others are no longer registered and reported in module init events.
> Revert "Fix module_walk_program_headers failure on Android partial mmap. (#5277)"

- api/docs/debug_memtrace.dox
Updates the drcachesim offline raw format debugging docs with udpated
version entry information.
> Update drcachesim offline doc version

- suite/tests/api/sort-dis-a64.py
> i#2626: Sort dis-a64.txt and and program to sort it again if needed

- api/docs/release.dox
> i#3044: Add release note for new element vectors

- api/docs/building.dox
https://stackoverflow.com/questions/28350214/how-to-build-x86-and-or-x64-on-windows-from-command-line-with-cmake
> Adjusting documentation

- core/ir/aarch64/codec_sve.txt
- core/ir/aarch64/instr_create_api.h
- suite/tests/api/dis-a64-sve.txt
- suite/tests/api/ir_aarch64_sve.c
```
CNTD    <Xd>{, <pattern>{, MUL #<imm>}}
CNTH    <Xd>{, <pattern>{, MUL #<imm>}}
CNTW    <Xd>{, <pattern>{, MUL #<imm>}}
DECW    <Xdn>{, <pattern>{, MUL #<imm>}}
DECW    <Zdn>.S{, <pattern>{, MUL #<imm>}}
INCB    <Xdn>{, <pattern>{, MUL #<imm>}}
INCD    <Xdn>{, <pattern>{, MUL #<imm>}}
INCD    <Zdn>.D{, <pattern>{, MUL #<imm>}}
INCH    <Xdn>{, <pattern>{, MUL #<imm>}}
INCH    <Zdn>.H{, <pattern>{, MUL #<imm>}}
INCW    <Xdn>{, <pattern>{, MUL #<imm>}}
INCW    <Zdn>.S{, <pattern>{, MUL #<imm>}}
SQDECB  <Xdn>, <Wdn>{, <pattern>{, MUL #<imm>}}
SQDECB  <Xdn>{, <pattern>{, MUL #<imm>}}
SQDECD  <Xdn>, <Wdn>{, <pattern>{, MUL #<imm>}}
SQDECD  <Xdn>{, <pattern>{, MUL #<imm>}}
SQDECD  <Zdn>.D{, …
```
> i#3044 AArch64 SVE codec: Add remaining constrained predicate counts

- core/ir/aarch64/codec.c
- core/ir/aarch64/codec.h
- core/ir/aarch64/codec_sve.txt
- core/ir/aarch64/instr_create_api.h
- core/ir/aarch64/opnd_defs.txt
- suite/tests/api/dis-a64-sve.txt
- suite/tests/api/ir_aarch64_sve.c
```
FABD    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
FABS    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
FDIV    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
FDIVR   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
FMAD    <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
FMULX   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
FNEG    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
FNMAD   <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
FNMLA   <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>
FNMLS   <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>
FRECPE  <Zd>.<Ts>, <Zn>.<Ts>
FRECPS  <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
FRECPX  <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
FRSQRTE <Zd>.<Ts>, <Zn>.<Ts>
FRSQRTS <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
FSCALE  <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts> …
```
> i#3044 AArch64 SVE codec: Add floating-point arithmetic instrs

- .github/workflows/ci-aarchxx.yml
- .github/workflows/ci-clang-format.yml
- .github/workflows/ci-osx.yml
- .github/workflows/ci-riscv64.yml
- .github/workflows/ci-windows.yml
- .github/workflows/ci-x86.yml
Adds "merge_group" as a CI trigger to our 6 GA CI auto-test workflows.
Issue: #5873
> i#5873: Add merge_group CI triggers

- clients/drcachesim/tests/raw2trace_unit_tests.cpp
- clients/drcachesim/tests/view_test.cpp
- clients/drcachesim/tracer/raw2trace.h
Refactors test code to move common logic to raw2trace.h to enable easier
code sharing among tests.
> Move test_module_mapper_t to raw2trace.h for code sharing

- clients/drcachesim/tools/invariant_checker.cpp
The "Branch target not immediately after branch" drmemtrace invariant check is relaxed here for instruction-filtered traces.
Tested:
$ ctest --repeat-until-fail 1000 -V -R rseq-filter
Fixes #5972
> i#5972: Relax delayed branch check for ifiltered traces

- clients/drcachesim/scheduler/scheduler.cpp
Fixes two locking issues with the scheduler:
+ Adds a missing input lock for stream_t::next_record
+ Adds a missing conditional on maintaining the ready_ queue which is only used for certain scheduling modes.
Tested: Ran ThreadSanitizer 500x on a test of analyzer parallel mode and on a test of the any-output scheduler mode.
Issue: #5843
> i#5843 scheduler: Add missing lock conditional and guard

- core/arch/riscv64/riscv64.asm
This patch optimizes some basic assembly functions and adds some comments to improve readability.
Issue: #3544
> i#3544 RV64: Small improvments to some assembly functions

- clients/drcachesim/common/memref.h
- clients/drcachesim/common/trace_entry.h
- clients/drcachesim/drpt2trace/pt2ir.h
- clients/drcachesim/reader/compressed_file_reader.cpp
- clients/drcachesim/reader/file_reader.h
- clients/drcachesim/reader/ipc_reader.h
- clients/drcachesim/reader/snappy_file_reader.cpp
- clients/drcachesim/simulator/caching_device.cpp
- clients/drcachesim/simulator/tlb_simulator.cpp
- clients/drcachesim/tests/record_filter_unit_tests.cpp
- clients/drcachesim/tests/stride_benchmark.cpp
- clients/drcachesim/tools/reuse_distance.h
- clients/drcachesim/tools/view.cpp
- clients/drcachesim/tracer/drmemtrace.h
- clients/drcachesim/tracer/instru.cpp
- clients/drcachesim/tracer/kcore_copy.cpp
- clients/drcachesim/tracer/raw2trace.cpp
Fixes a bunch of spelling errors identified by an external build lint checker.
> Fix spelling errors

- api/docs/deployment.dox
issue: [#725](https://github.com/DynamoRIO/dynamorio/issues/725)
> i#725: Update the documentation to include how to detach on Windows

- .github/workflows/ci-docs.yml
- .github/workflows/ci-package.yml
- CMakeLists.txt
- api/docs/new_release.dox
Increases the current version and the oldest compatible version to 10.0.
> Increase the version to 10.0

- core/ir/riscv64/instr.c
Implements `instr_branch_type()`, which is called during the execution of a simple program. Since compressed instructions have all the implicit operands listed in instr_t, they don't need any special treatment.
> i#3544 RV64: Refine instr_branch_type

- core/arch/riscv64/emit_utils.c
This patch implements the handling of compressed instructions in `exit_cti_reaches_target()` and `patch_branch()` that are encountered when running a simple libc program.
Issue: #3544
> i#3544 RV64 emit utils: Add support for compressed instructions

- clients/drcachesim/tests/raw2trace_unit_tests.cpp
- clients/drcachesim/tracer/raw2trace.cpp
If the thread trace ends mid-rseq-region, dump the buffer instead of losing not only the rseq sequence so far but also the thread exit record.
Adds a unit test.  Also tested on a real trace with this issue.
Fixes #6444
> i#6444 no exit: Dump rseq buffer on mid-region thread end

- ext/drx/scatter_gather_aarch64.c
I have rewritten a lot of the implementation of
drx_expand_scatter_gather() in an attempt to make the code easier to follow.
Issue: #5036
> i#5036 Refactor AArch64 scatter/gather expansion

- api/docs/test_suite.dox
Expands the docs on using tmate with detailed steps including removing other jobs and using a label to zero in on just one test.
> Add more detailed docs on using tmate

- README.md
- api/docs/tool.gendox
Noticed the 404 while searching documentation.
> Updated drstrace URL

- api/docs/scatter_gather_emulation.dox
Adds details of the AArch64 scatter/gather expansion to the scatter/gather expansion developer documentation.
Issue: #5036
> i#5036 Update scatter/gather docs with AArch64 details

- clients/drcachesim/tools/view.cpp
Adds drmemtrace view tool support for the 3 new markers added in PR #6826.
Issue: #6822
> i#6822 unscheduled: Add drmemtrace view support for new markers

- README.md
- api/docs/home.dox
Adds the newly-open-sourced GWPSan to the list of external tools that leverage DynamoRIO.
> Add GWPSan to the external tool list

- suite/tests/CMakeLists.txt
- suite/tests/client-interface/cbr-retarget.c
- suite/tests/client-interface/flush.c
- suite/tests/client-interface/flush.dll.c
> i#4474: Port client.flush and client.cbr-retarget tests to AARCH64

- suite/tests/CMakeLists.txt
- suite/tests/client-interface/strace.dll.c
Port client.strace test to AARCH64.
Issue: #4474
> i#4474: Port client.strace test to AARCH64

- suite/tests/CMakeLists.txt
- suite/tests/client-interface/thread.dll.c
Port client.thread test to AARCH64.
Issue: #4474
> i#4474: Port client.thread test to AARCH64

- suite/tests/CMakeLists.txt
- suite/tests/client-interface/nudge_ex.dll.c
Port client.nudge_ex test to AARCH64.
Issue: #4474
> i#4474: Port client.nudge_ex test to AARCH64

- suite/tests/CMakeLists.txt
- suite/tests/security-common/retexisting.c
Port security-common.retexisting test to AArch64.
Issue: #4474
> i#4474: Port security-common.retexisting test to AArch64

- suite/tests/CMakeLists.txt
- suite/tests/security-common/selfmod2.c
Port security-common.selfmod2 test to AArch64.
Issue: #4474
> i#4474: Port security-common.selfmod2 test to AArch64

- .github/workflows/ci-riscv64.yml
- api/docs/building.dox
- core/ir/riscv64/codec.py
- suite/tests/api/ir_riscv64.expect
Currently, we downloaded the cross-compile packages from unstable Debian sid, this PR changed it to a stable source Ubuntu 24.04 to avoid errors.
Issue: #6900
> i#6900 RV64: Fix CI build

- .github/workflows/ci-docs.yml
- .github/workflows/ci-package.yml
- CMakeLists.txt
Increases the current version and the oldest compatible version to 11.0.
> Increase the version to 11.0

- api/docs/release.dox
Creates a new changelog section for post-11.1 changes.
> Update changelog for 11.1 release

- api/docs/release.dox
Creates a new changelog section for post-11.2 changes.
> Update changelog for 11.2 release 

- core/arch/mangle_shared.c
This makes the test code_api|linux.signal_pre_syscall pass.
Issue: #3699
Change-Id: I3c6f51b36ee68f2e32b931e528c064a859aa52b3
> i#3699 ARM: Make some ASSERTs sensitive to dr_isa_mode_t.

- CMakeLists.txt
This may make it easier to debug CI problems.
> CMakeLists.txt: Print CMake version.

- core/ir/opnd_shared.c
Implements `reg_set_value_ex_priv` for A64, mirroring `reg_get_value_ex`
Issue: #1569
> i#1569 a64: Implement reg_set_value_ex_priv

- api/docs/release.dox
Follow up from: https://github.com/DynamoRIO/dynamorio/pull/7314#issuecomment-2748420081
Added a release note describing the changes in #7314.
> i#7287 Cache Policies: Added a Release Note on the Refactoring.

- ext/drsyscall/drsyscall_linux.c
#7389  was based on DrMemory code base prior to DynamoRIO/drmemory#2546
This PR ports DrMemory PR2546 over to DynamoRIO.
Issue:: #7303
> i#7303 drsyscall: Pull in latest drmemory/drsyscall changes.

- suite/tests/api/detach_state.c
All parts of `api.detach_state` now support AArch64.
Issues: #7576, #4698
Fixes: #4698
> i#7576 detach: Port thread_check_xsp_* tests to AArch64
