clients/drcachesim/launcher.cpp

Fixes a deref of a nullptr causing crashes on Windows with drcachesim
-offline.  The launcher on Windows waits for the child to exit and
then prints stats from the analyzer, but there is no analyzer for
-offline.
Fixes #3137

i#3137: Fix drcachesim -offline launcher crash

---

api/docs/bt.dox

Updates a now-stale detail in the rseq limitation docs: we no longer
try to analyze read-write sequences for restoring state for the second
rseq execution.  We do still limit our checkpointing to
general-purpose registers.
Issue: #2350

i#2350 rseq: Update rseq limitation docs

---

ext/drcontainers/drvector.c
suite/tests/client-interface/drcontainers-test.dll.c

Fixes a bug that occurs when the size of an empty vector is increased to set a value at index 0.
Fixes #4036

i#4036: Fix size increase of empty drvector

---

api/docs/bt.dox
core/arch/emit_utils_shared.c
core/arch/instr.h
core/arch/instr_shared.c
core/emit.c
core/lib/instrument.c
core/lib/instrument_api.h
core/link.h
tools/windbg-scripts/linkstub_flags

Removes the dr_add_prefixes_to_basic_blocks() +
instr_branch_set_prefix_target() feature and its flags
LINK_TARGET_PREFIX and INSTR_BRANCH_TARGETS_PREFIX.  These were
already under UNSUPPORTED_API and not supported.  Removing the feature
frees up a linkstub flag for #4038.

i#4045 cleanup: Remove the unsupported target-prefix feature

---

core/arch/emit_utils_shared.c
core/arch/instr.h
core/arch/instr_shared.c
core/arch/interp.c
core/arch/x86/emit_utils.c
core/emit.c
core/lib/statsx.h
core/link.h
core/monitor.c
core/options.c
core/optionsx.h
make/configure.cmake.h
tools/windbg-scripts/linkstub_flags

Adds new flags LINK_PADDED and INSTR_BRANCH_PADDED and uses them to
mark exit cti padding added for safe patching.  Reads the link flag in
decode_fragment() to remove the padding during trace building.  This
avoids prior trace barriers from extra basic block exits from inlined
syscall exits, rseq mangling, and client changes.
Removes the option and stats around -pad_jmps_mark_no_trace which is
no longer needed.
Tested on the linux.rseq test which now successfully traces through
the rseq mangling.
Fixes #4038

i#4038: Mark exit cti padding and remove it when trace building

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/tests/offline-rseq.templatex
clients/drcachesim/tests/trace_invariants.cpp
clients/drcachesim/tracer/raw2trace.h
core/globals.h
core/translate.c
core/translate.h
core/unix/signal.c
suite/tests/CMakeLists.txt
suite/tests/linux/rseq.c

When a signal occurs inside an rseq region, DR now provides the actual
interruption PC to the kernel xfer event (but not the signal event, to
match kernel behavior).  This is required to accurately place the
signal in a drmemtrace offline trace.
What this looks like:
Before:
0x00007fe36b1ea8f1  74 02                jz     $0x00007fe36b1ea8f5
0x00007fe36b1ea8f3  0f 0b                ud2a
0x00007fe36b1ea8f5  83 05 74 38 00 00 01 addl   $0x01, <rel> 0x00007fe36b1ee170
<marker: kernel xfer to handler>
<marker: timestamp 13224196441528495>
<marker: tid 74400 on core 0>
0x00007fe36b1ea85c  55                   push   %rbp
After:
0x00007f15e71d78f1  74 02                jz     $0x00007f15e71d78f5
0x00007f15e71d78f3  0f 0b                ud2a
<marker: kernel xfer to handler>
<marker: timestamp …

i#4041: Provide actual rseq interruption PC to clients

---

clients/drdisas/CMakeLists.txt

Fixes a build race by adding a missing api_headers dependence to
drdisas.
Fixes #4050

i#4050: Add api_headers dependence to drdisas

---

core/synch.c
core/win32/callback.c
core/win32/os.c

Fixes crashes on detach by walking the takeover_table on exit and
setting the context back to the interruption point for threads that we
tried to attach but were never scheduled.
Also adds a revert point in thread_attach_setup() if
init_apc_go_native() is set, for threads that are scheduled during
detach.
Tested on the tool.drcacheoff.burst_static test with VS2017, which
will soon become a regression test when we move to VS2017 (#2924).
Fixes #4053

i#4053: Restore attached-but-never-scheduled threads on exit

---

clients/drcachesim/tools/opcode_mix.cpp
clients/drcachesim/tools/opcode_mix.h

Replaces the DR mutex in the drcachesim opcode_mix tool with a
std::mutex.  This provides better interoperability with sanitizers and
other tools.
Issue: #3316

i#3316 standalone isolation: Remove DR mutex from opcode_mix

---

core/drlibc/drlibc_module_elf.c
core/heap.c
core/unix/loader.c
core/unix/os.c
ext/drsyms/CMakeLists.txt

Reserves 4MB instead of just 4KB for the initial reservation for
-emulate_brk, to avoid an mmap (such as a client lib) blocking the brk
and the app running out during early init, when it can't recover and
can crash.
Fixes two related issues:
+ -vm_base_near_app was not checking for overlap with the app to see whether
the default -vm_base will work.  Without this fix my test below does not
reproduce the bug.
+ Sets the preferred base for drsyms to 0x76000000 for UNIX (it was already set
for Windows) to avoid colliding with end-user clients like drmemtrace.
Tested on a static app with a certain size where libdrmemtrace.so
truncates the brk and reproduces the crash:
$ clang hello.c -g -o hello-static -static -Wl,-Ttext=0x71f54000
$ bin64/drrun -t drcachesim -dr_ops "-vm_base_near_app …

i#3982: Increase size of initial brk reservation

---

core/arch/x86/x86.asm

Removes the use of sysenter when building on x86_64 in order to avoid compilation errors.
The use of the sysenter gateway is most likely never used on 64-bit. Therefore, patching out sysenter should be okay.
Fixes #4066

i#4066: patch out sysenter on x86_64

---

clients/drcachesim/launcher.cpp
core/nudge.c
suite/tests/CMakeLists.txt
suite/tests/tools.h
suite/tests/win32/tls.c

Expands the pop-up disabling in drcachesim's launcher to warnings and
errors as well as asserts.
Applies the same MSVC message box disabling to the tests by adding it
to INIT() in tools.h.
Tested on win32.tls.exe which asserts on Win10.
Also fixes the assert in win32.tls on win8+ by switching from raw
NtCreateThread to high-level thread creation, with an allowance added
to the core to let this test in DEBUG target our nudge handler.  This
also makes it easy to enable the test for 64-bit mode after all that
low-level code is removed.
Issue: #4067

i#4067 Appveyor hangs: Disable popups in Windows tests

---

core/nudge.c
suite/tests/runall.cmake

Fixes two asserts involving nudge threads swapping to app state and
then accessing privlib TLS and other state.
Adds timeouts to each step in runall.cmake to avoid hangs.
Adds identification of an assert to runall.cmake.
Issue: #4074, #4059
Fixes #4074

i#4074: Fix nudge_test asserts and add timeouts

---

clients/drcachesim/tests/TLB-threads.templatex
clients/drcachesim/tests/coherence.templatex
clients/drcachesim/tests/threads-with-config-file.templatex
clients/drcachesim/tests/threads.templatex
suite/tests/CMakeLists.txt
suite/tests/client-interface/annotation-concurrency.c

Parametrizes the client.annotation-concurrency test to optionally take
in the matrix size and iteration count.  Changes the 4 drcachesim
tests that use this application to pass in a 128 size and 5
iterations, instead of the default 512 and 10, shrinking their
execution time by 7x.
Issue: #4059

i#4059 faster Appveyor: Shrink drcachesim Jacobi tests

---

suite/runsuite.cmake
suite/tests/CMakeLists.txt

For Appveyor PR's (master merges remain unchanged):
+ Disables building tests for the 64-bit release build, since we're
not running those (only running on Linux).
+ Disables less-differentiated tests for 32-bit: removes most from
each group of tool.drcachesim, tool.drcpusim, tool.[^d],
client.annotation-*.
Issue: #4059

i#4059 faster Appveyor: Disable rel test build + some 32-bit tests

---

clients/drcachesim/simulator/cache_miss_analyzer.cpp
clients/drcachesim/simulator/cache_stats.cpp
clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/tracer/instru.h

This removes some underscores from 5ed1a118e that were placed where we
do not want them: in function parameters.
Issue: #4049

i#4049: Cleanup: Trailing underscore in parameters

---

core/unix/loader.c

Listing "esp" in an inline asm clobber list is now deprecated.  The
asm block in question does restore esp, so we are fine just removing
the entry.
Fixes #4086

i#4086: Fix inline asm warning

---

.appveyor.yml
.travis.yml
suite/runsuite_wrapper.pl
third_party/vera++/use_vera++.cmake

Switches to a separate invocation of package.cmake for cronbuilds, to
make them look like release packages.
Checks out Dr. Memory to include it in the package.
Fixes #2861

i#2861: Build cronbuilds as official packages

---

.travis.yml
CMakeLists.txt
suite/runsuite_wrapper.pl

If the build number is 0, we omit it from the package name, rather than appending it.
.travis.yml now takes in VERSION_NUMBER and uses it directly.  There
is no more TAG_SUFFIX: VERSION_NUMBER has to include the build number
if that's desired, and that will be part of the tag as well.
If VERSION_NUMBER is not set it uses the default as before.
runsuite_wrapper.pl parses VERSION_NUMBER and if it has a -NNN it passes that
as the build= arg to package.cmake.  It also passes a version= argument.
Testing:
$ TRAVIS_EVENT_TYPE=cron ~/dr/git/src/suite/runsuite_wrapper.pl travis 64_only
Running ctest -VV -S "/home/bruening/dr/git/src/suite/../make/package.cmake,travis;64_only;build=0;invoke=/home/bruening/dr/git/src/suite/../drmemory/package.cmake;drmem_only"
$ VERSION_NUMBER=8.1.2 …

i#2861 cronbuilds: Add control over version and build numbers

---

.travis.yml
suite/runsuite.cmake
suite/tests/CMakeLists.txt

We no longer support 32-bit Mac as it does not really exist anymore.
Issue: #1979

i#1979 Mac64: Update Travis to test 64-bit Mac and not 32-bit

---

suite/tests/CMakeLists.txt

Drops the -trace_after_instrs flag from 50K to 20K to ensure it will
hit the 2nd trigger on shorter executions such as on AArch64.
Issue: #2892

i#2892 A64 tests: Fix flakiness in delay-simple test

---

core/vmareas.c

Adds support for start==end in vmarea binary_search.
Adds some unit tests.
Issue: #4031

i#4031 empty vmareas: Handle start==end in binary_search

---

.travis.yml

The 32-bit clang build does not provide much value, since most
clang-only warnings show up in the 64-bit build.  We remove the 32-bit
here to save Travis resources.

Remove 32-bit clang build from Travis

---

core/vmareas.c

Fixes a bug where flushing 0..-1 found only the very first code
region, due to passing 0..0 to binary_search.
Adds a unit test and an assert on passing 0..0 in the future.
Fixes #4097

i#4097: Fix flush-the-world code region locating

---

core/module_shared.h

Fixes the declaration parameter names of redirect_free() and
redirect_realloc() to match the definitions.
Issue: #4087

i#4087 redirect alloc: Cleanup decl vs def param name mismatches

---

.travis.yml

Turns out the TRAVIS_EVENT_TYPE env var is not set during jobs matrix
creation.  Instead we have to use the "type = cron" condition.
Issue: #2861

i#2861 cronbuilds: Fix cron condition in jobs matrix

---

CMakeLists.txt
clients/CMakeLists.txt
clients/common/gendocs.cmake
clients/drcachesim/CMakeLists.txt
clients/drcov/CMakeLists.txt
clients/drcpusim/CMakeLists.txt

Enables BUILD_DOCS by default for all architectures.
For option list documentation generation (drcpusim, drcov, drcachesim), when
cross-compiling and we cannot executed the generator, instead we place this into
the documentation:
The parameters available are described below:
The options list is not currently able to be generated for cross-compiled
builds (https://github.com/DynamoRIO/dynamorio/issues/1730). Please see the
online documentation or run the tool with -help.
This is better than having no documentation at all in our non-x86 packages.
Issue: #1730

i#1730 xc docs: Enable all docs but op lists for cross-compiling

---

.travis.yml

We have to check both the Travis "type" and the env var to support
both manual and scheduled package builds.
Issue: #2861

i#2861 cronbuilds: Support both manual and scheduled builds

---

.travis.yml
make/package.cmake
suite/runsuite_wrapper.pl

Has package.cmake copy docs into a top-level html/ directory.
Sets up Travis to push the html/ directory to the dynamorio_docs repository.
The x86 build sets DEPLOY_DOCS which runsuite_wrapper turns into a
copy_docs parameter to package.cmake and which is used as a condition
for the Travis deployment.
Travis will not do deployments on pull requests so this can only be
tested once it is merged into master.
Fixes #3194

i#3194: Publish doxygen docs to Github Pages

---

api/docs/samples.dox

Changes the sample code links to be absolute, rather than trying to
point at the local copy in a locally installed binary package, to fix
broken links in the online docs.
Fixes #4113

i#4113: Make sample code links absolute

---

core/win32/os_private.h

Increase `MAX_CONTEXT_SIZE` to `0xd2f`
Issue: #2666

i2666: increase MAX_CONTEXT_SIZE

---

core/dynamo.c
suite/runsuite_wrapper.pl
suite/tests/api/dis-a64.c
suite/tests/api/ir_aarch64_negative.c

Fixes leaks in the api.dis-a64 and api.ir_negative AArch64 tests.
Adds extra printing to runsuite_wrapper to try and help with the
AArch64 Travis hang.
Issue: #4126
Fixes #4124

i#4124: Fix AArch64 leaks in tests

---

clients/drcachesim/tests/TLB-simple.templatex
clients/drcachesim/tests/TLB-threads.templatex
clients/drcachesim/tests/coherence.templatex
clients/drcachesim/tests/delay-simple.templatex
clients/drcachesim/tests/filter-no-d.templatex
clients/drcachesim/tests/filter-no-i.templatex
clients/drcachesim/tests/filter-simple.templatex
clients/drcachesim/tests/missfile-config-file.templatex
clients/drcachesim/tests/multiproc.templatex
clients/drcachesim/tests/offline-burst_client.templatex
clients/drcachesim/tests/offline-burst_maps.templatex
clients/drcachesim/tests/offline-burst_noreach.templatex
clients/drcachesim/tests/offline-burst_replace.templatex
clients/drcachesim/tests/offline-burst_replaceall.templatex
clients/drcachesim/tests/offline-burst_static.templatex
clients/drcachesim/tests/offline-burst_threads.templatex
clients/drcachesim/tests/offline-filter.templatex
clients/drcachesim/tests/offline-multiproc.templatex
clients/drcachesim/tests/offline-rseq.templatex
clients/drcachesim/tests/offline-simple.templatex
clients/drcachesim/tests/phys.templatex
clients/drcachesim/tests/simple-config-file.templatex
clients/drcachesim/tests/simple.templatex
clients/drcachesim/tests/threads-with-config-file.templatex
clients/drcachesim/tests/threads.templatex
clients/drcachesim/tests/warmup-valid.templatex
clients/drcachesim/tests/warmup-zeros.templatex
suite/runsuite.cmake
suite/tests/CMakeLists.txt

Removes the 32-bit release build from PR builds (the 64-bit should
catch nearly all warnings).
Further shrinks drcachesim tests using the Jacobi app by dropping to a
64 matrix size and 3 instead of 5 iterations.
Shrinks drcacheoff tests on Windows by capping the trace sizes at 1M,
except for basic_counts which needs the full run to see kernel events.
Relaxes all of the templates to allow for correspondingly varying
simulator statistics.
Issue: #4059

i#4059 faster Appveyor: No rel-32; shrink drcacheoff tests

---

ext/drsyms/drsyms_elf.c
ext/drsyms/drsyms_macho.c
ext/drsyms/drsyms_obj.h
ext/drsyms/drsyms_pecoff.c
ext/drsyms/drsyms_unix_common.c

Adds to drsyms reading of the build id and searching in
/usr/lib/debug/.build-id for a separate debuginfo file, which is the
modern scheme for installed libraries.
Tested on internal symbols like __GI___libc_malloc on a local machine.
It is not easy to make an automated test for this without setting up a
chroot or something which does not seem worth the effort.
Fixes #4123

i#4123: Look for symbols in special build-id subdir

---

core/win32/os_private.h

@derekbruening Sorry if I did not make it clear in #4122 that we only looked at the `MAX_CONTEXT_SIZE` for 64-bit, and for simplicity just set the same for 32-bit.
Was able to debug it again today for 32-bit, and the value is indeed lower than for 64-bit.
Issue: #2666

i#2666: decrease MAX_CONTEXT_SIZE for 32-bit to actual value

---

ext/drreg/drreg.c

Cleans up the param of drreg_restore_all().
Issue #4103

i#4103: Cleans up drreg_restore_all

---

core/lib/instrument.c
core/unix/loader.c
core/win32/loader.c

raw2trace uses dr_map_executable_file() which calls
privload_map_and_relocate() which uses the DR-memory-tracking
dr_map_file(), which can hit problems in standalone mode.  We change
it to always use os_map_file() for standalone_library=true.
Fixes #4144

i#4144: Fix assert in raw2trace on mapping files

---

core/unix/include/sigcontext.h
ext/drgui/drgui_main_window.h

Fixes a duplicate sigcontext define and adds a missing override in
drgui to address issues building with gcc 9.2.1
Fixes #3917

i#3917: Fix gcc 9.2.1 build errors

---

core/stats.h
suite/tests/CMakeLists.txt

Adds a check for the current dcontext being GLOBAL_DCONTEXT in the
kstats code to avoid a raw2trace crash.
Enables the func_view test on Windows.
Fixes #4155

i#4155: Fix raw2trace crash on Windows

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-test.dll.c

Arranges instrumentation call-back functions of drbbdup to accept the passing of tag values.
Issue: #4134

i4134: Pass fragment tag to drbbdup instrum routines

---

api/docs/samples.dox
api/samples/CMakeLists.txt
api/samples/hot_bbcount.c

Includes a sample to demonstrate how to use drbbdup.
The client sets up two instrumentation cases per basic block. One case tracks the hit count of  a basic block when _cold_ to determine whether it exceeds a threshold and should be considered _hot_. The second version simply counts the number of times a hot basic block is executed.
Issue: #4134

i#4134: Add sample to highlight drbbdup API usage

---

api/samples/bbcount.c
api/samples/countcalls.c
api/samples/div.c
api/samples/hot_bbcount.c
api/samples/inscount.cpp
api/samples/modxfer_app2lib.c
api/samples/opcodes.c
api/samples/wrap.c

Adds parentheses to the param of the NULL_TERMINATE macro found in many samples.
Fixes: #4160

i#4160: Adds parens to NULL_TERMINATE Macro

---

suite/runsuite_wrapper.pl

Adds drcachesim.invariants (i#2982) and tool.histogram.offline
(i#3980) to the tests whose failures are ignored, until we can
reproduce and fix them.
Issue: #2892, #3980

i#2892,i#3980: Ignore known-flaky tests on A64

---

core/arch/arm/encode.c

Works around a gcc9 memset warning by using offsetof instead of a
direct field reference.
Fixes #4170

i#4170: Fix ARM gcc9 build error

---

core/lib/instrument_api.h

Documents the behavior on forks and execs in more detail.
An attempt at resolving #4151.

i#4151: expand documentation of dr_register_thread_exit_event

---

clients/drcachesim/analysis_tool.h
clients/drcachesim/analyzer.cpp
clients/drcachesim/simulator/cache_miss_analyzer.cpp
clients/drcachesim/tools/func_view.cpp
clients/drcachesim/tools/histogram.cpp
clients/drcachesim/tools/reuse_distance.cpp

Documents and implements a convention of resetting stderr to decimal
format in all print_results() and handle_memref() functions that
change the output format to hex, to better support chaining multiple
tools.

Reset stderr to decimal in analysis tools

---

CMakeLists.txt
clients/drcachesim/common/options.cpp
clients/drcachesim/tests/heap_test.cpp
clients/drcachesim/tests/offline-burst_malloc.templatex
clients/drcachesim/tests/offline-func_view_heap.templatex
clients/drcachesim/tools/func_view.cpp
suite/tests/CMakeLists.txt

Adds all 24 global operator new and delete variants to the default
-record_heap_value, since in some implementations they do not simply
call malloc and free.  We include the Itanium ABI manglings only here.
MSVC and Windows heap interception is even more complex with more
layers and we leave that for future work.
Adds a new test which calls each one, though some are only compiled
and called if C++17 is available in the compiler.  It is not easy to
check the output so for now we do not have good automated validation
that all operators were caught, only manual checking.
Issue: #3048

i#3048 func-trace: Add new+delete to -record_heap

---

core/arch/disassemble_shared.c
core/arch/emit_utils_shared.c
core/arch/instr.h
core/arch/instr_shared.c
core/arch/interp.c
core/arch/x86/emit_utils.c
core/emit.c
core/fcache.c
core/fragment.c
core/globals.h
core/heap.c
core/link.h
core/options.c
core/optionsx.h
make/configure.cmake.h

Removes the no-longer-supported custom exit stub feature: all of the
code under the CUSTOM_EXIT_STUBS define and the INSTR_HAS_CUSTOM_STUB
flag.  Removing the flag frees it up for use in #4180.
Issue: #4045, #4180

i#4045: Remove custom exit stub support

---

core/optionsx.h

There was a double parenthesis causing clang-format to fail to format
core/optionsx.h.  We fix that here.
Issue: #2876

i#2876 clang-format: Fix format of optionsx.h

---

ext/drwrap/drwrap.c

When a direct call to a drwrap target is found, we now proactively add
the post-call point to the to-be-instrumented table, potentially
avoiding a flush if that PC were to be reached through some other
method before we find it in our callee control point.
This also enables finding post-call points even if we limited dynamic
return address investigation, which does add overhead.  A future
change will explore this further.
Issue: #4070

i#4070 drwrap-site: Add post-call sites proactively

---

clients/drcachesim/common/options.cpp

PR #4178 (96a23da0) placed the -record_heap_value separator on the
wrong side of the ifdef for UNIX.  Windows issues prevent additional
tests there to catch things like this at this time.
Issue: #3048

i#3048 func-trace: Move separator on wrong side of ifdef

---

api/docs/release.dox
ext/drwrap/drwrap.c
ext/drwrap/drwrap.dox
ext/drwrap/drwrap.h
suite/tests/client-interface/drwrap-test.dll.c

Adds a new interface drwrap_get_stats() which returns the count of
flushes triggered by drwrap, for use when evaluating performance
overhead.  Adds documentation and a test.
Issue: #4070

i#4070 drwrap-site: Add drwrap_get_stats() with flush count

---

api/samples/hot_bbcount.c
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-test.dll.c

An incremental step to adding support for dynamic case handling. Essentially, when a new case encoding, which has not been registered upon the creation of a basic block, is frequently encountered at runtime, drbbdup aims to dynamically generate a basic block copy to handle the case.
Since #3773 is not yet closed, the functionality is not yet supported. However, with this PR, a lot of drbbdup's interface will be set.
Issue: #4134

i#4134: Add major functionality for dynamic case handling

---

api/docs/release.dox
ext/drwrap/drwrap.c
ext/drwrap/drwrap.h
suite/tests/client-interface/drwrap-test.appdll.c
suite/tests/client-interface/drwrap-test.dll.c
suite/tests/client-interface/drwrap-test.template

Adds DRWRAP_NO_DYNAMIC_RETADDRS which instructs drwrap to not look for
post-call points by examining the return address and comparing to
known sites while in the callee.  This incurs overhead, mostly due to
the locks and shared data structures, in large many-threaded
applications.  The downside is that the only post-call points in place
are those for direct calls, which drwrap always looks for with the
recent PR #4186.  Future work could add identification of
PLT-or-IAT-style indirect calls, or explore more scalable data
structures.
Adds testing to drwrap-test.
Issue: #4070

i#4070 drwrap-site: Add flag to skip retaddr examination

---

api/docs/release.dox
clients/drcachesim/tracer/func_trace.cpp
ext/drcontainers/hashtable.c
ext/drcontainers/hashtable.h
ext/drsyms/drsyms_unix_common.c

Instead of a linear search through the symbol table on every lookup,
on the first lookup drsyms now builds a hashtable of all symbol
variants and uses it on subsequent lookups.
Adds a new option to the drcontainers hashtable to supply a key
freeing callback, needed here because we are duplicating most strings
ourselves before adding and do not want to have drcontainers
re-duplicate.
Adds a -verbose 1 notification for libraries taking long amounts of
time to be processed, for easier diagnostics in the future.
Performance-tested on large applications where it reduces drcachesim
-record_heap query times by 5x for less-optimized code and 2x for
highly-optimized code.
Fixes #4187

i#4187: Build a hashtable for faster ELF symbol lookups

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/tracer/func_trace.cpp

Adds a new option -record_dynsym_only to drcachesim which causes
-record_function and -record_heap to only look in .dynsym, avoiding
drsyms and the main symbol table entirely.  This is to avoid overhead
issues with two scenarios: very large applications with millions of
symbol table entries, and applications with thousands of libraries
where setting up and tearing down drsyms and DWARF information adds up
across all of those libraries.  Quite often the target functions to
trace are in .dynsym, making this a reasonable solution.
Tested manually on both scenarios.
Issue: #4187

i#4187 sym perf: Add -record_dynsym_only to drcachesim

---

ext/drgui/drgui_main_window.cpp
ext/drgui/drgui_main_window.h

Switches from the deprecated QSignalMapper to a lambda.  There are no
tests of this code so while I did run drgui I am not 100% sure that I
have maintained the same functionality.
Fixes #4203

i#4203: Fix drgui build error

---

api/docs/release.dox

Makes the source compatibility change of adding the field to
hashtable_configure_t more explicit in the changelist, in light of
DynamoRIO/drmemory#2285.
Issue: #4187

i#4187 drsyms hash: Clarify the drcontainers source compat change

---

core/lib/globals_shared.h

Commit 4b8275b04b029079cb0cbe5760ee53d5b974fb08 for PR #4183 split two
strings due to clang-format shifts.  This ends up breaking the
Dr. Memory VS2013 build.  Here we restore the originals.

Fix string wrap which breaks VS2013

---

clients/drcachesim/drcachesim.dox.in
clients/drcachesim/simulator/cache.cpp
clients/drcachesim/simulator/cache_line.h

Removes stale comments about needing to implement coherence in
drcachesim.
Removes an input config file from the list of limitations in the docs,
since we do have that support now.
Issue: #1726

i#1726 coherence: Remove stale comments

---

suite/runsuite_common_pre.cmake

Tightens the regex for versioned SDK directories to look for a slash
followed by a "v" to avoid matching the WiX path, which we do not want
to mangle.
Also fixes a CMake warning about mismatched conditional end labels in
the same code.
Fixes #4108

i#4108: Avoid replacing WiX paths

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h

App2app changes should be done prior to drbbdup's basic block duplication. Therefore, this PR updates the drbbdup's app2app event priority to low.
Issue: #4134

i#4134: Update drbbdup's priority.

---

api/samples/hot_bbcount.c
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-test.dll.c

Adds statistics gathering to drbbdup. In particular, the PR includes drbbdup_get_stats(), which populates a passed struct with current stat values.
Issue: #4134

i#4134: Add statistics gathering to drbbdup

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.dox
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-test.dll.c

Includes drbbdup_is_first_nonlabel_instr() to determine whether or not the instruction considered during insertion is the first non label instruction of the basic block copy. 
Issue: #4134

i#4134: Add drbbdup_is_first_nonlabel_instr()

---

api/docs/release.dox
core/annotations.c
core/annotations.h
core/arch/x86/mangle.c
suite/tests/client-interface/annotation-concurrency.c
suite/tests/client-interface/annotation-concurrency.dll.c
suite/tests/client-interface/annotation/test_mode_annotations.c
suite/tests/client-interface/annotation/test_mode_annotations.h

Adds dr_annotation_pass_pc() which puts the interrutped app PC into
one of DR's scratch TLS slots (since it is difficult to pass it in an
argument, due to clobbering application tate).
Adds a test.
Fixes #4146

i#4146: Add option to get interrupted PC in an annotation

---

api/docs/release.dox
core/arch/arch_exports.h
core/lib/instrument.c
core/lib/instrument_api.h
ext/drwrap/drwrap.c
suite/tests/client-interface/thread.dll.c
suite/tests/client-interface/tls.dll.cpp

Adds 32-bit and 64-bit load and store atomics to core DR and exports
them to the client API.
Adds missing barriers to the existing store atomic macros on both ARM
and AArch64.
Adds a sanity test that at least exercises the functions.  Adds the
test sequence to client.thread and client.tls (only client.tls is
currently enabled on AArchXX).
Uses dr_atomic_load* in drwrap in place of a previously overkill
dr_atomic_add*.
These will also help with #2502.
The next step is to add gencode versions of these, either to the core
or drx.
Issue: #4215, #2502

i#4215 atomics: Add load and store atomics

---

core/unix/signal.c
core/win32/events.mc

Adds the signal number and thread id to this fatal message for better diagnostics:
<Cannot correctly handle received signal 11 in thread 204511.>
Tested in the #4219 failures.

Add signal and thread numbers to fatal signal message

---

clients/drcachesim/tests/burst_malloc.cpp
clients/drcachesim/tracer/func_trace.cpp

Clears the list of traced functions on exit to avoid accumulation on re-attach.
Sets the handoff separately for each attach in the burst_malloc test.
There are still problems with re-setting options: droption #4139 and
core #2661 (with the '#' prefix workaround).  Those are left to their
respective issues.
Issue: #3048, #2661, #4139

i#3048 func-trace: Improve function tracing re-attach

---

api/docs/release.dox
core/synch.c
core/translate.c
ext/drwrap/drwrap.c
ext/drwrap/drwrap.h
ext/drwrap/drwrap_asm_aarch64.asm
ext/drwrap/drwrap_asm_arm.asm
ext/drwrap/drwrap_asm_x86.asm
suite/tests/CMakeLists.txt
suite/tests/client-interface/drwrap-test-detach.cpp
suite/tests/client-interface/drwrap-test-detach.expect
suite/tests/client-interface/drwrap-test.appdll.c
suite/tests/client-interface/drwrap-test.dll.c
suite/tests/client-interface/drwrap-test.template
suite/tests/thread.h

Adds an alternative scheme for achieving a post-call control point
that does not require flushing or shared data structure examination
per-call: replacing the return address with a sentinel.
When the new flag DRWRAP_REPLACE_RETADDR is set, the return address is
replaced with the address of a single return instruction in the client
library, with the real address saved.  When a block is seen consisting
of that sentinel instruction, post-call callbacks are called, and then
control is sent to the saved real address using
dr_redirect_native_target().
Adds wrapping tests to drwrap-test.
This new scheme requires restoring return addresses on the stack on
detach or other state translation.  Adds functionality to do so, along
with a new test client.drwrap-test-detach.
This requires the client's …

i#4197: Add new drwrap post-call scheme: replace retaddr

---

suite/tests/CMakeLists.txt
suite/tests/client-interface/drwrap-test.appdll.c

PR #4221 broke the Mac build, but Travis failed to show the failure in
the logs in the PR builds (some buffering issue filed as #4223).  We
fix the Mac build here.
Issue: #4197, #4223

i#4197 replace RA: Fix Mac build

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/tests/burst_malloc.cpp
clients/drcachesim/tracer/func_trace.cpp

Adds a new option -record_replace_retaddr to drcachesim to allow
choosing the drwrap option DRWRAP_REPLACE_RETADDR, which has lower
overheads for post-call interception, at the risk of breaking some
applications.
Adds the option to the burst_malloc test.
Issue: #4197

i#4197 replace RA: Add -record_replace_retaddr to drcachesim

---

ext/drwrap/drwrap.c

Removes the drwrap fragment delete event, which is currently empty
since drwrap switched to checking consistency at lookup time a while
back as part of DynamoRIO/drmemory#673.
This speeds up detach and process cleanup in general, since the mere
presence of a fragment delete event can cause delays of a full second
or more when detaching from a large application.
Issue: #4226

i#4226 delete perf: Remove unused drwrap fragment delete event

---

clients/drcachesim/tests/burst_threadfilter.cpp
clients/drcachesim/tracer/tracer.cpp

Fixes an incorrect test in the combination of thread filtering and
function tracing in drcachesim.
Adds -record_heap to the threadfilter test, though I had trouble
reproducing the crash there.  I tested the fix on a third_party app
where it was hit but is unfortunately difficult to add as a regression
test here.
Issue: #3048

i#3048 func-trace: Fix thread filter + func trace crash

---

api/docs/release.dox
core/lib/instrument.c
core/lib/instrument.h
core/lib/instrument_api.h
core/synch.c
core/translate.c
suite/tests/client-interface/drwrap-test-detach.cpp

Adds invocation of the client restore state event for all cases, even
when the register state is known to already contain application
values, since the client may need to restore memory.
Adds a test to drwrap-test-detach by adding a system call.
Issue: #4197

i#4197 replace RA: Call client restore event for all cases

---

core/fragment.c
ext/drwrap/drwrap.c

i#4226: Faster fragment deletion event
Adds a dedicated loop to call the fragment deletion event without
calling all the other fragment freeing code.  This speeds up detach
and process exit in general by 2x.
Tested performance and correctness on a third-party app; also tested
correctness on a hacked drwrap-detach-test to ensure the same number
of deletion event calls were made.  I don't think it's easy to make a
performance regression test unfortunately.
Fixes #4226

i#4226: Faster fragment deletion event

---

api/docs/release.dox
core/lib/instrument.c
core/lib/instrument_api.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/process-id.c
suite/tests/client-interface/process-id.dll.c
suite/tests/client-interface/process-id.expect

i#4137: add API for getting a process id associated with a drcontext

---

clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/tracer.cpp

For drcachesim post-processing of explicit instr entries such as for
filtered traces, do not output non-xfer markers post-instr and just exit
back to the main loop instead, to avoid overflowing the buffer with
potentially unimited strings of markers before the next filtered
instr or memref entry.
For marker output during tracing, add an explicit check and buffer
dump when the redzone is hit, as a safety step, even though today's
code should not reach it.
Add a release-build check for hitting the buffer size so we can detect
pathological missing-post-call stacked function markers.  Fully
handling that is left for future work.
Issue: #4159

i#4159 marker overflow: Handle expected drcachesim marker overflows

---

clients/drcachesim/reader/file_reader.h

Updates a for loop in drcachesim's file reader to use a const
reference.

Cleanup: Change a for loop var to const ref

---

suite/runsuite_wrapper.pl

The 32-bit client.drwrap-test-detach test has been failing on Appveyor
but not our local machines.  Marking it flaky to keep the CI green.
Issue: #4058

i#4058 Appveyor: Mark 32-bit client.drwrap-test-detach flaky

---

core/win32/loader.c

Marks tls_next_idx and tls_array_count as volatile to prevent VS from
optimizing a conditional store into an unconditional store (to avoid a
branch) which causes crashes in release build with clients whose
imports use static TLS on multi-threaded applications.
Tested on drcachesim -offline on Win10 1909 with a dbghelp where the
filed crash reproduces.
Ensuring we have a regression test in the CI is trickier and out of
scope for this initial fix.
Fixes #4130

i#4130: Fix .data write crash from VS optimization

---

core/win32/loader.c

Fixes a bug in the check for a late-loaded library with static TLS,
which we do not currently support.
Tested by temporarily adding LoadLibrary("dbghelp.dll") to the
client.tls test client.
Issue: #4130

i#4130 static TLS: Enable fatal message on late static TLS

---

core/arch/instr_shared.c
suite/tests/api/drdecode_x86.c
suite/tests/api/ir_x86.c

The noalloc flag was stripped out by instr_reset, and the
heap-leak-based test was in api.drdecode, which doesn't actually check
for leaks and so did not catch the bug.  Here we fix the bug to
preserve the flag, and place a test in api.ir which does do the leak
check.  Confirmed that the test fails without the fix.
Issue: #4180

i#4180 noalloc IR: Fix instr_reset to preserve noalloc status

---

api/docs/release.dox
core/lib/instrument_api.h
core/loader_shared.c
core/module_shared.h
core/unix/loader.c
core/win32/drwinapi/ntdll_redir.c
suite/tests/client-interface/alloc.dll.c
suite/tests/client-interface/alloc.template
suite/tests/client_tools.h

Provides a guaranteed double-pointer-sized alignment for redirected
malloc, to match system allocators and avoid breaking private library
assumptions.
Adds a test to client.alloc.
Fixes #4237

i#4237: Align redirected malloc to double-ptr-sized

---

ext/drbbdup/drbbdup.c

Adds a check after the setting up of a basic block for duplication in order to ensure that the default case encoding is not erroneously registered already.
Issue: #4134

i#4134: Add check to ensure default case encoding is not already registered.

---

core/loader_shared.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/alloc.dll.c

Fixes a bug from 228933d #4237 where redirect_realloc() was not
updated to read the new malloc header, resulting in a memcpy that
reads beyond the end of the original allocation, which can crash if
it's at the end of a heap block with a subsequent guard page.
Adds at least some sanity checks of realloc to the alignment test.  I
tried to construct a regression test to reproduce the crash in the
bug, but it is not possible in a straightforward way just using the
public interface as it requires knowing what is beyond an allocation
or how two allocations are arranged and what headers or other bytes
are in between.
Fixes #4237

i#4237: Fix realloc over-read

---

core/arch/instrlist.c
core/arch/instrlist.h
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/drbbdup-analysis-test.dll.c
suite/tests/client-interface/drbbdup-analysis-test.expect

Enhances the case analysis call-back interface of drbbdup to enable the user to insert analysis labels.
The extension extracts the case instruction list from the main basic block and passes it to the user during analysis. After, drbbdup stitches the instruction list back to the main basic block.
A test is also included.
Issue: #4134

i#4134: Support analysis labels in drbbdup

---

ext/drbbdup/drbbdup.c

Replaces many creation of instructions with XINST_CREATE to improve the platform independence of drbbdup.
Issue: #4134

i#4134: Add some platform independent instructions to drbbdup

---

core/arch/arch_exports.h

Replaces ldxr..stxr with ldaxr..stlxr in the atomic sequences used to
implement DR's mutexes.  DR's mutexes, and its other atomic
operations, assume release-acquire memory ordering.
Issue: #3956

i#3956 arm locks: Use release-acquire atomics

---

core/vmareas.c

Raises the consistency check at the end of check_thread_vm_area to
default to checklevel 3 on AArch64, matching Mac64 where it is also
observed to be quite slow.
Issue: #4257

i#4257 slow memquery: Avoid slow vmarea check on AArch64

---

core/arch/arch_exports.h

Adds a "dmb ish" barrier prior to the "ldrex..strex" loops in the
atomics used to implement mutexes and other operations on 32-bit ARM
where we need release-acquire semantics.
Issue: #3956

i#3956 arm locks: Use release-acquire atomics for ARM

---

.travis.yml
CMakeLists.txt
api/docs/intro.dox
api/docs/release.dox
core/arch/arch.h
core/arch/asm_defines.asm
core/arch/mangle_shared.c
core/arch/x86/mangle.c
core/arch/x86/x86.asm
core/drlibc/drlibc_x86.asm
core/lib/instrument.c
core/unix/loader.c
ext/drgui/CMakeLists.txt
ext/drwrap/drwrap_asm_x86.asm
make/DynamoRIOConfig.cmake.in
suite/tests/client-interface/cleancall.dll.c
suite/tests/client-interface/cleancallparams.dll.c
suite/tests/client-interface/cleancallsig.dll.c
suite/tests/client-interface/drwrap-test.appdll.c
suite/tests/client_tools.h
suite/tests/common/nativeexec.c

Abandons the 4-byte stack alignment DR was using for 32-bit x86 Linux
(for compatibility with legacy code).  The SysV ABI breakage by gcc
4.5 was 10 years ago and in that time other compilers have followed
suit, making 16-byte the de facto standard.  Clang doesn't even
support requesting 4-byte stack alignment.  DR is now switching to the
modern ABI of 16-byte stack alignment.
Bumps the version to 7.92 and marks OLDEST_COMPATIBLE_VERSION as 791
to indicate the binary compatbility break for 32-bit x86 DR.
Leaves Windows as 4-byte-aligned, since changing the injection
assembly code and other pieces would be a bunch of extra work for
little benefit: Windows 32-bit only requires 4-byte alignment, and the
code is not that much more complex with a split alignment.
Aligns the stack after clean …

i#3966: Switch 32-bit x86 Linux to 16-byte stack alignment

---

api/docs/release.dox
api/samples/hot_bbcount.c
core/arch/arch_exports.h
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.dox
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-analysis-test.dll.c
suite/tests/client-interface/drbbdup-no-encode-test.dll.c
suite/tests/client-interface/drbbdup-test.dll.c

Makes minor changes to docs to better clarify some assumptions made by drbbdup.
Also adds a check to ensure that the runtime case operand provided by the user is of pointer-size.
Issue: #4134

i#4134: Add opnd check 

---

core/arch/aarch64/emit_utils.c
core/arch/arch_exports.h
core/arch/arm/emit_utils.c
core/arch/arm/instr_create.h
core/fragment.c

For update_lookuptable_tls: Adds a store-release to the lookuptable
store and a load-acquire to the IBL generated code for both ARM and
AArch64, as there is no lighter-weight way to ensure the mask and
table stores are seen in the proper order.
For flushtime_global: made all readers and the increment use
store-release semantics.
For safely_nullify_tables: leaving as weak stores since timing and
ordering does not matter there.
Issue: #2502

i#2502 lockless ARM: Fix missing AArch synchronization

---

ext/drbbdup/drbbdup.h

Add docs to clarify that users should not use drmgr variants to check for first, first_nonlabel and last instructions.
Issue: #4134

i#4313: Clarify docs regarding first, first_nonlabel, and last instr functions

---

api/docs/release.dox
ext/drmgr/CMakeLists.txt
ext/drmgr/drmgr.c
ext/drmgr/drmgr.h
suite/tests/client-interface/drmgr-test.dll.c
suite/tests/client-interface/drmgr-test.templatex

Adds the support of instrumentation events specific to opcode instructions to drmgr. In particular, two new API functions are introduced: drmgr_register_opcode_instrumentation_event() and drmgr_unregister_opcode_instrumentation_event().
drmgr_register_opcode_instrumentation_event() takes a call-back function and an opcode as input. The call-back is triggered during the insert per instruction stage (i.e., stage 3) only for those instructions that have the specified opcode.
Call-backs pertaining to an opcode are maintained via a hashtable. 
Some care is taken to avoid any performance hits if opcode events are not registered. For instance, with the use of flags, the code avoids locking or hash-lookups if opcode events are never registered by the user.
In order to ensure call-backs pertaining …

i#4280: Add support for opcode insert instrumentation to drmgr

---

api/docs/samples.dox
api/samples/CMakeLists.txt
api/samples/opcode_count.cpp
ext/drmgr/drmgr.c
suite/tests/CMakeLists.txt

Adds a new sample client to show how drmgr's opcode instrumentation can be used to count the number of executions of an instruction (with a specific opcode). The opcode number is given by the user as a parameter (the client uses droptions for parsing).
In addition, the PR also includes a bug fix in drmgr. In particular, drmgr was confusing the default priority as a different priority when used again for another event registration. The bug was only triggered if cblist_insert_other() is used - this function is only called for opcode registration at the moment so the bug's severity is low.

i#4280: Adds a sample highlighting opcode instrumentation.

---

suite/tests/client-interface/drx-scattergather.dll.c

Initialises the size of an emulated instruction's data to fix a bug in drx-scathergather.dll.c that was failing travis.
Fixes: #4287

i#4287: Initialize size of emu instr

---

ext/drmgr/drmgr.c

Fixes a potential race in drmgr's handling of a bb event. Prior, drmgr was accessing count information,  used for managing user data of instrumentation callbacks, without a lock.
Issue: #1356

i#1356: Fix potential race in drmgr's bb event

---

ext/drmgr/drmgr.c

Breaks down the code intended for copying cb information to local temporary storage into smaller helper functions. The main instrumentation pass of a basic block is also moved to a separate helper function.
This is a preliminary PR to help with the integration of drbbdup and drmgr.
Issue: #1356

i#1356: Break down instrumentation pass

---

ext/drmgr/drmgr.c
ext/drmgr/drmgr_priv.h

Introduces an internal interface for drmgr to enhance drbbdup's instrumentation callbacks. 
The interface enables drbbdup to register low level call-backs which drmgr can use to manage bb copies.
Issue: #4134

i#4134: Adds an internal interface to drmgr

---

core/unix/injector.c

When using -late, append to LD_PRELOAD rather than overwrite it.
Fixes #4291

i#4291: append to LD_PRELOAD when using -late

---

core/CMakeLists.txt

Bits from libgcc are not used on AArch64 and x86_64 but are still included in the build and may be linked statically into resulting binary. To avoid any licencing questions on these targets it's easier to just remove this part from the build where it is not used anyway.

Remove redundant libgcc dependency on 64 bit targets

---

core/arch/aarch64/aarch64.asm
core/drlibc/drlibc_xarch.asm

Moves unexpected_return() from drlibc to the core's asm file for
AArch64, to avoid a branch reachability link error when linking DR
statically into large apps.  unexpected_return() is not used in drlibc
for AArch64.
Fixes #4304

i#4304: Fix AArch64 asm reachability

---

core/lib/instrument.c

This check is helpful for AArch64 target which does not support loading into and storing from XSP.
This change allows to fail early with a meaningful error message: for a debug build it will look like this:
```
<Application /usr/bin/ls (68183) DynamoRIO usage error : dr_save_reg: store from XSP is not supported>
<Usage error: dr_save_reg: store from XSP is not supported (...dynamorio/core/lib/instrument.c, line 5807)
```

Add check for XSP in dr_restore_reg and dr_save_reg on AArch64

---

core/CMakeLists.txt
core/CMake_symbol_check.cmake
core/arch/aarch64/aarch64.asm
core/arch/aarch64/memfuncs.asm
core/arch/arm/arm.asm
core/arch/arm/memfuncs.asm
libutil/CMakeLists.txt

Provides isolation of mem{cpy,set,move} in the DR static library on
AArchXX.  Moves the assembly mem{cpy,set} into a separate memfuncs.asm
for arm and aarch64, and links in memmove.c.  Marks the
__mem{cpy,set}_chk aliases as weak.  This brings AArchXX into parity
with x86 on library symbol isolation.
Removes the exceptions for AArchXX in the CMake_symbol_check test.
Confirms the build-time test fails without the code changes here:
CMake Error at xxx/core/CMake_symbol_check.cmake:98 (message):
*** Error:
xxx/build_a64_dbg_tests/lib64/debug/libdynamorio_static_nohide.a
contains a likely-to-conflict symbol: 4279: 00000000002cea3c 0 FUNC GLOBAL
HIDDEN 248 memcpy
Issue: #3315, #3348

i#3315,i#3348: Move mem{cpy,set,move} into memfuncs on AArchXX

---

suite/runsuite_wrapper.pl

The 64-bit client.drwrap-test-detach test has been failing on Appveyor
but not our local machines.  Marking it flaky to keep the CI green.
Issue: #4058

i#4058 Appveyor: Mark 64-bit client.drwrap-test-detach flaky

---

core/heap.c

Adds the distinct name "vmcode" or "vmheap" so that our debug-build
OOM message diagnostic is more helpful.

Add vmcode/vmheap distinction in OOM message

---

clients/drcachesim/tests/offline-filter-no-i.templatex
suite/tests/CMakeLists.txt

Offline traces generated using '-L0_filter -L0I_size 0' have no instruction entries. Add a test to verify this.

Add test for offline traces with no instructions.

---

core/CMakeLists.txt
core/arch/aarchxx/mangle.c
core/arch/arch.h
core/arch/x86/mangle.c
core/ir/aarchxx/ir_utils.c
core/ir/ir_utils.h
core/ir/ir_utils_shared.c
core/ir/x86/ir_utils.c
core/lib/instrument.c

Moves the handful of functions from mangle.c used by drdecode (things
that are difficult to untangle from the IR functions) into ir_utils.c
Renames the top-level ir_utils.c to ir_utils_shared.c.  Adds
ir_utils.h.
Issue: #1684

i#1684 xarch-IR: Remove mangle.c from drdecode

---

core/drlibc/drlibc_module_elf.c
core/drlibc/drlibc_unix.c
core/drlibc/drlibc_unix.h
core/unix/os_private.h

Adds drlibc_unix.h to better separate drlibc and prevent it including
os_private.h and thus pulling in tls.h and other headers related to DR
execution, which incorrectly mixes target and host architectures for
drdecode and drdisas.
Issue: #1684

i#1684 xarch-IR: Remove tls.h from drlibc

---

api/samples/opcode_count.cpp
ext/drx/drx.h

DRX_COUNTER_LOCK is not currently supported on ARM. The opcode_count sample did not have a check and therefore failed to count instructions properly. This check is added now.
Fixes: #4326

i#4326: Fix opcode_count sample to check for DRX_COUNTER_LOCK support on ARM

---

core/link.c

Although this is a "benign" dereference (it is only used to compute the address of a member of a struct and no actual memory access is attempted), this is still undefined behavior and it causes problems when using tools like UndefinedBehaviorSanitizer.

Fix NULL pointer dereference.

---

.travis.yml
clients/drcachesim/common/trace_entry.h
clients/drcachesim/reader/file_reader.h

PR #4331 commit 5d49675c added a new marker with the architecture
early in a trace, enough to break the file_reader_t assumptions.  The
file reader was updated, but it's best to also bump the version for
old binary code.  Additionally, we provide a separate distinct message
about a version mismatch (otherwise the error message from the old
reader is the same as without the version bump).
Issue: #4318

i#4318 xarch memtrace: Bump version and add message for arch tags

---

.travis.yml

Sleep for 10 seconds after script run/failure to allow some time for Travis to capture the complete log.  It was used as a workaround also at travis-ci/travis-ci#6018.
Also attempted another workaround (using fcntl) from travis-ci/travis-ci#8973 but it didn't work as expected.
Fixes: #4223

i#4223: Fix truncated log issue for macOS on Travis

---

core/dispatch.c
core/dynamo.c
core/fragment.c
core/globals.h
core/heap.c
core/lib/instrument.c
core/optionsx.h
core/stats.c
core/unix/os.c
core/unix/signal.c
core/utils.c
suite/tests/CMakeLists.txt
suite/tests/api/thread_churn.c
suite/tests/api/thread_churn.expect

These leaks are all cleaned up at process exit, which is why the
existing exit-time leak checks don't notice anything.  The global
block list lets us clean them up later, and hence a classic
reachability-based leak detector would not catch them either: so
perhaps they should be called "reachable accumulations" instead of
"leaks".
Fixes a memory leak on thread exit in all builds:
+ The private reachable_heap units were not being freed
Fixes a number of memory leaks on thread exit in release build:
+ Adds individual private fragment deletion on thread exit, to free
stubs if -separate_private_stubs is on.
Turns off -separate_private_stubs by default, to avoid this for
shared caches where there are few benefits to separating private stubs.
-thread_private turns it back on where the benefits …

i#4334: Fix leaks on thread exit

---

core/ir/aarch64/codec.c
core/ir/opnd.h

#1569 Add decoding and encoding for system registers TPIDRRO_EL0 and CNTVCT_EL0.

Add missing system registers for AArch64

---

.travis.yml

Currently the default xcode9.4 is being used for macOS builds because osx_image setting is not present in jobs section. This somehow wasn't an issue when it was initially added in #4096.

Update xcode version from the default 9.4 to 11.3

---

ext/drwrap/drwrap.c

Fixes an undefined symbol in drwrap when host!=target.
Only some compilers complain about it.
Issue: #1684

i#1684 xarch-IR: Fix drwrap host!=target undef sym

---

clients/drcachesim/simulator/cache_simulator.cpp

This change updates the error_message_ member with a descriptive message based on the initialization failure.

Add descriptive error messages for cache initialization failures.

---

clients/drcachesim/common/options.cpp
clients/drcachesim/tools/opcode_mix_launcher.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace_launcher.cpp

Moves the -alt_module_dir for finding binaries during trace
post-processing to take precedence over the recorded path, to allow
avoiding problems when an identical-seeming path exists on the
processing machine (e.g., system libraries) on UNIX where we have no
checksum or other library distinguisher.
Tested manually on a case where a system library in the same path as
on the recorded machine caused failure.
Issue: #4318

i#4318 xarch memtrace: Make alt lib dir take precedence

---

core/win32/syscall.c

Fixes the thread handle leak when thread_handle_to_pid() in win32/syscall.c is called.
Fixes: #4352

i#4352: Thread handle Leak

---

clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/raw2trace_directory.cpp

When raw files are gzipped and named xxx.raw.gz, the corresponding
final trace files end up named xxx.raw.trace.gz, i.e., with an extra
"raw." in there.  We fix that here.
Issue: #4318

i#4318 xarch memtrace: Remove raw from final name

---

clients/drcachesim/tools/view.cpp

For the view tool, the original wrong-arch check was placed *after*
the entry skipping for -skip_refs, which can result in never checking
the architecture.  We fix that here by moving the check up front.
Issue: #4318

i#4318 xarch memtrace: Detect view arch mismatch earlier

---

CMakeLists.txt

Removes the stale workaround put in place that disabled zlib
altogether for cross-compiling before we had CMAKE_FIND_ROOT_PATH set
properly in all of our toolchain files.  Now that we're seeing the
find-root properly we need to remove the workaround to allow finding a
target zlib when cross-compiling.
Tested manually on an aarch64 cross-compilation.
The core of i#2285 was fixed earlier by PR #2551; this finishes off
the issue.
Fixes #2285

i#2285: Support cross-compile target-arch zlib

---

core/unix/module_elf.h

Hi!
I tried to build DynamoRIO on CentOS 6.9. I failed because old Linux distribution does not have EM_AARCH64 symbol which leads to compilation errrors. This merge request fixes compilation on CentOS 6.9 and maybe other old distros.

Fix compilation on old Linux which does not have EM_ARM/EM_AARCH64 symbols

---

clients/drcachesim/tracer/instru.cpp

Fixes a gcc 9.3 build warning introduced by cdc24cb PR #4341.
Issue: #4328

i#4328 AArch64 prefetch and flush instrs: Fix build warning

---

clients/drcachesim/common/options.cpp
clients/drcachesim/tools/view.cpp
core/ir/disassemble.h
core/ir/disassemble_shared.c
core/optionsx.h

Updates the default disassembly style for the drmemtrace view tool to
proper values for ARM and AArch64.
Adds "TODO i#4382" comments for adding DR_DISASM_AARCH64 and its
associated options.
Issue: #4381, #4382
Fixes: #4381

i#4381: Fix drmemtrace view disasm non-x86 default style

---

core/heap.c

Resets a flag used to auto-initialize when heap routines are called
without an explicit dr_standalone_init(), enable drdecode and other
use cases.  Without this reset, a prior dr_standalone_exit() can cause
a subsequent crash when using implicit-initialization interfaces.
Issue: #975

i#975 static DR: Reset flag used for auto-standalone-init

---

core/ir/aarch64/codec.txt
core/ir/aarch64/instr_create.h
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This fixes bugs in the 128-bit SIMD variant of STUR/LDUR instructions (#4337) and adds extra IR and disassembly tests.

i#4337: Fix STUR/LDUR bugs

---

.appveyor.yml

The Doxygen 1.8.17 download path we use on Appveyor is now stale.  We
replace it with 1.8.19.

Update Doxygen download path on Appveyor

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/burst_traceopts.cpp
clients/drcachesim/tests/reg_id_set_unit_tests.cpp
clients/drcachesim/tracer/instru.h

A std::unordered_set, even using dr_allocator_t, raises transparency
risks when statically linked on Windows (from lock functions and other
non-allocator resources).  We thus create our own resource-isolated
class to track GPR register inclusion for drmemtrace elision
optimizations.
Adds unit tests of the set class to burst_traceopts.
Further tested manually by ensuring the same number of elided
addresses is seen as with std::unordered_set in the burst_traceopts
test:
[drmemtrace]: Reconstructed 622 elided addresses.
Even further tested by ensuring that raw2trace using the new set
correctly operates on a raw file that was created using
std::unordered_set.
Issue: #975, #4403

i#975 static DR: Add isolated GPR set class

---

core/unix/os.c
core/unix/os_private.h
core/unix/signal.c

Fixes a crash on detach on aarchxx by setting xsp to the proper value
for SYS_rt_sigreturn to find the signal frame for resuming app state.
Tested manually on aarch64 the api.detach test in gdb.  Unfortunately
there are further bugs, so the test cannot be enabled yet.
Issue: #1578

i#1578 arm detach: Fix sigreturn crash by setting xsp

---

api/docs/release.dox

Commit 5ed1a118 (PR #4084) renamed fields in drcachesim classes to
adopt a consistent naming style.  This is a source compatibility break
for users who have created derived classes with references to those
fields.  Here we add a release note about this.
Issue: #4049

i#4049 style: Add source compatibility break release note

---

core/heap.c
suite/tests/CMakeLists.txt

Fixes a bug where beyond-vmm memory was subject to reachability
constraints even when it did not have VMM_REACHABLE set.
Adds a test by running client.alloc's current OOM test with
-no_enable_reset, which hits OOM and so fails without this fix.
Fixes #4335

i#4335 OOM: Fix beyond-vmm reachability constraints bug

---

core/heap.c
core/win32/events.mc

Improves the OOM message by printing the source, type, and OS code.
The source and code was printed in debug build previously but was not
available in release.
Tested on the new i#4335 test as well as on a custom app for which
i#4415 was opened.
Issue: #4335, #4415

i#4415 vmm sub-page: Improve OOM message

---

core/fcache.c
core/heap.c
core/module_list.c
core/module_shared.h
core/options.c
core/options.h
core/utils.h

Changes the "uint_size" option type to be pointer-sized, to better
handle larger values we are now wanting for things like -vmheap_size,
especially on ARM machines with larger page sizes.
Adds some sanity tests to ensure all the parsing and printing code was
updated.
Issue: #4418

i#4418 vmheap: Change sized options to use pointer-sized types

---

core/win32/os_private.h

32-bit Windows 10 1909+ was overflowing the interception buffer,
causing crashes.  We increase the size here.
Tested on Win10 2004.
Fixes #4426

i#4426: Fix interception buffer overflow

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/allasm-aarch64-flush-basic-counts.templatex
clients/drcachesim/tests/allasm-aarch64-prefetch-basic-counts.templatex
clients/drcachesim/tests/allasm_aarch64_flush.asm
clients/drcachesim/tests/basic_counts.templatex
clients/drcachesim/tests/builtin-prefetch-basic-counts.templatex
clients/drcachesim/tests/burst_flush_aarch64.cpp
clients/drcachesim/tests/offline-allasm-aarch64-flush-basic-counts.templatex
clients/drcachesim/tests/offline-allasm-aarch64-prefetch-counts.templatex
clients/drcachesim/tests/offline-basic_counts.templatex
clients/drcachesim/tests/offline-builtin-prefetch-basic-counts.templatex
clients/drcachesim/tests/offline-burst_flush_aarch64.templatex
clients/drcachesim/tests/offline-burst_threadL0filter.templatex
clients/drcachesim/tests/offline-burst_threadfilter.templatex
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h
clients/drcachesim/tracer/instru.cpp
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
suite/tests/CMakeLists.txt

Maps variants of AArch64 flush instructions to existing instr and data flush trace types. Also adds count of instr and data flush operations to basic_counts simulator.
Issue: #4328

i#4328: Handle AArch64 cache flush operations in drmemtrace.

---

core/globals.h
core/heap.c
core/lib/statsx.h
core/utils.c
suite/tests/api/thread_churn.c

Given the vmcode vs vmheap split and completely different size limits
on the two, the VMM stats need to be split to be useful.  Here we
split the heap, special heap, and special mmap stats into reachable
and unreachable versions.  We also split the public versions in
dr_statistics_t, renaming and reordering fields, which is not
considered a compatibility break because we are in between releases.
Additionally tested on a large AArch64 app where the stats used to
look something like this:
Peak vmm blocks for heap :             14679
Peak vmm blocks for cache :              5139
Peak vmm blocks for stack :              9039
Peak vmm blocks for special heap :              4518
Peak vmm blocks for special mmap :              9043
Now they are more useful as this (different params so not …

i#4423: Split VMM stats into reachable vs unreachable

---

core/fcache.c
core/heap.c
core/heap.h
core/optionsx.h

Decouples guard page use from cache and heap unit size.
Changes the Windows -vmm_block_size to the page size so that there is
nothing special about 64K for 4K pages.  The logic is that 99% of our
usage stays within the VMM reservations these days, so it is not worth
the complexity of dealing with 64K sizing for 4K pages.
Removes the guard page adjustments to cache and heap units.  Now the
specified sizes are the actual usable sizes, with any guard pages
added externally and not considered as part of the unit size.
Adjusts the default heap unit sizes down by 8K to maintain the same
sizing as before.
Leaves the default cache unit sizes how they were.  The sub-64K did
*not* have 8K subtracted and remain small.  The 64K will now occupy
72K, but shrinking to 56K is complicated by the …

i#2607: Externalize guard pages from units

---

core/arch/arch.c
core/fcache.c
core/heap.c
core/heap.h
core/options.c
core/optionsx.h
core/unix/loader_linux.c
core/unix/os.c

Adds a new option -per_thread_guard_pages controlling whether
per-thread allocations have guard pages.  This option is turned off by
default for >4K pages, removing guard pages from thread-private
initial cache units, all thread-private heap units, thread-private
signal-pending special heap units, stacks, TLS segments (DR and
privlib), and thread-private gencode.  This saves a lot of space on
many-threaded apps, while maintaining guards throughout the VMM from
shared units, which are used far more often than private these days.
Implements the option with a new VMM flag VMM_PER_THREAD, added to the
reservation calls for the above list of unit types.
Additionally, for >4K pages, tunes the default unit sizes to take into
account the guard changes.  Increases the shared unit sizes further
for …

i#4424: Adjust guard pages and unit sizes for >4K pages

---

core/arch/asm_defines.asm
core/arch/x86/mangle.c
suite/tests/common/decode.c

An app with a far cti that uses rcx/ecx but whose segment is flat (cs,
ds, es) today raises a debug-build assert.  It works fine in release.
Here we relax the debug-build assert.
Adds a test case to common.decode which fails with the assert without
this fix.
Issue: #107

i#107 app seg: Relax assert on flat far cti using xcx

---

clients/drcachesim/tests/drmemtrace.threadsig.aarch64.raw/README

Adds a README about how to re-generate the testdata added in PR #4330
commit 58a911a1.
Issue: #4318

i#4318 xarch memtrace: Add README for testdata

---

clients/drcachesim/tracer/instru_online.cpp
core/arch/aarch64/proc.c
core/drlibc/drlibc.c
core/drlibc/drlibc.h

Uses the CTR_EL0 system register to obtain cache line size in proc_get_cache_line_size on AArch64.
Fixes: #4446

i#4446: Obtain AArch64 cache line size using ctr_el0.

---

clients/drcachesim/tests/offline-func_view_noret.templatex
clients/drcachesim/tools/func_view.cpp

After an upgdate, my machine has 7-digit thread id's, causing the
func_view tests to fail.  Here I widen the printed field and update
the expected output for the stored trace.
Issue: #4083

i#4083 func view: Allow for 7-digit thread id in func_view tests

---

core/arch/mangle_shared.c

Disables emulation of thread register reads or writes by the
application when -no_private_loader is in place, such as with
statically linked DR.  Such emulation is unnecessary as the
thread register holds native values in such cases.
Fixes #4459

i#4459: Do not mangle app TLS ops for -no_private_loader

---

CMakeLists.txt
core/lib/dr_annotations_asm.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/annotation-concurrency.appdll.c
suite/tests/client-interface/annotation-concurrency.c

Adds custom annotation macro defines to enable building the
client.annotation-concurrency executable and its shared library on
AArchXX.
Enables the 4 tests that require that executable, but do not need
annotation support: tool.drcachesim.threads,
tool.drcachesim.threads-with-config-file, tool.drcachesim.coherence,
and tool.drcachesim.TLB-threads.
Issue: #4474, #1672

i#4474 A64 testing: Enable drcachesim thread tests

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/tests/delay-global.templatex
clients/drcachesim/tests/offline-max-global.templatex
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Adds a new drcachesim memtrace option -max_global_trace_refs to supply
a global trace size limit that does not kill the process.  When the
maximum is reached, the tracer omits traces for new threads entirely.
Add an online and an offline test for the feature.
Adds documentation.
Fixes #4462

i#4462: Add new global memtrace size limit

---

core/arch/aarch64/emit_utils.c
suite/tests/CMakeLists.txt

Fixes failures to use the writable addresses when patching code on AArch64.
Enables the 5 -satisfy_w_xor_x tests on AArch64.
Fixes #4458

i#4458: W^X on AArch64

---

suite/tests/CMakeLists.txt

PR #4470 for #4468 enabled client.drwrap-test-detach but it seems to
still have problems: PR #4467 found that it hangs 28 out of 100 times.
We re-disable it here for now.
Issue: #1578

i#1578 arm detach: Disable hanging drwrap detach test

---

core/CMakeLists.txt
core/drlibc/drlibc.c
core/drlibc/drlibc.h
core/drlibc/drlibc_notdr_error.c
core/drlibc/drlibc_notdr_ignoreassert.c
core/drlibc/drlibc_x86.asm
core/win32/os.c

On AMD there is a processor bug where the stack segment descriptor is
corrupted after a mode switch from 64-bit to 32-bit which coincides
with a thread context switch.  We fix that by re-loading the
descriptor from the selector, using the value observed at
initialization time.
Duplicate symbol errors which are somehow raised in VS2017 with the
new drlibc call from the core are resolved by moving
d_r_internal_error and d_r_ignore_assert to their own source files.
Tested the code path on an Intel processor.  Will ask those with AMD
processors to test it out before committing.
Fixes #4091

i#4091: Fix crash due to AMD stack segment bug

---

clients/drcachesim/reader/config_reader.cpp
clients/drcachesim/reader/config_reader.h
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/cache_simulator.h

Changes the drcachesim configuration file interface to use a
std::istream rather than a file path string, to support non-standard
filesystems.
Tested with a proprietary filesystem library.
Issue: #2006

i#2006 drcachesim: Support config files on other filesystems

---

clients/drcachesim/reader/config_reader.cpp

The drcachesim config file checking code doesn't free two temporary
arrays.  We fix that here by switching to vectors.

Fix leaks in drcachesim config file check

---

clients/drcachesim/tracer/raw2trace.h

Extends PR #4236 to cover 1-instruction blocks in filtered traces, and
not just 0-instruction blocks, using the top-level filter type flag.
This avoids filling the buffer up with markers using the escape back
to the main loop from PR #4236.
Tested on a proprietary app where drcachesim with filtering hits the
assert added in PR #4236.  This change fixes it.
For a local test: it may be tricky to arrange a live trace to have
enough markers in a row; maybe a synthetic trace.  For now just going
with the manual proprietary test run.
Issue: #4159

i#4159 marker overflow: Use filter flag for 1-instr blocks

---

core/arch/arch.c
core/fcache.c
core/fragment.c
core/synch.c
core/win32/events.mc
suite/tests/CMakeLists.txt

Enables the diagnostic option -steal_reg_at_reset for AArch64,
generalizing the existing ARM code.
Switches -reset_at_fragment_count to work in release build by using
the sum of the release stats num_bbs and num_traces.
Adds a release-build syslog for an informational notification when any
reset occurs.
Adds a test of -steal_reg_at_reset.
Issue: #1569

i#1569 AArch64: Enable -steal_reg_at_reset for AArch64

---

api/samples/cbr.c
ext/drbbdup/drbbdup.c
suite/tests/client-interface/avx512ctx.dll.c
suite/tests/client-interface/cbr3.dll.c
suite/tests/client-interface/cleancall.dll.c
suite/tests/client-interface/drreg-end-restore.dll.c
suite/tests/client-interface/events.dll.c
suite/tests/client-interface/flush.dll.c
suite/tests/client-interface/syscall.dll.c

Instead of using partial struct initialisation, simply initialise the required fields.

Optimise mcontext init by avoiding excessive zeroing.

---

clients/drcachesim/tracer/instru.cpp
clients/drcachesim/tracer/instru_offline.cpp

While investigating #4460 I found that reg_ptr_used in
insert_save_addr is uninitialized locally and insert_obtain_addr only
writes it when true, leaving it uninitialized for the false case: thus
we may re-instate the buffer pointer in cases where we don't need to.
I believe this is only a performance issue.
Issue: #4460

Fix uninitialized var in drmemtrace offline instru

---

clients/drcachesim/tracer/instru.cpp
clients/drcachesim/tracer/instru_offline.cpp

This reverts commit 420adb01d466e134037b1db6ed7023749c3f8034
because it causes crashes in large apps linking drcachesim statically.
We believe that PR #4506 itself is actually correct and that it is
simply revealing an underlying problem, and once we find that problem
the plan is to re-instate it.
Issue: #4460

Revert "Fix uninitialized var in drmemtrace offline instru (#4506)"

---

suite/tests/client-interface/alloc.dll.c
tools/CMakeLists.txt

Fixes a gcc 10 build warning on snprintf overlapping in drdeploy.c by
disabling the warning type.  A better solution would be nice to avoid
missing warnings on real problems but this will do for now.
Fixes a warning about ignoring a return value in the client.alloc test.
Fixes #4363
Fixes #4511

Fix gcc 10 build warnings

---

clients/drcachesim/tests/burst_traceopts.cpp

Fixes an error in the a64 assembly in the burst_traceopts test.  The
test is not yet officially enabled for a64 but that work will be done
later and it seems worth fixing this error now.
Issue: #4474

i#4474 a64 tests: Fix a64 asm error in burst_traceopts

---

core/arch/aarch64/emit_utils.c
core/arch/arm/emit_utils.c
core/lib/mcxtx.h
core/unix/signal.c

Adds a missing restore of the app's stolen register value into the
signal frame's ucontext when a signal interrupts an auto-restart
syscall.  In that case, we do not go through the full translation path
and instead perform a custom translation, which is why we missed this
step.
Adds asserts on several signal paths to help detect similar errors or
regressions in the future.
Adds comments making it more clear what is in the stolen register's
mcontext slot while in the cache.
Tested on the linux.eintr test which fails with the new asserts but
without the fix.  Additionally tested on the proprietary app where it
was first encountered.
Fixes #4460

i#4460: Restore stolen reg on signal in auto-restart syscall

---

core/unix/signal_linux_aarch64.c
core/unix/signal_linux_arm.c

Fixes a crash when an aarch64 signal frame has a NULL fp_simd_state
pointer, which is a legitimate situation.
Tested on the client.signal test's forthcoming port to a64.
Fixes #4518

i#4518: Handle NULL fp_simd_state signal frame pointer

---

core/ir/opnd.h

Avoids padding due to 8-byte-alignment of the new opnd_t.immed_double
field, to keep the layout how it was before PR #4467, avoiding an
init-time assert and problems matching the "black box" exported opnd_t
struct.
Fixes #4520

i#4520: Restore ARM opnd_t layout

---

core/arch/aarch64/aarch64.asm
core/arch/arm/arm.asm
core/unix/os.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/signal.c
suite/tests/client-interface/signal.dll.c

Adds client thread support to AArchXX.
Implements dynamorio_clone for both ARM and AArch64 and adds necessary
TLS swapping, including handling initial tpidr* values pointing at
read-only memory.
Ports the client.signal test's assembly to a64 and arm.  Enables the
client.signal test on aarchxx.  The test covers the client thread support
here, as well as general client signal handling and manipulating.
Tested manually on arm with the #4522 fix.
Issue: #4474, #4516, #4522
Fixes #4516

i#4516: Add client thread support for AArchXX

---

core/dispatch.c
core/synch.c
core/unix/signal.c
suite/tests/CMakeLists.txt

Changes reset trigger for `linux.thread-reset` and `linux.clone-reset` tests to `-reset_at_nth_thread`. To increase coverage of these tests, we need to trigger reset at a time when multiple threads are active. This is difficult to do using the existing` -reset_at_fragment_count` option in tests, which may need to be tuned regularly to its ideal value, which also differs based on platform.
Implements some missing AArch64 pieces for `dynamorio_sigreturn`.
Relaxes dispatch assert to allow threads to enter dispatch after reset. The current condition allows it only when sending threads native.
Fixes #4496
Fixes #4497

i#4496: Fix reset issues on AArch64 and x86

---

core/arch/arch.c

Fixes some ARM defines to be AARCHXX to enable printing AArch64
register values in dump_mcontext().

Print AArch64 register values in dump_mcontext()

---

core/synch.c
core/unix/os.c
core/unix/os_private.h
core/unix/os_public.h
core/unix/signal.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/stolen-reg.c
suite/tests/client-interface/stolen-reg.dll.c
suite/tests/client-interface/stolen-reg.expect

Currently, a stolen register value that is translated by a client is
discarded both in a synchall and a synchronous signal.  We fix both
paths here.
Adds a new test client.stolen-reg which tests both a synchronous fault
signal translation path as well as a synchall translation path via a
synchall flush.  The test was confirmed to fail without either of the
fixes in place.
Ensures the new test passes on 32-bit ARM.  This exercised the
translate_from_synchall_to_dispatch() path and found some ARM bugs:
the reset exit stub is A32 mode, so we need to change the mode for the
suspended sigcontext; yet thread_set_mcontext() did not support that.
That is all fixed now and verified.
Fixes #4495

i#4495: Preserve translated stolen register

---

api/samples/cbr.c
clients/drcachesim/tracer/tracer.cpp
core/lib/instrument_api.h
ext/drbbdup/drbbdup.c
suite/tests/client-interface/cbr3.dll.c
suite/tests/client-interface/flush.dll.c

Fixes drcachesim delayed tracing which was broken by commit 72275ad
for #4496 via PR #4507.  The fix is to decorate the target PC to
indicate the ISA mode.
Adds a reminder to the dr_flush_region_ex() documentation where it
talks about using dr_redirect_execution() to set the ISA mode.
Tested on ARM:
$ bin32/drrun -t drcachesim -trace_after_instrs 20000 -- suite/tests/bin/simple_app
Fixes #4527

i#4527: Set ISA mode for drcachesim flush redirect PC

---

core/ir/aarch64/instr_create.h
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

Adds a fix allowing the 'sp' register as the first source operand of
an ADD or SUB by using the extended-register rather than
shifted-register form on AArch64.
Adds a test which fails without the fix.
Fixes #4542

i#4542: Allow XINST_CREATE_sub with sp source on A64

---

core/ir/decode_shared.c

This appears to be an oversight from when it was added. It got added to the very end of the list after the fractional register sizes, when it should not have been.
Fixes #4537

i#4537: Move OPSZ_8x16 to the correct location in size_names

---

core/ir/instr_inline.h
core/ir/opnd.h
core/ir/opnd_shared.c
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

Adds preservation of AArch64 extended reg and base-disp attributes in
opnd_replace_reg().  Adds some AArch64 basic tests.
Fixes #4540

i#4540: Preserve extended opnd attributes in opnd_replace_reg()

---

core/ir/aarch64/instr.c
core/ir/opnd_shared.c
suite/tests/api/ir_aarch64.c

Fixes reg_is_gpr() to return false for both XZR and WZR.
Adds handling of the two zero register names to the register resize routines.
Adds some tests to api.ir.
Fixes #4560

i#4560: Handle AArch64 zero registers consistently

---

core/arch/aarchxx/mangle.c
core/arch/arch.c
core/ir/aarch64/instr.c
core/ir/instr.h
core/translate.c

Adds recognition of stolen register mangling moves and the special
spills and restores when translating.  Tested by ensuring the
'unsupported mangle instr' messages are gone when running the
client.stolen-reg test.
Fixes #4556

i#4556: Recognize stolen register mangling in translation

---

.github/workflows/ci-aarchxx.yml
.github/workflows/ci-clang-format.yml
.github/workflows/ci-osx.yml
.github/workflows/ci-x86.yml

Changes the Github Actions trigger from pushes on all branches, which
fails to trigger on a pull request from a forked repository, to pull
requests and pushes on master.
Issue: #4549

i#4549 Github Actions: Trigger on pull requests

---

suite/tests/client-interface/winxfer.templatex

Relaxes the client.winxfer test golden output regex further based on
observed output on Appveyor.
Issue: #4058

i#4058 flaky tests: Relax winxfer output regex

---

suite/runsuite_wrapper.pl

Adds client.alloc-noreset to the auto-ignore list.  Although we'd like
to fix the memory iteration issue, we can't reproduce it locally, and
it is making the CI red often enough to be a pain.
Issue: #4436

i#4436 alloc-noreset: Mark client.alloc-noreset as flaky

---

core/ir/decodelib.c
core/ir/disassemble_shared.c

The mask register is always the first source operand. i here is stale, the result of previous loop. The `instr_get_src` correctly uses a hardcoded zero. But instr_info_opnd_type reuses i and dies if the instruction has a single source operand (because i is always out of range). is_evex_mask_pending is not ever set for Intel style disassembly which is why this bug only affects AT&T syntax.
drdisas -syntax att 62 f2 fe 48 28 c9 will trigger this bug.
This is tested in the (currently ifdefed out) binutils AVX-512 tests.
Fixes #4567

i#4567: Handle instructions with a single source operand that's an AVX-512 mask register in AT&T style disassembly

---

suite/runsuite_wrapper.pl

Ignore failure in `tool.drcachesim.delay-simple` test on AArch64 to unblock various PRs. 
Confirmed locally that this test started failing at 893c06c2605eb8423ef4a4b33185d0fef9c75257; the failure didn't show up on the Jenkins test suite for PR #4491 somehow.
Issue: #4571

i#4571: Ignore drcachesim delay-simple failure

---

make/DynamoRIOConfig.cmake.in

Changes the absolute set of COMPILE_DEFINITIONS from PR #4582 for
clients to an append, to avoid breaking clients who set their own
defines (like Dr. Memory).
Tested on Dr. Memory, which fails to configure without this fix when
using the latest DR.
Issue: #4370

i#4370 cmake 3.19: Do no clobber client defines

---

make/utils_exposed.cmake

PR #4582 hardcoded "dynamorio" as the library to link to, breaking
users (like Dr. Memory) who rely on rpath linking to layers of their
own libraries.  We fix that here.
Tested on Dr. Memory, where drfuzz tests fail without this fix when
using the latest DR.
Issue: #4370

i#4370 cmake 3.19: Use proper target lib for rpath

---

core/win32/ntdll.c

Uses the empirically-determined syscall numbers even for OS versions
we have in our static table, for win10-1511+.  We have seen variants
that our current version logic is not aware of, and we're using the
from-wrapper numbers on all very-recent versions anyway.
Tested on the Github Actions Windows Server 16 images.
Issue: #4587, DynamoRIO/drmemory#2329
Fixes #4587

i#4587: Use from-wrapper syscall numbers for all win10

---

core/arch/aarchxx/mangle.c
core/arch/mangle_shared.c
core/arch/proc.h
core/arch/proc_shared.c
core/optionsx.h
suite/tests/client-interface/ldstex.c
suite/tests/client-interface/ldstex.dll.c

Turns on -ldstex2cas by default for 32-bit ARM.
However, adds bailing on conversion for predication or for pair
operations, which are not yet handled.
Fixes -no_ldstex2cas to properly mangle stolen register usage in
exclusive operations.
Adds proc_get_architecture() for determining whether the processor
supports load-acquire operations.
Tested on the client.ldstex test on ARM Linux.
Issue: #1698

i#1698 ldstex: Enable -ldstex2cas on ARM by default

---

core/arch/arch.h
core/arch/clean_call_opt_shared.c
core/arch/mangle_shared.c
core/lib/instrument.c
core/lib/statsx.h

Adds X86 ifdefs around the AVX-512 opmask fields in the clean call
optimization structures and the code that references them, to avoid
zero-size-array compiler errors with gcc10 (and with Visual Studio).
Issue: #1684, #4594
Fixes #4594

i#4594: Fix a64 gcc10 zero-size-array build failures

---

libutil/dr_config.c
suite/tests/libutil/drconfig_test.c

Fixes a bug where drconfiglib clobbers the buffer holding the library
path before it reads it to check for debug vs release build.
Adds a test of debug to libutil.drconfig_test which fails without this
fix.
Fixes #4597

i#4597: Fix drconfig error reading debug status

---

api/docs/samples.dox
api/docs/transp.dox
core/arch/proc.h
core/lib/instrument_api.h

Clarifies the prose documentation and API routine documentation on
what floating-point state is preserved and what is not by DR and what
the various explicit "fpstate" preservation routines operate on: only
the *x87* floating-point state.
Fixes #2629

i#2629: Clarify docs on floating-point preservation

---

core/arch/aarchxx/mangle.c
suite/tests/client-interface/ldstex.c

Adds comments explaining why we're leaving DR's strict equality checks
on the base address and size between the exclusive-load and
exclusive-store.
Issue: #1698

i#1698 ldstex2cas: Add comments on mismatched pair handling

---

.github/workflows/ci-aarchxx.yml
.github/workflows/ci-x86.yml

PR #4599 failed to add auto-cancel to jobs beyond the first in each
workflow, thus missing 3 jobs.  We correct that here.
Issue: #4585

i#4585 CI autocancel: Add missing auto-cancel to 3 jobs

---

core/arch/interp.c
core/dispatch.c
core/synch.c
core/unix/signal.c
core/utils.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/gonative.c
suite/tests/client-interface/gonative.dll.c
suite/tests/client-interface/gonative.expect

Adds a new execute_native_handler() feature where DR delivers a signal
to a currently-native thread.  For a native thread, a signal frame is
set up on the appropriate stack, blocked signals are set natively
rather than for emulation, and control is directly sent to the
application's handler.
Adds handling of asynchronous signals by not recording them for
delivery later but delivering immediately.
Adds a test that uses the client interface DR_EMIT_GO_NATIVE to send a
thread native.  The app then generates a synchronous and an
asynchronous signal.
Initial attempts are made to also handle a pure-native thread with no
dcontex, such as late in detach, but that portion is not fully
finished and will be completed separately.  Handling deault-action
signals is also not fully tested and likely …

i#1921 native sig: Add handling for signals for temp-native threads

---

.github/workflows/ci-package.yml
suite/runsuite.cmake
suite/runsuite_wrapper.pl

Adds a new GA workflow triggered via cron Fridays 9pm or manually with
version and build input fields.
Uses 4 parallel jobs to build 5 packages: Linux, AArch64, ARM,
Android, and Windows.  Each job uploads its binaries as artifacts,
allowing sharing between jobs (having each build job racily create and
upload to the same release failed: there is no check for an existing
release in the provided scripts).
Then a separate job waits for the build jobs to finish, creates a
release (which includes adding a tag), downloads the artifacts, and
uploads them to the release.
Adds a step to the Linux package job to deploy the html documentation
to our Github Pages docs site.  Relies on a personal access token stored
as a secret in the dynamorio repository for access to dynamorio_docs.
Renames the …

i#4549 GA CI: Add release package building and uploading

---

suite/runsuite_wrapper.pl

Updates the Windows CI ignore list bug numbers to reflect the
newly-filed individual issues.
Re-adds client.drwrap-test-detach to the ignore list for 32-bit.
Issue: #2246, #4616, #4617, #4618, #4619, #4621, #4622, #4131, #4058

i#4131 Windows CI: Update ignore list bug numbers

---

.github/workflows/ci-package.yml

Fixes a few issues with the script added in PR #4612:
+ Splits the a64 and a32 builds into separate jobs, as package.cmake doesn't support both at once.
+ Fixes minor issues.
Tested via a manual launch with filled-in version and build and it worked:
+ https://github.com/DynamoRIO/dynamorio/actions/runs/424016479
(longest build time: Windows took 29:15)
+ https://github.com/DynamoRIO/dynamorio/releases/tag/release_8.0.18611-2
All 5 files are present and with similar sizes to the last Travis+Appevyor-produced build, indicating they do contain Dr. Memory.
+ https://dynamorio.org/dynamorio_docs/ has a new timestamp: successful docs deployment
Issue: #4549

i#4549: Finalize package building and docs deployment

---

suite/runsuite_wrapper.pl

Adds client.drwrap-test-detach to the 32-bit Linux ignore list as it
is a known flaky failure.
Issue: #4593

i#4593 drwrap-detach-test: Add to ignore list

---

suite/runsuite_wrapper.pl

Re-enables the `code_api|tool.drcachesim.delay-simple` test on AArch64, following the PR #4513 fix.
Fixes: #4571

i#4571: Enable drcachesim delay-simple on AArch64

---

core/arch/aarchxx/mangle.c
core/ir/aarch64/instr_create.h
core/ir/arm/instr_create.h
core/ir/x86/instr_create.h
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect
suite/tests/api/ir_arm.c
suite/tests/api/ir_x86.c

Adds `XINST_CREATE_call_ind` macros for ARM, AArch64 and x86. They point to the respective instrs on the platforms for transferring control to address in given register operand.

iX add platform-independent macros for call ind

---

.github/workflows/ci-package.yml

The cronbuild version was missing the major and minor: that was on the
tag only.  We fix that here.
Adds a source checkout to the release job, needed to run "git log"
to compute the version.
Allows manual cronbuilds via a blank version, so we can actually test
them on demand, and create them separately from the scheduled time.
Applies input build numbers to cronbuilds too so we can manually test
them the same day as a scheduled build.
Moves the scheduled cronbuild to 2am UTC for 9pm EST.
Issue: #4549

i#4549 GA CI: Fix cronbuild version errors and allow manual

---

.github/workflows/ci-package.yml
.github/workflows/ci-windows.yml

The doxygen.nl URL breaks every few months when they put out their
latest release and remove the old release.  We switch to their
sourceforge site which archives old releases, so we won't break in the
near future.  (Xref #4000 where we used to use chocolatey to avoid
specifying the precise version: but choco was flaky.)

Use a stable URL for downloading Windows doxygen

---

core/dynamo.c
core/globals.h
core/synch.c
core/unix/os.c
core/unix/signal.c

Eliminates a race on detach where the detaching thread removes DR's
SIGSEGV handler while a now-native detached thread is in the middle of
having a signal delivered (natively) and invokes a TLS magic field
safe read, whose SIGSEGV then goes to the application.
The detaching thread is the one doing all the real cleanup, so we
simply avoid any safe reads or TLS for detaching threads by recording
the detacher's ID when we start the detach process.  This var is not
cleared until re-init, so we have no race with the end of detach.
Tested on api.detach_signal with the forthcoming signal mask checks,
which trigger when the handler is invoked for a DR signal instead of
an app-generated signal.  Without this fix, the test fails easily:
about 1 in 5 runs in debug build.  With this fix, it succeeds …

i#3535: Solve detach handler race

---

core/unix/signal.c
suite/tests/api/detach_signal.cpp

Adds proper signal mask setting for native signals, which requires
adding handler-masked signals to the DR frame's mask instead of
setting the mask in the kernel.
Adds tests to api.detach_signal.  These mask tests also detect when a
DR-caused crash from a DR bug during detach shows up in the app's
handler post-detach due to detach races, including from #3535.
Issue: #1921, #3535

i#1921 native sig: Properly set native signal mask

---

core/unix/signal.c
core/win32/events.mc
suite/tests/api/detach_signal.cpp

The native frame adjustments to handle the DR handler being on the
native stack previously failed to handle an application with a
sigaltstack.  We correct that here.
Adds sigaltstack testing to the api.detach_signal test.  With a
smaller stack, this exercises the stack-too-small error message path
from DR.
Issue: #1921

i#1921 native sig: Account for sigaltstack when placing native frames

---

core/ir/x86/decode.c

Fix a bug that can trigger a warning about invalid VSIB encodings, and then enable AVX-512 decenc tests for supported instructions. There are issues on file for everything that's still ifdefed out. There's still no "ground truth" testing that these outputs actually correspond to what binutils gives.

Enable binutils decenc tests for AVX-512

---

core/ir/decodelib.c

This fixes a regression introduced in #4567.

Don't use libc's stderr in libdrdecode

---

CMakeLists.txt

Makes doxygen required for all test suite builds, including Windows,
rather than just a soft warning.  We need it to work in order to
create release packages, after all.
Fixes #4654

i#4654: Require doxygen for test suite builds

---

core/dynamo.c
core/win32/events.mc

Adds a check and a fatal error when calling dr_app_setup() in the
middle of standalone library usage (such as from a custom allocator
using DR heap outside of DR-managed windows).  This is much nicer than
a mysterious crash that happens otherwise.
Tested on a proposed #4640 solution to eliminate application heap from
droption where the droption static initializers use DR heap and thus
invoke standalone mode behind the scenes, while later the app tries to
run dr_app_setup().
Issue: #4640

i#4640 static client: Detect mixing standalone and full DR

---

clients/drcachesim/common/options.cpp

Fixes several drcachesim options which specified DROPTION_SCOPE_ALL
but are actually only used by the client.  This can affect heap usage
for option sweeping, which was how it was discovered while examining
heap usage for #4640.

Fix incorrect drcachesim option scopes

---

core/options.c
core/optionsx.h

`fragment_prefix_size` returns an incorrect value on AArch64 when `-shared_bb_ibt_tables` is set. To fix this, we set the default value of `-bb_prefixes` to true on AArch64.
Fixes: #4658

i#4658: Fix fragment_prefix_size on AArch64.

---

core/dynamo.c
core/globals.h
core/unix/signal.c
core/utils.c
core/utils.h
suite/tests/CMakeLists.txt
suite/tests/api/detach_signal.cpp

Puts in place 6 fixes for handling signals during DR initialization,
typically in a start/stop setup where other threads are alive.
1) Copy the app handler at init time for delivering native signals
during init.
2) Reorder signal_arch_init(), which obtains the signal frame size, to
run before DR installs its handler.
3) Obtains the app handler before installing DR's handler, eliminating
a (narrow) race window.
4) Until DR starts executing the app, continues delivering native
signals and using the globally recorded app handler, to match how DR
init works.
5) Set detacher_tid between init and setup to avoid races like in
DR's handler at the end of init that were under #3535
6) Handle a race where the init thread has set the global try_except,
causing master_signal_handler_C to think an app …

i#1921 native sig: Handle signals during DR initialization

---

core/unix/signal.c
suite/tests/api/static_crash.c
suite/tests/api/static_crash.templatex

A fault in the executable that has a statically-linked client and DR
is currently reported as a client crash, even though we have no way to
distinguish client code from app code in such a situation.  We change
that here to invoke execute_native_handler(), which solves problems
where the application has a fault handler in place and a tool or other
mechanism that generates faults during DR init or other points.
I tried to reproduce this by making a static version of
api.detach_signal but it requires a fault-generating allocator
replacement (hit by droption and other places that use the system
allocator) or something similar, which is non-trivial to replicate in
a small test.  I did test on the original proprietary application.
Fixes #4640

i#4640: Pass static "client" faults to the app

---

core/ir/x86/decode_fast.c
suite/tests/api/ir_x86.c

When decoding the two-byte c5 VEX prefix, currently the second byte of the prefix is not skipped and is instead treated as its own prefix. If the second byte is, say, c4, that will trigger the three-byte c4 VEX prefix code path which will cause decode_cti to fail spuriously. Since VEX prefixes are always the final prefix, just copy what we do for c4 VEX and EVEX prefixes and stop looking for additional prefixes after we see a c5 VEX prefix.

Stop searching for additional prefixes in decode_cti after a c5 VEX prefix is found

---

core/translate.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/timer.c
suite/tests/client-interface/timer.dll.c

Applies the existing client_data->is_translating debug flag to avoid a
curiosity and an assert on translation failure stemming from client
use of dr_app_pc_from_cache_pc() on a sampling itimer.
Augments the client.timer test to run with -disable_traces and use a
lot of indirect branches to trigger a curiosity on xl8 failure on
every run when the iterations are increased (a little too high for our
small regression tests though).  With this fix, the curiosity never
occurs.
Issue: #4669

i#4669 xl8 failures: No asserts for client xl8 requests

---

core/loader_shared.c

This is a general diagnostic improvement identified under issue #4669:
having the DR library (or static exe for static linking) included in
the callstack simplifies offline symbolization.  Client library bases
were already included.
Here is what the new output looks like, tested on client.timer with
the prior #4669 fix from PR #4672 disabled so the curiosity showed up:
<CURIOSITY : tdcontext != ...
version 8.0.18639, custom build
-no_dynamic_options ...
0x00007fa69912a0a0 0x00007fa8dd273fa5
0x00007fa69912a1b0 0x00007fa8dd276688
0x00007fa69912b4c0 0x00007fa8dd2769fc
0x00007fa69912be10 0x00007fa8dd26f2ae
0x00007fa69912be50 0x00007fa8990742c0
0x00007fa69912be90 0x00007fa8dd366d63
0x00007fa69912c810 0x00007fa8dd35f3d2
0x00007fa69912c9b0 0x00007fa8dd31d034
0x00007ffdf0bb12b0 0x00007fa8dce7cd0a …

i#4669 xl8 failures: Include DR base in assert messages

---

core/arch/interp.c
core/translate.c

Fixes two issues with rip-relative push translation:
1) The push must be cleared on the first instruction of a subsequent
consecutive mangling region.  For this we split
translate_walk_state() into pre_instr and post_instr versions.
This split then raises an assert due to recreate_fragment_ilist()
changing an exit jump's target without re-instating the
instr_set_our_mangling(), which we also fix here.
2) The assert about stack changes in the epilogue must be relaxed.
Tested on the decode-stress test on Linux x86, which is not yet fully
enabled in the suite as it needs more work: that's #1025.
Issue: #1025, #4679
Fixes #4679

i#4679: Rip-relative push translation

---

core/arch/x86/mangle.c
core/translate.c

Marks segment moves as "our mangling" for proper spill restoration on
translation.
Adds segment move mangling opcodes to the list of known manglings to
avoid marking as unsupported, which can lead to translation failures.
Tested on the decode-stress test on Linux and Windows.  #1025
and #4618 cover enabling/un-ignoring the test in the suite.
Issue: #1025, #4618, #4681
Fixes #4681

i#4681: Restore spills on translation for segment moves

---

core/arch/x86/mangle.c
suite/tests/CMakeLists.txt
suite/tests/common/decode.c
suite/tests/common/decode.templatex

Enables the decode-stress test for UNIX x86 after confirming all the
bugs are fixed (#4679, #4681).  The bug reported in the #1025 issue
does not reproduce.
Issue: #1025, #4679, #4681
Fixes #1025

i#1025: Enable decode-stress test on UNIX x86

---

suite/runsuite_wrapper.pl
suite/tests/common/decode.c
suite/tests/common/decode.templatex

Adjusts the setjmp call from common.decode's assembly to use the
pre-parameter-slot stack value, avoiding fatal crashes on longjmp.
Disables test_data16_mbr() on 64-bit Windows, as SEH64 can't handle
the unaligned stacks and other oddities of the instructions there.  We
still have coverage on 64-bit Linux which is sufficient.
Removes the ignore rules on failure for common.decode and
common.decode-stress from the runsuite_wrapper.
Issue: #4618

i#4618 SEH fail: Fix common.decode Windows failures

---

core/arch/aarchxx/mangle.c

Fixes a missing translation field for a conditional branch that uses
the stolen register.
This was caught by the forthcoming common.broadfun-stress test, which
will serve as the regression test once it is added after all other
bugs it finds are addressed.
Issue: #4680

i#4680 aarch xl8: Fix missing translation of stolen-reg cbr

---

core/emit.c
core/translate.c
suite/tests/common/decode.c

Adds handling of translation inside short-cti-rewrite bundles.
Adds an OP_jecxz to common.decode as a test of short cti mangling.
Changes the DOLOG stress test qualifiers for -stress_recreate_* to
DOCHECK so we run them every time and not just at high loglevel.
Tested on arm on the forthcoming common.broadfun-stress test.
Issue: #4680

i#4680 aarch xl8: Add intra-short-cti-bundle translation

---

core/arch/arch_exports.h
core/emit.c
core/ir/arm/decode.c
core/ir/arm/encode.c
core/ir/instr_shared.c
core/ir/instrlist.c

Fixes 3 issues with IT state tracking for ad-hoc decoding/encoding
uncovered by -stress_recreate_state:
+ Fixes a use-after-free by adding a hook in instr_destroy() to reset
the IT state if the stored instruction is freed, along with a state
reset in instrlist_clear().
+ On decode, limit advance-undo prior-instruction matching to the
current instruction's Thumb size, to avoid incorrect advance-undo
when switching between decoding sequences.
Also, check for the current instruction being OP_it via raw
byte checks to again avoid incorrect advance-undo.
+ On encode, walk backward to re-identify IT blocks after a state reset.
Tested on the forthcoming common.broadfun-stress test on ARM.
Issue: #4680

i#4680 aarch xl8: Fix IT state tracking bugs

---

core/translate.c

Relaxes a too-strict assert on TLS spill-restore proper pairing when
across application instructions, which happens on AArchXX.  We now
only look for restores of the precise spills we observed.
This showed up on the forthcoming common.decode-stress test on arm.
Issue: #4680

i#4680 aarch xl8: Relax spill-restore pairing assert

---

core/translate.c
suite/tests/CMakeLists.txt

Generalizes stress_test_recreate_state(), mostly just the indirect
branch target register.
Adds a -stress_recreate_test for aarch, as "common.broadfun-stress"
since common.decode is so x86-specific we may never make an arm
version.
Fixes #4680

i#4680 aarch xl8: Port stress_test_recreate_state() to aarch

---

core/arch/mangle_shared.c
core/ir/x86/opcode.h

Uses backward raw decoding to deduce 64-bit system call numbers on
Win10-1511+ where a branch isolates the syscall instruction in its own
block.
Fixes #4700

i#4700: Deduce syscall numbers on Win10-1511+

---

core/win32/module_shared.c
core/win32/ntdll.c
core/win32/os.c
core/win32/os_private.h
core/win32/syscall.c

Changes all stack buffers using hardcoded sizes for CONTEXT to instead
use heap-allocated buffers sized to match the kernel's actual CONTEXT
size for the given flags.
Adds a mechanism to query the CONTEXT64 size from 32-bit DR using
switch_modes_and_call().
The one place where we can't easily use heap is
thread_set_self_mcontext() because it doesn't return and we thus do
not have a simple way to free the buffer.  There, we use a large
4096-byte stack buffer, and we check the size needed: if it's larger
than that, we use a lost heap allocation and issue a debug build
warning which should alert someone.  If we end up needing more space
there in the future we may want to store a pointer in the dcontext and
have a special check to free it or something.
Fixes #2666

i#2666: Dynamically size CONTEXT buffers

---

clients/drcachesim/tracer/tracer.cpp

Fixes compilation warning for potentially uninitialized variable in tracer.cpp (drcachesim).
Issue: #4487

i#4487: fix compiler warning for uninit var

---

core/dispatch.c
core/fragment.c
core/fragment.h
core/lib/statsx.h

When an indirect branch lookup table (IBT) is resized, the old table
is filled with "target deleted" markers.  Another thread that hits in
the table is redirected to a cache exit due to the deleted marker.
However, previously that thread would *not* update its thread-local
pointer to the table on such an exit; it would only update on an
actual miss in the table.  This can lead to repeated cache exits on
hits until a miss is reached.
The problem is solved here with an explicit update of all tables on a
target-deleted exit.
Tested on "bin32/drrun -disable_traces -shared_bb_ibt_tables
-shared_ibt_table_bb_init 2 -- suite/tests/bin/linux.signest" on ARM.
Fixes #4704

i#4704: Update thread IBT on exit due to delete

---

core/arch/asm_defines.asm
make/CMake_asm.cmake
suite/tests/CMakeLists.txt
suite/tests/api/detach_state.c
suite/tests/api/detach_state_shared.h

Enables api.detach_state on AArch64 with some initial the sub-tests enabled:
+ Enables the cross-platform signal state tests on AArch64.
+ Ports the assembly to push and pop all the general-purpose
registers, fill them with sentinel values, and test them on a detach
from the code cache.
As part of this, adds some general assembly support:
+ @P@ expands to # in cpp2asm.
+ Adds REG_SP and JUMP_NOT_EQUAL cross-platform asm_defines.
+ Adds a missing dep on detach_state_shared.h for the asm code.
Still left to do for future work:
+ Check SIMD registers.
+ Check flags.
+ Check stack.
+ Detach from DR rather than the cache.
Issue: #4698

i#4698 detach_state: Port signal + GPR-cache tests to A64

---

suite/tests/client-interface/stolen-reg.c
suite/tests/client-interface/stolen-reg.dll.c

Fixes a race in the test where the synchall can catch the main thread
before it returns from calling create_thread(), in which case the
app's code to restore the callee-saved stolen register overwrites the
client's restored value.
Tested on ARM and by running 2000x on AArch64.
Fixes #4671

i#4671: Fix flaw in translation point in stolen-reg test

---

suite/tests/CMakeLists.txt

The api.startstop test was crashing previously, but one of the many
recent fixes seems to have addressed that problem.  It now runs to
completion 1000x in a row on AArch64.
Issue: #1578, #4474

i#1578,i#4474 arm detach: Enable api.startstop on arm

---

ext/drwrap/drwrap.c

drwrap_ensure_postcall may not return. Thus, we should decrement
wrap_level, so, it won't be incremented again in drwrap_in_callee. We
reproduce the behavior prior to 9bb0354 commit.
Fixes #4607

i#4607: Fix null pointer dereference in drwrap

---

api/docs/API.doxy
clients/drcachesim/tracer/drmemtrace.h

Removes the obsolete Doxyfile entry COLS_IN_ALPHA_INDEX.
Fixes a code vs docs mismatch on a parameter name in drmemtrace.h.
Tested with a local doxygen 1.9.1 build.
Fixes #4712

i#4712: Fix doxygen 1.9.1 build errors

---

core/dispatch.c
suite/tests/CMakeLists.txt
suite/tests/api/static_prepop.c

Fixes a bug in the api.static_prepop assembly where the link register
is clobbered, leading to an infinite loop on aarchxx.
Enables the test for aarchxx.
Fixes a bug on identifying stopping points on ARM where LSB Thumb
decoration on the two sides of the comparison was not consistent.
Fixes a corresponding bug on going native where the LSB was not set.
Tested manually on ARM.
Issue: #1578, #4717, #4720
Fixes #4717

i#4717: Fix hang in api.static_prepop test on aarchxx

---

core/win32/os.c
core/win32/syscall.c

Fixes a bug in PR #4703 where for post-CreateUserProcess handling it
frees the heap buffer for a CONTEXT before the code is finished using
it.
Also updates the CONTEXT heap buffers from PR #4703 to use
thread-private heap where possible, to avoid locks.
Issue: #2666

i#2666 dyn cxt: Fix early context free

---

core/optionsx.h
core/unix/os.c
core/win32/events.mc

Adds a maximum tries when waiting for a thread to be taken over at
initialization time, instead of looping forever.  When the max is hit,
a fatal error is raised, unless a newly added option
-ignore_takeover_timeout is set.
The new option is used to ignore QEMU's own thread when running DR
under QEMU.  QEMU is not fully transparent and unfortunately does not
hide its thread from DR in procfs.
Manually tested both option settings under QEMU.  Regression tests
with QEMU are planned for the test suite for ARM.
Issue: #4719

i#4719 qemu: Add -ignore_takeover_timeout

---

core/optionsx.h
core/unix/os.c

Fixes a problem with the hardcoded small timeout from PR #4725 by
parameterizing the timeout in a new option -takeover_timeout_ms.  It
is set to a high value by default; the plan is to have -xarch_root set
it to a low value for the common QEMU case of running a small test,
while still overridable for large apps.
Renames -ignore_takeover_timeout to -unsafe_ignore_takeover_timeout to
indicate that it can cause problems if actual application threads are
left native.
Issue: #4719

i#4719 qemu: Add -takeover_timeout_ms

---

core/drlibc/drlibc_module_elf.c
core/dynamo.c
core/globals.h
core/heap.h
core/module_shared.h
core/optionsx.h
core/unix/loader.c
core/unix/os.c

Adds a new option -xarch_root which sets a path that is prepended to:
+ The application executable's interpreter, if the original does not exist.
+ SYS_openat paths, if the original does not exist.
+ System paths ued for loading private libraries: here the prefix is prepended
before checking whether the original exists.
Splits dynamorio_app_init() into two pieces in order to have the
options set up at the time the loader maps the interpreter, while
avoiding ordering problems with the rest of the initialization.
The new option also auto-sets -ignore_takeover_timeout for
convenience, as that is always needed when running under QEMU.
Manually tested in cross-compile AArchXX setups on a Debian system.
Test suite integration is forthcoming.
Issue: #4719

i#4719 qemu: Add xarch_root option for QEMU

---

core/config.c
core/dynamo.c
core/globals.h
core/unix/loader.c

Avoids printing of an internal warning during early initialization for
single-bitwidth setups regardless of -stderr_mask by moving options
init even earlier.
To avoid DR heap init messing up the app's brk setup, moves heap init
out of the options init and into the later half.  This undoes the
early heap init from PR #4726, which is worked around by switching to
a stack buffer for -arch_init.  This seems safer in any case, delaying
heap init and client lib loads until after the app's interpreter is
loaded.
Issue: #4719

Avoid blind syslog during init

---

clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Switches the module_mapper_t used by raw2trace to explicitly track
individual segments, rather than collapsing them into the single
whole-module mmap, in order to handle objects like vdso allocated in
gaps between the segments.
Tested on a proprietary system where vdso was in the middle of ld.so,
causing the opcode_mix tool to crash.  (Creating a regression test
would be complex, requiring synthesizing ELF files with the required
characteristics.)
Fixes #4731

i#4731: Properly handle non-empty segment gaps in raw2trace

---

api/docs/release.dox
clients/drcachesim/tests/burst_replace.cpp
clients/drcachesim/tracer/drmemtrace.h
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/tracer.cpp
ext/drcovlib/drcovlib.h
ext/drcovlib/modules.c
suite/tests/client-interface/drmodtrack-test.dll.cpp

Changes the drmodtrack_add_custom_data() and
drmemtrace_custom_module_data() interfaces to call each load and free
callback separately for each module segment, adding a new parameter
with the segment index to the load callback.
This eliminates a superfluous vdso map when the vdso is split into two
segments (#3900), and properly handles a gap between segments with
custom data.
Updates the documentation to indicate the compatibility break.  Since
this is isolated to rarely used extension libraries and drcachesim
interfaces, we do not bump DR's own release major or minor numbers.
Compatibility is maintained for drcachesim offline traces, so the
offline trace and custom module versions are not changed.
Tested by running opcode_mix with -verbose 1.
Before we mapped 8K twice and never used the …

i#4741: Split custom modtrack data by segment

---

api/docs/bt.dox
api/docs/intro.dox

Removes several cases where the documentation about the IR says
"IA-32" when it means all the ISA'ss we support.

Remove IA-32 from general IR statements

---

core/unix/loader.c

Fixes a bug introduced by PR #4729 which swapped a heap buffer for a
stack buffer but placed the buffer in a too-deep scope.
Manually tested via:
$ qemu-aarch64 -L /usr/aarch64-linux-gnu bin64/drrun -xarch_root /usr/aarch64-linux-gnu -- suite/tests/bin/simple_app
$ qemu-arm -L /usr/arm-linux-gnueabihf bin32/drrun -xarch_root /usr/arm-linux-gnueabihf -- suite/tests/bin/simple_app
Forthcoming test suite support for running under qemu will add CI
tests that will avoid such regressions in the future.
Issue: #4719

i#4719 qemu: Fix regression in interp rewrite

---

.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/CMakeLists.txt
api/docs/CMake_doxyfile.cmake
api/docs/CMake_rundoxygen.cmake
make/package.cmake

Creates a second version of the doxygen html output suitable for
embedding in our jekyll-based web site.  This version turns off the
doxygen treeview, but then borrows the javascript menu files from the
treeview version.  We then edit the html to remove the headers, and
edit the menu files for inlining into our web site's single array.
Furthermore, we generate keyword search term data so that searches
using lunr for functions or types result in direct links to their
anchors within their pages.  It generates keyword tokens for each
component of an underscore-separated multi-word type, along with
tokens for each prefix (e.g., so that "dr_mutex" will find
"dr_mutex_*").
Adds installation into a "docs_embed" directory.
Adds deployment logic to package.cmake to copy the embedded html to a
top …

i#4111: Generate doxygen suitable for embedding in jekyll

---

.github/workflows/ci-aarchxx.yml
CMakeLists.txt
core/CMakeLists.txt
core/unix/signal.c
make/utils_exposed.cmake
suite/runsuite.cmake
suite/tests/CMakeLists.txt

When cross-compiling, inserts QEMU commands into each test command line.
Increases the test timeouts by 4x to account for emulation overhead.
Adds GA CI support by installing QEMU and enabling running tests for
the AArchXX cross-compilation jobs.  For now, limits the tests to
those marked with a new label RUNS_ON_QEMU, which starts out added to
the ~1/3 of tests that currently pass.  As we get more tests to work
we may want to separate the jobs if they take too much time.
Issue: #4719

i#4719 qemu: Add support for running tests under QEMU

---

make/package.cmake
make/toolchain-aarch64.cmake
suite/runsuite.cmake

Renames toolchain-arm64.cmake to toolchain-aarch64.cmake to match
conventions.
Renames the test suite runs arm-xx-yy-64 to aarch64-xx-yy and
arm-xx-yy-32 to arm-xx-yy.
Issue: #1569

i#1569 AArch64: Rename arm64 to aarch64

---

core/ir/x86/decode_table.c
suite/tests/api/ir_x86_2args_avx512_evex.h

These instruction variants, which do not have a EVEX.W=0 vmovd equivalent, were missed when EVEX instructions were added. The XMM/mem forms of these instructions are redundant with existing encodings and can't be tested via the normal encoding API.
Fixes #4755.

Add EVEX encodings of missing vmovq variants.

---

api/docs/CMake_rundoxygen.cmake

Use permalinks to deploy all the content from the docs/ web subdir
into the top level, rather than having docs/ in every single URL.
Issue: #4111

i#4111 web: Deploy web content from docs/ to root dir

---

.github/workflows/ci-docs.yml

Adds a new ci-docs workflow to publish docs changes to the web site
without also building a new release package.
Issue: #4111

i#4111 web: Add docs-only GA workflow

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml

For the ci-docs workflow, use Ubuntu 20.04 for a newer doxygen for
better markdown support.
Issue: #4111

i#4111 web: Use newer Ubuntu for newer doxygen for docs

---

core/ir/aarch64/instr_create.h
core/ir/arm/instr_create.h
core/ir/x86/instr_create.h
ext/drbbdup/drbbdup.h
ext/drcontainers/drtable.h
ext/drcontainers/drvector.h
ext/drcontainers/hashtable.h
ext/drcovlib/drcovlib.h
ext/drmgr/drmgr.h
ext/drreg/drreg.h
ext/drsyms/drsyms.h
ext/drutil/drutil.h
ext/drwrap/drwrap.h
ext/drx/drx.h
tools/arm_macros_gen.pl

The group delimiters @{ and @} in our headers were inside regular C
comments rather than Doxygen comments.  This worked fine with doxygen
through 1.8.13; but 1.8.17 and up ignore these group directives.  Here
we fix this by adding the extra asterisk.
Fixes #4749

i#4749: Use proper doxygen comments for group delimiters

---

suite/tests/linux/syscall_pwait.cpp

Passes by reference in the syscall_pwait test to avoid a copy.
This was suggested by an automated clang-tidy tool.

Avoid copy via pass by reference in test

---

suite/runsuite_wrapper.pl

Adds the burst_static and burst_replace tests for 64-bit Windows to
the ignore list.  We would like to fix them, esp. since the failure is
a core assert, but nobody can reproduce the assert hit locally.
Adds 32-bit Linux thread-reset to the ignore list.
Issue: #4486, #4604

i#4486,i#4604: Add flaky tests to ignore list

---

api/docs/CMake_rundoxygen.cmake
api/docs/intro.dox

Rewrites the handful of image paths to point to an images/ subdir.
Removes the superfluous logo image on the overview page, along with the
superfluous references.
Issue: #4111

i#4111 web: Redirect image paths to subdir

---

.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md
README
README.md
api/docs/README.md
api/docs/home.dox
api/docs/ldstex.dox
api/docs/test_suite.dox
api/docs/workflow.dox
api/samples/README.md
clients/drcachesim/README.md
clients/drcov/README.md
clients/drcpusim/README.md
core/README.md
core/annotations.c
core/arch/aarch64/emit_utils.c
core/arch/aarchxx/mangle.c
core/lib/dr_annotations_asm.h
ext/README.md
ext/drcontainers/README.md
ext/drgui/README.md
ext/drmgr/README.md
ext/drsyms/README.md
ext/drutil/README.md
ext/drwrap/README.md
ext/drx/README.md
libutil/README.md
make/README.md
make/git/git_review.sh
suite/README.md

Updates links to the now-moved wiki pages.
Updates the Worklow page to remove a superfluous section layer.
Issue: #4111

i#4111 web: Update stale wiki links

---

api/docs/code_reviews.dox

Adds a note to the section on submitting a Pull Request
from a forked repo that Actions must be allowed.

Document permissions needed for forked PR

---

ext/drcovlib/drcovlib.h
ext/drcovlib/modules.c

PR #2940 and #2973 added an offset field to drmodtrack for #2939, but
they ifdef-ed the field in some places but not others, resulting in
uninitialized output.  Since it's already locked into the interface,
we always set it to 0 here and include it in internal structures to
fix the problem.
Tested on drmodtrack-test where the fields were manually confirmed to
no longer contain bogus values, and where the test doesn't fail when
i#4474 adds a new field that shifts the test buffer to avoid the
happens-to-match scenario that masked this bug in that test before.
Issue: #2939, #4474, #4777
Fixes #4777

i#4777: Fix uninitialized drmodtrack offset on Windows

---

api/docs/release.dox
core/lib/instrument.c
core/lib/instrument_api.h
ext/drcovlib/drcovlib.h
ext/drcovlib/modules.c
suite/tests/client-interface/drmodtrack-test.dll.cpp
suite/tests/client-interface/modules.dll.c

Adds a preferred_base field to the module_data_t struct.  There is no
compatibility break as DR allocates all such structs.
Adds a preferred_base field to the drmodtrack_info_t struct.  There is
no compatibility break as it has a struct_size field.  Offline
drmodtrack files do incur a version bump here, so an old reader will
fail when reading a file with the new field.  The field is set to a -1
sentinel to aid in determining whether a file has the field or not.
This is also done here with the previously-added offset field.
Adds some sanity checks to the corresponding tests.
Fixes #4774

i#4774: Add preferred base to DR and drmodtrack interfaces

---

api/docs/building.dox

Be explicit about 32-bit vs 64-bit instructions and use of the correct VS command prompt.

Be more explicit in Windows build instructions

---

.github/workflows/ci-aarchxx.yml
.github/workflows/ci-clang-format.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
.github/workflows/ci-x86.yml

Avoids installation errors due to stale data by running "apt-get
update" prior to every install.  Unfortunately this adds 30s to each
job, but it is unavoidable it seems on these GA CI VM's.
Fixes #4780

i#4780: Run apt-get update before every install

---

.github/workflows/ci-package.yml
.github/workflows/ci-x86.yml

The underlying issue behind the multilib apt problems has been
resolved so we no longer need the workaround.
Issue: #4780

i#4780 apt: Remove multilib workaround

---

.github/workflows/ci-docs.yml

The daily docs cronbuilds are steadily increasing the size of the
repo, due to timestamps in every single file changing every time.
Given that we rarely make docs changes that we want to make live
immediately, we reduce the cronbuild to coincide with the package
build, and rely on manually-triggered docs builds for anything else.
Issue: #4111

i#4111 web: Reduce docs cronbuilds to weekly

---

.github/workflows/ci-docs.yml

The dynamorio_docs repository has been deleted and we now only deploy
embedded docs to the dynamorio.github.io repository.
Issue: #4111

i#4111 web: Remove deployment to dynamorio_docs

---

api/docs/deployment.dox
api/docs/release.dox
api/docs/test_suite.dox

Adds a new section on Running Under QEMU.
Adds a documented option entry for -xarch_root.
Adds a release note on the new support.
Issue: #4719

i#4719 qemu: Add user docs on running under QEMU

---

suite/runsuite_wrapper.pl

The client.cbr4 test has been failing on master merges, but passing on
pull requests.  The failure does not reproduce locally.  We add it to
the ignore list here to keep the suite green until someone is able to
act on it.
Issue: #4792

i#4792 cbr4 failure: Add client.cbr4 to ignore list

---

clients/CMakeLists.txt
clients/drcachesim/CMakeLists.txt
clients/drcov/CMakeLists.txt

Adds a flag to arrange only one of drcov and drcachesim trying to copy
dynamorio.dll into the same directory, which can lead to failures with
bad timing.
Fixes #4668

i#4668: Fix build race on competing library copies

---

clients/CMakeLists.txt
clients/drcachesim/CMakeLists.txt
clients/drcov/CMakeLists.txt

Adds a new target at the clients/ level to copy dynamorio.dll into the
bin dir for use by both drcov and drcachesim, to avoid races between
the two.  The prior solution avoided dueling copies, but left a race
where the doc generation of one could be left without a copy in place.
Fixes #4668

i#4668 build race: Fix DR copy race via single target

---

core/heap.c
core/ir/disassemble_shared.c
core/ir/instr_shared.c
core/stats.c
core/unix/memquery_linux.c
core/vmareas.c
suite/tests/CMakeLists.txt
suite/tests/common/allasm_x86_64.asm
suite/tests/common/allasm_x86_64.expect

Fixes several problems with loglevel 5 and above:
+ Fixes a deadlock by avoiding an over-long LOG in a fragile memquery context.
+ Avoids an assert by avoiding an opcode query for a level 0 bundle.
+ Fixes a rank order violation by avoiding diagnostic module name
lookup if holding fcache_unit_areas->lock.
+ Fixes an infinite recursion by avoiding the same module lookup for the
loaded_module_areas vector.
+ Fixes a crash when thread_kstats is not yet allocated.
+ Fixes a memory leak at level 5.
+ Effectively disables vmm_dump_map as with 4K blocks it has enormous output now.
Adds a test of loglevel 19 that runs a pure-asm app to keep the time
and space down.  Marks it as part of the QEMU suite.
Fixes #4736

i#4736: Fix high-loglevel issues and add test

---

core/options.c
core/utils.c
core/utils.h
core/win32/module.c
make/configure.cmake.h

We no longer support linking dynamorio.dll with libc on Windows.
We remove the NOLIBC define and assume it is always set.
Issue: #4807

i#4807 rm defs: Remove NOBLIC

---

api/docs/bt.dox
api/docs/intro.dox
core/globals.h
core/ir/instrlist.h
ext/drwrap/drwrap.h

Adds doxygen comments to the instrlist_t typedef so we can add links
to the docs, although it is an opaque type.  Renames the underlying struct to better match the final name.
Also converts the regular comment on DRWRAP_CALLCONV_MASK to a doxygen
comment.
Issue: #4111

i#4111 web: Add instrlist_t entry and links

---

api/docs/CMake_doxyfile.cmake
api/docs/bt.dox
api/docs/deployment.dox
api/docs/intro.dox
api/docs/license.dox
api/docs/tool.gendox
core/lib/dr_app.h

Moves the License page to a top-level entry and renames the sections
for shorter menu entries.
Fixes other misc layout issues:
+ Removes the bt.dox samples TOC entry since that is now on another page
+ Adds missing start/stop API entries
+ Removes a duplicate Disassembly Tool list entry
Issue: #4111

i#4111 web: Move License to top-level

---

core/arch/interp.c
core/fragment.c
core/lib/globals_shared.h
core/lib/instrument.c
core/lib/instrument.h
core/lib/instrument_api.h
core/lib/statsx.h
core/link.c
core/monitor.c
core/monitor.h
core/options.c
make/configure.cmake.h

Removes CUSTOM_TRACES as part of removing CLIENT_INTERFACE and related
defines for interfaces that are always enabled.
Issue: #2971

i#2971 rm CI: Remove CUSTOM_TRACES define; it is always on.

---

core/dispatch.c
core/dynamo.c
core/fragment.c
core/fragment.h
core/globals.h
core/lib/instrument.c
core/lib/instrument_api.h
core/synch.c
core/unix/os.c
core/utils.h
core/win32/callback.c
core/win32/os.c
core/win32/os_private.h
make/configure.cmake.h

Removes the CLIENT_SIDELINE define as part of removing
CLIENT_INTERFACE and related defines for interfaces that are always
enabled.
Issue: #2971

i#2971 rm CI: Remove CLIENT_SIDELINE define; it is always on.

---

CMakeLists.txt
core/globals.h
core/lib/genapi.pl
make/configure.cmake.h

Removes the DYNAMORIO_IR_EXPORTS define as part of removing
CLIENT_INTERFACE and related defines for interfaces that are always
enabled.
Adds comments about removing {DR_}APP_EXPORTS in the future: #4819.
Issue: #2971, #4819
Fixes #2971

i#2971 rm CI: Remove DYNAMORIO_IR_EXPORTS; it is always on.

---

core/CMakeLists.txt
core/ir/aarch64/codec.py
core/ir/arm/opcode_api.h
core/ir/arm/table_encode.c
core/ir/dr_ir_opcodes.h
core/ir/instr.h
core/ir/opnd.h
core/ir/x86/decode_table.c
core/ir/x86/opcode_api.h
core/lib/genapi.pl
make/CMake_aarch64_gen_codec.cmake
tools/x86opnums.pl

Moves the small non-public parts of core/ir/*/opcode.h into instr.h
and opnd.h.
Cleans up core/ir/*/opcode.h and codec.py's generated content such
that these files are now just directly copied to the public include/
directory.
Renames opcode.h to opcode_api.h for all 3 arches to make it clear
they are part of the public interface.
Issue: #3092

i#3092 genapi: Rename and clean up opcode headers

---

.github/workflows/ci-clang-format.yml
.github/workflows/ci-package.yml
.github/workflows/ci-x86.yml

WIP: Try Ubuntu 20 for clang w/o the clang-9 env var;
Try Ubuntu 18 for x86 to see if toolchain is better w/o test failures
Issue: #4830

i#4830: Work around GA CI VM 32-bit and clang-format toolchain regressions

---

CMakeLists.txt
core/CMakeLists.txt

Adds a custom target to avoid AArch64 builds repeatedly copying the
opcode header and rebuilding affected targets.
Issue: #3092

i#3092 genapi: Avoid superfluous header copies

---

core/arch/emit_utils_shared.c
core/unix/signal.c

PR #3003 added handling of a signal interrupting the ibl hit path's jump, but the introduced
client.cleancallsig test could not test the ibl jump on AArchXX leading to the insertion of an
ASSERT_NOT_TESTED() for AARCHXX. Testing on a proprietary app with plain DR (debug build)
on AArch64 hit this case without problems. Thus, we can remove the ASSERT_NOT_TESTED() 
for AARCH64.
The code inserted in PR #4797 was triggered and tested for AARCH64 on a proprietary app so 
remove the ASSERT_NOT_TESTED() for AARCH64 from there as well.

Remove two (now tested) cases of ASSERT_NOT_TESTED for AARCH64

---

clients/drcachesim/tests/burst_aarch64_sys.cpp
core/unix/signal.c

Prevents a seg fault in the burst_aarch64_sys test that was caused by reading an unspecified
sigaction restorer in sig_has_restorer() in unix/signal.c. Does so by returning false early
in sig_has_restorer() for AArch64 when the SA_RESTORER flag is not set.
By preventing the seg fault, it also prevents the nested signal handling and consequently
the stack overflow in burst_aarch64_sys test when the -signal_stack_size is not specified.
Issue: #4425

i#4425: handle unspecified-by-the-app sigaction restorer for AArch64

---

clients/drcachesim/simulator/cache.cpp
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/simulator/caching_device.h
clients/drcachesim/simulator/tlb.cpp
clients/drcachesim/simulator/tlb.h
clients/drcachesim/tests/cores-1-levels-3-no-missfile.conf
clients/drcachesim/tests/simple-config-file.templatex
clients/drcachesim/tests/threads-with-config-file.templatex

Replaces drcachesim's loops over all ways with a hashtable lookup.
For larger cache hierarchies and caches with higher associativity this
increases performance by 15% in cpu-bound tests on offline traces,
when we use a large initial table size to avoid resizes which seem to
outweigh the gains.
The hashtable unfortunately results in a 15% slowdown on simple cache
hierarchies, due to the extra time in erase() and other maintenance
operations outweighing the smaller gains in lookup.  Thus, we make the
default to *not* use a hashtable and use the original linear walk,
providing a method to optionally enable the hashtable.  The cache
simulator enables the hashtables for any 3+-level cache hierarchy with
either coherence or many cores.
Adds coherence to some existing 3-level-hierarchy tests to …

i#1738 dr$sim perf: Improve tag lookup speed with a hashtable

---

core/ir/aarch64/codec.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

FCVTZU was overlooked in the original AArch64 port.
This is the first in a series of patches to implement missing instructions in the codec.
This patch is related to issue 2626:
https://github.com/DynamoRIO/dynamorio/issues/2626

Add support for FCVTZU to DynamoRIO codec

---

clients/drcachesim/tests/filter-no-d.templatex
clients/drcachesim/tests/filter-no-i.templatex
clients/drcachesim/tests/filter-simple.templatex
clients/drcachesim/tests/offline-filter-no-i.templatex
clients/drcachesim/tests/offline-filter.templatex
suite/tests/CMakeLists.txt

Modifies miss rate regex to allow matching rates less than 10%, by making the first digit optional.
Due to this issue, `code_api|tool.drcachesim.filter-no-i` failed in `vs2017-32` at github.com/DynamoRIO/dynamorio/actions/runs/750037355.

Fix flaky regex that doesn't match smaller miss rates

---

api/docs/rseq.dox

Adds a direct link to the rseq limitations list from the rseq design
doc, which we can easily do now that everything is merged in one
place.
Issue: #4111

i#4111 web: Add direct link to rseq limitations

---

core/vmareas.c

Fixes a rank order violation at -loglevel 5 with rseq.
It is the same vmarea diagnostic issue seen with other vmarea lists.
It does not seem worth the complexity of adding rseq to the existing
high-loglevel test or adding a new one; tested manually on the
linux.rseq test.
Issue: #4736, #4316

i#4736 loglevel: Fix high-loglevel rseq rank order

---

suite/tests/linux/rseq.c
suite/tests/linux/rseq_disable.c

Ports the linux.rseq test and its extensive inline assembly to
AArch64.  We use compiler-acquired C variable addresses prior to the
assembly sequences for simplicity.  This should be fine as there are
plenty of GPR's and DR handles inputs.
Tested natively and with forthcoming DR rseq mangling changes;
separated to keep diffs smaller.  These tests will be enabled in the
PR that adds DR handling.
Issue: #4316

i#4316 a64 rseq: Port linux.rseq test to AArch64

---

api/docs/bt.dox
core/arch/aarch64/emit_utils.c
core/arch/aarchxx/mangle.c
core/arch/arch.h
core/arch/mangle_shared.c
core/ir/aarchxx/ir_utils.c
core/ir/instr.h
core/translate.c
core/unix/rseq_linux.c
suite/tests/CMakeLists.txt
suite/tests/linux/rseq.c

Ports rseq mangling to AArch64.  This requires implementing
patch_mov_immed_arch() (done by leveraging existing raw encoding code
from exit stub support) and spilling extra scratch registers in
multiple places.
Expands translation support to cover the new mangling.  This includes
adding proper recognition of an mcontext base load, which was
incorrectly identified as an indirect branch target load on x86.
Ports the heuristic for finding the app's rseq TLS offset on attach
(when we did not see an rseq syscall) for AArch64 to look forward
instead of backward as on x86 where negative segment offsets are used.
Enables the rseq tests for AArch64.
Updates the rseq docs to state that AArch64 is supported.
One final step is to support stores with writeback, which are seen in
real rseq sequences. …

i#4316 a64 rseq: Port rseq mangling to AArch64

---

api/docs/bt.dox
core/arch/mangle_shared.c
suite/tests/CMakeLists.txt
suite/tests/linux/rseq.c

Adds nop-ing of writeback stores inside rseq regions by replacing them
with adds to preserve the GPR changes but throw away the memory changes.
Updates the documentation.
Adds a test case.
Fixes #4316

i#4316 a64 rseq: Nop writeback stores

---

api/docs/rseq.dox
core/arch/mangle_shared.c
core/optionsx.h

Removes the option -rseq_assume_call and its code in favor of the
more-general native-copy approach, which has been the default for a
while now and has not shown any stability issues.
Issue: #2350

i#2350 rseq: Remove -rseq_assume_call and code

---

core/ir/aarch64/codec.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

i#4848 AArch64 GPR Decode: Add FCVT instructions (#4855)
This implements:
- Scalar floating-point
- Vector floating-point
- Scalar floating-point to GPR
for FCVTAS, FCVTNS, FCVTPS, FCVTPU, and FCVTZS.
Issue: #4848, #2626

i#4848 AArch64 Decoder: Add FCVT instructions

---

core/ir/x86/instr_create_api.h
suite/tests/api/ir_x86.c

XINST_CREATE_add leaves the scale as 0 even when an index register is
present, which does not encode.  We fix that here, along with fixing
the same bug in XINST_CREATE_add_2src.
A test case is added.
Fixes #4861

i#4861: Fix x86 encode bug in 2-reg XINST_CREATE_add

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch adds `scale` and `immh:immb` bitfeld handling
for the `#fbits` value in the codec using the `FCVTZU`
instruction as a use-case.
Issues: #2626, #4848

i#2626 Add #fbits fixed-point handling to AArch64 codec

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/common/trace_entry.h
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/tests/filter-asm.templatex
clients/drcachesim/tests/filter-no-d.templatex
clients/drcachesim/tests/filter-no-i.templatex
clients/drcachesim/tests/filter-simple.templatex
clients/drcachesim/tests/trace_invariants.cpp
clients/drcachesim/tests/trace_invariants.h
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Adds tracking of the dynamic (pre-filtered) instruction count for each thread.
Stores the count in a marker at thread exit (storing prior to each miss entry
might be useful but in experiments it adds too much overhead to include
without a clear mandate and possibly under an off-by-default runtime option).
Adds a check to the filter tests confirming that the instruction count
marker is present at thread exit for filtered traces.  This is done by
invoked test_mode for these traces.  To simplify testing for online
and offline, the trace type marker is added to online traces.
Adds a new tool.drcachesim.filter-asm test which ensures the instr
count is the precise count expected for that fully-deterministic
tiny static binary.
A larger-than-static-asm application was manually tested, confirming …

i#4857: Add instr count to drmemtrace filtered traces

---

core/ir/aarch64/codec.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

Add handling of:
- scalar, integer
- vector, integer
- scalar, fixed-point
- vector, fixed-point
for instructions UCVTF and SCVTF
Issue: #2626, #4848

i#4848: AArch64 GPR Decode: Add UCVTF and SCVTF

---

core/arch/mangle_shared.c

Fixes stores to dcontext_t.whereami on AArch64 where a 64-bit register
is written to a 32-bit field, overflowing it and clobbering the
adjacent signals_pending field.  This causes signals to not be
delivered and fragments that were unlinked to not be relinked, raising
an assert.
Tested on the proprietary application that reproduced the signal
assert in every run: it is gone with this fix.
Fixes #4878

i#4878: Fix whereami overflow corruption of signal field

---

suite/tests/api/dis-a64.txt

Ordering dis-a64.txt alphabetically by instruction name will make it
much easier to navigate and detect missing or erroneous tests.
Issue: #2626, #4847, #4848, #4849

i#2626 AArch64 v8.0 Decode: Order dis-a64.txt alphabetically

---

core/unix/module.h
core/unix/os.c

Prevents triggering an ASSERT_CURIOSITY for duplicated elf headers for debug DR builds 
on AArch64 systems. It is possible for small modules (less than 1 page of disk space) to 
have multiple LOAD data segments. Since these segments are mapped from a single disk 
page they will all have an elf header. The triggered assertion assumed that there can only 
be one data segment. Extends this assertion check to accommodate for more than one 
data segments.
Fixes: #4256

i#4256: prevent triggered assertion for duplicated elf_headers on AArch64

---

api/docs/release.dox
core/ir/instr_api.h
core/ir/instr_shared.c
suite/tests/api/ir_x86.c

Adds instr_zeroes_zmmh(), which returns true if the instruction clears the upper bits of a ZMM register with zeros.
Updates instr_zeroes_ymmh() to take into account EVEX instructions.
Tests for the above are also included.
Issue: #1312

i#1312: Adds instr_zeroes_zmmh()

---

core/dispatch.c

Adds a pending-signal check to avoid attempting to run a syscall for a
signal arriving in the cache, avoiding running pre-syscall handling
only to abort and have complications with undoing or duplicating
actions.
For a signal arriving in DR while executing a syscall, changes DR to
go ahead and do the syscall for all non-ignorable syscalls, again
avoiding complications with undoing or duplicating pre-syscall action.
Previously, this was only done for sigreturn or clone syscalls.
Non-ignorable syscalls generally do not block, so this should not
impact signal delivery delays.
Moves the pending-signal check to be the first thing checked for the
exit reason, for proper exit attribution.
Avoids the IBT add code for a pending-signal exit.
Tested on the large proprietary app where the wrong exit …

i#4884: Check signal exit before syscall, etc. reasons

---

api/docs/release.dox
core/ir/instr_api.h
core/ir/instr_shared.c
suite/tests/client-interface/drx-scattergather.c
suite/tests/client-interface/drx-scattergather.templatex

PR #3960 added a call to instr_set_label_callback() to set it to NULL
from instr_clone(), but if the callback is non-NULL an assert fires in
that case.  This only normally happens with emulation labels that turn
into traces, which happens to not occur in our very few tests of
emulation labels (#3173 covers adding more tests).
We fix that by adding instr_clear_label_callback() here and using that
from instr_clone(), since these callbacks are a little different from
other values and it feels best to not clear them using the set
routine.
A test is added by putting a loop around a scatter-gather expansion,
triggering trace creation.  I confirmed that the assert does fire
without this fix with the loop in place.
Fixes #3962

i#3962 label cb: Add instr_clear_label_callback()

---

core/unix/signal.c

Avoids redundant stack allocations during signal handling for copies of sigcontext_t
by hiding them within callsites.
Issue: #4425

i#4425: save signal stack space with deeper call stack

---

core/unix/os.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/large_options.dll.c

Fixes a regression from the #1660 fix which changes the
executable_path buffer after most initialization, yet fails to update
the executable_basename pointer into that same buffer.
Adds a test by changing the linux.execve64 test to use a relative path
for the sub-path, and having that client check for slashes in
dr_get_application_name().  Confirmed the new test fails without this fix.
Issue: #1660, #4892
Fixes #4892

i#4892: Update basename pointer when path buffer changes

---

core/unix/signal_linux_x86.c

Adds a comment that reports a relatively recent security vulnerability that forces eager
saving and restoration of FPU state for every task/context switch. These changes might
make the execution of an xmm-related inst in `signal_arch_init` unnecessary. 
Yet, it does not remove this inst execution, given that older kernels will not have this fix 
and since eager FPU state save/restore mitigates transparency concerns (this instruction 
execution essentially will have minimum (if any) visible effect on recent kernels).

Add comment about CVE related to FPU state on x86

---

ext/drx/drx.c

Adds a check that slot2 on AArchXX is set properly, to mirror the
existing first slot check for all platforms.

Add drx_insert_counter_update() slot2 check

---

clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/tracer.cpp

Adds recording of all app-valued registers at the skip point of
drmemtrace's instrumentation skips for filtered or global-maximum
offline trace options.  These registers are then restored prior to the
skip target, to ensure scratch register parity on all paths.
Tested on the precise basic block that triggered the bug when combined
with drreg limitations on which scratch registers to use.  Considered
trying to create a regression test out of this but there are many
complexities that make it non-trivial.
Fixes #4899

i#4899: Fix drmemtrace drreg control flow discrepancies

---

clients/drcachesim/tests/offline-delay-func.templatex
clients/drcachesim/tracer/func_trace.cpp
clients/drcachesim/tracer/func_trace.h
clients/drcachesim/tracer/tracer.cpp
ext/drwrap/drwrap.h
suite/tests/CMakeLists.txt

In drcachesim, the -trace_after_instrs delayed-tracing feature fails
to delay function tracing.  We fix that here by leaving the function
wrapping in place from the start and simply ignoring i/o until the
trigger point.
Delaying the function wrapping is complicated by being unable to hold
locks during the whole module load event.  Locks are needed to delay
that event, as we need to enable it and then iterate existing modules.
This is why we instead opt to not delay function wrapping.
Adds documentation to drwrap_wrap* that event-blocking locks cannot be
held.
Adds a new test that delays all tracing and ensures there are zero
function markers.
Fixes #4893

i#4893: Delay function tracing with address tracing

---

clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/allasm_repstr.asm
clients/drcachesim/tests/allasm_scattergather.asm
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/offline-allasm-scattergather-basic-counts.templatex
clients/drcachesim/tracer/instru.cpp
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/tracer.cpp
ext/drutil/drutil.c
ext/drutil/drutil.h
suite/tests/CMakeLists.txt

Fixes issues in drcachesim and raw2trace because of which some
instructions and memrefs in the scatter/gather expansion were
not being instrumented. This led to lower than expected
basic_counts for data loads and stores.
In the scatter/gather expansion, all instrs have the same app
pc (this is unlike rep str expansion where the stringop has
the original app pc, and others have a fake one). So we need
to continue instrumenting even if we see an instr with app pc
same as the last one we saw.
Modifies raw2trace to properly detect scatter/gather memrefs:
when we see a scatter/gather instr, we keep reading entries
until we encounter a non-memref entry. The alternative to this
was to add a pc entry for each mov instr (to fulfil raw2trace's
requirement of always having a preceding pc entry for …

i#2985 scatter-gather: Fix drcachesim and raw2trace issues.

---

suite/tests/api/dis-a64.txt

Add a wider and more extensive range of decoder tests for ST1.
Issue: #4847, #2626

i#4847 AArch64 v8.0 memory decode: Add more ST1 decode tests

---

api/docs/release.dox
ext/drmgr/drmgr.c
ext/drmgr/drmgr.h
ext/drutil/drutil.c
ext/drx/drx.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drutil-test.dll.c
suite/tests/client-interface/emulation_api_simple.dll.c

Adds a convenience routine drmgr_in_emulation_region() and flag
DR_EMULATE_FIRST_INSTR to make it easier to query emulation markers.
Adds a new flag DR_EMULATE_INSTR_ONLY for expansions where the
sequence being executed should be examined for data references
and only instruction observation should look at the original
instruction.  Sets the flag for drutil_expand_rep_string*() and
drx_expand_scatter_gather().
Clarifies that the flags field added in PR #4877 is a source
compatibility break if source code was not zeroing the full struct.
Ports the emulation_api_simple test to x86_64.  Augments the test to
perform a partial DR_EMULATE_INSTR_ONLY emulation as well for both
platforms.  Adds checks for various invariants in the test.
Future work will add emulation awareness to tracing clients. …

i#4865: Add emulation instr-only and convenience features

---

core/ir/aarch64/instr_create_api.h
core/ir/instr_api.h
core/ir/instr_shared.c
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

Add encoding and decoding IR tests for:
- adrp, ldpsw, ld2, ld3, ld4, ld2r, ld3r, ld4r
Issue #4847, #2626

i#4847 AArch64 v8.0 Memory decode: Add Encoding and Decoding tests

---

ext/drreg/drreg.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drreg-test-shared.h
suite/tests/client-interface/drreg-test.c
suite/tests/client-interface/drreg-test.dll.c

Moves label that contains slot id for register spill/restore instrs to after the instr instead of
before. The free spill slot selection logic that makes use of these labels scans instrs *after*
the given one, so we may miss the label if it is placed before.
Fixes order of app val spill and tool val restore instrs after an instr that reads and writes a
spilled reg. This was to take into account the label which is now after the tool restore instr.
Adds test to verify restoration of reg that was reserved in multiple phases on a fault, for
X86 and AARCHXX.
Also adds AARCHXX variant of the multi-phase slot conflict test, and extends it to also
check proper restoration of app val (under normal operation, as opposed to under a
fault which is done by the above test). The existing test only …

i#3823 multi-phase drreg: Delay slot id label

---

suite/runsuite_wrapper.pl
suite/tests/CMakeLists.txt

The following tests fail on the new Jenkins CI host, an Ampere Altra:
code_api|tool.drcachesim.phys            i4922
code_api|tool.drcacheoff.rseq            i4924
code_api|api.rseq                        i4923
code_api|tool.drcachesim.threads         i4928
code_api|tool.drcachesim.TLB-threads     i4928
This patch adds them to the 'ignore' list for now.
Issues have been raised to track fixes:
Issue: #2417

i#2417 Suppress regressions caused by CI migration

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Adds the following instructions to the codec with decoder tests
- FCVTAU, FCVTL, FCVTL2, FCVTMS, FCVTN, FCVTN2
Issue: #4848, #2626

i#4848 AArch64 v8.0 GPR decode: Add FCVT- to codec

---

ext/drmgr/drmgr.c

The drmgr_bb_cb_add() and drmgr_bb_cb_remove() functions had become
unwieldy over time, with very long lists of parameters and complex
conditionals.  This makes it difficult to add new callbacks.  Here we
refactor them to take in helpers to set key fields while sharing all
of the other code.
A new has_pair field is also added.  This fixes a bug where
drmgr_register_opcode_instrumentation_event() incorrectly increased
the pair count.
Issue: #4865

i#4865 emul: Refactor drmgr callback list management

---

suite/tests/CMakeLists.txt

Fixes a bug in the tool.drcacheoff.rseq test command line where the
glob for the output directory was run up against the -test_mode
parameter.  The bug was introduced in PR #4929.
Issue: #2417

i#2417 suite: Fix regression from bad tool.drcacheoff.rseq cmdline

---

api/docs/intro.dox
api/docs/release.dox
api/samples/memtrace_simple.c
ext/drmgr/drmgr.c
ext/drmgr/drmgr.dox
ext/drmgr/drmgr.h
ext/drutil/drutil.c
ext/drutil/drutil.h
ext/drx/drx.h
make/DynamoRIOConfig.cmake.in
suite/tests/CMakeLists.txt
suite/tests/client-interface/emulation_api_simple.dll.c
suite/tests/samples/memtrace_simple_repstr.templatex

Adds a new emulation instrumentation interface with simpler
convenience routines for identifying the original application
instruction fetch and operands.
Uses the new interface in memtrace_simple.  Separate commits will
update memval_simple, memtrace_x86, and drmemtrace.
Adds an x86 test that runs the memtrace_simple sample on the
allasm_repstr app and ensures we see 2-byte "rep movs" instructions
instead of the 1-byte "movs" that the existing sample client records
due to not being emulation-aware.  Adds a -log_to_stderr flag to the
sample to make the test simpler and not have to deal with log files.
Adding new events is separated into #4947 which we may attempt in the
future.  Removing rep string non-fetched instructions is #4948. …

i#4865 emulate: Add new emulation instrumentation API

---

ext/drreg/drreg.c
ext/drreg/drreg.dox
ext/drreg/drreg.h

Modifies free spill slot selection logic to use is_our_spill_or_restore instead
of the labels with spill slot use information added for this purpose. We do not
need the extra information in the latter and can simply use the former routine.
Removes the extra spill slot use metadata added in form of labels from the
instrlist.
Also adds documentation about possibility of DR slot conflicts if DR APIs are
mixed with drreg ones.
Issue: #3823

i#3823 multi-phase drreg: Remove slot id labels.

---

api/samples/memtrace_x86.c
api/samples/memval_simple.c

Uses the new emulation instrumentation interface in the memval_simple
and memtrace_x86 samples.
Here's the output of memval_simple before:
$ bin64/drrun -c api/bin/libmemval_simple.so -- suite/tests/bin/allasm_repstr && cat `ls -1td api/bin/*.log|head -1`
0x402000: movs  1 41
0x402001: movs  1 64
0x402002: movs  1 69
0x402003: movs  1 6f
0x402004: movs  1 73
And after:
0x402000: rep movs  1 41
0x402001: rep movs  1 64
0x402002: rep movs  1 69
0x402003: rep movs  1 6f
0x402004: rep movs  1 73
Issue: #4865

i#4865 emulate: Use new API in memval_simple + memtrace_x86

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Adds the following AArch64 v8.0 instructions to the codec:
- CLZ (vector)
- NEG (vector)
- NEG (vector, scalar)
- ORR (vector, immediate)
- MOV (vector, element) (INS alias)
- MOV (vector, from general) (INS alias)
- MOV (vector, scalar)
- MOV (vector, to general) (UMOV alias)
Issue: #4848, #2626

i#4848: AArch64 v8.0 GPR Decode: CLZ, NEG, ORR and MOV

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- ADDV
- MLA (by element)
- MLS (by element)
Issue: #2626

i2626: AArch64 v8.0 decode: Add ADDV, MLA, MLS

---

clients/drcachesim/common/options.cpp
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/tests/trace_invariants.cpp
clients/drcachesim/tests/trace_invariants.h
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/tracer.cpp

Adds the instruction count to the buffer header for drcachesim
filtered traces, instead of just at thread exit, to aid in correlating
filtered and unfiltered traces.
Updates the documentation and the trace_invariants test.
Augments the view tool to print out these markers.
Further verified manually on a larger trace with the view tool:
<marker: filetype 65>
<marker: cache line size 64>
<marker: timestamp 13268850698443940>
<marker: tid 2539348 on core 1>
<marker: instruction count 33326>
0x00007f6f64314090  48 89 e7             mov    %rsp, %rdi
0x00007f6f6432dce0  b8 0c 00 00 00       mov    $0x0000000c, %eax
<marker: timestamp 13268850698727951>
<marker: tid 2539348 on core 1>
<marker: instruction count 40130>
0x00007f6f6432c906  c7 44 24 3c 00 00 00 movl   $0x00000000, 0x3c(%rsp)
<...> …

i#4857 icount: Include instr count in filtered trace unit header

---

api/samples/memtrace_simple.c
clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/allasm_repstr.asm
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tracer/instru.cpp
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/samples/memtrace_simple_repstr.templatex

Uses the new emulation instrumentation interface in drcachesim's
drmemtrace tracer.  Removes all of the special-case code for both
online and offline tracing that is no longer needed now that a general
emulation approach is used for rep string and scatter expansion.
Confirmed that the allasm_repstr and allasm_scattergather applications
have the exact same behavior after the changes.
Fixes #4865

i#4865 emulate: Use new API in drmemtrace

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

FCSEL Hd, Hn, Hm, cond 
FCSEL Sd, Sn, Sm, cond 
FCSEL Dd, Dn, Dm, cond 
FMAXV Vd, Vn.T
FMINV Vd, Vn.T
FCMP Hn, Hm
FCMP Hn, #0.0
FCMP Sn, Sm
FCMP Sn, #0.0
FCMP Dn, Dm
FCMP Dn, #0.0
FCCMP Hn, Hm, #nzcv, cond
FCCMP Sn, Sm, #nzcv, cond
FCCMP Dn, Dm, #nzcv, cond
FCCMPE Hn, Hm, #nzcv, cond
FCCMPE Sn, Sm, #nzcv, cond
FCCMPE Dn, Dm, #nzcv, cond
Issue: #2626

i#2626: AArch64 decode: Add FCSEL FMAXV FMINV FCMP FCCMP FCCMPE

---

core/ir/aarch64/codec.c

Change imm5 bitsize from 6 to 5
Issue: #2626

i#2626 AArch64 Decode: Fix imm5 decode bits

---

api/docs/CMake_rundoxygen.cmake

Adds a regex command for docs to find SVG data in /images.
Fixes: #4965

i#4965: Add SVG data path modification.

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Add the following instructions to the codec:
- ABS (scalar, vector)
- ADDP (scalar)
- SMAXV
- SMINV
- ZIP1
- ZIP2
Issue #2626

i#2626 AArch64 Decode: Missing misc SIMD instructions, part 1

---

api/docs/building.dox

Apparently Doxygen's markdown parser cannot handle a single backtic
inside a triple-backtic quote block.  This was causing a messed-up
sequence of what is quoted and what is not and a missed final section
on the build-from-source web page.  We fix it here by switching to $()
instead of backtics in a bash function; we also add a named link to
the DrGUI build directions since Dr. Memory links to them.

Fix quoting mishap in build-from-source docs

---

api/docs/release.dox
core/arch/mangle_shared.c
core/lib/dr_events.h
core/unix/os_exports.h
core/unix/rseq_linux.c
suite/tests/linux/rseq.c

Adds source context information to the kernel xfer event for rseq
aborts, which was previously missing.  To provide the interrupted rseq
abort PC as the PC of the final committing store, adds logic inside DR
to record that PC when it is discovered during block creation.
Updates the rseq test to check the new information.
Issue: #4274

i#4274 kernel pc: Provide rseq abort interrupted pc

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Adds the following instructions to the codec
- SQRDMULH (by element scalar, by element vector, vector scalar)
- SQRDMLAH (by element scalar, by element vector, vector scalar)
- SQRDMULH (by element scalar, by element vector, vector scalar)
- SQSHL    (immediate scalar, register scalar, register vector)
- SQXTN    (scalar, vector)
- SQXTN2   (vector)
- SQXTUN   (scalar, vector)
- SQXTUN2  (vector)
- UQXTN    (scalar, vector)
- UQXTN2   (vector)
Issue: #2626

i#2626 AArch64 Decode: Add Saturating SIMD instructions

---

clients/drcachesim/tests/trace_invariants.cpp
clients/drcachesim/tests/trace_invariants.h
suite/tests/CMakeLists.txt

Improves the robustness of the trace_invariants test by shifting the
various tracked state to be per-thread and per-nested-signal, avoiding
incorrect results from thread interleavings or nested signals.
This presumably explains past flakiness like #4575.
Fixes #4575

i#4575: Track threads and nesting in trace_invariants test

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- SADALP
- SADDLP
- SMLAL, SMLAL2
- SXTL, SXTL2 (SSHLL alias)
Issue: #2626

i#2626: AArch64 decode: Add signed arithmetic SIMD instructions

---

ext/drreg/drreg.c

Rearranges some code to obviate the need for the *_now variables. Also separates out the common instr-is-meta check to an outer if-condition.
This is in preparation for sending the i#4963 fix for review. Split out this harmless refactor to make review easier for that fix.
Issue: #4963

Simplify drreg state restoration code.

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/reader/reader.cpp
clients/drcachesim/tests/offline-delay-func.templatex
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp

The version number in a drmemtrace trace is currently hidden in a
header that the reader hides from analysis tools.  Here we add a new
marker type that exports the version number so that analysis tools can
handle legacy traces.
Adds version awareness to the view tool.
Tested by manually running the view tool:
$ bin64/drrun -t drcachesim -verbose 3 -- suite/tests/bin/allasm_repstr
::4152878.4152878:: marker type 12 value 2
::4152878.4152878:: marker type 9 value 64
::4152878.4152878:: marker type 10 value 64
...
$ bin64/drrun -t drcachesim -offline -- suite/tests/bin/allasm_repstr
$ bin64/drrun -t drcachesim -simulator_type view -indir drmemtrace.allasm_repstr.*.dir
<marker: version 2>
<marker: filetype 40>
<marker: cache line size 64>
<marker: timestamp 13269494545173426>
<marker: tid …

i#4274 kernel pc: Export version number in final trace

---

clients/drcachesim/drcachesim.dox.in
clients/drcachesim/tests/offline-view.templatex
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

Augments the drmemtrace view tool to include loads and stores.
Adds a thread id prefix, handling the two initial no-id entries.
Adds a divider on thread switches.
Updates the documentation's example output.
This makes the tool now provide a complete view of a trace.
Fixes #4984

i#4984: Add loads, stores, and tid prefix to view tool

---

clients/drcachesim/tests/trace_invariants.cpp

Fixes a regression from the trace invariant test refactoring in PR #4974
where allowing a branch before a thread switch when a signal
arrives at the branch was not properly checked.
Tested in an Ubuntu 16.04 VM where the failure reproduced easily
before.
Fixes #4982

i#4982: Fix trace invariant assert

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- sha1c
- sha1h
- sha1m
- sha1p
- sha1su0
- sha1su1
- sha256h
- sha256h2
- sha256su0
- sha256su1
Issue: #2626

i#2626: AArch64 v8.0 decode: Add SHA- instructions to codec

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- AESD
- AESE
- AESIMC
- AESMC
Issue: #2626

i#2626: AArch64 v8.0 decode: Add AES instructions to codec

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- CNT
- TRN1, TRN2
- UXTL, UXTL2 (USHLL alias)
- UZP, UZP2
- XTN, XTN2
Issue: #2626

i#2626: AArch64 v8.0 Decode: Add misc SIMD instructions

---

clients/drcachesim/tools/view.cpp

Moves the TID prefix outside of the cached disassembly to avoid a
stale prefix in drcachesim's view tool.
Tested manually:
```
$ bin64/drrun -t drcachesim -offline -- suite/tests/bin/drmemtrace.signal_invariants
$ bin64/drrun -t drcachesim -indir drmemtrace.drm*[0-9]*.dir -simulator_type view 2>&1 | less
```
Before:
```
T480221   0x00007ff86d0c4648  48 89 94 24 50 02 00 mov    %rdx, 0x00000250(%rsp)
T480218                       00
T480221     write 8 byte(s) @ 0x7ff86c96fd50
T480221   0x00007ff86d0c4650  48 89 94 24 58 02 00 mov    %rdx, 0x00000258(%rsp)
T480218                       00
T480221     write 8 byte(s) @ 0x7ff86c96fd58 …
```

i#4984 view tool: Fix stale prefix on 2-line-disasm bug

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Adds FCVTMU FCVTNU SYSL and CMLT to the codec.
Issue: #4848, #2626

i#4848: AArch64 v8.2 Decode: FCVTMU FCVTNU SYSL CMLT

---

suite/runsuite_wrapper.pl

Adds nativeexec tests to ignore list for x86-64. We've been seeing a lot of red
on CI due to failures on different options for these tests.
Also ignores common.fib for one combination of options on vs2017-32.
Also ignores tool.drcachesim.threads-with-config-file failures on Arch64.
Issue: #5010, #1807, #4954

i#1807: ignore various flaky test failures

---

core/unix/signal.c
core/unix/signal_linux.c
core/unix/signal_private.h
suite/tests/linux/signest.c
suite/tests/linux/signest.expect

Fixes a bug where DR delivers a signal while an app is inside its
signal handler for that same signal and has blocked such self-nesting.
The fix is to undo some of the sigsuspend-handling changes that cause
this regression by moving the sigsuspend state restore to actual
delivery rather than at pending signal time.
Improves the linux.signest test to reproduce the original bug and
verify the fix.  Also adds a test case to ensure that signals are
nested when not blocked.
Fixes #4998

i#4998: Fix incorrectly nested signals

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- CMLE
- FCMLE
- FCMPE
- FCVTXN
- FCVTXN2
Issue: #2626

i#2626: AArch64 v8.2 Decode: Add missing instructions, part 1

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- FMAXNMV
- FMINNMV
- FRECPE
- FRECPX
- FRSQRTE
- RSHRN, RSHRN2
- SADDLV
- SQABS
Issue: #2626

i#2626: AArch64 v8.2 Decode: Add missing instructions, part 2

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- SQNEG
- SQSHRN, SQSHRN2
- SQRSHRUN, SQRSHRUN2
- SQSHLU
- SQSHRUN, SQSHRUN2
- SRI
Issue: #2626

i#2626: AArch64 v8.2 decode: Add missing instructions, part 3

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

- SUQADD
- TBX
- UQRSHRN, UQRSHRN2
- URECPE
- URSRA
- USQADD
Issue: #2626

i#2626: AArch64 v8.2 Decode: Add missing instructions, part 4

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Adds the following instructions to the codec
- DCPS1
- DCPS2
- DCPS3
- DRPS
- ERET
Issue: #2626

i#2626: AArch64 v8.0 Decode: Add missing instructions, part 5

---

core/ir/aarch64/codec.c

Fixes a regression from PR #4966 and PR #5012 where FCSEL and FC*MP*
opcodes were added to the decoder but the flag reading/writing code
was not updated for them, meaning they no longer went into the OP_xx
workaround, resulting in incorrect aflags attributes and resulting
instrumentation bugs.
Tested on the large application where app crashes were first seen.
It's not clear how to easily add a regression test for this kind of
thing for all opcodes.
Fixes #5023

i#5023: Mark FCSEL, FC*MP* as reading/writing aflags

---

clients/drcachesim/tracer/tracer.cpp
core/ir/aarch64/instr_create_api.h
ext/drx/drx.c
suite/tests/client-interface/drx-test.dll.c

Switches the instruction counting inlined code for AArch64
drmemtrace's delayed-by-instruction-count feature to count down and
use TBZ, avoiding use of the arithmetic flags.
Adds INSTR_CREATE_ support for TBZ and TBNZ.
Fixes missing support for subtracting in drx_insert_counter_update()
for AArch64 (fatal encoder errors are raised without this).
Adds a drx test for subtracting.
Issue: #5026

i#5026 icount perf: Avoid flags for arm drmemtrace

---

clients/drcachesim/common/options.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

For drmemtrace -trace_after_instrs, if the threshold is large (>10M),
we use per-thread counters and only check the global value every 10K
instructions in each thread.  The approximate result is fine for these
use cases.
Tested on the original app where the global counter contention results
in a 20x slowdown over plain DR.  The new scheme has a 14% slowdown
over plain DR on this app, a massive speedup.
Fixes #5026

i#5026 icount perf: Use per-thread counters

---

clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/tracer.cpp

Adds a new drmemtrace mechanism to set a frozen timestamp for all
future entries, to avoid huge time gaps when -max_global_trace_refs is
reached but existing thread buffers and exits are not emitted until
much later when the app exits.
Adding a small regression test seems difficult without flakiness as
this involved real-time gaps.  Tested manually:
Pre-fix we see a 2s gap before the thread exit:
$ ninja && ctest -V -R max-global
$ bin64/drrun -t drcachesim -simulator_type view -indir suite/tests/tool.drcacheoff.max-global*.dir 2>&1 | grep timestamp
T3427537 <marker: timestamp 13271354817417504>
T3427537 <marker: timestamp 13271354817418955>
T3427537 <marker: timestamp 13271354817624561>
T3427537 <marker: timestamp 13271354817657186>
T3427537 <marker: timestamp 13271354817659466>
T3427537 …

i#5021: Set frozen timestamp at drmemtrace max size

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.py
core/ir/aarch64/codec.txt

This patch adds a new field to codec.txt to make developers
explicitly specify whether an instruction touches the condition
code register.
For v8.0:
```
Read only      Write only      Read and write
adc            adds            adcs
bcond          ands            ccmn
csel           bics            ccmp
csinc          fccmp           sbcs
csinv          fccmpe
csneg          fcmp
fcsel          fcmpe
sbc            subs
mrs            msr
```
Issues: #5023, #5025

i#5023: AArch64 decode: generate condition flags register r/w marking

---

clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/cache_simulator.h
clients/drcachesim/simulator/cache_stats.cpp
clients/drcachesim/simulator/caching_device_stats.cpp
clients/drcachesim/simulator/caching_device_stats.h
clients/drcachesim/tests/drcachesim_unit_tests.cpp

This patch contains implementation of the API for accessing separate
metrics gathered during the simulation.
Functions for accessing metrics were added for all caches in the
default configuration: L1I, L1D and LL. Also additional functions
for getting configuration options of the cache_simulator_t.
Issue: #3068

i#3068: API for accessing cache model metrics

---

suite/tests/api/drdecode_aarch64.c

This patch fixes an intermittent issue when the CI tests are run on AArch64 V8.0 machines. Depending on the compiler used to build the tests, SIGILLs or SEGFAULTS are triggered when generated code is run before the generated code is flushed from the cache. 
This change adds an explicit cache flush in the test that has been exhibiting this flaky behaviour.
Fixes #5033

i5033: Fix intermittent crash in api.drdecode aarch64 test

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

```
CMEQ <V><d>, <V><n>, <V><m>
FCMEQ <Vd>.<T>, <Vn>.<T>, #0.0
FCMEQ <V><d>, <V><n>, #0.0
FCMGE <Vd>.<T>, <Vn>.<T>, #0.0
FCMGE <V><d>, <V><n>, #0.0
FCMGT <Vd>.<T>, <Vn>.<T>, #0.0
FCMGT <V><d>, <V><n>, #0.0
```
Issue: #2626

i#2626: AArch64 v8.0 decode: Add CMEQ FCMEQ FCMGE FCMGT

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`FRINTA <Vd>.<T>, <Vn>.<T>`
`FRINTM <Vd>.<T>, <Vn>.<T>`
`FRINTP <Vd>.<T>, <Vn>.<T>`
Issue: #2626

i#2626: AArch64 v8.0 decode: Add FRINTA, FRINTM, FRINTP

---

suite/runsuite_wrapper.pl

This test always fails on certain types of aarch64 hardware.

i#2417: Add drcachesim.coherence to the aarch64 flaky list

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Add the instructions
`FMOV <Wd>, <Sn>`
`FMOV <Xd>, <Dn>`
`FRECPE <Vd>.<T>, <Vn>.<T>`
`FSQRT <Vd>.<T>, <Vn>.<T>`
Issue: #2626

i#2626 aarch64 decode: add fmov, fsqrt, frecpe

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

In addition to fixing broken indexed vector instructions,
this patch also adds:
```
FMLS <Vd>.<T>, <Vn>.<T>, <Vm>.<Ts>[<index>]
FMUL <V><d>, <V><n>, <Vm>.<Ts>[<index>]
FMUL <Vd>.<T>, <Vn>.<T>, <Vm>.<Ts>[<index>]
```
Issue: #2626

i#2626: AArch64 v8.0 decode: Fix indexed vector instructions

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`RBIT <Vd>.<T>, <Vn>.<T>`
`REV16 <Vd>.<T>, <Vn>.<T>`
`SQADD <V><d>, <V><n>, <V><m>`
Issue: #2626

i#2626 AArch64 v8.0 decode: Add RBIT, REV16, SQADD

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

This patch adds
`FRINTZ <Vd>.<T>, <Vn>.<T>`
`CMGT <V><d>, <V><n>, <V><m>`
issue: #2626

i#2626: AArch64 v8.0 decode: add frintz and cmgt

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
make/aarch64_check_codec_order.py
suite/tests/api/dis-a64.txt

This patch adds the instuctions:
`UDOT <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tb>`
`SDOT <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tb>`
This patch also updates the test error message in
aarch64_check_codec_order.py to be more helpful

i#2626: AArch64 v8.2 decode: Add UDOT and SDOT

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

This patch adds the instructions:
`SMLSL{2} <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Ts>[<index>]`
`SMULL{2} <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Ts>[<index>]`
Issue: #2626

i#2626: AArch64 v8.0 decode: Add missing smlsl{2} smull{2} varients

---

clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

When -skip_refs is passed, the view tool still needs to look at the
initial metadata to obtain the trace version and file type.
Tested:
Before:
$ bin64/drrun -t drcachesim -offline -- suite/tests/bin/linux.signest
$ bin64/drrun -t drcachesim -simulator_type view -skip_refs 100 -indir drmemtrace.linux.signest.*.dir/ 2>&1 | egrep 'version|kernel xfer'
T1602962 <marker: version -1>
T1602964 <marker: version -1>
T1602964 <marker: kernel xfer from module offset +0x7fc58e2bd212 to handler>
T1602964 <marker: kernel xfer from module offset +0x7fc58e2bd212 to handler>
T1602964 <marker: kernel xfer from module offset +0x7fc58e2bd212 to handler>
T1602964 <marker: kernel xfer from module offset +0x7fc58e2b87b2 to handler>
After:
$ bin64/drrun -t drcachesim -simulator_type view -skip_refs 100 -indir …

i#5067: Do not skip version in view tool

---

core/ir/aarch64/codec.py
core/ir/instr.h
core/lib/dr_inject.h

Fixes a signed shift issue in instr_set_predicate().
Fixes a typo in dr_inject.h.
Fixes singleton-tuple warnings in codec.py.

Fix clang-tidy and python linter warnings

---

clients/drcachesim/tests/trace_invariants.cpp
clients/drcachesim/tests/trace_invariants.h

Replaces the use of assert() with a virtual function report_if_false()
so that subclasses can set up custom reporting.
Generalizes the includes for easier use in other build frameworks.
Issue: #5076

i#5076 trace invariants, part 1: Generalize error reporting

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/tests/signal_invariants.c
clients/drcachesim/tools/histogram_launcher.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
suite/tests/CMakeLists.txt
suite/tests/linux/rseq.c

Moves tests/trace_invariants.* to tools/invariant_checker.*.
Renames trace_invariants_t to invariant_checker_t.
Issue: #5076

i#5076 trace invariants, part 2: Rename to invariant_checker

---

core/ir/aarch64/codec.py

This patch fixes the inability of codec.py to correctly
generate decode function names with sufficient resolution
to deal with variants of the same opcode.
Issues: #5070, #2626

i#5070: AArch64 decode: fixes generated decoder function names

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Many of the AArch64 entries using the <#shift> argument
were incorrectly decoding the value of the shift. This
incorrect decoding was recorded in the tests and thus
was not caught.
This patch has replaced all the incorrect implementations
with correct ones and increases the test coverage
Issue: #2626

i#2626: AArch64 v8.0 decode: Fix misimplemented shifting instructions

---

core/arch/interp.c

Adds handling of the vsyscall hook failing by avoiding trying to
set the PC to the (zero) displacement PC in such a case.
Tested on a 5.11 kernel where 32-bit hello,world under DR crashes
without this fix but works with the fix.
Issue #5085

i#5085 vsys hook: Handle hook failure in SA_RESTART adjustment

---

clients/drcachesim/common/memref.h

Fixes a typo in a memref.h comment.

Fix spelling error in memref header

---

suite/tests/api/detach_state.c

Fixes the failure to align the stack to 16 on entry to the assembly
functions in the api.detach_state test.
This fixes an app crash in GA CI on Ubuntu20.
Issue: #4953

i#4953 ubuntu20: Fix stack mis-alignment in detach_state

---

.github/workflows/ci-clang-format.yml
core/dispatch.c
suite/runsuite.cmake

Locates python2 and uses it to invoke clang-format-diff for 6.0, to
support running that old version on Ubuntu 20.
Issue: #4953

i#4953 ubuntu20: Explicily invoke python2 for clang-format-diff

---

api/docs/release.dox
clients/drcov/postprocess/drcov2lcov.cpp
ext/drcovlib/drcovlib.c
ext/drcovlib/drcovlib.h
ext/drcovlib/modules.c

Adds support to drcov and drcov2lcov for code in a non-initial module
segment, and for gaps between segments.
Changes drcov's output to uses the module segment offset, rather than
the module base offset.  This better supports modules with code
beyond the first segment and with gaps between segments.
Updates drcov2lcov to use a separate bitmap table per segment, rather
than per module.
Fixes #2243

i#2243: Support non-first-segment-code in drcov

---

.github/workflows/ci-package.yml

Upgrades the VM's used for package building from Ubuntu 16.04 to
Ubuntu 20.04.
Issue: #4953

i#4953 ubuntu20: Update package building to use Ubuntu 20

---

.github/workflows/ci-aarchxx.yml

Upgrades Ubuntu version in android-arm-cross-compile and a64-on-x86 CI jobs on Github to 20.04. We currently use 16.04 which is going to be deprecated on Github next week.
Issue: #4953

i#4953: Upgrade some AArchXX CI jobs to use Ubuntu 20.04

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
suite/runsuite_wrapper.pl
suite/tests/CMakeLists.txt

Makes the -test_mode option, which runs the invariant_checker tool,
available in release builds.  This fixes the drcacheoff.rseq test
failures on GA CI when rseq is actually available in our upgrade to
Ubuntu 20.04.
Removes the test failure ignore rule for Jenkins as this also fixes
the AArch64 failure for the same test.
Fixes #4924
Issue: #4924, #4953

i#4924: Enable drcachesim -test_mode in release builds

---

clients/drcachesim/tests/offline-legacy.templatex
clients/drcachesim/tests/offline-snappy-serial.templatex

Fixes bugs in the drcacheoff.legacy and drcacheoff.snappy tests which
do not account for different locales in matching numbers.
Tested:
Dots instead of commas:
$ LANG=de_DE.UTF-8 ctest -j4 -R drcacheoff
100% tests passed, 0 tests failed out of 36
No thousands separator at all:
$ LANG= ctest -j4 -R drcacheoff
100% tests passed, 0 tests failed out of 36
Issue: #4953

i#4953 ubuntu20: Fix locale test mismatches

---

core/arch/emit_utils_shared.c
core/dispatch.c

Fix a bug where the coarse base shift is not applied due to checking
the module base plus region size, instead of the persisted-region
base, which when the text segment is not at the module base is not the
same thing.
Tested on the pcache-use test, which raises an application crash on
recent Linux distros without this fix.
Fixes #5101

i#5101 pcache: Fix incorrect shift bounds

---

.github/workflows/ci-x86.yml
core/arch/emit_utils_shared.c
core/dispatch.c

Upgrades the x86-64 test suite job to Ubnutu 20 now that all failures
have been addressed.
Issue: #4953

i#4953 ubuntu20: Upgrade the x86-64 job to Ubuntu 20

---

suite/tests/client-interface/signal.c

Moves accesses to global variables and string constants to a separate method
that we always execute from the beginning.
Jumping to the middle of a routine using DR_SIGNAL_REDIRECT causes us to skip the
__x86.get_pc_thunk.x calls that are required before accesses to global variables
in PIC. This call allows accessing them using a fixed offset from code, by
loading the pc of code in a register. Skipping this call may cause the program
to crash due to a bad address.
This fixes the client.signal test on x86 32-bit, which would otherwise keep crashing
in an infinite loop (the crash loop is due to other setup in this test).
Issue: #5079

i#5079: Avoid skipping get_pc_thunk after redirect.

---

suite/tests/CMakeLists.txt

Removes the Klamath and Deschutes tests as there are no flags to
prevent the Ubuntu20 toolchain from including CET instructions which
DR thinks are SSE multi-byte nops, failing these two tests.
Issue: #5109, #4953

i#5109 drcpusim CET: Remove Klamath and Deschutes tests

---

clients/drcachesim/tracer/raw2trace.h
suite/runsuite_wrapper.pl

Fixes a raw2trace cast from 32-bit app_pc to 64-bit int that was
incorrectly sign-extending, to fix the histogram test's invariant
check failure.
Issue: #4953

i#4953 ubuntu20: Fix bad cast in raw2trace

---

.github/workflows/ci-x86.yml
core/monitor.c

Adds a missing KSTOP in monitor_cache_enter for the case when we abort
trace building.
This was causing an assert failure in core/stats.c:361 'stop not matching TOS'
in the code_api,opt_memory|client.events test, on Ubuntu 18.04 in Github CI.
Issue: #4953

i#4953: Add missing KSTOP in trace building.

---

core/unix/loader.c
core/unix/module_elf.c

Some libraries list DT_JMPREL as overlapping with DT_REL{,A} and it's
implied that really JMPREL comes after.  We now handle that when
relocating private libraries.  This fixes crashes from improper
relocation.
Tested on the 32-bit drltrace and drfuzz tests that were crashing due
to this.
Fixes #5080

i#5080: Handle misleading DT_JMPREL library entry

---

api/docs/samples.dox

While browsing the documentation I noticed a broken link due to a typo.

Fix wrong link (instrcalls sample)

---

core/lib/instrument.c
core/lib/instrument.h
core/unix/memcache.c

Removes the query about client aux libs from diagnostics while holding
the all_all_memory_areas lock, avoiding a rank order violation (at the
cost of a potentially spurious warnings).
Fixes #5127

i#5127: Avoid client aux lib query to avoid rank order

---

clients/drcachesim/tests/drstatecmp-fuzz.templatex
core/ir/aarch64/codec.c
core/ir/aarch64/codec.py
suite/tests/CMakeLists.txt
suite/tests/client-interface/drstatecmp-fuzz-app.c

Adds a fuzzing app for AArch64 that automatically generates from the decoding
files a random sequence of side-effect-free and non-branch instructions with 
fuzzed operands for stress-testing clients with drstatecmp. 
This enables automatic testing of even newly inserted instructions in the decoder.
Adds a drcachesim test with delayed tracing for the fuzzing app. 
Testing with an older DR version showed that this test would have eventually 
automatically detected #5023 (instrumentation-clobbering of aflags).
Originally part of #4938. 
Issue: #4678

i#4678: AArch64 fuzz app for drstatecmp.

---

core/unix/loader.c

Mirrors the glibc 2.32+ behavior where ld.so has a hardcoded call to
"__libc_eary_init" before it calls the regular ELF constructors.
This fixes crashes in clients on Ubuntu 21.
Tested in Dr. Memory on Ubuntu 21.
Fixes #5133

i#5133: Call __libc_eary_init for private libc

---

clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/simulator/analyzer_interface.cpp
clients/drcachesim/tests/offline-invariant_checker.expect
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker_create.h
suite/tests/CMakeLists.txt

Adds a new -simulator_type invariant_checker to support a user
launching the checker explicitly on a target trace.
Adds documentation on the new top-level tool.
Adds a simple sanity test of the new flag.  (The -test_mode versions
of existing tests are already stressing the actual invariant checks.)
Issue: #5076

i#5076 trace invariants, part 3: Add simulator_type

---

clients/drcov/postprocess/drcov2lcov.cpp
ext/drcovlib/drcovlib.h

PR #5094 added support for non-first-segment-code in drcov by changing
the drcov output format.  It should have bumped its file format
version; we do that here.
drcov2lcov prints a warning but continues if passed the prior version,
as we expect it to work for cases that worked before: code in the
first segment.  An old build of drcov2lcov would have failed on the
different module table format in any case; now it gives a better error
message about a version change.
Reduces the warning level to 1 for the fatal warnings opening files to
make them more visible.
Tested on a version 2 file from an 8.0 run on a +rx-first-segment application:
$ clients/bin64/drcov2lcov -input ~/dr/releases/DynamoRIO-Linux-8.0.0-1/drcov*.log && grep -A 5 hello coverage.info
[6/6] Generating embed/html/index.html …

i#2243 drcov segments: Increase drov output format version

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/invariant_checker_test.cpp

Adds targeted testing for the trace invariants checker tool for checks
that are not tested by the signal_invariants app's prefetch and
handler markers.
Issue: #5076

i#5076 trace invariants, part 4: Add unit tests

---

clients/drdisas/test_simple.template
core/ir/aarch64/codec.c
core/ir/aarch64/codec.h
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

This patch implements the instructions:
`FMOV <Vd>.<T>, #<imm>`
`FMOV <Vd>.2D, #<imm>`
`FMOV <Xd>, <Dn>.1D[1]`
`MOVI <Dd>, #<imm>`
`MOVI <Vd>.2D, #<imm>`
`CMHI <V><d>, <V><n>, <V><m>`
`FCMGT <V><d>, <V><n>, <V><m>`
`UDF #<imm>`
and their appropriate en/decode functions.
The encoder currently uses ENCFAIL, with a value
of 0 to determine if an encoding has passed or failed.
Unfortunately, this turned out to be a bad assumption of
an invalid value as UDF can be decoded from an encoding of 0.
This patch changes it to 0xFFFFFFF which is currently unused.
A longer term solution would be to return true/false and write
the encoded value to a variable rather than returning it.

i#2626: AArch64 v8.0 decode: Add FMOV, MOVI, CMHI, FCMGT and UDF

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/memref_gen.h
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Changes the view tool's -skip_refs and -sim_refs behavior to count
memrefs rather than instructions, for consistency with other tools.
It was only counting instructions at all because until recently when
it was augmented to print data and markers it only printed
instructions.
Removes the feature of printing the version and filetype for
-skip_refs as the usefulness is outweighed by messing up the reference
count (not an issue with the instruction count).
Adds a new unit test for the view tool which mocks the module mapping
and tests the skip_refs and num_refs options.
Issue: #5076

i#5076 trace invariants, part 6: Count memrefs in view tool

---

clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/simulator/analyzer_interface.cpp
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h
clients/drcachesim/tools/view_create.h

Augments the view tool to show a single thread when the new option
"-only_thread <tid>" is passed.  This is done in parallel mode for
efficiency.
Updates the view test with a simple thread filter test.
Issue: #5076

i#5076 trace invariants, part 7: View single threads

---

clients/drcachesim/tests/allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/allasm_scattergather.asm
clients/drcachesim/tests/offline-allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/scattergather.templatex
ext/drx/drx.c
suite/tests/client-interface/drx-scattergather.c
suite/tests/client-interface/drx-scattergather.templatex

Preserves the scratch xmm register by spilling it before the scatter/gather
instr expansion, and restoring it after. We use memory obtained from the
thread-private heap, using dr_thread_alloc, as the spill slot.
Reserves TLS slot for every thread in drx, to store the allocated pointer to the
xmm spill slot.
Extends drx's state restore to also restore the app value of the spilled xmm
register.
An alternate approach was to extend drreg to make it capable of spilling xmm
regs too, but that was overkill as the scatter/gather expansion requires only
a small subset of that functionality that is very easily implemented as a set of
manual spill and restore. When that support is available in drreg (#3844) we
can use it here too; added a TODO.
Also extends the pure-asm scatter/gather test to verify …

i#2985 scatter-gather: Preserve scratch xmm.

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Tracks the thread and memref count for reporting with each error
found, for use with the view tool to see the context around the error.
Adds location checking to the invariant test.
Issue: #5076

i#5076 trace invariants, part 8: Report error location

---

api/docs/release.dox
clients/drcachesim/tools/view.cpp

Fixes an omission from part 7 (PR #5185) where the view tools runs in
parallel but fails to report error strings for that mode.
Tested manually on a wrong-archtecture trace.
Issue: #5076

i#5076 trace invariants: Report parallel view error

---

.github/workflows/ci-package.yml
.github/workflows/ci-windows.yml

We're hitting problems downloading 1.7.2 and it's good to upgrade in
any case.  This udpates the ninja in our CI jobs to 1.10.2.

Upgrade GA CI ninja to 1.10.2

---

api/docs/release.dox
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/simulator/caching_device.h
clients/drcachesim/simulator/tlb.cpp
clients/drcachesim/tests/drcachesim_unit_tests.cpp

The child (==lower level) cache stats in drcachesim today are only for
the immediately lower level. This is a holdover from the original
implementation which didn't support other than 2 levels. For multiple
levels, one would expect the child stats to include the sum of all the
lower levels.  We fix that here and add a unit test.
The difference is clear in the config file test:
LLC stats:
Child hits:                        147
=>
LLC stats:
Child hits:                    174,695
But to avoid flakiness we do not update its regex and rely on the unit
test.
Fixes #5190

i#5190: drcachesim child stats include all lower levels

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Moves two invariant_checker_t data fields that are written
concurrently (though we expect their values to be constant across
threads) into per-thread data to avoid data race tools complaining.
Tested under ThreadSanitizer.
Issue: #5076

i#5076 trace invariants: Fix concurrent thread writes

---

clients/drcachesim/tests/offline-view.templatex
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

Adds a memref count prefix to every line output by the view tool to
make it easier to use the -skip_refs and -sim_refs options, including
for visualizing errors reported by the trace_invariants tool.
Tested manually.  Here is an example showing a thread change and a
multi-line disassembly with the same prefix for both lines:
```
$ clients/bin64/drcachesim -indir drmemtrace.threadsig.*.dir -simulator_type view -sim_refs 25 -skip_refs 3016012
3016013: T327766   0x00007fe61d582a4a  b8 38 00 00 00       mov    $0x00000038, %eax
3016014: T327766   0x00007fe61d582a4f  0f 05                syscall
------------------------------------------------------------
3016015: T327767 <marker: timestamp 13280020226777973>
3016016: T327767 <marker: tid 327767 on core 8>
3016017: T327767   0x00007fe61d582a51 …
```

i#5076 trace invariants: Print ref count prefix in view tool

---

api/docs/intro.dox
api/docs/transp.dox

Updates the docs on transparency to reflect that we have a private
loader and do support many typical uses of clients using external
libraries.

Udpate transparency docs to reflect modern support

---

api/docs/publications.dox

The move from the old dynamorio.org to the new Github Pages-hosted
site did not bring over 5 academic papers, whose links were broken.
We fix that here by pointing at copies on burningcutlery.com.
Also updates from http to https for burningcutlery.com.

Fix broken paper links

---

core/win32/inject.c
core/win32/os.c
core/win32/os_private.h

Instead of blindly marking the inject hook page as +rx, we remember
its actual prior protections and restore those.  This avoids crashes
in cases where the app's initial code is actually writable.
Tested manually by the filer of #5198.  It is difficult to create an
automated test.
Fixes #5198

i#5198: Preserve actual inject hook page protections

---

core/arch/x86/x86.asm
core/dynamo.c

Switches Windows default map injection to record an app mcontext and
take over there, rather than taking over on the return path out of DR
functions and confusing clients with two initial blocks in the DR
library.
Tested by observing the block sequence in the log file.
Without the fix:
```
Fragment 1, tag 0x000000001502643b, flags 0x1000630, shared, size 19:
[dynamorio.dll~dynamorio_app_init_and_early_takeover+0x37b,~dr_persist_start-0x
Fragment 2, tag 0x0000000015349c23, flags 0x1000030, shared, size 44:
[dynamorio.dll~dynamorio_earliest_init_takeover+0x2d,~dr_virtual_query-0x24dfd]
Fragment 3, tag 0x00007fff20502630, flags 0x9000630, shared, size 34:
[ntdll.dll!RtlUserThreadStart]
```
With the fix:
```
Fragment 1, tag 0x00007ffc25822630, flags 0x9000630, shared, size 34: …
```

i#4958: Take over at app context, not DR return

---

clients/drcachesim/tools/opcode_mix.cpp

Updates the opcode_mix tool to use decode_from_copy() as a better
example of the proper way to decode offline trace instructions which
are mapped to a different address than their original location during
tracing.

Use decode_from_copy in opcode_mix tool

---

ext/drx/drx.dox

Removes a misplaced \p marker in the drx docs.
Fixes #2891

i#2891 docs: Fix drx doc typo

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`CMHS    <Dd>, <Dn>, <Dm>`
`CMGE    <Dd>, <Dn>, <Dm>`
`CMTST   <Dd>, <Dn>, <Dm>`
`CLS     <Vd>.<T>, <Vn>.<T>`
Issues: #2626

i#2626: AArch64 v8.0 decode: Add CLS, CMGE, CMHS, CMTST

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`SQDMULL <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Ts>[<index>]`
`SQDMULL2 <Vd>.<Ta>, <Vn>.<Vb>, <Vm>.<Ts>[<index>]`
`SQDMULL <V><d>, <Vb><n>, <Vm>.<T>[<index>]`
`SQDMULL <V><d>, <Vb><n>, <Vb><m>`
`UMULL   <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Ts>[<index>]`
`UMULL2  <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Ts>[<index>]`
Issues: #2626

i#2626: AArch64 v8.0 decode: Add SQDMULL{2}, UMULL{2}

---

core/ir/aarch64/codec.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.expect

`UMLSL2  <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`UMLAL   <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`UMLSL   <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`UMLAL2  <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
Issues: #2626

i#2626: AArch64 V8.0 decode: add UMLAL{2}, UMLSL{2}

---

core/unix/include/syscall_linux_uapi.h
core/unix/os.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/file_io.c
suite/tests/linux/clone.c

Fixes an existing bug in dup3 handling on AArch64. As SYS_dup2 is not
available on AArch64, SYS_dup3 was not being included in the switch in
pre-syscall handling due to a misplaced conditional compile statement. Note
that on AArch64 dup2 automatically uses dup3 internally, so the bug affected
also the dup2 calls in the client.file_io test.
Fixes close_range handling on AArch64 by updating the syscall defines from a
newer header file that does define __NR_close_range. Defines the
SYS_close_range constant for AArch64.
Enables the client.file_io test on AArchXX. Replaces the inline asm code to
unmask divide-by-zero exceptions, with a glibc wrapper. Also adds a test for
dup3. The clone_range part of this test is enabled on AArchXX but hasn't been
run yet, because our CI machine does not have …

i#5131 new linux syscalls: Fix aarch64 dup3 and close_range handling

---

core/unix/include/syscall_linux_arm.h
core/unix/include/syscall_linux_uapi.h
core/unix/include/syscall_linux_x86.h

Defines SYS_openat2 for all arch. This is another case where the glibc headers
define the NR constant but not the SYS constant.
For x86, the latest glibc version indeed defines SYS_openat2. But it had to be
manually defined for arm and aarch64.
Issue: #5131

i#5131 new linux syscalls: define SYS_openat2

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`SQDMLAL <V><d>, <Vb><n>, <Vb><m>`
`SQDMLAL <V><d>, <Vb><n>, <Hm>.<T>[<index>]`
`SQDMLAL <Vd>.<T>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`SQDMLSL2 <Vd>.<T>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`SQDMLSL <V><d>, <Vb><n>, <Hm>.<T>[<index>]`
`SQDMLAL2 <Vd>.<T>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`SQDMLSL <Vd>.<T>, <Vn>.<Tb>, <Vm>.<Tc>[<index>]`
`SQDMLSL <V><d>, <Vb><n>, <Vb><m>`
Issues: #2626

i#2626: AArch64 v8.0 decode: Add SQDMLAL{2}, SQDMLSL{2}

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`FACGT   <V><d>, <V><n>, <V><m>`
`FACGE   <V><d>, <V><n>, <V><m>`
`FRINTX  <Vd>.<T>, <Vn>.<T>`
`FCMGE   <V><d>, <V><n>, <V><m>`
`FRINTI  <Vd>.<T>, <Vn>.<T>`
`FRSQRTS <V><d>, <V><n>, <V><m>`
`FRINTN  <Vd>.<T>, <Vn>.<T>`
`FRECPS  <V><d>, <V><n>, <V><m>`
`FCMEQ   <V><d>, <V><n>, <V><m>`
Issues: #2626

i#2626: AArch64 v8.0 decode: add FAC*, FCM*, FML*, FRECPS, FRINT*, FRSQRTS

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`FMULX   <Vd>.<Ta>, <Vn>.<T>, <Vm>.<Tb>[<index>]`
`FMULX   <V><d>, <V><n>, <Vm>.<T>[<index>]`
`FMULX   <V><d>, <V><n>, <V><m>`
issues: #2626

i#2626: AArch64 v8.0 decode: add fmulx variants

---

core/unix/os.c

Moves the switch case statement for SYS_rt_sigtimedwait_time64
closer to SYS_rt_sigtimedwait for better code. This is just for
cleanup.
Issue: #5131

i#5131 new linux syscalls: move SYS_rt_sigtimedwait_time64 case

---

api/docs/deployment.dox
api/docs/release.dox
tools/drdeploy.c

Hides the -attach flag from the drrun -help output.
Hides the -attach example in the documentation.
Once #5054 is fixed we can re-enable these, but for now it is just too
broken and advertising it causes more confusion than good.
Issue: #5145, #5054

i#5054: Hide Linux attach until it is fixed

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Fixes cases in which hints not defined in codec.txt should be
treated as OP_nop (NOP) rather than undecoded OP_xx instructions.
Issues: #2626

i#2626: AArch64 v8.0 codec: handle unallocated HINT encodings correctly

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.h
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

`URSHR   <Dd>, <Dn>, #<shift>`
`SQSHRUN <V><d>, <Vb><n>, #<shift>`
`SQRSHRN <V><d>, <Vb><n>, #<shift>`
`UQSHL   <V><d>, <V><n>, #<shift>`
`SQRSHRUN <V><d>, <Vb><n>, #<shift>`
`UQSHRN  <V><d>, <Vb><n>, #<shift>`
`UQSHL   <Vd>.<T>, <Vn>.<T>, #<shift>`
`UQSHL   <V><d>, <V><n>, <V><m>`
And the appropriate tests as well as a readability
update to codec.c
Issues: #2626

i#2626: AArch64 v8 decode: add SQSHRN, SQRSHRUN, SQSHRUN, UQSHL, UQSHRN, URSHR

---

.github/workflows/ci-x86.yml
api/docs/deployment.dox
api/docs/release.dox
core/drlibc/drlibc_module_elf.c
core/unix/injector.c
core/unix/loader.c
core/unix/module_elf.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/attach_test.dll.c
suite/tests/client-interface/attach_test.template
suite/tests/linux/infloop.c
tools/drdeploy.c

Fixes a number of issues with Linux attach:
+ Set xdi to zero for x86 _start relocation of libdynamorio.
+ Implement remote memset for .bss zeroing in elf_loader_map_phdrs(),
fixing a crash in some builds such as Ubuntu20 release build.
+ Don't kill target if attach fails.
+ Fix crash if no pid passed.
+ Adds a useful error message on failure to look at ptrace permissions.
+ Adds a warning to use -skip_syscall if attach hangs.
+ Adds a test by porting the Windows client.attach test to Linux.
Disables the mprotect syscall due to weird failures which need to be
examined.
Further tests of blocking syscalls and -skip_syscall are needed.
Re-enables the attach help message for drrun and the deployment docs.
Tested release build on Ubuntu20 where the .bss crash reproduced every
run and is now …

i#5054: Fix attach crash and other problems

---

clients/drcachesim/tracer/raw2trace.h

Currently offline traces do not support code that is not in a library
(e.g. JIT compiled code). Increased the log severity from 3 to 1 so that
it is more easily noticeable.
Issue: #2062

i#2062: Increased severity of logs for JITted code

---

clients/drcachesim/tests/allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/allasm_scattergather.asm
clients/drcachesim/tests/offline-allasm-scattergather-basic-counts.templatex
ext/drx/drx.c

Fixes a crash in the expanded scatter gather sequence when
a double word index is negative and needs to be sign-extended.
Without sign extension, the computed address may be invalid
(e.g. base + 0xffffffff, instead of base - 1). Double indices are
always signed in scatter/gather instrs; they are already loaded
in 32-bit registers in the expansion.
Also adds test for the same. Fixes some asm test code to use
pcmpeqq for xmm comparisons; vcmpeqss does it only for the
low 32-bits.
Issue: #2985

i#2985 scatter-gather: sign-extend double word index.

---

core/win32/loader.c

The API-MS-Win-Core-File-L2-1 pseudo-dll is provided by kernel32.dll
on Windows 7, instead of kernelbase.dll as it is on all later
versions.
Issue: #2658

i#2658: Core-File-L2 is in kernel32 on Win7

---

core/unix/signal.c
suite/tests/CMakeLists.txt
suite/tests/linux/signal-base.h

Removes a too-early-and-thus-incorrect call to set_pc_mode_in_cpsr()
in execute_handler_from_cache()
(transfer_from_sig_handler_to_fcache_return() does this for us at the
right time).
Removes an incorrect call to dr_set_isa_mode from the cpsr in
transfer_from_sig_handler_to_fcache_return(): we want to only set the
mode from the target, not the interruption point.
Works around QEMU bugs with signals 63 and 64 by using 62 instead in
the linux.signalNNNN tests.  This allows adding them to the list of
tests that work under QEMU.
Augments the linux.signalNNNN tests to vary whether the main code and
the signal handler are arm or thumb, helping to catch and test signal
transition issues.
Issue: #4719, #5233
Fixes #5233

i#5233: Fix arm-vs-thumb signal transitions

---

api/docs/ldstex.dox
core/arch/aarchxx/mangle.c
core/arch/interp.c
suite/tests/client-interface/ldstex.c
suite/tests/client-interface/ldstex.dll.c
suite/tests/client-interface/ldstex.expect

Adds handling for AArch64 exclusive loads that discard a value by
targeting the zero register.  Without this fix, we loop forever in the
store since we load the real value and compare it to the zero we
recorded.  Our fix is to replace the zero register with a scratch
register so that we record the actual value at load time.  For the
same-block optimized case, we instead simply skip the value comparison
check at the store.
Adds a test of every size and destination zero variant.  This test
spins (at multiple points) without the fix.
Fixes #5245

i#5245: Handle exclusive loads into the zero register

---

clients/drcachesim/tests/allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/allasm_scattergather.asm
clients/drcachesim/tests/offline-allasm-scattergather-basic-counts.templatex
ext/drx/drx.c

Fixes spill and restore for the scratch xmm reg. Mov-ing to the lower
xmm bits zeroes the upper bits of the corresponding ymm and zmm
reg. So we need to spill and restore the entire ymm or zmm reg,
whichever is the largest one reg supported by the system, and not
just the xmm part of it.
Also adjusts the state restoration machine to expect the new spill
instrs.
Replaces the linear address of spill slot in instrumentation with an
address computed online using the TLS reg.
Extends the allasm-scattergather test to verify the whole zmm reg
after the scatter/gather expansion. On systems without AVX512, we
verify ymm. This test fails without the fix.
Issue: #2985

i#2985 scatter-gather: Fix spill/restore of scratch xmm reg.

---

core/arch/aarchxx/mangle.c

Removes a no-longer-needed extra check to identify a load exclusive
pair, now that the superfluous immediate integer operands are removed.
Tested on the client.ldstex test which should fail if we incorrectly
identify a pair.
Issue: #4532

i#4532 extra opnds: Remove extra opnd handling in mangling

---

api/docs/deployment.dox

Fixes a reference to "Dr. Memory" which should be "DynamoRIO" in the
deployment docs.

Fix typo in deployment docs

---

api/docs/download.dox
api/docs/new_release.dox
api/docs/release.dox

Updates the Download page to list the new 9.0.0 release.
Prepares the changelog for new post-9.0 changes.
Updates the New Release instructions for a separate docs step.
Fixes #5145

i#5145 v9.0: Post-release documentation updates

---

suite/runsuite_wrapper.pl

Adds the following tests to the ignore list in order to keep the long
suite on master merges greener:
+ win64 'common.floatpc_xl8all' #2267
+ win64 'code_api|tool.drcachesim.simple-config-file' #1807
+ lin32 'code_api,opt_speed|common.fib' #1807
+ lin32 'prof_pcs|common.nativeexec_exe_opt' #2052
+ lin64 'code_api,opt_speed|common.floatpc_xl8all' #1807
Only ignored in the long suite since these are tests we don't want to
completely break:
+ lin32 'code_api|api.startstop' #4604
+ lin64 'code_api|api.detach_state' #5123
+ lin64 'code_api|client.cleancallsig' #1807
Issue: #1807, #2267, #2052, #4604, #5123

i#1807 long failures: List 8 long suite tests as flaky

---

api/docs/release.dox
ext/droption/droption.dox
ext/droption/droption.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/option_parse.dll.cpp

Adds support for multiple names for one option.
Adds a simple test.
This is needed for renaming a drcpusim option while keeping legacy
support for #4366.
Issue: #4366

Add alias support to droption

---

clients/drcachesim/drcachesim.dox.in

Adds explicit documentation for the drmemtrace trace entry record
types.  This is a common topic asked about by new users of our tracing
framework.

Add drmemtrace trace entry docs

---

core/arch/proc.h
core/arch/proc_shared.c
core/arch/x86/proc.c

Fixes a symbol conflict with a python package PyTables that is hit
when statically linking with certain toolchains where non-exported
symbol hiding is not available.  The fix is to rename set_cache_size()
to proc_set_cache_size().  This also matches the proc_ prefix for
related functions, so we do not resort to the d_r_ prefix.
Issue: #3348

i#3348 sym conflicts: Rename set_cache_size to proc_set_cache_size

---

core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch removes the TODO note for clrex which stated it had a superfluous
operand. The spec states that it is a real operand but is ignored and defaults
to a value of 15. The instr_create.h macros have been updated to reflect this.
Fixes: #4532

i#4532: aarch64 decode: remove incorrect clrex todo

---

suite/tests/api/dis-a64.c
suite/tests/api/dis-a64.txt

As part of #2626, exhaustive tests for the instructions that use GPR
registers have been generated. Some of these tests have revealed issues
with the current implementation of several of these instructions. This
patch is the first of several and contains all of the tests that validate
existing instructions as correct.
issues: #2626

i#2626: AArch64 v8 decode: Add validating tests for GPR instructions

---

.github/workflows/ci-windows.yml
CMakeLists.txt
core/CMakeLists.txt
ext/drsyms/CMakeLists.txt
tools/DRstats/CMakeLists.txt

This addresses issue #3805 as follows:
- Remove old detection code for CMake versions older than 2.6.3 to detect `cl_path`. This was hindering CMake from finding the correct `cl_path`.
- Ensure `cl_path` is defined before `cpp2asm_support.cmake` gets included, such that `ml.exe` and `ml64.exe` for x86 and x64 respectively are found in the correct path.
- Specify `cl_path` as a hint when trying to find `lib.exe` and `dumpbin.exe`.
- The Windows SDK that is being used may be installed into `C:\Program Files (x86)\Windows Kits\10`, of which the installation path is covered by a different registry key, namely `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Kits\Installed Roots\KitsRoot10`. Check if the registry key points to an existing path, and use it as `kits_dir` if it does and then use …

i#3805 msvc2019: add support for Microsoft Visual Studio 2019 and Tools for Visual Studio 2019

---

core/unix/os.c

Fix module_walk_program_headers failed when mmap a partial map on Android.
So add module_is_partial_map check before call os_add_new_app_module as other platforms do.

Fix add new module failed when mmap  a partial map on Android.

---

api/docs/ldstex.dox

Adds a missing line break for a Disadvantages list header in the
exclusive monitor docs.

Add missing line break in ldstex2cas docs

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch fixes two underlying issues:
* Several of the instruction variants were decoding to an x register
when they should have been decoding to a w register
* LSL #12 was being decoded as 0x10 (16) rather than 0x0c (12)
issues: #2626

i#2626: AArch64 v8 decode: Fix incorrect decode of add/s, sub/s, tb(n)z

---

CMakeLists.txt
api/docs/release.dox
core/CMakeLists.txt
core/CMake_readelf.cmake
make/package.cmake
tools/CMakeLists.txt

This addresses issue #5130 in the following ways:
- Improve the glibc import checking code by using a regex to match all imports, and then for each import extract the version and use CMake's version comparison functionality to match the version. This allows us to write the desired glibc version as a string such as "2.4", instead of having to write a regular expression that matches everything greater than 2.4 or in general the desired version.
- Introduce a `BUILD_PACKAGE` option that is `ON` by default, but can be turned off when invoking `cmake` as follows: `cmake -DBUILD_PACKAGE=OFF ..`. This is important for rolling release distributions where glibc 2.32 is currently stable and these checks prevent drrun from building.
- Bump the glibc version to 2.17. After checking multiple …

i#5130: improve glibc import checks and make them optional

---

core/ir/x86/decode_table.c
core/ir/x86/instr_create_api.h
core/ir/x86/opcode_api.h
suite/tests/api/ir_x86_0args.h

This PR adds support for the `encls`, `enclu` and `enclv` instructions as described by [chapter 41 "SGX Instruction References"](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3d-part-4-manual.pdf) in volume 3D of the Intel 64 and IA-32 Architectures Software Developer's Manual. These are used in **s**upervisor mode, **u**ser mode and **V**MM mode respectively.
These instructions are somewhat similar to `cpuid`, in that they accept all have a leaf function that can be specified through the `eax` register. However, unlike `cpuid`, the `ebx`, `ecx` and `edx` can both be used as inputs and outputs depending on the specific leaf function.
While Intel SGX is usable on a select set of Intel CPUs, it is usable both in 32-bit and …

add support for the encls/enclu/enclv instructions

---

core/ir/aarch64/codec.c
core/ir/aarch64/disassemble.c
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch fixes two problems with ldrb:
* Some variants were decoding to an x register
when they should have been decoding to a w register
* The "extension" LSL #0 was being decoded as uxtx #0
issues: #2626

i#2626: AArch64 v8 decode: Fix incorrect decode of ldrb

---

api/docs/download.dox

Replaces stale bintray URLs with proper links to our past tutorials
and talks.

Fix broken bintray URLs

---

core/ir/aarch64/codec.txt
suite/tests/api/dis-a64.txt

Previously, the sha* instructions were decoding the vector
container size incorrectly and weren't specifying the
element size. This patch fixes those issues and adds
appropriate tests
Fixes: #5284
Issues: #2626

i#5284: AArch64 v8 decode: fix sha* instructions

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.dox

Changes hardcoded slot numbers to use the corresponding symbolic enum
value instead.
Re-orders a too-late dead register analysis.
Fixes a typo in the drbbdup docs.
Issue: #4134

i#4134 drbbdup: Use spill slot enum

---

CMakeLists.txt

Replaces "-march=armv7-a" with "-march=armv7-a+fp" to make explicit
our gnueabihf architecture target and avoid errors on gcc 11.2
cross-compilation.
Fixes #5299

i#5299: Add +fp to arm arch

---

core/ir/arm/encode.c
core/ir/encode_shared.c

On ARM, instr_is_encoding_possible() was checking reachabilty, yet it
took no target encode address, causing it to fail for any but very
small addresses.  We remove the reachability checks to solve this.
The test for #5302 in a forthcoming PR adds a regression test for
this.
Fixes #5304

i#5304: Ignore reachability for instr_is_encoding_possible()

---

CMakeLists.txt

On Arm, the configure process outputs warnings for not finding AVX support, but that's to be expected on Arm.
-- WARNING: Compiler or processor do not support AVX. Skipping tests
-- WARNING: Compiler or processor do not support AVX2. Skipping tests
-- WARNING: Compiler or processor do not support AVX-512. Skipping tests
Only probe for AVX on x86 platforms, which avoids the warnings elsewhere.

Only check for AVX instructions on x86

---

api/docs/ldstex.dox

Documents several more cases where core DR, even without any tool,
inserts memory operations between an application's load-exclusive and
store-exclusive: far direct links; trace building; indirect branches.
Issue: #1698

i#1698 ldstex: Document core DR memop insertion

---

core/ir/aarch64/instr_create_api.h
ext/drx/drx.c

Corrects INST_CREATE_stlr to INSTR_CREATE_stlr.  Leaves an alias with
the old, incorrect name in case there are any uses outside of this
repository.

Fix incorrect AArch64 name INST_CREATE_stlr

---

core/arch/mangle_shared.c

Makes ARM behave like x86 and AArch64 by having DR mangle pc-relative
operands in tool instructions on all architectures.
Full support in DR's translation code is still needed.
Similarly mangling stolen register and segment references is also
still undone; it may require a new bit identifying "app operands".
Issue: #1834, #5316

i#1834 tool mangle: Make ARM symmetric with other arches

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
ext/drx/drx.c
suite/tests/client-interface/drbbdup-test.dll.c

Updates drbbdup_options_t.atomic_load_encoding to provide acquire
semantics, which is all that's generally needed for a load of a flag.
Implements the option on AArchXX (nothing to do on x86).
Adds a sanity test to one of the existing tests, ensuring the code
generated at least executes succesfully in one thread.
Issue: #4134

i#4134 drbbdup: Add acquire semantics to case loading

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-no-encode-test.dll.c

Adds a new drbbdup option max_case_encoding.  When the value is small,
we can avoid a 2nd scratch register for aarchxx, since we can fit all
encodings in immediates inside compare instructions.
Adds a sanity check.
Confirmed visually in the debug logs that the 2nd scratch is gone:
Before:
```
after instrumentation:
TAG  0x0000ffff868340c0
+0    m4 @0x0000fffd428950e8  f900b781   str    %x1 -> +0x0168(%x28)[8byte]
+4    m4 @0x0000fffd42894da0  d53b4200   mrs    %nzcv -> %x0
+8    m4 @0x0000fffd42894cd8  f900af80   str    %x0 -> +0x0158(%x28)[8byte]
+12   m4 @0x0000fffd42894c58  d28c1000   movz   $0x6080 lsl $0x00 -> %x0
+16   m4 @0x0000fffd42894bd8  f2a85000   movk   %x0 $0x4280 lsl $0x10 -> %x0
+20   m4 @0x0000fffd42894b10  f2dfffe0 …
```

i#4134 drbbdup: Avoid 2nd scratch via max_case_encoding

---

suite/tests/client-interface/inline.dll.c

Fixes a failure in the client.inline_test where it was multiplying an int
by a larger-than-int constant to compare to a 64-bit value, which ends up with
truncation with some toolchains.
Tested on such a toolchain (forthcoming llvm).

Fix integer truncation in client.inline_test

---

ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.dox
suite/tests/CMakeLists.txt
suite/tests/client-interface/drbbdup-nonzero-test.dll.c
suite/tests/client-interface/drbbdup-nonzero-test.expect

When there are just 2 drbbdup cases and one has an encoding of zero,
we can use a flags-free jump-if-register-is-zero for our dispatch,
avoiding flags preservation costs.
Applies this to x86 as well by switching to the xcx scratch register
and using JECXZ.  JECXZ is relatively slow on modern processors.  I
measure its performance, and it depends on the application whether it
out-performs savings the flags.  I left it as the default with hopes
that it will help more often than not on larger clients and
applications, but we can remove it if that is not borne out in future
evaluations.
The existing no-encode-test meets the criteria and serves as a test.
Before:
```
after instrumentation:
TAG  0x0000ffff868340c0
+0    m4 @0x0000fffd428950e8 …
```

i#4134 drbbdup: Avoid flags preservation for 2 cases

---

.github/workflows/ci-osx.yml
CMakeLists.txt
core/arch/asm_defines.asm
core/unix/signal_macos.c
make/cpp2asm_support.cmake
suite/tests/CMakeLists.txt
suite/tests/client-interface/syscall-mod.c

Tested on macOS 12.2 with the following compilation commands:
```
cmake -G "Unix Makefiles" -DCMAKE_CPP=$(which gcc)
make -j16
```
Dependencies like snappy were installed with [Homebrew](https://brew.sh).

Fix macOS compilation

---

core/ir/x86/decode.c
suite/tests/api/ir_x86.c
suite/tests/api/ir_x86.templatex

Fix the following error reported during fuzzing:
core/ir/x86/decode.c:1758:36: runtime error: division of
-2147483648 by -1 cannot be represented in type 'int'
in decode_modrm core/ir/x86/decode.c:1758:36
in decode_operand core/ir/x86/decode.c
in decode_common core/ir/x86/decode.c:2574:18
in decode core/ir/x86/decode.c:2695:12
Issues: #5320

i#5320: Fix error handling in in x86 decode_modrm

---

api/docs/CMake_rundoxygen.cmake
api/docs/scatter_gather_emulation.dox
clients/drdisas/drdisas.dox

Fixes the dynamorio.org docs release by addressing
the unexpected Jekyll tag string "{%" that is present
as part of the scatter and gather instruction
disassembly.
Adds the raw-endraw pair around "{%" and "%}" to
prevent them from being interpreted as tag-start
and tag-end respectively.
Also removes the old workaround of adding raw-endraw
in docx itself, from drdisas.dox.
Tested locally that this fix works.
Fixes: #5328

i#5328: Fix broken docs release.

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v82.txt
suite/tests/api/dis-a64.txt

The current functions for encoding and decoding
vector element size operands using immediate int
enums clashes with operands representing actual
immediate ints.
Issue: #2626

i#2626: Fix operand clashes in AArch64 codec

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch adds better testing coverage for instructions
with SIMD/FP and GPR registers. Of the tests that were
found to fail, the fixes are included.
This fixes:
* DUP: Missing vector size and incorrectly decoded index
* FMOV: Missing index and size
* INS: Incorrectly decoded index and missing size
* SMOV: Incorrectly decoded index and missing size
* UMOV: Incorrectly decoded index and missing size.
issues: #2626

i#2626: AArch64 v8 decode: Fix incorrectly implemented SIMD/FP+GPR instrs

---

core/unix/pcprofile.c

The pcprofile printing code was missing DR_WHERE_TRAMPOLINE, leading
to an assert.
I was not able to reproduce the assert locally so the new case is
technically not tested.
Fixes #5336

i#5336: Add missing pcprofile whereami category

---

suite/runsuite_wrapper.pl

Adds ignore rules for the following observed long suite failures,
keeping some of them limited to the long suite only so we do not lose
the ability to detect fails-every-time breakage in pull requests:
+ #2052: signal.c:5306 tr == NULL || tr->under_dynamo_control || IS_CLIENT_THREAD(dcontext) || sig == SUSPEND_SIGNAL
+ lin64 prof_pcs|common.nativeexec_exe_opt
https://github.com/DynamoRIO/dynamorio/runs/5079862873
+ lin32 prof_pcs|common.nativeexec_retakeover_opt
https://github.com/DynamoRIO/dynamorio/runs/5080176761
+ lin64 prof_pcs,thread_private|common.nativeexec_exe_opt
https://github.com/DynamoRIO/dynamorio/runs/4992456119
+ lin32 prof_pcs,thread_private|common.nativeexec_bindnow_opt
https://github.com/DynamoRIO/dynamorio/runs/4993095901
+ lin32 prof_pcs|common.nativeexec_bindnow_opt …

i#1807: Ignore long suite flaky failures to get it green

---

core/dynamo.c
core/win32/loader.c

Adds a missing swap to private TEB fields on
dr_app_stop_and_cleanup*(), and a swap back to app fields on detaching
thread cleanup.
This fixes problems using droption on client exit in drcachesim tests
for #4139.
Issue: #4139, #5340
Fixes #5340

i#5340: Swap TEB fields to private values during detach

---

clients/drcachesim/CMakeLists.txt
suite/tests/CMakeLists.txt
suite/tests/linux/rseq.c

Our test machines now have a new-enough toolchain to get past a
linking bug that blocked building and running a dozen drcachesim tests
with statically-linked DR on AArch64.  We enable them all here, which
helps bridge the testing gap with x86.
Issue: #2007, #4474
Fixes #2007

i#2007: Enable static dr$sim tests on AArch64

---

suite/tests/api/dis-a64.txt

This patch adds better test coverage of aarch64
instructions concerned with branching and other
control functions
issue: #2626

i#2626: AArch64 v8 decode: Add tests for control instructions

---

core/translate.c
suite/runsuite_wrapper.pl

Adds translation of the save of input registers to rseq sequences.
This fixes a hang on detach in the api.ir test on AArch64, which we
remove from the flaky list here.
Manually tested by running api.rseq 200x on the Jenkins machine.
Previously the test failed every single time there.
Issue: #4923, #4316, #4669
Fixes #4923

i#4923: Add missing rseq mangling translation case

---

CMakeLists.txt
api/docs/code_style.dox
clients/drcachesim/tracer/instru_online.cpp
core/arch/emit_utils_shared.c
core/arch/interp.c
core/ir/x86/decode.c
core/ir/x86/decode_fast.c
core/ir/x86/encode.c
core/unix/injector.c
core/utils.c
core/win32/inject.c
suite/tests/api/drdecode_x86.c
suite/tests/api/drdecode_x86.template
suite/tests/tools.c

Updates pieces of the code that used "char" and assumed it was signed
to use "sbyte" instead.
Adds "-funsigned-char" to the base compiler flags to really ensure the
code base is free of assumptions and to further ensure it is
interoperable with other toolchains that use "-funsigned-char".
Adds a note to the style guide.
Tweaks the drdecode_x86 test to fail without the fixes here in the x86
decoder.
Fixes #1034

i#1034: Eliminate signed char assumptions

---

api/docs/download.dox
api/docs/release.dox

We put out a 9.0.1 bugfix release for the #5352 performance regression
on Windows.  Here we update the direct download links.
Also updates the changelog, which includes a couple of minor features
added since 9.0.0.  We stick with 9.0.1 despite that for simplicity.
The only compatibility change affects just those building DR from
sources and so is less relevant for versioning.
Issue: #5352

i#5352 perf regression: Point at 9.0.1 release

---

api/docs/release.dox
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-test.dll.c

Adds a new field to the drbbdup options that points at an
instrumentation handler that takes in the "for_trace" and
"translating" parameters and returns dr_emit_flags_t.  Either the
original or this one must be set.
Adds a simple sanity check of the parameters.  Testing the return
value is difficult, unfortunately.
Issue: #5356, #3995, #4134

i#5356 bbdup-wrap: Add extended drbbdup instrumentation callback

---

suite/tests/api/startstop_avx512lazy.dll.c
suite/tests/client-interface/app_args.dll.c
suite/tests/client-interface/avx512lazy.dll.c
suite/tests/client-interface/drbbdup-analysis-test.dll.c
suite/tests/client-interface/drbbdup-no-encode-test.dll.c
suite/tests/client-interface/drbbdup-nonzero-test.dll.c
suite/tests/client-interface/drbbdup-test.dll.c
suite/tests/client-interface/drcontainers-test.dll.c
suite/tests/client-interface/drmgr-test.dll.c
suite/tests/client-interface/drmodtrack-test.dll.cpp
suite/tests/client-interface/drreg-cross.dll.c
suite/tests/client-interface/drreg-end-restore.dll.c
suite/tests/client-interface/drreg-flow.dll.c
suite/tests/client-interface/drreg-test.dll.c
suite/tests/client-interface/drutil-test.dll.c
suite/tests/client-interface/drwrap-drreg-test.dll.c
suite/tests/client-interface/drwrap-test.dll.c
suite/tests/client-interface/drx-scattergather.dll.c
suite/tests/client-interface/drx-test.dll.c
suite/tests/client-interface/drx_buf-test.dll.c
suite/tests/client-interface/drxmgr-test.dll.c
suite/tests/client-interface/emulation_api_simple.dll.c
suite/tests/client-interface/mangle_suspend.dll.c
suite/tests/client-interface/predicate-test.dll.c
suite/tests/client-interface/reg_size_test.dll.c
suite/tests/client_tools.h

Moves the CHECK macro defined in quite a few tests into
client_tools.h for sharing.

Share duplicate CHECK macros in client-interface tests

---

core/arch/arch_exports.h

Adds a missing load-acquire in a loop in ATOMIC_MAX that causes hangs
in RSTATS_ADD_PEAK.
Tested on the client.annotation-concurrency test on AArch64 where
without this fix it hangs under release-build plain DR every ~100
runs.  With the fix, there is no hang in 20K runs.
Issue: #2502, #4928

i#2502 locks: Fix bug in ATOMIC_MAX on AArchXX

---

core/unix/loader.c
suite/runsuite_wrapper.pl

Adds private loader redirection of open, close, read, and write to
DR's syscall-wrapper versions (plus file descriptor isolation, for
open and close).  The libc write invokes pthread code for cancel
features, and we are not able to create a private libpthread or
isolate pthread resources (#956) which leads to poor interactions with
application pthread uses and observed hangs.
Tested on the AArch64 Jenkins machine where these tests all hung every
5 to 10 runs in release build before and now they succeed 20,000 times
in a row:
```
derek@dynamorio:~/dr/build_rel$ for i in sim.threads\$ sim.TLB-threads sim.coherence sim.threads-with; do echo $i; ctest --repeat-until-fail 20000 -R $i > RUN-$i 2>&1; done
sim.threads$
sim.TLB-threads …
```

i#4928: Isolate libc write to avoid hangs

---

ext/drwrap/drwrap.c
suite/tests/client-interface/drbbdup-drwrap-test.dll.c

Fixes a drwrap reattach bug by resetting global_flags to 0.
Adds a test case to the drbbdup-drwrap-test.
Fixes #5376

i#5376: Fix drwrap reattach failing to clear flags

---

clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/tracer.cpp
suite/runsuite_wrapper.pl

Fixes the incorrect usage of OP_stur in tool.drcachesim.phys test on AArch64.
This was caused by delaying instrumentation for too many instructions, so that
when we finally did instrument them, we exceeded the  maximum immediate
displacement allowed by OP_stur. Our code needs to use OP_stur because the
trace_entry_t has a size of 12 bytes, meaning that every other entry in the buffer
will have a non-8-byte-aligned address for the `addr` field.
Grants the online_instr_t class the ability to update the trace buffer pointer
by passing the required function to it.
Also removes the test from the ignore list for AArch64.
Fixes: #4922

i#4922: Fix tool.drcachesim.phys on AArch64.

---

ext/drbbdup/drbbdup.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drbbdup-drwrap-test.dll.c
suite/tests/client-interface/drbbdup-empty-bb-test.asm
suite/tests/client-interface/drbbdup-empty-bb-test.dll.c
suite/tests/client-interface/drbbdup-empty-bb-test.expect
suite/tests/client-interface/drbbdup-meta-label-bb-test.asm
suite/tests/client-interface/drbbdup-meta-label-bb-test.dll.c
suite/tests/client-interface/drbbdup-meta-label-bb-test.expect
suite/tests/client-interface/drbbdup-meta-nop-bb-test.asm
suite/tests/client-interface/drbbdup-meta-nop-bb-test.dll.c
suite/tests/client-interface/drbbdup-meta-nop-bb-test.expect

Adds drbbdup support for basic blocks consisting solely of meta instructions. The hash-table manager no longer uses  PCs of the first app instructions inside basic blocks as keys. Instead, tags of basic blocks are now used.
The PR also adds tests. 
Issue: #5356

i#5456: Add drbbdup support for meta bbs

---

ext/drbbdup/drbbdup.c
suite/tests/CMakeLists.txt

Adds better support for thread-private caches for drbbdup. Naturally, manager tables are thread specific when thread-private caches are enabled.
Issue #4134

i#4134: Thread-private support for drbbdup

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.py
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/codecsort.py
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64.txt

This patch adds better test coverage of aarch64
floating point instructions that have an implicit
zero as well as the relevant fixes when the zero
is not decoded.
issues: #2626

i#2626: AArch64 v8 decode: Fix FP instrs with implicit 0

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64.txt

This patch corrects missing element operand sizes
for fminv, fmaxv, fmaxnmv, fminnmv and fcvtxn{2}
as well as adding tests for other instructions to
ensure they are correct.
issues: #2626

i#2626: AArch64 v8 decode: Fix missing element sizes in fp instrs

---

ext/drbbdup/drbbdup.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drbbdup-emul-test.c
suite/tests/client-interface/drbbdup-emul-test.dll.c

Fixes a bug involving rep string expansion where drbbdup told drreg
to ignore control flow even when it was present in the app block.
Adds a guard on that setting based on a check for app control flow.
Adds a custom app for the drbbdup-emul-test which contains a zero-iter
rep string, and augments the test client to reserve rcx on the movs
only.  This reproduces the #5398 crash, and is fixed by the changes
here.
Fixes #5398

i#5398: Handle rep string expansion in drbbdup

---

core/heap.c
ext/drbbdup/drbbdup.c
suite/tests/api/static_prepop.c

Adds diagnostics and fixes related to running out of memory with
drmemtrace now using drbbdup:
Augments the beyond-vmm diagnostics to dump the rstats and print the
allocation type.
Makes a beyond-vmm event non-fatal for -satisfy_w_xor_x for vmheap.
Resets a global drbbdup variable for reattach.
Removes a conditional for static_prepop that is not needed now that
stats are reset on reattach (#2964).
Issue: #2964

Add rstats and alloc type to beyond-vmm diagnostics

---

.github/workflows/ci-docs.yml

The prior updates to other workflows seem to have
missed the docs one, which we update to 9.0 here.
Issue: #5145

i#5145 v9.0: Update docs version number to 9.0

---

.github/workflows/ci-windows.yml
suite/runsuite.cmake
suite/tests/security-win32/except-execution.c
suite/tests/security-win32/except-execution.templatex
suite/tests/security-win32/except-thread.template
suite/tests/security-win32/except.h
suite/tests/win32/debugger.template

Updates the security-win32.except-execution test to not make a raw
thread with a custom stack, which fails on GA CI win2019.  Running the
test code on the initial thread as-is works fine, for regular DR
instrumentation modes.
To avoid headaches with tabs and trailing spaces, updates the context
dumping to avoid those, and updates other templates that use that.
Issue: #5195

i#5195 win2019: Fix except-execution test

---

ext/drbbdup/drbbdup.c

Switch drbbdup's per-block bookkeeping to use unreachable heap instead
of reachable.  This data can really add up, taking up half a GB or
more on large applications -- which really eats into or exceeds the
limited reachable space.
Quick small local test:
Before:
```
Basic block fragments generated :              5169
Trace fragments generated :               527
Peak vmm blocks for unreachable heap :               641
Peak vmm blocks for reachable heap :               336
```
After:
```
Basic block fragments generated :              5169
Trace fragments generated :               527
Peak vmm blocks for unreachable heap :               757
Peak vmm blocks for reachable heap :               230
```
Issue: #5411

i#5411 bbdup mem: Use unreachable heap for per-block data

---

suite/tests/client-interface/drsyms-test.templatex

Relaxes the ordering of symbols found through the dbghelp iterator to
handle orderings seen with VS2019.
This has the client.drsyms-test (and client.drsyms-testgcc) tests now
passing for both 32-bit and 64-bit on my VS2019 local setup.
Unfortunately the GA CI setup has further problems.
Issue: #5195

i#5195 win2019: Relax drsyms-test output ordering

---

clients/drcachesim/tracer/tracer.cpp
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/client-interface/drbbdup-test.dll.c

Moves all drbbdup per-thread memory to unreachable heap.
Moves the drbbdup dynamic case hit table to be dynamically allocated
based on a new drbbdup option "never_enable_dynamic_handling" not
being set.  This eliminates 128K per thread for drmemtrace, which
makes a big difference on large applications.
Sanity test:
Before:
```
$ bin64/drrun -rstats_to_stderr -t drcachesim -offline -max_global_trace_refs 10K -- suite/tests/bin/client.annotation-concurrency libclient.annotation-concurrency.appdll.so A 4 64 3
Peak threads under DynamoRIO control :                 5
Peak vmm blocks for unreachable heap :               767
Peak vmm blocks for reachable heap :               726
Peak vmm virtual memory in use (bytes) :          10293248
```
After:
```
Peak threads under DynamoRIO control : …
```

i#5411 bbdup mem: Shrink per-thread heap usage

---

.github/workflows/ci-windows.yml
api/docs/building.dox
suite/runsuite_wrapper.pl

Updates our official supported Windows toolchain from VS2017 to VS2019.
Updates the documentation on how to build.
Updates our GA CI jobs.
Adds 3 tests to the ignore list as they fail on this platform and we
do not yet have fixes.
Issue: #5195

i#5195 win2019: Switch to VS2019 in GA CI and docs

---

suite/runsuite_wrapper.pl
suite/tests/CMakeLists.txt
suite/tests/client-interface/tls.template

Fixes the expected output for client.tls on Windows. The previous template
accounts for a mysterious output line, which we're not seeing anymore on
vs2019, so we just remove it from the expected output.
Also removes support for PRE_VS2015, seeing as we're effectively dropping
support for vs2017 too by removing the above-mentioned line.
Issue: #5195

i#5195 win2019: Fix client.tls test.

---

core/unix/os.c
suite/tests/CMakeLists.txt

Adds the `dual_map_file` to the DR `fd_table`. This is to prevent the app from
closing this FD, which manifests as an OOM on an extending commit.
Unfortunately, due to constraints on the order of invocation of
`vmm_heap_unit_init` and `d_r_os_init` in `dynamorio_app_init_part_two_finalize`,
the `fd_table` is not initialized when the `dual_map_file` is created. This means that
`fd_table_add` will not really add it to the `fd_table`. So, we remember the
`dual_map_file_fd` and add it to `fd_table` when we create it.
Modifies the handling for the global log file to use the same mechanism, instead of
adding it explicitly in the DEBUG build.
Also adds a `-satisfy_w_xor_x` variant for the `client.file_io` test which attempts to
close DR FDs. It fails without adding `dual_map_file` to `fd_table`. …

i#5421: Prevent app from closing dual_map_file.

---

clients/drcachesim/tracer/tracer.cpp
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/drbbdup-no-dup-test.dll.c
suite/tests/client-interface/drbbdup-no-dup-test.expect

Augments drbbdup to allow a value of 0 for
drbbdup_options_t.non_default_case_limit.  When it is set to 0, no
duplication will occur, and no per-block data structures will be
allocated, saving memory.
Adds a test case for this.
Updates drmemtrace to use this when multi-case options are not
selected.
Sanity test:
Before:
```
$ bin64/drrun -rstats_to_stderr -t drcachesim -offline -max_global_trace_refs 10K -- ~/spec2006/bzip2-test/bzip2_base.gcc-64bit ~/spec2006/bzip2-test/dryer.jpg 2
Peak vmm blocks for unreachable heap :               747
Peak vmm virtual memory in use (bytes) :           6963200
```
After:
```
Peak vmm blocks for unreachable heap :               631
Peak vmm virtual memory in use (bytes) :           6389760
```
Along with the prior shift to use unreachable heap for …

i#5411 bbdup mem: Eliminate per-block bookkeeping for no-dup usage

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/cache_lru_unit_tests.cpp
clients/drcachesim/tests/cache_replacement_policy_unit_test.cpp
clients/drcachesim/tests/cache_replacement_policy_unit_test.h
clients/drcachesim/tests/drcachesim_unit_tests.cpp

This change adds unit tests for clients/drcachesim/simulators/cache_lru.cpp.
These unit tests catch issues reported in i#4881 which was tested by
reverting the fix for that issue #4883.
Issue: #4842, #4881

i#4842 drcachesim unit tests: Add cache_lru unit test

---

core/utils.c
suite/tests/client-interface/drwrap-test.dll.c

Fixes a regression from PR #5370 which added asserts to various DR
lock routines which are not valid for client locks marked as the app.
Adds sanity tests for each of the 3 types of locks that can be marked
as app locks.  These hit the asserts without this fix.
Fixes #5432

i#5432: Relax asserts for marked-app locks

---

.github/workflows/ci-package.yml

The windows-2016 image is deprecated so we update the DR package
building job to use windows-219.
Issue: #5195

i#5195 win2019: Switch to 2019 image for Windows package

---

api/docs/triager.dox

Updates a few stale entries in the triager docs, such as mentions of
Appveyor and Travis.

Update triager docs

---

core/vmareas.c

There are some cases with null start and end app_pc-s during profiling java on AArch64.
As result, we caught hang in release build.
Kirill

Added missed unlock in case of failed binary search

---

api/docs/home.dox
clients/drcachesim/drcachesim.dox.in

Adds a page describing and pointing at the Google data center workload
traces that are being made available in drmemtrace format.
The page deliberately uses a distinct top-level name so that
we can point at https://dynamorio.org/google_workload_traces.html.
Adds a pointer to the front page as this is considered relevant and
interesting to many users.

Add docs for Google Workload Traces

---

tools/drdeploy.c

Fixes a regression from PR #5443 where warnings about an incomplete
multi-bitwidth installation that used to be suppressed when -use_dll
is passed were instead enabled.
Issue: #5250

i#5250 alt-bitwidth: Fix regression in drrun warning

---

CMakeLists.txt
clients/drcachesim/common/options.cpp
clients/drcachesim/common/snappy_consts.h
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/reader/snappy_file_reader.cpp
clients/drcachesim/tracer/snappy_file_writer.cpp
clients/drcachesim/tracer/snappy_file_writer.h
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Adds a new drmemtrace option -raw_compress snappy_nocrc.
This requests snappy compression but omitting checksums.
This is 2.5x faster than snappy with checksums.
This currently uses local-only snappy chunk types; we should
propose adding them to the public spec.
Adds a sanity test.
Issue: #5427

i#5427 compress: Add snappy_nocrc drmemtrace option

---

api/docs/debugging.dox
core/unix/os.c
core/unix/os_private.h
core/unix/signal.c
suite/tests/api/detach_signal.cpp

Changes the signal that DR uses to suspend a thread from SIGUSR2,
which is sometimes blocked by the app at attach time, to SIGFPE, which
as a fatal normally-synchronous signal is less likely to be blocked.
Manually tested on an attach to mysqld which failed with SIGUSR2 but
succeeds now.
Fixes #5458

i#5458: Switch suspend signal to SIGFPE

---

api/docs/release.dox
core/arch/aarchxx/aarchxx.asm
core/ir/arm/encode.c
core/ir/disassemble_shared.c
core/ir/opnd.h
core/unix/injector.c
suite/tests/CMakeLists.txt
suite/tests/runall.cmake
tools/drdeploy.c

Implements missing functionality for ptrace attach on AArch64 and
AArch32: generated code sequences were previously x86-only;
-skip_syscall handling only supported x86; and AArch64 does not
support PTRACE_POKEUSER or PTRACE_PEEKUSER.
For AArch32, Thumb vs Arm mode require multiple steps: clearing LSB to
point at the path used as data via a call; switching to Arm mode for
DR's _start; setting the LSB of the initial app PC.
For AArch32, additionally fixes an encoder error where the opcode is
queried before copying a needs-no-encoding instruction.  This is
required for the instruction used to hold data for injection.
Tweaks the disassembler to leave a level 0 instr alone, again to
better handle the data-only insruction used for injection.
Enables the client.attach test on AArch64 and …

i#38 attach: Enable attach on AArch64

---

core/arch/arch_exports.h
core/unix/loader.c

Fixes errors that can lead to crashes in relocate_dynamorio, where its
access to a function pointer and to the page size can both return
garbage pre-relocation.  We solve this with assembly to get the
current PC, and just using a 4K minimum page size for the backward
walk.
Tested with the PR #5462 branch where the new client.attach_blocking
test crashes without this fix on AArch64.
Manually tested on arm as well.
Fixes #5463

i#5463: Avoid globals pre-relocation

---

api/docs/release.dox
core/unix/injector.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/attach_blocking.expect
suite/tests/client-interface/attach_blocking.runall
suite/tests/linux/infloop.c
suite/tests/runall.cmake
tools/drdeploy.c

Makes interrupting a blocking syscall on attach the default behavior.
Removes the -skip_syscall drrun/drinject parameter.
Adds a test by adding an optional blocking syscall to infloop.
Issue: #38

i#38 attach: Make -skip_syscall the default

---

core/win32/drwinapi/ntdll_redir.c

"index < 0" always false because index is unsigned integer

Fix bitmap_find_free_sequence() result check

---

api/docs/code_reviews.dox

Removes old Appveyor and Travis information from the code review docs.

Update code review docs for Github Actions

---

core/unix/signal.c
core/unix/signal_private.h

Refactors all data shared across a CLONE_SIGHAND group into a single
structure.  This makes it easier to understand and easier to add new
such fields, which we'll want for mask handling.
Issue: #2311

i#2311 sigmask: Cleanup: Refactor sighand data into struct

---

core/unix/os.c
core/unix/os_private.h
core/unix/signal.c
core/unix/signal_private.h
core/utils.h
suite/tests/CMakeLists.txt
suite/tests/api/static_signal.c
suite/tests/api/static_signal.expect
suite/tests/linux/sigmask.c
suite/tests/linux/sigmask.expect

Adds a solution to the problem of the real signal mask having a signal
unblocked in a thread where the app has it blocked, while another app
thread has it unblocked, when the kernel delivers a group-wide signal.
To avoid checking all threads on every blocked signal, which requires
heavyweight locks that can't be acquired from our signal handler, we
maintain a count of unmasked threads for each signal number.  This is
shared across the handler group and is updated using atomic
operations.
On arrival of a signal blocked by the app, we first detect whether it
is whole-group-directed, by examining the si_code values.  If it is,
and if the unmasked thread count is > 0, we want to re-route it: but
we can't acquire the locks here, so we mark it unblocked, unlink the
interrupted fragment (if …

i#2311 sigmask: Reroute blocked signal if unblocked thread exists

---

core/ir/aarch64/codec.c
suite/tests/api/dis-a64.txt

Previously, some of the ld* and st* instructions were
showing the post-index offset as OPSZ_1, which was
inconsistent with all other aarch64 post-index offsets
which showed them as OPSZ_PRT
Issues: #2626

i#2626: AArch64 v8 decode: gpr-mem: make post-index offsets consistent

---

libutil/dr_frontend_unix.c
suite/tests/libutil/frontend_test.c

I changed the required access mode to `DRFRONT_EXEC` to ciruumvent trying to execute files that aren't executable.
A new check in `drfront_searchenv()` is introduced to determine if the path in option is in fact a directory and should not be executed.
In this implementiation we are in the akward situation of calling `stat()` twice (first time in `drfront_access()` and then in `drfront_searchenv()`). An alternative approach would be to add a new variant for `drfront_access_mode_t` called `DRFRONT_ISDIR`. Though `ISDIR` isn't really an access mode.
So what would the preferable method be?
```
Fixes a bug where DynamoRIO tries to execute a directory or a file that
is not marked as executable when it is present in a directory contained
in the PATH environment variable.
Fixes #5455
```

i#5455 path-ignore-directory: Do not try to execute directories

---

CMakeLists.txt
core/drlibc/drlibc.h
core/drlibc/drlibc_unix.c
core/unix/os.c
libutil/CMakeLists.txt
libutil/dr_config.c
libutil/dr_frontend_unix.c
libutil/utils.c

Eliminates a dependence on glibc 2.33 coming from the use of stat() in
drfrontendlib.  This is done by using the dr_stat_syscall() from drlibc.
Fixes #5474

i#5474: Eliminate stat glibc 2.33 dependence

---

core/ir/aarch64/codec_v80.txt
core/ir/aarch64/instr_create_api.h
core/ir/instr_api.h
core/ir/instr_shared.c
suite/tests/api/dis-a64.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch adds the element size to the memory
instructions that were missing it, as well as
removing several extraneous register fields in
those registers. This covers ld*, st* instructions
and updates both the disassembly and encoding tests.
Issues: #2626

i#2626: AArch64 v8 decode: gpr-mem: add element sizes and remove duplicated regs

---

core/lib/statsx.h
core/optionsx.h
core/unix/signal.c
core/unix/signal_private.h
suite/tests/CMakeLists.txt
suite/tests/linux/sigmask.c
suite/tests/linux/sigmask.expect

Disables rerouting of blocked alarm signals while inside an app
handler.  This is not bulletproof: I have it considering the handler
as exited if we see sigreturn or sigprocmask, but there is no
requirement that the app use either siglongjmp or sigreturn to exit a
handler and to not use sigprocmask inside the handler.  But, if we get
it wrong, it will fall back to not rerouting alarms at all, which we
can live with as those are typically not used as required messages and
routed to a single thread.
The rerouting of alarms was seen to cause problems on large apps where
normally they can accumulate due to DR overhead causing a new one to
arrive while still in the handler for theprior one.  Rerouting sent
them to new threads, rather than marking pending and dropping if
several accumulated. …

i#2311 sigmask: Avoid rerouting alarms in handlers

---

api/docs/debug_memtrace.dox
api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/drcachesim.dox.in
suite/tests/CMakeLists.txt

For non-static drmemtrace, -raw_compress is now set to lz4 by default,
as that is nearly always faster than no compression or any other
compression scheme we've tried.
If lz4 is not enabled in the build, and again drmemtrace is not
static, snappy_nocrc is the default.
Otherwise, compression is disabled by default, just like today.
Inverts the raw-lz4 tests to become raw-none tests.
Updates the documentation.
Issue: #5427

i#5427 compress: Turn -raw_compress lz4 on by default

---

clients/drcachesim/drcachesim.dox.in
clients/drcachesim/simulator/analyzer_interface.cpp
clients/drcachesim/tests/offline-view.templatex
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

Adds support for using the drmemtrace view tool on a trace for which
no modules.log, and thus no binary, is available.
The output looks like this:
```
----------------------------------------------------------------------
63586: T3551528   0x7f7fe453152a  non-branch 5 byte(s)
63587: T3551528   0x7f7fe453152f  non-branch 2 byte(s)
63588: T3551528     read  1 byte(s) @ 0x7f7fe3ec538c
63589: T3551528     read  1 byte(s) @ 0x7f7fe454e90d
63590: T3551528   0x7f7fe453152f  non-fetched instruction 2 byte(s)
63591: T3551528     read  1 byte(s) @ 0x7f7fe3ec538d
63592: T3551528     read  1 byte(s) @ 0x7f7fe454e90e
63593: T3551528   0x7f7fe453152f  non-fetched instruction 2 byte(s)
63594: T3551528     read  1 byte(s) @ 0x7f7fe3ec538e
63595: T3551528     read  1 byte(s) @ …
```

i#5486: Add drmemtrace view tool support for no binaries

---

clients/drcachesim/tests/offline-fork.templatex
clients/drcachesim/tracer/tracer.cpp
core/heap.c
suite/tests/CMakeLists.txt

Fixes a bug where drcachesim -offline complained about an open file
across a fork.  This bug blocked tracing of SPECCPU perlbench.
Adds a new test of drcachesim -offline with an app that forks.  As is,
this matched the -satisfy_w_xor_x test regex, and I tried to make it
work with that option by fixing a file close bug here.  However, I did
not have time to figure out another bug which I filed as #5499.  I
thus tightened the "fork" regex to exclude this test from
-satisfy_w_xor_x.
Fixes #5495

i#5495: Fix drcachesim fork bug

---

clients/drcachesim/tracer/physaddr.cpp
clients/drcachesim/tracer/physaddr.h
clients/drcachesim/tracer/tracer.cpp

Switches from std::unordered_map in physaddr_t to a drcontainers
hashtable to avoid malloc and make things safe for statically-linked
drmemtrace.
Similarly, switches from std::ostringstream to dr_snprintf in
physaddr_t::init() to avoid malloc.
Tested on a multi-threaded app which hits the post-init malloc warning
without both fixes (test will be added in a forthcoming PR: it cannot
be added now as physaddr_t is not thread-safe yet).
Issue: #4014

i#4014 dr$sim phys: Avoid malloc in physaddr_t

---

clients/drcachesim/tests/cache_replacement_policy_unit_test.cpp

Adds a test case with an 8 way set associative cache.
Makes the address vector used in the unit tests common for all tests.
Issue: #4842

i#4842 drcachesim: Add more test cases for LRU cache simulator

---

clients/drcachesim/tests/phys-threads.templatex
clients/drcachesim/tracer/physaddr.h
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

The physaddr_t class is not thread-safe and was previously used racily
in the drmemtrace code.  We fix that by creating a separate instance
per thread.  A test with multiple threads is added.
Issue: #4014

i#4014 dr$sim phys: Make physaddr_t per-thread

---

api/docs/release.dox
ext/drcovlib/drcovlib.h
ext/drcovlib/modules.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drmodtrack-test.dll.cpp

Adds a new reverse-lookup routine drmodtrack_lookup_pc_from_index()
which is needed to implement physical address support for offline
dr$sim traces.
Adds a simple test.
Issue: #4014

i#4014 dr$sim phys: Add drmodtrack_lookup_pc_from_index()

---

clients/drcachesim/common/utils.h
clients/drcachesim/launcher.cpp
clients/drcachesim/tracer/physaddr.cpp
clients/drcachesim/tracer/physaddr.h
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/tracer.cpp

Adds support for different page sizes from 4K for drmemtrace's
-use_physical.
Adds hugepage support, which does not require anything special: just
updated the comment.
Improves the error reporting for physical translation.
Tested on an AArch64 machine with 64K pages.
Issue: #4014

i#4014 dr$sim phys: Add different page size support

---

clients/drcachesim/common/trace_entry.h

Documents which bits hold the cpu number versus the socket/node number
on Linux for the drmemtrace marker #TRACE_MARKER_TYPE_CPU_ID.

Document Linx cpu id versus socket split

---

clients/drcachesim/tracer/physaddr.cpp
clients/drcachesim/tracer/physaddr.h
clients/drcachesim/tracer/tracer.cpp

Switches from the drcontainers hashtable to the new open-address
hashtable provided by DR.  This is 2x to 3x faster due to the reduced
dereferences from the inlined data.
Increases the last-value cache from one entry to an array of 8
entries.  This was found to provide improved performance on small
benchmarks.
Measured on bzip2 local and SPEC2006 runs as they are short enough to
allow interactive experimentation.  -use_physical still incurs a ~2.5x
slowdown, but it was 9x before these changes.  The bottleneck is no
longer the hashtable but is now spread across all the address
iteration and querying code.
Issue: #4014

i#4014 dr$sim phys: Improve v2p cache and hash performance

---

clients/drcachesim/drcachesim.dox.in

Adds a clarification to the documentation of TRACE_MARKER_TYPE_CPU_ID. Mention that this
marker is output in trace headers, and may not capture thread migrations to a different cpu
due to kernel preemption. But this should be relatively rare.

Clarify documentation about cpu_id trace marker

---

api/docs/building.dox

Also changed the description to have 64-bit as default.

Fixed instructions for building 64-bit VS 2019

---

clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

Fixes a regression in the view tool caused by the delay in printing
timestamps in order to print window dividers for multi-window traces.
Improves the view_test to include timestamps, which now fails without
this fix.
Fixes #5524

i#5524: Fix view skip_refs timestamp undercounting

---

.github/workflows/ci-aarchxx.yml
.github/workflows/ci-package.yml

Fixes the problem of NDK setup failing due to ANDROID_NDK_ROOT pointing to the wrong path. The GitHub VM system preset ANDROID_NDK_ROOT to a location which does not include the necessary resources that the setup process needs. We set the ANDROID_NDK_ROOT to the right location before running the setup script. 
Fixed: #5527

i#5527: fix android build broken by preset ANDROID_NDK_ROOT

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Solves issues with requiring precise placement of physical markers
prior to their corresponding regular virtual address entry (ifetch
entries being inserted between the marker and memref by raw2trace;
delayed branches needing to carry their marker; page-spanning extra
markers needing to land in the right place) by switching to a scheme
where markers come in pairs with a physical and a virtual.  Such a
pair has flexibility on where it can appear in the trace so long as it
is prior to the regular entry with that virtual address.  This
eliminates all work and complexity for raw2trace to move the markers
around.
Solves issues with capacity where the tracer runs out of pre-allocated
space inside the main buffer for marker-heavy output by switching to
use a separately-allocated-and-emitted …

i#4014 dr$sim phys: Solve placement and capacity issues

---

clients/drcachesim/tools/view.cpp

The recent refactoring of the drmemtrace view output failed to update
the indent for second-line raw bytes from disassembly.  We correct
that here.
Before:
------------------------------------------------------------------------------------------------------------------------
342: T2539054 ifetch 2 byte(s) @ 0x00007f5feed8cf42 74 0e                jz     $0x00007f5feed8cf52
343: T2539054 ifetch 8 byte(s) @ 0x00007f5feed8cf52 48 83 3d 16 fc 02 00 cmp    <rel> 0x00007f5feedbcb70, $0x00
343: T2539054  00
344: T2539054 read   8 byte(s) @ 0x00007f5feedbcb70 by PC 0x00007f5feed8cf52
------------------------------------------------------------------------------------------------------------------------
After:
---------------------------------------------------------------------------------------- …

i#5486 view no-opc: Fix incorrect indent in drmemtrace view tool

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/burst_aarch64_sys.cpp
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tests/offline-windows-asm.templatex
clients/drcachesim/tests/raw2trace_io.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp

To use the new physical address markers in a trace analysis tool, the
page size must be known.  Here we add a new marker to the thread
headers holding the page size.  Sanity tests are added.
Issue: #4014

i#4014 dr$sim phys: Add page size marker

---

clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/allasm_repstr.asm
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tests/offline-windows-asm.templatex
clients/drcachesim/tracer/physaddr.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt
suite/tests/samples/memtrace_simple_repstr.templatex

Adds handling of page-spanning instruction fetch and data accesses.
For offline traces these are heuristics as we do not know the precise
sizes at tracing time.  Since an extra physical page value is not
harmful, the heuristics emit a second page if there is any decent
change that it is reached.
Adds a data page span test by switching the drcacheoff.phys test to
use allasm_repstr and adding such an access there.  An instruction
cross is more difficult to synthesize.
Issue: #4014

i#4014 dr$sim phys: Handle page-spanning accesses

---

clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/physaddr.cpp
clients/drcachesim/tracer/physaddr.h
clients/drcachesim/tracer/tracer.cpp

Fixes two bugs causing crashes with -use_physical:
+ Records the drcontext used for hashtable creation to ensure the same
one is used at destruction as a different thread can call the exit
event.
+ Orders the drmemtrace thread exit event before the drmodtrack one to
ensure drmodtrack access during the final thread buffer output is safe.
These fixes were manually tested on large multi-threaded applications
where these two crashes showed up before and disappear with the fixes.
Issue: #4014

i#4014 dr$sim phys: Fix 2 crashes

---

clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

Separates out header printing to a separate routine that can
be invoked by sub-classes instead of duplicating the print logic.
Sets width of instr/data bytes to 2, so that double-digit byte
memrefs are formatted the same as single-digit ones.

Minor formatting fixes in the view tool

---

core/unix/os.c

This minimal fix ensures that the cur_range_*_fd variables
are always initialized to make it compatible with the gcc compiler
flag -Wmaybe-uninitialized.
Technically, this does not fix any bug but supresses the warning
as the compiler cannot see through the for loop that changes the
variables value.

Fix maybe-uninitialized compiler warnings

---

core/fragment.c
core/fragment.h

This fixes the return of a local stack addr by making the
function void. This is an internal API and the return value
is nowhere used across DynamoRIO.
closes: #5534

Fix return of local addr in fragment_add_ibl_target

---

clients/drcachesim/drcachesim.dox.in
clients/drcachesim/tests/allasm-aarch64-prefetch-basic-counts.templatex
clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/basic_counts.templatex
clients/drcachesim/tests/builtin-prefetch-basic-counts.templatex
clients/drcachesim/tests/offline-allasm-aarch64-prefetch-counts.templatex
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/offline-allasm-scattergather-basic-counts.templatex
clients/drcachesim/tests/offline-basic_counts.templatex
clients/drcachesim/tests/offline-builtin-prefetch-basic-counts.templatex
clients/drcachesim/tests/offline-burst_aarch64_sys.templatex
clients/drcachesim/tests/offline-burst_threadL0filter.templatex
clients/drcachesim/tests/offline-burst_threadfilter.templatex
clients/drcachesim/tests/offline-legacy-int-offs.templatex
clients/drcachesim/tests/offline-windows-asm.templatex
clients/drcachesim/tests/scattergather.templatex
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h

Adds counts of physical,virtual marker pairs and of unavailable
physical address markers to the basic_counts tool.  Updates various
test outputs.
Issue: #4014

i#4014 dr$sim phys: Add counts of physaddr markers

---

core/fragment.c

Removes a redundant return statement at the end of
fragment_add_ibl_target that's triggering a formatting
check.

Remove redundant return statement at routine end

---

api/docs/release.dox
tools/drdeploy.c

This patch adds a new parameter -tool_dir to specify in which folder tool configuration files should be looked up.
This is a preparation for issue #5153.

Add support to overwrite default tool config dir

---

tools/drdeploy.c

This patch adds a check when parsing the tool config files:
Clients for alternative archs (e.g. for cross-exec) injection
are only appended if the path to the client lib actually
exists.
This is a preparation for system-wide deployments, where this
check has to be performed at runtime as users might only
install the dr library for a single architecture.
Previously having invalid paths in the tool config file
worked if the respective client was not requested, but led to a warning.
With this patch, the missing client is simply not registered at all.
Issue: #5153

Only enable alt-arch tools/clients when available

---

clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/physaddr.cpp

The view tool was not printing the virtual address for
virtual-to-physical translations, nor the address for software
prefetches, which made it hard to diagnose physical address failures
in general and in particular when the culprit virtual address was from
a prefetch as it did not appear in the text output.  We add that here.
Since some prefetches have long names, we abbreviate them, but still
need to widen the name field to align them all.
While at it, we add the function marker values to the view tool as
well.
Example output:
```
10: T462774 ifetch        7 byte(s) @ 0x00007f6cae908a54 non-branch
11: T462774 read          8 byte(s) @ 0x00007f6cae90ca20 by PC 0x00007f6cae908a54
12: T462774 ifetch        4 byte(s) @ 0x00007f6cae908a5c non-branch
13: T462774 pref-w-L3-NT  8 byte(s) @ …
```

i#4014 dr$sim phys: Add p2v fail, prefetch, and funcs to view tool

---

api/docs/deployment.dox
core/lib/dr_events.h
suite/tests/CMakeLists.txt
suite/tests/runall.cmake
tools/CMakeLists.txt
tools/drdeploy.c
tools/nudgeunix.c

This patch renames the nudgeunix tool to drnudgeunix to be
named more consistently with the rest of DynamoRIOs frontend tooling.
This helps for packaging as nudgeunix is somehow non-specific.
For backward compatibility, a symlink with the old name is added.
Related to issue #5153

Rename nudgeunix to drnudgeunix

---

CMakeLists.txt

Before this patch, libutil was not built in case building of
BUILD_TOOLS and BUILD_DRSTATS was disabled. This lead to a
link-time error as drcachesim (a client) depends on drfrontendlib.
This is now fixed by also building libutil when enabling BUILD_CLIENTS.

Build libutil when clients are built to fix drcachesim dependency

---

ext/droption/droption.h
suite/tests/CMakeLists.txt
suite/tests/client-interface/option_parse.dll.cpp
suite/tests/client-interface/option_parse.expect

- Enhance the conversion of integer options to support parsing octal or hexadecimal format strings
- Added negative format string checking before unsigned integer option's parsing
- Added test cases in the  test client 'code_api|client.option_parse'. The new test cases use integer options to parse octal and hexadecimal format strings and unsigned integers to parse the negative format strings.
Issue: #5505

i#5505 kernel trace: Support octal and hex values in droption

---

core/lib/dr_tools.h

Some of the syntax in dr_tools.h was in the format
@param[name]  desc
which can cause issues with certain versions of doxygen.
This patch changes it to the format
@param[in|out] name desc
which is widely supported
Fixes: #5529

i#5529: Fix incompatible doxygen syntax

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/arch/proc_shared.c

The Limited Ordering Regions feature is required for the v8.1
load-acquire and store-release instructions like LDLAR and STLLR which
rely on the hardware providing order between memory accesses to
regions of the physical address map. Read from ID_AA64MMFR1_EL1.
Issues: #5475, #1569

i#5475 Add FEATURE_LOR for AArch64 v8.1

---

core/ir/instr_create_shared_api.h
core/ir/instr_inline_api.h
core/ir/instr_shared.c
core/ir/opnd_shared.c
core/ir/riscv64/instr.c
core/ir/riscv64/instr_create_api.h
core/ir/riscv64/opcode_api.h
core/ir/riscv64/opnd.c

Add minimal opcode, operand and instruction generation macro definitions
to enable the rest of the code to compile.
NOTE:
This code is not validated and mostly contains stubs as the main point
was to achieve compilation and estimate the effort required for the
port. Some of the trivial logic has been implemented though.
Issue: #3544

i#3544 RISC-V, part 2: Add opcode and instr macros

---

api/samples/div.c
api/samples/opcodes.c
api/samples/statecmp.c

Add definitions required for samples to compile for RISC-V.
NOTE:
This code is not validated and mostly contains stubs as the main point
was to achieve compilation and estimate the effort required for the
port. Some of the trivial logic has been implemented though.
Issue: #3544
Signed-off-by: Stanislaw Kardach <kda@semihalf.com>

i#3544 RISC-V, part 3: Add sample stubs

---

core/CMakeLists.txt
make/DynamoRIOConfig.cmake.in

Switches to dynamorio_static_unhide for configuring static DR so
that DR's symbols are visible when building static binaries.
Various symbols in dynamorio_static, like d_r_safe_read and
safe_read_if_fast in core/unix/os.c are non-weak symbols, but
they are not exported by the static DR library because we use
`--localize_hidden` during build.
$ nm --defined ../../lib64/debug/libdynamorio_static.a | grep d_r_safe_read
00000000002962e8 t d_r_safe_read
$ nm --defined ../../lib64/debug/libdynamorio_static.a | grep safe_read_if_fast
0000000000296272 t safe_read_if_fast
This causes drlibc code to use the wrong routines in is_elf_so_header.
The same would happen for other weakly linked routines in drlibc which
are actually supposed to be suppressed by their respective DR
definitions.
There's an …

i#5570: Use unhide variant for linking DR statically

---

core/arch/aarch64/proc.c
core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect
suite/tests/api/ir_aarch64_v82.c

This patch fixes current implementations of the floating-point fused
multiply-add/subtract long to/from accumulator instructions.
```
FMLAL <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tb>
FMLAL2 <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tb>
FMLSL <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tb>
FMLSL2 <Vd>.<Ta>, <Vn>.<Tb>, <Vm>.<Tb>
```
Issue: #2626

i#2626: AArch64 v8.2 codec: fix FMLAL/FMLSL instructions

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/histogram_test.cpp
clients/drcachesim/tests/memref_gen.h
clients/drcachesim/tools/histogram.cpp
clients/drcachesim/tools/histogram.h

Augments the histogram drcachesim tool to count every line a
cross-line access touches.  Previously it would incorrectly only
consider the first line.
Adds a test with synthetic test cases.

Add cross-line counting to histogram tool

---

core/CMakeLists.txt
make/DynamoRIOConfig.cmake.in
suite/tests/CMakeLists.txt

Renames dynamorio_static_nohide to dynamorio_static and deprecates
the version where we hide DR symbols using hide_symbols.
Removes tobuild_static_nohide_api, since now all static DR builds use
the nohide variant.
Documents hide_symbols as unsafe because it may lead to
confusing linking behavior.
Issue: #5570, #3348

i#5570: Make nohide the default for static DR

---

core/arch/aarch64/proc.c
core/ir/aarch64/codec.c
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/ir_aarch64_v82.c

This patch adds the following decodes, encoding macros
and appropriate tests for both
```
SM3PARTW1 <Sd>.4S, <Sn>.4S, <Sm>.4S
SM3PARTW2 <Sd>.4S, <Sn>.4S, <Sm>.4S
SM3SS1  <Sd>.4S, <Sn>.4S, <Sm>.4S, <Sa>.4S
SM3TT1A <Sd>.4S, <Sn>.4S, <Sm>.S[<index>]
SM3TT1B <Sd>.4S, <Sn>.4S, <Sm>.S[<index>]
SM3TT2A <Sd>.4S, <Sn>.4S, <Sm>.S[<index>]
SM3TT2B <Sd>.4S, <Sn>.4S, <Sm>.S[<index>]
SM4E    <Sd>.4S, <Sn>.4S
SM4EKEY <Sd>.4S, <Sn>.4S, <Sm>.4S
```
Issue: #2626

i#2626: AArch64 v8.2 codec: Add SM3/4 instructions

---

core/arch/aarch64/proc.c
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

This patch  adds the following decodes, encoding macros
and appropriate tests for both
BCAX    <Bd>.16B, <Bn>.16B, <Bm>.16B, <Ba>.16B
EOR3    <Bd>.16B, <Bn>.16B, <Bm>.16B, <Ba>.16B
ESB
PSB
These instructions are part of features that have not
yet been added, so BASE has been used as a placeholder
where appropriate
Issue: #2626

i#2626: AArch64 v8.2 codec: Add BCAX, EOR3, P/ESB instructions

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

This patch adds half-precision FP arithmetic and conversion
instructions extending support of full-precision variants in v8.0.
```
FSQRT   <Hd>.<Ts>, <Hn>.<Ts>
FSQRT   <Hd>, <Hn>
SCVTF   <Hd>.<Ts>, <Hn>.<Ts>
SCVTF   <Hd>, <Wn>
SCVTF   <Hd>, <Xn>
SCVTF   <Hd>, <Hn>
SCVTF   <Hd>, <Wn>, #<imm>
SCVTF   <Hd>, <Xn>, #<imm>
UCVTF   <Hd>.<Ts>, <Hn>.<Ts>
UCVTF   <Hd>, <Wn>
UCVTF   <Hd>, <Xn>
UCVTF   <Hd>, <Wn>, #<imm>
UCVTF   <Hd>, <Xn>, #<imm>
UCVTF   <Hd>, <Hn>
```
Also adds bit manipulation instructions new in v8.2:
```
RAX1    <Dd>.2D, <Dn>.2D, <Dm>.2D
XAR     <Dd>.2D, <Dn>.2D, <Dm>.2D, #<imm>
```
Issue: #2626

i#2626: AArch64 v8.2 codec: add FSQRT, FP convert instructions

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/ir/aarch64/codec_v82.txt

The Reliability, Availability, and Serviceability (RAS) extension and
Statistical Profiling Extension (SPE) feature checks are required for
v8.2 instructions ESB and PSB. Hardware support for these read from
registers ID_AA64PFR0_EL1 and ID_AA64DFR0_EL1.
Issues: #5475, #2626

i#5475 Add RAS and SPE feature checks for AArch64 v8.2

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/disassemble.c
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

This patch updates the following decodes, encoding macros
and appropriate tests for both. It also aligns the fccm*
instructions with the ccm* instructions, it hoists the
condition to the mnemonic and designates it as a
predicate.
```
FCCMP   <Dn>, <Dm>, #<imm>, <cond>
FCCMP   <Hn>, <Hm>, #<imm>, <cond>
FCCMP   <Sn>, <Sm>, #<imm>, <cond>
FCCMPE  <Dn>, <Dm>, #<imm>, <cond>
FCCMPE  <Hn>, <Hm>, #<imm>, <cond>
FCCMPE  <Sn>, <Sm>, #<imm>, <cond>
FCMP    <Dn>, #0.0
FCMP    <Hn>, #0.0
FCMP    <Sn>, #0.0
FCMP    <Dn>, <Dm>
FCMP    <Hn>, <Hm>
FCMP    <Sn>, <Sm>
FCMPE   <Dn>, #0.0
FCMPE   <Hn>, #0.0
FCMPE   <Sn>, #0.0
FCMPE   <Dn>, <Dm>
FCMPE   <Hn>, <Hm>
FCMPE   <Sn>, <Sm>
```
Issue: #2626

i#2626: AArch64 v8.2 codec: Add fccmp/e fcmp/e instructions

---

.clang-format
clients/drcachesim/CMakeLists.txt
clients/drcachesim/tracer/instr_counter.cpp
clients/drcachesim/tracer/instr_counter.h
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/output.h
clients/drcachesim/tracer/tracer.cpp
clients/drcachesim/tracer/tracer.h

Separates out two big pieces of tracer.cpp into their own files:
instruction counting into instr_counter.cpp and i/o into output.cpp.
Both still have some dependencies on some of the same TLS and globals
as the rest of the tracer, but shrinking the tracer.cpp file is still
of value, and the interfaces between the files are not huge.  Future
work could further modularize and isolate.
Adds a namespace, especially important now that we have global symbols
shared between files.
Issue: #5560, #4343

i#5560 drmemtrace refactor: Split counting + i/o code

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

This patch adds half-precision FP conversion instructions extending
support of full-precision variants in v8.0.
```
FCVTMU  <Hd>.<Ts>, <Hn>.<Ts>
FCVTNU  <Hd>.<Ts>, <Hn>.<Ts>
FCVTZS  <Hd>.<Ts>, <Hn>.<Ts>
FCVTZS  <Wd>, <Hn>
FCVTZS  <Xd>, <Hn>
FCVTZS  <Wd>, <Hn>, #<fbits>
FCVTZS  <Xd>, <Hn>, #<fbits>
FCVTZS  <Hd>, <Hn>
FCVTZU  <Hd>.<Ts>, <Hn>.<Ts>
FCVTZU  <Wd>, <Hn>
FCVTZU  <Xd>, <Hn>
FCVTZU  <Wd>, <Hn>, #<fbits>
FCVTZU  <Xd>, <Hn>, #<fbits>
FCVTZU  <Hd>, <Hn>
```
Issue: #2626

i#2626: AArch64 v8.2 codec: add FCVT instructions

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/disassemble.c
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

This patch updates fcsel so that it sets the condition
parameter as a predicate and joins it to the mnemonic
when printing as debug. Also added are tests and
instr_create macros.
Issue: #2626

i#2626: AArch64 v8.2 codec: Update fcsel to use a predicate

---

.github/workflows/ci-clang-format.yml
api/docs/code_style.dox
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/offline-gencode.templatex
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/tracer.cpp
suite/runsuite.cmake
suite/tests/CMakeLists.txt

Adds a drmemtrace test which generates code outside of any module.
Adds a proper warning about this scenario at level 0 (with a do-once
to avoid spew) to both the tracer and raw2trace (previously it would
silently be traced without any indication of a problem, and the
raw2trace warning was at level 1).
Issue: #2062

i#2062 memtrace nonmod: Add test for generated code

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

This patch corrects the signatures for un-indexed s/udot instructions
and adds the indexed operands as well as instr_create macros and tests.
It affects:
```
SDOT    <Sd>.<Ts>, <Bn>.<Tb>, <Bm>.<Tb>
SDOT    <Sd>.<Ts>, <Bn>.<Tb>, <Bm>.4B[<index>]
UDOT    <Sd>.<Ts>, <Bn>.<Tb>, <Bm>.<Tb>
UDOT    <Sd>.<Ts>, <Bn>.<Tb>, <Bm>.4B[<index>]
```
Issue: #2626

i#2626: AArch64 v8.2 codec: Fix s/udot operands and add missing variants

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_v82.c

```
*    FMULX   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
*    FMULX   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
*    FMOV    <Wd>, <Hn>
*    FMOV    <Xd>, <Hn>
*    FMULX   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.H[<index>]
*    FMULX   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Tb>[<index>]
*    FMULX   <Hd>, <Hn>, <Hm>.H[<index>]
*    FMULX   <V><d>, <V><n>, <Sm>.<Ts>[<index>]
*    FMULX   <Hd>, <Hn>, <Hm>
*    FMULX   <V><d>, <V><n>, <V><m>
*    FMLSL/2   <Sd>.<T>, <Hn>.<Tb>, <Hm>.H[<imm>]
```
It also tidies up some of the ir tests by adding a
macro to implement the testing loops and making sure
that all failures are printed
Issues: #2626

i#2626: AArch64 v8.2 codec: add missing fmov and fmulx variants

---

core/lib/mcxtx_api.h

RISC-V does not have condition codes. Instead all conditional branches
are arithmetic register comparison based and those are also used for
overflow checking.
Therefore remove the xflags field so that client code does not use it by
mistake.
Issue #3544
Signed-off-by: Stanislaw Kardach <kda@semihalf.com>

i#3544 RISC-V, part 7: remove xflags

---

core/arch/arch.c
core/ir/decode.h
core/ir/riscv64/decode.c
core/ir/riscv64/decode_private.h
core/ir/riscv64/disassemble.c
core/ir/riscv64/encode.c
core/ir/riscv64/ir_utils.c
core/lib/globals_api.h

Add stubs to get the IR related code to compile. Most of the code is
non-functional, with exception of the register name list.
Issue: #3544
Signed-off-by: Stanislaw Kardach <kda@semihalf.com>

i#3544 RISC-V, part 8: Add core/ir stubs

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

```
FACGE   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FACGE   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FACGE   <Hd>, <Hn>, <Hm>
FACGE   <V><d>, <V><n>, <V><m>
FACGT   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FACGT   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FACGT   <Hd>, <Hn>, <Hm>
FACGT   <V><d>, <V><n>, <V><m>
FADDP   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FADDP   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FADDP   <Hd>, <Hn>.2H
FADDP   <V><d>, <Sn>.<Ts>
FCMEQ   <Hd>.<Ts>, <Hn>.<Ts>, #0
FCMEQ   <Dd>.<Ts>, <Dn>.<Ts>, #0
FCMEQ   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FCMEQ   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FCMEQ   <Hd>, <Hn>, #0
FCMEQ   <V><d>, <V><n>, #0
FCMEQ   <Hd>, <Hn>, <Hm>
FCMEQ   <V><d>, <V><n>, <V><m>
FCMGT   <Hd>.<Ts>, <Hn>.<Ts>, #0
FCMGT …
```

i#2626: AArch64 v8.2 codec: Add missing fac/fad/fcm variants

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

```
FMAXNMP <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FMAXNMP <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FMAXNMP <Hd>, <Hn>.2H
FMAXNMP <V><d>, <Sn>.<Ts>
FMAXP   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FMAXP   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FMAXP   <Hd>, <Hn>.2H
FMAXP   <V><d>, <Sn>.<Ts>
FMINNMP <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FMINNMP <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FMINNMP <Hd>, <Hn>.2H
FMINNMP <V><d>, <Sn>.<Ts>
FMINNMV <Hd>, <Hn>.<Ts>
FMINNMV <Sd>, <Sn>.4S
FMINP   <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FMINP   <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FMINP   <Hd>, <Hn>.2H
FMINP   <V><d>, <Sn>.<Ts>
```
Issues: #2626

i#2626: AArch64 v8.2 codec: Add missing fmax/fmin variants

---

core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_v82.c

```
FMLA    <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FMLA    <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FMLA    <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.H[<index>]
FMLA    <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Tb>[<index>]
FMLA    <Hd>, <Hn>, <Hm>.H[<index>]
FMLA    <V><d>, <V><n>, <Sm>.<Ts>[<index>]
FMLAL   <Sd>.<Ts>, <Hn>.<Tb>, <Hm>.<Tb>
FMLAL   <Sd>.<Ts>, <Hn>.<Tb>, <Hm>.H[<index>]
FMLAL2  <Sd>.<Ts>, <Hn>.<Tb>, <Hm>.<Tb>
FMLAL2  <Sd>.<Ts>, <Hn>.<Tb>, <Hm>.H[<index>]
FMLS    <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FMLS    <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FMLS    <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.H[<index>]
FMLS    <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Tb>[<index>]
FMLS    <Hd>, <Hn>, <Hm>.H[<index>]
FMLS    <V><d>, <V><n>, <Sm>.<Ts>[<index>]
```
Issues: #2626

i#2626: AArch64 v8.2 codec: correct fml* instrs

---

core/ir/aarch64/codec_v82.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v82.c

```
FRECPE  <Hd>.<Ts>, <Hn>.<Ts>
FRECPE  <Dd>.<Ts>, <Dn>.<Ts>
FRECPE  <Hd>, <Hn>
FRECPE  <V><d>, <V><n>
FRECPS  <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FRECPS  <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FRECPS  <Hd>, <Hn>, <Hm>
FRECPS  <V><d>, <V><n>, <V><m>
FRSQRTE <Hd>.<Ts>, <Hn>.<Ts>
FRSQRTE <Dd>.<Ts>, <Dn>.<Ts>
FRSQRTE <Hd>, <Hn>
FRSQRTE <V><d>, <V><n>
FRSQRTS <Hd>.<Ts>, <Hn>.<Ts>, <Hm>.<Ts>
FRSQRTS <Dd>.<Ts>, <Dn>.<Ts>, <Dm>.<Ts>
FRSQRTS <Hd>, <Hn>, <Hm>
FRSQRTS <V><d>, <V><n>, <V><m>
```
Issues: #2626

i#2626: AArch64 v8.2 codec: Add h variants for frecpe/s and frsqrte/s

---

api/docs/API.doxy
api/docs/deployment.dox
core/lib/dr_config.h
core/lib/dr_events.h

Fixes several errors raised by Doxygen 1.9.4:
+ Adds escapes to quotes which caused parsing to miss a \param.
+ Removes \return directives on void functions.
+ Removes a deprecated Doxyfile parameter.
+ Moves a nested list higher up to fix what looks like a bug
in the Doxygen parser: I found no other explanation.
Tested manually on 1.9.4.
Fixes #5615

i#5615: Fix Doxygen 1.9.4 build

---

api/docs/release.dox
clients/CMakeLists.txt
clients/drcachesim/common/trace_entry.h
clients/drcachesim/reader/file_reader.h
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/burst_replaceall.cpp
clients/drcachesim/tests/offline-gencode.templatex
clients/drcachesim/tracer/drmemtrace.h
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/raw2trace_directory.cpp
clients/drcachesim/tracer/raw2trace_directory.h
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Augments drmemtrace to emit the instruction encodings for non-module
code while tracing.  The instru_offline_t class emits them into a
global buffer and from there into a new file in the raw/ subdirectory.
Encodings are obtained by encoding each app or emulated instruction in
the block.
Adds a new drmemtrace interface function
drmemtrace_get_encoding_path() to obtain the path to the file where
the encodings are stored.  Adds a sanity check that the file exists to
the gencode test.
The file reader and raw2trace_directory_t are updated to be aware of
the encoding file.
Raw2trace support for parsing the encoding file will be added in a
separate commit to keep things small and incremental.
Issue: #2062

i#2062 memtrace nonmod: Emit encodings for non-module code

---

api/docs/release.dox
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/tests/burst_aarch64_sys.cpp
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/burst_replace.cpp
clients/drcachesim/tests/burst_traceopts.cpp
clients/drcachesim/tests/offline-gencode.templatex
clients/drcachesim/tests/raw2trace_io.cpp
clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tools/opcode_mix.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/raw2trace_launcher.cpp
core/unix/signal.c
suite/tests/CMakeLists.txt

Adds raw2trace parsing of the encoding file used by the tracer to
store instruction encodings for generated code.  This involves the
following changes:
+ Adds encoding file parsing to module_mapper_t.
+ Changes module map queries to use new module_mapper_t interfaces instead,
which handle generated code.
+ Changes block lookup to use the modidx,modoffs pair as the key rather than
the absolute pc.
The changes are compatibility-breaking for raw2trace_t which now takes
an encoding file parameter in the middle of existing parameters.
Updates existing uses.
For module_mapper_t the encoding file is added last with a default
value to preserve compatibility for existing analysis tools like
opcode_mix and view.  It is assumed that encodings for generated code
will be added to the final trace file …

i#2062 memtrace nonmod part 2: Raw2trace parsing of encoding file

---

clients/drcachesim/tests/burst_gencode.cpp
core/unix/os.c

In standalone mode after a detach with -satisfy_w_xor_x, an overactive
assert is hit.  We relax it here.
Augments the tool.drcacheoff.gencode test to cover this case.
Fixes #5621

i#5621: Fix fdtable assert in standalone mode

---

suite/tests/linux/clone.c

Accepts EINVAL as a valid response from clone3 even if SYS_clone3
is not defined by glibc. This is to avoid incorrectly failing the
test on systems where the kernel supports clone3 but glibc version
doesn't define the SYS_clone3 constant.
Fixes: #5629

i#5629: Fix expected output in linux.clone test.

---

clients/drcachesim/common/archive_ostream.h
clients/drcachesim/common/gzip_ostream.h
clients/drcachesim/common/zipfile_ostream.h

Cleans up the drmemtrace i/o classes by removing redundant "virtual"
keywords and adding missing "explicit" constructor qualifiers.
Issue: #5538

i#5538 memtrace seek, part 2: Remove redundant "virtual" keywords

---

clients/drcachesim/reader/compressed_file_reader.cpp
clients/drcachesim/reader/compressed_file_reader.h
clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/reader/zipfile_file_reader.h

Adds buffering to the zipfile reader, which eliminates the 60% slowdown it showed compared to our gzip reader and in fact results in faster read times than the gzip reader.
Adds similar buffering to the gzip reader, which results in an 18% speedup and matches the new zipfile speed.
Issue: #5538

i#5538 memtrace seek, part 3: Add reader buffering

---

clients/drcachesim/tests/heap_test.cpp
clients/drcachesim/tools/invariant_checker.h
core/unix/signal.c

Fixes 3 warnings reported by gcc 12.1.
One is an actual bug but looks like it would not have had any impact.

Fix compiler warnings on gcc 12.1

---

core/ir/x86/decode.c
suite/tests/api/ir_x86.c

x86 allows multiple prefixes to be present on an instruction. Although not documented in the Intel SDM, empirical testing shows that the last rep/repne prefix "wins", since it makes no sense for both prefixes to be present. Since these prefixes are used at times to select between instructions (e.g. anything with PREFIX_EXT in the decoder table) faithfully replicating this behavior is important to ensure that byte sequences with unnecessary leading prefixes are correctly decoded.
Fixes #5645
Fixes #5447

i5645: Make the last rep/repne prefix "win"

---

ext/drutil/drutil.c
suite/tests/client-interface/stolen-reg-index.dll.c

The fix in PR #5511 for drutil_insert_get_mem_addr() on a w28 index register failed to use the application value in a temp register and resulted in an incorrect recorded address.  The test added in that PR failed to actually check the value and so failed to catch the error.
Here we augment the test to check the value by passing the recorded address and the operand to a clean call.  This new test fails for the w28 case.  With the included fix, it now passes.
Fixes #5498

i#5498: Fix drutil_insert_get_mem_addr for w28 index

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Clarifies that the string parameter to report_to_false is supposed to be the invariant name.

Rename formal parameter to report_to_false.

---

api/docs/release.dox
core/dynamo.c
core/globals.h
core/lib/dr_events.h
core/lib/instrument.c
core/lib/instrument.h
core/synch.c
core/unix/loader.c
core/unix/os.c
suite/tests/api/startstop.c
suite/tests/api/startstop.expect
suite/tests/api/static_prepop.c
suite/tests/api/static_prepop.expect
suite/tests/client-interface/attach_blocking.expect
suite/tests/client-interface/attach_test.dll.c
suite/tests/client-interface/attach_test.template
suite/tests/client-interface/events.dll.c

Adds two new DR events: post-attach and pre-detach.  These help tools align instrumentation with points where all threads are under DR control, avoiding uneven thread execution during the incremental staggered attach and detach processes.
Adds some sanity tests that the events are called where they should be.  Adding them to drmemtrace will be done separately.
Issue: #2039

i#2039 trace trim, part 1: Add post-attach and pre-detach events

---

api/docs/debugging.dox
core/lib/globals_shared.h
core/unix/nudgesig.c
core/unix/os.c
core/unix/os_private.h
core/unix/signal.c
core/unix/signal_linux_x86.c
libutil/dr_config.c
suite/tests/api/detach_signal.cpp
tools/nudgeunix.c

Switches the signal DR uses to suspend threads from SIGSTKFLT, which is not supported in gdb, to SIGPWR.  SIGPWR is similarly obscure and never used on Linux, but is supported by gdb, and does not cause QEMU to fail.
Fixes #5651

i#5651: Switch DR's suspend signal to SIGILL with sigqueueinfo

---

core/arch/aarch64/proc.c

Looks like typo in 'if' condition. Extend threshold to AA64MMFR1

Fix typo for "Add FEATURE_LOR for AArch64 v8.1"

---

core/arch/mangle_shared.c
core/unix/rseq_linux.c
suite/tests/CMakeLists.txt
suite/tests/linux/rseq.c

Adds support for multiple app copies in rseq mangling finalization's search for labels to fill in code cache PC's.
Adds support for multiple rseq regions in one fragment_t by expanding the stored rseq_cs per fragment to become a list.
Adds "-trace_after_instrs 5K" to the tool.drcacheoff.rseq test to exercise rseq with drbbdup.
Augments the attach/detach api.rseq test to use drmemtrace, which with the forthcoming #2039 mode switches also hits this multi-rseq case.
Fixes #5659

i#5659: Handle multiple app copies in rseq mangling

---

core/arch/interp.c
core/arch/mangle_shared.c

Fixes PR #5663 which fixed drreg restoration for drbbdup but broke it for non-drbbdup.  bb->instr was NULL so the preinsert was an append, and the label as the last instruction moved the drreg restore point to after the native sequence!
Here, we explicitly append to avoid confusion, and we move the native sequence to the point of the barrier instead of at the final app instr, which is where the registers are actually native.
Tested on larger apps using rseq which reliably crashed without this fix.  This fix also seems to fully fix drbbdup usage with drmemtrace for #2039.
Issue: #5658, #2039

i#5658 rseq drreg: Put native sequence by barrier

---

clients/drcachesim/drcachesim.dox.in

Adds explicit mention of the encoding_is_new field to the memtrace format docs.
Updates the Core Simulation section: mentions encodings again, and removes the stale module_mapper paragraph.
Issue: #5520

i#5520 memtrace encodings: Clarify docs on encodings

---

suite/tests/CMakeLists.txt

Resolves a gcc 12.2 compiler warning in release build on the client.exception.dll target.

Fix gcc 12.2 compiler warning

---

clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h

Adds a check that the memref.instr.encoding_is_new flag is valid in the basic_counts tool.
Issue: #5520

i#5520 memtrace encodings: Access field behind flag when counting

---

core/ir/aarch64/instr_create_api.h
suite/tests/CMakeLists.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c
suite/tests/api/ir_aarch64_sve.expect
suite/tests/api/sort-dis-a64.py

This patch creates a new file for SVE disassembly tests and another ir_aarch64 test file. Also included is a small bug fix for the disassembly test sorter that could remove a test if the file did not end in a new line.
issues: #3044

i#3044: Split out SVE instruction test files

---

api/docs/release.dox
clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/burst_replaceall.cpp
clients/drcachesim/tests/offline-burst_replaceall.templatex
clients/drcachesim/tracer/drmemtrace.h
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/tracer.cpp
clients/drcachesim/tracer/tracer.h
suite/tests/CMakeLists.txt

Adds drmemtrace_replace_file_ex_ops() with an expanded file opening function which takes in the thread id and window id, to better support the external file opener with delayed opens due to nop mode and windows.
Adds a test of the function to burst_replaceall.  Adds additional threads to the test and checks that the tid for each thread was seen.
Issue: #2039

i#2039 trace trim, part 2: Add open_file with tid

---

clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/drcachesim.dox.in
clients/drcachesim/simulator/analyzer_interface.cpp
clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/opcode_mix.templatex
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Adds a new option -instr_encodings which enables instruction encoding records for online traces.  This is under this off-by-default option as it adds significant overhead to online tracing and is only needed for some tools.
Updates the launcher and docs.
Adds an online opcode_mix test and adds encodings to a basic_counts online test.
Manually tested the view tool with and without -instr_encodings:
$ bin64/drrun -t drcachesim -instr_encodings -simulator_type view -- suite/tests/bin/allasm_x86_64
...
166: T1718245 ifetch       4 byte(s) @ 0x0000000000401028 48 83 eb 01          sub    $0x0000000000000001 %rbx -> %rbx
167: T1718245 ifetch       4 byte(s) @ 0x000000000040102c 48 83 fb 00          cmp    %rbx $0x0000000000000000
168: T1718245 ifetch       2 byte(s) @ 0x0000000000401030 75 d9 …

i#5520 memtrace encodings: Add online encodings

---

clients/drcachesim/tests/drstatecmp-delay-simple.templatex
clients/drcachesim/tests/offline-drstatecmp-delay-simple.templatex
ext/drstatecmp/drstatecmp.c
suite/tests/CMakeLists.txt

Checks for block truncation in drstatecmp so it can use the post-app2app ilist instead of incorrectly using the untruncated version in its state comparison.
Adds a test of drcachesim offline that fails with a false positive without this fix.
Fixes #5683

i#5683: Detect bb truncation in drstatecmp

---

clients/drcachesim/docs/drcachesim.dox.in

We have perma-links to redirect our html pages to the root directory, but other files are in the docs/ directory.
Issue: #5520

i#5520 memtrace encodings: Fix pdf path

---

core/lib/dr_events.h
core/lib/instrument.c

instrument_restore_nonfcache_state_prealloc() was creating a dr_restore_state_info_t structure but leaving its fragment_info.ilist field unintialized.  We fix that here.
Tested on the forthcoming drbbdup state restore event (#5686) which crashed walking the bogus ilist without this fix.
Fixes #5688

i#5688: Fix uninitialized state restore field

---

core/drlibc/drlibc_unix.c
core/os_shared.h
core/unix/signal.c
suite/tests/tools.h

SIGSTKSZ and MINSIGSTKSZ are moving away from being constants. SIGSTKSZ is now a call to sysconf().
This was causing a build error building our tests, which is fixed using the suggestion from Stanislaw Kardach.
For the core, we eliminate the constants to avoid invoking libc.  We look for AT_MINSIGSTKSIZE in our existing auxv search code and if not found we fall back to a hardcoded value.
Co-authored-by: Stanislaw Kardach <kda@semihalf.com>
Fixes #5434

i#5434: Remove reliance on SIGSTKSZ and related defines

---

core/ir/x86/decode_table.c
suite/tests/api/ir_x86_4args_avx512_evex_mask_C.h

The EVEX-prefixed vsqrtss/vsqrtsd entries should take three-quarter and half width merge operands respectively, like their VEX-prefixed counterparts.
This was an oversight when I wrote #4739.

Fix EVEX-prefixed vsqrtss/vsqrtsd merge operand sizes

---

clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tracer/instru_offline.cpp

Default initialization produces DR_ASSERT each time because drmgr_get_emulated_instr_data retruns false in this case
```
...
} else if (drmgr_is_emulation_start(instr)) {
bool ok = drmgr_get_emulated_instr_data(instr, &emulation_info);
DR_ASSERT(ok);
...
```
```
DR_EXPORT
bool
drmgr_get_emulated_instr_data(instr_t *instr, emulated_instr_t *emulated)
{
ASSERT(instr_is_label(instr), "emulation instruction does not have a label");
ASSERT(drmgr_is_emulation_start(instr), "instruction is not a start emulation label");
if (emulated->size < offsetof(emulated_instr_t, flags))
return false;
...
```

Add initialization of emulation_info to exclude unavoidable DR_ASSERT.

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/tests/burst_replace.cpp
clients/drcachesim/tests/burst_threads.cpp
clients/drcachesim/tests/offline-burst_replace.templatex
clients/drcachesim/tests/offline-burst_threads_counts.templatex
clients/drcachesim/tracer/instr_counter.cpp
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/tracer.cpp
clients/drcachesim/tracer/tracer.h
suite/tests/CMakeLists.txt

Adds a new drbbdup mode to drmemtrace which performs zero instrumentation (except drwrap cleanup).  This mode is used when attaching for the period prior to full control of all threads and when detaching prior to starting to let threads go native, to avoid uneven thread instrumentation during these incremental staggered processes. The mode is initially under an off-by-default new option -align_endpoints while drbbdup stability is being worked on (i#5686).
Threads that did nothing during the trace-mode period are now omitted from the trace.
Adds a test by adding 4 idle threads to burst_threads and ensuring they do not show up in the trace.
Alignment itself was tested manually by running larger applications and analyzing the timestamp ranges in the trace.
Fixes the burst_replace test to …

i#2039 trace trim, part 3: Add nop mode to drmemtrace

---

core/arch/mangle_shared.c
suite/tests/linux/rseq.c

If SP is written inside an rseq region, DR was trying to save and restore it like a regular GPR, which fails.  We have to go through a scratch register.
Adds a test that reproduces an encoding failure with this fix.
Fixes #5705

i#5705: Add handling of written SP in rseq regions

---

core/module_list.c

It is useful to have the full module path in debug case.
For example, if we have some issue in address in basic block we could try to map it on source code (addr2line tool) to investigate the issue.

Add full module path in debug log

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tracer/raw2trace.cpp

Adds an invariant check that chunk boundaries contain the proper number of instructions.
Fixes off-by-one errors in chunk counts due to not checking at end-of-loop, found by visual inspection (with a local view tool that prints instr counts; that will be committed later) and confirmed to break this new check without the fix in the
tool.drcacheoff.invariant_checker test.
Issue: #5538

i#5538 memtrace seek, part 4: Check chunk boundaries

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect
suite/tests/api/ir_aarch64_sve.c

```
SQADD   <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>, <shift>
SQADD   <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SQSUB   <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>, <shift>
SQSUB   <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SUB     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
SUB     <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>, <shift>
SUB     <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SUBR    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
SUBR    <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>, <shift>
UQADD   <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>, <shift>
UQADD   <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
UQSUB   <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>, <shift>
UQSUB   <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
```
issues: #3044

i#3044: AArch64 sve codec: add sqadd, sqsub, sub, subr, uqadd and uqsub

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/analyzer_multi.h
clients/drcachesim/common/trace_entry.h
clients/drcachesim/common/utils.h
clients/drcachesim/common/zipfile_istream.h
clients/drcachesim/common/zipfile_ostream.h
clients/drcachesim/reader/file_reader.h
clients/drcachesim/tests/burst_aarch64_sys.cpp
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/burst_replace.cpp
clients/drcachesim/tests/burst_traceopts.cpp
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/raw2trace_io.cpp
clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/raw2trace_directory.cpp
clients/drcachesim/tracer/raw2trace_directory.h
clients/drcachesim/tracer/raw2trace_launcher.cpp

Adds two new files generated by raw2trace, each containing 4-entry records of <tid, timestamp, cpuid, instr_count>.  These are used to take a global or per-cpu target instruction count and determine the corresponding instruction count within each software thread, for seeking within each trace file.  One file is globally sorted by timestamp, and the other is a zip file with a separate component for each cpuid holding entries sorted by timestamp for that cpu.
Adds new invariant_checker tests for each file by passing them in for test_mode.  The invariant_checker re-constructs the same sorted sequences using the trace data and confirms it matches the data in the files.  This involves adding a new zipfile_stream_t interface for a simple continuous stream of each zipfile component in turn. …

i#5538 memtrace seek, part 5: Add schedule index files

---

clients/drcachesim/tracer/raw2trace.h

Adds a missing piece from part 5 PR #5713 where raw2trace's thread_data_ was indirected to support a subclass extending it. However, its destructor was not virtual, which prevented such extension.  We address that here.
Issue: #5538

i#5538 memtrace seek, part 6: Virtualize raw2trace_thread_data

---

clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/tests/warmup-valid.templatex

Fixes a bug where drcachesim under-counts warmup_refs and ignores the warmup completely if it is an even number due to incorrectly calling the checking routine when it should just check the warmed-up state flag.
Updates the warmup template to require non-zero icache warmup misses (before it allowed any values including zero) to properly fail without this fix.
Fixes #5716

i#5716: Fix ignored warmup_refs

---

suite/tests/client-interface/drbbdup-empty-bb-test.asm
suite/tests/client-interface/drbbdup-meta-label-bb-test.asm
suite/tests/client-interface/drbbdup-meta-nop-bb-test.asm

Replaces the incorrect "main" with "_start" in the bbdup asm tests to eliminate a linker warning.
Fixes #5722

i#5722: Fix linker warning on bbdup asm

---

api/docs/building.dox

2019 is not needed and x64 was inside the G flag

Another adjustment to the documentation

---

clients/drcachesim/tracer/output.cpp

On java examples we have double calling thread exit callbacks but data->file could be already closed.
Write file operation is fail on write attempt and it is asserted.

Exclude 2nd write on 2nd thead exit call

---

.gitignore
core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
FEXPA   <Zd>.<Ts>, <Zn>.<Ts>
FTMAD   <Zdn>.<Ts>, <Zdn>.<Ts>, <Zm>.<Ts>, #<imm>
FTSMUL  <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
FTSSEL  <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
```
Issue: #3044

i#3044: AArch64 SVE codec: add FTMAD,FTSMUL,FTSSEL,FEXPA

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
MAD     <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
MLA     <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>
MLS     <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>
MSB     <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
MUL     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
MUL     <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>
SMULH   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
UMULH   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
```
issues: #3044

i#3044: AArch64 sve codec: add mad, mla, mls, msb, mul, smulh and umulh

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/common/trace_entry.cpp
clients/drcachesim/reader/compressed_file_reader.cpp
clients/drcachesim/reader/file_reader.cpp
clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/record_file_reader.cpp
clients/drcachesim/reader/snappy_file_reader.cpp
clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Updates numerous diagnostics to use the string name instead of just the enum value for trace entry types.

Use trace entry string names in diagnostics

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
ABS     <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
CNOT    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
NEG     <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
SABD    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
SMAX    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
SMAX    <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>
SMIN    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
SMIN    <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>
UABD    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
```
issues: #3044

i#3044: AArch64 sve codec: add abs, cnot, neg, sabd, smax, smin and uabd

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
FACGE   <Pd>.<Ts>, <Pg>/Z, <Zn>.<Ts>, <Zm>.<Ts>
FACGT   <Pd>.<Ts>, <Pg>/Z, <Zn>.<Ts>, <Zm>.<Ts>
```
issue: #3044

i#3044 AArch64 SVE codec: add FACGE, FACGT

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
SDIV    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
SDIVR   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
UDIV    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
UDIVR   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
UMAX    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
UMAX    <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>
UMIN    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
UMIN    <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>
```
issues: #3044
Change-Id: Ided8f402c6e8b897a48d32e9151954fb29e68d80

i#3044: AArch64 SVE codec: add SDIV/R, UDIV/R, UMAX and UMIN

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/ir/aarch64/codec.c
core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect

This patch adds the appropriate macros, tests and codec entries to encode the following:
LDAPR <Wt>, [<Xn|SP> {,#0}]
LDAPR <Xt>, [<Xn|SP> {,#0}]
LDAPRB <Wt>, [<Xn|SP> {,#0}]
LDAPRH <Wt>, [<Xn|SP> {,#0}]
It also adds FEATURE_LRCPC which introduces these 3 instructions supporting the weaker release consistency processor consistent (RCpc) model that enables the reordering of a store-Release followed by a load-acquire to a different address.
Issues: #5744, #4847

i#5744: AArch64 codec: adds LDAPR, LDAPRB, LDAPRH

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
SXTB    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
SXTH    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
SXTW    <Zd>.D, <Pg>/M, <Zn>.D
UXTB    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
UXTH    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
UXTW    <Zd>.D, <Pg>/M, <Zn>.D
```
issues: #3044

i#3044: AArch64 SVE codec: add SXTB, SXTH, SXTW, UXTB, UXTH and UXTW

---

suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c
suite/tests/api/ir_aarch64_v81.c
suite/tests/api/ir_aarch64_v82.c

This patch modifies the testing macros to reduce the need to
instantiate variables in each test.
It also predefines some lists of registers that are commonly
used
issues: #4393

i#4393: AArch64 decode: Reduce boilerplate for IR tests

---

clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/tracer.cpp

Part 4 added a minimum timestamp, but it only works for data that is not actually emitted until we are fully attached.  For data emitted before that point, we'll use a too-early timestamp.  We solve that here by dropping such data.
Tested on a large app where these changes solve gaps at the start of the trace due to an early timestamp in one thread.
Issue: #2039

i#2039 trace trim, part 5: Drop early data

---

make/package.cmake
suite/runsuite.cmake

Works around issues with strawberry perl zlib on GA CI package builders by disabling zlib by setting AUTOMATED_TESTING for package builds, just like we're doing for testing on GA CI.
Issue: #5767

i#5767: Disable zlib on windows package builds

---

api/docs/debug_memtrace.dox
clients/drcachesim/tracer/output.cpp

Fixes an issue with refreshing the timestamp when filtering is on where the first (extended) header flag was cleared on a filter-discarded buffer.
Tested by running "ctest -V --repeat-until-fail 100 -R burst_threadL0filter". Previously it failed on the 3rd test; now all 100 pass.
Issue: #2039

i#2039 trace trim, part 7: Fix filtered refresh

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter.h

Fixes a race in updating input_entry_count_ and output_entry_count_
in parallel_shard_exit in the record_filter analyzer.
Moves aggregation logic to print_results instead. Like other analyzers,
we now keep track of all shard data pointers and free them in the
destructor instead. We destroy the writer object in parallel_shard_exit
itself though, for symmetry with how it's created (in parallel_shard_stream_init)
and so that users don't have to destroy the record_filter_t object itself
for output files to be written out.
Issue: #5675

i#5675: Fix data race in record_filter.

---

clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/filter/cache_filter.cpp
clients/drcachesim/tools/filter/cache_filter.h
clients/drcachesim/tools/filter/null_filter.h
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter.h
clients/drcachesim/tools/filter/type_filter.h

Adjusts the trace's file type based on the entries being filtered out.
Removes the const property for the trace_entry_t argument to
parallel_shard_filter, which allows record_filter_func_t to modify the entry.
Tests operation in the record_filter_unit_tests.
Issue: #5675

i#5675 record filter: Adjust trace file type

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c

This patch adds the appropriate macros, tests and codec entries to decode and encode the following instructions:
RDFFR <Pd>.B
RDFFR <Pd>.B, <Pg>/Z
RDFFRS <Pd>.B, <Pg>/Z
SETFFR
WRFFR <Pn>.B
The First Fault register is currently not part of the machine state (mcxtx_api.h). Handling of the FFR in the core and the API will be added in later patches.
Issue: #3044

i#3044: AArch64 SVE codec: add RDFFR[S] SETFFR WRFFR

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c

```
CNTP    <Xd>, <Pg>, <Pn>.<Ts>
DECP    <Xdn>, <Pm>.<Ts>
DECP    <Zdn>.<Ts>, <Pm>.<Ts>
INCP    <Xdn>, <Pm>.<Ts>
INCP    <Zdn>.<Ts>, <Pm>.<Ts>
SQDECP  <Xdn>, <Pm>.<Ts>, <Wdn>
SQDECP  <Xdn>, <Pm>.<Ts>
SQDECP  <Zdn>.<Ts>, <Pm>.<Ts>
SQINCP  <Xdn>, <Pm>.<Ts>, <Wdn>
SQINCP  <Xdn>, <Pm>.<Ts>
SQINCP  <Zdn>.<Ts>, <Pm>.<Ts>
UQDECP  <Wdn>, <Pm>.<Ts>
UQDECP  <Xdn>, <Pm>.<Ts>
UQDECP  <Zdn>.<Ts>, <Pm>.<Ts>
UQINCP  <Wdn>, <Pm>.<Ts>
UQINCP  <Xdn>, <Pm>.<Ts>
UQINCP  <Zdn>.<Ts>, <Pm>.<Ts>
```
issues: #3044

i#3044 AArch64 SVE codec: Add unconstrained predicate count instructions

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
core/ir/opnd_api.h
core/ir/opnd_shared.c
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c
suite/tests/api/opnd-a64.c
suite/tests/api/opnd-a64.expect

```
AND     <Zdn>.<T>, <Zdn>.<T>, #<const>
BIC     <Zdn>.<T>, <Zdn>.<T>, #<const>
EOR     <Zdn>.<T>, <Zdn>.<T>, #<const>
ORN     <Zdn>.<T>, <Zdn>.<T>, #<const>
ORR     <Zdn>.<T>, <Zdn>.<T>, #<const>
```
Issue #3044

i#3044 AArch64 SVE codec: add AND, BIC, EOR, ORN, ORR (imm)

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Fixes two false positives in the drcachesim invariant checker code. Skips the pre-signal instr check when returning from signals that arrived before any other instr in the trace, or before any other instr since the last kernel xfer (nested signals without any intervening instr). In both these cases we don't have any pre-signal instr whose pc we can compare with the post-signal instr.
Note that we still do not handle the back-to-back signals case where the second signal arrives just after the first one returns, without any intervening instruction. Improved the comment for that.
Adds tests that fail without this fix.
Fixes: #5784

i#5784: Fix false positives in invariant checker

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
AND     <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
AND     <Zd>.D, <Zn>.D, <Zm>.D
ANDS    <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
BIC     <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
BIC     <Zd>.D, <Zn>.D, <Zm>.D
BICS    <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
EOR     <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
EOR     <Zd>.D, <Zn>.D, <Zm>.D
EORS    <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
NAND    <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
NANDS   <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
NOR     <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
NORS    <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
NOT     <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
ORN     <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
ORNS    <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
ORR     <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
ORR     <Zd>.D, <Zn>.D, <Zm>.D
ORRS    <Pd>.B, <Pg>/Z, …
```

i#3044 AArch64 SVE codec:  Add predicate logical operations

---

clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
suite/tests/linux/rseq.c

Adds -max_trace_size to api.rseq to avoid generating too much trace data,
which may cause us to run out of disk space. The issue on varying run times
(and therefore trace data) is not reproducing now on the Jenkins machine,
but with this change, the trace size comes down to 512K from 130M+ which
is better.
Fixes an issue in the invariant checker that causes a SIGSEGV crash during
error reporting when there's no shard stream available. This came up in the
tool.drcacheoff.rseq test during the `check_schedule_data` checks that
happen at the very end in `print_results` of the invariant checker, where
we do not have the shard stream anymore. The invariant error itself is yet
to be debugged (i#5734).
Issue: #5733, #5734

i#5733, i#5734: Minor fixes in tests

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c

```
CLASTA <R><dn>, <Pg>, <R><dn>, <Zm>.<T>
CLASTA <V><dn>, <Pg>, <V><dn>, <Zm>.<T>
CLASTA <Zdn>.<T>, <Pg>, <Zdn>.<T>, <Zm>.<T>
CLASTB <R><dn>, <Pg>, <R><dn>, <Zm>.<T>
CLASTB <V><dn>, <Pg>, <V><dn>, <Zm>.<T>
CLASTB <Zdn>.<T>, <Pg>, <Zdn>.<T>, <Zm>.<T>
LASTA <R><d>, <Pg>, <Zn>.<T>
LASTA <V><d>, <Pg>, <Zn>.<T>
LASTB <R><d>, <Pg>, <Zn>.<T>
LASTB <V><d>, <Pg>, <Zn>.<T>
```
Issue #3044

i3044 AArch64: Add LAST instructions

---

suite/runsuite_wrapper.pl

Temporarily disable file_io as it has started failing constantly after upgrades
on the windows CI runners. The reason is currently unknown but is tracked 
by #5802.
issue: #5802

i#5802: Disable failing file_io test on windows

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
BRKA    <Pd>.B, <Pg>/<ZM>, <Pn>.B
BRKAS   <Pd>.B, <Pg>/Z, <Pn>.B
BRKB    <Pd>.B, <Pg>/<ZM>, <Pn>.B
BRKBS   <Pd>.B, <Pg>/Z, <Pn>.B
BRKN    <Pdm>.B, <Pg>/Z, <Pn>.B, <Pdm>.B
BRKNS   <Pdm>.B, <Pg>/Z, <Pn>.B, <Pdm>.B
BRKPA   <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
BRKPAS  <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
BRKPB   <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
BRKPBS  <Pd>.B, <Pg>/Z, <Pn>.B, <Pm>.B
WHILELE <Pd>.<Ts>, <R><n>, <R><m>
WHILELO <Pd>.<Ts>, <R><n>, <R><m>
WHILELS <Pd>.<Ts>, <R><n>, <R><m>
WHILELT <Pd>.<Ts>, <R><n>, <R><m>
```
issue: #3044

i#3044 AArch64 SVE codec: Add Loop control instructions

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
EXT     <Zdn>.B, <Zdn>.B, <Zm>.B, #<imm>
SPLICE  <Zdn>.<Ts>, <Pv>, <Zdn>.<Ts>, <Zm>.<Ts>
```
Issue #3044

i#3044 AArch64 SVE codec: Add EXT (Des.), SPLICE (Des.)

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
REV     <Pd>.<Ts>, <Pn>.<Ts>
REV     <Zd>.<Ts>, <Zn>.<Ts>
REVB    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
REVH    <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
REVW    <Zd>.D, <Pg>/M, <Zn>.D
COMPACT <Zd>.<Ts>, <Pg>, <Zn>.<Ts>
```
Issue #3044

i#3044 AArch64 SVE codec: Add REV, REVB, REVH, REVW, COMPACT

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.h
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
PUNPKHI <Pd>.H, <Pn>.B
PUNPKLO <Pd>.H, <Pn>.B
SUNPKHI <Zd>.<Ts>, <Zn>.<Tb>
SUNPKLO <Zd>.<Ts>, <Zn>.<Tb>
UUNPKHI <Zd>.<Ts>, <Zn>.<Tb>
UUNPKLO <Zd>.<Ts>, <Zn>.<Tb>
UZP1    <Pd>.<Ts>, <Pn>.<Ts>, <Pm>.<Ts>
UZP1    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
UZP2    <Pd>.<Ts>, <Pn>.<Ts>, <Pm>.<Ts>
UZP2    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
ZIP1    <Pd>.<Ts>, <Pn>.<Ts>, <Pm>.<Ts>
ZIP1    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
ZIP2    <Pd>.<Ts>, <Pn>.<Ts>, <Pm>.<Ts>
ZIP2    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
TRN1    <Pd>.<Ts>, <Pn>.<Ts>, <Pm>.<Ts>
TRN1    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
TRN2    <Pd>.<Ts>, <Pn>.<Ts>, <Pm>.<Ts>
TRN2    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
```
Issue #3044

i#3044 AArch64 SVE codec: Add unpack, zip, and interleaving instructions

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
DUPM    <Zd>.<Ts>, #<const>
EON     <Zdn>.<Ts>, <Zdn>.<Ts>, #<imm>
```
Issue #3044

i#3044 AArch64 SVE codec: Add DUPM, EON

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
PFALSE  <Pd>.B
PFIRST  <Pdn>.B, <Pg>, <Pdn>.B
SEL     <Pd>.B, <Pg>, <Pn>.B, <Pm>.B
SEL     <Zd>.<Ts>, <Pv>, <Zn>.<Ts>, <Zm>.<Ts>
MOV     <Pd>.B, <Pn>.B
MOVS    <Pd>.B, <Pg>/Z, <Pn>.B
PTRUE   <Pd>.<Ts>{, <pattern>}
PTRUES  <Pd>.<Ts>{, <pattern>}
```
Issue #3044

i#3044 AArch64 SVE codec: Add MOV, MOVS, PFALSE, PFIRST, PTRUE, PTRUES, SEL

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt
core/ir/aarch64/opnd_defs.txt

This pulls out code for encoding and decoding 8-bit floating-point immedate values into helper functions that can be re-used for future instructions with similar operands.
Issues: #4393, #2626

i#4393 AArch64 codec: Refactor fpimm8 codec

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
ASR     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, #<const>
ASR     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.D
ASR     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
ASR     <Zd>.<Ts>, <Zn>.<Ts>, #<const>
ASR     <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.D
ASRD    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, #<const>
ASRR    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
CLS     <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
CLZ     <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
CNT     <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
LSL     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, #<const>
LSL     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.D
LSL     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
LSL     <Zd>.<Ts>, <Zn>.<Ts>, #<const>
LSL     <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.D
LSLR    <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, …
```

i#3044 AArch64 SVE codec: Add Bitwise shift, permute and count instrs

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c

```
LD1RB   { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RB   { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RB   { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RB   { <Zt>.B }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RH   { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RH   { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RH   { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RW   { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RW   { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RD   { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RSB  { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RSB  { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RSB  { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RSH  { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<pimm>}]
LD1RSH  { …
```

i#3044 AArch64 SVE codec: Add LD1R broadcast instructions

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
ANDV    <V><d>, <Pg>, <Zn>.<Ts>
EORV    <V><d>, <Pg>, <Zn>.<Ts>
FADDA   <V><dn>, <Pg>, <V><dn>, <Zm>.<Ts>
FADDV   <V><d>, <Pg>, <Zn>.<Ts>
FMAXNMV <V><d>, <Pg>, <Zn>.<Ts>
FMAXV   <V><d>, <Pg>, <Zn>.<Ts>
FMINNMV <V><d>, <Pg>, <Zn>.<Ts>
FMINV   <V><d>, <Pg>, <Zn>.<Ts>
ORV     <V><d>, <Pg>, <Zn>.<Ts>
SADDV   <Dd>, <Pg>, <Zn>.<Ts>
SMAXV   <V><d>, <Pg>, <Zn>.<Ts>
SMINV   <V><d>, <Pg>, <Zn>.<Ts>
UADDV   <Dd>, <Pg>, <Zn>.<Ts>
UMAXV   <V><d>, <Pg>, <Zn>.<Ts>
UMINV   <V><d>, <Pg>, <Zn>.<Ts>
```
issue: #3044

i#3044 AArch64 SVE codec: Add horizontal reduction instructions

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

FCVT    <Zd>.H, <Pg>/M, <Zn>.D
FCVT    <Zd>.S, <Pg>/M, <Zn>.D
FCVT    <Zd>.D, <Pg>/M, <Zn>.H
FCVT    <Zd>.S, <Pg>/M, <Zn>.H
FCVT    <Zd>.D, <Pg>/M, <Zn>.S
FCVT    <Zd>.H, <Pg>/M, <Zn>.S
FCVTZS  <Zd>.S, <Pg>/M, <Zn>.D
FCVTZS  <Zd>.D, <Pg>/M, <Zn>.D
FCVTZS  <Zd>.H, <Pg>/M, <Zn>.H
FCVTZS  <Zd>.S, <Pg>/M, <Zn>.H
FCVTZS  <Zd>.D, <Pg>/M, <Zn>.H
FCVTZS  <Zd>.S, <Pg>/M, <Zn>.S
FCVTZS  <Zd>.D, <Pg>/M, <Zn>.S
FCVTZU  <Zd>.S, <Pg>/M, <Zn>.D
FCVTZU  <Zd>.D, <Pg>/M, <Zn>.D
FCVTZU  <Zd>.H, <Pg>/M, <Zn>.H
FCVTZU  <Zd>.S, <Pg>/M, <Zn>.H
FCVTZU  <Zd>.D, <Pg>/M, <Zn>.H
FCVTZU  <Zd>.S, <Pg>/M, <Zn>.S
FCVTZU  <Zd>.D, <Pg>/M, <Zn>.S
FRINTA  <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
FRINTI  <Zd>.<Ts>, <Pg>/M, <Zn>.<Ts>
FRINTM …

i#3044 AArch64 SVE codec: Add floating-point conversion instructions

---

core/ir/aarch64/codec.c
ext/drbbdup/drbbdup.c
ext/drbbdup/drbbdup.h
ext/drx/drx.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drx-scattergather-bbdup.dll.c

Moves the drbbdup restore state event to a very early priority and has it modify the restore state parameters to focus on the containing copy of the block where the restore resides.  It modifies the instruction list and the cache start pc.
Adds a new test drx-scattergather-bbdup by adding drbbdup to the existing drx-scattergather test.  This test fails to restore without the fix described above, due to the scatter/gather expansion restore state machine getting confused across multiple copies.
Does not augment drbbdup's restore to handle the no-ilist case: leaves that for the general #3801 mechanism.
Issue: #5686

i#5686 bbdup xl8: Modify xl8 params for other libs
