DynamoRIO/dynamorio

clients/drcachesim/common/options.cpp
clients/drcachesim/tracer/instru_online.cpp

With the stability issues with drbbdup seemingly solved, we enable -align_endpoints by default for x86 (it was already on for AArchXX).
Fixes #2039

i#2039 trace trim, part 8: Enable for x86

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

CTERMEQ <R><n>, <R><m>
CTERMNE <R><n>, <R><m>
PNEXT   <Pdn>.<Ts>, <Pv>, <Pdn>.<Ts>
Issues: #3044

i#3044 AArch64 SVE codec: Add serialized operations

---

core/ir/decodelib.c
core/utils.c
suite/tests/api/ir_x86.c

Fixes a bug where print_to_buffer() does not correctly handle d_r_vsnprintf()'s return value for the case where the max size is filled up exactly with no room for a null.  This bug showed up in the exported disassemble_to_buffer().
Adds tests of these corner cases in disassemble_to_buffer() to api.ir.
Fixes #5833

i#5833: Fix print_to_buffer full-buffer return error

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
ADDPL   <Xd|SP>, <Xn|SP>, #<imm>
ADDVL   <Xd|SP>, <Xn|SP>, #<imm>
RDVL    <Xd>, #<imm>
```
Support for ADR instructions will be added in a later commit.
Issues: #3044

i#3044 AArch64 SVE codec: Add vector address calculations

---

suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_sve.c

This patch changes the values of the registers used in the ir_aarch64 tests so that they better defend against transposition of operands
Issue: #3044

i#3044 AArch64 SVE tests: Update list of registers used for tests

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
core/ir/opnd_api.h
core/ir/opnd_shared.c
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LDFF1B  { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1B  { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1B  { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1B  { <Zt>.B }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1D  { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL #3}]
LDFF1H  { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL #1}]
LDFF1H  { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL #1}]
LDFF1H  { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL #1}]
LDFF1SB { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1SB { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1SB { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, <Xm>}]
LDFF1SH { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL #1}]
LDFF1SH { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL #1}]
LDFF1SW { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, <Xm>, LSL …
```

i#3044 AArch64 SVE codec: Add LDFF1* (scalar plus scalar) instructions

---

api/docs/release.dox

Added the new opnd_size_to_shift_amount() and opnd_create_base_disp_shift_aarch64() functions.
Issue #3044

i#3044 AArch64 SVE Codec: Update release dox for API changes

---

ext/drcovlib/drcovlib.c

The drcov bb count was being printed as a 32-bit integer but passed a 64-bit value for x64/aarch64 builds.  We fix that here to pass a 32-bit value with an overflow check (we do not support >4G blocks in drcov's post-processing today).
Unfortunately there is not a simple way to make a test.  I experimented and actually failed to get the original bug to cause any visible problem even with subsequent specifiers in that same format string, with today's va_list accessors.  Making a test of millions or billions of blocks is non-trivial: the easiest way is to dynamically generate the code, but that is not a great test for drcov in general where we want source lines to map back to; plus it will take a while to run which is not great in the CI suite.
Fixes #5845

i#5845: Fix format string type for drcov bb count

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
FCADD   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>, <const>
FCMLA   <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>, <const>
FCMLA   <Zda>.H, <Zn>.H, <Zm>.H[<imm>], <const>
FCMLA   <Zda>.S, <Zn>.S, <Zm>.S[<imm>], <const>
```
Issue #3044

i#3044 AArch64 SVE codec: v8.3 complex number instructions

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt

We bumped the build version to 9.90 but failed to match it in the package and docs command lines (unfortunately these are not shared and we have no simple way to do so).  We update the other versions here to all be 9.90.
Fixes #5869

i#5869: Update package and docs versions to match build

---

api/docs/release.dox
core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
core/ir/opnd_api.h
core/ir/opnd_shared.c
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD2B    { <Zt1>.B, <Zt2>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
LD3B    { <Zt1>.B, <Zt2>.B, <Zt3>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
LD4B    { <Zt1>.B, <Zt2>.B, <Zt3>.B, <Zt4>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
ST2B    { <Zt1>.B, <Zt2>.B }, <Pg>, [<Xn|SP>, <Xm>]
ST3B    { <Zt1>.B, <Zt2>.B, <Zt3>.B }, <Pg>, [<Xn|SP>, <Xm>]
ST4B    { <Zt1>.B, <Zt2>.B, <Zt3>.B, <Zt4>.B }, <Pg>, [<Xn|SP>, <Xm>]
```
issue: #3044

i#3044 AArch64 SVE codec: Add multi gpr memory load/stores

---

clients/drcachesim/tools/opcode_mix.cpp

Adds a missing instr_free on an opcode_mix error path found in a tree for #5871.

Fix missing free on opcode_mix error path

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.py
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/codec_v86.txt
core/ir/aarch64/codecsort.py
core/ir/aarch64/instr_create_api.h
make/CMake_aarch64_gen_codec.cmake
make/aarch64_check_codec_order.py
suite/tests/CMakeLists.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/dis-a64-v86.txt
suite/tests/api/ir_aarch64_sve2.c
suite/tests/api/ir_aarch64_sve2.expect
suite/tests/api/ir_aarch64_v86.c
suite/tests/api/ir_aarch64_v86.expect

* Updating the build and test system backends to support v8.6 and SVE2
* Added v8.3 to the codec checking scripts, as it seems to have been missed
Issue #2626

i#2626 Finish AArch64 encoder/decoder: Preparations for v8.6 and SVE2

---

clients/drcachesim/common/options.cpp
clients/drcachesim/reader/config_reader.cpp
clients/drcachesim/simulator/cache.cpp
clients/drcachesim/simulator/cache_fifo.cpp
clients/drcachesim/simulator/cache_lru.cpp
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/simulator/caching_device.h
clients/drcachesim/tests/drcachesim_unit_tests.cpp

Remove restriction that cache associativity and size must be a power-of-two.  Updated requirement is that size / associativity must be a power-of-two.  Added tests for newly supported sizes, and for the updated cache.init() parameter checkers.
Issue: #4489
Fixes: #4996

i#4489 drcachesim: support any cache associativity

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/release.dox
core/arch/arch.c
core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/encode.c
core/ir/aarch64/instr.c
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
core/ir/disassemble_shared.c
core/ir/opnd_api.h
core/ir/opnd_shared.c
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
ADR     <Zd>.D, [<Zn>.D, <Zm>.D, SXTW <amount>]
ADR     <Zd>.D, [<Zn>.D, <Zm>.D, UXTW <amount>]
ADR     <Zd>.<Ts>, [<Zn>.<Ts>, <Zm>.<Ts>, <extend> <amount>]
```
and the required changes to support the use of vector registers in base+disp adress operands.
This required two main changes:
1) Adding element size to base disp operand
ADR uses Z vector registers for the base and index register so we
need to be able to specify the element size in the operand.
This adds an element size field to base+disp operands (AArch64
only). The following sizes are supported:
OPSZ_4: Single
OPSZ_8: Double
For example, the memory operand for:
```
adr z0.d, [z1.d, z2.d, lsl 2]
```
could be created with the …

i#3044 AArch64 SVE codec: Add ADR instructions

---

core/ir/aarch64/codec_v86.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-v86.txt
suite/tests/api/ir_aarch64_v86.c

```
SMMLA   <Vd>.4S, <Vn>.16B, <Vm>.16B
SUDOT   <Vd>.<Ts>, <Vn>.<Tb>, <Vm>.4B[<index>]
UMMLA   <Vd>.4S, <Vn>.16B, <Vm>.16B
USMMLA  <Vd>.4S, <Vn>.16B, <Vm>.16B
USDOT   <Vd>.<Ts>, <Vn>.<Tb>, <Vm>.<Tb>
USDOT   <Vd>.<Ts>, <Vn>.<Tb>, <Vm>.4B[<index>]
```
Issue #2626

i#2626 Finish AArch64 encoder/decoder: v8.6 MatMul operations

---

suite/runsuite_wrapper.pl

The rseq test fails on various different machines, and in different contexts including during postcommit on the test runner, but not on precommit. Ignoring this by default due to the flakiness
issue: #5734

i#5734: disable rseq test on AArch64 runners

---

api/docs/release.dox
clients/drcachesim/CMakeLists.txt
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/common/utils.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/reader/file_reader.h
clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/reader.h
clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/burst_aarch64_sys.cpp
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/burst_traceopts.cpp
clients/drcachesim/tests/offline-skip2.expect
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tests/skip_unit_tests.cpp
clients/drcachesim/tools/histogram_launcher.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/raw2trace.h
suite/tests/CMakeLists.txt

Adds a new scheduler component to drmemtrace which provides flexibility in combining input traces and is meant to supply key features for simulation of traces.
This first stage adds a base scheduler which only supports the two analyzer modes: parallel software thread streams or a single serial stream.
The input file opening code and the input-to-worker code is moved from the analyzer to the scheduler.  The analyzer now has to look at the tid fields in the stream records to identify shards to tools, but the input-to-worker does belong in the scheduler.
Removes the analyzer external iterator interface; tools should instead use the scheduler directly.  Updates histogram_launcher and two tests to do this.
Adds a new scheduler unit test with a mocked reader that takes vectors of records, …

i#5843 scheduler: Add memtrace scheduler and refactor analyzer

---

suite/runsuite_wrapper.pl
suite/tests/CMakeLists.txt

Windows-zlib fails about 5% of the time for currently unknown reasons. A reproducer has been submitted to the associated ticket and this patch marks it as flaky.
The patch also increases the timeouts of drstatecmp_fuzz which were slightly exceeding them.
issue: #5507

i#5507: AArch64 testing: Mark windows-zlib as flaky and extend timeouts

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD1B    { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LD1B    { <Zt>.S }, <Pg>/Z, [<Zn>.S{, #<imm>}]
LD1H    { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LD1H    { <Zt>.S }, <Pg>/Z, [<Zn>.S{, #<imm>}]
LD1W    { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LD1W    { <Zt>.S }, <Pg>/Z, [<Zn>.S{, #<imm>}]
LD1D    { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LD1SB   { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LD1SB   { <Zt>.S }, <Pg>/Z, [<Zn>.S{, #<imm>}]
LD1SH   { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LD1SH   { <Zt>.S }, <Pg>/Z, [<Zn>.S{, #<imm>}]
LD1SW   { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LDFF1B  { <Zt>.D }, <Pg>/Z, [<Zn>.D{, #<imm>}]
LDFF1B  { <Zt>.S }, <Pg>/Z, [<Zn>.S{, #<imm>}]
LDFF1H  { <Zt>.D }, <Pg>/Z, [<Zn>.D{, …
```

i#3044 AArch64 SVE codec: Add memory vector+immed

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD1B    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, LSL #3]
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LD1H    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, LSL #1]
LD1H    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LD1SB   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LD1SH   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, LSL #1]
LD1SH   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LD1SW   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, LSL #2]
LD1SW   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LD1W    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, LSL #2]
LD1W    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LDFF1B  { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D]
LDFF1D  { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, LSL #3] …
```

i#3044 AArch64 SVE codec: Add memory scalar+vector 64-bit offset

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD1B    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend>]
LD1B    { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Zm>.S, <extend>]
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend> #3]
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend>]
LD1H    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend> #1]
LD1H    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend>]
LD1H    { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Zm>.S, <extend> #1]
LD1H    { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Zm>.S, <extend>]
LD1SB   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend>]
LD1SB   { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Zm>.S, <extend>]
LD1SH   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend> #1]
LD1SH   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Zm>.D, <extend>]
LD1SH   { …
```

i#3044 AArch64 SVE codec: Add memory scalar+vector 32-bit offset

---

core/arch/aarch64/proc.c

Attempting to read the ID_AA64ZFR0_EL1 outside of the unit tests resulted in a CLIENT_ASSERT failure on supporting hardware.
Issue #3044

i#3044 AArch64 SVE codec:  SVE processor feature fix

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Implements timestamp ordering in scheduler_t rather than relying on the old implementation inside file_reader_t.
Adds a sanity test.
Removing the file_reader_t code, along with eliminating the thread-as-sub-reader API routines, will be done as a separate refactoring.
Issue: #5843

i#5843 scheduler: Move timestamp ordering into scheduler

---

.github/workflows/ci-x86.yml
core/unix/loader.c

Adds the same workaround for the SIGFPE in glibc 2.34+ __libc_early_init() as for 64-bit in PR #5695: we hardcode the 32-bit offsets of the two globals written by the workaround.
Tested on glibc 2.34 where every libc-using client crashes with SIGFPE but they work with this fix.
Adds an Ubuntu22 GA CI 32-bit run.
Issue: #5437

i#5437 glibc2.34-35: 32-bit workaround for SIGFPE

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #3]
LD1H    { <Zt>.H }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD1H    { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD1H    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD1SH   { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD1SH   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD1SW   { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #2]
LD1W    { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #2]
LD1W    { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #2]
LD2D    { <Zt1>.D, <Zt2>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #3]
LD2H    { <Zt1>.H, <Zt2>.H }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD2W    { <Zt1>.S, <Zt2>.S }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #2]
LD3D    { <Zt1>.D, <Zt2>.D, <Zt3>.D }, …
```

i#3044 AArch64 SVE codec: Add scalar memory with shift instructions

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD1B    { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1B    { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1B    { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1B    { <Zt>.B }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1H    { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1H    { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1H    { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1SB   { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1SB   { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1SB   { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1SH   { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1SH   { …
```

i#3044 AArch64 SVE codec: Add memory scalar+immed

---

clients/drcachesim/tests/reuse_distance_test.cpp
clients/drcachesim/tools/reuse_distance.cpp

Avoids trying to read from an empty vector.
Adds a unit test for this corner case.
Fixes #5909

i#5909: handle empty input vector in print_histogram

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD2B    { <Zt1>.B, <Zt2>.B }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD2D    { <Zt1>.D, <Zt2>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD2H    { <Zt1>.H, <Zt2>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD2W    { <Zt1>.S, <Zt2>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD3B    { <Zt1>.B, <Zt2>.B, <Zt3>.B }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD3D    { <Zt1>.D, <Zt2>.D, <Zt3>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD3H    { <Zt1>.H, <Zt2>.H, <Zt3>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD3W    { <Zt1>.S, <Zt2>.S, <Zt3>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD4B    { <Zt1>.B, <Zt2>.B, <Zt3>.B, <Zt4>.B }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD4D    { <Zt1>.D, <Zt2>.D, <Zt3>.D, …
```

i#3044 AArch64 SVE codec: Add memory scalar+immed multi-register

---

clients/drcachesim/tools/reuse_distance.cpp
clients/drcachesim/tools/reuse_distance.h

The old DEBUG_VERSOSE(level) macro returns a condition that can be evaluated at runtime for debug actions.  When not in DEBUG mode, the condition always evaluates to false, resulting in unreachable code the compiler will hopefully eliminate, but may cause a warning.
The new IF_DEBUG_VERBOSE(level, action) macro includes the condition evaluation to perform <action> when the condition is met in DEBUG mode.  When not in DEBUG mode, all code including the condition is eliminated, leaving nothing to the compiler.

Updates debug printing macro to include if().

---

third_party/vera++/use_vera++.cmake

vera++ complains for various files in the build directory when it is a sub-directory of the source directory.
Our documentation suggests creating a `build` directory inside the source directory, so this flow must work.

Skip vera++ checks for build directory

---

core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-v83.txt
suite/tests/api/ir_aarch64_v83.c

```
AUTDA   <Xd>, <Xn|SP>
AUTDB   <Xd>, <Xn|SP>
AUTDZA  <Xd>
AUTDZB  <Xd>
```

i#2626 Finish AArch64 encoder/decoder: AUTD*

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds initial support for MAP_TO_ANY_OUTPUT with multiple outputs. Uses a simple queue of ready-to-schedule inputs and implements an instruction-based scheduling quantum.
Adds a test.
Issue: #5843

i#5843 scheduler: Add simple interleaving

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp
suite/tests/CMakeLists.txt

Fixes a too-long chunk after a prior chunk splits up consecutive delayed branches in the same buffer.
Avoids placing wasted encodings at the end of a chunk.
Adds a unit test, and reduces the chunk size for the larger test which causes the original problem to reproduce much more reliably.
Still to fix is to re-emit encodings for the second consecutive branch after the boundary.
Issue: #5724

i#5724 chunk bounds: Fix incorrect instruction counts

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-v83.txt
suite/tests/api/ir_aarch64_v83.c

```
AUTIA   <Xd>, <Xn|SP>
AUTIB   <Xd>, <Xn|SP>
AUTIA1716
AUTIB1716
AUTIASP
AUTIBSP
AUTIAZ
AUTIBZ
AUTIZA  <Xd>
AUTIZB  <Xd>
```

i#2626 Finish AArch64 encoder/decoder: AUTI*

---

core/arch/aarchxx/mangle.c
core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr.c
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-v83.txt
suite/tests/api/ir_aarch64_v83.c

```
BLRAA   <Xn>, <Xm|SP>
BLRAB   <Xn>, <Xm|SP>
BRAA    <Xn>, <Xm|SP>
BRAB    <Xn>, <Xm|SP>
BLRAAZ  <Xn>
BLRABZ  <Xn>
BRAAZ   <Xn>
BRABZ   <Xn>
```

i#2626 Finish AArch64 encoder/decoder: B[L]RA*

---

core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-v83.txt
suite/tests/api/ir_aarch64_v83.c

```
PACDA   <Xd>, <Xn|SP>
PACDB   <Xd>, <Xn|SP>
PACDZA  <Xd>
PACDZB  <Xd>
PACGA   <Xd>, <Xn>, <Xm|SP>
```

i#2626 Finish AArch64 encoder/decoder: PACD*

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-v83.txt
suite/tests/api/ir_aarch64_v83.c

```
LDRAA   <Xt>, [<Xn|SP>, #<simm>]!
LDRAA   <Xt>, [<Xn|SP>, #<simm>]
LDRAB   <Xt>, [<Xn|SP>, #<simm>]!
LDRAB   <Xt>, [<Xn|SP>, #<simm>]
```

i#2626 Finish AArch64 encoder/decoder: LDRA*

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
suite/runsuite_wrapper.pl

Adds logic to insert new encodings for instruction entries that were generated before it was known they'd appear after a chunk boundary. This has some inherent complexity due to the different modules owning record generation and chunk creation, along with the complexity of needing the decode PC for instruction records generated in the past.
This finishes #5724, allowing us to remove it from the flaky list.
Fixes #5724

i#5724 chunk bounds: Insert encodings in new chunks

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/release.dox
core/arch/aarchxx/mangle.c
core/ir/aarch64/codec_v83.txt
core/ir/aarch64/instr.c
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-v83.txt
suite/tests/api/ir_aarch64_v83.c

i#2626 Finish AArch64 encoder/decoder: *RETA*

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Skips emitting to the final trace the 1-instr duplicate system call block which
has the same pc as the immediately previous system call instr. This will serve
as a workaround until we root-cause and fix the underlying issue in the
drmemtrace tracer.
Adds a unit test for this scenario.
Tested on a proprietary app trace known to have duplicate syscall errors that
this fixes all instances of such errors.
Issue: #5934

i#5934 dup syscall: Skip extraneous syscall in raw2trace.

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/reader/reader.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds an explicit check for -skip_instructions hitting the footer to avoid an assert on trying to process it as a normal entry.
Adds a scheduler test.
Adds a separate analyzer error string for this.
I tested this manually:
-------------
$ clients/bin64/drcachesim -simulator_type view -indir drmemtrace.*.dir -skip_instrs 6300 -verbose 2
ERROR: failed to run analyzer: Too-far -skip_instrs for: drmemtrace.allasm_x86_64.2490594.5358.trace.zip
-------------
Fixes #5950

i#5950: Stop skipping at footer

---

suite/tests/linux/rseq.c

Adds struct rseq offset for glibc 2.36, but also preserves the existing ones for
older glibc since our CI workflows are still on the older versions.
Glibc 2.36 made some changes to the __rseq_offset. We have logic that uses a
heuristic to search for the struct rseq offset. But we also assert on the
expected known glibc rseq offset in the linux.rseq test; this is to
proactively detect glibc changes in rseq handling.
This fixes all rseq tests on glibc 2.36 except tool.drcacheoff.rseq which is
covered by #5734.
Fixes: #5955

i#5955: Update expected rseq offset for glibc 2.36

---

core/arch/aarch64/proc.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/instr_create_api.h
suite/tests/CMakeLists.txt
suite/tests/api/dis-a64-v82.txt
suite/tests/api/ir_aarch64_v82.c

```
DC CVAP, <Xt>
DC CVADP, <Xt>
```
Issue: #2626

i#2626 Finish AArch64 encoder/decoder: DC CVA[D]P

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp

Shares the chunk of code running raw2trace on a vector of offline entries and producing a vector of trace_entry_t, which was previously duplicated in every test.
Issue: #5953

i#5953 rseq side: Share code in raw2trace_unit_tests

---

api/docs/release.dox
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Removes the separate template class trace_converter_t and moves its contents into the raw2trace_t class.  We no longer need this separation, and in fact it is hindering our efforts to add new capabilities to raw2trace_t.
Fixes #4062

i#4062: Remove trace_converter_t to simplify raw2trace_t

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/tracer.cpp
core/arch/interp.c
core/fragment.h
core/lib/globals_api.h
core/unix/os_exports.h
core/unix/rseq_linux.c
core/unix/rseq_linux.h
core/vmareas.c
suite/tests/linux/rseq.c

With our run-twice rseq solution, we first run an instrumented path through the rseq region which goes into the recorded drmemtrace trace. But the native rseq execution might take a side exit or abort.  We already had code to try to roll back the committing store on an abort, but it was fragile as a timestamp in between thwarted it.  We had no code to make a side exit match and as a result we'd see PC discontinuities.
Here, we solve both problems with the following approach:
First, we have DR add a new DR_NOTE_RSEQ_ENTRY label to the top of the first block in an rseq region.  This label's data stores the end PC and the abort handler PC (we do not currently use the latter in drmemtrace: once we revert #4041 we may need to do so).
Next, the tracer turns that label into a new …

i#5954: Adjust rseq trace path to match real path

---

core/lib/instrument.c
core/unix/module_elf.c

This PR tries to fix #5946 by performing extra check for dynamic info was initialized in os_module_data_t during module load.
The error is triggered when loaded ELF module have a specific program sections order: `.dynstr`  should be placed in the end. In such case it wouldn't be mapped at the moment of os_module_data_t initialization.
If DR-client would try to use module data later (via dr_get_proc_address for example), DR will crash.
_How to reproduce for testing:_
1) You need a target program with dynamic linking to the shared library (example: )
2) Shared library ELF should have late .dynstr section. This could be achieved by using `patchelf` utility: after a compilation of libtest.so object you need to run `patchelf --set-rpath '$ORIGIN' libtest.so`. To check program sections …

i#5946: Check whether dynamic info is set in os_module_data_t before using it

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
clients/drcachesim/tracer/tracer.cpp
core/globals.h
core/lib/dr_events.h
core/translate.c
core/translate.h
core/unix/signal.c
suite/tests/CMakeLists.txt

Fixes problems with the new rseq adjustment code with filtered traces:
+ Load and update the buffer pointer when emitting the rseq entry label
+ Do not try to adjust for i-filtered
Adds 2 new tests for filtering the linux.rseq app.
The new tests revealed a problem with the instr counts in the schedule file:
raw2trace was counting the PC-only entries as instructions; we fix that here.
Reverts the rseq abort event and marker value back to the interrupted
PC for a signal in the instrumented execution.  Leaves all other cases
(all aborts in the native execution) as the handler.  This lets us
properly place the abort+signal for the instrumented interruption
case.
Adjusts the invariant checker abort check to use the new end PC for a
more accurate test to avoid false positives and negatives. …

i#5953 rseq: Fix rseq adjust issues with filtering

---

.github/workflows/ci-windows.yml
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/memref_gen.h
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Adds a dedicated invariant check for duplicate syscalls that have the same PC and reported as 'Non-explicit control flow has no marker'.
Tested with an app that has the 'Non-explicit control flow has no marker' error for duplicate syscalls and after this change, most of the errors classified in that original error type are now reported as 'Duplicate syscall instrs with the same PC'.
Issue: #5934

i#5934 Add 'Duplicate syscalls with the same PC' invariant check

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
TRN1    <Zd>.Q, <Zn>.Q, <Zm>.Q
TRN2    <Zd>.Q, <Zn>.Q, <Zm>.Q
```
issue: #3044

i#3044 AArch64 SVE codec: Add TRN1/2 Q-sized opcodes

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/simulator/analyzer_interface.cpp
clients/drcachesim/tests/counts_only_thread.templatex
clients/drcachesim/tests/skip_unit_tests.cpp
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h
clients/drcachesim/tools/view_create.h
suite/tests/CMakeLists.txt

Applies -only_thread at the analyzer framework level, setting a thread filter for the scheduler.  This results in just one thread file being opened.
Removes the only_thread knob from the view tool.
Tested:
Before:
$ bin64/drrun -t drcachesim -verbose 1 -simulator_type view -indir drmemtrace.*.dir -only_thread 2557808 -sim_refs 20 2>&1 | grep -c 'Opened reader'
9
After:
$ bin64/drrun -t drcachesim -verbose 1 -simulator_type view -indir drmemtrace.*.dir -only_thread 2557808 -sim_refs 20 2>&1 | grep -c 'Opened reader'
0
Fixes #5951

i#5951: Make -only_thread a top-level analyzer option

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h
core/lib/instrument.c
core/translate.c
core/translate.h
core/unix/rseq_linux.c
core/unix/signal.c
suite/tests/linux/rseq.c

Fixes 3 more problems with rseq in DR and in drmemtraces related to exits and signals:
1) Side exit in instrumented run: avoids unbounded buffer growth by detecting by looking at the region bounds.  Adds a buffer large size sanity check.  Adds a test to linux.rseq.
2) Try to handle double-abort: couldn't repro in test though so the fix of disabling a later signal from reporting an abort when we report an abort fragment exit is not fully vetted.
3) Asynch signal in instrumented run: this was not being adjusted so the interruption/continuation PC is the abort handler.  Adds a test to linux.rseq.
Adds more invariant checks around rseq region exits.
Issue: #5953, #4041, #5954, #5980
Fixes #5980

i#5980: Fix 3 rseq exit/signal issues

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

For rseq rollbacks in raw2trace, we can end up leaving a branch followed by a timestamp after we remove other records.  This violates our branch invariant.  We solve this by removing any timestamp adjacent to the rollback region.
Adds a new unit test for this and adjusts an exiting one.
Further tested on a proprietary app where this showed up for real: it is now gone.
Fixes #5986

i#5986: Remove timestamps too in rseq rollbacks

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Adds instr_autoclean_t to ensure the instance of instr_t is cleaned up when it is out of scope.
Fixes #5982

i#5982: Fix memory leak in invariant checker

---

ext/drsyms/drsyms.dox

Adds details about the missing support for DWARFv5 in elftoolchain which means that drsyms would not work as expected with binaries compiled with recent compiler versions like g++-11.
Also suggests possible workarounds: use older compiler version, or output DWARFv4 by specifying -gdwarf-4.
Issue: #5926

i#5926: Document DWARFv4 limitation for drsyms

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
LD1RQB  { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>}]
LD1RQB  { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>]
LD1RQD  { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>}]
LD1RQD  { <Zt>.D }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #3]
LD1RQH  { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>}]
LD1RQH  { <Zt>.H }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #1]
LD1RQW  { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>}]
LD1RQW  { <Zt>.S }, <Pg>/Z, [<Xn|SP>, <Xm>, LSL #2]
```
Issue: #3044

i#3044 AArch64 SVE codec: Add LD1RQ*

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
SDOT    <Zda>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SDOT    <Zda>.D, <Zn>.H, <Zm>.H[<index>]
SDOT    <Zda>.S, <Zn>.B, <Zm>.B[<index>]
UDOT    <Zda>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
UDOT    <Zda>.D, <Zn>.H, <Zm>.H[<index>]
UDOT    <Zda>.S, <Zn>.B, <Zm>.B[<index>]
```
Issue: #3044

i#3044 AArch64 SVE codec: Add SDOT/UDOT

---

core/unix/signal.c

Avoids installing DR's own signal handlers when in standalone mode, as we do not want to mess up the app's own handlers.  Standalone mode does not support safe_read or try_except.
Tested on a large app with DR in standalone mode and confirmed sigaction_syscall was not hit under the debugger any more.
Fixes #5998

i#5998: Do not install DR signal handlers in standalone mode

---

core/ir/encode_api.h

Updates the documentation for various encode APIs to correctly state that
the offset field of instr_t is used for instr_t target offset computation, instead
of the note field which was used prior to #5791.

Update offset field name in encode API doc

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/tracer.cpp
core/ir/aarch64/instr_create_api.h
core/ir/opnd_api.h

Changes the kernel interruption PC for 64-bit from a modidx+modoffs scheme that was trying to avoid a 2nd record but which failed to handle a non-module PC to use the absolute PC (a recently added assert fires in this case; previously we could assert or crash or continue with a bogus value in raw2trace depending on the uninitialized value of modidx).
Bumps the raw offline version number.  Updates raw2trace to handle both the old version as modix+modoffs plus the new absolute PC version.  Adds new unit tests for both.
Adds a SIGILL to the burst_gencode trace which triggers the new tracer assert and passes with this fix.
To build the test, adds 0-valued entries to operand enums: DR_EXTEND_DEFAULT and DR_OPND_NONE, to avoid C++ compiler warnings in INSTR_CREATE_dc_ivac().  #6000 covers using …

i#2062 memtrace nonmod part 3: Kernel interruption PC

---

core/ir/aarch64/instr_create_api.h

Some INSTR_CREATE macros which use opnd_create_base_disp_aarch64() pass in 0 for the dr_extend_type_t and/or dr_opnd_flags_t parameters. The implicit conversion from int to enum fails when such macros are used in C++ source. This patch replaces addressing with the simpler generic opnd_create_base_disp() to avoid using dr_extend_type_t and dr_opnd_flags_t parameters.
Issue: #6000

i#6000 AArch64: Fix INSTR_CREATE macros which use 0 for enums

---

.github/workflows/ci-aarch64-native.yml

Adds test workflow running on self-hosted aarch64 runner, as these are not currently available from Github.
This will replace tests triggered on external Jenkins instance.

iX: Add native aarch64 test workflow

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
FNMSB   <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
```
Issues: #3044

i#3044 AArch64 SVE codec: FNMSB

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/release.dox
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.expect
suite/tests/api/ir_aarch64_negative.c
suite/tests/api/ir_aarch64_negative.expect
suite/tests/api/ir_aarch64_sve.c

These instructions were implemented before the IR was fully defined for SVE and were thus missing the predicate mode and the vector element sizes.
This patch updates the appropriate macros, tests and codec entries to encode the following variants:
```
AND     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
BIC     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
EOR     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
ORR     <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, <Zm>.<Ts>
```
issue: #3044

i#3044 AArch64 SVE codec: Update old AND, BIC, EOR and ORR encodings

---

clients/drcachesim/common/trace_entry.h

Removes the maybe-fetch type which was erroneously included in the type_is_data() helper function for drmemtrace types.

Remove instruction fetch from type_is_data()

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/speculator.cpp
clients/drcachesim/scheduler/speculator.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Implements initial speculation support, supplying nops.  Speculation is separated into its own class where we can fill in different strategies in the future.
The start_speculation() function takes a flag controlling whether the scheduler queues up the current record and re-returns it as the first record after speculation stops.  This is often what a simulator wants as it has to read the instruction record following a branch to determine whether it is on the wrong path, and it would like to resume with that already-read instruction after speculation.
Issue: #5843

i#5843 scheduler: Implement speculation with nops

---

api/docs/CMakeLists.txt

The online html docs ended up with the Tracing and Analysis Framework at the top level listed under License, rather than a sub-menu entry of Available Tools, due to PR #5685 which moved drcachesim.dox.in into a docs/ subdir and now the cmake glob doesn't find it.
We fix that by extending the glob.
Tested with a local docs build.
Fixes #5858

i#5858: Fix drmemtrace docs location in menu

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

Several instructions had the predicate decoded into the wrong location in the ir relative to the disassembly. This patch corrects that
This patch fixes the appropriate macros, tests and codec entries to encode the following variants:
```
DECP    <Xdn>, <Pm>.<Ts>
DECP    <Zdn>.<Ts>, <Pm>.<Ts>
INCP    <Xdn>, <Pm>.<Ts>
INCP    <Zdn>.<Ts>, <Pm>.<Ts>
MAD     <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
MLA     <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>
MLS     <Zda>.<Ts>, <Pg>/M, <Zn>.<Ts>, <Zm>.<Ts>
MSB     <Zdn>.<Ts>, <Pg>/M, <Zm>.<Ts>, <Za>.<Ts>
SQDECP  <Xdn>, <Pm>.<Ts>
SQDECP  <Zdn>.<Ts>, <Pm>.<Ts>
SQINCP  <Xdn>, <Pm>.<Ts>, <Wdn>
SQINCP  <Xdn>, <Pm>.<Ts>
SQINCP  <Zdn>.<Ts>, <Pm>.<Ts>
UQDECP  <Wdn>, <Pm>.<Ts>
UQDECP  <Xdn>, <Pm>.<Ts>
UQDECP  <Zdn>.<Ts>, <Pm>.<Ts>
UQINCP  <Wdn>, <Pm>.<Ts>
UQINCP …
```

i#3044: AArch64 SVE codec: Fix misplaced predicates

---

clients/drcachesim/analyzer.cpp

Adds missing only_thread arg value in call-site for init_scheduler. We
need to re-specify the default value for only_thread if we want to specify
verbosity.

Fix init_scheduler call-site in analyzer_t

---

README.md
api/docs/ext.gendox
api/docs/home.dox

Removed "docs/" prefix as was suggested by [derekbruening](https://github.com/derekbruening)
Related  [PR](https://github.com/DynamoRIO/dynamorio.github.io/pull/37)

removed "docs/" prefix from drmemory.org/docs links

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

```
BFCVTNT <Zd>.H, <Pg>/M, <Zn>.S
SQDECP  <Xdn>, <Pm>.<Ts>, <Wdn>
```
issue: #3044

i#3044: AArch64 SVE codec: Add bfcvtnt and sqdecp

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/scheduler_launcher.cpp

Adds a new larger manual test harness in the form of a standalone launcher for the scheduler which can be used on larger application threads for experimentation.
Issue: #5843

i#5843: Add scheduler CLI tool

---

clients/drcachesim/drpt2trace/CMakeLists.txt
clients/drcachesim/drpt2trace/drpt2trace.cpp
clients/drcachesim/drpt2trace/ir2trace.cpp
clients/drcachesim/drpt2trace/ir2trace.h
clients/drcachesim/drpt2trace/test_simple.expect
clients/drcachesim/tests/offline-kernel-simple.templatex

Adds a new library drir2trace and updates drpt2trace
(1) Adds a new library drir2trace to convert DR's IR to trace entries.
This library converts DynamoRIO's Intermediate Representation (DR's IR) into trace entries. Currently, the library focuses on converting DR's IR format into trace_entry_t instances specific to instruction types.
(2)Updates drpt2trace to support converting Intel PT raw data to trace entries.
drpt2trace is updated to facilitate the conversion of Intel PT raw data into trace entries. It accomplishes this by initially transforming the Intel PT raw data into DR's IR, which is subsequently converted into trace entries using the newly introduced drir2trace library.
Issue: #5505

i#5505 kernel trace: Add drir2trace to convert DR's IR to trace entries

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/invariant_checker.cpp

Adds replay of the as-traced schedule using the cpu_schedule.zip file written by raw2trace.  That file is converted into the record+replay format for dynamic schedules and the existing replay code leveraged.
This implements as-traced cpu-oriented parallel iteration in the scheduler which is part of #5694.  Adding analysis tool support for this will be done separately.
Updates all replays (whether as-traced or as-previously) to consider DEPENDENCY_TIMESTAMPS to indicate whether to have one output wait if it gets ahead of another's timestamp.
Removes STATUS_IDLE since we always use STATUS_WAIT.  We're between releases so we can delete from the public enum for this still-under-development component without worrying about binary compatibility.
Adds a missing check for output count mismatches …

i#5843 scheduler: Add replay of the as-traced schedule

---

clients/drcachesim/tests/filter-no-i.templatex
clients/drcachesim/tests/offline-filter-no-i.templatex
clients/drcachesim/tools/basic_counts.cpp

Fixes TID tracking in basic counts which is broken for data-only traces.
The breakage was caused by the recently submitted PR #6022.
Issue: #6020

i#6020: Fix TID tracking in basic_counts.

---

clients/drcachesim/analyzer.h

Fixes incorrect args to std::move. This was another bug introduced in PR #6022.
Issue: #6020

i#6020: Fix incorrect args to std::move.

---

clients/drcachesim/analyzer.h

Cleans up constructors of analyzer_worker_data_t,
analyzer_shard_data_t and analyzer_tool_shard_data_t.
Deletes copy constructor and assignment operator where we do not
want them. Removes the move constructor for analyzer_shard_data_t
since we do not need it; we do not store analyzer_shard_data_t in a
vector unlike analyzer_tool_shard_data_t and analyzer_worker_data_t.
Move or copy constructors are required for use with std::vector since
it may need to resize.
Adds comment to document an explanation where needed.
Issue: #6020

i#6020: Cleanup analyzer internal data constructors

---

clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h

Adds the TID to the basic_counts_t::count_snapshot_t struct. This is to
allow the tool to figure out the TID the snapshot belongs to if needed.
Issue: #6020

i#6020: Add TID to basic counts interval snapshot

---

clients/drcachesim/analysis_tool.h
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp
clients/drcachesim/tools/basic_counts.cpp

Provides instr counts cumulative till an interval and the incremental delta vs
the previous interval, in the analysis_tool_t::interval_state_snapshot_t
struct. This makes it easier for tools to compute per-kilo instr metrics,
without having to duplicate instr counting for intervals.
Also, adds comparison of the interval framework provided value with the
basic counts value, under the verbose flag.
Issue: #6020

i#6020 interval analysis: Provide convenient instr counts

---

core/arch/riscv64/riscv64.asm

This patch implemented `dr_call_on_clean_stack` for RV64.
Issue: #3544

i#3544 RV64: Implemented dr_call_on_clean_stack

---

clients/drcachesim/analysis_tool.h
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp

Adds to the print_interval_results() doc that tools should avoid free-ing memory
or modifying global state, so that the analyzer framework can invoke it multiple
times. This is to keep open the possibility of the framework printing interval results
for each shard separately in the future by invoking this API multiple times.
Separately: Adds missing comparison for instr_count_delta and instr_count_cumulative
to recorded_snapshot_t::operator==().
Issue: #6020

i#6020: Document possible multiple print_interval_results calls

---

core/arch/interp.c
core/arch/riscv64/riscv64.asm

This patch implemented the following global assembly functions for RV64:
1. `dr_app_start`
2. `dr_app_take_over`
3. `dr_app_running_under_dynamorio`
4. `dynamorio_app_take_over`
Issue: #3544

i#3544 RV64: Implemented more global assembly functions

---

core/arch/riscv64/memfuncs.asm

This patch implements `memcpy` and `memset` for RV64.
`memset` is used in `drrun` when parsing config files at startup. After this patch, it can successfully parse the config file, and then segfaults in `execv`(expected, as the RV64 port is far from complete).
Issue: #3544

 i#3544 RV64: Implemented a naive version of memfuncs

---

core/arch/riscv64/riscv64.asm

This commit introduces the following change:
- Implemented dynamorio-clone
Issue: #3544

i#3544 RV64: Implemented dynamorio-clone

---

suite/runsuite_common_pre.cmake

If cmake 3.17+ is in use, enables retrying of failed tests up to 3x with any one of them passing resulting in an overall pass.  This avoids flaky tests marking the whole suite red, which is even more problematic with merge queues.
All of our Github Actions platforms (macos-11, windows-2019, ubuntu-20.04, ubuntu-22.04) have cmake 3.26+ so this is enabled for all of our GA CI tests.
Tested:
I made a test which fails 3/4 of the time:
```
add_test(bogus bash -c "exit \$((RANDOM % 4))")
```
I made it easy to run just this test (gave it a label; disabled other builds, etc.) for convenience and then ran:
```
$ ctest -VV -S ../src/suite/runsuite.cmake,64_only
```
Which resulted in:
```
test 1
Start 1: bogus
1: Test command: /usr/bin/bash "-c" "exit $((RANDOM % 4))"
1: Working Directory: …
```

i#2204: Retry flaky tests in suite

---

core/arch/riscv64/riscv64.asm

Some fixes and improvements to `call_switch_stack` for RV64, including:
1. Reformatted a bit
2. Used `mv` instead of `addi` for readability
3. Fixed errors of stack swapping
Issue: #3544

i#3544 RV64: Some fixes and improvements to call_switch_stack

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h

Adjusts virtual interfaces to allow derived classes to cleanly modify the
logic for handling merging of interval snapshots.
Issue: #6020

i#6020 interval analysis: Adjust virtual interface

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/speculator.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Changes speculation support to use distinct layers, allowing an inner speculation to roll back to the next-outermost interruption point.
Adds unit tests.
Issue: #5843

i#5843 scheduler: Add nested speculation layers

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds timestamp ordering to dynamic scheduling.  Accomplishes this by using a priority queue keyed by the last timestamp seen in an input relative to the minimum timestamp across all inputs for that workload, to allow mixing workloads in the same queue.
Adds a test and updates other tests and tools to enable timestamps.
Also tested manually on some larger traces as sanity tests that no errors are reported at least.
Issue: #5843

i#5843 scheduler: Add time dependencies to dynamic schedules

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds support for different input priorities.  This is easily done using the priority queue added for timestamp ordering simply by adding the input priority value to the priority queue comparator.
Removes the FIFO-only queue as priorities should be used with and without timestamps, using the priority queue for all cases.
Issue: #5843

i#5843 scheduler: Add priority support

---

clients/drcachesim/analysis_tool.h
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/tests/offline-interval-count-output.templatex
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h

Adds TID to the interval_state_snapshot_t base struct, so that tools do not need to track it themselves if they need it. The TID is stored as "shard_id" which in future may contain a different id if we define shards differently.
Also changes interval_id to always be a positive integer, which makes some things simpler downstream.
Issue: #6020

i#6020 interval analysis: add TID and positive interval_id

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds support for inputs bound to a subset of the available cores. This is implemented by repeatedly popping the priority queue of ready inputs until one able to run on the core in question is found; the rest are re-added to the queue.
Adds a test.
Issue: #5843

i#5843 scheduler: Add core binding support

---

core/drlibc/drlibc_module_elf.c
core/unix/loader.c

This patch added ELF header checks for RISC-V.
Issue: https://github.com/DynamoRIO/dynamorio/issues/3544

i#3544 RV64: Added machine type support for ELF hdr verification

---

clients/drcachesim/tests/offline-interval-count-output.templatex
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h

Avoids tracking unique pc addresses in counters_t for interval state snapshots.
This takes up excessive memory on apps with a lot of threads, even if the
interval count is not that high. For apps with O(1K) threads and O(100) intervals,
the number of tracked "unique" pcs goes up by O(10^5), causing memory
usage to grow even beyond 300GB in some cases.
Issue: #6020

i#6020 interval analysis: optimize basic_counts memory

---

core/arch/aarch64/aarch64.asm

This patch fixed a typo in AArch64 `dr_longjmp` assembly function.
`int dr_longjmp(dr_jmp_buf_t *buf, int val);`
The expected behavior of `dr_longjmp` is to return 1 if `val` is 0, and `val` otherwise. So we should check arg2 (`w1`) instead of arg1 (`w0`). In most cases, this typo won't cause an issue, I guess that's why we didn't notice it before.

AArch64: Fixed dr_longjmp

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

```
ADCLB   <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
ADCLT   <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
BDEP    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
BEXT    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
BGRP    <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
EORBT   <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
EORTB   <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SABA    <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SBCLB   <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SBCLT   <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SQDMULH <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SQRDMLAH <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SQRDMLSH <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
SQRDMULH <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
TBX     <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
UABA    <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>
```
issue: #3044

i3044: AArch64 SVE2 codec: Add 3 operand instructions

---

api/docs/debugging.dox

Augments the debugging documentation with an example gdb session to help make it more clear what one of the simplest ways to debug client code is.

Add example gdb session to debugging docs

---

README.md

Fixes link to the API samples page on dynamorio.org in the README file.

Fix link to API samples in README

---

core/unix/signal.c

When building dynamorio with -Wmaybe-uninitialized, the compiler reported the error. At a first glance, it looks like this is a false positive, as the variables are initialized by either of the above branches. However, it does not hurt to initialize them to make the compiler happy.
This is also helps when packaging for distros, as there usually this warning is enabled.

initialize kernel_sigaction_t variables in signal.c

---

clients/drcachesim/tests/offline-interval-count-output.templatex
clients/drcachesim/tools/basic_counts.cpp

Ensures that we do not track unique PCs in the combined interval
snapshots. Since the shard-local snapshots themselves do not track
unique pcs, the combined snapshot also wouldn't have anything in
the unique pc set. But we need to explicitly disable unique pcs
tracking so that we skip printing that field. This was missing in the
original PR #6097.
Also fixes expected regex of basic counts interval output so that only
digits and leading white-spaces are accepted at the beginning of each
line. Otherwise we aren't able to detect that the unique pc addrs line
in the counters output is still present.
Also fixes a regression due to #6113 which causes a regex match
failure in case only a single interval is output for the whole trace.
Issue: #6020, #6112

i#6020 interval analysis: Fix interval counts regex

---

ext/drsyms/CMakeLists.txt

We already create cmake import targets for the vendored libraries. By that, also use them in target_link_libraries instead of using the full path. In most cases this does not have any effect, but it helps when debugging linking issues. It also makes the logic easier to read.

drsyms: link against import targets

---

core/annotations.c

Removes the hardcoded path to the two Valgrind headers included in core/annotations.c to use the copy in the build directory instead. This gives more flexibility for DynamoRIO sources embedded in other build systems.

Generalize annotation include path

---

suite/tests/runmulti.cmake

Removes a message line accidentally left in PR #6113.
Issue: #6112

i#6112 runmulti: Remove diagnostic print

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Generalizes the schedule file checks to make it easier to invoke them from subclasses:
+ Pass in the synthetic shard data.
+ Make the shard data destructor virtual.
Issue: #6107

i#6107 sched count bug: Generalize sched checks for subclasses

---

core/arch/atomic_exports.h
core/fragment.c

This patch fixed some atomic functions and macros of the RV64 port.
Issue: https://github.com/DynamoRIO/dynamorio/issues/3544

i#3544 RV64: Fixed atomic functions and macros

---

core/unix/tls_linux_risc.c

Removes a superfluous return statement to satisfy clang-tidy.

Fix clang-tidy warning about return from void func

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/burst_aarch64_sys.cpp
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/burst_malloc.cpp
clients/drcachesim/tests/burst_maps.cpp
clients/drcachesim/tests/burst_noreach.cpp
clients/drcachesim/tests/burst_reattach.cpp
clients/drcachesim/tests/burst_replace.cpp
clients/drcachesim/tests/burst_replaceall.cpp
clients/drcachesim/tests/burst_static.cpp
clients/drcachesim/tests/burst_threadfilter.cpp
clients/drcachesim/tests/burst_threads.cpp
clients/drcachesim/tests/burst_traceopts.cpp
clients/drcachesim/tests/cache_miss_analyzer_test.cpp
clients/drcachesim/tests/drcachesim_unit_tests.cpp
clients/drcachesim/tests/histogram_test.cpp
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/raw2trace_io.cpp
clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tests/reuse_distance_test.cpp
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tests/test_helpers.cpp
clients/drcachesim/tests/test_helpers.h
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp
clients/drcachesim/tests/view_test.cpp
suite/tests/CMakeLists.txt

Adds a library test_helpers for drcachesim tests which provides main() and calls disable_popups() to avoid Windows assert and exception pop-up windows hanging the test suite.  Tests now define a test_main() which is called by the test_helpers main().  (The DR core test suite has its own popup disabling code but it is complex to link that into
the standalone drcachesim tests.)
For _tmain, we compile test_helpers.cpp separately to access its disable_popups() but with a define to disable main().
Issue: #6131

i#6131 hang win32: Disable popups in drcachesim tests

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.h
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

```
ADDHNB  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
ADDHNT  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
PMULLB  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
PMULLT  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
RADDHNB <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
RADDHNT <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
RSUBHNB <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
RSUBHNT <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SABALB  <Zda>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SABALT  <Zda>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SABDLB  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SABDLT  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SADDLB  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SADDLBT <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SADDLT  <Zd>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>
SADDWB  <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Tb>
SADDWT  <Zd>.<Ts>, <Zn>.<Ts>, <Zm>.<Tb>
SMLALB …
```

i#3044: AArch64 SVE2 codec: Add 3 different operand instructions

---

suite/runsuite_wrapper.pl

Adds the tool.drcacheoff.gencode test to the 32-bit windows test failure ignore list.
Issue: #6131

i#6131 hang win32: Add drcacheoff.gencode to ignore list

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/burst_gencode.cpp
suite/tests/CMakeLists.txt

The dr$sim unit tests, tests using runcmp (such as nearly all
drcacheoff.* tests), and native tests had no drrun or runstats or
ctest timeout set, leaving them the too-long default 10 minutes,
which combined with the try-3-times results in 30 minutes for a
hung test.  We set the 90s timeout here for these tests.
Issue: #6131

i#6131 hang win32: Add test timeouts to dr$sim and runcmp tests

---

clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Adds raw2trace stats for earliest and latest trace timestamp. These are used to compute the trace's wall-clock duration which is printed at the end of raw2trace decomposition, along with other raw2trace stats.
It may be useful for the user to know the trace's wall-clock duration to compute the value for `-trace_interval` (which is the length of each trace interval for interval analysis) to get the required number of total intervals.
Issue: #6020

i#6020: Add raw2trace stat for trace duration

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

The svemem_gpr_simm9_vl operand was setting the memory transfer size to the current vector length, which is correct for Z register loads and stores but not P register loads and stores.
The encoder/decoder will now detect which kind of register is being accessed and set the correct size.
Issues: #3044

i#3044 AArch64 SVE codec: Fix LDR/STR <P> mem size

---

api/docs/tutorial.dox

Fix for the register name used in bbdynsize7 tutorial: renamed `REG_XDI` to `DR_REG_XDI`
Tutorial:
https://dynamorio.org/API_tutorial_bbdynsize7.html

fix register name in bbdynsize7 tutorial

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/burst_futex.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/tracer.cpp

The 64-bit system call function id base was accidentally put in as decimal rather than hex.  We fix that here.  Any traces created in between this and PR #6132 that contain futex should be considered ill-formed with respect to function markers.
Issue: #5843

i#5843 scheduler: Fix syscall function id base

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec.h
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

```
FMLALB  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
FMLALT  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
FMLSLB  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
FMLSLT  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
SMLALB  <Zda>.D, <Zn>.S, <Zm>.S[<index>]
SMLALB  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
SMLALT  <Zda>.D, <Zn>.S, <Zm>.S[<index>]
SMLALT  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
SMLSLB  <Zda>.D, <Zn>.S, <Zm>.S[<index>]
SMLSLB  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
SMLSLT  <Zda>.D, <Zn>.S, <Zm>.S[<index>]
SMLSLT  <Zda>.S, <Zn>.H, <Zm>.H[<index>]
SMULLB  <Zd>.D, <Zn>.S, <Zm>.S[<index>]
SMULLB  <Zd>.S, <Zn>.H, <Zm>.H[<index>]
SMULLT  <Zd>.D, <Zn>.S, <Zm>.S[<index>]
SMULLT  <Zd>.S, <Zn>.H, <Zm>.H[<index>]
SQDMLALB <Zda>.D, <Zn>.S, <Zm>.S[<index>] …
```

i#3044: AArch64 SVE2 codec: add instructions with indexes

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

```
CADD    <Zdn>.<Ts>, <Zdn>.<Ts>, <Zm>.<Ts>, <const>
CDOT    <Zda>.<Ts>, <Zn>.<Tb>, <Zm>.<Tb>, <const>
CMLA    <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>, <const>
RSHRNB  <Zd>.<Ts>, <Zn>.<Tb>, #<const>
RSHRNT  <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SHRNB   <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SHRNT   <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SLI     <Zd>.<Ts>, <Zn>.<Ts>, #<const>
SQCADD  <Zdn>.<Ts>, <Zdn>.<Ts>, <Zm>.<Ts>, <const>
SQRDCMLAH <Zda>.<Ts>, <Zn>.<Ts>, <Zm>.<Ts>, <const>
SQRSHRNB <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SQRSHRNT <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SQRSHRUNB <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SQRSHRUNT <Zd>.<Ts>, <Zn>.<Tb>, #<const>
SQSHL   <Zdn>.<Ts>, <Pg>/M, <Zdn>.<Ts>, #<const>
SQSHLU  <Zdn>.<Ts>, <Pg>/M, …
```

i#3044: AArch64 SVE2 codec: Add instructions with a const

---

clients/drcachesim/tracer/raw2trace.cpp

To avoid issues building on other platforms (as evidenced by a user list email), we add an include of the core's syscall.h for the maybe-blocking syscall feature added by PR #6132.
Issue: #5843

i#5843 scheduler: Include core syscall.h

---

core/ir/instr_api.h

Add the SVE condition code aliases to dr_pred_type_t.
In order to distinguish the SVE NONE condition from the existing DR_PRED_NONE member, the new SVE condition aliases all start with "DR_PRED_SVE_":
DR_PRED_NONE        No predicate is present.
DR_PRED_SVE_NONE    All active elements were false or there were no active
elements.
Issue: #3044

i#3044 Add AArch64 SVE condition aliases

---

clients/drcachesim/tools/func_view.cpp
clients/drcachesim/tools/func_view.h

Augments the func_view tool to handle the syscall-related function markers.
The func_view tool is expected to print details of only the functions that the user specified explicitly in -record_function, and not the system calls like futex that also use function markers.
Tested locally with a trace that has futex calls.

Handle syscall-func markers in func_view.

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tracer/raw2trace.cpp

The #4343 namespace change PR #6169 changed suite/tests/rseq.c to be C++ which somehow triggered two problems with i-filtered traces.  To separate the fixes for those from the large namespace change we commit them separately:
+ Do not try to roll back rseq for i-filtered traces.
+ Do not complain about signal placement vs test-app annotations for i-filtered traces.
We rely on the rseq-filter test in PR #6169 as a test and do not attempt to add a different test here.
Issue: #4343

Fix i-filtered trace issues

---

core/unix/os_exports.h

According to RISCV processor specific application binary interface, psABI : https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc "tp containing the address one past the end of the TCB." further documentation for that can be found in glibc sources sysdeps/riscv/nptl/tls.h:
/* Return the address of the dtv for the current thread.  */
(((tcbhead_t *) (READ_THREAD_POINTER () - TLS_TCB_OFFSET))[-1].dtv)

i#3544 fix: risc-v TCB offset from tp register is negative according to psABI

---

clients/drcachesim/tools/invariant_checker.cpp

In some internal tests we modify the TID of some entries to test the schedule file invariant check. This inadvertently inverts the order of some entries for this check if the new synthetic TID matches with an existing real TID. By sorting also by CPU id, we ensure consistent ordering.

Sort also by CPU for schedule file invariant check

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Avoids an out-of-bounds vector access by checking for init value. This occurs in the case when an output starts in the wait state.
Modifies an existing scheduler unit test to test this case.

Fix out-of-bounds vector access in Scheduler

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

LDNT1SB { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
LDNT1SB { <Zt>.S }, <Pg>/Z, [<Zn>.S{, <Xm>}]
LDNT1SH { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
LDNT1SH { <Zt>.S }, <Pg>/Z, [<Zn>.S{, <Xm>}]
LDNT1SW { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
Issue: #3044

i#3044 Add AArch64 SVE codec: Gather load non-temporal signed

---

ext/drx/scatter_gather_x86.c

Fixes a build breakage introduced in PR #6173 with an invalid include path.
Issue: #5844

i#5844 scatter-gather: Fix broken include path

---

api/samples/callstack.cpp
api/samples/inscount.cpp
api/samples/opcode_count.cpp
api/samples/stl_test.cpp
clients/drcov/postprocess/drcov2lcov.cpp
clients/drcpusim/drcpusim.cpp
clients/drcpusim/options.cpp
clients/drcpusim/options.h
ext/drgui/drgui_main_window.cpp
ext/drgui/drgui_main_window.h
ext/drgui/drgui_options_interface.h
ext/drgui/drgui_options_window.cpp
ext/drgui/drgui_options_window.h
ext/drgui/drgui_tool_interface.h
ext/drgui/main.cpp
make/style_checks/exclude
make/style_checks/scripts/rules/required_namespaces.tcl

Adds dynamorio::<name> namespaces to drcpusim, drgui, drcov2lcov, and our C++ samples.
Adds a new vera++ check that all C++ files have namespaces; it excludes droption which is still not converted.
It only checks that namespace declarations are present, catching the most common error of a new file being
added but omitting namespaces.  it does not try to check that all code is inside the namespace (there are multiple
exceptions there to handle and it gets complex).
Issue: #4343

i#4343 namespaces: Add namespaces to drcpusim, drgui, drcov, samples

---

api/samples/stl_test.cpp
clients/drcachesim/tests/allasm_aarch64_flush.asm
clients/drcachesim/tests/allasm_aarch64_prefetch.asm
core/arch/asm_defines.asm
core/ir/aarch64/codec.c
core/unix/os.c
suite/tests/CMakeLists.txt
suite/tests/api/drdecode_aarch64.c
suite/tests/api/ibl-stress.c
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.h
suite/tests/client-interface/drsyms-test.dll.cpp
suite/tests/client-interface/drwrap-drreg-test.appdll.c
suite/tests/client-interface/drwrap-test.appdll.c
suite/tests/client-interface/stolen-reg-index.c
suite/tests/common/allasm_aarch64_cache.asm
suite/tests/common/allasm_aarch64_isa.asm
suite/tests/tools.c
suite/tests/tools.h

Enables BUILD_TESTS to compile for M1: a combination of fixing and disabling tests.  Many issues came from assembler and pre-processor differences.
Issue: #5383

i#5383 mac a64, part 4: Enable tests to build

---

api/samples/stl_test.cpp
clients/drcachesim/tests/allasm_aarch64_flush.asm
clients/drcachesim/tests/allasm_aarch64_prefetch.asm
core/arch/aarch64/aarch64.asm
core/arch/aarchxx/emit_utils.c
core/arch/asm_defines.asm
core/ir/aarch64/codec.c
core/unix/os.c
core/unix/os_exports.h
core/unix/tls_macos.c
suite/tests/CMakeLists.txt
suite/tests/api/drdecode_aarch64.c
suite/tests/api/ibl-stress.c
suite/tests/api/ir_aarch64.c
suite/tests/api/ir_aarch64.h
suite/tests/client-interface/drsyms-test.dll.cpp
suite/tests/client-interface/drwrap-drreg-test.appdll.c
suite/tests/client-interface/drwrap-test.appdll.c
suite/tests/client-interface/stolen-reg-index.c
suite/tests/common/allasm_aarch64_cache.asm
suite/tests/common/allasm_aarch64_isa.asm
suite/tests/tools.c
suite/tests/tools.h

Fixes global references in aarch64.asm which were loading the value instead of the address (the Linux a64 assembler auto-magically gives the address whether using ADD or LDR!).
Fixes and clarifies the Mac64 x86 and arm TLS slots vs offsets.
Uses gettimeofday() for query_time_seconds() instead of SYS_gettimeofday.
Removes an invalid hardcoded 0 sysnum for global_do_syscall.
Issue: #5383

i#5383 mac a64, part 5: Get hello,world to run

---

core/arch/aarch64/aarch64.asm
core/unix/os.c
core/unix/signal.c
core/unix/signal_macos.c
core/unix/signal_private.h
core/unix/tls_macos.c
suite/tests/CMakeLists.txt
suite/tests/tools.c

8 of the 13 tests on Mac AArch64 labeled "OSX" fail prior to this PR. Here we fix the following:
+ Syscall success is indicated by the carry flag just like x86 Mac
+ Handle sigreturn with its extra parameters just like x86 Mac
+ Fix signal handler parameters
+ Fix stolen register support in signal contexts
+ Use MAP_JIT and pthread_jit_write_protect_np for +rwx gencode in tests
+ Use DYLD_LIBRARY_PATH on Mac in tests
Now all 13 tests pass:
```
---------------------------------------------------------------------------------------
$ ctest -j 5 -L OSX
1/13 Test  #13: code_api|common.fib ................................  Passed  0.59 sec
2/13 Test #243: code_api|libutil.frontend_test .....................  Passed  0.63 sec
3/13 Test #231: code_api|api.ir .................................... …
```

i#5383 mac a64, part 6: Get OSX-labeled tests to succeed

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

```
CDOT    <Zda>.D, <Zn>.H, <Zm>.H[<imm>], <const>
CDOT    <Zda>.S, <Zn>.B, <Zm>.B[<imm>], <const>
CMLA    <Zda>.H, <Zn>.H, <Zm>.H[<imm>], <const>
CMLA    <Zda>.S, <Zn>.S, <Zm>.S[<imm>], <const>
SQRDCMLAH <Zda>.H, <Zn>.H, <Zm>.H[<imm>], <const>
SQRDCMLAH <Zda>.S, <Zn>.S, <Zm>.S[<imm>], <const>
```
issue: #3044

i#3044: AArch64 SVE2 codec: add instructions with consts and indexes

---

core/ir/aarch64/codec_sve.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

This patch adds the appropriate macros, tests and codec entries to decode and encode the following instructions:
```UZP1    <Zd>.Q, <Zn>.Q, <Zm>.Q (UZP1-Z.ZZ-Q)```
```UZP2    <Zd>.Q, <Zn>.Q, <Zm>.Q (UZP2-Z.ZZ-Q)```
```ZIP1    <Zd>.Q, <Zn>.Q, <Zm>.Q (ZIP1-Z.ZZ-Q)```
Issue: #3044

i#3044 AArch64 SVE codec: Add UZP1, UZP2, ZIP1 Q variants

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

This patch adds the appropriate macros, tests and codec entries to encode and decode the following variants:
```
MATCH   <Pd>.<Ts>, <Pg>/Z, <Zn>.<Ts>, <Zm>.<Ts>
NMATCH  <Pd>.<Ts>, <Pg>/Z, <Zn>.<Ts>, <Zm>.<Ts>
URECPE  <Zd>.S, <Pg>/M, <Zn>.S
URSQRTE <Zd>.S, <Pg>/M, <Zn>.S
WHILEGE <Pd>.<Ts>, <R><n>, <R><m>
WHILEGT <Pd>.<Ts>, <R><n>, <R><m>
WHILEHI <Pd>.<Ts>, <R><n>, <R><m>
WHILEHS <Pd>.<Ts>, <R><n>, <R><m>
WHILERW <Pd>.<Ts>, <Xn>, <Xm>
WHILEWR <Pd>.<Ts>, <Xn>, <Xm>
```
issue: #3044

i#3044 AArch64 SVE2 codec: Add misc predicate instructions

---

clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/common/options.cpp
clients/drcachesim/common/trace_entry.h
clients/drcachesim/scheduler/scheduler.h

By adding Doxygen docs to namespace declarations we can shrink many of
the awkwardly long references in Doxygen comments.  Some still produce
errors if not qualified which I do not understand so those are left.
I only updated a couple of key headers which contained the worst
instances.
Fixes a clang-tidy-found unused using declaration.
This completes the namespace cleanup.
Fixes #4343

i#4343 namespaces: Shrink Doxygen qualifications where possible

---

api/docs/API.doxy
clients/drcachesim/tests/burst_replaceall.cpp

Adds missing include for `stdint.h` in one file that relies on `math.h`, which breaks with GCC 13.1.
Also, removes a redundant default-value assignment for DOT_TRANSPARENT, which is deprecated
and would abort in the newest Doxygen.

Fix build with GCC 13.1 and Doxygen 1.9.7

---

clients/drcachesim/tracer/raw2trace.h
core/ir/decode.h
core/ir/instr_shared.c
core/ir/x86/encode.c

Avoids non-regular-encode code paths which do not set a final PC and thus have a null PC value from manipulating that PC in opnd_type_ok().
Documents that get_encoding_info() may not find the same template as when called with the real final PC.  Documents in key callers that this is fine.
Adjusts the raw2trace unit test helper to use a non-null final PC.
Fixes #6196

i#6196: Avoid adding to a null pointer

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/ir/aarch64/codec.c
core/ir/aarch64/codec_v86.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-v86.txt
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_v86.c

This patch adds the appropriate macros, tests and codec entries to decode and encode the following instructions:
```
LDG     <Xt>, [<Xn|SP>, #<simm>]
ST2G    <Xt>, [<Xn|SP>], #<simm>
ST2G    <Xt>, [<Xn|SP>, #<simm>]!
ST2G    <Xt>, [<Xn|SP>, #<simm>]
STG     <Xt>, [<Xn|SP>], #<simm>
STG     <Xt>, [<Xn|SP>, #<simm>]!
STG     <Xt>, [<Xn|SP>, #<simm>]
STZ2G   <Xt>, [<Xn|SP>], #<simm>
STZ2G   <Xt>, [<Xn|SP>, #<simm>]!
STZ2G   <Xt>, [<Xn|SP>, #<simm>]
STZG    <Xt>, [<Xn|SP>], #<simm>
STZG    <Xt>, [<Xn|SP>, #<simm>]!
STZG    <Xt>, [<Xn|SP>, #<simm>]
STGP    <Xt>, <Xt2>, [<Xn|SP>], #<simm>
STGP    <Xt>, <Xt2>, [<Xn|SP>, #<simm>]!
STGP    <Xt>, <Xt2>, [<Xn|SP>, #<simm>]
```
Issue #3044

i#3044 AArch64 SVE codec: Add memory tagged load/stores

---

core/arch/riscv64/proc.c
core/unix/include/syscall_linux_riscv64.h

We need to flush the icache on all harts, which is not feasible for FENCE.I, so we use `SYS_riscv_flush_icache` to let the kernel do this. Note this is also how gcc implements `__builtin___clear_cache`.
Issue: https://github.com/DynamoRIO/dynamorio/issues/3544

i#3544 RV64: Implemented machine_cache_sync

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v86.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-v86.txt
suite/tests/api/ir_aarch64_v86.c

```
GMI     <Xd>, <Xn|SP>, <Xm>
IRG     <Xd|SP>, <Xn|SP>{, <Xm>}
SUBP    <Xd>, <Xn|SP>, <Xm|SP>
SUBPS   <Xd>, <Xn|SP>, <Xm|SP>
ADDG    <Xd|SP>, <Xn|SP>, #<imm1>, #<imm2>
SUBG    <Xd|SP>, <Xn|SP>, #<imm1>, #<imm2>
DC GVA, <Xt>
DC GZVA, <Xt>
```
Issue #3044

i#3044 AArch64 SVE codec: Data-processing and DC memory tagged

---

tools/drdeploy.c

The old way to trigger detach on the Windows platform is the no-longer-supported "drcontrol" front-end. 
Re-exposing the detach feature in drconfig front-end on the Windows platform.
The following briefly describes my manual testing process, and I'll continue to submit an automated testing tool in a new PR soon.
I wrote my own continuously running example as a manual test case for DynamoRIO, which counts the time of summing the first 1 billion numbers in real time. I'd like to use the real-time output of the test case to present the running state of the program.
```
#include <iostream>
#include <chrono>
#define LOOPCOUNT 100000;
// Function to perform a computationally intensive task
void performTask()
{
//calculate the sum of the first 1 billion numbers
long long unsigned sum = 0;
for …
```

i#725: Re-expose the Windows detach in drconfig

---

core/arch/riscv64/emit_utils.c

Implemented `exit_cti_reaches_target()` and `patch_branch()`, which are required for execution of a simple program.
Issue: #3544

i#3544 RV64: Implemented exit_cti_reaches_target and patch_branch

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h
clients/drcachesim/tools/filter/cache_filter.cpp
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/raw2trace.cpp

Adds OFFLINE_FILE_TYPE_BIMODAL_FILTERED_WARMUP for traces that are filtered before the TRACE_MARKER_TYPE_FILTER_ENDPOINT marker and unfiltered after it.
Adds invariant_checker checks to make sure the new file type and the filter end-point marker are
always present together, or not at all.
Adds a test that the record filter adds the filter end-point marker also for threads that start after
the filtering stop_timestamp. Adds a shard_count member to basic_counts_t::counters_t to make
it easier to write the new test without hard-coding count of threads in the test.
Fixes: #6164

i#6164: Add new file type for bimodal filtered traces

---

clients/drdisas/test_simple.template
core/ir/aarch64/codec.c
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

For the current decode/encode functions of:
```
LDR <Zt>, [<Xn|SP>{, #<imm>, MUL VL}]
LDR <Pt>, [<Xn|SP>{, #<imm>, MUL VL}]
STR <Zt>, [<Xn|SP>{, #<imm>, MUL VL}]
STR <Pt>, [<Xn|SP>{, #<imm>, MUL VL}]
PRFB <prfop>, <Pg>, [<Xn|SP>{, #<imm>, MUL VL}]
PRFH <prfop>, <Pg>, [<Xn|SP>{, #<imm>, MUL VL}]
PRFW <prfop>, <Pg>, [<Xn|SP>{, #<imm>, MUL VL}]
PRFD <prfop>, <Pg>, [<Xn|SP>{, #<imm>, MUL VL}]
```
Vector indexing is used in the memory operand at the IR level. However
the IR must always refer to the address in terms of the base register
value plus a byte offset displacement. This patch changes the
decode/encode functions for these instructions to expect byte offsets
at the IR level, converting to vector length offsets within the codec.
Issues #3044, #5365

i#3044 AArch64 SVE codec: change LDR/STR and PRF to use byte offsets

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Fixes a problem with the implementation of context switching on a blocking syscall: it was being done immediately upon seeing the maybe-blocking marker, which is right after the syscall instruction. This resulted in recording the syscall instruction ordinal as the switch point, when that ordinal is supposed to be exclusive and so needs to be right before the subsequent instruction.
Adds a test that ensures we don't switch until after all the markers after a blocking syscall.
Issue: #5843

i#5843 scheduler: Delay switch to instr after blocking syscall

---

clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds read-ahead to timestamps when replaying, to match record ordinals and not just instruction ordinals at start and switch points when recording.
Adds use of the just-read timestamp when skipping in the reader, to avoid losing the timestamp when the scheduler has read ahead.
Adds recording of the ordinals at switch points in the unit tests for comprehensive testing of switch points instead of just testing thread sequences.
Fixes several tests which were passing incorrect flags.
Issue: #5843

i#5843 scheduler: Fix record-replay ordinal mismatches

---

api/docs/release.dox
clients/drcachesim/common/memref.h
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/cache_simulator.h
clients/drcachesim/simulator/cache_stats.h
clients/drcachesim/simulator/caching_device_block.h
clients/drcachesim/simulator/caching_device_stats.h
clients/drcachesim/simulator/snoop_filter.h
clients/drcachesim/tests/drcachesim_unit_tests.cpp
clients/drcachesim/tests/reuse_distance_test.cpp
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h
clients/drcachesim/tools/func_view.h
clients/drcachesim/tools/opcode_mix.cpp
clients/drcachesim/tools/opcode_mix.h
clients/drcachesim/tools/reuse_distance.cpp
clients/drcachesim/tools/reuse_distance.h
clients/drcachesim/tools/reuse_time.cpp
clients/drcachesim/tools/reuse_time.h
clients/drcachesim/tools/syscall_mix.cpp
clients/drcachesim/tools/syscall_mix.h

Replaces the {u,}int_least64_t types used throughout the drcachesim code base with the more-precise {u,}int64_t types.  We were treating them as 64-bit anyway in our printf codes and other places, and all our supported toolchains have precise 64-bit types.
Adds a note to the release docs on the change.

Replace {u,}int_least64_t with {u,}int64_t

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new stream API get_input_workload_ordinal() which allows the output stream to figure out which workload its current input stream came from.
Adds a couple of sanity tests.
Issue: #5843

i#5843 scheduler: Add query of input workload

---

suite/tests/client-interface/attach_blocking.expect
suite/tests/client-interface/attach_test.dll.c
suite/tests/client-interface/attach_test.template

Removes the printing of "event_post_attach" in the client.attach test, as it had non-deterministic ordering versus the "thread init" printing (and runall.cmake requires "thread init").  Replaces with a boolean check and error print at exit to ensure we saw the attach event.
This completes the base attach feature.  Future problems should open new issues.
Fixes #725

i#725 attach: Remove flakiness from attach test

---

api/docs/release.dox
clients/drcachesim/common/memref.h
clients/drcachesim/common/trace_entry.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/reader.h
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/memref_gen.h
clients/drcachesim/tests/offline-legacy-int-offs.templatex
clients/drcachesim/tools/basic_counts.h
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tools/view.cpp

Adds a new "indirect_branch_target" field to memref_t.instr. Converts the new TRACE_MARKER_TYPE_BRANCH_TARGET marker to an internal record used by reader_t to fill in the new field.
Updates the invariant checker and test.
Updates the legacy test's marker counts.
Updates the documentation.
Issue: #5490

i#5490 ib targets: Add memref ind branch target field

---

clients/drcachesim/tests/scheduler_launcher.cpp

Switches from using the tid in scheduler_launcher to distinguish inputs to the input ordinal.  Tid values can be duplicated so they should not be used as unique identifiers across workloads.
Tested: No automated test currently relies on the launcher; it is there for experimentation and as an example for how to use the scheduler, so we want it to use the recommended techniques.  I ran it on the threadsig app and confirmed record and replay are using ordinals:
```
$ rm -rf drmemtrace.*.dir; bin64/drrun -stderr_mask 12 -t drcachesim -offline -- ~/dr/test/threadsig 16 2000 && bin64/drrun -t drcachesim -simulator_type basic_counts -indir drmemtrace.*.dir > COUNTS 2>&1 && clients/bin64/scheduler_launcher -trace_dir drmemtrace.*.dir/trace -num_cores 4 -sched_quantum 2000 -record_file record.zip …
```

i#5843 scheduler: Use input instead of tid in launcher

---

core/CMakeLists.txt
core/ir/riscv64/codec.py
make/CMake_riscv64_gen_codec.cmake

Currently, all C files that depend on header files generated by codec.py will be recompiled every time we run `make`, even if no changes have been made to those headers, causing headaches on weak devices. This issue is caused by two reasons:
1. opcode_names.h does not exist in RISC-V, but was added to `RISCV64_CODEC_GEN_SRCS` by mistake, so the primary custom command output (i.e. opcode_api.h) will be deleted to trigger a regeneration.
2. If codec.py gets modified, it will cause the header files to be regenerated even if the generated files have not changed.
This patch deletes opcode_names.h from `RISCV64_CODEC_GEN_SRCS`, and uses `write_if_changed` to write only files whose content has changed, thus fixing this issue.
Issue: #3544

i#3544 RV64: Fix redundant compilation issue

---

core/arch/arch.h

`core/arch/arch.h:143` is duplicated with `core/arch/arch.h:188`, the definition is identical, which is allowed by C. But it will become different when line 188 adds support for RISC-V, this PR pre-removes the duplicate definition to avoid this issue.

AARCHXX: Remove redundant macro definition

---

clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/reader.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Fixes a boundary case of skipping 1 instruction when the scheduler has already read an instruction record but not yet passed it to the user.
Fixes a boundary case of back-to-back regions of interest.
Adds test cases.
Issue: #5538

i#5538 skip: Fix skip-1-instr and skip-0-instr cases

---

api/docs/download.dox
api/docs/new_release.dox
api/docs/release.dox

Adds a download section for the new 10.0.0 release.
Updates the New Release docs to suggest modifying the download docs at
the same time as the version bump, if doing a single-build release.

Add 10.0.0 download links

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Due to complexities in identifying and removing them, omitting false wow64 syscalls is disabled.
Tested: Ran the windows-test from PR #6165 which was failing every time and confirmed it now passes.
Issue: #6280, #6131
Fixes #6280

i#6280: Do not try to omit wow64 syscalls

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Adds a test case for consecutive window-final branches which reproduces a problem where the final is removed but the penultimate is then not marked taken/untaken.
Updates raw2trace to correctly mark the penultimate.  Also confirmed this fix on the drcacheoff.windows-invar test on aarch64 where it was first observed.
Fixes #6294

i#6294: Handle consecutive window-final branches

---

clients/drcachesim/tests/scattergather-aarch64.templatex
ext/drx/scatter_gather_aarch64.c
suite/tests/client-interface/drx-scattergather-aarch64.cpp
suite/tests/client-interface/drx-scattergather-aarch64.templatex

Adds support to drx_expand_scatter_gather() for SVE scalar+vector scatter store instructions, along with tests.
Issue: #5036

i#5036 A64 scatter/gather, part 2: Expand scalar+vector stores

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tracer/raw2trace.cpp

Before, we wrote out a schedule file record for every timestamp.  But for scheduling we only need to know the thread switch points, so consecutive same-thread records are superfluous.  This will only get worse with more timestamps from #6290.  Here we collapse consecutive same-thread entries in both the serial and cpu schedule files, and update the invariant checker to allow either the old or new type of file.
On simple_app, before (2nd column is tid):
```
$ zcat drmemtrace.*.dir/trace/serial* | od -t d8 -A d -w32 | tail
0002464              1484994    13338489228331182        3               112619
0002496              1484994    13338489228331508        3               112619
0002528              1484994    13338489228337025        3               112886
0002560              1484994 …
```

i#6299: Collapse redundant entries in schedule files

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tracer/tracer.cpp
core/arch/emit_utils_shared.c
core/arch/interp.c
core/ir/instr_shared.c
core/ir/riscv64/instr_create_api.h.in
ext/drbbdup/drbbdup.c
suite/tests/api/ir_riscv64.c
suite/tests/api/ir_riscv64.expect

Implement platform-independent `XINST_CREATE_xxx` macros, also remove APIs that do not make sense for RISC-V.

i#3544 RV64 XINST_CREATE: Implement platform-independent macros

---

core/ir/riscv64/codec.c
core/ir/riscv64/codec.h
core/ir/riscv64/codec.py
core/ir/riscv64/isl/README.md
core/ir/riscv64/isl/rv32c.txt
core/ir/riscv64/isl/rv64c.txt
core/ir/riscv64/isl/rvc.txt
suite/tests/api/ir_riscv64.expect

The RISC-V compressed extension (RVC) contains some instructions that have implicit operands, e.g.:
C.JR expands to `jalr x0, 0(rs1)`; C.JALR expands to `jalr x1, 0(rs1)`.
This patch puts these implicit operands into instr_t.

i#3544 RV64: Include implicit operands in instr_t

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new scheduler output stream interface unread_last_record(). This queues the just-read record for reading later.  This is meant to aid simulators reading one record ahead to the next instruction, but not yet processing it.  The new interface is limited in that it can only be called once at a time and while the output ordinals are fixed up other metrics like the output last timestamp and the input ordinals are not.
Adds a new record type TRACE_TYPE_INVALID for use as a sentinel.
Adds some sanity tests.
Issue: #5843

i#5843 scheduler: Add unread_last_record()

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tests/offline-windows-asm.templatex
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/output.cpp
clients/drcachesim/tracer/output.h
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/tracer.cpp

Adds a timestamp+cpuid pair at the end of normal buffers, to help separate trace output i/o time.
Adds a timestamp+cpuid pair before and after each application syscall. It appears around the syscall marker.  The trace buffer is no longer output pre-syscall (this addresses #3113) except for i-filtered traces or small-window traces where we need a frequent trace size check.
Adds a timestamp+cpuid pair when a kernel transfer event occurs.  The trace buffer is no longer output here.
Fixes the existing behavior where the post-syscall-buffer's timestamp contains the pre-syscall time.
Bumps the trace version for this change as the contents of post-syscall timestamps are now different.
Augments the documentation around timestamps and adds a missing entry on syscall markers.
Adds some invariant …

i#6289: Add timestamps at buffer end and around syscalls

---

core/ir/riscv64/codec.c
suite/tests/api/ir_riscv64.c

The "u" in uimm means U-type, not unsigned, the immediate is a signed integer. This patch fixes this issue and adds a test case for it.

i#3544 RV64: Fix AUIPC uimm sign-extension issue

---

clients/drcachesim/tests/scattergather-aarch64.templatex
clients/drcachesim/tests/scattergather-x86.templatex
suite/tests/CMakeLists.txt

This should reduce the churn in the test output template files compared to basic_counts which it used before.
Issues: #6298, #5036

i#6298 Use invariant_checker for drcachesim scattergather test

---

clients/drcachesim/tracer/output.cpp

Avoids going over the atomic write size while waiting for enough entries to write to IPC pipe. If we find we went over, we just write till the last ok-to-split ref.
tool.drcachesim.scattergather-x86 worked fine 100x on local workstation with this fix.
This issue manifests on this test because some scatter-gather instruction has eight consecutive memrefs which puts us over the threshold suddenly without any opportunity to write the buffer before all the memrefs.
Fixes: #5329

i#5329: Fix tool.drcachesim.scattergather-x86 test failure

---

core/fragment.h
core/ir/opnd_api.h
core/ir/riscv64/codec.c
core/ir/riscv64/instr.c
suite/tests/api/ir_riscv64.c
suite/tests/api/ir_riscv64.expect

This patch implements the necessary instr_* functions that are called when running simple programs. Also, the opnd type of `auipc` has been changed again to `REL_ADDR_kind`. This is essential for `opc_is_not_a_real_memory_load()` and `instr_has_rel_addr_reference()` to work correctly.
Issue: #3544

i#3544 RV64: Implement instr_* functions

---

core/arch/arch.c
core/unix/os.c

GCC11 has stricter requirements for uninitialised
variables in -O3 mode
Issue: #1569

i#1569: Fix compilation errors with GCC11 and "-O3" option

---

README.md
api/docs/home.dox

We develop a portable and efficient framework [VClinic](https://github.com/VClinic/VClinic) for fine-grained value profilers built atop DynamoRIO. We wish to add a short line of intrudocution with corresponding external link into the README. 
In short, the highlights of VClinic built upon DynamoRIO are shown as follows:
- Decoupling implementation of value tracing and value profiling
- Implement trace buffer with lightweight inline assembly for efficient value tracing
- Support operand-centric view for development of fine-grained value profilers instead of instruction-centric view of DynamoRIO.
- Currently support both ARM and X86 platforms. In the future, it can support all DynamoRIO-supported architectures.
The detailed document of VClinic can be referred to …

Add existing dynamorio-based external tools for value profilers

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Fixes a case where a branch followed by an indirect branch with a chunk split in the middle results in an extra encoding entry after the indirect branch target marker.  This extra entry is accumulated in the reader and results in a fatal error.
Adds a unit test.  Confirmed the fix on the
drcacheoff.invariant_checker test as well where it was failing reliably on one machine.
Fixes #6303

i#6303: Avoid duplicate encoding entry on chunk-split branch pair

---

core/arch/mangle_shared.c

Add missing handling of RISC-V system call method `SYSCALL_METHOD_ECALL` in `mangle_syscall()`.
Issue: #3544

i#3544 RV64: Add handling of SYSCALL_METHOD_ECALL in mangle_syscall

---

.github/workflows/ci-docs.yml

With drmemory now updated to the latest DR, it needs to initialize the minizip submodule when we build its docs inside DR's docs.
Tested via a ci-docs action run on this branch: https://github.com/DynamoRIO/dynamorio/actions/runs/6270125682

Fix docs build with drmemory

---

clients/drcachesim/tests/core_sharded_test.cpp
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h
core/arch/mangle_shared.c

Adds first-class counting of threads per shard in the basic_counts tool, for use with core-sharded operation.
Updates the core-sharded tests with sanity checks.
Issue: #5694

i#5694 core-sharded: Count threads in basic_counts

---

core/ir/aarch64/codec.c

Fixes an uninitialized var warning in gcc 12.

Fix uninit warning in gcc 12

---

make/utils.cmake

Fixes a crash in newer CMake versions from an attempt to run a target-arch executable when cross-compiling.
Tested on the same setup where the issue was reported.
Fixes #6327

i#6327: Do not try-run when cross-compiling

---

.github/workflows/ci-package.yml

With drmemory now updated to the latest DR, it needs to initialize the minizip submodule when we build it inside DR's package.
Tested via a ci-package action run on this branch:
https://github.com/DynamoRIO/dynamorio/actions/runs/6294268920

Fix package build with drmemory

---

core/ir/x86/decode.c
core/ir/x86/decode_table.c
suite/tests/api/drdecode_x86.c

Add instructions to categories:
OP_push,OP_pop,OP_cmp,OP_pusha,OP_popa,OP_push_imm,OP_ret,OP_ret_far,OP_loopne,OP_loope,OP_loop,OP_movzx,OP_cmp,OP_rcr
Fix: Moved category decoding after operands decoding to check STORE/LOAD memory access 
Issue: https://github.com/DynamoRIO/dynamorio/issues/6238

i#6238: validate instructions: push,pop,cmp,pusha,popa,push_imm,ret,ret_far,loopne,loope,loop,movzx,cmp,rcr

---

CMakeLists.txt

The gcc 13 -Wdangling-pointer complains about our TRY macros and I could not figure out hwo to rewrite them to make it happy.  We disable the warning to fix the build.
Fixes #6337

i#6337: Disable -Wdangling-pointer

---

api/docs/release.dox
clients/drcachesim/CMakeLists.txt
clients/drcachesim/common/options.cpp
clients/drcachesim/tests/burst_malloc.cpp
clients/drcachesim/tests/offline-burst_malloc.templatex

Adds realloc to the list of heap functions traced by -record_heap by drmemtrace by default.  Also fills in missing variants for tc_ and __libc for calloc.
Adds a sanity check to the burst_malloc test that we find realloc, and extends burst_malloc to post-process and walk the trace and confirm we actually see markers for realloc.  Reduces the iteration count to try to keep the test from taking too long in the suite.
Fixes #4465

i#4465: Trace realloc by default

---

api/docs/release.dox
api/samples/stats.c
core/arch/x86/mangle.c
core/ir/aarch64/instr.c
core/ir/arm/instr.c
core/ir/instr_api.h
core/ir/x86/decode.c
core/ir/x86/instr.c

Continue #6331 discussion
FP types are not needed now because all information is in category now
Issue: https://github.com/DynamoRIO/dynamorio/issues/6238

i#6238: deprecate dr_fp_type_t structure and migrate to dr_instr_category_t

---

api/docs/release.dox
clients/drcachesim/CMakeLists.txt
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/analysis_unit_tests.cpp
clients/drcachesim/tests/mock_reader.h
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp

Adds several routines to the memtrace_stream_t interface for drmemtrace analysis tools in core-sharded mode:
+ get_workload_id()
+ get_input_id()
+ get_input_interface()
Adds a new analysis_unit_tests executable with some sanity tests. Splits out the mock_reader_t and helpers used by scheduler_unit_tests to share them with the new test.
Documents the additions.
Fixes a bug with core-sharded analysis tools where parallel_shard_exit was called for every thread, resulting use-after-frees when more than one thread was on a core and the tool deletes its shard data structure in the parallel_shard_exit routine (most of our tools do not, which is why this was not noticed before).
Issue: #5694

i#5694 core-sharded: Add stream input query interfaces

---

api/docs/code_style.dox

Documents the rule that C++ exceptions are not allowed, to maximimize interoperability.

Add a no-C++-exception code style rule

---

clients/drcachesim/tracer/func_trace.cpp
suite/tests/CMakeLists.txt

Looking up symbols is very slow on Windows.  Here we avoid looking at dynamorio.dll and the client and extension libraries.
For the drcacheoff.max-global test, we also reduce the number of functions from -record_heap to just -record_function 'malloc|1'.
Combined, these shrink the test from taking over 6 minutes on my local machine to taking 24 seconds.  The test was timing out periodically on GA CI and this should fix that.
Fixes #6342

i#6342: Speed up function tracing on Windows

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Adds a new raw2trace statistic that counts the number of instructions written to the final trace.
This instr count is printed out along with other raw2trace stats at the end of raw2trace conversion. It is also available for sub-classes to obtain using the get_statistic API.
Adds tests for the new and existing raw2trace stats in raw2trace_unit_tests.
Verified that the log printed by raw2trace has the same instr count as what's printed by basic_counts, for both the default .zip and `-compress none`.

Add raw2trace statistic for instr count

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/common/utils.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/tests/offline-allasm-record-syscall.templatex
clients/drcachesim/tracer/func_trace.cpp
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Adds a new option -record_sysall to drmemtrace which records the parameter and success values for the given system call numbers.  Just like with -record_function, the user must specify the parameter count.
SYS_futex is left as traced by default, but it can be disabled.
Adds documentation and a test.
Further manual testing:
```
---------------------------------------------------------------------------
$ rm -rf drmemtrace.*.dir; bin64/drrun -t drcachesim -offline -record_syscall '1|-3&12|4&9|2' -record_syscall '12|2&158|4' -- suite/tests/bin/simple_app && bin64/drrun -t drcachesim -indir drmemtrace.*.dir -simulator_type view 2>&1 | egrep 'system call |function'
Error: -record_syscall invalid parameter count -3
--------------------------------------------------------------------------- …
```

i#6344: Add -record_syscall to drmemtrace

---

clients/drcachesim/tests/scattergather-aarch64.templatex
ext/drx/scatter_gather_aarch64.c
suite/tests/client-interface/drx-scattergather-aarch64.cpp
suite/tests/client-interface/drx-scattergather-aarch64.templatex

Adds support to drx_expand_scatter_gather() for SVE vector+immediate gather load and scatter store instructions, along with tests.
Issue: #5036

i#5036 A64 scatter/gather, part 3: Expand vector+immediate

---

clients/drcachesim/scheduler/scheduler.h

Improves two instances of push_back by replacing with emplace_back.
Issue: #5843

i#5843 scheduler: Replace push_back with emplace_back

---

core/unix/memcache.h

The current one doesn't work because defined name is different from the one that's checked with `#ifndef`.
This can lead to including this header more than once.
Also changed `#define` formatting to be consistent with other files.

Fix include guard in memcache.h

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new unit test which targets replaying with region-of-interest limits stopping before the end of the input streams.
The test has two variations, one with no interleavings and one with interleavings, each hitting different bugs.
Fixes one significant bug:
+ The main bug hit and fixed is a race where the candidate record already read from an input by one output is not queued until after giving up the lock and re-acquiring later: and in that window another output could pick up that input, think it's at the right spot, and miss the queued entry, which then may show up randomly later.
The input queue is a deque so we can use both ends.  The solution is to put the candidate record in the queue before giving up the lock, and if the input didn't change upon re-acquiring the lock, to pop it …

i#6336: Fix multiple replay bugs

---

clients/drcachesim/tools/external/example/CMakeLists.txt

Fixes un-escaped quote characters from PR #6335 which show up as CMake warnings.
Issue: #3101

i#3101 drcachesim external: Fix CMake syntax errors

---

clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tools/external/example/CMakeLists.txt
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tracer/output.cpp

Tightens the normal-mode output rule to discard a thread with no instructions (keeping the no-data check for i-filtered modes) and expands the empty-thread behavior to include regular exit runs and not just detach.
Adds the scheduler_launcher CPU check from PR #6355.
It is not easy to create a test with a thread that reliably executes zero instructions yet still outputs some data.  I added an invariant check for a zero-instruction thread and confirmed it fires on the trace in PR #6355:
```
$ bin64/drrun -t drcachesim -simulator_type invariant_checker -indir ~/tmp/drmemtrace.schedtest.x64
Trace invariant failure in T85300 at ref # 12 (0 instrs since timestamp 13341391214912820): An unfiltered thread should have at least 1 instruction
```
Issue: #6354

i#6354: Do not output zero-instruction (unfiltered) threads

---

core/ir/riscv64/codec.c
core/ir/riscv64/codec.h
suite/tests/api/ir_riscv64.c
suite/tests/api/ir_riscv64.expect

Currently, valid RISC-V instruction length can be 16-bit (compressed instruction) or 32-bit, but according to the "Extended Instruction-Length Encoding" section of the RISC-V Unprivileged Specification 20191213 on page 8, instruction length can be greater than 32-bit in the future.
Our RISC-V instruction_width() function follows the spec except that it returns the wrong length for the last case. While this patch fixes that, it may still return an unsupported length for bad data.
While performing decoding, sometimes we decode bad data and expect the decoder to print an error message and carry on. Therefore, we should not assert unsupported instruction length, this patch also removes the corresponding assert in decode_common().
Issue: #3544

i#3544 RV64: Fix invalid instr width handling when decoding

---

core/arch/arch.h
core/arch/arch_exports.h
core/arch/emit_utils_shared.c
core/arch/riscv64/emit_utils.c

The implementation of this function is roughly the same as AArch64, except for some additional handling of C extension instructions.
Issue: #3544

i#3544 RV64: Implement insert_exit_stub_other_flags

---

core/arch/riscv64/emit_utils.c

This patch implements patch_stub() and stub_is_patched(). Similar to AArch64, our RISC-V port supports near-fragment linking and far-fragment linking. For the former, we use `J offset` (short for `JAL x0, offset`) to link the basic blocks. For the latter, we update target_pc_slot to reuse the original indirect jump.
Issue: #3544

i#3544 RV64: Implement patch_stub and stub_is_patched

---

core/unix/os.c

This patch fixes the WRITE_TLS_INT_SLOT_IMM and READ_TLS_INT_SLOT_IMM macros. These macros are used by `replace_thread_id()`, which is called when executing a program that uses fork.
Issue: #3544

i#3544 RV64: Fix TLS macros

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tracer/raw2trace.cpp

We have captured traces from the same thread with the same CPU and timestamp, their start_instructions are tens of instructions apart.
The current comparators in raw2trace and the invariant checker do not take start_instruction into account. And it leads to indeterministic sorting results. It causes the invariant checker to report cpu/serial entry does not match trace error when raw2trace and the invariant checker sort the entries differently.
The change is to compare the start_instruction when two schedule entries have the same CPU, thread ID, and timestamp.
And add a unit test to cover the case where two schedule entries have the same CPU, thread ID, and timestamp, but different start_instruction.
Fixes: #6364

i#6364: add start_instruction to schedule entry comparator.

---

clients/drcachesim/tracer/func_trace.cpp

Makes the function trace symbol skipping for a module considered a client or DR more visible to more easily diagnose missing function tracing.
Issue: #6342

i#6342 func trace opt: Make symbol skipping visible

---

clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/raw2trace.cpp
core/lib/globals_api.h

A couple of places in the drcachesim tracer there was code that handles scatter/gather instructions that was guarded by #ifdef X86 which meant offline traces that include scatter/gather instructions were producing errors on AArch64.
For example running the aarch64 scattergather test app:
```
$bin64/drrun -t drcachesim -offline -- suite/tests/bin/client.drx-scattergather
$bin64/drrun -t drcachesim -indir drmemtrace.client.drx-scattergather.662655.1769.dir
```
produced the error:
```
ERROR: failed to initialize analyzer: raw2trace failed: Failed to process file for thread 662655: memref entry found outside of bb
```
This commit enables the code on AArch64 as well and fixes the error.
Issue: #5036

i#5036 A64 scatter/gather: Fix drcachesim offline tracing

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp

When a signal causes an rseq abort, there will be a rseq  abort marker, followed by a kernel event marker.
When another signal follows immediately, another kernel event maker will be added with a different value.
If a back-to-back signal happens without any intervening instructions, the new kernel event marker (3rd one) should have the same value as the second kernel event marker.
The current implementation of the invariant check fails to consider this case, and flag an error.
If the instruction before the rseq marker is a branch, the invariant checker reports "Branch does not go to the correct target @ kernel_event marker", otherwise it reports "Non-explicit control flow has no marker @ kernel_event marker".
The fix is to check if the kernel event marker has the same value as the …

i#6373: handle back-to-back signals after an rseq abort.

---

clients/drcachesim/tracer/raw2trace.cpp
core/unix/include/syscall_linux_uapi.h
core/unix/include/syscall_linux_x86.h

Add epoll_pwait2, sendmmsg, recvmmsg, and membarrier to the maybe-blocking syscall list.  These don't always block: e.g., membarrier has some sub-operations for which it never blocks.
Updates the DR syscall headers to include recently added syscalls, including epoll_pwait2.  The uapi headers are only partly updated due to lack of easy access to a header to fill in the other SYS_ defines.
Issue: #5843

i#5843 scheduler: Mark more maybe-blocking syscalls

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/tests/allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/allasm_repstr.asm
clients/drcachesim/tests/burst_futex.cpp
clients/drcachesim/tests/offline-allasm-record-syscall.templatex
clients/drcachesim/tests/offline-allasm-repstr-basic-counts.templatex
clients/drcachesim/tests/offline-windows-asm.templatex
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/tracer.cpp

Changes what the drmemtrace -record_syscall feature does with system call returns to record the actual value instead of the success boolean.  Adds a new TRACE_MARKER_TYPE_SYSCALL_FAILED to indicate failure.
Adds a sanity test to allasm-repstr (and updates other tests that have hardcoded counts for this app).
Adds documentation on the change.
Issue: #6344

i#6344 record_syscall: Record return values and add failure marker

---

clients/drcachesim/tracer/output.cpp

For BIMODAL traces (see https://github.com/DynamoRIO/dynamorio/issues/5199), the normal transition is from COUNT to L0_FILTER to TRACE. But some threads may transition from COUNT to TRACE directly e.g., if they were not scheduled during L0_FILTER mode. In this case, the FILTER_ENDPOINT marker is not inserted currently, which leads to raw2trace failures.
An example cmd line that reproduces the bug is shown below. Note that there is only one worker thread which transitions through L0_FILTER and TRACE mode while the main thread is still in COUNT mode.
```
bin64/drrun -t drcachesim -offline \
-trace_after_instrs 2200K -L0_filter_until_instrs 10K -max_trace_size 10K -- ./threadsig 1 1000
```
Issue: #6367

i#6367: Insert FILTER_ENDPOINT when going to TRACE from COUNT also.

---

clients/drcachesim/tracer/func_trace.cpp

Adds #6376 to the comment that documents that we do not currently
support function tracing in the drmemtrace online mode.
Issue: #6376

i#6376: Add issue# for supporting online func tracing

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/scheduler/scheduler.h

Adds explicit documentation that the various drmemtrace packed on-disk formats are little-endian, except the raw offline trace format (for efficiency).  The memref_t format is left as flexible as the reader can convert from the little-endian trace_entry_t if desired.

Document the endianness of drmemtrace wire formats

---

ext/drx/CMakeLists.txt
ext/drx/scatter_gather_aarch64.c

drx has a BSD license so we don't want it to depend on drutil which has an LGPL license.
The replaces the drutil_insert_get_mem_addr() call with equivalent code to calculate the start address for the contiguous memory range.
Issue: #5036

i#5036 A64 scatter gather: Avoid dependency on drutil

---

api/docs/release.dox
core/ir/aarch64/codec.c
suite/tests/api/dis-a64-sve.txt
suite/tests/api/ir_aarch64_sve.c

All SVE scalar+immediate LD[1234]/ST[1234] have a signed 4-bit immediate value that encodes a vector index offset from the base register. This value was being used directly in the IR for instructions, however base+disp memory operands should always use a byte displacement.
This changes the codec to use byte displacements in the IR and updates the codec unit tests accordingly.
The following instructions are updated:
```
LD1B    { <Zt>.B }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1B    { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1B    { <Zt>.S }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1B    { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1D    { <Zt>.D }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1H    { <Zt>.H }, <Pg>/Z, [<Xn|SP>{, #<simm>, MUL VL}]
LD1H    { <Zt>.S }, <Pg>/Z, …
```

i#3044 AArch64 SVE codec: fix scalar+immediate LD/ST offsets

---

.github/workflows/ci-riscv64.yml

Updates the RISC-V Debian repository from debian-ports to debian.
This is to fix the RISC-V build in our CI workflows which is currently
failing because debian-ports doesn't support arch=riscv64 anymore.
As per the news on  https://www.ports.debian.org, riscv64 is now
part of the official archive instead.
```
Thu, 26 Oct 2023 22:28:36 +0200
The riscv64 architecture has been [added to the official archive](https://lists.debian.org/debian-riscv/2023/07/msg00053.html) a few months ago. Given most of the packages have now been rebuilt, it has just been removed from the debian-ports archive.
```
Fixes #6399

i#6399: Update Debian repository to fix RISC-V CI build

---

clients/drcachesim/drpt2trace/ir2trace.h

Modifies an import statement to use a non-relative path to header file.
This is required for third-party integration to work properly. Not sure
how this was missed in #6381.
Issue: #5505

i#5505 kernel trace: Fix relative header import path

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Adds a new marker type TRACE_MARKER_TYPE_DIRECT_THREAD_SWITCH for use with custom kernel scheduling features where one thread directly switches to another on the same cpu.
Refactors raw2trace marker processing code to allow a subclass to insert the new marker.
Makes the raw2trace blocking syscall code virtual to allow a subclass to label custom syscalls as blocking.
Given that the changes are used in separate code it is not simple to make a test of the raw2trace refactoring + virtual. For the marker: tests that use the marker will be forthcoming in scheduler_unit_tests.
Issue: #5843

i#5843 scheduler: Add direct thread switch marker

---

api/docs/release.dox
core/ir/aarch64/instr_create_api.h
core/ir/instr_api.h
core/ir/instr_shared.c
suite/tests/api/drdecode_aarch64.c
suite/tests/api/drdecode_arm.c
suite/tests/api/drdecode_x86.c

Adds a new IR API routine instr_is_opnd_store_source() which identifies whether a given source operand supplies the value to be stored into memory for a store instruction.  Although generally DR avoids modeling dataflow, especially for complex SIMD shifts, this data identification is useful enough that we provide a helper function.  However, we do not go as far as annotating the decoder operands, and instead deduce the answer based on conventions in our IR, which should suffice for now and even if not as clean as decoder markup it is better to have this helper in one place we could improve in the future instead of different users trying to figure this out.
Adds some tests for each architecture.
Fixes #6397

i#6397: Add instr_is_opnd_store_source()

---

core/lib/dr_tools.h

Fixes a doxygen ref to "dr_abort_ex" to the correct "dr_abort_with_code".

Fix incorrect doxygen xref

---

core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v82.txt

Move `FCVT` from `codec_v82.txt` to `codec_v80.txt` and replace `FP16` with `BASE` as these instructions work without the FP16 feature.
No need to move the tests as they were already in `dis-a64.txt`!

i#4393 AArch64 codec: Move FCVT from v82 to v80.

---

core/arch/proc_shared.c
core/arch/x86/proc.c

If we initialize the proc_get_vendor() to VENDOR_UNKNOWN we get contradictory decoding results for x86 opcodes that vary between VENDOR_AMD and VENDOR_INTEL (because some of our decoding code checks one and some checks the other), so we pick one (VENDOR_INTEL) for a stable self-consistent default.  We set this statically and we override the underlying hardware in proc_init().  The user can use proc_set_vendor() (after an explicit init) to override if desired.
Fixes #5725

i#5725: Set consistent x86 vendor decoding default

---

api/docs/bt.dox

Fixes 2 typos found while reading.

docs: Fix 2 typos in bt.dox

---

core/unix/signal.c

This patch fixes some typos that may introduced by copy-paste from `execute_handler_from_cache()`.
Issue: #3544

i#3544 RV64: Fix a copy-paste mistake in execute_handler_from_dispatch

---

clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/reader/zipfile_file_reader.h

Stores the file path in the zipfile_file_reader_t and prints it in every diagnostic message.  Obtains the chunk name for the truncation message and includes that.
Tested on a trace with a truncated file.

Add better zipfile error diagnostics

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Adds an invariant check that each thread has an exit record in a drmemtrace.
Adds a path for the analyzer to call process_shard_exit() when there is no exit record.
Manually tested this on a real truncated trace.
The new check failed on nearly every existing unit test, requiring adding thread exits.  That in turn triggered exit checks on missing headers and filetypes.  I ended up having to edit every test case.  As part of this I standardized the tid constants used.
Issue: #6444

i#6444 no exit: Add invariant check for thread exit

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Augments the mid-rseq-trace-exit case to handle the rseq final instr being reached but not passed.  Adds a test case.
Issue: #6444

i#6444 mid-rseq-exit: Handle at-exit trace exit

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tests/schedule_stats_test.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Rather than context switching on every syscall labeled maybe-blocking, the scheduler uses the now-available syscall latency to decide whether the syscall should block and result in a context switch.
Adds two new command line options, -sched_syscall_switch_us (default 500us) and -sched_blocking_switch_us (default 100us), and corresponding scheduler_t inputs, to control the latency thresholds. To avoid relying too much on the maybe-blocking labels, we do consider a very-high-latency syscall not marked as maybe-blocking to block.
Adds a new schedule_stats unit test.
Tested in a large proprietary app where this reduces the context switch rate from ~100x too high down to ~10x too high.  The next step of adding i/o wait times should further improve the representativeness.
Issue: #5843

i#5843 scheduler: Only consider long-latency syscalls blocking

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Fixes a < assert from PR #6458 to be <=, to allow the pre-syscall timestamp to equal the post-syscall timestamp.
Adds a test that fails without the fix.
Issue: #5843

i#5843 scheduler: Fix assert to allow 0-latency syscalls

---

clients/drcachesim/tracer/instru.h
clients/drcachesim/tracer/instru_offline.cpp
clients/drcachesim/tracer/raw2trace.cpp

Removes the vdso raw bytes we were storing in the module file for offline drmemtraces.  Switches to using per-block encodings instead. This avoids problems with hooked vsysenter on 32-bit AMD.
Tested on tool.drcacheoff.simple on 32-bit AMD on a machine where that test failed every time before this fix.
Removes the unused offline_instru_t::get_modoffs() rather than updating it for the vdso change.
Issue: #6416, #2062
Fixes #6416

i#6416: Replace vdso raw bytes with per-block encodings

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Fixes a corner case for filtered traces in the raw2trace delayed branch logic
that affects how encodings are written.
Adds an increment missing for zero sized pc entries for the ordinal into the
decode_pcs array. This caused the wrong decode_pc to be recorded as
emitted, which caused the "missing encoding" error when that decode_pc
was not really emitted later.
This affects CTI that read memory and may generate in some cases only a
zero-sized PC entry (if the instr is i-filtered out but its memref isn't).
Adds a raw2trace_unit_test for filtered traces that fails without this fix.
Fixes: #6466

i#6466: Fix raw2trace missing encoding error for filtered traces

---

core/synch.c

Handle AMD 32-bit syscall instruction.
The  fix is to check for AMD 32-bit SYSCALL in is_at_do_syscall().
Here's more details:
CI x86-32 signalNNNN tests started failing recently. After checking the log, the failures happen on AMD 32-bit system.
Based on the debug logs 
AMD:
0xf7f90583  89 cd                mov    %ecx -> %ebp
0xf7f90585  0f 05                syscall  -> %ecx
interp: syscall @ 0xf7f90585
instr_get_opcode(instr): 95
change_prot(0xf7f90000, 0x2000, rwx) => mprotect(0xf7f90000, 0x2000, 7)==2 pages
change_prot(0xf7f90000, 0x2000, r-x) => mprotect(0xf7f90000, 0x2000, 5)==2 pages
set_syscall_method to 3make_writable: pc 0x441fc000 -> 0x441fc000-0x441fe000 0
Just updated syscall routine:      
0x441fd240  0f 05                syscall  -> %ecx
0x441fd242  a3 5c 29 18 44       mov …

i#6417: Handle AMD 32-bit syscall instruction.

---

api/docs/home.dox

The Arm Instruction Emulator home page on developer.arm.com has moved. Link to it at https://dynamorio.org/index.html updated.
Issue: #4111

i#4111: Update HREF link to ArmIE on home page

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

```
LDNT1B  { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
LDNT1D  { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
LDNT1H  { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
LDNT1W  { <Zt>.D }, <Pg>/Z, [<Zn>.D{, <Xm>}]
STNT1B  { <Zt>.D }, <Pg>, [<Zn>.D{, <Xm>}]
STNT1D  { <Zt>.D }, <Pg>, [<Zn>.D{, <Xm>}]
STNT1H  { <Zt>.D }, <Pg>, [<Zn>.D{, <Xm>}]
STNT1W  { <Zt>.D }, <Pg>, [<Zn>.D{, <Xm>}]
LDNT1B  { <Zt>.S }, <Pg>/Z, [<Zn>.S{, <Xm>}]
LDNT1H  { <Zt>.S }, <Pg>/Z, [<Zn>.S{, <Xm>}]
LDNT1W  { <Zt>.S }, <Pg>/Z, [<Zn>.S{, <Xm>}]
STNT1B  { <Zt>.S }, <Pg>, [<Zn>.S{, <Xm>}]
STNT1H  { <Zt>.S }, <Pg>, [<Zn>.S{, <Xm>}]
STNT1W  { <Zt>.S }, <Pg>, [<Zn>.S{, <Xm>}]
```
issue: #3044

i#3044: AArch64 SVE2 codec: add vector+scalar versions of st/ldnt

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/common/options.cpp
clients/drcachesim/common/trace_entry.h
clients/drcachesim/reader/reader.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/analysis_unit_tests.cpp
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tests/schedule_stats_test.cpp
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h
clients/drcachesim/tools/view.cpp

Adds a new STATUS_IDLE return code, and a corresponding TRACE_MARKER_TYPE_CORE_IDLE record.
Changes the scheduler behavior to no longer return STATUS_EOF for an output when the ready queue is empty: instead STATUS_IDLE is returned until every single input is at EOF.  This results in a more realistic schedule where other cores can pick up work later rather than disappearing from the system.
Augments the schedule_stats tool to count idle replies and compute a % cpu usage metric.  Adds a unit test for counting idles.
Augments the scheduler_launcher to also compute %cpu usage.
Updates all the scheduler tests for the new change.
Adding idle time due to blocking syscalls will be done separately.
Issue: #6471

i#6471 sched idle: Add idle time

---

.github/workflows/ci-riscv64.yml

Adds a check for the existence of a package install dir when manually copying packages for the cross-compile setup as it seems to not be present in newer versions of the packages.
Issue: #3544

i#3544 RV64: Fix CI rsync issue

---

core/arch/arch.c
core/arch/arch.h
core/arch/arch_exports.h
core/arch/riscv64/mangle.c
core/arch/x86_code.c
core/translate.c
core/unix/os_public.h
core/unix/signal.c
core/unix/signal_linux_riscv64.c
suite/tests/CMakeLists.txt

Refine fault translation and signal handling, part of the linux.signalXXXX tests works on real hardware; however, they do not work on QEMU, so we can't enable them on CI.
Issue: #3544

i#3544 RV64: Refine fault translation and signal handling

---

suite/tests/CMakeLists.txt
suite/tests/client-interface/drsyms-test.cpp
suite/tests/client-interface/drwrap-test-detach.cpp

- client.drsyms-test and client.drwrap-test-detach: The tests expect to observe a certain function call a certain sub-function but it doesn't happen when built with optimisation on because the sub-function gets inlined. This is fixed by marking the sub-functions as NOINLINE.
- client.drx-scattergather and client.drx-scattergather-bbdup: The test clients used with these tests count the number of scatter/gather instructions that are expanded and print the number at the end of the test, which gets checked against a reference value. Building the test app with -O3 causes some code to be auto vectorized so there are additional scatter/gather instructions which throws off the count. I removed this tests from the sve_tests list so it won't be built with -O3.
Issue: #5365

i#5365 Fix some tests which fail when build with -O3

---

api/samples/CMakeLists.txt
api/samples/bbbuf.c
core/arch/riscv64/mangle.c
core/ir/opnd_api.h
core/ir/opnd_shared.c
ext/drreg/drreg.c
ext/drx/drx_buf.c
suite/tests/CMakeLists.txt

This patch enables sample.bbbuf test with the following fixes:
- x0 on RISC-V is like XZR on AArch64, so do not consider it as a general register
- tp should be avoided in `drreg_reserve_reg_internal()`
- RISC-V does not have control flags, so a dummy hello test is used for `control_flags` instead
Also removed `linux.sigaction_nosignals` and `pthreads.pthreads` from `RUNS_ON_QEMU` since they are not working on real hardware.
#3544

i#3544 RV64: Enable sample.bbbuf test

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a longer waiting period on blocking syscalls using either provided output time or for instruction-based quanta a count of queue selections before a blocked input is actually selected.  Since the scheduler does not have timer interrupts or regular points of control and relies on its user calling it, idle inputs are kept on the ready queue and are checked for becoming unblocked when the ready queue is queried.
The wait duration is set based on the "wait time factor" which is the syscall latency divided by the context switch threshold multipled by a user-provided "block_time_scale" option which can be used to scale up or down the durations.
The wait duration is erased on a direct switch to an input.
Adds a new replay record type to represent idle time on replay.
Augments the unit tests …

i#6471 sched idle: Add idle time from blocking syscalls

---

clients/drcachesim/scheduler/scheduler.cpp

Fixes an assert variable decl to use #ifndef NDEBUG instead of #ifdef DEBUG to support builds in between DEBUG and NDEBUG.  We don't have such builds on Github but some third-party builders use them.
Issue: #6471

i#6471 sched idle: Fix assert define

---

api/docs/release.dox
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve.c
suite/tests/api/ir_aarch64_sve2.c

This patch adds the appropriate macros, tests and codec entries to decode and encode the following instructions:
```MUL    <Zd>.<T>, <Zn>.<T>, <Zm>.<T>```
```MUL    <Zd>.D, <Zn>.D, <Zm>.D[<imm>]```
```MUL    <Zd>.H, <Zn>.H, <Zm>.H[<imm>]```
```MUL    <Zd>.S, <Zn>.S, <Zm>.S[<imm>]```
Issue: #3044

i#3044 AArch64 SVE codec: Add SVE2 MUL variants

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Changes the quanta accounting to match the real kernel by accumulating it across executions if a prior execution was terminated early due to a voluntary context switch.
Adds new testing, and updates old tests with the behavior change. Scheduler unit test string changes were carefully vetted.  E.g., for test_synthetic_with_syscalls_multiple(): the output strings changed because H's quantum accumulates and it hits a preempt in the middle of its second HH sequence, which decrements B's quantum, causing B to become available sooner.
Issue: #5843

i#5843 scheduler: Accumulate quanta across runs

---

clients/drcachesim/tracer/raw2trace.cpp

Fixes print format specifier in a raw2trace verbose level 2 log. This causes a segmentation fault with -verbose 2.
Issue: #6495

i#6495 syscall templates: Fix format specifier in log

---

api/samples/CMakeLists.txt
core/arch/mangle_shared.c
core/arch/proc_api.h
core/arch/riscv64/mangle.c
core/arch/riscv64/proc.c
suite/tests/CMakeLists.txt

This patch fixes a bug in `insert_pop_all_registers()` and thus enables the following sample tests:
code_api|sample.bbsize
code_api|sample.div
code_api|sample.empty
code_api|sample.inline
code_api|sample.inscount
code_api|sample.opcode_count
code_api|sample.signal
code_api|sample.stl_test
code_api|sample.syscall
Issue: #3544

i3544 RV64: Enable a few more sample tests

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tests/schedule_stats_test.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Changes instruction quantum idle handling to use wall-clock time, instead of a counter decremented in queue pops.  The counter was skewed unfairly by the rate of queue queries.  This results in all quanta using a unified time-based approach for blocked time.
Changes block_time_scale to remove the division by the latency threshold.  Now the scale is directly multiplied by the latency to result in the blocked time units.  The default scale is set to 1000 which matches the wall-clock time to process an instruction by the schedule_stats tool (about 1 instruction per microsecond) and which should be a rough match for many simulators passing one nanosecond cycle per instruction as the time unit.
Adds a new scheduler option block_time_max and drcachesim option -sched_block_max which caps the …

i#6471 idle: Add better idle time modeling

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
core/ir/opnd_api.h
core/ir/opnd_shared.c
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve.c
suite/tests/api/ir_aarch64_sve2.c

This patch adds the appropriate macros, tests and codec entries to decode and encode the following instruction:
```SPLICE    <Zd>.<T>, <Pv>, { <Zn1>.<T>, <Zn2>.<T> }```
Issue: #3044

i#3044 AArch64 SVE codec: Add SVE2 SPLICE variant

---

clients/drcachesim/drpt2trace/ir2trace.cpp

Fixes a ClangTidy error in inline construction of a trace_entry_t object
that is failing downstream build.
Adds direct include statements for some dependencies while we're
at it.
Issue: #5505

i#5505 kernel trace: Fix blocking ClangTidy error

---

.github/ISSUE_TEMPLATE/bug_report.md

Removes the `<pre>` tags which made the backticks visible when rendered (as in the issue template view at
https://github.com/DynamoRIO/dynamorio/issues/templates/edit) in favor of making the raw source edit less confusing.

Remove "pre" tags from bug template

---

core/ir/aarch64/codec_sve2.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-sve2.txt
suite/tests/api/ir_aarch64_sve2.c

This patch adds the appropriate macros, tests and codec entries to decode and encode the following instruction:
```TBL    <Zd>.<Ts>, { <Zn1>.<Ts>, <Zn2>.<Ts> }, <Zm>.<Ts>```
Issue: #3044

i#3044 AArch64 SVE codec: Add SVE2 TBL variant

---

suite/tests/linux/clone.c
suite/tests/linux/clone.expect

The output is basically the same for each test variation, making it hard to correlate each test's output with the test's code.

Identify each test variation in linux.clone test output

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/simulator.cpp
clients/drcachesim/simulator/simulator.h
clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/drcachesim_unit_tests.cpp
clients/drcachesim/tests/simulate_as_traced.templatex
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/basic_counts.h
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h
suite/tests/CMakeLists.txt

Adds a new scheduler option single_lockstep_output which multiplexes the virtual core output streams onto a single global stream.  This is simple to implement as the existing scheduler_t::stream_t class already multiplexes inputs onto an output.
Hooks up the drcachesim launcher -core_serial option to this new scheduler mode.
Updates the schedule_stats, basic_counts, and cache_simulator tools to support core_serial.  For cache_simulator, the existing thread-to-core mapping code for round-robin and for -cpu_scheduling is kept for when in thread-sharded mode; in core-sharded mode, the scheduler's cpuid is mapped to a core index.
Adds a core_serial test of schedule_stats and basic_counts and a test of cache_simulator using the scheduler's -cpu_schedule_file as-traced mode.
Adds some dr$sim …

i#5694 core-sharded: Add core-serial support

---

suite/tests/client-interface/drsyms-test.dll.cpp

The drsyms-test was looking for "/libc-" to find the libc library, which failes to find "/usr/lib/x86_64-linux-gnu/libc.so.6".  We update the search here to allow a dot.
Tested locally where the test failed before.
Fixes #6530

i#6530: Support alternate libc name in drsyms-test

---

core/unix/rseq_linux.c

Updates the rseq_process_module() check for the section headers being in the mapped region to check the endpoint instead of the start point.
Tested locally: now client.drwrap-test passes when it failed with the toolchain on my local machine.
Fixes #6529

i#6529: Check end of section headers mapped

---

api/docs/release.dox
core/lib/dr_tools.h
core/lib/instrument.c
suite/tests/api/ir_x86.c
suite/tests/client-interface/dr_options.dll.c

Adds a new API routine dr_running_under_dynamorio() which is similar to the application interface dr_app_running_under_dynamorio() but is callable from a client.  The use case is code meant for us both in managed mode under DR and in standalone library mode.  Sometimes the behavior for the two differs significantly, such as whether certain library routines are safe when linked statically.
Adds sanity checks to some existing tests.
The driving use case is in drsyms's support for libdw.  The actual use of this will come in that libdw commit.
Issue: #5926

i#5926 libdw: Add new interface dr_running_under_dynamorio()

---

core/unix/loader.c
core/vmareas.c

Wraps private library init/fini calls in a try/except on Linux (as is already done on Windows) and reports a crash as a SYSLOG_ERROR pointing at the library's name.  This is much better than a weird assert or mysterious secondary crash later.
Adds a check for shared_data==NULL in check_thread_in_last_vmwarea() to avoid a crash seen there.
Issue: #6541

i#6541 privlib: Add try/except around private library init/fini

---

api/docs/release.dox

Fixes a typo in the release notes:
s/dr_disallow_unsafe_static_behavior/dr_allow_unsafe_static_behavior/

Fix release notes typo in dr_allow_unsafe_static_behavior

---

api/docs/building.dox
api/docs/deployment.dox

Updates the example command lines in the Linux Deployment docs to use 64-bit which is far more common these days.

Use 64-bit in Linux examples in docs

---

api/docs/building.dox
api/docs/workflow.dox

Submodules are now required for Linux (for elfutils for drsyms) so we go ahead and add them to all git clone commands in the documentation.
Issue: #5926

i#5926 elfutils: Add submodule init to all git clone commands

---

clients/drcachesim/scheduler/scheduler.cpp

A release build on RISC-V outputs the following compilation error:
```
$HOME/dynamorio/clients/drcachesim/scheduler/scheduler.cpp:1223:70: error: ‘marker_type’ may be used uninitialized [-Werror=maybe-uninitialized]
1223 |         if (record_type_is_marker(record, marker_type, marker_value) &&
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
1224 |             marker_type == TRACE_MARKER_TYPE_CONTEXT_SWITCH_END) {
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$HOME/dynamorio/clients/drcachesim/scheduler/scheduler.cpp:1211:29: note: ‘marker_type’ was declared here
1211 |         trace_marker_type_t marker_type;
|                             ^~~~~~~~~~~
$HOME/dynamorio/clients/drcachesim/scheduler/scheduler.cpp:1225:17: error: ‘marker_value’ may …
```

i#6508: Fix a compilation error in release build

---

.gitmodules

Use HTTPs version of the elfutils submodule URL as it's easier for users behind an HTTP proxy.

i#5926: Update elfutils submodule to https protocol

---

core/unix/signal.c
core/unix/signal_private.h

The `retcode` field in `sigframe_rt_t` is only available in x86 and AArch32, this fixes a buffer overflow in `memcpy_rt_frame()` on RISC-V.
Issue: #3544 #1551 #1569

i#3544, i#1551, i#1569 signal: Remove a non-existing field in sigframe_rt_t

---

suite/tests/CMakeLists.txt

Before, we relied on drrun -s for all test suite timeouts except for runcmp tests where we set a CTest timeout.  This resulted in the default 10 minute CTest timeout for all tests, which was the only timeout for runall tests and caused long suite times on the AArch64 machine which accidentally had no ptrace privileges (#5740, #6558,
Here, we set the CTest time for runall in addition to runcmp, and for all other tests with no timeout specified (which are presumably relying on drrun -s) we set a timeout of the drrun timeout plus 30 seconds.
Tested on the attach test:
Before:
```
123: Test timeout computed to be: 1500
```
Now:
```
$ echo 1 | sudo tee /proc/sys/kernel/yama/ptrace_scope; /usr/bin/time ctest -V -R client.attach_test; echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
... …
```

i#6558, i#6127: Set CTest timeouts for all tests

---

suite/runsuite_wrapper.pl

Adds two tracing tests to the 64-bit Windows ignore list:
i#6423 tool.drcacheoff.burst_traceopts: though a disturbing assert, many attempts to reproduce including under tmate have failed.
i#5412 tool.drcacheoff.burst_replaceall: this one appears to be non-deterministic output ordering so a true flake.
Issue: #5412, #6423

i#6423,i#5412: Ignore Windows flaky tests

---

core/win32/loader.c

A recent Windows update caused the bcrypt.dll process init routine to fail.  This made the unit_tests and client.loader tests fail.  For now we ignore the failure which so far has no harmful visible side effects.
Fixes #6570

i#6570: Ignore bcrypt.dll init failure

---

core/arch/aarch64/aarch64.asm
core/arch/arm/arm.asm
core/arch/riscv64/riscv64.asm
core/drlibc/drlibc_xarch.asm

Fix i#4304 in a different way by always using a branch/call instruction with enough bits of offset to reach the unexpected_return function. Conditional branches don't always have enough offsets to branch to any function within a binary: they're generally only intended for branching within a single function. On aarch64 conditional branch instructions have 19 bits of offset and unconditional branch and call instructions have 26 bits, and is used for every other function call so we should be good for awhile.
Fixes #4304

i#4304 unexpected_return unreachable on aarch64: Use long branch

---

core/ir/encode_api.h
suite/tests/api/ir_aarch64.c

dr_set_sve_vector_length() and dr_get_sve_vector_length() in encode_api.h were missing DR_API specifiers and thus were not exported from libdynamorio, causing link errors.
Adds a test to ir_aarch64.c which fails without the fix.  However, the test may fail on actual SVE hardware: updating it is future work, maybe by changing dr_set_sve_vector_length() to return a bool.
Also tested on the same internal build where the failure was observed.
Issue: #6575

i#6575: dr_{get,set}_sve_vector_length missing export specifiers

---

suite/runsuite_wrapper.pl

Adds two tests to the x86-64 unix ignore list:
i#6452 code_api|client.attach_test
i#6536 code_api|client.detach_test
Issue: #6452, #6536

i#6452,i#6536: Disable flaky attach_test, disable_test for unix x86-64

---

suite/runsuite.cmake

We have lived with our x86-32 GA CI job being red from massive test failures from the AMD switch for long enough.  The fix here may be too drastic, but it's simple: we scale back to the tiny set of tests run on ubuntu22.  I considered listing the failures on the ignore list, but with timeouts included this job was just taking too long.
The plan is to have another Fixit and try to fix enough AMD failures we can re-enable the full job.
Issue: #6417

i#6417 AMD 32-bit: Temporarily, drastically reduce x86-32 tests run

---

core/ir/aarch64/codec.py

Disable a pytype static analysis check on opnd_stem() in aarch64/codec.py as the analysis produces a false positive.
Tested on an internal build where pytype is enabled.
Fixes #6580

i#6580: Disable pytype check on aarch64 codec line

---

core/ir/decode_shared.c
core/ir/encode_api.h
suite/tests/api/ir_aarch64.c

Fixes a buffer overflow in dr_set_sve_vector_length().
Changes dr_set_sve_vector_length() to return a boolean.
Updates the dr_set_sve_vector_length() test to check failure cases.
Tested in an internal build with a memory tool where the overflow was detected:
confirmed no error is reported anymore (with the raw2trace call to
dr_set_sve_vector_length() put back to pass 0 for arm-on-x86).
Fixes: #6584

i#6584: Fix buffer overflow in dr_set_sve_vector_length

---

ext/drsyms/elfutils/config.h

Makes HAVE_GCC_STRUCT in our elfutils config.h conditional on building on x86, which is the only place the gcc_struct attribute is supported.
Fixes #6604

i#6604: Use gcc_struct in elfutils only on x86

---

core/unix/module_elf.h

The elf.h header file on RHEL-7 does not define EM_RISCV which is being used in the source files. This results in a build failure. This change fixes the issue.

iX: RHEL-7 build fix due to EM_RISCV.

---

clients/drcachesim/tools/record_filter_launcher.cpp

Updates the drmemtrace record filter launcher:
+ Passes the verbosity flag through to the analyzer.
+ Removes mistaken "Required" markers for some options.
Tested the verbosity flag manually.
Issue: #5675, #6593

i#5675 memtrace filter: Pass verbosity through

---

suite/runsuite_wrapper.pl

Adds code_api|api.rseq test to Linux 64-bit ignore list
in suite/runsuite_wrapper.pl.
Issue: #1807 #6185

i#6612: Add code_api|api.rseq to Linux x64 flaky test ignore list

---

suite/tests/linux/clone.c

Fix build errors resulting from #6597 by using DR's copy of struct clone_args
This has happened on Android.
Fixes #6596

i#6596 linux.clone* tests on Ubuntu: Handle struct clone_args not defined

---

core/arch/arch.h
core/arch/riscv64/emit_utils.c
core/unix/signal.c
suite/tests/CMakeLists.txt

Added a few more tests to `RUNS_ON_QEMU` and more tests (like `linux.signalXXXX`) is passing under real hardware, but not on QEMU for some reason unknown for now.
Issue: #3544

i#3544 RV64: Implements more functions and enable more tests

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp

Fixes an error in the "An unfiltered thread should have at least 1 instruction" drmemtrace invariant where it does not consider a no-fetch or prefetch instruction.
Adds a unit test which fails without the fix.
Fixes #6622

i#6622: Fix invariant on missing instructions

---

clients/drcachesim/tools/record_filter_launcher.cpp

Fixes an up-front failure with the record_filter_launcher tool on Windows by defining _UNICODE.
Tested both manually and with the new automated test in PR #6598.
Fixes: #6620

i#6620: Fix record_filter_launcher on Windows

---

suite/tests/linux/bad-signal-stack.c

Update bad-signal-stack.c to include tools.h after the other header files so that _GNU_SOURCE is not defined when signal.h is included.
Fixes #6615

i#6615: linux.bad-signal-stack test fails on Ubuntu 22.04

---

clients/drcachesim/tracer/kcore_copy.cpp
ext/drpttracer/drpttracer.dox

Fixes drmemtrace kernel trace libipt post-processing failures caused by missing
instruction encodings for some kernel code execution captured using Intel-PT.
The root-cause seems to be that JIT code executed by the kernel, BPF code in
this case, does not have entries in `/proc/modules`. So, our kcore dump logic
did not include them. This fix looks for BPF related symbols in `/proc/kallsyms`
and includes them in the copied regions from `/proc/kcore`.
Note that BPF JIT symbols are not included in `/proc/kallsyms` by default. One
needs to set `/proc/sys/net/core/bpf_jit_harden` and
`/proc/sys/net/core/bpf_jit_kallsyms` appropriately (see
https://docs.kernel.org/admin-guide/sysctl/net.html#proc-sys-net-core-network-core-options
for more details). Added this suggestion to documentation. It may …

i#6486 kernel tracing: Include BPF JIT code in kcore dump

---

suite/tests/linux/clone.c

Reformat with updated clang-format. There are no functional changes.

Reformat suite/tests/linux/clone.c

---

suite/tests/linux/clone.c

Fix having label "parent" multiply defined by replacing it with a "local label":
Ref: https://sourceware.org/binutils/docs-2.42/as/Symbol-Names.html
The multiple definition is caused by make_clone3_syscall being inlined into create_thread_clone3.
Tested by running the following before/after the patch:
cd build && \
clang \
-I../dynamorio/core/drlibc \
-I../dynamorio/core/lib \
-I../dynamorio/suite/tests \
-I. \
-Iinclude \
-O1 \
-c ../dynamorio/suite/tests/linux/clone.c \
-o clone.o
Fixes #6627

i#6627: Fix multiply defined label in linux/clone.c

---

core/unix/loader.c
core/unix/loader_linux.c

Fixes a hang on glibc 2.37 by initializing the tid pthread TLS field. Its offset is located by decoding an exported function known to reference it in a new routine privload_set_pthread_tls_fields().
Only x86 is supported with this fix as no aarch64 machine with the required glibc is available for developing and testing the decode fix.
Tested on a glibc 2.37 machine where without this fix the client.drcallstack test hangs in release build.
Also tested on a Dr. Memory 2.6.19737 build pointing at a release build DR with this fix and confirmed it fixes the hang there.
Fixes #6611

i#6611: Fix pthread lock hang

---

suite/tests/linux/clone.c

This reverts commit 984e33548cde2b9869d16a60b15383c494470386 as it breaks our internal build.
Issue: #6627

Revert "i#6627: Fix multiply defined label in linux/clone.c (#6628)"

---

suite/tests/linux/clone.c

This reverts commit ef572627cab469b830d08d7be22f1de9d581e8da as it breaks out internal build's workaround for i#6627.

Revert "Reformat suite/tests/linux/clone.c (#6629)"

---

core/arch/aarch64/proc.c
core/arch/proc_api.h
core/ir/aarch64/codec.c
core/ir/aarch64/codec.py
core/ir/aarch64/codec_sve.txt
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/codec_v85.txt
core/ir/aarch64/instr_create_api.h
core/ir/aarch64/opnd_defs.txt
make/CMake_aarch64_gen_codec.cmake
make/aarch64_check_codec_order.py
suite/tests/CMakeLists.txt
suite/tests/api/dis-a64-v85.txt
suite/tests/api/ir_aarch64_v85.c
suite/tests/api/ir_aarch64_v85.expect

This patch adds the tests and code to recognise the BTI instruction when it is encoded as a HINT
As this is the first v8.5 instruction, it also adds the appropriate infrastructure for generating that
codec.
issues: #2626

i#2626: AArch64 codec: Add BTI hinted instruction

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/common/utils.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/window_test.cpp
clients/drcachesim/tools/schedule_stats.cpp

Switches from GetSystemTime on Windows to QueryPerformanceCounter in scheduler and related drmemtrace code.  GetSystemTime was returning times that did not have microsecond granularity, causing problems with identical timestamps.  QueryPerformanceCounter is not an absolute time but none of the use cases need that: they just need relative orderings.
Tested on a Windows machine where GetSystemTime returned the same value repeatedly in the test_random_schedule() test from PR #6639:
```
5: time is 133518165841993473
5: time is 133518165841993473
5: time is 133518165841993473
5: time is 133518165841993473
```
While QueryPerformanceCounter changes:
```
5: time is 3353910786292
5: time is 3353910787556
5: time is 3353910810719
5: time is 3353910811957
```
Fixes #6640

i#6640: Switch to QueryPerformanceCounter for scheduler on Windows

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/flexible_queue.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new scheduler option randomize_next_input and corresponding launcher option -sched_randomize.  When enabled, priorities and timestamps and FIFO ordering are ignored and instead a random next element from the ready queue is selected.  This will be useful for schedule sensitivity studies.
Tested manually end-to-end as well:
```
$ for ((i=0; i<10; ++i)); do bin64/drrun -t drcachesim -simulator_type schedule_stats -core_sharded -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir/ -cores 2 -sched_randomize 2>&1 | grep schedule; done
Core #0 schedule: HEFBF_
Core #1 schedule: GCDFA
Core #0 schedule: GDBH
Core #1 schedule: CFAFEF__
Core #0 schedule: GDBF__
Core #1 schedule: EFCFAH
Core #0 schedule: BHFDF__
Core #1 schedule: EGFAC
Core #0 schedule: …
```

i#6636: Add randomized schedule feature

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/analyzer_multi.h

Templatizes analyzer_multi_t over RecordType and ReaderType as a first step toward allowing the drcachesim launcher and its set of options to be used to launch the record filter tool.
Issue: #6635

i#6635 core filter, part 1: Templatize analyzer_multi_t

---

suite/tests/CMakeLists.txt

Remove linux.fib-conflict from list of tests to be builts with -03.
The cause of the infinite loop is hard to determine, being caused by the linker script.
As this is not a DynamoRIO issue, and this test often fails at the moment anyway, just build it without -O3 for now.
Issue: #5365

i#5365: Infinite loop in linux.fib-conflict test when built with -O3

---

core/arch/aarch64/proc.c
core/ir/aarch64/codec.h

Some of the SVE tests are written assuming a 256-bit vector length so that we get consistent output from the codec regardless of the hardware vector length that the test is run on. This was previously acheived by hard coding DynamoRIO's vector length to 256-bits when built with BUILD_TESTS=1.
This worked fine for the codec tests (api.ir_sve, api.dis-a64-sve) but this breaks tests such as client.drx-scattergather which need the vector length to match the hardware.
This patch tweaks two things so that all tests should now work on all vector lengths:
1. get_processor_specific_info() now initializes the vector length to the correct hardware value whether or not BUILD_TESTS=1. This enables the client tests to work on all vector lengths.
2. The AArch64 codec now uses dr_get_sve_vector_length() …

i#5365 AArch64: Fix tests on non 256-bit VL hardware

---

suite/tests/runmulti.cmake

Fixes this warning in runmulti.cmake:
CMake Warning (dev) at suite/tests/runmulti.cmake:104 (if):
if given arguments:
"NOT" "ON" "OR" "NOT" "precmd" "STREQUAL" "" "AND" "NOT" "globempty"
An argument named "ON" appears in a conditional statement.  Policy CMP0012
is not set: if() recognizes numbers and boolean constants.  Run "cmake
--help-policy CMP0012" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.

Fix CMake warning in runmulti.cmake

---

clients/drcachesim/tools/filter/type_filter.h

Fixes an error where type_filter_t inverted the flag and value parameters to TESTANY.  This was found by inspection and was not observed to have caused any problems (TESTALL would have cared about the order but for TESTANY the order ends up not mattering).

Fix TESTANY parameter error in type_filter_t

---

suite/runsuite_wrapper.pl

Adds tool.drcachesim.threads to the SVE flaky list as it has failed twice now on the type_is_instr assert.
Issue: #3320

i#3320 type assert: Add drcachesim.threads to SVE flaky list

---

clients/drcachesim/scheduler/scheduler.h

Clarifies the docs for the block_time_scale scheduler parameter: the units are not microseconds for QUANTUM_TIME.
Issue: #6471

i#6471 sched idle: Clarify block_time_scale units

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/launcher.cpp
clients/drcachesim/tests/offline-trim.templatex
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter_create.h
clients/drcachesim/tools/record_filter_launcher.cpp
suite/tests/CMakeLists.txt

Adds "-simulator_type record_filter" support to the dr$sim launcher. This builds on the templatized analyzer_multi_t to enable using record readers and record tools.
Adds a record_filter_tool_create() function and moves the filter creation out of record_filter_launcher.
Adds dr$sim launcher options -filter_stop_timestamp, -filter_cache_size, -filter_trace_types, -filter_marker_types, -trim_before_timestamp, and -trim_after_timestamp.
Changes the trim test to use the dr$sim launcher.
Adds a section on the record filter to the drmemtrace tools documentation.
Issue: #6635

i#6635 core filter, part 2: Add record filter to dr$sim launcher

---

api/docs/building.dox

Updates the stale list of gcc versions we support with a pointer to the Github Actions runner image docs which list the versions we use in testing.

Update gcc version docs

---

clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter.h

Since file removal of now-empty shards can involve global operations that could race among shards, we move shard removal to the aggregation stage print_results() in the record filter.
Issue: #6648, #6593

i#6648 trim tool: Move file removal to the end

---

clients/drcachesim/common/options.cpp
clients/drcachesim/tests/offline-trim.templatex
clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/filter/trim_filter.h
clients/drcachesim/tools/record_filter_launcher.cpp

The original PR #6651 ended up keeping the timestamp (+ cpuid) whose value is beyond the trim-after threshold, as it logically makes sense to have that endpoint's timestamp.  However, when that's across a blocking syscall, it canbe far into the future and result in large time gaps in the trimmed trace.  Instead, we throw out the timestamp, as the PR #6551 did in its first form.  (Other options such as editing the timestamp seem worse.)
Adjusts the unit test that tests this.
Issue: #6648

i#6648 trim tool: Remove over-threshold timestamp

---

ext/drwrap/drwrap.c
suite/tests/CMakeLists.txt

Expand drwrap's return address sentinel replacement from just x86 (as was added in PR #6395) to cover all architectures.
When -record_replace_retaddr is used in ARM (as well as x86) platforms, the return address in the stack is replaced by the sentinel.
For a tailcall, the current implementation uses the address in the stack, the sentinel, as the return address. The change is to check if the return address in the stack is the sentinel or not. If it is, replace it with the return address of the outer level.
The problem can be reproduced by
./build/bin64/drrun -t drcachesim -offline -record_replace_retaddr -record_function 'tailcall_with_retaddr|1&foo|1' -- ../build_suite/build_debug-internal-64/suite/tests/bin/common.getretaddr
on an ARM machine.
This change expends PR #6395  to cover ARM. …

i#6668: Replace drwrap retaddr sentinel on all architectures, not just x86

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/tests/analysis_unit_tests.cpp

Adds a call to set_active(false) on the output stream when an analyzer worker thread returns early due to an error.  This frees up the current input and avoids a hang in the scheduler after the error is printed.
Adds a unit test which hangs without this fix.
Fixes #6666

i#6666: Avoid hang when analyzer worker returns early

---

api/docs/release.dox
clients/drcachesim/analysis_tool.h
clients/drcachesim/analyzer.cpp
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp
clients/drcachesim/tools/basic_counts.cpp

Marks the data members of the base interval_state_snapshot_t as private. This is to formally disallow analysis tools that subclass this from modifying the data members such as shard_id, interval_end_timestamp, etc., some of which are essential to the interval merge logic implemented by the analyzer framework.
The analyzer framework implementation in analyzer_tmpl_t is marked as a friend class so that it can still set those private data members.
Converted interval_state_snapshot_t from a struct to a class to follow our style guide.
Issue: #6643, #6020

i#6643: Mark interval_state_snapshot_t data members private

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Saves substantial file space in the drmemtrace scheduler's record-replay file when cores are idling by combining consecutive idle entries.
Adds checks to all unit tests which create replay files; this requires access to the non-public record format, done via a helper class.
Also tested on several real applications: for one the record file drops from 34MB to 4K, matching the size of the as-traced schedule files.  Even tiny applications like threadsig show clear reductions.  Consecutive idle entries were ballooning these files.  Large applications had multi-GB files; with this fix they are orders of magnitude smaller.
Issue: #6471, #6675
Fixes: #6675

i#6675: Collapse consecutive idle replay entries

---

core/ir/aarch64/codec.c
core/ir/aarch64/opnd_defs.txt

The compiler on my local machine complains about z16 aarch64 codec routines being unused, which is a fatal error with our build settings.  The compiler is:
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin23.3.0
```

Remove unused z16 codec functions

---

core/unix/signal.c

It looks like when the ilist member was added to
dr_fault_fragment_info_t, send_signal_to_client() was not updated to set it.
Issue: #6687

i#6687: Fix uninitialised field in dr_siginfo_t

---

core/lib/dr_tools.h

Documents the fact that standalone dcontext_t is not fully thread-safe, hence parallel analysis tools should be aware that when different threads set DR ISA mode at the same time a race condition happens.
Issue #6690

i#6690 dcontext_t standalone: update doc

---

clients/drcachesim/reader/record_file_reader.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/mock_reader.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

For record_scheduler_t, context switch on encoding boundaries instead of instruction boundaries to avoid splitting up encodings from their instructions.
We end up not supporting unread_last_record() for record_scheduler_t as we do not have the pre-prev record to identify a first encoding in a sequence.
Inserting synthetic tid,pid records so the switches are actually visible will be added separately.
Issue: #6635

i#6635 core filter, part 3: record_scheduler_t switch boundaries

---

core/unix/loader.c

Adds a check for glibc 2.39 on x64. x86 values are left unchanged.
Fixes #6693

i#6693 SIGFPE-glibc-2-39: Update workaround offsets

---

clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter.h

Improves record_filter_t subclass support for initially-idle cores by refactoring get_output_basename() out of initialize_shard_output(), allowing a subclass to share the complex initial setup while still using its own output scheme.  Also moves the setup variable to protected for access to output_ext_ in subclasses.
Removes code that was refactored into initialize_shard_output() but accidentally left in place in PR #6704.
Tested internally.
Issue: #6635

i#6635 core filter, part 7: Improve init-idle subclass support

---

api/docs/bt.dox

Adds text clarifying that memory operands do not have their constituent registers listed as separate operands.
This will show up in the online docs here:
https://dynamorio.org/API_BT.html#sec_IR

Clarify docs on IR memory operands

---

.github/workflows/ci-package.yml

Updates the PATH of our package build to find the new WIX version on the GA CI VM's.
Tested: https://github.com/DynamoRIO/dynamorio/actions/runs/8308632272
Fixes #6709

i#6709: Update WIX version to 6.14

---

core/arch/riscv64/emit_utils.c

To simplify codegen, we require the exit stub pc to be aligned to 4 bytes. If it is not aligned, we place a 2-byte `c.nop` at the beginning of the exit stub. Therefore, all functions that modify the exit stub should skip the possible `c.nop`.
The wrongly implemented `patch_stub()` makes `unlink_branch()` not affect the exit stub, which makes the async signal handling error-prone.
Before the fix, it hits the following assertion ~1/5 times when running `linux.signal0001` on a RISC-V machine, which indicates that the second signal comes from a different fragment after the unlinking, and the real reason is that the unlinking is not successful.
```
ASSERT signal.c:4954 info->interrupted == NULL || info->interrupted == f
```
It would be great if we could enable the signal tests in CI, but these …

i#3544 RV64: Fix patch_stub for unaligned stub_pc

---

clients/drcachesim/reader/record_file_reader.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/record_filter_as_traced.templatex
clients/drcachesim/tests/scheduler_unit_tests.cpp
suite/tests/CMakeLists.txt

Adds record_scheduler_t (for the record_filter tool) support for
replaying as-traced.  The key change here is having record_reader_t's
instruction ordinal, record_scheduler_t's output stream instruction
ordinal, and record_scheduler_t's switch boundaries all consider the
first in any sequence of encoding records or
TRACE_MARKER_TYPE_BRANCH_TARGET markers to start an instruction
instead of waiting for the instruction record.  (Previously the
scheduler switch point did consider encodings, but not branch targets,
and the ordinals only considered instructions.)
Moving the boundary back avoids splitting encodings from instructions
when operating at instrution boundaries in the scheduler (encountered
during replay, but this would also affect skipping for scheduler
regions of interest).
Adds …

i#6712: Add record_scheduler_t support for replay-as-traced

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Removes same-input-same-start cpu_schedule entries when reading the schedule file in the scheduler.  The scheduler cannot emulate a switch with no instructions in between in replay mode, and these same-start entries cause problems.
Adds a scheduler unit test.
Tested on a larger app in as-traced mode where there are many of these same-start entries and without this fix the scheduler advances too early, causing problems.
Fixes #6713

i#6713: Remove same-input-same-start cpu_schedule entries

---

clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/filter/record_filter.cpp

Updates record_filter to ignore TRACE_MARKER_TYPE_CORE_WAIT records. These are artificial timing records: we do not want to output them, nor consider them real input records.
Fixes #6727

i#6727: Ignore wait records in record_filter

---

api/docs/CMake_rundoxygen.cmake
api/docs/test_suite.dox

Doxygen 1.9.8 changed the way javascript menu files are generated, by inlining much of the menu hierarchy that was previously written to a separate file per page.
Updates cmake rules to handle the new javascript.  Also removes extra curly braces from a doxygen page that were inadvertently triggering GitHub's Liquid template expansion and removing the intended text.
This fix was verified by building the embedded doxygen files, copying them to a
local dynamorio.github.io workspace, running a Jekyll server to host the pages,
and comparing the local site vs. the online dynamorio.org pages.
Issue: #6681

i#6681: Fix Doxygen file generation for GitHub pages.

---

suite/runsuite_wrapper.pl

To get the post-merge suite green, we ignore failures in the code_api|tool.drcacheoff.windows-timestamps test on win32.  That is a lower priority platform and there are just not enough maintainers for that platform to chase down these issues at this time.
Issue: #6081

i#6081 cb assert: Ignore win32 drcacheoff.windows-timestamps failures

---

clients/drcachesim/tests/record_filter_bycore_uni.templatex
clients/drcachesim/tools/filter/record_filter.cpp
suite/tests/CMakeLists.txt

Sets the filetype for record_filter shards from the filetype_ var to ensure start-idle shards have the correct type.
Switches to using opcode_mix in the tool.record_filter_bycore_uni test, which fails with encoding errors without this fix.
Fixes #6734

i#6734: Set filetype in record_filter start-idle shards

---

suite/runsuite.cmake

Currently runsuite.cmake assumes that "origin/master" is the branch to diff against.
However sometimes this is not the case, e.g. for internal CI systems using their own branches.
Add a "branch" parameter to runsuite.cmake, defaulting to "master", allowing a different source branch to be specified.
Issue: #5365

i#5365: Add "branch" parameter to runsuite.cmake

---

suite/runsuite_wrapper.pl

The code_api|tool.drcachesim.multiproc test has failed several times in release build on the sve runner post-merge.  Despite attempts to figure out or theorize as to what is causing the failure, it remains a mystery.  For now we add multiproc to the list of failures to ignore.
Issue: #3320

i#3320 dr$sim bundle error: Mark multiproc test as ignore

---

clients/drcachesim/tests/invariant_checker_test.cpp

tool.drcachesim.invariant_checker_test  fails on x86-32 with the following error:
1/371 Test https://github.com/DynamoRIO/dynamorio/issues/11: tool.drcachesim.invariant_checker_test ...........................***Failed 0.04 sec
Recording |Too many read records| in T1 @ ref # 16 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 17 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 18 (6 instrs since timestamp 0)
Recording |Too many read records| in T1 @ ref # 19 (6 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 21 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 22 (7 instrs since timestamp 0)
Recording |Too many write records| in T1 @ ref # 23 (7 instrs since timestamp 0) …

i#6744: Use xrstors32 and xsaves32 for invariant checker test on x86-32.

---

suite/runsuite.cmake
suite/tests/CMakeLists.txt

We rely on git diff to do trailing space checks, so to remove the trailing spaces in existing lines that may have been introduced by mistake, deletion lines should be excluded during the check.
Tested with following snippets:
```cmake
cmake_minimum_required(VERSION 3.0)
project(StringRegexMatchExample)
function(match_string_with_regex input_string regex_pattern)
string(REGEX MATCH "${regex_pattern}" match_result "${input_string}")
if(match_result)
message("Match")
else()
message("Not match")
endif()
endfunction()
set(regex_pattern "\n[+ ][^\n]* \n")
set(input_string "diff\n hello  \n")
match_string_with_regex("${input_string}" "${regex_pattern}")
set(input_string "diff\n+ \n")
match_string_with_regex("${input_string}" "${regex_pattern}")
set(input_string "diff\n  \n") …
```

Fix trailing space checker to remove existing trailing spaces

---

api/docs/building.dox

toolchain-arm64.cmake was renamed to toolchain-aarch64.cmake in PR #4753, but building.dox was not in sync.
Issue: #1569

i#1569 AArch64: Update unsynchronized filename in building.dox

---

clients/drcachesim/tests/allasm-scattergather-basic-counts-aarch64.templatex
clients/drcachesim/tests/allasm_scattergather_aarch64.asm
clients/drcachesim/tests/offline-allasm-scattergather-basic-counts-aarch64.templatex
clients/drcachesim/tests/scattergather-aarch64.templatex
ext/drx/drx.c
ext/drx/scatter_gather_aarch64.c
suite/tests/client-interface/drx-scattergather-aarch64.cpp
suite/tests/client-interface/drx-scattergather-aarch64.templatex

Adds support for first-fault loads to drx_expand_scatter_gather(). First-fault loads (ldff1*) work similarly to
scalar+vector/vector+immediate gather instructions or scalar+scalar predicated contiguous ld1* loads, but with different behaviour if an element access faults. This commit implements this behaviour and extends the scatter/gather tests to include ldff1* instructions.
Issue: #5036

i#5036 A64 scatter/gather, part 11: First-fault loads

---

core/ir/aarch64/codec.c
core/ir/instr_inline_api.h

Fix incorrect assert and a decoding bug which by luck still worked.
Issue: #2626

i#2626: AArch64: Fix vector decode bugs

---

suite/runsuite_wrapper.pl

The client.detach_test has been timing out on win32 quite frequently. We put it on the ignore list to get the test suite green.
Issue: #6764

i#6764: Mark detach_test flaky on win32

---

clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/tests/drcachesim_unit_tests.cpp

Adds a check with an error message for too few simulated drcachesim cpus with a core-sharded-on-disk trace.
Adds a unit test which crashes without the fix.
Also tested manually:
Before:
$ bin64/drrun -t drcachesim -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig-core-sharded.x64.tracedir/ -cores 3
Segmentation fault
After:
$ bin64/drrun -t drcachesim -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig-core-sharded.x64.tracedir/ -cores 3
ERROR: failed to run analyzer: Too-small core count 3 for trace core #3
Fixes #6778

i#6778: Gracefully handle too few drcachesim cpus

---

clients/drcachesim/scheduler/scheduler.h

Updates the drmemtrace scheduler regions_of_interest docs which incorrectly stated the window id markers were not inserted between back-to-back regions: they are inserted, as the code confirms (with an explicit comment) and the unit tests check.

Update incorrect docs about scheduler window ids

---

clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tools/schedule_stats.cpp

Adds the list of threads per cpu to the schedule_stats output. Updates the schedule_stats tests to confirm some tids are printed.
Issue: #6426

i#6426 sched stats: Print list of threads

---

clients/drcachesim/tools/schedule_stats.cpp

Relaxes an assert added in PR #6784 to allow zero time to have elapsed when updating the schedule_stats time buckets.
Issue: #6728

i#6728 sched time stats: Relax assert for zero time

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp

Skips generating the final interval snapshot for thread-shards that are missing the thread exit entry, during trace interval analysis in the drmemtrace analyzer framework. Such final intervals currently have incorrect data (the cumulative instr count, instr count delta, and end timestamp). Instead of generating incorrect data we skip such a final interval and print a non-fatal error message.
This issue is seen on interval analysis of only the traces affected by i#6444. That issue has already been fixed many months ago, and does not affect newer traces. This fix is to allow trace interval analysis of those older traces.
Due to i#6444, some threads were missing thread exit entries because tracing ended in an rseq region. For such traces, the i#6444 fix already added an analyzer workaround …

i#6793: Skip incorrect final interval during trace analysis

---

api/docs/release.dox
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/launcher.cpp
clients/drcachesim/tests/core_sharded_test.cpp
clients/drcachesim/tools/external/example/CMakeLists.txt
suite/tests/CMakeLists.txt

Adds -tool as the preferred alias for the -simulator_type option for the drmemtrace/drcachesim framework.  This is long overdue as many analysis tools are not "simulators" and the original option was solely to pick between cache and TLB simulators.
Updates all uses in tests and documentation.
Adds a release note.
Changes the preferred cache and TLB simulator tool names to have _simulator suffixes.  Adds a "drcachesim" alias for the cache simulator as well.
Manually tested the "cache" and "drcachesim" aliases.
Issue: #6660

i#6660 dr$sim aliases: Add -tool to replace -simulator_type

---

core/ir/aarch64/encode.c
core/ir/arm/encode.c
core/ir/riscv64/encode.c
core/ir/x86/encode.c

Fixes a size mismatch between dr_reg_fixer[] and d_r_reg_id_to_virtual[] maps in aarch64.
Adds a check in encode_debug_checks() (in core/ir/${ARCH}/encode.c) for all architecures.
Issue: #6662, #3544, #1569

i#6662 virtual regs: bug fix

---

core/arch/arch.h
core/arch/clean_call_opt_shared.c
core/arch/emit_utils_shared.c
core/arch/mangle_shared.c
core/arch/riscv64/mangle.c
core/lib/globals_api.h
core/optionsx.h
suite/tests/CMakeLists.txt

Implements out-of-line clean calls on RISCV64, the implementation is similar to AArch64. Also enables out-of-line by default for all clean calls. With this patch, the previous trick of reducing `-max_bb_instrs` is no longer needed.
Issue: #3544

i#3544 RV64: Implement out-of-line clean calls

---

core/ir/opnd_shared.c

For now, we only support base+disp on RISC-V, there is no other way of addressing in the standard ISA extensions. This code path is executed by running `bin64/drrun gcc-13 hello.c`.
Issue: #3544

i#3544 RV64: Refine opnd_replace_reg

---

core/CMakeLists.txt
core/arch/riscv64/memfuncs.asm
core/io.c

1. Optimize private memcpy and memset for RV64.
2. Add test to compare private and libc memset.
3. Compare private memcpy with libc memcpy on more small sizes.
4. Fix a bug of core/CMakeLists.txt. For unit_tests, to compare private and libc memcpy, we should link unit_tests to drmemfuncs but not link to libc.
Compare original memcpy&memset, optimized private memcpy&memset and glibc memcpy&memset.
Test command:
```
./bin64/unit_tests
```
When we use original memcpy and memset, outputs:
```
our_memcpy_time: size=1 time=0
libc_memcpy_time: size=1 time=2
our_memcpy_time: size=4 time=2
libc_memcpy_time: size=4 time=2
our_memcpy_time: size=128 time=16
libc_memcpy_time: size=128 time=4
our_memcpy_time: size=512 time=57
libc_memcpy_time: size=512 time=7
our_memcpy_time: size=8192 time=824 …
```

i#3544 RV64: Optimize private memcpy and memset

---

.github/workflows/ci-aarchxx.yml

Job names were changed to be in human readable format. This patch changes them to be more consistent with the autogenerated names used by all the other CI jobs.
issue: #6777

i#6777 AArch64 ci: Update names of jobs to be more consistent

---

clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Adds a very simple histogram with fixed bin sizes recording the distribution of instructions per context switch in the schedule_stats tool.
Updates two tests to confirm the histogram is produced.
This feature is structured to allow replacing this simple histogram with a more sophisticated version in subclasses.
Issue: #6426

i#6426 sched stats: Add histogram of instrs per switch

---

core/ir/riscv64/codec.c
core/ir/riscv64/codec.h
core/ir/riscv64/codec.py
core/ir/riscv64/isl/v.txt
make/CMake_riscv64_gen_codec.cmake

This is the first part of adding RISC-V vector (RVV) extension support to the core.
RVV is a vector architecture similar to SVE, and its vector length (VLEN) can vary from 64 up to 65536. For more information about RVV, please refer to https://github.com/riscv/riscv-isa-manual.
The code itself is compiled and preliminarily tested on real hardware with RVV (VLEN=256) support by running https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/main/examples/rvv_strlen.c.
isl/v.txt is transformed from https://github.com/riscv/riscv-opcodes/blob/master/rv_v by an off-tree one-time python script.
Follow-up patches will address the following parts with RVV support:
- encoder/decoder unit tests;
- code cache context switch;
- clean-call;
- signal context;
- scatter/gather emulation;
- sample …

i#3544 RV64 vector part1: Added vector extension encoder/decoder support

---

core/ir/aarch64/instr.c
core/ir/arm/instr.c
core/ir/instr.h
core/ir/instr_shared.c
core/ir/riscv64/instr.c
core/ir/x86/instr.c
suite/tests/api/ir_aarch64_v86.c

Add ldg to the list of opcodes which are excluded from instr_reads_memory() and add a similar mechanism to exclude stg/st2g from instr_writes_memory().
These instructions have a similar operand signature to load/store instructions but they actually read/write allocation tags for the pointer indicated by the memory operand, rather than read/write the memory it points to.
Issue: #6796
Fixes: #6796

i#6796 AArch64: Exclude ldg/stg from instr_reads/writes_memory()

---

README
api/docs/new_release.dox
api/docs/release.dox
clients/drcachesim/CMakeLists.txt
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/tests/drmemtrace.threadsig.aarch64.raw/README
clients/drcachesim/tests/stride_benchmark.cpp
clients/drcachesim/tools/external/example/CMakeLists.txt
suite/tests/CMakeLists.txt

Adds a tool file so "-t drmemtrace" can become the preferred way to launch the drmemtrace tool framework, as "drcachesim" is just one tool within the framework.
Updates the documentation and tests.
Renames the "drcachesim" executable to "drmemtrace_launcher".
Fixes #6660

i#6660 dr$sim aliases: Add "-t drmemtrace"

---

clients/drcachesim/tests/record_filter-offline.templatex
clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/filter/encodings2regdeps_filter.h
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter.h
clients/drcachesim/tools/opcode_mix.cpp
clients/drcachesim/tools/opcode_mix.h

Fixes a data race due to multiple dr_standalone_init() done in parallel (per shard) by encodings2regdeps_filter_t.
dcontext is now initialized one time by record_filter_t and passed to its filters through the record_filter_info_t interface.
Avoids a data race in opcode_mix where all threads set the dcontext isa_mode to DR_ISA_REGDEPS for regdeps input traces.
Issue #6662 #6812

i#6662 encodings2regdeps: data race bug fix

---

.github/workflows/ci-riscv64.yml
api/docs/building.dox

1. Add docs on cross-compiling building commands for RISCV64 on Linux.
2. Fix some typos.
Issue: #3544

i#3544 RV64: Add docs on cross-compiling for RISCV64 on Linux

---

api/samples/opcodes.c
core/arch/arch_exports.h
core/fragment.h
core/ir/encode_api.h
core/ir/riscv64/decode.c
core/ir/riscv64/instr.c
core/unix/injector.c

RISC-V's ISA string describes a certain combination of extensions. For example, RV64IMAFDC is a 64-bit architecture that supports I M A F D C extensions, but there is no available hardware with this combination. For now, the most common one is RV64GC, where G is short for IMAFD_Zicsr_Zifencei.
DynamoRIO only relies on the G extension to work properly and it can run on various combinations as long as all the extensions the program requires are supported. So the name `DR_ISA_RV64IMAFDC` is not a minimum requirement, nor a combination we supported. This PR changes it to `DR_ISA_RV64` to be more generic.
Issue: #3544

i#3544 RV64: Rename DR_ISA_RV64IMAFDC to DR_ISA_RV64

---

clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/view.cpp
core/ir/isa_regdeps/disassemble.c
make/style_checks/scripts/rules/line_length_content.tcl
suite/tests/api/ir_regdeps.c

Modifies the view tool to handle OFFLINE_FILE_TYPE_ARCH_REGDEPS traces,
leveraging the disassembly of DR_ISA_REGDEPS instructions.
When visualizing DR_ISA_REGDEPS instructions, the view tool still prints the
instruction length and PC, which for OFFLINE_FILE_TYPE_ARCH_REGDEPS
traces are the same as those in the original trace.
Then, after the PC, the instruction encoding, categories, operation size, and 
registers are printed following the disassembly format of DR_ISA_REGDEPS
instructions (xref: #6799).
DR_ISA_REGDEPS instructions printed by the view tool look as follows:
```
[...] ifetch      10 byte(s) @ 0x00007f86ef03d107 00001931 04020204 load store [4byte]       %rv0 %rv2 %rv36 -> %rv0
[...]                                             00000026
```
We also fix a formatting bug in …

i#6662 public traces, part 4: view tool

---

core/arch/aarch64/proc.c
core/ir/aarch64/codec_v85.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/dis-a64-v85.txt
suite/tests/api/ir_aarch64_v85.c

```
AXFLAG
XAFLAG
```
Issue: #2626

i#2626 AArch64 codec: Add FEAT_FlagM2 instructions

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

Refactors the scheduler marker processing into two virtual functions subclasses can override: the initialization time header marker reading now has process_next_initial_record() while regular processing has process_marker().
No change in functionality.  Future work will add "unscheduled thread" support with new markers, building on this refactoring.
Issue: #6822

i#6822 unscheduled: Virtualize scheduler marker processing

---

core/ir/x86/decode_table.c
core/ir/x86/instr_create_api.h
core/ir/x86/opcode_api.h
suite/tests/api/ir_x86_0args.h

The new TSXLDTRK feature in Sapphire Rapids adds two new instructions, XSUSLDTRK and XRESLDTRK. This commit adds support for them to the decoding and encoding machinery and adds tests.

Add encode/decode for new TSXLDTRK instructions.

---

core/unix/signal.c
suite/tests/api/detach_signal.cpp

Adds the missing app blocked sigmask in the frame-copy created for native signal delivery during detach.
During detach we do not have the thread's dcontext_t anymore, which includes thread_sig_info_t. There is existing code that creates a synthetic thread_sig_info_t for use by execute_native_handler(). To fix this issue, we only needed to set its app_sigblocked field from the signal frame (which was delivered to the native app thread, therefore contains the actual app blocked sigmask).
Modifies the existing detach_signal test to verify this scenario.
Fixes: #6828

i#6828: Fix blocked sigmask in native signal frame copy

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Augments the drmemtrace scheduler with a new notion of an "unscheduled" input which, if it has no timeout, is not runnable indefinitely until another input explicitly wakes it up.
Adds 3 new markers:
+ TRACE_MARKER_TYPE_SYSCALL_UNSCHEDULE, which makes the caller "unscheduled".
+ TRACE_MARKER_TYPE_SYSCALL_SCHEDULE, which makes a target no longer "unscheduled".
+ TRACE_MARKER_TYPE_SYSCALL_ARG_TIMEOUT which adds a timeout parameter to TRACE_MARKER_TYPE_SYSCALL_UNSCHEDULE and TRACE_MARKER_TYPE_DIRECT_THREAD_SWITCH
Adds handling for the new marker types.
Changes TRACE_MARKER_TYPE_DIRECT_THREAD_SWITCH to make the source input unscheduled, unless a timeout is passed which is honored (previously it was ignored and the syscall latency was used as the block time if it was over the thresholds).
Adds …

i#6822 unscheduled: Add unscheduled-input drmemtrace support

---

core/arch/aarch64/proc.c
core/arch/proc_api.h

Allow the following AARCH64 v8.3 and v8.4 features to be identified:
FEAT_SSBS
FEAT_SSBS2
FEAT_CONSTPACFIELD
FEAT_DIT
FEAT_LSE2
Issue: #5623

i#5623: Add AARCH64 v8.3 and v8.4 feature support bits

---

clients/drcachesim/tools/syscall_mix.h

Adds a virtual destructor to the drmemtrace tool
syscall_mix_t::shard_data_t, to support subclassing that struct
for extended usage such as tracking callstacks for each syscall.

Support subclassing drmemtrace syscall_mix data

---

core/arch/proc_api.h
core/arch/proc_shared.c
core/arch/riscv64/proc.c
core/unix/signal_linux_riscv64.c

Detects RISC-V vector extension support using SIGILL in signal_arch_init(). Manually tested on real hardware.
Issue: #3544

i#3544 RV64: Implements proc_has_feature() for vector extension

---

core/ir/aarch64/codec.c
core/ir/aarch64/encode.c
core/ir/opnd_api.h
core/ir/opnd_shared.c

Registers like ID_AA64ISAR0_EL1 are readable at EL0 on Linux, but are not included in the DR_REG enum as this only includes EL0 registers.
This means that MRS instructions that read these registers will not be disassembled in the normal way in the DR log.
Issue: #2626

i#2626: Add AARCH64 Attribute registers to the DR_REG enum

---

core/ir/aarch64/codec.c
core/ir/aarch64/codec_v80.txt
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v80.c

Extends INSTR_CREATE_msr to be able to encode the immediate variant of the MSR instruction:
```
MSR <pstatefield>, #<imm>
```
Adds codec support for some missing pstatefields, and adds missing IR and disassembly tests for MSR.
Issue: #2626

i#2626 AArch64: Add missing MSR variants

---

api/docs/release.dox
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tests/skip_to_timestamp.templatex
suite/tests/CMakeLists.txt

Adds a new feature times_of_interest to the drmemtrace scheduler. This allows specifying regions of interest via timestamps, which cut across all inputs in a workload, providing for a consistent starting point across all threads.
The feature requires a cpu schedule file which is used to build a mapping from timestamps to instruction ordinals.  The mapping is not perfect due to collapsed consecutive entries and coarse-grained timestamps so interpolation is used in between known points.
Adds a new analyzer command-line option -skip_to_timestamp which sets a single time-of-interest in the scheduler.  Adds a test using the checked-in threadsig x86_64 trace.
Fixes #6844

i#6844: Add times_of_interest to drmemtrace scheduler

---

clients/drcachesim/scheduler/scheduler.h

Fixes two misspellings of "timestamp" in the docs for the new times_of_interest drmemtrace scheduler feature.
Issue: #6844

i#6844 skip-to-time: Fix typos in drmemtrace docs

---

clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/reader.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Adds support for threads starting out in an "unscheduled" state.  This is accomplished by always reading ahead in each input and looking for a TRACE_MARKER_TYPE_SYSCALL_UNSCHEDULE marker *before* the first instruction.  Normally such a marker indicates the invocation of a system call and is after the system call instruction; for start-unscheduled threads it is present at the system call exit at the start of the trace.
Changes the scheduler's virtual method process_next_initial_record() to make the booleans on finding certain markers input-and-output parameters and moves filetype marker handling and timestamp recording into the function.  This also fixes a problem where an input's initial next_timestamp was replaced with the 2nd timestamp if a subclass read ahead.
The extra readahead …

i#6822 unscheduled: Add start-unscheduled support

---

core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64.h
suite/tests/api/ir_aarch64_v80.c

While working on another patch I noticed we were missing macros to create the GPR ORR instructions so this patch adds them along with IR unit tests.
Issue: #2626

i#2626 AArch64: Add missing INSTR_CREATE_orr macros

---

clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Adds a new virtual raw2trace per-record action point observe_entry_output() for use in subclasses to compute statistics or possibly trim nearly-empty start-unscheduled threads.
Issue: #6822

i#6822 unscheduled: Add raw2trace per-record action point

---

clients/drcachesim/common/options.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_launcher.cpp

Fixes an inconsistency in the CLI drmemtrace scheduler quantum and the internal API by making them both the same at 6 million.  We pick 6 million to match 2 instructions per nanosecond with a 3ms quantum. The scheduler_launcher default is also made to match.
Issue: #5843

i#5843 scheduler: Raise default drmemtrace sched quantum to 6M

---

.github/workflows/ci-osx.yml

Upgrades to macos-12 or ci-osx. As informed by https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/, macos-11 is now deprecated. This is causing our ci-osx workflow to fail and block PRs. Here we upgrade to the immediately next version for now, as that is least likely to introduce compatibility issues.
Issue: #6864

i#6864: Upgrade to macos-12 for ci-osx

---

suite/tests/CMakeLists.txt
suite/tests/api/ir_rvv.c
suite/tests/api/ir_rvv.expect

This is a follow-up patch of adding RISC-V vector (RVV) extension support to the core, part1 in PR https://github.com/DynamoRIO/dynamorio/pull/6810 (https://github.com/DynamoRIO/dynamorio/commit/f1ce1bca75ed24782f459543ecce57febd44311c), part2 in PR https://github.com/DynamoRIO/dynamorio/pull/6848 (https://github.com/DynamoRIO/dynamorio/commit/59d0360f3d68433c31d95c0b82082eaac275cd5c).
This patch adds ir-test of RISC-V vector extension.
Issue: #3544

i#3544 RV64 vector part3: Add vector instruction codec test

---

core/ir/aarch64/instr.c
core/ir/decode_shared.c
core/ir/opnd_api.h
core/ir/opnd_shared.c
ext/drx/scatter_gather_aarch64.c

I have done some testing with 512-bit vector registers and found a couple of bugs in the scatter/gather expansion code.
- An assert had incorrect logic (< should have been <=)
- Added OPSZ_192, needed to represent 3 512-bit Z registers.
Issue: #5036

i#5036 AArch64 scatter/gather: Fix 512-bit bugs

---

clients/drcachesim/tests/record_filter_keep_func_ids.templatex
clients/drcachesim/tools/filter/record_filter.cpp
suite/tests/CMakeLists.txt

When filtering function related markers (i.e., TRACE_MARKER_TYPE_FUNC_) by function ID we need to provide the original marker value (function ID) in the trace to func_id_filter.
When filtering out system calls, the ID can be large due to TRACE_FUNC_ID_SYSCALL_BASE (which is 0x100000000ULL == 4294967296 for x64) that is added to the system call number, and can cause an std::out_of_range error.
We now use std::stoull to handle large function IDs.
We add a test which runs func_id_filter (part of record_filter) with a large function ID and then checks that there is no function marker left in the filtered trace with basic_counts.
Issue #6662

i#6662 func_id_filter: large function IDs

---

clients/drcachesim/tools/filter/record_filter.cpp

std::numeric_limits<>::min()/max() return 0 on enum types.
This causes the parse_string() specialization for trace_marker_type_t and trace_type_t to not add any value to the vector used by type_filter to remove markers from a trace.
We revert this change to the previous behavior: always add the parsed value to the vector, even if static_cast<> might truncate it.
If we want to re-add the check that type T can hold the parsed value, we'll need to add std::underlying_type support to trace_marker_type_t and trace_type_t enums.
Issue #6662

i#6662 type_filter: parse_string() bug fix

---

suite/tests/CMakeLists.txt
suite/tests/client-interface/dr_options.dll.c

Port client.dr_options test to AARCH64.
Issue: #4474

i#4474: Port client.dr_options test to AARCH64

---

core/arch/riscv64/memfuncs.asm
core/io.c

We optimized RV64 memfuncs in PR #6800. However, there was a mistake where the return value of memcpy was incorrectly set to ARG2 which led to segfaults in the release build. This PR addresses this issue. Additionally, our unit_tests did not catch this error because `ret = our_memcpy(&i, &j, sizeof(i));` was optimized by the compiler to `i = j; ret = &i;`. We resolved this by utilizing the `noinline` attribute.

i#3544 RV64: Fix our memcpy return value error

---

core/options.c
core/unix/os.c
core/unix/signal.c

PR #5835 inadvertently broke support for large pages on AArch64 by introducing code that assumed a 4K page size.
The core options unit_tests were also failing on large page systems because a lot of options need to be overridden and the test was not accounting for extra options being set in the options string.
Issues: #1680, #6451
Fixes: #6451

i#6451 AArch64: Fix large page support

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

The drmemtrace scheduler was not honoring output bindings during dynamic-mode initialization without time dependencies.  This is fixed here and a test is added.
Fixes #6874

i#6874: Honor bindings in drmemtrace scheduler no-time-dep init

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tracer/tracer.cpp

Adds a new drmemtrace marker holding the signal number which is emitted after the kernel event marker.  It is not emitted at the signal return point; only at the transfer to the handler.
Does not add a feature bit or increase the version as this marker is considered optional and so no mechanism is provided for users to be guaranteed that it is present.
Adds view tool support.
Adds a test that the marker is emitted in the burst_gencode test. Output from the test's trace:
```
52          32:     1616564 ifetch       2 byte(s) @ 0x00007f615935d023 0f 0b                ud2
53          32:     1616564 <marker: kernel xfer from 0x7f615935d023 to handler>
54          32:     1616564 <marker: signal #4>
55          32:     1616564 <marker: timestamp 13365562571171519>
56          32:     1616564 …
```

i#6884: Add drmemtrace signal number marker

---

api/docs/code_reviews.dox

Updates the docs on merging a pull request to the new scheme of using the pull request title + description.  The docs were still describing the old setup where devs had to manually edit a concatenated squash-and-merge message.

Update squash-and-merge docs

---

clients/drcachesim/tools/view.cpp

Adds a missing closing '>' to the drmemtrace view tool's output for a syscall that makes a thread become unscheduled.
Issue: #6822

i#6822 unsched: Add missing closing '>' to drmemtrace view tool

---

make/git/commit-template.txt
make/git/hook-commit-msg.sh

Removes "<issue-brief>" from the commit template title line as it is only for multi-part commits.  Adds a template line explaining what to do for multi-part commits.
Updates the unedited-template check.

Clarify commit template for single vs multi-part commits

---

suite/tests/api/drdecode_aarch64.c

On AArch64 instrlist_insert_mov_instr_addr() uses a sequence of movz and movk instructions to, and uses the encode_estimate pointer to determine how many movk instructions will be needed.
The test api.drdecode was calling instrlist_insert_mov_instr_addr() with this ilist as the encode_estimate pointer which proved to be a bad estimate on some systems.
The system where I was testing had:
ilist =          0x000000001a3b0380
generated_code = 0x0000ffffb4fb0000
Each movz/movk instruction in the sequence encodes a 16-bit immediate so
3 instructions would be needed to move an address in the generated_code
buffer, but using the ilist pointer as an estimate we would only generate
2 and end up with a truncated address.
Now the test will allocate the buffer for the generated code up front so we can …

i#2417 AArch64: Fix drdecode test

---

clients/drcachesim/tests/burst_aarch64_sys.cpp

tool.drcacheoff.burst_aarch64_sys fails with an assert on systems with 256-byte cache lines such as A64FX.
Issue: #2417

i#2417 AArch64: Fix test on large cache line cpus

---

clients/drcachesim/scheduler/scheduler.cpp

Adds a comment explaining that rounding down when interpolating for the drmemtrace skip-to-timestamp feature is the right thing to do, as it ensures we include a system call that spans the start time and thus will correctly block/unschedule up front.
Issue: #6844

i#6844 skip time: Explain rounding down for drmemtrace interpolation

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

For inputs with regions of interest that skip over their initial records, the drmemtrace scheduler was using the initial records for the initial timestamp and start-unscheduled state, which is incorrect.
Solves this by applying an initial region skip at init time instead of waiting for an input to be scheduled.  This requires shifting around when record file output is recorded.
Adds a unit test that fails without this fix as it leaves one input permanently unscheduled and has the two inputs in the wrong order without using the skip timestamp.
Fixes #6882

i#6882: Set drmemtrace scheduler init state to post-skip

---

clients/drcachesim/tracer/instru_online.cpp
clients/drcachesim/tracer/tracer.cpp

Fix the issue in drcachesim where missing architecture-related code leads to incorrect counting results.
Issue: #3544

i#3544 RV64: Add the missing architecture-related code to drcachesim

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/common/schedule_file.cpp
clients/drcachesim/common/schedule_file.h
clients/drcachesim/reader/record_file_reader.h
clients/drcachesim/tests/schedule_file_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Refactors the raw2trace and invariant_checker code dealing with schedule files into a common "schedule_file" library.
Adds some unit tests for the library.
Issue: #6897

i#6897 sched file: Create drmemtace schedule file library

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/common/zipfile_ostream.h
clients/drcachesim/tests/record_filter_unit_tests.cpp
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/filter/record_filter.h
clients/drcachesim/tools/record_filter_launcher.cpp

Leverages the new schedule file library in the drmemtrace record_filter to produce schedule files for derived traces, which were previously missing.
Adds schedule file checks to the record filter unit tests.  The existing end-to-end tests run invariant_checker which checks schedule file contents now that they're created.
Adds a missing check for print_stats failing to record_filter_launcher.
Fixes #6897

i#6897 sched file: Add schedule file output to record_filter

---

api/docs/triager.dox

Adds docs to the triager page https://dynamorio.org/page_triager.html on moderating messages sent to the users list from first-time posters.

Add triager docs on moderating the user list

---

make/DynamoRIOConfig.cmake.in

After switching to the elfutils submodule, libraries libelf and libdwarf became optional. Static library libelftc is still required to be linked, so in cmake files there must be a separate check for it.
The issue appears when building an external DynamoRIO client.
Issue: #6909

i6909: Handle libelftc separately in cmake files

---

clients/drcachesim/scheduler/scheduler.cpp

We make logging available in release build to help with diagnosing issues and understanding scheduler behavior.  We assume the extra branches do not add undue overhead.
Issue: #5843

i#5843 scheduler: Enable logging in release build

---

core/heap.c
core/unix/os.c

Fixes 3 problems hit on recent Linux kernels where our mmap hints are being ignored:
1) os_heap_reserve_in_region()'s POINTER_MAX check fails as the end is aligned,
causing an unnecessary bounded-region search.
2) vmm_place_vmcode() tries smaller sizes on failure but does not propagate
the new size to the caller, resulting in memory corruption.
3) os_heap_reserve() for Linux now uses the new-ish MAP_FIXED_NOREPLACE
to get the behavior various code expects without risk of clobbering.
Tested on a 6.7.12 kernel where raw2trace failed up front reliably without these fixes but now succeeds.
Further tested the size propagation with the other fixes disabled and now we have a graceful failure instead of memory corruption and a weird crash:
```
$ clients/bin64/drmemtrace_launcher -indir …
```

i#6921: Fix heap allocation on latest Linux kernel

---

core/unix/os.c

Define MAP_FIXED_NOREPLACE if it isn't provided by the system headers, as it is not always available.
Issue: #6921

i#6921 preferred mmap: Ensure MAP_FIXED_NOREPLACE is always defined

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/analyzer_multi.h
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/only_shards.templatex
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/filter/record_filter.cpp
suite/tests/CMakeLists.txt

Adds a new filter by shard ordinal to the drmemtrace scheduler and analyzers, and adds multi-thread filtering on the command line.
Adds input_workload_t.only_shards to filter scheduler inputs by ordinal, which is mostly useful for core-sharded-on-disk traces.
Adds new CLI options -only_shards, which takes a comma-separated list of ordinals, and -only_threads, which takes a comma-separated list of tids.
Adds sorting of file names when reading inputs from a directory so that ordinals are reliable.  Adds leading 0's to record_filter's output name so this lexicographic sort keeps cores in order.
Adds error checking that any tid or ordinal filter is actually present in the inputs.
Adds an internal struct input_read_info_t to implement the new filtering inside the scheduler.
Adds scheduler unit …

i#6685 core-shard: Add only_shards drmemtrace filter

---

clients/drcachesim/reader/reader.cpp
clients/drcachesim/tracer/output.cpp

Encodings can occupy multiple consecutive records, especially for 32-bit where the record size is smaller.  For online tracing, we were allowing buffer splits for atomic pipe writes in between encoding records.  We fix that here.
Tested via "ctest --repeat-until-fail 10000 -R drcachesim.opcode_mix". This was failing locally every 500-1500 runs.  With named_pipe_t::get_atomic_write_size() returning 512 it was failing every 14 runs.  With the fix it has yet to fail after thousands of runs.
Fixes #6303

i#6303: Do not split encodings when splitting pipe writes

---

core/unix/loader.c

Adds decoding of __libc_early_init to find the glibc private loader workaround
offsets we need.  The heuristic is to look for the last large (>0x100) load offset before
the first DIV.
Tested on 2.38 64-bit and 32-bit.
Also updates the __libc_early_init offsets for 32-bit glibc 2.38 as a fallback.
Tested locally.
Issue: #5437

i#5437 glibc: Auto-deduce __libc_early_init offsets

---

clients/drcachesim/tests/offline-kernel-simple.templatex
clients/drcachesim/tracer/kcore_copy.cpp

Modifies the kcore dump logic to include multiple pages worth of kcore after each BPF JIT symbol. It does not seem uncommon for /proc/kallsyms to not have full coverage of BPF JIT code seen in the PT raw trace, even at the page-level. This increases the kcore dump size only by a very small amount (< ~1%).
Verified that the PT related tests continue to work on a system that supports the Intel-PT hardware feature:
```
The following tests passed:
code_api|tool.drcacheoff.kernel.simple_SUDO
code_api|tool.drcacheoff.kernel.opcode-mix_SUDO
code_api|tool.drcacheoff.kernel.syscall-mix_SUDO
code_api|tool.drcacheoff.kernel.invariant-checker_SUDO
The following tests passed:
code_api|client.drpttracer_SUDO-test
```
Issue: #5505

i#5505 kernel tracing: Dump more potential BPF JIT code

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tests/offline-kernel-simple.templatex
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tracer/tracer.cpp

Delays outputting the TRACE_MARKER_TYPE_SYSCALL_IDX marker to the post-syscall callback (instead of the pre-syscall callback where it is output currently) where we also output the PT trace. Some drmemtrace derivations may interleave user-space and PT trace data, which means we want the PT trace to be read before the syscall_idx marker. If a signal interrupts the syscall, then the syscall_idx marker will be written to trace before the PT trace: we want to avoid this.
Relaxes invariant checks related to the syscall_num marker before the syscall trace start marker for PT instr-only traces. In the case described above, there will be no syscall_num marker immediately before the syscall trace start. Added a comment noting the complexities of handling this case, which exist even without the …

i#5505 kernel tracing: Delay syscall_idx marker after PT trace

---

clients/drcachesim/tools/func_view.cpp
clients/drcachesim/tools/func_view.h

While debugging a malformed trace, I hit multiple crashes in func_view. This update eliminates two causes of these crashes: situations that would previously decrement the nesting level below zero now print warnings instead, and any function IDs encountered in the trace that don't have a matching funclist.log entry are reported as an error.
Fixes: #6913

i#6913: Eliminate unsafe accesses in func_view

---

clients/drcachesim/tools/view.cpp
suite/tests/CMakeLists.txt

The view tool was blindly loading binaries even for traces that have
encodings.  This leads to fatal errors when binaries have changed, even
when the change has no impact on viewing a trace.  We fix that here by
reading the filtype at init time.
Work around the #6942 crash by always setting the disasm syntax to DR style
for REGDEPS traces.
This change actually sets the disasm syntax to AT&T by default if no module
path is passed in; which is what it is supposed to do: but it was not doing
that and this breaks 3 tests comparing DR-style output.  We put in a quick
fix to request DR style for those tests.
Tested locally where the view tool asserts without this fix.
Issue: #6940, #6942
Fixes #6940

i#6940: Do not always load binaries in view tool

---

api/docs/deployment.dox
api/docs/intro.dox

Adds a new documentation section on statically linking DR and clients into the application, and the limitations of that mode.
Issue: #975

i#975 static DR: Document statically linked DR usage

---

clients/drcachesim/common/options.cpp
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

Reduces the scheduler and drmemtrace launcher default values for block_time_scale down to 10 and block_time_max down to 2.5s.  This improves the scheduler behavior for small traces under fast analyzers. It seems better to err on the side of faster and let more heavyweight simulations tune the block times for more idle time; otherwise we can end up with local runs and especially new users trying things out and seeing the tool seem to just sit there doing nothing.
This reduces the threadsig core-sharded time from a minute and a half down to 10 seconds in local runs (see #6945 for command lines); there is still some idle time in there so it seems a reasonable compromise.
Fixes #6945

i#6945: Reduce default block time

---

clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/schedule_stats.cpp

Adds schedule statistics to memtrace_stream.h.  Implements these statistics in the streams returned by scheduler_t.  This initial round includes the following values:
```
[scheduler] Stats for output #0
[scheduler]   Switch input->input      :        16
[scheduler]   Switch input->idle       :         4
[scheduler]   Switch idle->input       :         3
[scheduler]   Switch nop               :       119
[scheduler]   Quantum preempts         :       131
[scheduler]   Direct switch attempts   :         0
[scheduler]   Direct switch successes  :         0
```
The switches are split into those 4 categories to make it easier to compare to other sources of switch counts, such as `perf` where `perf` limited to a cgroup or process will be missing the `idle->input` switches, or schedule_stats …

i#6938 sched migrate: Add scheduler statistics

---

clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds the migration count to the new scheduler stats. Adds checks of the count to various unit tests.
Issue: #6938

i#6938 sched migrate: Add migration count to scheduler

---

suite/tests/linux/sigcontext.c

Replaces a kill() with an inlined system call in the linux.sigcontext test to avoid failure when compiled for AVX only, as the compiler inserts VZEROUPPER there (VZEROUPPER is recommended by Intel to avoid a performance penalty when switching between upper-zeroing VEX-encoded XMM operations and legacy upper-preserving SSE* operations: so doing it at transitions to code you don't control makes sense).
Tested on a toolchain targeting AVX.
Fixes #6953

i#6953: Fix sigcontext test AVX error

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Adds the new scheduler-provided statistics to the schedule_stats tool. 
Adds a sanity test check.
Tested on some larger apps where a high count of "nop" switches was sometimes found; as part of understanding those, I found a code path where if the runqueue is empty and the current thread is supposed to go unscheduled it would be run again instead.  Fixed that here; unclear it has ever happened.
Issue: #6938

i#6938 sched migrate: Include scheduler stats in schedule_stats

---

clients/drcachesim/scheduler/scheduler.cpp

Reverts a fix for a bug in the scheduler where it let a thread going unscheduled continue running if there are no other non-running-now scheduleable inputs.  This triggered too-frequent all-unscheduled cases and the current timeout for those is too high, causing tail delays.  We'll re-instate the fix once we add an early exit feature for that scenario.
Issue: #6959

i#6959 all-unsched: Revert only-unscheduled fix

---

clients/drcachesim/tools/invariant_checker.cpp

Temporarily suppresses the drmemtrace invariant checker test for a thread exit record in online mode as it is happening frequently enough in our tests that it is blocking progress, though at the same time it is very difficult to reproduce locally and figure it out.  We want our tests green as a priority for now and can re-enable once someone figures out the root cause.  This only affects online mode.
Issue: #6733

i#6733 missing exit: Suppress drmemtrace invariant check

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/common/mutex_dbg_owned.cpp
clients/drcachesim/common/mutex_dbg_owned.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/memref_gen.h

Adds lock contention counters for mutex_dbg_owned::lock() in non-NDEBUG builds.
While it's not there for release builds, the results in non-release should still be
indicative of general lock behavior.
When I just changed the mutex_dbg_owned header, the relese build static drmemtrace
tests (e.g., the burst_* ones) were all failing with floating point exceptions.  It
turns out it's due to different compilation units having different values for NDEBUG.
I tried to make them all the same: but we have some files that contain `#undef NDEBUG`
and other complexities.  So I split the mutex_dbg_owned implementation into a
.cpp file and have the mutex wrapper extra fields always present.
Prints the stats for sched_lock_ with the other scheduler stats.
Sample results on schedule_stats on a threadsig …

i#6938 sched migrate: Add lock contention stats

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Improves speculation error checking by printing the error message on failure.  Adds missing return status checks to the speculation calls in the speculator unit test.
Issue: #5843

i#5843 scheduler: Improve speculation error checking

---

clients/drcachesim/tests/scheduler_unit_tests.cpp

Replaces a comment with an official compiler annotation for a switch case fallthrough, to fix a warning under some compilers as part of running scheduler_unit_tests internally.
Issue: #6938

i#6938 sched migrate: Use annotation for fallthrough

---

clients/drcachesim/scheduler/scheduler.cpp

Only call gettimeofday once per next_record for instruction quanta, rather than every get_output_time() call.
Future work will try to revisit using a counter to eliminate the non-determinism of wall-clock time and make analyzers behavior more like simulators, easing testing.
Issue: #6971

i#6971 sched time: Reduce gettimeofday calls

---

clients/drcachesim/scheduler/scheduler.cpp

Direct thread switches were not being counted as migrations in the original migration stats in PR #6950: we address that here.  A test with multiple outputs will be added later as part of the move to separate runqueues, which is where this bug was discovered.
Issue: #6938

i#6938 sched migrate: Count direct switches as migrations

---

clients/drcachesim/scheduler/scheduler.cpp

Fix bug underflowing quantum time when trying to correct overshoot but the quantum just expired and so is 0; or, we're replaying. Adds an assert.
A test will come in the forthcoming rebalance test for per-output runqueues, which is where this bug was discovered.
Fixes #6977

i#6977: Fix quantum underflow

---

clients/drcachesim/tests/trace_interval_analysis_unit_tests.cpp

My local compiler (clang 14.0.0) complained about a missing override keyword in trace_interval_analysis_unit_tests.c; fixed here.

Add missing override keyword in memtrace unit tests

---

core/loader_shared.c
core/module_shared.h
core/unix/loader.c
core/unix/module_elf.c
suite/tests/CMakeLists.txt

In `module_lookup_symbol`, which is invoked from DynamoRIO's private loader, skip other top-level client modules (but not extensions/libraries) because some will not be initialised and top-level clients should be leaves of the dependency tree and not provide symbols for other modules. Top-level client modules are recognised using a new module flag, `is_top_level_client`.
Also add a test that two clients can be loaded without a crash.
Fixes #4501

i#4501: In module_lookup_symbol skip other client modules.

---

.github/workflows/ci-package.yml

Changes the version used for upload-artifact and download-artifact actions to the current one recommended at https://github.com/actions/upload-artifact and https://github.com/actions/download-artifact.
For these two actions, "v4" points to the latest available v4.x.x release, as evidenced by the commit hash for the versions at https://github.com/actions/download-artifact/tags and https://github.com/actions/upload-artifact/tags. So we would still be using the latest version as suggested by the security advisory for download-artifact (https://github.com/advisories/GHSA-cxww-7g56-2vh6).
PR #6964 bumped the download-artifact version but not the upload-artifact which caused a mismatch and the #6981 issue.
Test run worked fine: https://github.com/DynamoRIO/dynamorio/actions/runs/10835746272 …

i#6981: Use consistent version for upload-artifact and download-artifact

---

clients/drcachesim/docs/drcachesim.dox.in

Promotes the scheduler section to a full page and adds information on the deficiencies of the as-traced schedule, details of dynamic scheduling, simulated time, idle time, record-replay, regions of interest, and speculation support.  Updates the example code to include multiple threads each processing one core.
Issue: #5843

i#5843 scheduler: Improve drmemtrace scheduler documentation

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_launcher.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Refactors the scheduler's time-oriented options to become based on simulated microseconds rather than being unitless and having to all be separately scaled depending on the simulator's clock.
Deprecates these scheduler_options_t fields, replacing them with new versions:
+ quantum_duration => quantum_duration_{instructions,us}
+ block_time_scale => block_time_multiplier
+ block_time_max => block_time_max_us
Adds a new "time_units_per_us" which is the single place where a simulator sets the relationship between the value passed to "cur_time" in next_record() and simulated microseconds.  The aforementioned fields are all compared to cur_time multiplied by time_units_per_us.
This is a prelude to adding yet more time-based options for the forthcoming scheduler additions with migration …

i#6938 sched migrate: All options in microseconds + single scale

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

Fixes clang-tidy complaints from PR #6985 about a misspelling, mismatched parameter names, and missing includes, and removes a stale comment.
Issue: #6938

i#6938 sched migrate: Fix clang-tidy complaints

---

clients/drcachesim/scheduler/scheduler.cpp

Adds a missing clear of an input being "unscheduled" when it times out but is not selected (due to the migration threshold).  This fixes an assert a few lines above this fix the next time this input is selected in pop_from_ready_queue_hold_locks().
Tested on a particular input which triggers the assert.
Issue: #6938

i#6938 sched migrate: Fix input not unscheduled assert

---

clients/drcachesim/common/options.cpp
clients/drcachesim/scheduler/scheduler.h

It turns out the Linux kernel's maximum rebalance period is 100ms (the actual value varies dynamically; our simplified scheduler uses a constant, though).  We thus drop our default value from 150ms to 50ms which should better match real machines.  We also make the launcher's default match the scheduler's default as the launcher's was even higher.
Issue: #6938

i#6938 sched migrate: Reduce rebalance period to better match kernel

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

PR #6985 removed the global sched_lock_ which used to synchronize
access to other output's record_index field, leaving a data
race (affecting only the rough timing across outputs where an output
waits if gets ahead of other outputs' timestamps).
Since only the index and not the recorded contents need
synchronization, we use an atomic rather than a mutex to coordinate.
Tested by running an internal test under ThreadSanitizer where a race
is reported without this fix and no race with the fix.
Issue: #6938

i#6938 sched migrate: Make replay record_index atomic

---

clients/drcachesim/scheduler/scheduler.cpp

Adds a missing input lock to the result of popping from the queue.
Changes set_cur_input to set the prior input's last_run_time, etc. *before* adding to the ready queue.
Tested by running ThreadSanitizer on the same internal test where it reported a race in reading input_info_t.last_run_time by pop_from_ready_queue_hold_locks while not holding a lock (during a rebalance), versus set_cur_input writing to that field.
Issue: #6938

i#6938 sched migrate: Add input lock to queue pop result

---

api/docs/API.doxy
api/docs/CMakeLists.txt
api/docs/intro.dox
api/docs/transp.dox
api/docs/tutorial_secdev16.dox

Generating RTF documentation is causing `error: Style 'Heading7' redefines \s0.`
errors with doxygen 1.12. We disable RTF in api/docs/API.doxy.
We fix `warning: unable to resolve reference to 'ref1' for \ref command` issues
using `\anchor ref1` instead of `<a name="ref1"></a>` when citing papers in
"SecDev 2016 Tutorial".
Fixes #6992

i#6992 doxygen 1.12: heading and reference workaround

---

clients/drcachesim/simulator/caching_device_stats.cpp

The format specifier "%lld" used for `memref_pid_t` in printf statement may not be correct for all platform. `memref_pid_t` is `int64_t` which may be `signed long int`. `memref_pid_t` should not be print with "%lld" format specifier. Should use PRId64 defined in <inttypes.h> instead.
Further details:
distro: KDE Neon 6.0
gcc: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
In "dynamorio/clients/drcachesim/common/memref.h":52
```
typedef int64_t memref_pid_t;
```
In "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h":27
```
typedef __int64_t int64_t;
```
In "/usr/include/x86_64-linux-gnu/bits/types.h":44
```
typedef signed long int __int64_t;
```

Fix printf format specifier for `memref_pid_t`

---

clients/drcachesim/common/options.h
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/cache_simulator.h
clients/drcachesim/simulator/prefetcher.cpp
clients/drcachesim/simulator/prefetcher.h
clients/drcachesim/tests/drcachesim_unit_tests.cpp

Add constructors to the cache_simulator_t that accept a custom prefetcher factory argument.
No change to default behavior.
Added unit tests for a custom prefetcher and the existing nextline prefetcher.

Add support for custom prefetchers in drcachesim

---

clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Sets the scheduler_t system call switch thresholds to match the command-line interface defaults, which were raised a long time ago to reflect better understanding of real behavior.
Issue: #5843

i#5843 scheduler: Make scheduler_t and CLI thresholds match

---

core/win32/loader.c

Extends the private loader bcrypt.dll entry failure being ignore to ignore all private library entry failures.  We have had multiple cases of initializers failing without fatal consequences, and given that we do not have resources to track down every detail it is best to note the failure and move on.  We have seen Dr. Memory in particular fail on newer Windows versions and in some cases ignoring that failure lets the tool continue and succeed, as only a small piece of the private library is needed (generally pulled in as a chain of dependences from dbghelp.dll which is used for symbol information).  The private loader on Windows is considered best-effort at this point.
Issue: #6570, #6962

i#6570 entry failure: Ignore all privlib failures

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h

Removes a duplicate option -sched_time_per_us which was accidentally added by PR #6980 separately from the similar -sched_time_units_per_us from PR #6985.
Issue: #6938

i#6938 sched migrate: Remove duplicate option

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Fixes a bug for going-unscheduled actions where scaling a small timeout rounds it down to 0, which is then interpreted as an infinite timeout.
Adds a unit test that fails without the fix.
Issue: #6822

i#6822 unscheduled: Fix bug making small timeouts infinite

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Fixes a bug where an input that just went unscheduled indefinitely will be resumed if there are no other inputs to run.
Adds a unit test that fails without the fix.
Issue: #6959, #6822

i#6959 unsched exit: Fix stay-unsched bug

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new drmemtrace scheduler option
scheduler_options_t.honor_infinite_timeouts and a CLI parameter -sched_infinite_timeouts, both off by default.  If turned on, these match the previous behavior.
Changes the default behavior to use the (scaled per the scale parameter) maximum block timeout for indefinitely-unscheduled cases, rather than using an infinite timeout.  This avoids waiting a long time for things like background threads that do nothing but wait the entire duration of a trace.
Adds unit test variants for both infinite and max-timeout.
Tested on a large application where this did not noticeably decrease the successful number of direct switches, but did reduce the idle time which was too high previously.
Issue: #6822

i#6822 unscheduled: Change infinite to max timeout in scheduler

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

Adds a -verbose 1 dump of the scheduler options at startup.  This helps to record what options were passed in a particular run.
Issue: #6938

i#6938 sched migrate: Print configuration at startup

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Improves diagnostics by augmenting the all-runqueue printing:
+ It now constructs its many-line string in memory and then prints it all at once, to make it more atomic.
+ It includes the remaining blocked times for blocked inputs.
+ It is moved from pop_from_ready_queue() where the popped input is in flux to pick_next_input() where the current running input is valid.
+ It is printed more frequently.
Also prints the size of the unscheduled queue when moving it.
Issue: #6938

i#6938 sched migrate: Print blocked times in queues

---

clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new scheduler feature and CLI option exit_if_fraction_left. This applies to -core_sharded and -core_serial modes.  When an input reaches EOF, if the number of non-EOF inputs left as a fraction of the original inputs is equal to or less than this value then the scheduler exits (sets all outputs to EOF) rather than finishing off the final inputs.  This helps avoid long sequences of idles during staggered endings with fewer inputs left than cores and only a small fraction of the total instructions left in those inputs.
The default value in scheduler_options_t is 0 as simulators are typically already choosing to stop at some even point.  For analyzers, however, via the command-line option, the default is 0.05 (i.e., 5%), which when tested on an large internal trace helps eliminate much …

i#6959: Add exit_if_fraction_left option

---

clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/simulator/prefetcher.cpp
clients/drcachesim/simulator/prefetcher.h
clients/drcachesim/tests/drcachesim_unit_tests.cpp

This allows custom prefetchers to train on cache hits in addition to misses

Move conditions for prefetching into the prefetch() function

---

CMakeLists.txt
make/package.cmake

Replaces the AUTOMATED_TESTING set in package builds by PR #5769 with a new DISABLE_ZLIB CMake option to accomplish the goal of disabling the zlib found on these VMs while avoiding turning off msgbox_mask. The disabling by default of msgbox_mask in packages has caused many users to fail to obtain error information and has led to confusion with silent errors.
Tested: built a cronbuild based on this branch and downloaded it to the Windows VM used for #7024.
I ran this:
```
C:\Users\bruening\DynamoRIO-Windows-10.93.20004>bin64\drrun -- msg
<Application C:\Windows\system32\msg.exe (3892).  Out of memory.  Program aborted.  Source I, type 0x0000000000000001, code 0x00000000c000001c.>
```
And confirmed a messagebox popped up: thus showing that `-msgbox_mask` is *not* set to 0 anymore.
Issue: …

i#7025: Restore msgbox_mask package defaults

---

core/heap.c
core/optionsx.h

Adds the use of "-vm_base 0" to mean to let the OS pick our vmcode base, with no random offset applied.  This was useful during diagnosing the OOM from the CrowdStrike hook.
Issue: #7024

i#7024 hook oom: Allow vm_base=0 to mean pick from OS

---

ext/drx/scatter_gather_aarch64.c

Fixes the compiler error seen on GCC 13.2:
ext/drx/scatter_gather_aarch64.c:1238:37: error:
array subscript 2 is above array bounds of 'sg_slot_t[2]' {aka 'struct _sg_slot_t[2]'}
[-Werror=array-bounds=]
1238 |     DR_ASSERT(slot_state->pred_slots[slot].kind == SLOT_KIND_UNUSED);
In practice the code will never make an out of bounds access because the for loop above will always terminate by breaking so `slot` is always `< NUM_PRED_SLOTS`.
Issue: #5036

i#5036 AArch64 scatter/gather: Fix GCC 13.2 compiler error

---

clients/drcachesim/CMakeLists.txt
clients/drcachesim/tests/burst_syscall_pt.cpp
clients/drcachesim/tests/offline-burst_syscall_pt_SUDO.template
clients/drcachesim/tests/offline-burst_syscall_pt_SUDO.templatex
clients/drcachesim/tracer/tracer.cpp
suite/tests/CMakeLists.txt

Adds a test where one of the threads is waiting on a futex when detach occurs. PT traces for such futex syscalls have been observed to fail in libipt decode. We also do not want such PT traces because they do not represent real app behavior, as the syscall was interrupted by DR's detach signal. #7027 added logic to skip them from the written trace. 
This PR adds a regression test. Unfortunately this test still does not reproduce the original libipt decode issue that was seen on a large app. Most errors seen were on a modified kernel and only a few on a regular futex. But it is still useful to add this test that ensures that the thread-final interrupted syscall is skipped.
This test also uncovers a possible transparency violation seen in the behavior of an interrupted-and-restarted futex …

i#5505 PT tracing: Add burst PT test with interrupted futex

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

The drmemtrace replay of idles was using wall-clock time to reproduce the duration.  A new idle replay type is added here (and made the default) which uses the idle record count instead, leaving support for the old format under the old type.
Idle during replay now properly returns STATUS_IDLE, rather than STATUS_WAIT.
Tested the new idle type on the existing record-replay tests inside scheduler_unit_tests and in core_sharded_test.
Support for the old format is considered best-effort as its use of wall-clock time makes it not able to reproduce precise timing in any case.  Tested manually by generating an old-style record and ensuring the new code handled it:
$ clients/bin64/drmemtrace_launcher -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir -core_sharded -cores 4 …

i#7023: Switch drmemtrace replay of idles to use record count

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

In core-sharded dynamically-scheduled mode, the as-traced cpu ids and timestamps are interleaved in a way that makes them confusing and not useful.  We change the scheduler here to replace each cpu id value with the shard id, and replace the timestamp with a synthetic value based on the instruction and idle counts.
Adds a test.
Fixes #7028

i#7028: Modify core-sharded cpu ids and timestamps

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Previously, a never-executed input could be moved to another output at any time, yet was still counted as a "migration".  We change that here to consider a never-executed input to have executed at the initial simulation time seen on an output, so it will not be migrated until that threshold is met.  An exception is the very first rebalance at init time for the initial allocation of inputs to outputs when inputs can be freely moved; this does not count as a migration.
Issue: #6938

i#6938 sched migrate: Enforce migration threshold at the start

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

Fixes a race in the drmemtrace scheduler by making output_info_t.initial_cur_time atomic.
Tested on ThreadSanitizer on the internal test where this was first reported.
Issue: #6938

i#6938 sched migrate: Make initial_cur_time atomic

---

clients/drcachesim/docs/drcachesim.dox.in

Updates the documentation to explain that dynamic scheduling modifies timestamp and cpu id markers.
Issue: #7028

i#7028 mod markers: Document scheduler-modified markers

---

api/docs/release.dox
clients/drcachesim/analysis_tool.h
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/simulator.cpp
clients/drcachesim/simulator/simulator.h
clients/drcachesim/simulator/tlb_simulator.cpp
clients/drcachesim/tests/offline-burst_client.templatex
clients/drcachesim/tests/offline-burst_maps.templatex
clients/drcachesim/tests/offline-burst_noreach.templatex
clients/drcachesim/tests/offline-burst_replace.templatex
clients/drcachesim/tests/offline-burst_static.templatex
clients/drcachesim/tests/offline-filter-and-instr-only-trace.templatex
clients/drcachesim/tests/offline-filter.templatex
clients/drcachesim/tests/offline-fork.templatex
clients/drcachesim/tests/offline-instr-only-trace.templatex
clients/drcachesim/tests/offline-multiproc.templatex
clients/drcachesim/tests/offline-simple.templatex
clients/drcachesim/tests/offline-tlb_simulator_v2p.templatex
clients/drcachesim/tools/schedule_stats.h
suite/tests/CMakeLists.txt

Adds a new interface trace_analysis_tool::preferred_shard_type() to the drmemtrace framework to allow tools to request core-sharded operation.
The cache simulator, TLB simulator, and schedule_stats tools override the new interface to request core-sharded mode.
In the launcher, if all tools prefer core-sharded, and the user did not specify sharding (via -[no_]core_{sharded,serial} or -cpu_scheduling), then core-sharded (or core-serial) mode is enabled, with a -verbose 1+ message.
```
$ bin64/drrun -stderr_mask 0 -t drcachesim -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir/ -verbose 1 -tool schedule_stats:cache_simulator
Enabling -core_serial as all tools prefer it
<...>
Schedule stats tool results:
Total counts:
4 cores
8 threads: 1257600, 1257602, 1257599, …
```

i#6949: Enable core-sharded by default for simulators

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h

Fixes a deadlock on replay introduced by PR #6985.  If a recorded schedule has back-to-back entries with the same input (with a gap where another thread runs that input in between of course) and it has to wait for that other thread for its 2nd stint with that input, it will deadlock as it holds the input's lock while it tries to get the lock in set_cur_input().  That 2nd lock acquisition is what was added by PR #6985: that's the source of the regression.
Tested on a 12-thread threadsig trace which hangs without the fix and succeeds with the fix.  It is too large to turn into a convenient regression test.
Issue: #7044

i#7044 hang: Fix deadlock regression on drmemtrace replay

---

clients/drcachesim/analyzer.cpp

Adds a 1ms sleep on a STATUS_WAIT in the drmemtrace analyzer when operating in parallel.  This avoids costly spinning in replay mode. Adding targeted condition variables inside the scheduler doesn't end up performing any better and is complicated by the scheduler not knowing the threading model of the user, so this is a safer and simpler solution despite not waiting on an event.
Tested on a medium-large internal trace where the spinning makes replaying as-traced take 7:35; with the sleep it takes 1:15.
Fixes #7044

i#7044 hang: Sleep on wait in parallel drmemtrace analyzer

---

clients/drcachesim/scheduler/scheduler.cpp

Add a missing check that we're doing a dynamic schedule before trying to steal work when idle.  There don't seem to be any consequences from the missing check but it is best to have it for clarity.
Issue: #6938

i#6938 sched migrate: Add missing check for work stealing

---

clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Adds two statistics reported by the scheduler to the schedule_stats report: work steals and rebalances.
Tests that something is printed out, but checks of the actual values are left to existing scheduler tests.
Issue: #6938

i#6938 sched migrate: Add steals + rebalances to schedule stats

---

clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tests/schedule_stats_test.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

While the schedule_stats tool already reports the migration count from the scheduler, that is only non-zero for a dynamic schedule, resulting in 0 for core-sharded-on-disk traces.  We add "observed migrations" where schedule_stats looks for migrations on its own.  This requires a global lock on each context switch, but experimental results show that this does not seem to cause noticeable overhead.
Adds some testing.
Issue: #6938

i#6938 sched migrate: Add observed migrations to schedule stats

---

clients/drcachesim/tools/schedule_stats.cpp

Fixes an assert on the new observed_migrations stat added to schedule_stats in PR #7057.  These observed_migrations are counted on the destination core, while the scheduler reports migrations away from a source core: so they can differ, causing the assert to fire.  Fixed by moving it to only check the aggregated stats across all cores.
Tested on the internal trace where the assert fired before.
Issue: #6938

i#6938 migrate: Fix observed_migrations assert in schedule_stats

---

clients/drcachesim/tools/schedule_stats.cpp

schedule_stats_t::get_total_counts() was not including scheduler-provided stats, as it was doing its own simple aggregation instead of calling aggregate_results().  We fix that here.  That then triggers the newly added assert from PR #7057 which checks for the scheduler-provided value being exactly equal meaning there is no data available.  It fires on the schedule_stats_test, which uses a mock stream which returns -1 for such a stat, so we end up with a negative value.  We update the assert for that condition.
Issue: #6938

i#6938 migrate: Include sched stats in query and fix related assert

---

clients/drcachesim/tests/view_test.cpp
core/ir/isa_regdeps/disassemble.c
suite/tests/api/ir_regdeps.c

In REGDEPS public traces the encodings of instructions printed with the
`view` tool (which uses our disassembler) are divided in 4 byte words,
2 words on the first line and an additional 2 on the second line (if necessary).
Instructions that only have 1 word encodings (e.g., a branch) have their
categories printed right after the encodings of their first word and don't
align with the categories of 2 or more word instructions.
For single word instructions we now add spacing equivalent to a second word.
So, we now have:
```
102268       78352:     1271326 ifetch       3 byte(s) @ 0x00005605ec276c4a 00040110 00000206 math [8byte]       %rv0
102269       78353:     1271326 ifetch       2 byte(s) @ 0x00005605ec276c4d 00002200          branch  (taken)
```
Instead of:
```
102268       78352: …
```

i#6662: view tool spacing fix

---

api/docs/download.dox
api/docs/new_release.dox
api/docs/release.dox

The 11.0.0 release is now official so we update the download page for the new version and prepare the changelist for subsequent releases.

Update changelist and download for 11.0 release

---

api/docs/release.dox

Restores the word "changes:" which was accidentally removed in PR #7066.

Fix typo in changelist

---

core/globals.h
core/ir/instr_create_shared_api.h
core/lib/dr_api.h
core/lib/globals_shared.h
core/unix/os_exports.h
core/win32/os_exports.h

Adds clang-tidy annotations to the deliberately hierarchical headers in core DR where one header is meant to include a set of other headers.  This avoids clang-tidy Include What You Use complaints which can cause users to include individual sub-headers, which sometimes have ordering constraints if the top-level header is not included first (or solely).
Issue: #4103

i#4103 clang-tidy: Mark hierarchical headers for IWYU

---

core/lib/instrument.c
core/unix/coredump.c

Clean up include files in core/lib/instrument.c and core/unix/coredump.c.
Issue: #7046

i#7046: clang-tidy: Clean up headers to include what is used by coredump.c and instrument.c.

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

This first step toward separating key scheduler code into separate subclasses by mode of operation adds the pImpl idiom to the scheduler: the scheduler_t implementation is moved to a private class scheduler_impl_t, to let us (in a future step) create the appropriate subclass without changing callers who construct a scheduler_t.  This also helps to split up and modularize the enormous scheduler class.
A future step will move the scheduler_impl_t code into a new file scheduler_impl.cpp.  That was separated out to make the diff easier to read here.
The bulk of the changes involve:
+ The name change scheduler_tmpl_t to scheduler_impl_tmpl_t.
+ Having to qualify enum types as we do not have C++20's using enum.
+ Having to refer to types in another class now that the impl class is separate from …

i#6831 sched refactor, step 1: Add pImpl idiom

---

core/vmareas.c

Downgrades an assert in vmareas.c:is_on_stack() on a bad stack pointer to a warning, as this is just a surprising application state and nothing DR can't handle.
Fixes #6624

i#6624: Warn instead of ASSERT for unexpected SP value.

---

clients/drcachesim/scheduler/scheduler_dynamic.cpp
clients/drcachesim/scheduler/scheduler_fixed.cpp
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_replay.cpp

Adds used include files to the 3 scheduler subclasses that were omitted when new overrides were added in step 3.
Issue: #6831

i#6831 sched refactor, step 5: Add missing includes

---

clients/drcachesim/scheduler/scheduler.cpp
clients/drcachesim/scheduler/scheduler_dynamic.cpp
clients/drcachesim/scheduler/scheduler_fixed.cpp
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/scheduler/scheduler_replay.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Splits set_initial_schedule() into separate overrides in the 3 scheduler subclasses, sharing the initial content reading in init() prior to calling set_initial_schedule().
Splits set_output_active(): it is only valid in dynamic.
Moves rebalance_queues() and two rebalance vars to dynamic.
Moves read_recorded_schedule() and
read_and_instantiate_traced_schedule() to replay.
Adds more using statements to remove the need for "this->" prefixes on frequent base class member field references.
Issue: #6831

i#6831 sched refactor, step 6: Split set_initial_schedule()

---

clients/drcachesim/tracer/raw2trace.h

raw2trace_t::handle_rseq_abort_marker() uses different names of the last parameter. It's interrupted in raw2trace.h
but it is rseq_aborted in raw2trace.cpp.
Change the name from interrupted to rseq_aborted to be consistent with raw2trace.cpp.
The inconsistency was introduced by PR #7058.
Fixes: https://github.com/DynamoRIO/dynamorio/issues/7084

i#7084: Change handle_rseq_abort_marker parameter name interrupted to rseq_aborted.

---

clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h

Adds a check for the caller holding the previous input's lock before acquiring it to retrieve the previous workload.  The existing code acquired the new lock without checking caller_holds_cur_input_lock, which could hang (it happened not to because the only caller who sets caller_holds_cur_input_lock to true set the current input to invalid and set_cur_input() returns prior to this point).
Issue: #7044

i#7044 sched deadlock: Fix theoretical deadlock

---

clients/drcachesim/scheduler/scheduler_dynamic.cpp
clients/drcachesim/scheduler/scheduler_fixed.cpp
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/scheduler/scheduler_replay.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds swap_in_input() and swap_out_input() subclass hooks inside set_cur_input().  This allows moving ready queue functions into the dynamic subclass, and will be used there for future live workload tracking for #7067.
Moves add_to_ready_queue(), add_to_ready_queue_hold_locks(), add_to_unscheduled_queue(), and print_queue_stats() into the dynamic subclass.
Issue: #7067, #6831

i#6831 sched refactor: Add set_cur_input() hooks

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_dynamic.cpp
clients/drcachesim/scheduler/scheduler_fixed.cpp
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/scheduler/scheduler_replay.cpp
clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_maxcores.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h
suite/tests/CMakeLists.txt

Adds a new input_workload_t field: output_limit.  This is a peak simultaneously-live output stream maximum for the inputs of that workload.
To implement, atomics are used, with a new workload_info_t array tracking per-workload fields.  A new stat
memtrace_stream_t::SCHED_STAT_HIT_OUTPUT_LIMIT is added.  An initially-idle output attempts to steal immediately, as the initial round-robin layout does not take into account output limits.
Fixes #7067

i#7067: Add per-workload simultaneous output limits

---

core/ir/x86/decode_table.c
core/ir/x86/instr_create_api.h
core/ir/x86/opcode_api.h
suite/tests/api/ir_x86_0args.h

Alder Lake/Sapphire Rapids introduced the SERIALIZE extension which adds a single new SERIALIZE instruction. Support that.

Add decode/encode support for the Intel SERIALIZE extension.

---

api/docs/release.dox
core/ir/aarch64/codec.c
core/ir/aarch64/encode.c
core/ir/opnd_api.h
core/ir/opnd_shared.c

FPMR is present only when FEAT_FPMR is implemented. It is then part of the user-mode execution state and controls the behaviour of instructions that operate on 8-bit floating-point values.
DR_REG_FPMR is added at the end of the DR_REG_ enum to improve ABI compatibility.
Change-Id: Ife0bc0239d029ca3f83fe7d6b5ecbbaceebfac5f

i#2626 AArch64: Add register FPMR.

---

core/unix/coredump.c
suite/tests/client-interface/memory_dump_test.templatex

Add loadable segment program headers to memory dump file. Set the entry point address in the ELF file header based on the PC value.
Update the unit test to check loadable segment program header.
Here's the output of readelf -l using the unit test output from a X86 machine:
$ readelf -l logs/simple_app.3281609.00000000.elf
Elf file type is CORE (Core file)
Entry point 0x7fcd05936320
There are 47 program headers, starting at offset 64
Program Headers:
Type           Offset             VirtAddr           PhysAddr
FileSiz            MemSiz              Flags  Align
NOTE           0x0000000000000a88 0x0000000000000000 0x0000000000000000
0x0000000000000378 0x0000000000000378         0x2
LOAD           0x0000000000000e00 0x00007fcac1000000 0x00007fcac1000000
0x0000000000040000 0x0000000000040000 …

i#7046: Add loadable segment program headers to memory dump file.

---

core/ir/x86/decode_table.c
core/ir/x86/disassemble.c
core/ir/x86/instr_create_api.h
core/ir/x86/opcode_api.h
suite/tests/api/ir_x86_2args_mm.h

Add the ENQCMD/ENQCMDS instructions. Because they are patterned identically to MOVDIR64B the changes are very straightforward. MOD_EXT entries are added because the upcoming USER_MSR extension will use the modrm.mod == 3 slots for these opcodes.

Add decode/encode support for Intel's ENQCMD extension.

---

core/ir/x86/decode_table.c
core/ir/x86/instr_create_api.h
core/ir/x86/opcode_api.h
suite/tests/api/ir_x86_1args.h

Add the RDPID instruction, which is intended to be a faster replacement for RDTSCP when the caller only cares about the processor ID and does not need the timestamp.
Also mark RDSEED as catOther since we have to move its entry in the decoder table anyways.

Add decode/encode support for Intel's RDPID extension.

---

suite/tests/CMakeLists.txt
suite/tests/api/ir_riscv64.c
suite/tests/api/ir_riscv64.expect
suite/tests/api/ir_riscv64.h
suite/tests/api/ir_riscv64_common.c
suite/tests/api/ir_rv64_addr.c
suite/tests/api/ir_rv64_addr.templatex

Disassemble result of instructions like jal and auipc on riscv64 is PC-sensitve, i.e. depends on the current PC value. We used to omit the check since address of the buffer that we encode instructions to is unknown before running the test.
This commit splits IR tests of these instructions out and enables regex match to handle the varying addresses. It's important to keep it small and standalone to workaround the inefficient regex implementation of CMake.
Issue: #3544

i#3544: RV64: Split PC-sensitive IR tests into another test

---

core/ir/x86/decode_table.c

The x86 OP_clflush opcode was marked as DR_INSTR_CATEGORY_SIMD by PR operations.  We change it to OTHER which matches CLFLUSHOPT which was just added.
Issue: #6238

i#6238 op cat: Change clflush opcode category to OTHER

---

suite/tests/api/dis-armA32.expect
suite/tests/api/dis-armT32.expect

The decoder was fixed by #2967 but the test was not updated.
Issue: #3699

i#3699: Correct encoding of vadd.f32 in api.disA32, api.disT32.

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tracer/instru.cpp

Adds handling to drmemtrace for the x86 CLFLUSHOPT opcode to treat it just like CLFLUSH; the two are similar enough for most uses.
Augments the existing CLFLUSH invariant_checker test as a sanity test of the new opcode handling.
Issue: #7111

i#7111 cache opcodes: Add CLFLUSHOPT handling to drmemtrace

---

core/unix/loader.c
core/unix/module_elf.c

Despite "rela" relocations having an explicit addend value and it being set to non-0 in a new Debian glibc, the addend is assumed to *not* be added to the symbol value when relocating on x86_64 and aarch64 (it does seem to be added on RISCV).
This is not obvious and not well documented; we have to just behave like existing loaders behave from experimentation/examination. (Yet another reason to possibly invert the private loader and let the private copy of ld.so do all the loading and relocating: #5437).
Tested on a machine where nearly every client test in our suite was crashing after a glibc update: now they pass.  Unfortunately it's not simple to make automated tests for this: we don't have an existing framework for relocation testing and it would take non-trivial effort to construct …

i#7120: Do not add addend for rela jump slot relocation

---

make/DynamoRIOConfig.cmake.in

Fixes a build warning due to mis-matching arguments in cmake if() and endif().
Issue: #2154

i#2154 android64: Fix a build warning in cmake config

---

core/ir/x86/decode_table.c
core/ir/x86/instr_create_api.h
core/ir/x86/opcode_api.h
suite/tests/api/ir_x86_3args_avx512_evex_mask.h
suite/tests/api/ir_x86_4args_avx512_evex_mask_A.h
suite/tests/api/ir_x86_4args_avx512_evex_mask_C.h
suite/tests/api/ir_x86_5args_avx512_evex_mask.h

This adds 16 new VBMI2 opcodes:
- vpcompressb
- vpcompressw
- vpexpandb
- vpexpandw
- vpshldw
- vpshldd
- vpshldq
- vpshldvw
- vpshldvd
- vpshldvq
- vpshrdw
- vpshrdd
- vpshrdq
- vpshrdvw
- vpshrdvd
- vpshrdvq
And one VBMI opcode that was missing.
- vpmultishiftqb
The changes are generally what would be expected. The only quirk worth mentioning is that vpshrdvw's decoder table entry does not take reqp (unlike every other opcode added) because the path to get there goes through a PREFIX_EXT to split off some AVX512_BF16 instructions.

Add support for AVX-512 VBMI2.

---

clients/drcachesim/tracer/raw2trace_directory.cpp

In raw2trace_directory.cpp, `std::replace` requires `<algorithm>`.

Fix failing Windows build (`std::replace` requires `<algorithm>`)

---

core/unix/signal.c
core/unix/signal_private.h

The definition did not agree with the Linux kernel's definition.
There is a retcode field in sigframe, but not in rt_sigframe.
This change made the previously failing common.segfault test pass
in a Debian 10 container running under a 64-bit 5.4.47 kernel
on Cortex-A72 hardware.
Issue: #3699

i#3699: Remove retcode from 32-bit ARM rt_sigframe.

---

ext/drmgr/drmgr.c

In `drmgr.c`, fix potential index out of bounds if users passed in an invalid index as the checks for a too-high limit have a fencepost error.

Fix too-loose drmgr TLS array limit checks

---

suite/tests/linux/clone.c

Add previously missing asm for 32-bit ARM clone3 system call.
Issue: #3699

i#3699: Add asm wrapper for 32-bit ARM clone3 in test.

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/download.dox

Update the version number to 11.1 for a bugfix release primarily for the #7120 bug fix.
Issue: #7120

Version 11.1

---

clients/drcachesim/tests/burst_syscall_inject.cpp

This is needed on Debian 10 and seems harmless on newer OS versions.

Use syscall instead of C library's gettid in drcachesim test.

---

suite/tests/api/it_arm.c

Otherwise "memory leak detected" in api.it test,
since dr_standalone_exit was added by 76def0818.
Issue: #3699

i#3699: Call instrlist_clear_and_destroy in it_arm.c.

---

api/docs/code_reviews.dox

Updates some old material in the section "Responding to Review Comments and Submitting Code Updates" of our docs which talked about later commit messages as though they became part of the final merge commit message, which is no longer true since we now use the pull request description.

Update review process docs for final commit message

---

api/docs/release.dox
core/ir/instr_api.h
core/ir/instr_shared.c
suite/tests/api/ir_regdeps.c

Adds instr_get_operation_size() and instr_set_operation_size() public
APIs for DR_ISA_REGDEPS instructions, which are currently the only
instructions for which operation_size is defined.
We set operation_size of DR_ISA_REGDEPS instructions with no
operands to OPSZ_0 in the convertion to REGDEPS process,
so decoded and converted instructions look the same.
Previously a converted instruction might have had an operation_size
different than OPSZ_0 even with no register operands, that would
then be corrected during encoding and subsequent decoding.
This is mostly for convenience when testing.
We update a test to also invoke the instr_length() API on
DR_ISA_REGDEPS instructions.
Issue #6662

i#6662 public traces: add instr_t operation_size API

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
suite/tests/CMakeLists.txt

Public traces should never have TRACE_MARKER_TYPE_SIGNAL_NUMBER markers.
Temporarily, we also disallow TRACE_MARKER_TYPE_UNCOMPLETED_INSTRUCTION
markers until we can handle their partial encoding. Eventually we want to preserve them
(xref: #7155).
We add two invariants in invariant_checker to detect the presence of these
markers in REGDEPS traces and raise an invariant error if necessary.
Updated unit tests and end-to-end tests.
Issue #6662 #7155

i#6662 public traces: add signal and uncompleted instr invariants

---

core/arch/aarchxx/mangle.c

dd1589c0c modified dstack_offs in insert_push_all_registers without generating an instruction that modifies SP. So add a SUB SP, SP, #4 there, and a corresponding ADD SP, SP, #4 in insert_pop_all_registers.
This made the test client.cleancallparams pass.
Issue: #3699

i#3699 ARM: Keep stack aligned in insert_{push,pop}_all_registers.

---

clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_dynamic.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds handling for statically-injected kernel syscall traces in the scheduler.
Ensures that quantum and voluntary context switches are delayed until after the statically-injected syscall trace. This involved fixing the bookkeeping logic which is done on the next user-space instr now.
Note that the injected kernel syscall traces do not include any scheduling-related markers such as TRACE_MARKER_TYPE_SYSCALL_UNSCHEDULE and TRACE_MARKER_TYPE_TIMESTAMP.
For now we keep status quo on the scheduler behavior of showing the post-syscall markers before the switch.
Adds a unit test for static-injected kernel syscall trace handling by the scheduler for various scenarios involving syscall sequences shorter and longer than the quantum, for system calls that do and do not cause context switches, and …

i#7157 syscall sched: Handle static injected syscall traces in scheduler

---

api/docs/release.dox
clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tests/offline-trim.templatex

Add a new trace version TRACE_ENTRY_VERSION_RETIRED_INSTRUCTIONS_ONLY for #7050 and bump the TRACE_ENTRY_VERSION. 
Rename OFFLINE_FILE_VERSION_RETIRED_INSTRUCTIONS_ONLY to OFFLINE_FILE_VERSION_NO_OP since there were no changes in the raw trace by #7050.
#7058 incorrectly changed the OFFLINE_FILE_VERSION, it should have changed TRACE_ENTRY_VERSION instead.
Issue: #7050

i#7050: Bump the TRACE_ENTRY_VERSION and rename OFFLINE_FILE_VERSION_RETIRED_INSTRUCTIONS_ONLY.

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/download.dox

Update the version number to v11.2 to pull in #7156 .
Bumped the TRACE_ENTRY_VERSION so that analysis tools can determine compatibility with the new marker TRACE_MARKER_TYPE_UNCOMPLETED_INSTRUCTION.
Issue: #7050

Version 11.2

---

api/samples/div.c

Fixes the div sample client to ensure that the opnd reg passed to dr_insert_clean_call is pointer sized.
This showed up as a CLIENT_ASSERT crash on an AArch64 machine when the div client was run on suite/tests/bin/simple_app. On affected environments, it did show up on the sample.div test also.
Fixes: #7162

i#7162 div sample: Ensure clean call opnd reg is ptr sized

---

suite/tests/CMakeLists.txt
suite/tests/common/getretaddr.c
suite/tests/tools.c

Port assembly in common/getretaddr.c to riscv64 and implements tailcall_with_retaddr().
Issue: #3544

i#3544: RV64: Port test common.getretaddr to RV64

---

suite/tests/linux/signal_pre_syscall.c

The test is rewritten to repeatedly adjust the timer so that it hits the critical section more often. On AArch64 without DEBUG the new test ran in about 0.5 s instead of about 15 s and hit the critical section about 400 times instead of about 1 time. Also tested on X86_64.

Improve "sysnums" test (signal_pre_syscall.c).

---

clients/drcachesim/reader/v2p_reader.cpp
clients/drcachesim/reader/v2p_reader.h
clients/drcachesim/tests/v2p_example.textproto
clients/drcachesim/tests/v2p_reader_unit_test.cpp

The textproto format does not have fields with value == 0.
In some cases a trace can use virtual address 0x0, which
would result in a missing virtual_address field in `v2p.textproto`.
Previously we did not allow any missing fields in `v2p.textproto`,
so this case needs to be handled.
We do so relying on the fact that multiple missing virtual_address
fields would try to map 0x0 multiple times, resulting in an error.
We add the missing virtual_address case to the unit tests.
Issue #6662

i#6662 public traces: allow one missing virtual_address in v2p.textproto

---

core/heap.c
core/heap.h
core/loader_shared.c

Some C++ library functions require 8-byte alignment. This made the test drcacheoff.simple pass on 32-bit ARM.
Issue: #3699

i#3699: Change HEAP_ALIGNMENT to 8 on 32-bit ARM.

---

ext/drreg/drreg.c

On ARM/AArch64 not all MRS/MSR instructions operate on aflags, and on ARM the register source operand of MSR, if there is one, is the second operand.
This change made the test sample.memval_simple pass on 32-bit ARM. (But client.drreg-test does not yet pass.)
Issue: #3699

i#3699: Add more checks to is_aflags_{spill,restore} in drreg.c.

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/download.dox
api/docs/release.dox

Update the version number to 11.3.
Necessary for compatibility with the new public traces and their
v2p.textproto file (xref: #7136 #7174).
Issue #6662

Version 11.3

---

api/docs/release.dox

PR #7176 incorrectly failed to include the new pure-static support under the changes included in the 11.3 release.
Issue: #6662

Fix 11.3 changelist to properly include pure-static support

---

api/docs/download.dox

Due to building another 11.3.0 version of DynamoRIO, the download links
have the incorrect build number (no build number, instead of "1").
Here we fix the download links adding "-1" to "release_11.3.0".
Issue #6662

i#6662: Fix download links for version 11.3.0

---

core/ir/aarch64/codec.c
core/ir/aarch64/encode.c
core/ir/opnd_api.h
core/ir/opnd_shared.c
suite/tests/api/ir_aarch64_v80.c

Add decoding support for the following AArch64 registers:
CONTEXTIDR_EL1
ELR_EL1
SPSR_EL1
TPIDR_EL1
Also add some missing tests for other AArch64 registers.
Fixes: #7185

i#7185 Add missing AArch64 system register enums

---

clients/drcachesim/docs/drcachesim.dox.in

Fixes new line issues after bullet point lists for better readability.
Fixes citation, for which the title wasn't being displayed correctly.
Issue #6662

i#6662 public traces: fix doc formatting

---

CMakeLists.txt
make/utils.cmake

This patch changes the base address for `libdynamorio.so` on aarch64 Android so that `libdynamorio.so`'s ELF header does not get overwritten by the `vDSO`.
`drrun` now runs error-free with basic assembly programs, and runs with 'CURIOSITY'-ies for more complex programs like a compiled 'hello world' or `pwd`.
Issue: #2154

i#2154 android64: Fix base address issue to get drrun working

---

suite/tests/tools.c

Current versions of Android make the FILE struct opaque so we can't access its members to get the file descriptor for stderr. Instead we can use STDERR_FILENO from unistd.h.
Issue: #1874, #2154

i#2154 Android64: Fix write syscall in nolibc_print()

---

.github/workflows/ci-docs.yml
.github/workflows/ci-package.yml
CMakeLists.txt
api/docs/release.dox
core/arch/aarchxx/mangle.c
core/arch/arm/arm.asm
core/lib/mcxtx_api.h

ef4482e13 caused a few additional failures. In particular, the child of a clone3 system call started with the register values shifted: R2 got the value that should be in R1 and so on. That caused the test linux.clone to fail.
It turns out that some callers of insert_{push,pop}_all_registers expect that an unpadded priv_mcontext_t will be pushed/popped. Moving the 4-byte padding to above the struct instead of below it makes some tests pass but breaks others. So we add some padding in the middle of priv_mcontext_t, changing its size from 324 to 328. It will probably run slightly faster with the struct (and particularly the field "simd") 8-byte aligned.
Update insert_{push,pop}_all_registers and arm.asm for the new struct layout, with some additional changes to arm.asm:
+ Delete irrelevant …

i#3699 ARM: Add padding to priv_mcontext_t for 8-byte alignment.

---

suite/tests/client-interface/drx-scattergather-aarch64.cpp

Fixes error:
```
drx-scattergather-aarch64.cpp:835:21: error: enumeration value 'DOUBLE' not handled in switch [-Werror,-Wswitch]
835 |             switch (value_size) {
|                     ^~~~~~~~~~
```
seen when building the test for Android.
Issue: #1874, #2154

i#2154 Android64: Fix drx-scattergather-aarch64.cpp build

---

clients/drcachesim/scheduler/scheduler.h

The drmemtrace scheduler get_shard_index() docs incorrectly stated it returns the tid for SCHEDULER_USE_INPUT_ORDINALS in the combined-stream serial analysis mode, when in fact it returns the ordinal of that tid in observation order.

Clarifies the drmemtrace scheduler get_shard_index() docs

---

CMakeLists.txt
make/DynamoRIOConfig.cmake.in
make/utils.cmake

Change the build scripts to use lld's `--image-base=` argument to set the preferred base address for libraries instead of `-Ttext=`.
`-Ttext=` sets the address for the `.text` section but `lld`'s section layout does not put the `.text` section first so not all sections are moved to the preferred base.
Changing it to use `--image-base=` instead means we can remove the Android special-casing and use the same preferred base address that we do for Linux.
Fixes: #7195

i#7195 Fix Android library base address

---

clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/offline-skip_instrs_opcode_mix.templatex
clients/drcachesim/tests/opcode_mix_test.cpp
clients/drcachesim/tools/common/decode_cache.h
clients/drcachesim/tools/opcode_mix.cpp
clients/drcachesim/tools/opcode_mix.h
suite/tests/CMakeLists.txt

Fixes the opcode_mix tool to get the filetype from the memtrace_stream_t interface instead of the TRACE_MARKER_TYPE_FILETYPE marker memref which may not be seen if -skip_instrs is applied by the user.
Modifies opcode_mix_t to use initialize_stream instead of initialize, to get the serial stream.
Adds a new unit test that runs the opcode_mix tool with -skip_instrs, which would fail because of an unseen filetype prior to this fix.
Augments decode_cache_t::init() documentation to suggest a reliable way to obtain the filetype.
Issue: #7224, #7113

i#7224 skipped header: Get filetype from stream in opcode_mix

---

clients/drcachesim/tracer/raw2trace_shared.cpp
clients/drcachesim/tracer/raw2trace_shared.h
core/drlibc/drlibc_module_elf.c
core/ir/aarch64/codec.c
core/ir/instrlist.c
core/ir/x86/encode.c
ext/drcovlib/modules.c

Adding to NULL is undefined behavior.
This fixes reports we detected on our internal tests
of tools depending on DynamoRIO.
Examples of reports are in #7229.
Many others are likely still undiscovered.
Issue: #7229

i#7229: Fix --fsanitize=pointer-overflow reports

---

suite/tests/api/detach_signal.cpp
suite/tests/linux/signal-base.h
suite/tests/linux/sigplain-base.h
suite/tests/tools.c
suite/tests/tools.h

All 16 of the `linux.signalXXXX` and all 8 of the `linux.sigplainXXX` tests were failing on 64-bit Android.
These failures were due to a common `ASSERT` which checks to make sure that the signal mask that is manually created and set as the process' signal mask is the same as the actual signal mask that is in use by the process at the end of the test, i.e. the process is blocking all of the signals we asked it to block - no more and no less.
However, it seems that Android (at least 64-bit) automatically sets the 32nd/last bit of the signal mask. This means that the mask we create (which is missing this 32nd bit) is not the same as the mask that is returned at the end (with the 32nd bit), and so the test fails.
The same issue is also present in the `api.detach_signal` test and has been …

i#2154 Android64: Fix linux.signal and linux.sigplain tests

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/decode_cache_test.cpp
clients/drcachesim/tools/common/decode_cache.cpp
clients/drcachesim/tools/common/decode_cache.h
clients/drcachesim/tools/opcode_mix.cpp

Moves the check that compares the current build enviroment with the arch bit of the trace file to decode_cache_t::init.
Due to some complexities in how build_target_arch_type() is declared in trace_entry.h, it had to be wrapped by a new API in decode_cache_base_t. build_target_arch_type() is defined conditionally in trace_entry.h only if dr_defines.h has already defined certain symbols. It is hard to ensure that for all builds dr_defines.h is included before trace_entry.h, so we ensure it just for decode_cache.cpp which is packaged as a separate lib unit drmemtrace_decode_cache. This also means that the new API could not be in decode_cache_t which is a template class that has to be defined in the header.
Issue: #7113, #7236

i#7113 decode cache: Add build arch check

---

clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Drops scheduler_impl_t::INSTRS_PER_US from 2000, which assumed IPC=1, to 1000, for IPC=0.5, in order to match
scheduler_options_t.time_units_per_us which is also estimating time per instruction.  This will also result in more quickly advancing synthetic timestamps which is good as the microsecond granularity at full speed tends to have too many timestamps with identical values.
Updates the timestamp-change unit test to test the new value.
Adds a new unit test to ensure the two constants remain the same.
Issue: #7028

i#7028 synth timestamps: Unify instrs-per-us in drmemtrace scheduler

---

clients/drcachesim/common/options.cpp
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/tlb_simulator.cpp

Clarifies that the -{skip,sim,warmup}_refs options skip a count of trace records inside particular tools, rather than in the framework.
Clarifies that the -skip_{instrs,to_timestamp} options skip over top-level markers, but their values are available from the stream API.
Adds i#7230 TODO comments on fixing the -{sim,warmup}_refs options in the simulators to count marker records (or possibly to keep as is and update the docs).
Issue: #7224, #7230

i#7224 skip docs: Clarify drmemtrace skip option docs

---

.github/workflows/ci-aarchxx-cross.yml
.github/workflows/ci-aarchxx.yml

CMake is updated to 3.26.4, which enables automatic retry of tests on failure.
Fixes: #2417

i#2417 AArch64: Update CMake in .github/workflows/ci-aarchxx*.

---

core/arch/aarch64/asm_offsetsx.h

Fixes a compile error for Android64 introduced by #7202 (commit 2f2614b92):
```
core/arch/aarch64/asm_offsetsx.h:85:1: error: offsetof of incomplete type 'struct tlsdesc_t'
85 | OFFSET(struct tlsdesc_t, arg, 8)
| ^      ~~~~~~
```
`tlsdesc_t` is not defined on Android.
Issues: #2154, #7226

i#2154 Android64: Fix compile error

---

.github/workflows/ci-aarchxx.yml

These labels point to a set of Arm AWS instances which are scalable and will get better support over the long-term.
See: https://gitlab.arm.com/tooling/gha-runner-docs#runner-configurations
Issue: #1569

i#1569: Update Arm hosted GitHub Action Runner labels

---

clients/drcachesim/tests/offline-altbindir.templatex
clients/drcachesim/tests/offline-tlb_simulator_v2p.templatex
suite/tests/CMakeLists.txt

Fixes a bug where the new tlb_simulator_v2p test used the same directory as the existing altbindir test.  Both tests were then clobbering each other's files.  This is solved by using unique names.
Further improves the altbindir test by dynamically removing the trace/ directory, since the test is supposed to test post-processing but wasn't if run more than once in the same build directory.
Fixes #7245

i#7245: Fix test race by using unique dirs

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/analyzer_multi.h
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/launcher.cpp
clients/drcachesim/tests/multi_indir.templatex
suite/tests/CMakeLists.txt

Adds a new option -multi_indir to the drmemtrace framework.  This allows combining multiple workload traces in core-sharded mode, interleaving threads from all the workloads together.
Updates the documentation.
Adds a test that runs 3 copies of the checked-in threadsig trace.
Manually tested error checking:
```
$ bin64/drrun -t drmemtrace -tool schedule_stats -cores 3 -multi_indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir:../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir:../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir -only_shards 1
ERROR: failed to initialize analyzer: Input limits are not currently supported with -multi_indir
```
Issue: #7091

i#7091: Add -multi_indir to drmemtrace

---

core/unix/loader_android.c
core/unix/os.c
core/unix/os_private.h

Since the original 32-bit Android port was done bionic was changed [1] to pass argc, argv, and envp to library _init() functions so when targeting newer versions of Android (>= 8.0, API level 26) we don't need the old workaround.
This fixes several tests which were failing with the error:
```
Internal Error: DynamoRIO debug check failure: failed to find envp
@dynamorio/core/unix/os.c:801 envp != NULL
```
[1] https://android.googlesource.com/platform/bionic/+/554374693408cd7c74d0cae596fca7349661edea
Issue: #2154

i#2154 Android64: Conditionally compile get_kernel_args()

---

suite/runsuite_wrapper.pl
suite/tests/CMakeLists.txt

Disables running longer sets of tests on merges to master: both TEST_LONG for the general test suite and
SKIP_LESS_DIFFERENTIATED_TESTS_FOR_PULL_REQUEST being disabled for 32-bit Windows.
We ideally would run our full set of tests on merges to the master branch, but we have not had the resources to keep that suite green. And now that we are turning off the "Require branches to be up to date before merging" requirement we really want pre and post merge suites to be identical for ease of monitoring concurrent merge problems.
Issue: #4800, #5873

i#4800,i#5873: Disable longer test suite on merge

---

.github/workflows/ci-aarchxx-cross.yml
.github/workflows/ci-aarchxx.yml
.github/workflows/ci-clang-format.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-osx.yml
.github/workflows/ci-package.yml
.github/workflows/ci-riscv64.yml
.github/workflows/ci-windows.yml
.github/workflows/ci-x86.yml

Updates the actions/checkout to v4 in all our workflows in an attempt to avoid the submodule failures we've seen recently.
Issue: #7253

i#7253 submodule fail: Try actions/checkout@v4

---

core/unix/coredump.c
suite/tests/client-interface/memory_dump_test.templatex

Add NT_ARM_TLS note to store  tpidr_el0 for Aarch64.
tpidr_el0 is not covered by the existing notes NT_PRSTATUS and NT_FPREGSET. 
Modified memory_dump_test.templatex to check NT_ARM_TLS for Aarch64.
Issue: #7046

i#7046 memory dump: Add NT_ARM_TLS note to store tpidr_el0 for Aarch64.

---

.gitmodules

Switches to a local fork of elfutils in our Github project to avoid pull failures from sourceware.org.
Issue: #7253

i#7253 elfutils pull: Use local elfutils fork

---

api/docs/building.dox
api/docs/new_release.dox
make/package.cmake

`ci-package` is failing in generating Android 32 bit package because
`toolchain-android.cmake` was renamed as `toolchain-android-gcc.cmake`.
This is blocking all package builds.
We also fix the name in the doc that explains how to cross-compile for
ARM Android.
Tested:
https://github.com/DynamoRIO/dynamorio/actions/runs/13212140385/job/36886983427
Fixes #7262

i#7262: fix toolchain-android.cmake name

---

clients/drcachesim/tests/allasm_aarch64_flush.asm
clients/drcachesim/tests/allasm_aarch64_prefetch.asm
clients/drcachesim/tests/allasm_scattergather_aarch64.asm
clients/drcachesim/tests/allasm_scattergather_x86.asm
clients/drcachesim/tests/builtin_prefetch.c
suite/tests/CMakeLists.txt
suite/tests/common/allasm_aarch64_cache.asm
suite/tests/common/allasm_arm.asm
suite/tests/common/allasm_thumb.asm
suite/tests/common/allasm_x86_64.asm

Adds removal of the drcachesim pipe before and after running each test, to avoid a stale pipe file causing a retry-on-failure to time out.  This should help prevent #3320 from turning the suite red from what should be a single failure passing on a retry.
Modifies the asm tests to print to stderr instead of stdout for proper ordering within runcmp.cmake (as well as to match the conventions of all other tests).
Tested by adding "-unsafe_crash_process" to the options and then:
```
$ ctest -V -R coherence
<...>
325:   <Application
325:   /usr/local/google/home/bruening/dr/git/build_x64_dbg_tests/suite/tests/bin/client.annotation-concurrency
325:   (465432).  DynamoRIO Cache Simulator Tracer internal crash at PC
325:   0x00007f46cc0614b4.  Please report this at http://dynamorio.org/issues. …
```

i#3320 pipe order: Remove pipe before and after tests

---

suite/tests/CMakeLists.txt

Switches from "cmake -E copy" to "cmake -E copy_if_different" for the Windows library copies used for API standalone tests.  We have seen sporadic fatal errors from drconfiglib.dll failing to copy, presumably because another rule already copied it.  It has proven difficult to figure out which rules are colliding, so we solve this by making it a non-fatal error.
Fixes #5888

i#5888: Avoid fatal error on lib copy collision

---

clients/drcachesim/docs/drcachesim.dox.in

Replaces the now-old news about drmemtrace format updates with a pointer to the new Public Google Workload Traces.
Issue #6662

i#6662 public traces: Add to drmemtrace news

---

make/cpp2asm_support.cmake

Works around a Mac M1 build hang on assembly configuration.
Tested on a local M1 machine where CMake configuration now finishes.
Issue: #6326

i#6326 M1 hang: Work around M1 build hang

---

core/unix/module_private.h

Solves a missing header issue that results in a build error on Mac M1 with the new asm offset files from PR #7202: module.h has to be included before module_private.h so we explicitly include the former in the latter.  Tested locally on M1 Mac.
Issue: #7226

i#7226 asm offsets: Add missing header

---

clients/drcachesim/tests/scheduler_unit_tests.cpp

Fixes the existing scheduler unit test that verifies kernel context switch template injection.
The res bool was unused, therefore a failure to match expectations was never reported. The expected timestamps inside the injected part of the trace should be the ones updated by the scheduler, not the original one in the trace template.
Issue: #7157

i#7157 dyn inject: Fix switch trace injection test

---

.github/workflows/ci-aarchxx-cross.yml
.github/workflows/ci-aarchxx.yml
.github/workflows/ci-clang-format.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-osx.yml
.github/workflows/ci-package.yml
.github/workflows/ci-riscv64.yml
.github/workflows/ci-windows.yml
.github/workflows/ci-x86.yml
.github/workflows/failure-notification.yml

Refactors the Github Action configs to move logic to send notification email on  master merge failure into a reusable workflow which is now used by all workflows instead of duplicating the logic 24 times.
Also, each workflow file now has a separate job for the new reusable workflow that is invoked after all other jobs (that actually run the test suite) are done. Status of all the test suite jobs are sent as part of the one failure notification email, if there's at least one failure; we skip filtering of status message by test suite status mostly for simplicity of logic that must be duplicated in each workflow file.
Note that the reusable workflow cannot be invoked as part of some step of a job; it has to be a separate job on its own.
The failure notification job requires a separate …

i#7281: Move failure notification config to reusable workflow

---

.github/workflows/failure-notification.yml

Includes the commit hash in the subject line of notification emails sent out on post-commit master merge CI failures.
Without this, failures in the same CI workflow at different commits are merged in the same subject thread. It is better to have them on different threads as the reasons for the failures could very well be different.
Issue: #5873

i#5873: Include hash in post-commit CI failure email subject

---

.github/workflows/ci-x86.yml

Previously, the build environment is bootstrapped with a static version of apk downloaded from Alpine mirror, whose URL isn't stable since the package is upgraded irregularly.
This commit switches to prebuilt minirootfs tarball, which is considered as release artifacts and has a stable URL, saving the burden of frequently synchronizing with Alpine upstream.
Fixes: #7284

i#7284: Bootstrap Alpine build environment from minirootfs in workflow

---

clients/drcachesim/tracer/output.cpp
core/arch/x86/mangle.c
core/unix/module_elf.c
core/unix/signal.c
core/vmareas.c
ext/drcovlib/modules.c

Adding to NULL is undefined behavior.
Examples of reports are in #7229.
Many others are likely still undiscovered.
Some reports are here https://github.com/DynamoRIO/dynamorio/issues/7229#issuecomment-2623360901
Issue: #7229

i#7229 part 2: Fix --fsanitize=pointer-overflow reports

---

suite/tests/client-interface/emulation_api_simple.dll.c

The emulation_api_simple test fails on Ubuntu 22 with "no encoding found":
```
before instrumentation:
TAG  0x000076f83bd3bcbd
+0    L3 @0x000076f5f74bbeb8  48 b8 7f ff ff ff ff mov    $0xffefffffffffff7f -> %rax
ff ef ff
+10   L3 @0x000076f5f74bbf40  48 21 05 ce fe 01 00 and    %rax <rel> 0x000076f83bd5bb9c[8byte] -> <rel> 0x000076f83bd5bb9c[8byte]
+17   L3 @0x000076f5f74ba5e8  48 81 c4 d8 00 00 00 add    $0x00000000000000d8 %rsp -> %rsp
+24   L3 @0x000076f5f74ba4c0  5b                   pop    %rsp (%rsp)[8byte] -> %rbx %rsp
+25   L3 @0x000076f5f74ba578  5d                   pop    %rsp (%rsp)[8byte] -> %rbp %rsp
+26   L3 @0x000076f5f74baaa0  41 5c                pop    %rsp (%rsp)[8byte] -> %r12 %rsp
+28   L3 @0x000076f5f750a620  41 5d                pop    %rsp (%rsp)[8byte] -> %r13 …
```

i#7270 ub22: Limit emulation test to reg dests too

---

core/unix/loader_linux.c

Increases the private TLS "tcb_size" from 0x970 to 0x1000, which fixes crashes in glibc code like this with an offset larger than 0x970 on a call to fprintf by a client on Ubuntu 22:
```
(gdb) bt
at ./libio/libioP.h:947
<fprintf from client here>
=> 0x00007ffdf70909ff <+15>:	mov    %fs:0x972,%al
_sigfault = {si_addr = 0x7ffdf78a4072
7ffdf78a2000-7ffdf78a4000 rw-p 00000000 00:00 0
7ffdf78a4000-7ffdf78a6000 ---p 00000000 00:00 0
```
This fixes the following tests which failed on Ubuntu 22:
+ client.destructor
+ client.file_io
+ code_api,satisfy_w_xor_x|client.file_io
+ sample.memtrace_simple_repstr
+ sample.memtrace_simple_repstr
+ sample.memtrace_simple
+ sample.memval_simple
+ sample.memval_simple_scattergather
+ sample.instrace_simple
+ sample.callstack
+ sample.memtrace_x86_text
+ …

i#7293 print crash: Increase privload tcb size to fix crashes

---

clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/tests/core_serial.templatex
clients/drcachesim/tests/schedule_stats_nopreempt.templatex
clients/drcachesim/tests/switch_insertion.templatex
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h
suite/tests/CMakeLists.txt

Adds the count of instances where the context switch sequence was injected to the schedule_stats tool output.
Modifies the switch_insertion test to use schedule_stats instead of basic_counts. This helps reveal a bug in context switch trace template dynamic injection logic that causes the injection to happen many more times than the context switch events.
This diff is split out from #7302 which fixes the above bug.
Issue: #7157

i#7157 dyn inject: Add switch injection count to schedule_stats

---

suite/tests/CMakeLists.txt
suite/tests/client-interface/memory_dump_test.templatex

The memory_dump_test fails on Ubuntu 22 because of failure to match expected output. 
The failure is due to the following lines in between "Hello, world!" and "ELF Header:"
readelf: Warning: Corrupt debuglink section:
readelf: Warning: Corrupt debuglink section:
readelf: Warning: unable to open file
'/home/runner/work/dynamorio/dynamorio/build_debug-internal-64/logs/'
referenced from .debug_sup section
readelf: Warning: .note.gnu.build-id data size is too small
The memory dump file does not have a debuglink section or .note.gnu.build-id. The change is to add a ".*" before "ELF Header:" to skip the warnings.
Add client.memory_dump_test and client.attach_memory_dump_test to ubuntu22 test suites.
Issue: #7270

i#7270 ub22: Handle readelf warnings in memory_dump_test output.

---

clients/drcachesim/simulator/cache_fifo.h
clients/drcachesim/simulator/cache_lru.h
clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/simulator/caching_device.h
clients/drcachesim/simulator/tlb_simulator.cpp

Small fixes in drcachesim which were not enough to justify a separate issue.
- Fixed inconsistent argument names in `cache_fifo_t` and `cache_lru_t` - header vs implementation.
- Improved error printing in `tlb_t` so you can know what actually failed.
- Sorted includes in caching_device.cpp.
- Fixed `tlb_simulator_t`'s destructor.

drcachesim Cleanup - Consistent argument Naming, TLB Error Printing and Destruction.

---

clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/simulator/tlb.cpp
clients/drcachesim/simulator/tlb.h
clients/drcachesim/simulator/tlb_simulator.cpp
clients/drcachesim/tests/cache_replacement_policy_unit_test.cpp

Added support for bit PLRU in the TLB. Added two deriving classes tlb_bit_plru_t and tlb_lfu_t that handle each option.
This is a temporary solution, and we should implement #7287 .
Fixes #7288

i#7288: Support bit PLRU in TLB

---

core/ir/x86/decode_table.c
suite/tests/api/dis-x64.expect
suite/tests/api/dis-x86.expect

XBEGIN/ABORT are accepted only if their modrm byte is f8. Filter out other previously modrm bytes by introducing the necessary decode table entries to filter on the mod and rm fields in addition to the reg field.
Fixes #7275

i#7275: decode/x86 decode xbegin/xabort more strictly.

---

api/docs/release.dox

Fixes \DR_VERSION which was left on the 9.0.0 minor compatibility change list.

Fix incorrect version # on 9.0 release notes

---

clients/drcachesim/scheduler/scheduler_dynamic.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Rebalancing was propagating an idle status from a runqueue to the caller, where it was treated as an error when it is in fact innocuous.
Adds a unit test that reproduces the error without the fix and passes with the fix.
Fixes https://github.com/DynamoRIO/dynamorio/issues/7318

i#7318: Do not propagate idle status on rebalance

---

core/ir/decode_shared.c
core/ir/x86/decode.c

Solves an isa mode assert by propagating the dcontext through read_instruction() for x86 decodes, and keeping GLOBAL_DCONTEXT when passed into dr_set_isa_mode().
The assert was triggered by a decode after DR global init but before the thread has its dcontext set up.  The passed-in dcontext turned from GLOBAL_DCONTEXT to NULL due to no propagation of dcontext through read_instruction().
Tested on an Ubuntu22 machine where client.tls and other tests hit the assert without the fix and pass with the fix.
Issue: #7270, #7320
Fixes #7320

i#7320: Fix isa mode assert

---

CMakeLists.txt

Unconditionally add libutil in CMakeLists.txt to ensure that DynamoRIO core and ext build correctly even when BUILD_TOOLS, BUILD_DRSTATS and BUILD_CLIENTS are all set to NO.
Fixes: #7313

i#7313: Unconditionally add libutil

---

core/CMake_readelf.cmake

A too-recent symbol with a long name had its name omitted from our error message because `readelf -s` truncated it:
```
CMake Error at core/CMake_readelf.cmake:165 (message):
*** Error:
build_package/build_release-64/bin64/drconfig has too-recent import(s):
GLOBAL DEFAULT  UND _[...]@GLIBC_2.34
```
Adding `--wide` produces the symbol name:
```
CMake Error at core/CMake_readelf.cmake:165 (message):
*** Error:
build_package/build_release-64/bin64/drconfig has too-recent import(s):
GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.34
GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.34
```
Issue: #5860

i#5860 glibc sym: Print whole symbol name in error message

---

suite/tests/CMakeLists.txt

Adds copy_target_to_device() for targets built with tobuild_ops() and tobuild() so these tests can be easily run on Android devices as well.
Issue: #2154, #1874

i#2154 Android64: Get more tests running on device

---

suite/runsuite_common_pre.cmake

Today the package platform name assumes x86 and is overridden for cross-compile jobs only in package.cmake. So a package build on an arm machine has an x86 name like 'DynamoRIO-x86_64-Linux-11.90.20152.tar.gz".
We fix that here to support building packages on arm machines directly. Tested on an aarch64 machine where this fix produces the name "DynamoRIO-AArch64-Linux-11.90.20152.tar.gz".
Fixes #7334

i#7334: Set package name for on-arm builds

---

tools/drdeploy.c

This fixes a check for a file that is expected to be present at a /debug/ path in release builds on macOS (despite files in /debug/ paths only being present in debug builds). `drrun` (without `-nocheck`) will error in release builds on macOS since `lib64/debug/libdrpreload.dylib` is not present and `is_debug` is wrongly set to false. This changes `is_debug` to be true for this file (as it should be true for all checked files living in the `lib64/debug/` path. The corresponding `lib64/release/` drpreload file is already present in the list and is already checked for release builds.
The check is here: https://github.com/DynamoRIO/dynamorio/blob/898d3fb4291706a823d19c73ff0904ea3ba4a649/tools/drdeploy.c#L576-L587
Issue: #5383

i#5383: fix 'debug' field in mac drdeploy checks

---

core/config.c
core/config.h
core/dynamo.c

When attaching to a running application, if the target application does not succeed in opening any config options files, the user does not know where the application has looked.
Store the config paths used and output them if no config files are found.
Fixes: #7338

i#7338: log which config paths have been read when no config found

---

clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

If an input is bound to every output, we now ignore those bindings, which eliminates complexities in initial output allocation where rebalancing is required to even things out (and that gets complicated by initially-blocked inputs) as well as removes overhead in the runqueue code during dynamic scheduling. Binding to every output is actually not uncommon as users have such bindings as a default value.
As part of detecting bind-to-all, invalid bindings are now detected.
Adds unit tests for the invalid bindings.
Updates the unbalanced rebalance test to bind to all but one as binding to all is no longer unbalanced.
Issue: #7318

i#7318 rebalance: Ignore bind-to-all

---

clients/drcachesim/scheduler/scheduler_impl.cpp

Fixes two typos in a comment and output string in scheduler_impl.cpp

Fix minor typos in scheduler comment + output

---

core/unix/loader_linux.c

Following PR #7294 which increases the privload tcb size estimate for x86-64, this increases the same for x86-32 to make it work on the Github Actions Ubuntu 22 runners.
Various tests crash with the following stacktrace without this fix:
```
(gdb) bt
#0  0xf779e5b3 in ?? ()
#1  0xf779a444 in _IO_link_in ()
#2  0xf7799206 in ?? ()
#3  0xf778c8fc in fdopen ()
#4  0xf7bb03c1 in log_stream_from_file (f=65440) at /home/runner/work/dynamorio/dynamorio/api/samples/utils.c:109 #5  0xf7baf70b in event_thread_init (drcontext=0x448efb40) at /home/runner/work/dynamorio/dynamorio/api/samples/instrace_simple.c:263 #6  0xf7b7dc07 in drmgr_thread_init_event (drcontext=0x448efb40) at /home/runner/work/dynamorio/dynamorio/ext/drmgr/drmgr.c:2639 #7  0xf7d898e1 in instrument_thread_init (dcontext=0x448efb40, …
```

i#7270 Ubuntu22: Increase x86-32 privload tcb size estimate

---

.github/workflows/ci-aarchxx-cross.yml
.github/workflows/ci-x86.yml
suite/runsuite.cmake
suite/tests/CMakeLists.txt

Removes the restriction on the test set run on Ubuntu22, and removes the UBUNTU_22 set itself.
Removes the x86-64 and x86-32 Ubuntu 20 Github Actions CI workflows, since we have others than run the same configuration on Ubuntu 22. Migrates the android-arm-cross-compile and a64-on-x86 to Ubuntu 22.
Removes the -ubuntu22 suffix from the workflows where that's the only variation left now.
This has been made possible after a bunch of work on #7270 by other contributors: @derekbruening, @edeiana, and @ivankyluk.
Issue: #7270

i#7270 Ubuntu22: Migrate x86-{32,64}, android-arm-cross, a64-on-x86

---

make/ldscript.cmake

We used to adjust current location pointer to our preferred base address at start of the linkscript, which creates a hole in the address space and allows the linker to put the ELF header and other sections before address of __executable_start symbol. This causes assertion failures when building with binutils 2.44,
Internal Error: DynamoRIO debug check failure:
/dynamorio/core/unix/os.c:9618 check_start == dynamo_dll_start
Since binutils ld.bfd always determines the base address by
. = SEGMENT_START("text-segment", 0x400000) + SIZEOF_HEADERS;
starting from at least 2003, it should be fine to drop the extra adjustment and only replace the default base with our preferred base.
Fixes: #7360

i#7360: Fix ldscript creation with binutils 2.44 and preferred base set

---

api/docs/code_style.dox

Updates the style guide for comments to avoid `FIXME` as its connotations are too negative and too easily mis-interpreted in code audits.

Update style guide to avoid FIXME

---

.github/workflows/ci-aarchxx.yml

Install gh on Arm Runners to support "gh api" for #7344. Add a step to check if format checks are disabled for Aarch64.
The command to install gh on Linux is listed here: https://github.com/cli/cli/blob/trunk/docs/install_linux.md.
Fixes: #7344

i#7344: Install gh on Arm Runners and check if format checks are disabled for ci-aarchxx.

---

CMakeLists.txt
suite/runsuite.cmake
suite/tests/CMakeLists.txt

#7361 disables vera checks when DISABLE_FORMAT_CHECKS is present in commit messages. 
It led to #7330 breaking subsequent tests due to failed style checks. 
Files should be added to make/style_checks/exclude to skip vera tests until formats are fixed. Revert the changes to skip vera checks when DISABLE_FORMAT_CHECKS is set.
Also change suite/runsuite.cmake so that tabs check allow tabs to be removed from existing files, i.e. files merged with DISABLE_FORMAT_CHECKS set.
Tests:
Make a change with a tab and ensure the check still catches it:
```
$ ./suite/runsuite_wrapper.pl automated_ci 64_only require_format 
Forking child for stdout tee
Parent tee-ing child stdout...
Running ctest --output-on-failure -VV -S "/usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake,automate …
```

i#7344: Do not skip vera tests when format checks are disabled.

---

core/unix/include/syscall_linux_riscv64.h
core/unix/include/syscall_linux_uapi.h
core/unix/module_elf.c

Our private loader invokes ifunc resolvers with no arguments. Although it's correct on x86-32 and x86-64, this doesn't match glibc loader's behaviour on AArchxx and riscv64.
On riscv64, resolvers will take the garbage in register. With a newer glibc version where a pointer to `__riscv_hwprobe()` was introduced to riscv64 ifunc ABI, the resolver may invoke the garbage as the hwprobe function, breaking clients depending on libc.
Let's mimic the bahaviour of glibc's dynamic loader to keep our private loader compatible with newer glibc on riscv64.
Issue: #3544, #7392

i#3544 RV64: Pass correct arguments to ifunc resolvers

---

clients/drcachesim/tools/schedule_stats.h
core/annotations.c

Fixes 3 clang-tidy warnings:
+ Removes default parameter value on virtual function schedule_stats_t::create_histogram()
+ Fixes inconsistent parameter name in is_annotation_tag()
+ Adds missing annotations_api.h header
Issue: #4103, #7355

i#4103 clang-tidy: Fix clang-tidy warnings

---

clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/caching_device.cpp
clients/drcachesim/tests/drcachesim_unit_tests.cpp

Fixes the problem of exclusive mode caches not properly updating state related to cache policies.
The problem was exposed by recent updates to the drcachesim cache policy logic that made policy updates much more explicit.  Several situations were identified by inspection in which exclusive caches did not update the policy counters properly.
This update fixes the problem, and adds two new tests to exercise the exclusive cache policy interactions.  Also included is a minor error check in get_cache_metric() to help users avoid wasting hours debugging phantom cache problems because they incorrectly expect cache levels to start at zero.
Fixes: #7363

i#7363: fix exclusive mode cache policy

---

api/docs/release.dox
clients/drcachesim/common/memref.h
clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/common/trace_entry.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/analysis_unit_tests.cpp
clients/drcachesim/tests/multi_indir.templatex
clients/drcachesim/tests/offline-allasm-record-syscall.templatex
clients/drcachesim/tests/offline-burst_syscall_inject.template
clients/drcachesim/tests/offline-phys.templatex
clients/drcachesim/tests/offline-skip.expect
clients/drcachesim/tests/offline-skip2.expect
clients/drcachesim/tests/offline-stdin.expect
clients/drcachesim/tests/offline-trim.templatex
clients/drcachesim/tests/offline-view.templatex
clients/drcachesim/tests/record_filter_modify_marker_value.templatex
clients/drcachesim/tests/scheduler_unit_tests.cpp
clients/drcachesim/tests/skip_unit_tests.cpp
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h

In dynamic drmemtrace schedules combining multiple workloads, there can be pid or tid collisions.  We solve that by having the scheduler set the workload ordinal in the top 32 bits of both the pid and tid. We ignore tids being 64-bit values on Mac; and we do not support unique values for 32-bit builds when trace_entry_t-based tools such as record_filter are used.
Documents this, along with missing docs for cpuid and timestamp modifications.
Updates the view tool and schedule stats to print tids in hex, to make it easier to distinguish the workload ordinal.  Updates test templates and docs for this change.
Adds scheduler unit tests.
Here is what this looks like:
```
drmemtrace -tool view -multi_indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir:../src/clients/drcachesim …
```

i#7401: Ensure unique pid,tid in drmemtrace schedules

---

.github/workflows/ci-aarchxx-cross.yml
core/unix/loader.c
suite/tests/CMakeLists.txt

Fixes an FPE on Ubuntu 22 for AArch32 under QEMU due to the __libc_early_init #5437 missing initialization of dl_tls_static_size by setting the offset to a value determined by experimentation.
Updates the arm-cross-compile job to Ubuntu 22.04.
Issue: #7270, #5437

i#7270,i#i5437: Add glibc 2.35 AArch32 dl_tls_static_size offs

---

.github/workflows/ci-clang-format.yml
.github/workflows/ci-docs.yml

Updates Github Actions CI config for ci-docs and ci-clang-format to use Ubuntu 22.04.
Issue: #7270

i#7270 ubuntu22: Update config for clang-format and docs

---

.github/workflows/ci-aarchxx-cross.yml
suite/runsuite_wrapper.pl

Adds `code_api|linux.signal_racesys` test to ignore list when executing
under QEMU on an x86 host with DynamoRIO's target set to AARCH64.
Upgrades from Ubuntu 20.04 to 22.04 for aarch64-cross-compile jobs.
Issue #7371

i#7371 Ubuntu 22: ignore signal_racesys

---

clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Removes the unused signal_context::xfer_aborted_rseq variable. Its previous use was removed by #5965.
xfer_aborted_rseq was used to relax the pre_signal_flow_continuity check that was intentionally removed (https://github.com/DynamoRIO/dynamorio/pull/5965/files#r1329469035).

Remove unused xfer_aborted_rseq var

---

core/ir/disassemble_shared.c
core/ir/instr_shared.c
suite/tests/api/ir_regdeps.c

Fixes a backward assert in instr_set_operation_size().
Fixes a crash if a regdeps instruction is disassembled with Intel, AT&T, or Arm styles selected.
Adds a test of both issues.
Also tested on drdisas temporarily disabling the "return 1" with a command that hits a SIGSEGV without this fix; with the fix it just doesn't print operands (the SYSLOG in this PR is only visible in full-DR runs):
```
$ clients/bin64/drdisas -syntax intel -mode regdeps 00001931 04020204 00000026
'regdeps' mode does not support 'intel' syntax
00001931 04020204 load store [4byte]
00000026
```
Issue: #6662

i#6662 public traces: Fix regdeps crash and assert

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Fixes PC discontinuity errors reported at kernel_event markers present immediately after a syscall or context switch trace.
Immediately following a system call or context switch sequence, the drmemtrace invariant_checker currently expects the kernel_event marker to hold the next PC of the last instruction inside the kernel trace. However, it should really expect the kernel_event marker to hold the actual pc after the kernel_event interruption (which could be a signal, rseq abort, exception, callback, etc). For traces without any kernel sequences, the interrupted pc would be the immediately prior instruction, but we need special handling for traces with kernel sequences where there is a whole syscall or context switch trace intervening. We extend the drmemtrace invariant_checker logic to …

i#6495 syscall inject: Fix PC disc at kernel_event after kernel trace

---

core/unix/include/linux_stat.h
core/unix/include/stat.h
ext/drsyscall/CMakeLists.txt
ext/drsyscall/linux_defines.h

Syscall statx was introduced in Linux Kernel 4.11. struct statx and statx_timestamp are not defined in older versions.
Define the structs in core/unix/include/stat.h and use the header file instead of linux/stat.h.
Issue: #7304

i#7303 drsyscall: Define statx and statx_timestamp for older Linux releases.

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp

Fixes the tracking for return addresses in drmemtrace invariant_checker for system call and context switch traces.
This fixes "Function marker retaddr should match prior call" in traces injected with kernel syscall sequences. This error weirdly manifested in the user-space part of the trace, but only after the trace was injected with kernel sequences. See details below.
At call instructions, the invariant_checker pushes the fallthrough pc to the retaddr stack, which is compared with the value of the later function return address marker. This entry is popped from the retaddr stack when we see a return instruction. At kernel_event markers, the invariant_checker inserts a dummy zero entry in the retaddr stack which is expected to be popped when the signal handler's return instruction is …

i#6495 syscall inject: Fix retaddr tracking inside kernel trace

---

clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds the OFFLINE_FILE_TYPE_KERNEL_SYSCALLS bit to the file type recorded in the TRACE_MARKER_TYPE_FILETYPE marker returned by scheduler_t::stream_t::next_record, and also to the file type returned by scheduler_t::stream_t::get_filetype()  for traces that have dynamic system call injection enabled.
Issue: #7157

i#7157 dyn inject: Adjust file type for syscall injected traces

---

.github/workflows/ci-package.yml
core/CMake_readelf.cmake

These are the oldest Linux releases we'd like to support with our binary packages:
+ Debian Bullseye, which is on glibc 2.31
+ RHEL 8, which is on glibc 2.28
+ Ubuntu 22.04, which is on glibc 2.35
Therefore, we want to support at least glibc 2.28.
Unfortunately, there is a compatibility break where glibc 2.34 contains `__libc_start_main@GLIBC_2.34` and non-trivial changes such that any binary built with 2.34+ will not run on a system with 2.33 or older. Since the oldest glibc Github Actions provides is Ubuntu 22.04's 2.35, we cannot easily build a pre-2.34 version.
For now we make 2.34 the minimum so our Github Actions docs and package builds succeed.
We leave open under #5860 the task of setting up a pre-2.34 build somewhere such as Travis so our binary releases will work on RHEL8 and …

i#5860: Increase min glibc to 2.34

---

suite/tests/CMakeLists.txt

Adds a missing dependence on drconfiglib being built before we try to copy it.  This should fix copy failures we see in the test suite.
Fixes #5888

i#5888 drconfiglib copy race: Add drconfiglib dep to drcopy

---

.github/ISSUE_TEMPLATE/bug_report.md

Augments the bug filing template to request symbolized callstacks, pointing at our documentation for loading symbols.

Request callstacks in bug template

---

core/CMakeLists.txt

Both dynamorio/core/CMakeLists.txt 
```
add_executable(unit_tests unit_tests.c
${CORE_SRCS} ${ARCH_SRCS} ${OS_SRCS} arch/x86_code_test.c)
```
and DrMemory drmrmory/CMakeLists.txt
```
if (TOOL_DR_MEMORY)
add_executable(unit_tests ${srcs})
```
use the name "unit_tests". It causes the following error on DrMemory:
```
CMake Error at CMakeLists.txt:1882 (add_executable):
add_executable cannot create target "unit_tests" because another target
with the same name already exists.  The existing target is an executable
created in source directory
"/usr/local/google/home/kyluk/DrMemory/drmemory/dynamorio/core".  See
documentation for policy CMP0002 for more details.
```
This PR changes the name unit_tests in dynamorio/core/CMakeLists.txt to core_unit_tests.
Issue: #7270

i#7270 ub22: Rename unit_tests in core/CMakeLists.txt to core_unit_tests.

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/reader/reader.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Since a core-shared-on-disk trace typically contains the footer record from when a source software thread trace exited, the reader and its skipping logic need to not abort when they see a footer.  They don't need to do anything on a footer as the EOF logic does not rely on such a record.  Here we fix both
reader_t::skip_instructions_with_timestamp() and
reader_t::process_input_entry() to not abort on a footer.
Adds a unit test, which fails without the fix.
Issue: #7442, #6685

i#7442 skip csod: Do not abort on a drmemtrace footer when skipping

---

api/docs/release.dox
clients/drcachesim/reader/reader.cpp
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

The drmemtrace scheduler's input_thread_info_t modifiers use a 'tids' field to allow applying the modifiers to a subset of a workload's inputs.  But for core-sharded-on-disk traces there are no thread ids. We solve that by adding a 'shards' field which can be used instead of 'tids' to specify inputs by ordinal (sorted lexicographically for a directory's files, just like for 'only_shards').
This change breaks binary compatibility, which unfortunately we cannot maintain as C++'s offsetof is not reliable on this  struct (due to some implementations of std::set not being a standard-layout class).  Adds a release note.
Issue: #7442, i#6685
Fixes #7442

i#7442 skip csod: Add scheduler input mod by shard

---

suite/tests/CMakeLists.txt

This test passes in our current QEMU CI environment, enable it to achieve better code coverage.
Issue: #1569

i#1569 AArch64: Enable client.flush in AArch64 QEMU CI

---

suite/tests/linux/infloop.c

Local runs of the dynamorio test suite on my workstation often leave behind stray linux.infloop processes.  While the current code has a loop count timeout mechanism to deal with this issue, it doesn't account for the extra loop delay of select() timeouts, which can lead to extremely long runtimes.
This PR causes the loop to exit after the first select() timeout.
Fixes #7449

i#7449: make sure linux/infloop.c exits eventually.

---

.github/workflows/ci-package.yml
api/docs/download.dox

Removes the release of an ARM-Android binary package since it does not have good support for recent Android versions, partly because of the lack of private library support.  The package can be re-added if that support is later added; or it can be replaced with an AArch64 version if that support becomes sufficient.  But right now it is misleading to release this package as it implies it should work when most tools will fail on recent Android versions.  We do not even have solid Continuous Integration testing for AArch32 Android at this time (#4639).
Issue: #3683, #4639, #2154, #7312

i#3683 android: Remove ARM-Android release package

---

core/ir/aarch64/instr.c
core/ir/aarch64/instr_create_api.h
suite/tests/api/ir_aarch64_v80.c

Adds missing handling for OP_eret on AArch64. Adds the INSTR_CREATE_eret macro, and marks OP_eret properly for instr_is_mbr, instr_is_return, and instr_branch_type.
Adds unit test for eret IR decoding.
eret is not expected to be seen by the user-space DynamoRIO. We've seen it in kernel system call traces collected on QEMU as the instruction that ends the syscall trace and interrupts within the syscall trace. We want such instructions to have the TRACE_MARKER_TYPE_BRANCH_TARGET so they must be marked as an indirect branch.
Issue: #6495, #7157

i#6495 syscall inject: Handle AArch64 OP_eret

---

core/ir/aarch64/instr.c

Unmarks eret as a return (it was marked as such in #7453), following similar treatment of sysexit/sysret in #7454.
Note that eret continues to be marked as an indirect branch, just not a return.
Issue: #6495

i#6495 syscall inject: Unmark eret as return

---

core/ir/aarch64/instr.c
core/ir/x86/instr.c

Marks the x86 OP_sysret and OP_sysexit properly for instr_is_mbr and instr_branch_type.
sysret and sysexit are not expected to be seen by the user-space DynamoRIO. We've seen sysret in kernel system call traces collected on QEMU as the instruction that ends the syscall trace and interrupts within the syscall trace. We want to annotate such instructions with the TRACE_MARKER_TYPE_BRANCH_TARGET marker, which requires that they must be marked as an indirect branch. This way we can show proper PC continuity in the kernel syscall injected traces.
We do not mark sysret and sysexit as return instructions because they are not returns in the usual sense that trace analysis tools would expect. E.g., they don't read the return address from the stack, and don't have matching call instrs (sysenter and …

i#6495 syscall inject: Handle x86 OP_sysret and OP_sysexit

---

clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Today, raw2trace tracks the last pc if it was a syscall, which is used to avoid consecutive duplicate system calls in the final trace.
Modifies raw2trace to instead track the fallthrough of the last pc if it was a syscall. This works just as well for the duplicate syscall check, and enables some upcoming logic which needs the fallthrough of the syscall instruction.
The existing test_duplicate_syscalls in raw2trace_unit_tests still passes.
Issue: #6495, #7157, #5934

i#6495 syscall inject: Track syscall-fallthrough pc in raw2trace

---

clients/drcachesim/tests/analysis_unit_tests.cpp
clients/drcachesim/tests/burst_syscall_inject.cpp
clients/drcachesim/tests/mock_reader.h
clients/drcachesim/tests/scheduler_unit_tests.cpp

Moves the classes and functions defined in mock_reader.h into their own dynamorio::drmemtrace::test_util namespace. Also refactors users of mock_reader.h to specify the "test_util::" prefix. Other test util code may be moved to the new namespace in separate cleanup PRs.
Some test files, such as raw2trace_unit_tests.cpp, define their own make_* functions, like make_memref, make_timestamp, etc. In #7451, we want to use mock_reader.h in raw2trace_unit_tests.cpp which fails to build because of the duplicate definitions.
Besides the clients/drcachesim/tests/mock_reader.h diff, others are just Find+Replace of the various mock_reader.h functions.
Issue: #6495, #7463

i#6495 syscall inject: Move mock_reader.h into separate namespace

---

clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace.h

Adds raw2trace_t::is_marker_type to avoid too much duplication of the not-so-trivial logic to check whether a given offline_entry_t is a marker of a specific type.

Add raw2trace_t::is_marker_type to avoid duplication

---

tools/drdeploy.c

In 3 of the 5 cases where strncpy is called the output string seemed not to be null-terminated.

In drdeploy.c, null-terminate strings after strncpy.

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Fixes the order in which split trace entries such as TRACE_MARKER_TYPE_SPLIT_VALUE are unread in unread_last_entry. TRACE_MARKER_TYPE_SPLIT_VALUE must be at the front of the pre_read deque so that it is returned _before_ the actual marker, in the same order it is read from the raw trace.
Adds a raw2trace_unit_test that fails with "SPLIT_VALUE marker is not adjacent to 2nd entry" due to the previously incorrect order of the split_value marker wrt the actual marker in the deque. The error was demonstrated using a large enough kernel_event marker value. This was not seen on a real trace probably because kernel_event marker values do not need the additional marker usually.
There is an additional bug where raw2trace does not fully take into account the fact that some markers may be preceded by …

i#7470: Fix order of unreading split trace entries

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h

Adds a drmemtrace invariant check that the chunk footer ordinals monotonically increase. This would have caught an error with an internal zipfile reader that sorts the subfiles combined with the only-4-digit zipfile suffix.
Also tested internally on a real world trace with out-of-order chunk reading and it does report an error:
```
Trace invariant failure in shard xxx Tnnn at ref # 14491816352 (347 instrs since timestamp 13389589136540837 in_kernel false): Chunks do not increase monotonically
```
Fixes #7474

i#7474 chunk order: Validate drmemtrace chunk order

---

clients/drcachesim/tools/invariant_checker.cpp

Adds the instruction ordinal to the drmemtrace invariant failure output, as it is much faster to skip by instruction than record for large traces. This information was desirable while working on #7474 which manifested on 100-billion-instruction-thread
traces.
Tested:
Temporarily changed the invariant on chunk counts to fail on the first chunk footer to test the failure output:
```
$ bin64/drrun -t drmemtrace -indir drmemtrace.simple_app.754774.9269.dir/ -tool invariant_checker
Trace invariant failure in T754774 at ref # 1419 at instruction # 1000 (1000 instrs since timestamp 13390545216200494): Chunk instruction counts are inconsistent
```
Issue: #7474

i#7474 chunk order: Include instruction ordinal in drmemtrace invariant failure

---

clients/drcachesim/tools/filter/record_filter.cpp
clients/drcachesim/tracer/raw2trace.cpp
clients/drcachesim/tracer/raw2trace_shared.h

The drmemtrace zip files split traces up into chunks, one per subfile. The names are of the form "chunk.0000", "chunk.0001", etc., with leading zeroes to ensure sorting keeps them in archive order, as some zip readers end up sorting.  But with more than 10K chunks (with the default 10M instructions per chunk, that's 100B instructions) an alphabetic sort no longer keeps them sorted.
We widen the suffix from 4 digits to 8 digits, and name that constant as TRACE_CHUNK_SUFFIX_WIDTH in raw2trace_sharded.h.
With no reader in this repository that hits a problem we do not attempt to add a test here.  This is being tested with an internal usage that does sort.
Adds a check to raw2trace that enough digits are present.
Tested by temporarily reducing TRACE_CHUNK_SUFFIX_WIDTH to 1:
```
$ rm -rf …
```

i#7474 chunk order: Widen drmemtrace zip chunk suffixes

---

ext/drsyscall/CMakeLists.txt
ext/drsyscall/drsyscall_record.h
ext/drsyscall/drsyscall_record_lib.c
ext/drsyscall/drsyscall_record_lib.h
ext/drsyscall/drsyscall_record_reader.c
ext/drsyscall/drsyscall_record_viewer.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/syscall-records-test.dll.c
suite/tests/linux/syscall-records.c
suite/tests/linux/syscall-records.templatex

Add a library, drsyscal_record_lib, to read and write syscall arguments and memory content.
Define a new structure, syscall_record_t, to store syscall arguments and memory content to a file.
Add a viewer, ext/drsyscall/drsyscall_record_viewer.c, to pretty print syscall_record_t records.
Add a new test, client.syscall-records-test, to verify  file I/O syscall arguments and memory content are stored
and retrieved correctly.
Issue: #7303

i#7303 drsyscall: Add a library to read and write syscall arguments and memory content.

---

clients/drcachesim/common/trace_entry.h
clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp

Adjusts the invariant expectation for injected traces of auto-restart syscalls that were interrupted by a signal.
Our raw2trace/scheduler injection logic sets the syscall-trace-end TRACE_MARKER_TYPE_BRANCH_TARGET marker to the syscall fallthrough pc, but in this case the syscall instruction is the actual next pc. Since the TRACE_MARKER_TYPE_KERNEL_EVENT marker already holds the correct next pc, it should take precedence. Notes this case in trace_entry.h.
Issue: #7157, #6495

i#7157, i#6495: Adjust invariant for interrupted auto-restart syscalls

---

clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Makes the schedule_stats_t method record_context_switch() virtual so it can be overridden in subclasses.
Addtiionally, since shard->prev_workload_id and shard->prev_tid are cleared when this function is called,
we pass in the preserved values so there's no confusion.
Tested in an internal use case.

Mark schedule_stats_t::record_context_switch() virtual

---

clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

For core-sharded-on-disk traces, idle and wait periods are represented by markers that the analyzer framework created from scheduler status codes. When these traces are passed back through the scheduler, it makes it easier for simulators directly using the scheduler interface to have them reverted back to the scheduler status codes.
Adds unit tests.
Issue: #6685

i#6685 core-sharded: Turn idle+wait markers back into status codes

---

api/samples/CMakeLists.txt
core/ir/aarch64/instr_create_api.h
core/lib/instrument.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/count-ctis.c
suite/tests/client-interface/count-ctis.dll.c

Implement mbr & cbr instrumentation for AARCH64, previously only available for X86. For cbr instrumentation, there are three types of conditional branches on AARCH64:
1. conditional branch if (non) zero: generate code to compare the register against zero to compute the direction
2. test bit and branch if (non) zero: generate code to extract the bit out of the register (using ubfm) and then compare the bit against zero to compute the direction
3. conditional branch according to NZCV: generate code to compute the direction using csinc instruction
Special care is implemented if the stolen register x28 is used as the operand, to avoid generating incorrect results.
For mbr instrumentation, the target address is placed in the register, which is later passed to the clean call from the user. …

i#2297: AARCH64: Implement mbr & cbr instrumentation

---

clients/drcachesim/common/memtrace_stream.h
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/tests/schedule_stats_test.cpp
clients/drcachesim/tools/schedule_stats.cpp
clients/drcachesim/tools/schedule_stats.h

Adapts various logic in schedule_stats to the presence of syscall traces.
Unit tests to verify more properties of the injected context switch trace are orthogonal to this PR, and will be added as part of the #7495 work.
Issue: #6495, #7157

i#7157 dyn inject: Adapt schedule_stats to syscall traces

---

clients/drcachesim/tools/invariant_checker.cpp

Adds back drmemtrace invariant checks that were unintentionally removed for MacOS by new conditional compilation directives in #7497. Only the new invariant_checker logic added by #7497 had to be guarded by LINUX whereas the existing adjacent UNIX block should've remained guarded by UNIX.
`tool.drcachesim.invariant_checker_test` is not enabled on MacOS because of #1997 so this regression was not detected in automated pre-submit testing.
https://github.com/DynamoRIO/dynamorio/blob/4ec1eda73ff3c01a36629ac0dec9163458e4efda/clients/drcachesim/CMakeLists.txt#L1025
Issue: #7496

i#7496: Revert unintentionally removed drmemtrace logic for MacOS

---

clients/drcachesim/scheduler/scheduler_impl.cpp

Since some Linux distribution shells set RLIMIT_NOFILE to 1024 by default and that's easily exceeded on some of our public trace sets, multiple users have hit an error opening a file that is puzzling to figure out. We add a suggestion to check this limit to the open file failure message.
Tested:
I synthetically added 50 threadsig files to a test dir:
```
$ ulimit -n 50
$ bin64/drrun -t drmemtrace -tool schedule_stats -cores 4 -indir drmemtrace.threadsig.3651695.9217.dir/
...
Failed to initialize scheduler: Failed to open drmemtrace.threadsig.3651695.9217.dir/trace/extra-46.trace.zip (was RLIMIT_NOFILE exceeded?)
```

Suggest checking RLMIT_NOFILE on open failure in scheduler

---

clients/drcachesim/scheduler/scheduler_impl.cpp

Adds a helpful error message to the invalid parameter error on an invalid region of interest in the scheduler, so the parameter error can be better understood.

Set error string for invalid scheduler region of interest

---

clients/drcachesim/docs/drcachesim.dox.in

Adds a new section: "Common Issues" that describes potential issues that
users might experience when using the Google Workload Traces.
As of now we have one issue that was hit for both public v1 and v2 traces:
"nofile" threshold can be set too low by the OS, which limits the number of
files a process (e.g., a DynamoRIO analyzer) can open. Google traces have
many files (over 2000 in some cases), so we recommend using `ulimit -n 8192`
to increase this threshold.
Issue #6662

i#6662 public traces: add common issues section to doc

---

core/lib/globals_api.h

The 64-bit SZFMT was incorrectly selecting a signed format string.

Fix sign error in SZFMT

---

api/docs/aarch64_far.dox

Fix doxygen tags in aarch64_far.dox which cause the following errors in ci-winodws:
```
FAILED: api/docs/html/index.html D:/a/dynamorio/dynamorio/build_debug-internal-32/api/docs/html/index.html 
C:\Windows\system32\cmd.exe /C "cd /D D:\a\dynamorio\dynamorio\build_debug-internal-32\api\docs && "C:\Program Files\CMake\bin\cmake.exe" -D DOXYGEN_EXECUTABLE=C:/Windows/doxygen.exe -Ddoxygen_ver=1.14.0 -Dversion_number=11.90.20265 "-Dmodule_string_long=\"DynamoRIO Extension Details\"" -Dmodule_string_short=\"Extension\" -Dhome_url=\"[http://www.dynamorio.org\](http://www.dynamorio.org/)" "-Dhome_title=\"DynamoRIO Home Page\"" -Dlogo_imgfile=\"drlogo.png\" -Dembeddable=OFF -Dproj_srcdir=D:/a/dynamorio/dynamorio -Dproj_bindir=D:/a/dynamorio/dynamorio/build_debug-internal-32 -P …
```

i#7514: Fix doxygen tags in aarch64_far.dox.

---

api/docs/release.dox
core/arch/interp.c
core/ir/decode.h
core/ir/instr.h
core/ir/opnd_api.h
core/ir/opnd_shared.c
core/ir/x86/instr.c

DR's lazy AVX-512 state preservation was only looking for zmm and opmask register usage: yet ymm16-31 are also AVX-512-only and my machine has ymm16 code before any zmm code runs. DR fails to preserve the state and the app state is corrupted.  Similarly, the gencode_filter test in #6490 has xmm16 in use, causing the weird printing there.
The check is augmented here to also look for xmm16+ or ymm16+.
Additionally, with full_decode, a check is added in build_bb_ilist, to fill a gap with full_decode but no client where AVX-512 would not be detected at all.
A new function reg_is_avx512() is added.
The PREFIX_EVEX is documented to clarify it is deliberately only set by decode_cti().
Tested:
My #7504 test's print() reliably printed the specifier ("%d") instead of the values when under DR …

i#7511 avx512: Identify {x,y}mm16+ as AVX-512 for lazy state preservation

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/tests/offline-windows-memdump.templatex
clients/drcachesim/tracer/instr_counter.cpp
clients/drcachesim/tracer/instr_counter.h
clients/drcachesim/tracer/tracer.cpp
clients/drcachesim/tracer/tracer.h
core/lib/dr_tools.h
core/lib/instrument.c
core/unix/coredump.c
core/unix/os_exports.h
core/utils.c
core/utils.h
core/win32/diagnost.c
core/win32/os.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/attach-memory-dump-syscall-test.dll.c
suite/tests/client-interface/memory_dump_test.dll.c

Add an option -memdump_on_window to the drmemtrace trace analysis tools framework.
The option triggers a memory dump when a trace window opens by -trace_after_instrs,  -trace_instr_intervals_file, or -retrace_every_instrs. If -retrace_every_instrs is also enabled, a memory dump will be captured for each individual tracing window. 
This feature only works on Linux X64. On Windows, raw2trace fails with "Non-module instructions found with no encoding information." if it is enabled. If this flag is used on Windows, the tracer will print an error message without capturing a memory dump.
Add a new parameter, embed_timestamp, to get_unique_logfile() to embed a timestamp in the file name. Adding a timestamp to the memory dump file name allows us to better correlate the memory dump file to the …

i#7508: Add an option -memdump_on_window to the drmemtrace trace analysis tools framework.

---

core/unix/os.c

We observed internal applications failing in some environments with -satisfy_w_xor_x with ENOMEM returned by the first two DUPFD attempts in fd_priv_dup().  fd_priv_dup() only retries once and that value is still too high in our failure cases.  Trying a 3rd time (/2 each time) succeeds. Here we generalize for a loop that retries, to make things more robust for cases where fds are limited.
Tested: Ran internal tests that were failing ~20% of the time and now there are zero failures.
Fixes #7516

i#7516: Try in a loop if fd_priv_dup() fails

---

suite/runsuite_wrapper.pl

Adds the sample.callstack 32-bit x86 failure to the ignore list as it is blocking progress.
Issue: #7394

i#7394 callstack failure: Add to ignore list

---

api/docs/release.dox
core/globals.h
core/lib/dr_tools.h
core/lib/instrument.c
core/unix/os.c
suite/tests/client-interface/strace.dll.c

Adds a new API routine dr_invoke_syscall_as_app() which invokes a system call as though the application made it, meaning it goes through DR's handling.  However, it does not trigger client syscall events (skipping them via an internal flag), which seems to be what use cases want (as otherwise each client or ext has to use flags to skip them).
(We may want a separate dr_invoke_syscall() that is not treated as an app syscall but just lets DR do its own internal tracking, but that is harder to implement and not needed for my use case, so it is left as future work for #199.)
Adds a test case that confirms DR acts on the syscall.
Issue: #199

i#199: Add dr_invoke_syscall_as_app()

---

clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds synthetic records for the new input's tid and pid before injecting the context switch sequence. This is required so that the injected switch sequence is identified by the new input's tid and pid also by the trace records themselves, like what the stream APIs do.
Makes relevant changes to the expectation in test_kernel_switch_sequences. The existing test_record_scheduler shows correct operation in the non-injection case.
Issue: #7157

i#7157 dyn inject: Add tid-pid before injected switch seq

---

clients/drcachesim/reader/reader.cpp

Resets the tracked last_branch_target_ in reader_t after we've created a memref using it. This is to avoid cases where the marker value is reused, which shouldn't ever happen. After this change, cases where there is a missing TRACE_MARKER_TYPE_BRANCH_TARGET before an indirect branch will clearly show a zero target instead of some non-zero value, which makes it easier to detect it as an error.

Reset last branch target after usage in the reader

---

api/docs/test_suite.dox

Updates the tmate docs on where to set extra test args as well as how to run the cdb debugger, which is not obvious as it is not on the PATH of the tmate shell.
Issue: #7499

i#7499 vs2022: Add cdb docs

---

api/docs/building.dox

Updates the Windows how-to-build docs to use VS2022 instead of VS2019.
I tested the Quick Start instructions on a Windows machine.
Issue: #7499

i#7499 vs2022: Update how-to-build docs

---

clients/drcachesim/tracer/instr_counter.cpp
clients/drcachesim/tracer/tracer.cpp
clients/drcachesim/tracer/tracer.h

https://github.com/DynamoRIO/dynamorio/pull/7509 introduced a race condition affecting tracing_window access.
This occurs when hit_instr_count_threshold() sends a self-nudge. Before event_nudge() can read tracing_window, a new window might open, incrementing its value. This leads to memory dump files being written to the incorrect (next) window's directory, or failing to write if that directory hasn't yet been created.
Manual test:
Ran "drrun -t drmemtrace -offline -trace_instr_intervals_file %{TRACE_FILE} -memdump_on_window" to capture multiple traces and memory dumps with and without the change. 
There were missing memory dump files without the change. And all memory dump files were captured with the change.
Fixes #7553

i#7533: Pass the tracing window number in self-nudge to create a memdump.

---

clients/drcachesim/docs/drcachesim.dox.in

Adds a reminder to the docs that when using the start/stop interface with static drmemtrace the -offline parameter needs to be passed via environment variable to produce trace files.  Prompted by users list confusion.

Document the need for -offline in static drmemtrace

---

api/docs/release.dox
clients/drcachesim/analyzer.cpp
clients/drcachesim/analyzer.h
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/common/options.cpp
clients/drcachesim/common/options.h
clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/tests/offline-all-early.templatex
suite/tests/CMakeLists.txt

Adds a new drmemtrace option -exit_after_records which applies to all tools and exits after N records.  However, it does not work with dr$sim's -warmup_fraction, and so we do not alias -sim_refs to this new option but keep -sim_refs separate and counted inside the simulators (and view tool: we could remove it there but without aliasing the old option it is simpler to leave it).
Updates the -sim_refs option docs to reflect #7549's exit and to refer to -exit_after_records for a similar option that works with all tools.
Adds get_output_record_ordinal() to the drmemtrace scheduler, required to get the record count *after* -skip_instrs.
Adds a test that verifies multiple tools all exit and that this starts counting after -skip_instrs.
Adds an entry to the release notes.
Issue: #7230

i#7230 simrefs: Add -exit_after_records drmemtrace option

---

clients/drcachesim/tests/offline-view-skip-instrs.templatex
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h
suite/tests/CMakeLists.txt

Ensures that the view_t sets the trace_version_ also when invoked with -skip_instrs. When -skip_instrs is specified, it causes the TRACE_MARKER_TYPE_VERSION trace entry to not be seen by the tool. In this case we need to initialize it from the stream API instead; this is same as what view_t already does for file type.
Without this fix, the view tool does not print the target pc for indirect branches like ret.
Adds a unit test that verifies that there's a ret instr with the target also shown, which fails without the fix.

Set trace version in view_t with -skip_instrs

---

suite/runsuite_wrapper.pl

client.attach-memory-dump-syscall-test test failed with missing "syscall" line in x86-64 run.
Mark this test as flaky until we have a fix for it.
Issue: #7552

i#7552: Mark client.attach-memory-dump-syscall-test test as flaky on x86-64.

---

core/os_shared.h
core/unix/loader.c
core/unix/os.c
suite/tests/client-interface/file_io.dll.c

Fixes the private loader's redirect of libc open() to a new function that properly handles the flags, instead of the old redirect which treated them as DR's custom flags.
Adds a test that hits the truncation described in the issue and so fails without the fix.
Also tested on the /dev/shm scenario described on the users list https://groups.google.com/g/dynamorio-users/c/kZHTGiIUn8Y/m/rSurDOWeAQAJ.
Fixes #7562

i#7562: Properly handle redirected libc open()

---

api/docs/release.dox
clients/drcachesim/common/options.cpp
clients/drcachesim/simulator/cache_simulator.cpp
clients/drcachesim/simulator/cache_simulator.h
clients/drcachesim/simulator/simulator.cpp
clients/drcachesim/simulator/simulator.h
clients/drcachesim/simulator/tlb_simulator.cpp
clients/drcachesim/tests/drcachesim_unit_tests.cpp

Changes the -skip_refs drmemtrace option to not count markers, matching the -sim_refs and -warmup_refs options.  (The new -skip_records counts markers.)
Adds a changelist entry.
Updates the docs for -skip_refs, -sim_refs, and -warmup_refs to clarify that they do not count markers.
Augments the drcachesim unit tests to check markers.
Cleans up the cache and tlb simulators to not short-circuit on a marker and skip later marker code, which requires a different solution for core_for_thread handling of early markers and setting the tid in tests.
A separate change will remove -skip_refs and -sim_refs from the view tool.
Issue: #7230

i#7230 simrefs: Change skip_refs to not count markers

---

core/lib/dr_tools.h
ext/drx/drx.h
ext/drx/drx_time_scale.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drx_sleep_scale-test.cpp
suite/tests/client-interface/drx_sleep_scale-test.templatex

Adds scaling of Linux SYS_nanosleep, SYS_clock_nanosleep, and SYS_clock_nanosleep_time64 system calls.
Augments the pre-existing timer scaling to check for syscall failure; checking the return code is required for sleep as the remaining time is only written when EINTR is returned.
Augments the pre-existing timer scaling to better handle an absolute flag by setting the TLS fields for post-handling prior to exiting pre-handling early, while putting this in place for sleep.
Adds a test.
Issue: #7504

i#7504 scale time: Scale sleep durations

---

api/docs/debug_memtrace.dox
api/docs/release.dox
clients/drcachesim/analyzer_multi.cpp
clients/drcachesim/tests/offline-one-early.templatex
clients/drcachesim/tests/offline-skip.expect
clients/drcachesim/tests/skip_unit_tests.cpp
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/invariant_checker.cpp
clients/drcachesim/tools/invariant_checker.h
clients/drcachesim/tools/view.cpp
clients/drcachesim/tools/view.h
clients/drcachesim/tools/view_create.h
suite/tests/CMakeLists.txt

Removes support for -skip_refs and -sim_refs from the view tool. These now count only non-markers and are limited to the simulator tools. They have been replaced by analyzer-provided -skip_records and -exit_after_records.
Adds an error message if a user tries to use the old options.
Removes the delay for printing version and filetype records. It is from a very old file reader which did not re-order records; the modern file reader re-orders so the reader_t always sees the tid before the first visible record.  This avoids having to port the old sim_refs logic for the delayed headers.
Augments invariant_checker with a flag "trace_incomplete" which relaxes the invariant that a thread exit is seen and also adds handling of skip_records via a heuristic.
Adjusts the drcacheoff.skip test to …

i#7230 sim refs: Remove -skip_refs and -sim_refs from view tool

---

clients/drcachesim/tests/scheduler_unit_tests.cpp

Adds a new scheduler unit test that demonstrates how an abandoned TRACE_MARKER_TYPE_BRANCH_TARGET is treated by the drmemtrace scheduler logic.
When there's an abandoned branch_target marker in the previous chunk, and other unrelated markers intervening before the corresponding encoding+instr in the next chunk, it affects the scheduler in unexpected ways: the instr ordinals are erroneously incremented for just the branch_target and then again at the encoding+instr, and there may be a context switch that splits up the branch_target marker and its corresponding instruction.
The plan is to ensure branch_target markers are not abandoned in raw2trace, and to also add a scheduler workaround to properly handle older traces that do have this problem.
Issue: #7574

i#7574 abandoned br tar: Show scheduling behavior

---

clients/drcachesim/tests/raw2trace_unit_tests.cpp
clients/drcachesim/tracer/raw2trace.cpp

Fixes an issue in raw2trace's handling of chunks that caused the TRACE_MARKER_TYPE_BRANCH_TARGET for certain indirect branches to be left behind in the prior chunk.
This happened when all of the following conditions were true:
- the indirect branch was the first instruction of a new chunk
- the indirect branch was a part of a sequence of delayed branches that crossed over chunk boundary
- the indirect branch had a prior instance in the previous chunk so that an encoding entry was not initially added before it (but would be added by raw2trace upon opening the new chunk)
Adds a unit test that reproduces the issue, which fails without this fix.
Issue: #7574

i#7574 abandoned br tar: Fix issue in raw2trace

---

ext/drsyscall/drsyscall.c

Applies a fix needed for running the drmemory drsyscall tests on Ubuntu22 from DynamoRIO/drmemory#2561. We have to duplicate every change in both places because drsyscall is currently duplicated in drmemory and dynamorio: #7303 covers removing it from drmemory.
Issue: #7303, DynamoRIO/drmemory#2548

Apply drsyscall Ubuntu22 fix from drmemory

---

ext/drx/drx_time_scale.c

Fixes an error in drx_unregister_time_scaling() where it re-registers instead of un-registering its syscall events.  The bug would not affect those only unregistering at exit or detach time but could affect other uses.
Issue: #7504

i#7504 time scale: Fix unregister bug

---

ext/drx/drx.h
ext/drx/drx_time_scale.c
suite/tests/client-interface/drx_sleep_scale-test.cpp
suite/tests/client-interface/drx_sleep_scale-test.templatex
suite/tests/client-interface/drx_time_scale-test.c
suite/tests/client-interface/drx_time_scale-test.templatex

Records and provides statistics on the counts of scaling attempts, failures, and nops for each class of operations that are scaled.
Adds testing of the new interface.
Issue: #7504

i#7504 time scale: Add stats on drx scaling

---

core/unix/os.c
ext/drx/drx.h
ext/drx/drx_time_scale.c
suite/tests/CMakeLists.txt
suite/tests/client-interface/drx_time_scale-test.c
suite/tests/client-interface/drx_timeout_scale-test.cpp
suite/tests/client-interface/drx_timeout_scale-test.templatex

Adds scaling of futex timeouts to the drx time scaling feature. Adds handling of both relative and absolute (both clock types) varieties.
Adds a new test drx_timeout_scale-test which exercises each type of timeout (and will be used for other system call timeouts as well, hence the name).
Fixes a bug in dr_invoke_syscall_as_app() where the result reg was clobbered by a new argument on AArch64 (or RISCV), causing the FUTEX_WAIT_BITSET in the new test here to fail with EFAULT.
Issue: #7504

i#7504 scale time: Scale futex timeouts

---

api/docs/release.dox
api/samples/strace.c
api/samples/syscall.c
clients/drcachesim/tracer/tracer.cpp
ext/drcovlib/drcovlib.c
ext/drmf/framework/samples/strace.c
ext/drmgr/drmgr.c
ext/drmgr/drmgr.h
ext/drsyscall/drsyscall.c
ext/drwrap/drwrap.c
ext/drx/drx.c
ext/drx/drx_time_scale.c
suite/tests/client-interface/attach-memory-dump-syscall-test.dll.c
suite/tests/client-interface/drmgr-test.dll.c
suite/tests/client-interface/drpttracer_SUDO-test.dll.c
suite/tests/client-interface/drsyscall-test.dll.c
suite/tests/client-interface/nudge_ex.dll.c
suite/tests/client-interface/strace-test.dll.c
suite/tests/client-interface/strace.dll.c
suite/tests/client-interface/syscall-file-io-test.dll.c
suite/tests/client-interface/syscall-records-test.dll.c

Adds a drmgr filter syscall event which replaces the base DR event and provides priorities and user_data parameters.
Removes the lazy drmgr pre and post syscall registration as it is no longer needed with drmgmr always registering a filter event, but leaves the underlying lazy mechanism in place in case we want it for something else.
Updates all our samples and tests to use the drmgr event.
Adds a note to the minor compatibility change list as this will break user's builds, but has no binary compatibility consequence.
Issue: #7604

i#7604 user data: Add drmgr syscall filter event

---

ext/drmgr/drmgr.c
ext/drmgr/drmgr.h
suite/tests/client-interface/drmgr-test.dll.c
suite/tests/client-interface/drmgr-test.templatex

Adds unregistration for the filter event with user data, which was omitted from PR #7605.
Adds testing to drmgr-test.
Issue: #7604

i#7604 user data: Add unreg for filter user data

---

ext/drsyscall/CMakeLists.txt
suite/tests/CMakeLists.txt

#7396 had a typo in drcontainters_drstatic, missing drsyms_drstatic, and used the wrong library for drmgr_drstatic.
I found the issue when I tried to add drsyscall library to add_drmemtrace as follows:
```
diff --git a/clients/drcachesim/CMakeLists.txt b/clients/drcachesim/CMakeLists.txt
index c9ef34368..3e47f8322 100644
--- a/clients/drcachesim/CMakeLists.txt
+++ b/clients/drcachesim/CMakeLists.txt
@@ -560,6 +560,7 @@ macro(add_drmemtrace name type static_DR no_main)
use_DynamoRIO_extension(${name} droption)
use_DynamoRIO_extension(${name} drcovlib${ext_sfx})
use_DynamoRIO_extension(${name} drbbdup${ext_sfx})
+  use_DynamoRIO_extension(${name} drsyscall${ext_sfx})
if (BUILD_PT_TRACER)
use_DynamoRIO_extension(${name} drpttracer${ext_sfx})
endif ()
```
Add a test to build with …

i#7303 drsyscall: fix drsyscall_drstatic library.

---

suite/tests/api/detach_state.c
suite/tests/api/detach_state_shared.h

Adds support for checking the AArch64 vector registers in the api.detach_state test. When built with SVE support it will check all Z and P registers and the FFR. When built without SVE support it will check all the Neon V registers.
The SVE support is intended to work with any vector length and has been tested with 128-bit and 256-bit vector lengths.
Issue: #7576, #4698

i#7576 detach: Check AArch64 SIMD registers in detach_state test

---

CMakeLists.txt

Some of my local git settings (at least one that shows GPG signatures) change the log format in a way that's breaking the parsing at cmake-time.  This sets GIT_CONFIG_GLOBAL, which causes the user's git configuration to be ignored and should avoid these sorts of issues.
Issue: #7617

i#7617: Force an empty git config, to avoid log format changes (#7617)

---

api/docs/API.doxy
api/docs/release.dox
clients/drcachesim/CMakeLists.txt
clients/drcachesim/reader/compressed_file_reader.cpp
clients/drcachesim/reader/file_reader.cpp
clients/drcachesim/reader/file_reader.h
clients/drcachesim/reader/ipc_reader.cpp
clients/drcachesim/reader/lz4_file_reader.cpp
clients/drcachesim/reader/reader.cpp
clients/drcachesim/reader/reader.h
clients/drcachesim/reader/reader_base.cpp
clients/drcachesim/reader/reader_base.h
clients/drcachesim/reader/record_file_reader.cpp
clients/drcachesim/reader/record_file_reader.h
clients/drcachesim/reader/snappy_file_reader.cpp
clients/drcachesim/reader/zipfile_file_reader.cpp
clients/drcachesim/tests/mock_reader.h
clients/drcachesim/tests/view_test.cpp
clients/drcachesim/tools/common/decode_cache.h

Adds a new base class for reader_t and record_reader_t, called reader_base_t, which holds some interface definitions and implementation common to the two kinds of readers.
Adds get_next_entry() which is intended to be used by derived classes to get the next entry, which is different from read_next_entry() which actually reads the next entry from the underlying trace source and is now made private. get_next_entry() may or may not invoke read_next_entry() depending on whether there are queued entries already available.
Removes read_queued_entry() from all derived class implementations, as that is now simply handled by the reader_base_t::get_next_entry() itself.
Renamed eof_ to at_eof_ in record_reader_t and its derived classes, as that is now declared in reader_base_t, shared with reader_t. …

i#7496 eret continuity: Add reader_base_t

---

clients/drcachesim/reader/file_reader.h

Replaces uses of read_next_entry() with get_next_entry() in file_reader_t.
Since these usages were in open_single_file() before anything was really queued, it didn't matter that get_next_entry() (which also checks the queue) wasn't used.
Under this non-virtual interface pattern, since file_reader_t itself has provided the implementation of read_next_entry(), we cannot stop it from using it, but the recommendation is to use get_next_entry().
Preserves private visibility for file_reader_t<T>::read_next_entry(), just because there's no reason to change it to protected.
Issue: #7496

i#7496 eret continuity: Use get_next_entry in file_reader_t

---

clients/drcachesim/scheduler/scheduler.h
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
suite/tests/CMakeLists.txt

Fixes a drmemtrace bug where the input count included threads excluded with -only_thread while the input_ array did not, leading to an array overflow.
Adds reader_info_t.unfiltered_input_count to fix a problem with the only_shards validity check.
Documents that input_thread_info_t.shards modifiers apply after only_* have filtered out inputs.
Adds a check on an invalid modifier index.
Avoids an empty binder set copy.
Adds "-skip_instrs 10" to the only_thread test, which reproduces the crash (now an invalid input error) without the fix and passes with the fix. The only_shards test exercises the unfiltered_input_count change as it fails without that change.
Fixes #7626

i#7626: Fix drmemtrace input count with only_thread

---

ext/drsyscall/CMakeLists.txt
ext/drsyscall/drsyscall_record_lib.c
ext/drsyscall/drsyscall_record_lib.h
suite/tests/client-interface/attach-memory-dump-syscall-test.dll.c
suite/tests/client-interface/syscall-records-test.dll.c

Add new functions to write pre-syscall and post-syscall records to drsyscall_record_lib.
drsyscall_write_pre_syscall_records() writes DRSYS_SYSCALL_NUMBER_TIMESTAMP, DRSYS_PRECALL_PARAM, and DRSYS_MEMORY_CONTENT records using the caller provided write function.
drsyscall_write_post_syscall_records() writes DRSYS_POSTCALL_PARAM, DRSYS_MEMORY_CONTENT,
DRSYS_RETURN_VALUE, and DRSYS_RECORD_END_TIMESTAMP records.
The caller must invoke drmgr_init() and drsys_init() before calling these functions.
Change attach-memory-dump-syscall-test.dll.c and syscall-records-test.dll.c  to use these functions.
Update ext/drsyscall/CMakeLists.txt to change drsyscall_record_lib into a shared library, and add drsyscall_record_lib_static and drsyscall_record_lib_drstatic libraries.
Fix a bug in …

i#7588 drsyscall: Add functions to write pre and post syscall records.

---

core/unix/loader.c

Various tests, including drbbdup-test, were failing with some toolchain versions.
The names without the __ prefix (memcpy_chk etc.) were already being redirected.
Fixes #7630

i#7630: Redirect __memcpy_chk etc. in private loader

---

clients/drcachesim/tests/burst_gencode.cpp
clients/drcachesim/tests/burst_syscall_inject.cpp

Removes the workarounds and comments about #6490 in two tests as it is now fixed.
Issue: #6490

i#6490 avx512 state: Remove workarounds since fixed

---

clients/drcachesim/tests/invariant_checker_test.cpp
clients/drcachesim/tools/invariant_checker.cpp

Enables PC continuity checks in the invariant_checker that verify control flow continuity of the branch_target marker value to the post-syscall trace pc.
Until #7639, the syscall-trace-end branch_target marker always held the syscall-fallthrough pc, but now it holds the pc of the actual next instr in the thread. This solves two previously-unhandled cases: auto-restart syscalls that resume control at the syscall pc itself, and control-transferring syscalls like sigreturn that resume control at some arbitrary pc.
Also manually ran the invariant checker on two large internal app traces (x86 and aarch64), and confirmed that no unexpected invariant errors were reported.
Issue: #7496

i#7496 eret continuity: Enable PC cont invariant checks

---

api/docs/release.dox
clients/drcachesim/tracer/tracer.cpp
ext/drmgr/drmgr.c
ext/drmgr/drmgr.h
suite/tests/client-interface/drx_timeout_scale-test.cpp

Adds drmgr mediation of the pre-detach event to provide a user-data version and priorities.
Adds testing in an existing test that uses drmgr and detach.
Updates the changelist compatibility section as this requires clients to switch from the base DR event.
Issue: #7598, #7604

i#7598 attach gap: Add drmgr pre-detach event

---

clients/drcachesim/scheduler/scheduler_impl.h

Initializes scheduler_impl_tmpl_t::cur_from_queue to false. This was detected by ASAN.
The bool was uninitialized before the recent i#7496 changes as well, but it was detected by ASAN when a use was introduced in the memtrace_stream_t API implementation by the scheduler.
Issue: #7496

i#7496 eret continuity: Fix uninit bool in scheduler

---

ext/drx/drx.h
ext/drx/drx_time_scale.c
suite/tests/client-interface/drx_timeout_scale-test.cpp
suite/tests/client-interface/drx_timeout_scale-test.templatex

Adds checks when scaling timeouts to prevent overflow.
Adds a new stat count_time_too_large to count such cases.
Adds test cases that fail without the new checks.
Further tested on an internal case where an app failed without this fix.
Issue: #7504

i#7504 scale time: Avoid scaling overflows

---

clients/drcachesim/analyzer.cpp
clients/drcachesim/common/trace_entry.h
clients/drcachesim/common/utils.h
clients/drcachesim/docs/drcachesim.dox.in
clients/drcachesim/scheduler/scheduler_impl.cpp
clients/drcachesim/scheduler/scheduler_impl.h
clients/drcachesim/tests/schedule_stats_test.cpp
clients/drcachesim/tools/basic_counts.cpp
clients/drcachesim/tools/schedule_stats.cpp

Changes analyzer_t::create_idle_marker() to use IDLE_THREAD_ID when creating marker records of type TRACE_MARKER_TYPE_CORE_IDLE. IDLE_THREAD_ID is the proper sentinel to be used for such records.
Extends an existing unit test to verify that transitions from start-idle to an input are counted as a switch.
Modifies test setup to also use the correct IDLE_THREAD_ID sentinel for core_idle markers.
Documents that record_type_has_tid considers IDLE_THREAD_ID as a valid thread id; it needs to because when opening a new core-sharded-on-disk file for a core that started idle, we cannot keep reading ahead until we find an actual tid.
Issue: #6685

i#6685: Use IDLE_THREAD_ID for core_idle markers

---

suite/tests/api/detach_state.c
suite/tests/api/detach_state_shared.h

Ports the two detach_state eflags tests to AArch64 and extends them to test the AArch64 floating point status and control registers as well. I have renamed the tests from check_eflags* to check_status_reg* to reflect the widened scope.
Issues: #7576, #4698

i#7576 detach: Port detach_state flags tests to AArch64 and extend

---

core/arch/aarch64/aarch64.asm
core/arch/aarch64/asm_offsetsx.h
core/arch/aarch64/mangle_aarch64.h
core/arch/aarchxx/mangle.c
core/ir/aarch64/instr.c

Instead of accumulating IC IVAU addresses in a global struct and only acting on them when an ISB is seen, act on each IC IVAU immediately and in the same thread. This may be slower in some cases as there may be multiple calls to flush_fragments_synch_unlink_priv instead of a single call but it avoids an inter-thread issue.
Fixes #7643

i#7643: Simplify icache sync on AArch64: act on IC IVAU immediately.

---

core/options.c

The existing check was ARM-only, though it was probably intended to be used on AArch64 too. Also, use the MIN/MAX macros instead of just referring to them in a comment.
Fixes #7540

i#7540: Check value of steal_reg on AArch64 as on ARM.
